### ISSUE TITLE
[BUG] LUIS SDK: Unable to read data from the transport connection : An existing connection was forcibly closed by the remote host

### ISSUE THREAD

**Issue by hazemelh** [Azure/azure-sdk-for-net#10008]
**Describe the bug**
When using the latest LUIS SDK 3.2.0-preview.1, when doing certain functions, specifically long running ones such as ImportWithHttpMessagesAsync, it may take a while but the SDK times out internally and throws **Unable to read data from the transport connection : An existing connection was forcibly closed by the remote host**, even though if you were to use the API directly it would not have the same timeout. 

**Expected behavior**
What is the expected behavior?

- For the SDK to keep the connection open for as along as the request takes.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

SDK Exception thrown:
System.Threading.Tasks.TaskCanceledException
  HResult=0x8013153B
  Message=The operation was canceled.
  Source=Microsoft.Rest.ClientRuntime
  StackTrace:
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at System.Net.Http.HttpClient.<FinishSendAsyncBuffered>d__62.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.Apps.<ImportWithHttpMessagesAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.AppsExtensions.<ImportAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at BenchmarkTests.ScenarioTests.PrebuiltDomainsTest.<TestDomain>d__13.MoveNext() in C:\W\luis\prebuilts-repo\Benchmark\BenchmarkTests\ScenarioTests\PrebuiltDomainsTest.cs:line 220

 

Inner Exception 1:
IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request.

 

Inner Exception 2:
SocketException: The I/O operation has been aborted because of either a thread exit or an application request
 

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Use the ImportWithHttpMessagesAsync method with the attached application json file at the bottom (change .txt to .json first).

**Environment:**
 - Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring" Version="3.2.0-preview.1"
[Communication_hi-in_official.txt](https://github.com/Azure/azure-sdk-for-net/files/4213671/Communication_hi-in_official.txt)

**Comment by pakrym** [comment]
How long does the response usually take? Default HttpClient timeout is 100seconds so if the request takes longer than that `Threading.Tasks.TaskCanceledException` would be thrown.

**Comment by lorenz-haenggi-axa** [comment]
hi - we have the same issue with ImportAsync because the .lu file to upload is > 1MB. This is because we are new auto-generate additional utterance and our file got bigger.

question: 
- is it a standard cancel after 100s ?
- is it possible to send the POST Request zipped? (lu / json file would be greatly gzipped)
- is it possible to use another settings in the LuisAuthoringClient constructor and add things to it?

tody we are using:
`public LUISAuthoringClient(ServiceClientCredentials credentials, params DelegatingHandler[] handlers);
`
possibly to use and adapt: HttpClientHandler 

`public LUISAuthoringClient(ServiceClientCredentials credentials, HttpClientHandler rootHandler, params DelegatingHandler[] handlers);
`

**Comment by lorenz-haenggi-axa** [comment]
we have now solved it while using LUISAuthoringClient with a configured HttpClient. The default of 100s is working fine but for some it is good to adapt.

```
var httpClient = new HttpClient();
httpClient.Timeout = TimeSpan.FromSeconds(timeoutInSeconds);
httpClient.DefaultRequestHeaders.Add("Ocp-Apim-Subscription-Key", "< your token>");

LUISAuthoringClient(credentials, httpClient, false)
```

**Comment by imranveliyev** [comment]
Hi. **var key = await functionApp.GetMasterKeyAsync()** trying to get maskter key. it works intermittently.
What can be the problem?
![bug](https://user-images.githubusercontent.com/46125297/89175622-c5dfb200-d590-11ea-8a01-f358202fb1c0.PNG)
