### ISSUE TITLE
[Storage] BlobBaseClient.DownloadAsync() throws XmlException if server response has no body

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#10294]
If the server response has no body, `BlobBaseClient.DownloadAsync()` tries to parse the emtpy stream as XML throws the following exception.  Instead, I think the client should check for empty body and throw a better exception.

```
Unhandled exception. System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Azure.Storage.Blobs.BlobRestClient.Blob.DownloadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.DownloadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String snapshot, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentHash, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadInternal(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadAsync(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadAsync(CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadAsync()
```

To repro, first start an HTTP server which sends an error response (say 404 to prevent retries) but no body:

```C#
new WebHostBuilder()
    .UseKestrel(options =>
    {
        options.Listen(IPAddress.Any, 5000);
    })
    .Configure(app => app.Run(context =>
    {
        Console.WriteLine("Received request");
        context.Response.StatusCode = 404;
        return Task.CompletedTask;
    }))
    .Build()
    .Run();
```

Then call a storage API like `DownloadAsync()` against this server:

```C#
BlobClient client = new BlobClient(new Uri("http://localhost:5000"));
Console.WriteLine("Calling DownloadAsync()...");
await client.DownloadAsync();
Console.WriteLine("Done");
```

**Comment by kasobol-msft** [comment]
That should be fixed in .NET generator.

**Comment by tg-msft** [comment]
Why should we do this?  What better exception should we throw when somebody mangles the response and doesn't meet the API contract?  What should we do if somebody MITMs a successful response and returns garbage XML?

**Comment by mikeharder** [comment]
@tg-msft, @kasobol-msft: If I recall correctly, I saw this exception in our live tests, because network issues can occasionally cause the client to receive headers but no body.  The repro steps above are an artificial way to simulate this occasional real-world scenario.

As a customer, if I got an `XmlException` when calling `BlobClient.DownloadAsync()` I would be fairly confused.  I'm not trying to do anything with XML, just Storage.  XML is an implementation detail that should be hidden from callers.

Maybe Storage should catch the `XmlException` and throw a different exception?

**Comment by mikeharder** [comment]
@tg-msft: I think the key point here is network issues alone can cause the client to see a mangled response.  It's not limited to the server failing to meet the API contract or a MITM attack.

**Comment by tg-msft** [comment]
What would you throw instead?  +@pakrym and @KrzysztofCwalina.  I can't think of something I'd prefer to throw over XmlException or JsonException if we receive a malformed body.

**Comment by pakrym** [comment]
>I think the key point here is network issues alone can cause the client to see a mangled response.

I don't think the HttpClient should allow successful reading of the body if the connection failed. If it does it's a bug.

**Comment by tg-msft** [comment]
Closing as we're not planning to do anything.  Please start a discussion if that's not satisfactory.
