### ISSUE TITLE
[BUG] DefaultAzureCredential throws exception in Azure Key Vault (File Not Found)

### ISSUE THREAD

**Issue by jublair** [Azure/azure-sdk-for-net#10306]
**Describe the bug**
`DefaultAzureCredential` appears to be throwing exceptions when invoking an Azure Key Vault method (in this case, getting a secret from AKV).

**Expected behavior**
Getting secret from AKV should not throw an exception if the key is available.

**Actual behavior (include Exception or Stack Trace)**
Exceptions:
```
AuthenticationFailedException: ClientSecretCredential authentication failed.
FileNotFoundException: Could not load file or assembly 'System.Memory, Version=4.2.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.
FileNotFoundException: Could not load the specified file.
This exception was originally thrown at this call stack:
	System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(System.Reflection.AssemblyName)
	System.Runtime.Loader.AssemblyLoadContext.ResolveUsingResolvingEvent(System.IntPtr, System.Reflection.AssemblyName)
```

Stack trace:
```
   at Azure.Identity.DefaultAzureCredential.<GetTokenAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.<AuthenticateRequestAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.<ProcessCoreAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecret(String name, String version, CancellationToken cancellationToken)
   at FraudHunters.Library.FHKeyVaultClient.<>c__DisplayClass4_0.<GetSecretAsync>b__0() in D:\Repos\FIST Tooling - Fraud Hunters\FraudHuntersLibrary\Clients\FHKeyVaultClient.cs:line 56
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
```

**To Reproduce**
```csharp
public FHKeyVaultClient()
{
    this.keyVaultClient = new SecretClient(new Uri(KeyVaultRoot), new DefaultAzureCredential());
}

KeyVaultSecret secret = this.keyVaultClient.GetSecret(key);
```

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Secrets v4.0.2
 - Hosting platform or OS and .NET runtime version: .NET Core 3.1; Windows 10 local and Azure
 - IDE and version : VS 16.4.5

**Comment by jsquire** [comment]
//cc: @heaths

**Comment by heaths** [comment]
It's listed as a package dependency: https://www.nuget.org/packages/Azure.Identity/

Did you do a `dotnet restore` (default when building). How did you deploy your application?

**Comment by jublair** [comment]
Seems like it's an issue with our project settings - not sure what it is, but after further discussions with @heaths it seems to be out of schope of the Azure SDKs. Will close this issue for now and re-open if I have any new information. Thanks!
