### ISSUE TITLE
[BUG] ResourceManager.ResourcesOperationsExtensions breaking changes in 3.4.0

### ISSUE THREAD

**Issue by wahyuen** [Azure/azure-sdk-for-net#10518]
**Describe the bug**
Please provide the description of issue you're seeing.
The latest 3.4.0 public package of `Microsoft.Azure.Management.ResourceManager` appears to contains breaking public API changes from 3.3.0.

Referencing from `Microsoft.Azure.AppConfiguration` now throws a Method Not Found exception as the API now expects to return a `GenericResourceExpanded` as opposed to `GenericResource`

**Expected behavior**
What is the expected behavior?
Existing libraries to still continue to work as this appears to have been a minor release.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Exception is thrown

```
Method not found: 'System.Threading.Tasks.Task`1<Microsoft.Rest.Azure.IPage`1<Microsoft.Azure.Management.ResourceManager.Models.GenericResource>> Microsoft.Azure.Management.ResourceManager.ResourcesOperationsExtensions.ListAsync(Microsoft.Azure.Management.ResourceManager.IResourcesOperations, Microsoft.Rest.Azure.OData.ODataQuery`1<Microsoft.Azure.Management.ResourceManager.Models.GenericResourceFilter>, System.Threading.CancellationToken)'.
```

```
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.<GetConfigurationStore>d__6.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.GetConfigurationStore(Uri endpoint, SubscriptionClient subscriptionClient, ResourceManagementClient resourceManager, CancellationToken cancellationToken)
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.<GetConnectionString>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.AppConfiguration.ManagedIdentityConnector.ManagedIdentityConnector.<GetConnectionString>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationOptions.ConnectWithManagedIdentity(String endpoint)
   at Common.Startup.LocalHostOptimizedStartup.<>c__DisplayClass2_0.<AddAppConfiguration>b__0(AzureAppConfigurationOptions options) in C:\Workspace\soze\Common\Startup\LocalHostOptimizedStartup.cs:line 147
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.<>c__DisplayClass2_0.<.ctor>b__0()
   at Microsoft.Extensions.Configuration.AzureAppConfiguration.AzureAppConfigurationSource.Build(IConfigurationBuilder builder)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Common.Startup.LocalHostOptimizedStartup.ConnectWebApiToAppConfigurationAndKeyVault(HostBuilderContext context, IConfigurationBuilder config) in C:\Workspace\soze\Common\Startup\LocalHostOptimizedStartup.cs:line 24
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Api.Program.Main(String[] args) in C:\Workspace\soze\Api\Program.cs:line 11
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Attempt to connect to AzureAppConfiguration

```
                config.AddAzureAppConfiguration(options =>
                {
                    options.ConnectWithManagedIdentity(appConfigurationEndpoint);
                    options.UseFeatureFlags();
                });
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0]  `Microsoft.Azure.Management.ResourceManager 3.4.0-preview`
`Microsoft.Azure.AppConfiguration.AspNetCore 2.1.0-preview-010380003-1338`
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8] Azure App Service Dotnet Core 3.1.101
 - IDE and version : [e.g. Visual Studio 16.3] Visual Studio 16.4.4

**Workaround**
Downgrade reference to Microsoft.Azure.Management.ResourceManager 3.3.0-preview

**Comment by jsquire** [comment]
@erich-wang: Would you be so kind as to help route this?

**Comment by isra-fel** [comment]
This issue was introduced by #9804 . We should have used autorest v2 to generate SDK but we used the latest v3, which generated something different.
cc @ramoka178 @hamidtirmizi I have updated all modules' `generate.ps1` to force autorest v2; how about we generate it again to roll back the change?
Thanks

**Comment by isra-fel** [comment]
Kindly ping @ramoka178 @hamidtirmizi 😀

**Comment by ramoka178** [comment]
@isra-fel 
I've added a workitem to track this on our board at 
https://msazure.visualstudio.com/One/_sprints/backlog/Azure-ARM-Organizing-Resources/One/Azure-ARM/Manganese/Apr-2020?workitem=7085964

**Comment by ramoka178** [comment]
Fixes are published by using autorest v2 now. 
New SDK at https://www.nuget.org/packages/Microsoft.Azure.Management.ResourceManager/3.7.2-preview

**Comment by isra-fel** [comment]
Closing as fixed. Thank you @ramoka178 😁
