### ISSUE TITLE
[BUG] DataLakeFileSystemClient.DeleteIfExistsAsync() throws if container does not exist

### ISSUE THREAD

**Issue by YevgenBorodkin** [Azure/azure-sdk-for-net#10746]
**Describe the bug**
DataLakeFileSystemClient.DeleteIfExistsAsync() throws exception when it tries to delete previously deleted container.

**Expected behavior**
Should return "false"

**Actual behavior (include Exception or Stack Trace)**
throws Azure.RequestFailedException exception with Status=404 "{The specified blob does not exist.}"

**To Reproduce**
                // Act: Delete container
                bool firstDeletion = (await dataLakeFileSystemClient.DeleteIfExistsAsync()).Value;
                Assert.IsTrue(firstDeletion);
throws-> bool secondDeletion = (await dataLakeFileSystemClient.DeleteIfExistsAsync()).Value;
                Assert.IsFalse(secondDeletion);

Stack:
Test method Microsoft.Exchange.Mars.AdlsGen2.Test.AdlsGen2ContainerTests.TestDeleteContainerIfExistsSdkIssueRepro threw exception: 
Azure.RequestFailedException: The specified blob does not exist.
RequestId:32b3a687-301e-0065-1be4-febb57000000
Time:2020-03-20T18:21:04.9437238Z
Status: 404 (The specified blob does not exist.)
ErrorCode: BlobNotFound

Headers:
x-ms-request-id: 32b3a687-301e-0065-1be4-febb57000000
x-ms-client-request-id: 72c904e2-bdcb-41b1-ba76-3a84c82dd3e6
x-ms-version: 2019-07-07
x-ms-error-code: BlobNotFound
Date: Fri, 20 Mar 2020 18:21:04 GMT
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
Content-Length: 215
Content-Type: application/xml

    at Azure.Storage.Blobs.BlobRestClient.Container.DeleteAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Container.<DeleteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.<DeleteInternal>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.<DeleteIfExistsInternal>d__52.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.<DeleteIfExistsAsync>d__51.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Files.DataLake.DataLakeFileSystemClient.<DeleteIfExistsAsync>d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Exchange.Mars.AdlsGen2.Test.AdlsGen2ContainerTests.<TestDeleteContainerIfExistsSdkIssueRepro>d__8.MoveNext() in C:\marscode\sources\test\mars\src\AdlsGen2.UnitTests\AdlsGen2ContainerTests.cs:line 282
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()

**Environment:**
 - Azure.Storage.Files.DataLake, Version=12.0.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8
 - TargetFramework 4.6.2, Windows 10 Enterprise Build 18363.720
 - IDE and version : 
        Microsoft Visual Studio Enterprise 2017 
        Version 15.9.21
        VisualStudio.15.Release/15.9.21+28307.1064
        Microsoft .NET Framework
        Version 4.8.03752

**Comment by seanmcc-msft** [comment]
The fix will be out with our next release, which will probably be the first week in April.
