### ISSUE TITLE
Downloading empty blob throws exception with error code "InvalidRange"

### ISSUE THREAD

**Issue by stevekirks** [Azure/azure-sdk-for-net#10827]
**Describe the bug**
Using Azure.Storage.Blobs v12.4.0, when downloading an empty blob an exception with error code "InvalidRange" is thrown.

**Expected behavior**
Download the empty contents of the blob without throwing an exception.

**Actual behavior (include Exception or Stack Trace)**
```
Azure.RequestFailedException: The range specified is invalid for the current size of the resource.
RequestId:efd8a54c-901e-0063-1327-02bb48000000
Time:2020-03-24T22:01:57.2523154Z
Status: 416 (The range specified is invalid for the current size of the resource.)
ErrorCode: InvalidRange

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: efd8a54c-901e-0063-1327-02bb48000000
x-ms-client-request-id: d824f60a-c7be-4f90-911f-3ae6019be11b
x-ms-version: 2019-07-07
x-ms-error-code: InvalidRange
Date: Tue, 24 Mar 2020 22:01:56 GMT
Content-Length: 249
Content-Type: application/xml
Content-Range: bytes */0

   at Azure.Storage.Blobs.BlobRestClient.Blob.DownloadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.DownloadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String snapshot, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentHash, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadInternal(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download(CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download()
```

**To Reproduce**
```csharp
var blobContainerClient = new BlobContainerClient(
                BlobConnectionString,
                "test");

var blobClient = blobContainerClient.GetBlobClient("test.txt");
var byteArray = Encoding.UTF8.GetBytes("");
using (var stream = new MemoryStream(byteArray))
{
	blobClient.Upload(stream, overwrite: true);
}

blobClient = blobContainerClient.GetBlobClient("test.txt");
try
{

	var blobDownload = blobClient.Download(); // throws exception "The range specified is invalid for the current size of the resource."
	using (var reader = new StreamReader(blobDownload.Value.Content))
	{
		var contents = reader.ReadToEnd();
		Console.WriteLine("Contents: " + contents);
	}
}
catch (Azure.RequestFailedException e)
{
	Console.WriteLine(e);
}
```

**Environment:**
 - Azure.Storage.Blobs 12.4.0
 - Windows 10
 - dotnet core 3.1.101

**Comment by amishra-dev** [comment]
Thanks for reporting this @stevekirks, @seanmcc-msft has pushed a PR that addresses this issue. Feel free to pull that branch and see if it fixes your issue.
