### ISSUE TITLE
[Flaky test] CreatePartitionProcessorReadsEmptyLastEventPropertiesWithNoOption

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#10869]
```
Azure.Messaging.EventHubs.EventHubsException : The Event Hub client responsible for this information is not available. has already been closed and cannot perform the requested operation. (The Event Hub client responsible for this information is not available.)


Stack trace
   at Azure.Core.Argument.AssertNotClosed(Boolean wasClosed, String targetName) in /Users/runner/runners/2.165.2/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/Argument.cs:line 135
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c__DisplayClass58_0.<CreatePartitionProcessor>g__readLastEnquedEventInformation|0() in /Users/runner/runners/2.165.2/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor{TPartition}.cs:line 489
   at Azure.Messaging.EventHubs.Tests.EventProcessorTests.CreatePartitionProcessorReadsEmptyLastEventPropertiesWithNoOption() in /Users/runner/runners/2.165.2/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Primitives/EventProcessorTests.PartitionProcessing.cs:line 208
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=332826&view=ms.vss-test-web.build-test-results-tab&runId=9854868&resultId=102989&paneView=debug

cc @jsquire

**Comment by jsquire** [comment]
Fixed by #10870.    _(investigation and adjustment to be done as part of current implementation workstream)_
