### ISSUE TITLE
[BUG] AzureConfigurationBuilder fails to build connection strings when deployed to App Service

### ISSUE THREAD

**Issue by yukfang** [Azure/azure-sdk-for-net#11371]
**Describe the bug**
in https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/identity/Azure.Identity/src/ManagedIdentityClient.cs

private AccessToken Deserialize(JsonElement json) throws exceptions if the Application culture is not "en-US".

            if (_msiType == MsiType.AppService)
            {
                if (!DateTimeOffset.TryParse(expiresOnProp.Value.GetString(), out expiresOn))
                {
                    throw new AuthenticationFailedException(AuthenticationResponseInvalidFormatError);
                }
            }

**Expected behavior**
1. Currently the SDK calls App Service MSI API version 2017-09-01, and the expires_on property is returned in TimeStamp format, en-US style; m/d/yyyy; so DateTimeOffset.TryParse should use its overrides to pass the style ;
2. A new MSI API is released, and the expires_on property is UNIX time in seconds, so we can consider to upgrade to know API. Document here: https://docs.microsoft.com/en-us/azure/app-service/overview-managed-identity?tabs=powershell#obtain-tokens-for-azure-resources

**Actual behavior (include Exception or Stack Trace)**
 [AuthenticationFailedException]: Invalid response, the authentication response was not in the expected format.
   at Azure.Identity.ManagedIdentityClient.Deserialize(JsonElement json)
   at Azure.Identity.ManagedIdentityClient.Deserialize(Stream content)
   at Azure.Identity.ManagedIdentityClient.Authenticate(String[] scopes, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImpl(TokenRequestContext requestContext, CancellationToken cancellationToken)
[AuthenticationFailedException]: DefaultAzureCredential authentication failed.
   at Azure.Identity.DefaultAzureCredential.&lt;GetTokenAsync&gt;d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.&lt;AuthenticateRequestAsync&gt;d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.&lt;ProcessCoreAsync&gt;d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.&lt;ProcessAsync&gt;d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Core.Pipeline.RetryPolicy.&lt;ProcessAsync&gt;d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.GetPage[T](Uri firstPageUri, String nextLink, Func`1 itemFactory, String operationName, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.Secrets.SecretClient.&lt;&gt;c__DisplayClass13_0.&lt;GetPropertiesOfSecrets&gt;b__0(String nextLink)
   at Azure.Core.PageResponseEnumerator.FuncPageable`1.&lt;AsPages&gt;d__2.MoveNext()
   at Azure.Pageable`1.&lt;GetEnumerator&gt;d__8.MoveNext()
   at Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder.GetAllKeys()
   at Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder.LazyInitialize(String name, NameValueCollection config)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureInitialized()
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.GetValueInternal(String key)
[Exception]: Error in Configuration Builder &#39;AzureKeyVault&#39;::GetValue(SecurityKeysConnectionString)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.GetValueInternal(String key)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.ProcessConfigurationSection(ConfigurationSection configSection)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.CreateSectionImpl(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.CreateSectionWithRestrictedPermissions(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   at System.Configuration.RuntimeConfigurationRecord.CreateSection(Boolean inputIsTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectTRUNCATED...

**To Reproduce**
1. Config Azure Configuration Builder in web.config to build connection string. Only repros in connection string, not app settings;
e.g.
  <connectionStrings configBuilders="AzureKeyVault01">
    <clear />
    <add name="conn-x" connectionString="db:user@passwod" />
    <add name="conn-y" connectionString="placeholder" />
  </connectionStrings>
2. Set culture to non "en-US"
e.g. 
    <globalization culture="en-AU" uiCulture="en-AU" />
3. Use the connection string value in Application_Start:
        protected void Application_Start()
        {
            var culture = System.Threading.Thread.CurrentThread.CurrentCulture; //it's the value in web.config
            var timeStyle = culture.DateTimeFormat.ShortDatePattern;// d/MM/yyyy

            Console.WriteLine(ConfigurationManager.ConnectionStrings["conn-x"].ConnectionString);

            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }

**Environment:**
 - .NET 4.7+
 - App Service + MSI enabled

We use procdump to capture memdumps at AuthenticationFailedException, and found the expires_on passed in is like this "4/16/2020 10:05:03 AM +00:00", and it's easy to get the parsing error when using DateTimeOffset.TryParse on it in an en-AU culture application.

**Comment by yukfang** [comment]
The 'e.g.' get lost, so I paste it here again:

  <connectionStrings configBuilders="AzureKeyVault01">
    <clear />
    <add name="conn-x" connectionString="db:user@passwod" />
    <add name="conn-y" connectionString="placeholder" />
  </connectionStrings>

    <globalization culture="en-AU" uiCulture="en-AU" />

        protected void Application_Start()
        {
            var culture = System.Threading.Thread.CurrentThread.CurrentCulture; //it's the value in web.config
            var timeStyle = culture.DateTimeFormat.ShortDatePattern;// d/MM/yyyy

            Console.WriteLine(ConfigurationManager.ConnectionStrings["conn-x"].ConnectionString);

            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }

**Comment by yukfang** [comment]
@schaabs do we have any plans on the fix?Thanks!

**Comment by schaabs** [comment]
@yukfang We are planning on fixing this. Most likely we will fix in two stages. First by fixing the default culture parsing issue for the short term, then later we will move to the new API version. I'll update this once we have a better idea of a release date for the fix.

**Comment by yukfang** [comment]
thanks Scott for your information!

**Comment by schaabs** [comment]
This issue was fixed with PR #11563 and was released in our 1.2.0-preview.3 release a few days ago. Please give it a try and feel free to reopen the issue if the fix doesn't address your issue.

This round of previews is set to GA sometime this summer, but if there is an critical need for a GA fix sooner we could possibly release a patch fix to 1.1.1, just let us know.
