### ISSUE TITLE
[BUG] Storage SDK 11 - The specified block list is invalid

### ISSUE THREAD

**Issue by mattmsft** [Azure/azure-sdk-for-net#11407]
**Describe the bug**
Intermittently, writing blobs to blob storage with "The specified block list is invalid."

We found other reports claiming this happened when they had concurrent writes to the same blob. Indeed,we were able to confirm the last two times we saw this, we were concurrently writing.

**Expected behavior**
The same behavior as the previous storage SDK we were on (WindowsAzure.Storage 9.3) where there is no concurrent writing issue with "The specified block list is invalid"

**Actual behavior (include Exception or Stack Trace)**
2020-04-16T22:52:11 StorageException failed with AggregateException.: The remote server returned an error: (400) Bad Request.. HttpStatusMessage:The specified block list is invalid. HttpStatusCode:400 ServiceRequestId:1f8e18da-801e-000f-2f41-140018000000
Stack: at Microsoft.WindowsAzure.Storage.Core.Util.StorageAsyncResult`1.End()
at Microsoft.WindowsAzure.Storage.Core.Util.AsyncExtensions.<>c__DisplayClass7.b__5(IAsyncResult ar)
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.WindowsAzure.Search.Util.Storage.ContentAwareBlobUploader.d__8.MoveNext() in Q:\cmd\0\Source\Common\Product\Util\Storage\ContentAwareBlobUploader.cs:line 96
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.WindowsAzure.Search.Util.Storage.ContentAwareBlobUploader.d__7.MoveNext() in Q:\cmd\0\Source\Common\Product\Util\Storage\ContentAwareBlobUploader.cs:line 54
--- End of stack trace from previous location where exception was thrown ---

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Write to any BlockBlob at the same time more than once using the Microsoft.Azure.Storage.Blob 11 SDK 

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Storage.Blob 11.1.0
 - Hosting platform or OS and .NET runtime version: .NET Framework 4.7.2
 - IDE and version : Visual Studio 16.5

[There's an existing issue for the v12 SDK that got fixed](https://github.com/Azure/azure-sdk-for-net/issues/10621) - any chance this can be also implemented on v11?

Thank you!

**Comment by kasobol-msft** [comment]
V11 uses "Latest" when committing block list so that means it's not related to https://github.com/Azure/azure-sdk-for-net/issues/10621 . 
@mattmsft Please provide a sample program that reproduces/illustrates "Write to any BlockBlob at the same time more than once using the Microsoft.Azure.Storage.Blob 11 SDK".

**Comment by mattmsft** [comment]
This is specific to us, closing
