### ISSUE TITLE
Avro JsonSchemaBuilder: "fixed" type references fail to resolve

### ISSUE THREAD

**Issue by johncrim** [Azure/azure-sdk-for-net#1206]
This Avro schema works with JsonSchemaBuilder:

```
{
    "type": "record",
    "name": "RequestHeader",
    "fields": [
        { "name": "ID", "type": { "type": "fixed", "name": "System.Guid", "size": 16 } }
    ]
}
```

However this one fails:

```
[
    {
        "type": "record",
        "name": "LogJam.RequestHeader",
        "fields": [
            { "name": "ID", "type": { "type": "fixed", "name": "System.Guid", "size": 16 } }
        ]
    },
    {
        "type": "record",
        "name": "LogJam.ApplicationEntry",
        "fields": [
            { "name": "Name", "type": [ "null", "string" ] },
            { "name": "Assembly", "type": [ "null", "string" ] },
            { "name": "Version", "type": [ "null", "string" ] },
            { "name": "MachineName", "type": [ "null", "string" ] },
            { "name": "ApplicationInstanceId", "type": "System.Guid" }
        ]
    }
]
```

The reference to fixed type named `"System.Guid"` fails, with this call stack:

```
Result Message: System.Collections.Generic.KeyNotFoundException : The given key was not present in the dictionary.
Result StackTrace:  
at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.CreatePrimitiveTypeSchema(String type, Dictionary`2 attributes) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 410
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParsePrimitiveTypeFromString(String token) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 382
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.Parse(JToken token, NamedSchema parent, Dictionary`2 namedSchemas) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 105
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParseRecordField(JObject field, NamedSchema parent, Dictionary`2 namedSchemas, Int32 position) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 349
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.<>c__DisplayClass3.<ParseRecordType>b__2(JToken field, Int32 index) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 318
   at System.Linq.Enumerable.<SelectIterator>d__1`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.Hadoop.Avro.Schema.JsonExtensions.ReadArrayProperty[T](JToken token, String propertyName, Boolean isOptional, Func`3 func) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonExtensions.cs:line 195
   at Microsoft.Hadoop.Avro.Schema.JsonExtensions.OptionalArrayProperty[T](JToken token, String propertyName, Func`3 func) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonExtensions.cs:line 78
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParseRecordType(JObject record, NamedSchema parent, Dictionary`2 namedSchemas) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 309
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParseJsonObject(JObject token, NamedSchema parent, Dictionary`2 namedSchemas) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 140
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.Parse(JToken token, NamedSchema parent, Dictionary`2 namedSchemas) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 88
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.ParseUnionType(JArray unionToken, NamedSchema parent, Dictionary`2 namedSchemas) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 180
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.Parse(JToken token, NamedSchema parent, Dictionary`2 namedSchemas) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 110
   at Microsoft.Hadoop.Avro.Schema.JsonSchemaBuilder.BuildSchema(String schema) in d:\src\codeplex\hadoopsdk\src\Microsoft.Hadoop.Avro\Schema\JsonSchemaBuilder.cs:line 71
```

This prevents reading Avro streams which contain such schema elements using `AvroContainer.CreateGenericReader`.

**Comment by johncrim** [comment]
Note that this bug was fixed here:
https://github.com/hdinsight/azure-sdk-for-net/commit/27d1ba62479f7dc3bfcd2a61a63144918489a9a9

But the public nuget build of Microsoft.Hadoop.Avro (1.5.6) still exhibits the bug.  I'll contribute a test case.

**Comment by johncrim** [comment]
Pull request with a test for this issue:
https://github.com/Azure/azure-sdk-for-net/pull/1207

As noted in the PR, this issue has already been fixed in the hdinsight branch (in hdinsight@27d1ba6).  

In the event that the hdinsight branch won't be merged for some time, the diff for the fix is here:
https://hadoopsdk.codeplex.com/SourceControl/network/forks/johncrim/bug76/changeset/92f1ca56a6be94f5a9c04dd70b441970606d7876

**Comment by jack71** [comment]
:+1:

**Comment by markcowl** [comment]
@johncrim  Thanks for the report and contribution.  Assigning to the service team to review

**Comment by roy128** [comment]
:+1:

**Comment by johncrim** [comment]
Any update on this? This is a significant bug, and I provided a test case. Shouldn't the version where it is fixed be marked?

**Comment by shahabhijeet** [comment]
@johncrim please open a new issue if the problem still exists/repros.
