### ISSUE TITLE
Calling BlockBlobClient.StageBlockAsync() results in a InvalidHeaderValue error

### ISSUE THREAD

**Issue by ProjectWest** [Azure/azure-sdk-for-net#12189]
**Describe the bug**
Seem to be getting an x-ms-version error when making calls the Azure Blobs storage client library. Says the header is not in the correct format

**Expected behavior**
This was working a day ago without error being thrown

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?
Call to StageBlockAsync() fails with exception being thrown:

The value for one of the HTTP headers is not in the correct format.
RequestId:40c13c23-e01e-00cc-6230-2e8136000000
Time:2020-05-19T22:54:17.3042565Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 40c13c23-e01e-00cc-6230-2e8136000000
x-ms-client-request-id: 7f9d187d-239c-424e-8ffb-2a6670f6f56f
x-ms-version: 2019-07-07
x-ms-error-code: InvalidHeaderValue
Date: Tue, 19 May 2020 22:54:16 GMT
Content-Length: 321
Content-Type: application/xml

Stack Track
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.StageBlockAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response) in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\src\Generated\BlobRestClient.cs:line 11305
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.<StageBlockAsync>d__3.MoveNext() in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\src\Generated\BlobRestClient.cs:line 11165
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Threading.Tasks.ValueTask`1.get_Result() in /_/src/System.Private.CoreLib/shared/System/Threading/Tasks/ValueTask.cs:line 759
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/ConfiguredValueTaskAwaitable.cs:line 159
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<StageBlockInternal>d__21.MoveNext() in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\src\BlockBlobClient.cs:line 783
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 563
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<StageBlockAsync>d__20.MoveNext() in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\src\BlockBlobClient.cs:line 702
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. create a BlobContainerClient(string connectionString, string ContainerName)
2. Verify container exists
3. GetBlockBlobClient(string blobName)
4. call StageBlockAsync(blockId, stream, null, null, null, stoppingToken):

```C#
                            //Get a blockId
                            string blockId = Guid.NewGuid().ToString();
                            string base64BlockId = Convert.ToBase64String(Encoding.UTF8.GetBytes(blockId));

                            //Send block
                            using (var blockStream = new MemoryStream(fileBlockToSend))
                            {
                                var blockResult = await _blockBlobClient.StageBlockAsync(base64BlockId, blockStream, null, null, null, stoppingToken);
                            }
```

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs v12.4.1 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): .NET Core 3.1
 - IDE and version : Visual Studio Version 16.5.4

**Comment by amishra-dev** [comment]
Hi @ProjectWest, are you still able to reproduce this problem? If yes, can you send me the "RequestId" from one of the later attempts, the logs pointed to by you have rolled over in the service.

**Comment by ProjectWest** [comment]
@amishra-dev  - this issue seems to be resolved - Staging blocks no longer results in an error
