### ISSUE TITLE
[BUG] NullReferenceException from StartRecognizeCustomForms

### ISSUE THREAD

**Issue by eics-ips** [Azure/azure-sdk-for-net#12322]
**Describe the bug**
Running a console app based on sample code. Getting a stack dump on some PDF files, but not on others. Error occurs when calling StartRecognizeCustomForms. I've attached a cutdown project and two PDFs. One that works (good.pdf) and one that doesn't (bad.pdf).

**Expected behavior**
Expect to return forms and fields. Does on some PDF forms, but not others

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

Unhandled Exception: System.AggregateException: One or more errors occurred. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.AI.FormRecognizer.Models.FormField..ctor(String name, FieldValue_internal fieldValue, IReadOnlyList`1 readResults)
   at Azure.AI.FormRecognizer.Models.RecognizedForm.ConvertFields(IReadOnlyDictionary`2 fields, IReadOnlyList`1 readResults)
   at Azure.AI.FormRecognizer.Models.RecognizedForm..ctor(DocumentResult_internal documentResult, IReadOnlyList`1 pageResults, IReadOnlyList`1 readResults)
   at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.ConvertSupervisedResult(AnalyzeResult_internal analyzeResult)
   at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.ConvertToRecognizedForms(AnalyzeResult_internal analyzeResult)
   at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.<UpdateStatusAsync>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.AI.FormRecognizer.Models.RecognizeCustomFormsOperation.<UpdateStatusAsync>d__23.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationHelpers.<DefaultWaitForCompletionAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at FormRecogTest.Program.<RunFormRecognizerClient>d__4.MoveNext() in C:\Visual Studio Projects\FormRecogTest\FormRecogTest\Program.cs:line 45
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks, Int32 millisecondsTimeout)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)
   at FormRecogTest.Program.Main(String[] args) in C:\Visual Studio Projects\FormRecogTest\FormRecogTest\Program.cs:line 34

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Compile attached project
2. Execute from powershell:  .\FormRecogTest.exe "C:\FormRecognizer\pdf\Bad.pdf"

**Environment:**
 - Name and version of the Library package used: Azure.AI.FormRecognizer 1.0.0-preview.2
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10. .Net Framework 4.7.2
 - IDE and version : Microsoft Visual Studio Enterprise 2019 Version 16.5.5

**Comment by kinelski** [comment]
Thank you for reporting this issue, @eics-ips.

I could not perfectly reproduce your environment because I don't have the files that were used for training your model, so our models are different.

However, even with a different model, I could get the same error message, so it's probably the same bug. If that's the case, it has already been fixed here: #12233, so we're not expecting it to fail anymore in our Preview 3 release, which will be available soon.

Once you upgrade to Preview 3, you will need to add a null check for every field in your code:

```cs
foreach (FormField field in form.Fields.Values)
{
  if (field != null)
  {
    var output = $"Field '{field.Name}'".PadRight(33);
    output += $"Value: '{field.ValueText.Text}'".PadRight(80);
    output += $"Confidence: '{field.Confidence}'";
    Console.WriteLine($"    {output}");
  }
}
```

Do you think it's possible to share your training files (forms and label files) so I can make sure it's not a completely different issue?

**Comment by eics-ips** [comment]
Training Data Attached.
[Training Data.zip](https://github.com/Azure/azure-sdk-for-net/files/4716206/Training.Data.zip)

**Comment by kinelski** [comment]
Thanks for the training files, @eics-ips.

Would you mind sending an email to `caio [dot] maia [@] microsoft [dot] com` so we can discuss this issue?
