### ISSUE TITLE
[BUG] DefaultAzureCredentials do not work on OS X

### ISSUE THREAD

**Issue by Console32** [Azure/azure-sdk-for-net#12417]
**Describe the bug**
DefaultAzureCredentials cause Error on MacOSX works on 

**Expected behavior**
The DefaultAzureCredentials create temporary security credentials that allow access for the BlobContainerClient.

**Actual behavior (include Exception or Stack Trace)**
Causes a Error:

```
Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:a5d63153-e01e-0070-79f3-388f38000000
Time:2020-06-02T15:34:09.0302993Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: a5d63153-e01e-0070-79f3-388f38000000
x-ms-error-code: AuthenticationFailed
Date: Tue, 02 Jun 2020 15:34:08 GMT
Content-Length: 422
Content-Type: application/xml

   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Stream body, Int64 contentLength, String version, Nullable`1 timeout, Byte[] transactionalContentHash, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentHash, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, Nullable`1 accessTier, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.PartitionedUploader.UploadAsync(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, IProgress`1 progressHandler, Nullable`1 accessTier, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadAsync(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, BlobRequestConditions conditions, IProgress`1 progressHandler, Nullable`1 accessTier, StorageTransferOptions transferOptions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.UploadBlobAsync(String blobName, Stream content, CancellationToken cancellationToken)
   at Api.Controllers.DemoController.Put() in /Users/rschn/Source/BRZ/ManagedIdentityWorkshop/Api/Controllers/DemoController.cs:line 58
   at Api.Controllers.DemoController.Put() in /Users/rschn/Source/BRZ/ManagedIdentityWorkshop/Api/Controllers/DemoController.cs:line 60
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

HEADERS
=======
Content-Type: text/plain
Accept: */*
Host: localhost:5000
User-Agent: curl/7.64.1
Content-Length: 15
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

```csharp
            var containerClient = new BlobContainerClient(new Uri($"https://{storageAccountName}.blob.core.windows.net/main"),new DefaultAzureCredential());

            await using var stream = new MemoryStream(Encoding.UTF8.GetBytes(plainText));
            await containerClient.UploadBlobAsync($"Upload_{DateTime.Now.ToFileTimeUtc()}", stream);
```

1. dotnet run on a macos

**Environment:**

.NET Core SDK (reflecting any global.json):
 Version:   3.1.202
 Commit:    6ea70c8dca

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.15
 OS Platform: Darwin
 RID:         osx.10.15-x64
 Base Path:   /usr/local/share/dotnet/sdk/3.1.202/

Host (useful for support):
  Version: 3.1.4
  Commit:  0c2e69caa6

.NET Core SDKs installed:
  3.1.202 [/usr/local/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.4 [/usr/local/share/dotnet/shared/Microsoft.NETCore.App]

Project 'Api' has the following package references
   [netcoreapp3.1]: 
   Top-level Package                                       Requested         Resolved       
   > Azure.Identity                                        1.2.0-preview.3   1.2.0-preview.3
   > Azure.Storage.Blobs                                   12.4.2            12.4.2         
   > Microsoft.Azure.KeyVault                              3.0.5             3.0.5          
   > Microsoft.Azure.Services.AppAuthentication            1.5.0             1.5.0          
   > Microsoft.Extensions.Configuration.AzureKeyVault      3.1.4             3.1.4

**Comment by joshfree** [comment]
@schaabs can you prioritize this for the August release?

**Comment by schaabs** [comment]
@Console32 Thanks for filling this issue, sorry you're experiencing this trouble. Looking at the call stack it doesn't appear that the `DefaultAzureCredential` is failing to authenticate, but rather that the call to storage failed because it was not authorized. Are you sure the account you are using has the appropriate RBAC permissions assigned to it? Also, if you're still experiencing this issue can you please provide more information on how you're authenticating your account? (For instance via Visual Studio, Visual Studio Code, or the Azure CLI)

**Comment by Console32** [comment]
@schaabs 
I was using Azure CLI and I sure had permissions assigned to it (created the blob storage using terraform). Maybe it is working with the new preview. I will give it a look.

**Comment by Console32** [comment]
@schaabs works as expected now.
