### ISSUE TITLE
NullReferenceException in Overlapped.Free in BlobRestClient

### ISSUE THREAD

**Issue by cosin2008** [Azure/azure-sdk-for-net#12580]
**Query/Question**

We are running some Blob R/W operation (v12.4.2) in Azure function app (v3). However, we found it will throw exception timely like below. The error is not just related  BlobLeaseClient but also in BlobClient. Since there is no special logic of our usage, we want to understand if this is bug within Azure Blob SDK and will this issue lead az func app crush or stuck?

Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: XXXX
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Threading.Overlapped.Free(NativeOverlapped* nativeOverlappedPtr)
   at System.Threading.PreAllocatedOverlapped.System.Threading.IDeferredDisposable.OnFinalRelease(Boolean disposed)
   at System.Threading.DeferredDisposableLifetime`1.Dispose(T obj)
   at System.Threading.PreAllocatedOverlapped.Dispose()
   at System.Net.Sockets.SocketAsyncEventArgs.Dispose()
   at System.Net.Sockets.Socket.DisposeCachedTaskSocketAsyncEventArgs()
   at System.Net.Sockets.Socket.Dispose(Boolean disposing)
   at System.Net.Sockets.Socket.Dispose()
   at System.Net.Sockets.Socket.Close(Int32 timeout)
   at System.Net.Sockets.NetworkStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at System.Net.Security.AuthenticatedStream.Dispose(Boolean disposing)
   at System.Net.Security.SslStream.Dispose(Boolean disposing)
   at System.IO.Stream.Close()
   at System.IO.Stream.Dispose()
   at System.Net.Http.HttpConnection.Dispose(Boolean disposing)
   at System.Net.Http.HttpConnection.Dispose()
   at System.Net.Http.HttpConnection.EnsureReadAheadAndPollRead()
   at System.Net.Http.HttpConnectionPool.GetOrReserveHttp11ConnectionAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message)
   at Azure.Core.Pipeline.HttpClientTransport.Process(HttpMessage message)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.RequestActivityPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobRestClient.Blob.ReleaseLeaseAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String leaseId, String version, Nullable`1 timeout, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.ReleaseInternal(RequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.Release(RequestConditions conditions, CancellationToken cancellationToken)

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs 12.4.2
 - Hosting platform or OS and .NET runtime version: Azure function app (v3), it should be in windows hosting
 - IDE and version : Visual Studio 16.3

**Comment by amnguye** [comment]
@kasobol-msft Could you take a look at this? This could be related to the issue that was fixed in Core a while ago.

**Comment by pakrym** [comment]
https://github.com/dotnet/runtime/issues/1218

**Comment by amishra-dev** [comment]
@pakrym is there a workaround?

**Comment by pakrym** [comment]
No sure, just an issue that seemed related.

**Comment by kasobol-msft** [comment]
Looks like Azure Functions v3 (what customer is using) run on .NET Core 3.X https://docs.microsoft.com/en-us/azure/azure-functions/functions-versions .
The stack trace is consistent with https://github.com/dotnet/runtime/issues/1218#issuecomment-569933805 .

**Comment by seanmcc-msft** [comment]
@cosin2008, please re-open if you have more information.
