### ISSUE TITLE
[BUG] BlobBaseClient.DownloadTo(string path) download >256MB or 0 size blob fail

### ISSUE THREAD

**Issue by blueww** [Azure/azure-sdk-for-net#12801]
**Describe the bug**
Download a >256MB (say 300MB) or 0 size block blob Fail with Track2 SDK API BlobBaseClient.DownloadTo(). 
`public virtual Response DownloadTo(string path, CancellationToken cancellationToken);`

**Expected behavior**
download should success

**Actual behavior (include Exception or Stack Trace)**
Download 0 size: fail with: 416 “The range specified is invalid for the current size of the resource.”
Downalod 300MB fail after retry 6 times, each time only download 256MB with return code 206.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a blob with 0 size, create another blob with 300MB
2. Try to download the blobs to local files with BlobBaseClient.DownloadTo(string path)

Compare network trace of Track2 SDK and Track1 SDK, we can see Track2 SDK has an additional Header “x-ms-range: bytes=0-268435455”. 

#### Size 300MB (downloaded content is hide since too long.)
- Track 2 SDK (retry 6 time, all fail same, following is one retry):
```
GET https://***.blob.core.windows.net/weitest/300 HTTP/1.1
x-ms-version: 2019-12-12
x-ms-range: bytes=0-268435455
x-ms-client-request-id: c5ddf65b-2e88-409c-b687-2089408595c4
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.5.0-dev.20200603.3 (.NET Framework 4.8.4180.0; Microsoft Windows 10.0.18363 )
x-ms-date: Mon, 15 Jun 2020 07:54:18 GMT
Authorization: SharedKey ***:****
Host: ***.blob.core.windows.net
Connection: Keep-Alive


HTTP/1.1 206 Partial Content
Content-Length: 268435456
Content-Type: application/octet-stream
Content-Range: bytes 0-268435455/307200000
Last-Modified: Mon, 15 Jun 2020 07:53:19 GMT
Accept-Ranges: bytes
ETag: "0x8D811012B933EA4"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: f3e3952e-701e-009a-6aea-42d379000000
x-ms-client-request-id: c5ddf65b-2e88-409c-b687-2089408595c4
x-ms-version: 2019-12-12
x-ms-version-id: 2020-06-15T07:53:19.6634788Z
x-ms-is-current-version: true
x-ms-creation-time: Mon, 15 Jun 2020 07:53:19 GMT
x-ms-blob-content-md5: 42e/YSV45GhxbHu/d5X8zA==
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-server-encrypted: true
Date: Mon, 15 Jun 2020 07:54:20 GMT
```
- Track1 SDK:
```
GET https://***.blob.core.windows.net/weitest/300 HTTP/1.1
x-ms-client-request-id: 3c4a727a-6661-46cc-b424-f8812a7363e4
User-Agent: Azure-Storage/11.1.1 (.NET Core; Win32NT 10.0.18363.0)
x-ms-version: 2019-02-02
x-ms-date: Mon, 15 Jun 2020 09:28:49 GMT
Authorization: SharedKey ***:****
Host: ***.blob.core.windows.net


HTTP/1.1 200 OK
Content-Length: 307200000
Content-Type: application/octet-stream
Content-MD5: 42e/YSV45GhxbHu/d5X8zA==
Last-Modified: Mon, 15 Jun 2020 07:53:19 GMT
Accept-Ranges: bytes
ETag: "0x8D811012B933EA4"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: ab23f599-001e-0039-7ef7-42b6bc000000
x-ms-client-request-id: 3c4a727a-6661-46cc-b424-f8812a7363e4
x-ms-version: 2019-02-02
x-ms-creation-time: Mon, 15 Jun 2020 07:53:19 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-server-encrypted: true
Date: Mon, 15 Jun 2020 09:28:49 GMT
```

#### Size 0:
- Track 2 SDK:
```
GET https://***.blob.core.windows.net/weitest/testblob HTTP/1.1
x-ms-version: 2019-07-07
x-ms-range: bytes=0-268435455
x-ms-client-request-id: 97f35d91-c05c-401e-b073-480a8dcf580e
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.4.0 (.NET Framework 4.8.4180.0; Microsoft Windows 10.0.18363 )
x-ms-date: Thu, 11 Jun 2020 06:31:12 GMT
Authorization: SharedKey ***:***
Host: ***.blob.core.windows.net
 
 
HTTP/1.1 416 The range specified is invalid for the current size of the resource.
Content-Length: 249
Content-Type: application/xml
Content-Range: bytes */0
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 4137e650-a01e-0099-2fb9-3f321d000000
x-ms-client-request-id: 97f35d91-c05c-401e-b073-480a8dcf580e
x-ms-version: 2019-07-07
x-ms-error-code: InvalidRange
Date: Thu, 11 Jun 2020 06:31:11 GMT
 
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidRange</Code><Message>The range specified is invalid for the current size of the resource.
RequestId:4137e650-a01e-0099-2fb9-3f321d000000
Time:2020-06-11T06:31:12.5196129Z</Message></Error>
 ```

- Track 1 SDK:
```
GET https://***.blob.core.windows.net/weitest/testblob HTTP/1.1
x-ms-client-request-id: f4370237-bbca-445c-bba2-d5be0cac02cb
User-Agent: Azure-Storage/11.1.1 (.NET Core; Win32NT 10.0.18363.0)
x-ms-version: 2019-02-02
x-ms-date: Thu, 11 Jun 2020 06:31:43 GMT
Authorization: SharedKey ***:***
Host: ***.blob.core.windows.net
 
 
HTTP/1.1 200 OK
Content-Length: 0
Content-Type: application/octet-stream
Content-MD5: 1B2M2Y8AsgTpgAmY7PhCfg==
Last-Modified: Wed, 10 Jun 2020 03:42:15 GMT
Accept-Ranges: bytes
ETag: "0x8D80CF044A95EC8"
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 6a58786f-e01e-0088-80b9-3fa8a9000000
x-ms-client-request-id: f4370237-bbca-445c-bba2-d5be0cac02cb
x-ms-version: 2019-02-02
x-ms-creation-time: Wed, 10 Jun 2020 03:42:15 GMT
x-ms-lease-status: unlocked
x-ms-lease-state: available
x-ms-blob-type: BlockBlob
x-ms-copy-id: 4592bed5-ce14-409d-adb6-bc05f40a1b9c
x-ms-copy-source: https://***.blob.core.windows.net/weitest/test3?versionid=2020-06-05T14:07:47.2661030Z&sv=2019-12-12&se=2020-06-17T03%3A42%3A15Z&sr=bv&sp=r
x-ms-copy-status: success
x-ms-copy-progress: 0/0
x-ms-copy-completion-time: Wed, 10 Jun 2020 03:42:15 GMT
x-ms-server-encrypted: true
Date: Thu, 11 Jun 2020 06:31:44 GMT
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
`Azure.Storage.Blobs 12.5.0-dev.20200603.3`
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
.NET Core SDK (reflecting any global.json):
 Version:   2.2.108
 Commit:    33ed5b90ce

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\2.2.108\

Host (useful for support):
  Version: 2.2.6
  Commit:  7dac9b1b51

.NET Core SDKs installed:
  2.2.108 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]
`Visual studio 15.7.4`

**Comment by seanmcc-msft** [comment]
Hi @blueww, I can repo the size 0 issue, but not the 256 MB+ issue.

I believe your experience with 256MB+ is the requests are timing out.  To sidestep this, I'd recommend something along the lines of:
```
            using (var resultStream = new MemoryStream(data))
            {
                await blob.DownloadToAsync(
                    resultStream,
                    transferOptions: new StorageTransferOptions
                    {
                        MaximumConcurrency = 4,
                        MaximumTransferSize = 4 * Constants.MB,
                        InitialTransferSize = 4 * Constants.MB
                    });
            }
```

**Comment by seanmcc-msft** [comment]
@blueww, what is your use case for downloading a blob of size 0?

**Comment by kasobol-msft** [comment]
The 300MB issue might be related to https://github.com/Azure/azure-sdk-for-net/issues/11503

**Comment by kasobol-msft** [comment]
@blueww For the 300MB . Did you use OpenRead before? If so then there is slight change of behavior. The stream in track 2 must be disposed after you're done reading it - otherwise it will block connection.
See https://github.com/Azure/azure-sdk-for-net/issues/11503#issuecomment-645014633

**Comment by kasobol-msft** [comment]
I got consistent repro of large file:
1. Use account that's far away (so that transfer rate is ~5Mbps)
2. Upload 800MB file
3. Use DownloadTo(path) or DownloadToAsync(path) (make sure connection is slow).
4. Make sure to use .NET Framework (not Core)

Here's what's happening:
Download spins up 5 concurrent workers.
ServicePointManager allows 2 connections per host by default.
Requests from 5 concurrent workers get queue up and some of them are timing out (due to slow transfer).

I got it working by either tweaking ServicePointManager or MaxWorkers and disposing stream eagerly in Downloader.
@blueww  things to try:
- previous @seanmcc-msft  suggestion to decrease single download size (so it doesn't time out)
- Increase connection pool , for example `ServicePointManager.DefaultConnectionLimit = 10;`
- Decrease number of workers
```
await blockBlobClient.DownloadToAsync(fileName, transferOptions: new StorageTransferOptions
            {
                MaximumConcurrency = 2
            })
```

**Comment by blueww** [comment]
@seanmcc-msft , @kasobol-msft 
Thanks for investigate this issue!

For 0 size, you can repro it.

For 300MB blob download, I think it's might not related with slow network, but related with the content to download with single request is too big (> 256MB).
The 206 return code should not cause by slow network, but cause by the blob > 256MB, since the Getblob request has header “x-ms-range: bytes=0-268435455”

You can try to repro by `BlobBaseClient.DownloadTo(localFileName)`
1. download to a local file path
2. don't user any transferOptions 

Only 1-2 requests runs on same time in the repro, so ServicePointManager.DefaultConnectionLimit should not matter.

**Comment by blueww** [comment]
For the 300MB download fail, I have discussed with @kasobol-msft online.

It seems my issue is caused by the first request to download timeout (it will download 256MB), and all 6 retries all timeout so failed. 
The default timeout for Track2 is 100s. For Track1 SDK it should be longer.
So when we have a slow network, and big chunk size, the first chunk might always fail so the whole blob download fail.

After make the chunk size to 4MB (each request download 4MB content), the issue not repro. 

But there are still something need fix:
1. The documentation should be update for the difference of Track1 and Track2 SDK
2. The current Track2 Error message is is not clear. We don't see words like "timeout" in it.
3. 0 size blob download fail

**Comment by TimLovellSmith** [comment]
@seanmcc-msft  I probably hit this same size=0 issue too, and I view it as a bug, or at the least a doc bug!

My use-case for downloading the blobs is... I have two apps that read and write a common blob. One of them is responsible for creating and populating the blob.

The way it does this is it takes a lease on the blob, to avoid concurrent writes. But it has to have a blob to lease it, so it will create a size 0 blob just to lease it. Then it will eventually write the blob and release the lease.

The other app just tries to read the whole blob, if it exists, *without taking a lease*, using `DownloadToAsync()`, at which point it sometimes sees the empty blob, and blows up.

Azure.RequestFailedException: The range specified is invalid for the current size of the resource.
RequestId:db10bf77-001e-0076-4d24-35089f000000
Time:2021-04-19T14:04:36.9772757Z
Status: 416 (The range specified is invalid for the current size of the resource.)
ErrorCode: InvalidRange
Headers:
x-ms-request-id: db10bf77-001e-0076-4d24-35089f000000
x-ms-client-request-id: bec1dea6-8464-4262-9425-be6abda2d39c
x-ms-version: 2019-07-07
x-ms-error-code: InvalidRange
Date: Mon, 19 Apr 2021 14:04:36 GMT
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
Content-Length: 249
Content-Range: bytes */0
Content-Type: application/xml
 at Azure.Storage.Blobs.BlobRestClient.Blob.DownloadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
 at Azure.Storage.Blobs.BlobRestClient.Blob.<DownloadAsync>d__0.MoveNext()
at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StartDownloadAsync>d__45.MoveNext()
at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadInternal>d__44.MoveNext()
at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadAsync>d__43.MoveNext()
at Azure.Storage.Blobs.PartitionedDownloader.<DownloadToAsync>d__5.MoveNext()
at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StagedDownloadAsync>d__58.MoveNext()
at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__56.MoveNext()
at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__52.MoveNext()
at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__48.MoveNext()

...and that is the end of what was observed.

My _expectation_ was different. My expectation was that an API like `BlobClient.DownloadToAsync()` shouldn't blow up with a RequestFailedException just because the blob is empty. It should download an empty blob.

My expectation was formed because I never saw this same issue happen with old storage library, and I wotted not that Azure Storage could respond with 416 for requests to download empty blobs, nor that this might be implied by the verbiage 'A RequestFailedException will be thrown if a failure occurs.'
