### ISSUE TITLE
[BUG] Managed identity token for App Service bad `expires_on` format

### ISSUE THREAD

**Issue by jasond-s** [Azure/azure-sdk-for-net#12869]
**Describe The Bug**

We have been using `Microsoft.Azure.KeyVault` for some time now with success. Using the managed identity in our App Services and an AD group to grant access to key vault.

I have updated a couple of apps to use the `Azure.Identity` package and the .Net Framework app has continued to operate, but the .Net Core 3.1 app now does not seem to pick up the credentials. The app SP is added to the group and the group has access to key vault, I have tried giving the app direct access rights to KV also, but no help.

If I add an explicit `AZURE_CLIENT_ID`, `AZURE_CLIENT_SECRET`, and `AZURE_TENENT_ID` that corresponds to an RBAC generated service principle, it all works fine. I don't want to have to do this though and would much prefer to use the managed identity (no config floating around).

**Expected Behaviour**

DefaultAzureCredential will find and use the managed identity in the App Service, to talk to KeyVault

**Actual Behaviour**

This is the stack trace:

 ---> Azure.Identity.AuthenticationFailedException: DefaultAzureCredential authentication failed.
 ---> Azure.Identity.AuthenticationFailedException: Invalid response, the authentication response was not in the expected format.
   at Azure.Identity.ManagedIdentityClient.Deserialize(JsonElement json)
   at Azure.Identity.ManagedIdentityClient.DeserializeAsync(Stream content, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(String[] scopes, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(Boolean isAsync, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async, AuthenticationChallenge challenge)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Secrets.SecretClient.GetSecretAsync(String name, String version, CancellationToken cancellationToken)
   at Codat.Infrastructure.SecretsProvider.SecretsProvider.<>c__DisplayClass18_0.<<TryGetKeyVaultValue>g__TryGetKeyVaultValue|0>d.MoveNext()

**Environment**

_Packages:_
    ```<PackageReference Include="Azure.Identity" Version="1.1.1" />
    <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.0.3" />```

_Calling Code:_
    `new SecretClient("name-of-vault", new DefaultAzureCredential());`

_Running in an Azure App Service, .Net Core:_

_System info_

System up time: 23.02:21:50.5000000
OS version: Microsoft Windows NT 10.0.14393.0
64 bit system: True
64 bit process: True
Processor count: 2
Machine name: RD0003FF0032D8
Instance id: c354aaef437b76d8ededfe5bdc9d74323b723378ca720209f87708f2ff1a26f5
Short instance id: c354aa
CLR version: 4.0.30319.42000
System directory: D:\Windows\system32
Current working directory: D:\Windows\system32
IIS command line: D:\Windows\system32\inetsrv\w3wp.exe -ap "~1REDACTED" -v "v4.0" -a "\\.\pipe\iisipmdREDACTED" -h "C:\DWASFiles\Sites\#1REDACTED\Config\applicationhost.config" -w "C:\DWASFiles\Sites\#1REDACTED\Config\rootweb.config" -m 0
D:\home usage: 512,000 MB total; 509,212 MB free
d:\local usage: 62,464 MB total; 60,179 MB free

_dot net version_

PS D:\home> dotnet --version
dotnet --version
3.1.202

**Comment by jasond-s** [comment]
I have tried releasing the same code to a different App Service to see if was an issue with just the infrastructure, but I seems to happen elsewhere with the same code.

**Comment by jasond-s** [comment]
@schaabs I have tried to call the MSI api from inside the Kudu prompt, and it returns something very sensible.

`$response = Invoke-WebRequest -Uri 'http://127.0.0.1:41601/MSI/token/?api-version=2017-09-01&resource=https://vault.azure.net' -Method GET -Headers @{Metadata="true";Secret="REDACTED"} -UseBasicParsing`

```StatusCode        : 200
StatusDescription : OK
Content           : {123, 34, 97, 99...}
RawContent        : HTTP/1.1 200 OK
                    Content-Length: 1698
                    Date: Mon, 22 Jun 2020 09:26:44 GMT
                    
                    {"access_token":"REDACTED...
Headers           : {[Content-Length, 1698], [Date, Mon, 22 Jun 2020 09:26:44 
                    GMT]}
RawContentLength  : 1698```

By I am still seeing this deserialize error on startup, from both the API and associated WebJobs. This is a blocker to a lot of work migrating to using managed identities. We have been seeing a lot of socket exceptions with the old lib, and so wanted to migrate to the new SDK.

**Comment by jasond-s** [comment]
@schaabs ah, seems that the `expires_on` is in an invalid format, it seems to be in the format `"M/d/yyyy H:m:s tt K"`. Which is really not very standard at all, which makes me think it isn't some culture thing that I can change myself.

**Comment by jasond-s** [comment]
Oh, it has been fixed already, just not released. When is the release scheduled? I don't mind bumping to preview-4 in a limited scope, but don't want to roll that out everywhere.
