### ISSUE TITLE
[FlakyTest] WithTimeoutPropagatesAnExceptionThatCompletesBeforeTimeout

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#12874]
Microsoft.Azure.EventHubs.Tests.TaskExtensionsTests.WithTimeoutPropagatesAnExceptionThatCompletesBeforeTimeout

https://dev.azure.com/azure-sdk/public/_build/results?buildId=431372&view=ms.vss-test-web.build-test-results-tab&runId=11547436&resultId=103502&paneView=debug

```
Assert.Throws() Failure
Expected: typeof(System.MissingMemberException)
Actual: typeof(System.TimeoutException): The operation has timed out.
---- System.TimeoutException : The operation has timed out.


Stack trace
   at Microsoft.Azure.EventHubs.Tests.TaskExtensions.<WithTimeout>d__0.MoveNext() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\Infrastructure\TaskExtensions.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.EventHubs.Tests.TaskExtensionsTests.<<WithTimeoutPropagatesAnExceptionThatCompletesBeforeTimeout>b__10_0>d.MoveNext() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\Instrastructure.Tests\TaskExtensionTests.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
----- Inner Stack Trace -----
   at Microsoft.Azure.EventHubs.Tests.TaskExtensions.<WithTimeout>d__0.MoveNext() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\Infrastructure\TaskExtensions.cs:line 60
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Microsoft.Azure.EventHubs.Tests.TaskExtensionsTests.<<WithTimeoutPropagatesAnExceptionThatCompletesBeforeTimeout>b__10_0>d.MoveNext() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\Instrastructure.Tests\TaskExtensionTests.cs:line 128
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
```

cc @jsquire

**Comment by jsquire** [comment]
A fix for this went in with #12928.
