### ISSUE TITLE
[Flaky test] ScheduleMessageLogsEvents

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#12931]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=433864&view=ms.vss-test-web.build-test-results-tab&runId=11580434&resultId=106835&paneView=debug

```

Error message
Moq.MockException :
Expected invocation on the mock once, but was 0 times: log => log.ScheduleMessagesStart("queueName-09deba83-ae28-419c-8c5d-650b84f4379b", 1, "06/22/2020 16:00:23 +00:00 +00:00")
No setups configured.

Performed invocations:
ServiceBusEventSource.ScheduleMessagesStart("queueName-09deba83-ae28-419c-8c5d-650b84f4379b", 1, "06/22/2020 16:00:23 +00:00")
ServiceBusEventSource.ScheduleMessagesComplete("queueName-09deba83-ae28-419c-8c5d-650b84f4379b")


Stack trace
   at Moq.Mock.VerifyCalls(Mock targetMock, InvocationShape expectation, LambdaExpression expression, Times times, String failMessage)
   at Moq.Mock.VerifyVoid(Mock mock, LambdaExpression expression, Times times, String failMessage)
   at Moq.Mock`1.Verify(Expression`1 expression, Func`1 times)
   at Azure.Messaging.ServiceBus.Tests.Diagnostics.EventSourceTests.<ScheduleMessageLogsEvents>d__4.MoveNext() in D:\a\1\s\sdk\servicebus\Azure.Messaging.ServiceBus\tests\Diagnostics\EventSourceTests.cs:line 194
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

```

**Comment by JoshLove-msft** [comment]
This is apparently a NET Framework bug involving ToString() of DateTimeOffset:
https://stackoverflow.com/questions/32884079/asp-net-datetime-randomly-duplicate-time-offset-is-a-bug
