### ISSUE TITLE
[Flaky test] Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.TimeoutTests.TimeoutInvokeTest

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#12930]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=433864&view=ms.vss-test-web.build-test-results-tab&runId=11580440&resultId=103623&paneView=debug

```
Error message
Unexpected loop exit at 0 batches and 10 seconds
Expected: True
Actual: False


Stack trace
   at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.TestState.CountNBatches(Int32 atLeastBatches, Int32 maxRetries) in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\ServiceFabricProcessor\TestState.cs:line 89
   at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.TimeoutTests.TimeoutInvokeTest() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\ServiceFabricProcessor\TimeoutTests.cs:line 83

```

/cc @jsquire

**Comment by jsquire** [comment]
Temporarily ignored by #12928, pending investigation.

**Comment by samuelkoppes** [comment]
We are investigating this issue and will report back with an update by 11/4/2020.

**Comment by kasun04** [comment]
The Microsoft.Azure.EventHubs.ServiceFabricProcessor package is in preview and there are no plans for a stable release. This package will soon be deprecated and therefore we won't be taking any changes.
