### ISSUE TITLE
Scenario Tests fails randomly

### ISSUE THREAD

**Issue by tonytang-microsoft-com** [Azure/azure-sdk-for-net#1293]
NullReferenceException and KeyNotFoundExceptoin is thrown randomly randomly when running multiple tests. It failed around HttpMockServer.records. If run one test at a time, then test passes. So looks like it's a timing issue when accessing the static member.

```
Test Name:	Test.Azure.Management.Logic.WorkflowAccessKeysScenarioTests.CreateAndList
Test FullName:	Test.Azure.Management.Logic.WorkflowAccessKeysScenarioTests.CreateAndList
Test Source:	d:\github\azure-sdk-for-net\src\ResourceManagement\Logic\Logic.Tests\ScenarioTests\WorkflowAccessKeys.ScenarioTests.cs : line 78
Test Outcome:	Failed
Test Duration:	0:00:00.391

Result Message:	System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'PUT ...'. Calling method CreateOrUpdateWithHttpMessagesAsync().
Result StackTrace:	
at Microsoft.Rest.ClientRuntime.Azure.TestFramework.HttpRecorder.Records.get_Item(String key) in d:\github\azure-sdk-for-net\src\ClientRuntime.Azure.TestFramework\TestFramework\HttpRecorder\Records.cs:line 48
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in d:\github\azure-sdk-for-net\src\ClientRuntime.Azure.TestFramework\TestFramework\HttpRecorder\HttpMockServer.cs:line 113
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Logic.WorkflowsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__33.MoveNext() in d:\github\azure-sdk-for-net\src\ResourceManagement\Logic\LogicManagement\Generated\WorkflowsOperations.cs:line 613
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Logic.WorkflowsOperationsExtensions.<CreateOrUpdateAsync>d__18.MoveNext() in d:\github\azure-sdk-for-net\src\ResourceManagement\Logic\LogicManagement\Generated\WorkflowsOperationsExtensions.cs:line 192
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Logic.WorkflowsOperationsExtensions.CreateOrUpdate(IWorkflowsOperations operations, String resourceGroupName, String workflowName, Workflow workflow) in d:\github\azure-sdk-for-net\src\ResourceManagement\Logic\LogicManagement\Generated\WorkflowsOperationsExtensions.cs:line 169
   at Test.Azure.Management.Logic.WorkflowAccessKeysScenarioTests.CreateAndList() in d:\github\azure-sdk-for-net\src\ResourceManagement\Logic\Logic.Tests\ScenarioTests\WorkflowAccessKeys.ScenarioTests.cs:line 86


```

```
Test Name:	Test.Azure.Management.Logic.WorkflowsScenarioTests.DeleteAllWorkflows
Test FullName:	Test.Azure.Management.Logic.WorkflowsScenarioTests.DeleteAllWorkflows
Test Source:	d:\github\azure-sdk-for-net\src\ResourceManagement\Logic\Logic.Tests\ScenarioTests\Workflows.ScenarioTests.cs : line 216
Test Outcome:	Failed
Test Duration:	0:00:00.25

Result Message:	System.NullReferenceException : Object reference not set to an instance of an object.
Result StackTrace:	
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Collections.Generic.Dictionary`2.set_Item(TKey key, TValue value)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.HttpRecorder.Records.Enqueue(RecordEntry record) in d:\github\azure-sdk-for-net\src\ClientRuntime.Azure.TestFramework\TestFramework\HttpRecorder\Records.cs:line 33
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode) in d:\github\azure-sdk-for-net\src\ClientRuntime.Azure.TestFramework\TestFramework\HttpRecorder\HttpMockServer.cs:line 71
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity) in d:\github\azure-sdk-for-net\src\ClientRuntime.Azure.TestFramework\TestFramework\HttpRecorder\HttpMockServer.cs:line 43
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(String className, String methodName) in d:\github\azure-sdk-for-net\src\ClientRuntime.Azure.TestFramework\TestFramework\MockContext.cs:line 44
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(Int32 currentMethodStackDepth) in d:\github\azure-sdk-for-net\src\ClientRuntime.Azure.TestFramework\TestFramework\MockContext.cs:line 33
   at Test.Azure.Management.Logic.WorkflowsScenarioTests.DeleteAllWorkflows() in d:\github\azure-sdk-for-net\src\ResourceManagement\Logic\Logic.Tests\ScenarioTests\Workflows.ScenarioTests.cs:line 217
```

**Comment by markcowl** [comment]
@tonytang-microsoft-com Currently, tests must be run in sequence, you can do this using attributes in xunit as in this example:https://github.com/Azure/autorest/blob/master/AutoRest/Generators/CSharp/CSharp.Tests/AcceptanceTests.cs

We have a separate issue tracking removal of the singleton from mocked tests which prevent simultaneous execution int he same process.  Closing this as a duplicate for now.
