### ISSUE TITLE
(QUERY) What could be causing this MissingMethodException?

### ISSUE THREAD

**Issue by daveoshinsky** [Azure/azure-sdk-for-net#13505]
We are seeing the MissingMethodException below, whether using an older version of Microsoft.Azure.Management.Compute (27.0) or the latest (38.0).  What could be causing the mismatch and error?

1340 678   07/16 21:09:34 ### CloudSDKWrapper DLL input System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a reqdAssembly System.Net.Http version 4.2.0.0
11340 678   07/16 21:09:34 ### Loading assembly System.Net.Http, Version=4.2.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a at path C:\Program Files\Commvault\ContentStore\Base\CloudSDKWrapper\System.Net.Http.dll
11340 678   07/16 21:09:34 ### CloudSDKWrapper DLL input Microsoft.Azure.Management.Compute, Version=27.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 reqdAssembly Microsoft.Azure.Management.Compute version 27.0.0.0
11340 678   07/16 21:09:34 ### Loading assembly Microsoft.Azure.Management.Compute, Version=38.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35 at path C:\Program Files\Commvault\ContentStore\Base\CloudSDKWrapper\Microsoft.Azure.Management.Compute.dll
11340 678   07/16 21:09:34 ### CloudSDKWrapper DLL input Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed reqdAssembly Newtonsoft.Json version 10.0.0.0
11340 678   07/16 21:09:34 ### Loading assembly Newtonsoft.Json, Version=10.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed at path C:\Program Files\Commvault\ContentStore\Base\CloudSDKWrapper\Newtonsoft.Json.dll
11340 678   07/16 21:09:34 ### exception - System.MissingMethodException: Method not found: 'Void Microsoft.Azure.Management.Compute.ComputeManagementClient..ctor(System.Uri, Microsoft.Rest.ServiceClientCredentials, System.Net.Http.DelegatingHandler[])'.

   at CloudSDKWrapper.AzureResourceBase..ctor(AzureResourceConnection connection)

   at CloudSDKWrapper.AzureResourceManagement..ctor(AzureResourceConnection connection)

   at CloudSDKWrapper.CAzureResourceWrapper.Connect(String subscriptionId, String strApplicatonId, String password)

**Comment by daveoshinsky** [comment]
It appears that the System.Net.Http v4.2 DLL that is loaded here is not compatible with ANY version of Microsoft.Azure.Management.Compute (and other similar logic, e.g. Network and KeyVault).  I have seen reports of similar issues, where one writer reported that only System.Net.Http through v4.0 is compatible with the old non-fluent Azure Management DLL's.  Unfortunately, I have other logic in my application that needs minimum v4.2 of System.Net.Http.  Hence it appears that these non-fluent management DLL's are no longer usable in applications like mine.  I inherited some older code using the non-fluent management logic.  All new logic that I am adding is using Fluent only.

**Comment by erich-wang** [comment]
@daveoshinsky, could you please provide minimal code sample to reproduce the issue? IMO, Microsoft.Azure.Management.Compute v38.0 should be compatible with System.Net.Http >= 4.2

**Comment by daveoshinsky** [comment]
It is part of a larger system, to which I cannot provide source code that would reproduce this problem.  I completely excised all of the calls to the non-fluent API's, and the problem is gone.

**Comment by daveoshinsky** [comment]
This looks to me like it may be the same issue as this:
https://github.com/Azure/azure-sdk-for-net/issues/3607

It appears to me that the non-fluent Azure Management SDK's are not compatible when used with newer SDK's like Azure Cosmos DB v3 SDK (https://github.com/Azure/azure-cosmos-dotnet-v3).  The problems only have begun like this issue describes when we started using Cosmos DB v3 SDK in the same application.  It requires many newer DLL's, and it appears to me that the combination of those newer DLL's (required by Cosmos DB v3 SDK) are incompatible with the older non-fluent Azure Management SDK's.

**Comment by erich-wang** [comment]
It sounds more like environment issue, I would suggest you to capture the loaded assemblies info right before and after exceptions in US hosts and India hosts and compare their difference.
