### ISSUE TITLE
DefaultAzureCredential authentication failed  

### ISSUE THREAD

**Issue by TaranbirBhullar** [Azure/azure-sdk-for-net#13564]
**Query/Question**
I am using [Microsoft.Identity.Web (MIW) version 0.2.0-preview](https://github.com/AzureAD/microsoft-identity-web/blob/84cdbef28ecf51dbff20a665ec8655fb9f09c7a6/src/Microsoft.Identity.Web/Microsoft.Identity.Web.csproj#L85), that uses Azure.Identity 1.1.1 underneath. 

Our deployed application wants to call Microsoft.Graph (as a on-behalf-of flow) and we are using user assigned MSI, to connect to other services and resources in Azure. 

If we are to use Microsoft.Azure.Services.AppAuthentication => AzureServiceTokenProvider
It allows us to get a token from MSI without any issue on the service side ( the deployed instance )

When we use DefaultAzureCredential inside MIW, the issue we get is this. Not sure how to debug this further.
[Here is code that calls DefaultAzureCredential in MIW](https://github.com/AzureAD/microsoft-identity-web/blob/84cdbef28ecf51dbff20a665ec8655fb9f09c7a6/src/Microsoft.Identity.Web/CertificateManagement/DefaultCertificateLoader.cs#L72),

This is the exception and stack trace that we get, any recommendation as to where to start debugging this issue.

```
"An unhandled exception has occurred while executing the request. 
Exception: 
 Azure.Identity.AuthenticationFailedException: DefaultAzureCredential authentication failed.
 ---> Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed.
 ---> Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Fri, 17 Jul 2020 21:24:34 GMT
Content-Length: 133

   at Azure.Identity.ManagedIdentityClient.Authenticate(String[] scopes, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImpl(TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   --- End of inner exception stack trace ---
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(Boolean isAsync, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, Boolean async, AuthenticationChallenge challenge)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.ProcessCoreAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequest[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Certificates.CertificateClient.GetCertificate(String certificateName, CancellationToken cancellationToken)
   at Microsoft.Identity.Web.DefaultCertificateLoader.LoadFromKeyVault(String keyVaultUrl, String certificateName)
   at Microsoft.Identity.Web.DefaultCertificateLoader.LoadIfNeeded(CertificateDescription certificateDescription)
   at Microsoft.Identity.Web.DefaultCertificateLoader.LoadFirstCertificate(IEnumerable`1 certificateDescription)
   at Microsoft.Identity.Web.TokenAcquisition.BuildConfidentialClientApplicationAsync()
   at Microsoft.Identity.Web.TokenAcquisition.GetOrBuildConfidentialClientApplicationAsync()
   at Microsoft.Identity.Web.TokenAcquisition.GetAccessTokenForUserAsync(IEnumerable`1 scopes, String tenant)
   at Microsoft.Azure.Elixir.Framework.Data.External.GraphDataProvider.GetAccessToken() in C:\source\Elixir.Framework\Data\External\GraphDataProvider.cs:line 123
   at Microsoft.Azure.Elixir.Framework.Data.External.GraphDataProvider.GetGraphClient() in C:\source\Elixir.Framework\Data\External\GraphDataProvider.cs:line 111
   at Microsoft.Azure.Elixir.Framework.Data.External.GraphDataProvider.GetUserByAlias(String alias) in C:\source\Elixir.Framework\Data\External\GraphDataProvider.cs:line 55
   at Microsoft.Azure.Elixir.Framework.Services.UserManagement.UserManagementService.RetrieveOrAddUser(String userAlias) in C:\source\Elixir.Framework\Services\UserManagement\UserManagementService.cs:line 173
   at Microsoft.Azure.Elixir.Framework.Services.SupportProduct.ProductMemberService.UpdateProductMembers(IEnumerable`1 productMembers) in C:\source\Elixir.Framework\Services\SupportProduct\ProductMemberService.cs:line 124
   at Microsoft.Azure.Elixir.Controllers.SupportProduct.ProductMembersController.UpdateProductMembers(List`1 members) in C:\source\Elixir\Controllers\SupportProduct\ProductMembersController.cs:line 51
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)"
```

**Environment:**
 - Name and version of the Library package used: 
    - Microsoft.Identity.Web 0.2.0-preview
    - Azure.Identity 1.1.1

 - Hosting platform or OS and .NET runtime version
    - Windows10-x64  - 10.0.18363 (locally)  
    - Azure AppService (deployed instance)
    - .NetCore SDK 3.1.302
    - Host - 3.1.6

**Comment by TaranbirBhullar** [comment]
After having a look through some more related issues, I came across this. [Similiar-Report](https://github.com/Azure/azure-sdk-for-net/issues/11400#issuecomment-620179175)

Which mentions you need to set Environment Variable `AZURE_CLIENT_ID` to be the User assigned MSI's client ID

If you want to do this through the Azure portal.
You can head over to your Azure App Service -> Settings | Configuration -> Application Settings
Add or update the `AZURE_CLIENT_ID` app setting to the User assigned MSI's client ID.
