### ISSUE TITLE
[BUG] Azure.Messaging.ServiceBus Frequent SessionLockLost when SessionLockedUntil isn't timed out yet

### ISSUE THREAD

**Issue by chris-skuvault** [Azure/azure-sdk-for-net#13682]
**Describe the bug**
Current setup:

Using a BackgroundService in .net core application host I'm currently spinning up a session processor per session id with a MaxConcurrentCalls of 1. I'm spinning up 1000 session processors and consuming 10 messages per session of 100 bytes in size. Pretty much every time I test this scenario I'm getting several hundred SessionLockLost exceptions. 

**Expected behavior**
To receive no SessionLockLost errors when the SessionLockedUntil property is not past due.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

Every time I test the above scenario I'm getting several hundred SessionLockLost exceptions with the stack below. Note the last line in the stack is an output of the current time and session lock time.

````
Error: Azure.Messaging.ServiceBus.ServiceBusException: The session lock was lost. Request a new session receiver. (SessionLockLost)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ThrowLockLostException()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteInternalAsync(String lockToken, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c__DisplayClass34_0.<<CompleteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteAsync(String lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.CompleteMessageAsync(String lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ProcessSessionMessageEventArgs.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
   at SkuVault.ServiceBus.Console.Program.ProcessMessage(ProcessSessionMessageEventArgs eventArgs) in C:\Git\sv-service-bus\SkuVault.ServiceBus\SkuVault.ServiceBus.Console\Program.cs:line 180 

   NowTime: 7/23/2020 2:33:20 PM -04:00 - SessionLockedUntil 7/23/2020 2:35:16 PM -04:00 - SessionId: 70
````

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Send 1000 message sessions with 10 messages each to service bus with 100 bytes per message
2. Spin up 1000 session processors 1 per session sent in step 1 with MaxConcurrentCalls set to 1, MaxAutoLockRenewalDuration set to 3 mins and MessageLockDuration 2 mins
3. Set message handler to just receive and complete the messages. On completion of the message randomly will get SessionLockLost exceptions that vary each run of this scenario. This doesn't seem to make it so the message doesn't complete but there is overhead in handling these exceptions when they don't need to be thrown.

**Environment:**
 - Azure.Messaging.ServiceBus v7.0.0-preview.4
 - .net core 3.1
 - VS 16.5.2

**Comment by JoshLove-msft** [comment]
Hi @chris-skuvault, thanks for bringing this to our attention. I think what is most likely happening here is that if the session receiver link connection drops intermittently, when using sessions we will not attempt to re-establish the link to that session as we can't be sure that the session hasn't already been locked by another receiver. So even though the SessionLockedUntil date is in the future, we throw a SessionLockedLost error. To address this, we could attempt to reconnect the session link, the way we do with non-session links, even though we might get a SessionCannotBeLocked error. Also, out of curiosity are you logging these errors from your error handler? Or is this the event source logging output that you have pasted?

**Comment by JoshLove-msft** [comment]
If you want to confirm that the connection is indeed being dropped, you can add an event source listener to your app:
```c#
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(System.Diagnostics.Tracing.EventLevel.Error);
```
The dropped connection exceptions wouldn't get propagated to your error handler as they would be retried automatically, and then translated to SessionLockedLost errors (which do get propagated).

**Comment by chris-skuvault** [comment]
Hey @JoshLove-msft,

Thanks for the heads up on connection dropping as a potential for what's happening. I am catching SessionLockLost inside my message handler currently and logging. It will propagate to the error handler though if I don't catch it in the message handler.

Thanks for the information about the event source logging I'll give it a try and confirm dropped connections.

**Comment by chris-skuvault** [comment]
@JoshLove-msft I tested it out with using the Event Source listener and found that it looks like the session locks were being created due to hitting a resource issue with service bus itself as shown in stack below

````
[Error] Azure-Messaging-ServiceBus: An exception occurred while creating receive link for Identifier: priority/Subscriptions/priority-0-2340d7a6-e05d-441c-8d77-c11125d0ce5c. Error Message: 'Microsoft.Azure.Amqp.AmqpException: The request was terminated because the namespace sv-servicebus-test is being throttled. Error code : 50009. Please wait 2 seconds and try again. To know more visit https://aka.ms/sbResourceMgrExceptions TrackingId:93b81c4f-2964-42e0-a8d2-1c230e8da228_B25, SystemTracker:sv-servicebus-test:Topic:priority|priority-0, Timestamp:2020-07-27T14:51:50 TrackingId:a4f22f2574c6418dbb86f6307c70be7d_G24, SystemTracker:gateway7, Timestamp:2020-07-27T14:51:50
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String entityPath, TimeSpan timeout, UInt32 prefetchCount, ReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver)'
````
After this errors throws I get a bunch of the following session lock errors:

````
[Error] Azure-Messaging-ServiceBus: priority/Subscriptions/priority-0-c37fdcd8-72a2-4bc5-a5a0-e163be3de5ec: CompleteAsync Exception: Azure.Messaging.ServiceBus.ServiceBusException: The session lock was lost. Request a new session receiver. (SessionLockLost)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ThrowLockLostException()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.DisposeMessagesAsync(IEnumerable`1 lockTokens, Outcome outcome, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteInternalAsync(String lockToken, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c__DisplayClass34_0.<<CompleteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteAsync(String lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.CompleteMessageAsync(String lockToken, CancellationToken cancellationToken).
````

Then I implemented the delays on the processors as mentioned in [#13686](https://github.com/Azure/azure-sdk-for-net/issues/13686) and the session locks stopped occurring all together.

**Comment by JoshLove-msft** [comment]
Sounds good, I will close out this issue. Feel free to reopen if you have additional questions!
