### ISSUE TITLE
[BUG] Microsoft.Azure.Management.Fluent should allow retry after network failures

### ISSUE THREAD

**Issue by garath** [Azure/azure-sdk-for-net#13731]
**Describe the bug**

We use Microsoft.Azure.Management.Fluent to manage Azure resource deployments for our service. During a recent deployment, there was an apparent random, transient network issue while operations were underway. All operations happen 
within Azure. 

**Expected behavior**

SDK should provide for recovery and retry of failed network connections. 

**Actual behavior (include Exception or Stack Trace)**

No retry happens.

```
 ##[error]D:\a\1\s\DeployQueues.exe(,): error : Unhandled exception: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: A connection that was expected to be kept alive was closed by the server. ---> System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
    at System.Net.Sockets.Socket.EndReceive(IAsyncResult asyncResult)
    at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
    --- End of inner exception stack trace ---
    at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
    at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
    at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
    --- End of inner exception stack trace ---
    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
    at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
    --- End of inner exception stack trace ---
    at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__15.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ProviderRegistrationDelegatingHandler.<SendAsync>d__4.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.HttpLoggingDelegatingHandler.<SendAsync>d__7.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at Microsoft.Azure.Management.ResourceManager.Fluent.Core.UserAgentDelegatingHandler.<SendAsync>d__5.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
    at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__58.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
    at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__40.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
    at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__35.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateResourceAsync>d__60.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
    at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateAsync>d__59.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.Internal.Helix.Machines.DeployQueues.QueueManager.<DeployAsync>d__58.MoveNext() in D:\a\1\s\src\DeployQueues\QueueManager.cs:line 793
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    at Microsoft.Internal.Helix.Machines.DeployQueues.Program.<>c__DisplayClass3_2.<<TryProcessDefinitionsAsync>b__4>d.MoveNext() in D:\a\1\s\src\DeployQueues\Program.cs:line 352
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.Internal.Helix.Machines.DeployQueues.Program.<TryProcessDefinitionsAsync>d__3.MoveNext() in D:\a\1\s\src\DeployQueues\Program.cs:line 362
 --- End of stack trace from previous location where exception was thrown ---
    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    at Microsoft.Internal.Helix.Machines.DeployQueues.Program.<Main>d__0.MoveNext() in D:\a\1\s\src\DeployQueues\Program.cs:line 180
```

**To Reproduce**

Cause network disconnect during transaction.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.Fluent 1.34.0
 - Hosting platform or OS and .NET runtime version: Azure Pipelines vs2017-win2016, .NET Framework 4.7.2
 - IDE and version : N/A

**Comment by jsquire** [comment]
Tagging and routing to the team best able to assist.

**Comment by isra-fel** [comment]
@weidongxu-microsoft for help

**Comment by weidongxu-microsoft** [comment]
@xccc-msft Do we have ready-to-use retry code snippet?

**Comment by xccc-msft** [comment]
@garath You might want to set via [RetryPolicy](https://docs.microsoft.com/en-us/dotnet/api/microsoft.rest.transientfaulthandling.retrypolicy.-ctor?view=azure-dotnet#Microsoft_Rest_TransientFaultHandling_RetryPolicy__ctor_Microsoft_Rest_TransientFaultHandling_ITransientErrorDetectionStrategy_System_Int32_System_TimeSpan_System_TimeSpan_System_TimeSpan_).
```csharp
var azure = Microsoft.Azure.Management.Fluent.Azure.Configure()
    // add configured retry policy
    .WithRetryPolicy(new RetryPolicy(new HttpStatusCodeErrorDetectionStrategy(), retryCount, minBackoff, maxBackoff, deltaBackoff))
    .Authenticate(azureCredentials)
    .WithDefaultSubscription();
```

**Comment by garath** [comment]
Somehow... we missed this method. I'll take this back to the team, update our service, and reopen if it reoccurs. 

Thanks for your help!
