### ISSUE TITLE
[Flaky test] UploadAsync_WithUnreliableConnection

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#13970]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=484399&view=ms.vss-test-web.build-test-results-tab&runId=12427772&resultId=108838&paneView=debug
```

Error message
System.IndexOutOfRangeException : Index was outside the bounds of the array.


Stack trace
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at System.Linq.Enumerable.LastOrDefault[TSource](IEnumerable`1 source)
   at Azure.Storage.Test.Shared.StorageTestBase.<WaitForProgressAsync>d__37.MoveNext() in D:\a\1\s\sdk\storage\Azure.Storage.Common\tests\Shared\StorageTestBase.cs:line 342
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Azure.Storage.Blobs.Test.BlockBlobClientTests.<UploadAsync_WithUnreliableConnection>d__66.MoveNext() in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\tests\BlockBlobClientTests.cs:line 1992
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Storage.Blobs.Test.BlockBlobClientTests.<UploadAsync_WithUnreliableConnection>d__66.MoveNext() in D:\a\1\s\sdk\storage\Azure.Storage.Blobs\tests\BlockBlobClientTests.cs:line 2011
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by pakrym** [comment]
cc @kasobol-msft 

this test often fails in core nightly runs. Can it be disabled?

**Comment by kasobol-msft** [comment]
@seanmcc-msft  @jaschrep-msft

**Comment by kasobol-msft** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/14213
