### ISSUE TITLE
[BUG] ErrorResponseException / InsufficientAuthorization when specifying more than one 'responseFilter' value for Microsoft.Azure.CognitiveServices.Search.WebSearch Search

### ISSUE THREAD

**Issue by joergbattermann** [Azure/azure-sdk-for-net#14067]
**Describe the bug**
When using the `Microsoft.Azure.CognitiveServices.Search.WebSearch.WebSearchClient` of the [Microsoft.Azure.CognitiveServices.Search.WebSearch v2.0 NuGet package](https://www.nuget.org/packages/Microsoft.Azure.CognitiveServices.Search.WebSearch/2.0.0)  I can either specify _no_ or _one_ _responseFilter_ value, however - since it is a `List<string>` [parameter type](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.cognitiveservices.search.websearch.webextensions.searchasync?view=azure-dotnet#parameters) and [its documentation states](https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-web-api-v7-reference#query-parameters) I can provide a list of response types I want to get, I tried just that -  more than one (i.e. _three_ as shown in the example below), but when making the call I get an `Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.ErrorResponseException` back stating that

```
Operation returned an invalid status code 'Forbidden'
Only these values are allowed: Webpages,Images,Videos,News,SpellSuggestions,entities,places,RelatedSearches,Computation,TimeZone,Translations
Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Azure.CognitiveServices.Search.WebSearch.Web.SearchWithHttpMessagesAsync(String query, String acceptLanguage, String pragma, String userAgent, String clientId, String clientIp, String location, Nullable`1 answerCount, String countryCode, Nullable`1 count, String freshness, String market, Nullable`1 offset, IList`1 promote, IList`1 responseFilter, String safeSearch, String setLang, Nullable`1 textDecorations, String textFormat, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Search.WebSearch.WebExtensions.SearchAsync(IWeb operations, String query, String acceptLanguage, String pragma, String userAgent, String clientId, String clientIp, String location, Nullable`1 answerCount, String countryCode, Nullable`1 count, String freshness, String market, Nullable`1 offset, IList`1 promote, IList`1 responseFilter, String safeSearch, String setLang, Nullable`1 textDecorations, String textFormat, CancellationToken cancellationToken)
   at AzureCognitiveSearch.Program.Main(String[] args) in D:\Development\Playground\AzureCognitiveSearch\AzureCognitiveSearch\Program.cs:line 63
```

See also:
![image](https://user-images.githubusercontent.com/828/89732361-8e6c7c00-da4e-11ea-878d-cc424cfce87d.png)

However, my input _responseFilter_ values _are_ part of the list of allowed values.

**Expected behavior**
Search returns results for the given responseFilter values

**Actual behavior (include Exception or Stack Trace)**
```
Operation returned an invalid status code 'Forbidden'
Only these values are allowed: Webpages,Images,Videos,News,SpellSuggestions,entities,places,RelatedSearches,Computation,TimeZone,Translations
Microsoft.Azure.CognitiveServices.Search.WebSearch.Models.ErrorResponseException: Operation returned an invalid status code 'Forbidden'
   at Microsoft.Azure.CognitiveServices.Search.WebSearch.Web.SearchWithHttpMessagesAsync(String query, String acceptLanguage, String pragma, String userAgent, String clientId, String clientIp, String location, Nullable`1 answerCount, String countryCode, Nullable`1 count, String freshness, String market, Nullable`1 offset, IList`1 promote, IList`1 responseFilter, String safeSearch, String setLang, Nullable`1 textDecorations, String textFormat, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Search.WebSearch.WebExtensions.SearchAsync(IWeb operations, String query, String acceptLanguage, String pragma, String userAgent, String clientId, String clientIp, String location, Nullable`1 answerCount, String countryCode, Nullable`1 count, String freshness, String market, Nullable`1 offset, IList`1 promote, IList`1 responseFilter, String safeSearch, String setLang, Nullable`1 textDecorations, String textFormat, CancellationToken cancellationToken)
   at AzureCognitiveSearch.Program.Main(String[] args) in D:\Development\Playground\AzureCognitiveSearch\AzureCognitiveSearch\Program.cs:line 63
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

Run the following repro code:
```
try
{
    var webSearchResponse = await new WebSearchClient(new ApiKeyServiceClientCredentials("Your API KEY HERE"))
        .Web
        .SearchAsync(
            query: "COVID-19 Statistik Erlangen",
            count: 50,
            offset: 0,
            market: "de-DE",
            setLang: "DE",
            //countryCode:
            safeSearch: SafeSearch.Off,
            location: $"lat:49.583332;long:11.016667;re:22;disp:Erlangen, Germany", // see https://docs.microsoft.com/en-us/rest/api/cognitiveservices-bingsearch/bing-web-api-v7-reference
            responseFilter: new List<string>()
            {
                "WebPages",
                "RelatedSearches",
                "SpellSuggestions"
            });

}
catch (Exception ex)
{
    Console.WriteLine("ex.Message);
}
```

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.CognitiveServices.Search.WebSearch 2.0
 - Hosting platform or OS and .NET runtime version: Windows 10 .NET Core 3.1
 - IDE and version : Visual Studio 16.7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by joergbattermann** [comment]
👍

**Comment by brjohnstmsft** [comment]
@jsquire This issue is regarding the Cognitive Services web search API, not Azure Cognitive Search (unfortunate that their names are so similar, I know...). I've updated the tags accordingly.

**Comment by jsquire** [comment]
Thanks, @brjohnstmsft.   I appreciate the assist and apologize for the inconvenience.

**Comment by KranthiPakala-MSFT** [comment]
@joergbattermann Apologies for the delayed response. I see that this issue is opened long time ago and no further activity had taken place. So wanted to check if you are still facing the issue and need assistance on this query? Please let us know .

**Comment by joergbattermann** [comment]
This issue can still be reproduced as originally reported @KranthiPakala-MSFT.

**Comment by JimSuplizio** [comment]
Hi @joergbattermann, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
