### ISSUE TITLE
Windows Service, CreateBlobContainer: Retry failed after 6 tries

### ISSUE THREAD

**Issue by phlexss** [Azure/azure-sdk-for-net#14124]
**Describe the bug**
When I run the CreateBlobContainer function to create a container the container is correctly created but the code does not continue after the function. After some time the following error is reported: Retry failed after 6 tries.

This ONLY happens when running the function in a "Windows Service" aplication (I'm using .Net framework 4.8 but the problem also exists in 4.7.2).

When I run the function in a winforms app it works correctly.

**Expected behavior**
The expected behaviour is that the function does not "hang" and run into some timeout but continues with the code immediately.

**Actual behavior (include Exception or Stack Trace)**
The program stalls and after some time the exception "Retry failed after 6 tries" is thrown.

**To Reproduce**
Dim myBlobServiceClient As BlobServiceClient = New BlobServiceClient("connectstring")
Dim myBlobContainerClient As BlobContainerClient = myBlobServiceClient.CreateBlobContainer("container1")

...and run this code in a Windows Service application.

**Environment:**
Azure.Storage.Blobs 12.4.4
.NET Framework 4.8
Windows 10
Windows Service application
VS2019 16.7.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Sorry I was not able to reproduce your issue. I created a Window Service Application using the one provided by Visual Studios without anything added on aside from creating a Blob Container.

Is there anything else you can provide that would help us figure out your issue? Like what you have configured in your windows service, a stack trace or anything you're doing before hand?

**Comment by phlexss** [comment]
I now created a new clean windows service application myself and this indeed seems to work fine.

I get the problem with an existing windows service app. I now put the Azure code as the first code to be executed when the service starts and it fails with the  "Retry failed after 6 retries." error.

Here is the stacktrace:

   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobRestClient.Container.<CreateAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.<CreateInternal>d__47.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.Create(PublicAccessType publicAccessType, IDictionary`2 metadata, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.CreateBlobContainer(String blobContainerName, PublicAccessType publicAccessType, IDictionary`2 metadata, CancellationToken cancellationToken)
   at omniphlex8d8.modCommonDaemons.Service_OnStart()

**Comment by phlexss** [comment]
I think I'm getting closer to the problem. The inner stacktrace shows:

INNER EXCEPTION:
Could not load file or assembly 'System.Buffers, Version=4.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
INNER EXCEPTION STACKTRACE:
   at Azure.Core.Pipeline.ResponseBodyPolicy.CopyTo(Stream source, Stream destination, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.ResponseBodyPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.LoggingPolicy.<ProcessAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.LoggingPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()

So I think the problem is related to incorrect binding redirects....and it seems this is a more common problem with nuget packages am I correct?

**Comment by phlexss** [comment]
I may have solved the problem.

The problem seems to have been inconsistencies in assemblies.....probably caused by the fact that at some point I downgraded to an earlier version of Azure.Storage .Blobs but the binding redirects were not removed from app.config.

I'm now cleaning the app.config and doing a complete re-install of the nuget packages.....

I'll report back if this has worked or not.

**Comment by phlexss** [comment]
The mismatch between dll versions has been resolved and everything now works fine.

I close this problem.
