### ISSUE TITLE
[Flaky test] BearerTokenAuthenticationPolicy_TokenExpiredThenFailed

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14129]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=490828&view=ms.vss-test-web.build-test-results-tab&runId=12546438&resultId=100428&paneView=debug

```

Error message
Expected: <System.InvalidOperationException: Error
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<>c__DisplayClass14_0.<BearerTokenAuthenticationPolicy_TokenExpiredThenFailed>b__0(TokenRequestContext r, CancellationToken c) in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 414
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.TokenCredentialStub.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 565
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(HttpMessage message, Boolean async, CancellationToken cancellationToken) in //sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 217
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, Boolean async) in //sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 110
at System.Threading.Tasks.ValueTask1.get_Result() at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory1 pipeline, Boolean async) in //sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 61
at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task) in //sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 78
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory1 pipeline) in /_/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 51 at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Pipeline/HttpPipeline.cs:line 80 at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipeline pipeline, Action1 requestAction, Boolean bufferResponse, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 32
at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipelineTransport transport, Action1 requestAction, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 43 at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendGetRequest(HttpPipelineTransport transport, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, Uri uri, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 48 at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<>c__DisplayClass14_0.<<BearerTokenAuthenticationPolicy_TokenExpiredThenFailed>b__1>d.MoveNext() in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 436 --- End of stack trace from previous location where exception was thrown --- at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter1.GetResult()
at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
at NUnit.Framework.Assert.ThrowsAsync(IResolveConstraint expression, AsyncTestDelegate code, String message, Object[] args)>
But was:  <System.InvalidOperationException: Error
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<>c__DisplayClass14_0.<BearerTokenAuthenticationPolicy_TokenExpiredThenFailed>b__0(TokenRequestContext r, CancellationToken c) in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 414
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.TokenCredentialStub.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.BearerTokenAuthenticationPolicy_TokenExpiredThenFailed() in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 440```

**Comment by pakrym** [comment]
Another failure https://dev.azure.com/azure-sdk/internal/_build/results?buildId=681178&view=ms.vss-test-web.build-test-results-tab&runId=15900704&resultId=101293&paneView=debug

**Comment by pakrym** [comment]
cc @schaabs @AlexGhiondea

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=687386&view=ms.vss-test-web.build-test-results-tab&runId=15992488&resultId=101549&paneView=debug

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=698001&view=ms.vss-test-web.build-test-results-tab&runId=16141158&resultId=100807&paneView=debug

**Comment by JoshLove-msft** [comment]
Hasn't failed in a while, closing.
