### ISSUE TITLE
[QUERY]how to get role assignment with scope "/"

### ISSUE THREAD

**Issue by Emma0727** [Azure/azure-sdk-for-net#14127]
**Query/Question**
How can we help?
how to get role assignment with scope "/".
It seems .RoleAssignments.ListByScopeAsyncor other method are not support scope “/”.
```
var tokenCredentials = new TokenCredentials(armToken);
                var authenticated = Azure
                    .Configure()
                    .WithLogLevel(HttpLoggingDelegatingHandler.Level.Basic)
                    .Authenticate(new AzureCredentials(
                        tokenCredentials,
                        tokenCredentials,
                        organizationId,
                        AzureEnvironment.AzureGlobalCloud));

                var roledefinition = await authenticated.RoleDefinitions.GetByScopeAndRoleNameAsync("/", BuiltInRole.UserAccessAdministrator.ToString());
                var roleAssignments = await authenticated.RoleAssignments.ListByScopeAsync("/");
```

now I can only get that from api:
https://management.azure.com/providers/Microsoft.Authorization/roleAssignments?api-version=2015-07-01&$filter=principalId eq '***'

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.management.fluent 1.34.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Emma0727** [comment]
any update?

**Comment by Emma0727** [comment]
I try to use another method to get role assginment:
var roleAssignments = await authenticated.RoleAssignments.GetByIdAsync(roledefinition.Id);
But it failed like ther viersion api version used 2018-09-01-preview, is not suitable.
Any one can help?

[2020_08_12_08_52_30.968] [LogException], AzureResourceService, GetAzureClientAynsc, 13be6b52-e8b1-4622-afd3-e8bcc5f3709e, exception:Microsoft.Rest.Azure.CloudException: The resource type 'roleDefinitions' could not be found in the namespace 'Microsoft.Authorization' for api version '2018-09-01-preview'. The supported api-versions are '2014-04-01-preview,2014-07-01-preview,2014-10-01-preview,2015-05-01-preview,2015-06-01,2015-07-01,2016-07-01,2017-05-01,2017-09-01,2018-01-01-preview,2018-07-01'.
at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperations.GetByIdWithHttpMessagesAsync(String roleId, Dictionary`2 customHeaders, CancellationToken cancellationToken)
at Microsoft.Azure.Management.Graph.RBAC.Fluent.RoleAssignmentsOperationsExtensions.GetByIdAsync(IRoleAssignmentsOperations operations, String roleId, CancellationToken cancellationToken)

**Comment by yungezz** [comment]
duplicate with https://github.com/Azure/azure-libraries-for-net/issues/1122
