### ISSUE TITLE
CreateOrUpdate(...) throws Hyak.Common.CloudException... most of the times

### ISSUE THREAD

**Issue by krist00fer** [Azure/azure-sdk-for-net#1426]
Both the CreateOrUpdate(...) method and the CreateOrUpdateAsync(...) message throws CloudException . At least most of the times. I've managed to get it to work a couple of times while trying to debug, but most of the times the call throws an exception, while the resource is still created in Azure.

Sample Code:

```
    public static void CreateStorageAccount(TokenCloudCredentials credential, string resourceGroupName, string storageAccountName, string location)
    {
        using (var client = new ResourceManagementClient(credential))
        {

            var resourceId = new ResourceIdentity()
            {
                ResourceType = "storageAccounts",
                ResourceName = storageAccountName,
                ResourceProviderApiVersion = "2015-05-01-preview",
                ResourceProviderNamespace = "Microsoft.Storage"
            };

            var properties = new GenericResource
            {
                Location = location,
                Properties = JsonConvert.SerializeObject(new
                {
                    accountType = "Standard-LRS"
                })
            };

            // Exception is thrown while running the following line
            var result = client.Resources.CreateOrUpdate(resourceGroupName, resourceId, properties);
        }
    }
```

Exception Details:

```
    Hyak.Common.CloudException was unhandled
      HResult = -2146233088
      Message=null
      Source=Microsoft.Threading.Tasks
      StackTrace:
           at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
           at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
           at Microsoft.Azure.Management.Resources.ResourceOperationsExtensions.CreateOrUpdate(IResourceOperations operations, String resourceGroupName, ResourceIdentity identity, GenericResource parameters)
           at DeploymentConsole.Program.CreateStorageAccount(TokenCloudCredentials credential, String resourceGroupName, String storageAccountName, String location) in C:\dev\DeploymentConsole\DeploymentConsole\Program.cs:line 136
           at DeploymentConsole.Program.Main(String[] args) in C:\dev\DeploymentConsole\DeploymentConsole\Program.cs:line 52
           at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
           at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
           at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
           at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
           at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
           at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
           at System.Threading.ThreadHelper.ThreadStart()
      InnerException:
```

**Comment by shahabhijeet** [comment]
@krist00fer please open a new issue if the problem still exists/repros.
