### ISSUE TITLE
[Flaky test] BearerTokenAuthenticationPolicy_TokenAlmostExpiredThenFailed

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14612]
```
Error message
Expected: 2
But was:  1


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<BearerTokenAuthenticationPolicy_TokenAlmostExpiredThenFailed>d__15.MoveNext() in D:\a\1\s\sdk\core\Azure.Core\tests\BearerTokenAuthenticationPolicyTests.cs:line 510
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)
```

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=512248&view=ms.vss-test-web.build-test-results-tab&runId=12919552&resultId=102284&paneView=debug

**Comment by pakrym** [comment]
Another one https://dev.azure.com/azure-sdk/internal/_build/results?buildId=519790&view=ms.vss-test-web.build-test-results-tab&runId=13070848&resultId=102439&paneView=debug

**Comment by pakrym** [comment]
Still flaky https://dev.azure.com/azure-sdk/public/_build/results?buildId=564767&view=ms.vss-test-web.build-test-results-tab&runId=13984944&resultId=101884&paneView=debug

**Comment by AlexGhiondea** [comment]
@schaabs can you take a look?

**Comment by pakrym** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/16054

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=949626&view=ms.vss-test-web.build-test-results-tab&runId=20321610&resultId=101799&paneView=debug

```
BearerTokenAuthenticationPolicy_TokenAlmostExpiredThenFailed

Result Details
Failed Wednesday on 5130688bc000004
Duration0:00:03.833
Ownernot available
Date started6/16/2021, 1:25:08 AM
Date completed6/16/2021, 1:25:12 AM
Failing sinceWednesday
Failing since build20210616.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: 2
But was:  1


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.BearerTokenAuthenticationPolicy_TokenAlmostExpiredThenFailed() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\BearerTokenAuthenticationPolicyTests.cs:line 533
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```
@AlexanderSher can you please disable the test?

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=957221&view=ms.vss-test-web.build-test-results-tab&runId=20479326&resultId=101708&paneView=debug


```
BearerTokenAuthenticationPolicy_TokenAlmostExpiredThenFailed

Result Details
Failed 2h ago on 61e773a2c000004
Duration0:00:04.083
Ownernot available
Date started6/21/2021, 1:35:10 PM
Date completed6/21/2021, 1:35:14 PM
Failing since2h ago
Failing since build20210621.10

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: 2
But was:  1


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.BearerTokenAuthenticationPolicy_TokenAlmostExpiredThenFailed() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\BearerTokenAuthenticationPolicyTests.cs:line 533
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by JoshLove-msft** [comment]
This hasn't failed recently - closing.
