### ISSUE TITLE
[WebJobs] Follow up on hierarchical configuration support in local.settings.json

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#14826]
There are two places that fail when the configuration has nested objects:

https://github.com/Azure/azure-functions-core-tools/blob/28be3f19626161c5cca94d2d4376a2a3350c923b/src/Azure.Functions.Cli/Common/AppSettingsFile.cs#L11

and 
```
Newtonsoft.Json.JsonReaderException: Unexpected character encountered while parsing value: {. Path 'Values.MyStorageConnection', line 5, position 30.
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.JsonTextReader.ReadStringValue(ReadType readType)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.JsonTextReader.ReadAsString()
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(IDictionary dictionary, JsonReader reader, JsonDictionaryContract contract, JsonProperty containerProperty, String id)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :    at MakeFunctionJson.FunctionJsonConverter.CheckAppSettingsAndFunctionName(FunctionJsonSchema functionJson, MethodDefinition method)
1>C:\Users\pakrym\.nuget\packages\microsoft.net.sdk.functions\3.0.9\build\Microsoft.NET.Sdk.Functions.Build.targets(32,5): warning :
```

in https://github.com/Azure/azure-functions-vs-build-sdk/blob/3a4efa5d8891b8d7efeff6e12c313d425281aa87/src/Microsoft.NET.Sdk.Functions.Generator/FunctionJsonConverter.cs#L208

**Comment by ellismg** [comment]
When we address this we should also look at the README.md for the extension package to see if we can use nested objects there.
