### ISSUE TITLE
[Azure Form Recognizer]Using ClientSecretCredential to authenticate FormTrainingClient not work in sovereign cloud

### ISSUE THREAD

**Issue by XuGuang-Yao** [Azure/azure-sdk-for-net#14952]
We are running live Tests against other clouds like US Gov and Azure China Cloud. The goal is to check whether new azure sdk package work with other clouds or not.

Test [FormTrainingClientCanAuthenticateWithTokenCredential](https://github.com/Azure/azure-sdk-for-net/blob/6ee76ca143cd2810660e0f0b7ec7878d9ab5852a/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormTrainingClient/FormTrainingClientLiveTests.cs#L41) uses `ClientSecretCredential` to authenticate `FormTrainingClient`. It works in Azure cloud but returns 401 in US gov cloud. 

```
Azure.RequestFailedException : Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource.
Status: 401 (Access Denied)
ErrorCode: 401

Content:
{"error":{"code":"401","message": "Access denied due to invalid subscription key or wrong API endpoint. Make sure to provide a valid key for an active subscription and use a correct regional API endpoint for your resource."}}

Headers:
apim-request-id: 67f0e954-9129-4679-a915-70781e8188d4
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
WWW-Authenticate: REDACTED
Date: Fri, 04 Sep 2020 01:56:57 GMT
Content-Length: 225
Content-Type: application/json

at Azure.AI.FormRecognizer.ServiceRestClient.AnalyzeLayoutAsync(FormContentType contentType, Stream fileStream, CancellationToken cancellationToken) in /_/sdk/formrecognizer/Azure.AI.FormRecognizer/src/Generated/ServiceRestClient.cs:line 850
   at Azure.AI.FormRecognizer.FormRecognizerClient.StartRecognizeContent(Stream form, RecognizeContentOptions recognizeContentOptions, CancellationToken cancellationToken) in /_/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormRecognizerClient.cs:line 140
--- End of stack trace from previous location where exception was thrown ---
   at Azure.AI.FormRecognizer.Tests.FormRecognizerClientLiveTests.FormRecognizerClientCanAuthenticateWithTokenCredential() in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerClient/FormRecognizerClientLiveTests.cs:line 54
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

The same result occurs when sending Rest API.

![image](https://user-images.githubusercontent.com/53599438/92428903-fdaacc80-f1c2-11ea-9aa5-d5c57027db3a.png)

@jongio @danieljurek for notification.

**Comment by maririos** [comment]
dup of https://github.com/Azure/azure-sdk-for-net/issues/17192
