### ISSUE TITLE
ResourceManagerClient.Resources.CheckExistenceByIdAsync throws CloudException

### ISSUE THREAD

**Issue by nikatiya** [Azure/azure-sdk-for-net#15227]
**Describe the bug**
We were using the CheckExistenceByIdAsync API to check existence of a user assigned identity before proceeding to do further operation but the call failed with following error:

request failed: Microsoft.Rest.Azure.CloudException: **_Operation returned an invalid status code 'BadGateway'_**
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.<CheckExistenceByIdWithHttpMessagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions.<CheckExistenceByIdAsync>d__9.MoveNext()

We are using a typical managed identity resourceId and a get resource call for it succeeds in case the identity exists.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.Management.ResourceManager.Fluent, Version=1.9.1

Can you help us understand if it a problem with this version of library or something missing from our end.

**Comment by nikatiya** [comment]
MSI team confirmed they do not support HEAD API.
