### ISSUE TITLE
[FEATURE REQ] Improve error handling when ASB message property exceeds max size

### ISSUE THREAD

**Issue by amolenk** [Azure/azure-sdk-for-net#15325]
**Library or service name.**
Azure Service Bus
 
**Is your feature request related to a problem? Please describe.**
We had an issue in a production system where a message went in a retry loop. We found the root cause to be a message property that exceeded the maximum size (it was a particularly large Exception stack trace stored in the message property).
It took us a while to figure this out because the error message is not really clear.

Repro:
``` csharp
try
{
    string messageBody = "Hello, world";
    var message = new Message(Encoding.UTF8.GetBytes(messageBody));
    message.UserProperties["TooLarge"] = string.Empty.PadRight(32786, '.');

    await queueClient.SendAsync(message);
}
catch (Exception exception)
{
    Console.WriteLine($"{DateTime.Now} :: Exception: {exception.Message}");
}
```

The exception caught is:
``` 
The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 Reference:ab4341ef-ee3e-4015-960f-1c99b1bbbd89, TrackingId:3374c6ae0000930c009bb77a5f69fca9_G9_B2, SystemTracker:unknownerrorrepro:Queue:error, Timestamp:2020-09-22T13:31:57
```

I did some debugging with the SDK, and what happens is that an AMQP rejection with code 37 is received from the server. This result cannot be mapped to an Error object which is why a `new ServiceBusException(true, "Unknown error.")` is thrown.

**Describe the solution you'd like**
The SDK should throw an Exception before publishing the message with clear information on why the message cannot be published.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft, @MiYanni

**Comment by axisc** [comment]
@amolenk Thanks for reporting this and the repro steps. We will investigate this and plan a fix in the upcoming release.

**Comment by anqyan** [comment]
This looks like an issue specific to Microsoft.Azure.ServiceBus SDK (track 1), because I got the expected exception when using Microsoft.ServiceBus.Messaging SDK (track 0):

> System.ArgumentException: The size of message property 'TooLarge' exceeds the limit of '32767' bytes.
Parameter name: Properties
   at Microsoft.ServiceBus.Messaging.BrokeredMessage.ValidateMessageProperties(IDictionary`2 properties, String propertyName)
   at Microsoft.ServiceBus.Messaging.MessageSender.RetrySenderAsyncResult..ctor(MessageSender sender, TrackingContext trackingContext, IEnumerable`1 messages, Boolean fromSync, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.ServiceBus.Messaging.MessageSender.<>c__DisplayClass55_0.<BeginSend>b__0(AsyncCallback c, Object s)
   at Microsoft.ServiceBus.Messaging.OpenOnceManager.OpenOnceManagerAsyncResult`1.BeginOperation()
   
@axisc  Should the fix owned by us or track 1 SDK team?

**Comment by ramya-rao-a** [comment]
Looks like there was a PR out to fix this, but was closed due to inactivity. See https://github.com/Azure/azure-sdk-for-net/pull/18503

@JoshLove-msft, Can you check if this is a problem in the newer Azure.Messaging.ServiceBus package as well?
