### ISSUE TITLE
Microsoft.Azure.ServiceBus 4.1.2 and 5.0.0 MessageReceiver.RenewLockAsync stops working after 5 minutes

### ISSUE THREAD

**Issue by josh-endries** [Azure/azure-sdk-for-net#15364]
I am having trouble with processing a long-running task wherein it seems like RenewLockAsync stops working or doesn't have any effect, or at least not the effect I was expecting.

This is how I create the MessageReceiver:

    new Microsoft.Azure.ServiceBus.Core.MessageReceiver(
        config.ServiceBusConnectionString,
        config.QueueName,
        Microsoft.Azure.ServiceBus.ReceiveMode.PeekLock,
        Microsoft.Azure.ServiceBus.RetryPolicy.Default,
        0 // prefetchCount
    )

Messages are received one at a time via:

    await MessageReceiver.ReceiveAsync(maxMessageCount, operationTimeout); // maxMessageCount is 1

Message locks are renewed via:

    await MessageReceiver.RenewLockAsync(message.LockToken);

Message locks are renewed in a timer every 1/4th of the lock duration, so for a 5 minute expiration, messages are renewed about every 1:15, but this is what I am seeing:

    [2020-09-23 12:49:19 +00:00 0.00:04:28.325 00:00:00.000] Message lock renewal timer started with interval 00:01:14.9950000 for message "15251574d1904c3484b2ce336f11e8e8".
    [2020-09-23 12:50:34 +00:00 0.00:05:44.162 00:00:00.969] Starting lock token renewal for message "15251574d1904c3484b2ce336f11e8e8".
    [2020-09-23 12:50:34 +00:00 0.00:05:44.171 00:00:00.007] Finished lock token renewal for message "15251574d1904c3484b2ce336f11e8e8".
    [2020-09-23 12:51:50 +00:00 0.00:06:59.273 00:00:00.017] Starting lock token renewal for message "15251574d1904c3484b2ce336f11e8e8".
    [2020-09-23 12:51:50 +00:00 0.00:06:59.275 00:00:00.002] Finished lock token renewal for message "15251574d1904c3484b2ce336f11e8e8".
    [2020-09-23 12:53:05 +00:00 0.00:08:14.271 00:00:03.287] Starting lock token renewal for message "15251574d1904c3484b2ce336f11e8e8".
    [2020-09-23 12:53:05 +00:00 0.00:08:14.274 00:00:00.002] Finished lock token renewal for message "15251574d1904c3484b2ce336f11e8e8".
    [2020-09-23 12:54:20 +00:00 0.00:09:29.385 00:00:00.039] Starting lock token renewal for message "15251574d1904c3484b2ce336f11e8e8".
    [2020-09-23 12:54:20 +00:00 0.00:09:29.668 00:00:00.126] Exception while renewing lock for message "15251574d1904c3484b2ce336f11e8e8"; requesting cancellation.
    Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue.

There's no reason this lock should have expired, AFAIK. It is just over 5 minutes from when it was received, however, which is the max lock duration set on the queue, so this is what I expect is the problem. My expectation was that if I were renewing the lock every minute, it wouldn't expire, unless I failed to renew the lock 4+ times in a row, which doesn't happen here. Is there some 5 minute cut-off that I'm not aware of?

I haven't found any documentation around this really. I've found references to AutoRenewDuration or MaxAutoRenewDuration or similar settings but I haven't found those in MessageReceiver or Message so I'm not sure if I can change those. They seem to only apply to (or be available when) registering a handler.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by jsquire** [comment]
//fyi: @JoshLove-msft, @MiYanni

**Comment by josh-endries** [comment]
A linqpad script seems to work beyond 5 minutes in a test environment. I would expect a networking issue while making the renewal request to result in a different error/exception, but maybe that's an invalid assumption. Other than that, I don't understand how the lock would disappear, especially almost exactly at 5 minutes. The message was still in the queue, so it wasn't removed (we ended up getting a dupe because of this). Very strange.

**Comment by josh-endries** [comment]
Looked into another one. This time, it did renew beyond 5 minutes successfully (allegedly), but was unable to complete after processing.

```
[2020-09-29 17:57:01 +00:00 0.00:01:00.487 00:00:00.000] Message lock renewal timer started with interval 00:01:14.1060000 for message "6221d43b6ecb4df886053af881ece696".
[2020-09-29 17:58:15 +00:00 0.00:02:14.598 00:00:20.138] Starting lock token renewal for message "6221d43b6ecb4df886053af881ece696" with lock token 5b308fd1-8b96-4c82-aacb-87c7f33300c6 and expiration 9/29/2020 6:01:57 PM +00:00.
[2020-09-29 17:58:15 +00:00 0.00:02:14.783 00:00:00.185] Finished lock token renewal for message "6221d43b6ecb4df886053af881ece696" with lock token 5b308fd1-8b96-4c82-aacb-87c7f33300c6 and new expiration 9/29/2020 6:03:15 PM +00:00.
...
[2020-09-29 18:04:26 +00:00 0.00:08:25.477 00:00:00.699] Starting lock token renewal for message "6221d43b6ecb4df886053af881ece696" with lock token 5b308fd1-8b96-4c82-aacb-87c7f33300c6 and expiration 9/29/2020 6:01:57 PM +00:00.
[2020-09-29 18:04:26 +00:00 0.00:08:25.481 00:00:00.003] Finished lock token renewal for message "6221d43b6ecb4df886053af881ece696" with lock token 5b308fd1-8b96-4c82-aacb-87c7f33300c6 and new expiration 9/29/2020 6:09:26 PM +00:00.
...
[2020-09-29 18:04:37 +00:00 0.00:08:36.256 00:00:00.038] Caught a "Microsoft.Azure.ServiceBus.MessageLockLostException" exception while completing message "6221d43b6ecb4df886053af881ece696" (attempt 1/5): The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.
```

The original expiration on the message never changes, I'm assuming that should be expected, but the date returned by `RenewAsync` does progress, which makes me think it should not expire.

The app only ever has one `MessageReceiver` instance, which receives messages in a loop, and is passed in to a new message processor for each message in the loop, so I am pretty sure that it's not a cross-instance problem.

At this point, I am working on updating/testing v5 of the library to see if that makes a difference, but based on the release notes I don't expect it to...

**Comment by josh-endries** [comment]
Nope, happened again with 5.0.0...

```
[2020-10-13 03:58:04 +00:00 0.00:00:42.137 00:00:00.008] Message lock renewal timer started with interval 00:01:14.9860000 for message "ddb425a91f2e429b8a2249f4a4902436".
...
[2020-10-13 04:08:04 +00:00 0.00:10:42.580 00:00:00.008] Finished lock token renewal for message "ddb425a91f2e429b8a2249f4a4902436" with lock token 8268d48b-daf6-475a-a497-f2c69958008d and new expiration 10/13/2020 4:13:04 AM +00:00.
...
[2020-10-13 04:08:25 +00:00 0.00:11:03.391 00:00:00.086] Caught a "Microsoft.Azure.ServiceBus.MessageLockLostException" exception while completing message "ddb425a91f2e429b8a2249f4a4902436" (attempt 1/5): The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.
Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance.
```

This one also gets beyond 5 minutes. I have no idea why the lock just up and vanishes before the date returned by the most recent `RenewAsync`. The same receiver instance is getting both calls.

**Comment by josh-endries** [comment]
Well I converted the app to using message handling, hoping that the internal renewal would work better than ours with the message processor, but that isn't reliable either...
```
fail: [2020-11-20 12:12:09 +00:00 0.01:08:01.827 00:03:15.211] Caught a MessageLockLostException exception while processing message: Microsoft.Azure.ServiceBus.ExceptionReceivedEventArgs
Microsoft.Azure.ServiceBus.MessageLockLostException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. [...], Timestamp:2020-11-20T12:12:09
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<OnRenewLockAsync>d__95.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass75_0.<<RenewLockAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Azure.ServiceBus.RetryPolicy.<RunOperation>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<RenewLockAsync>d__75.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<RenewLockAsync>d__74.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.ServiceBus.MessageReceivePump.<RenewMessageLockTask>d__18.MoveNext()
```

Message processing continued (including network requests) and at the end it broke again trying to complete the message.

I feel like there is something wrong on the server side, or by design, or maybe it missed some renewals. I don't get any other information from the message handler like I did with my own renewals.

**Comment by ramya-rao-a** [comment]
Hey @josh-endries 

Apologies for the lack of response here

This issue is now about a year old, I doubt you are seeing the same problems now. Therefore, I will be closing this issue. If you are still having problems, please open a new issue and we will do our best to help you. If you have an Azure support plan, you can also open an Azure support ticket.

Please note, a newer package Azure.Messaging.ServiceBus is available as of November 2020. While the older Microsoft.Azure.ServiceBus package will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [migration guide](https://aka.ms/azsdk/net/migrate/sb) for more details.
