### ISSUE TITLE
[BUG] Azure.Storage.Queues SDK fails with custom hostname in the connection string

### ISSUE THREAD

**Issue by PiotrNSmartlogic** [Azure/azure-sdk-for-net#15403]
**Describe the bug**
The Url used by the library ends up being `http://azurite:10001/queuename` instead of `http://azurite:10001/devstoreaccount1/queuename`
It's a problem analogous to the one described here [https://github.com/Azure/azure-sdk-for-net/issues/9404](url). It was already fixed for the blobs but not for the queues.

**Expected behavior**
Correctly interpret connection string when using custom host name.

**Actual behavior (include Exception or Stack Trace)**
```
{System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Azure.Storage.Queues.QueueRestClient.Messages.DequeueAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Queues.QueueRestClient.Messages.DequeueAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, Nullable`1 numberOfMessages, Nullable`1 visibilitytimeout, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Queues.QueueClient.ReceiveMessagesInternal(Nullable`1 maxMessages, Nullable`1 visibilityTimeout, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Queues.QueueClient.ReceiveMessagesAsync(Nullable`1 maxMessages, Nullable`1 visibilityTimeout, CancellationToken cancellationToken)
```

**To Reproduce**
```
var connectionString = "UseDevelopmentStorage=true;DevelopmentStorageProxyUri=http://azurite/;"
var queueClient = new QueueClient(connectionString, queueName);
queueClient.CreateIfNotExists();
```

**Environment:**
Azure.Storage.Queues 12.4.2
.NET Core 3.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

Thanks for bringing up this issue. You're correct looks like the PR fixed it for blobs, but not for queues or files.

We will look to reference this PR https://github.com/Azure/azure-sdk-for-net/pull/13124 for the fix.

I will label this issue as a bug and we will look to getting this in when we can.

**Comment by wcabus** [comment]
Just got here because of that PR #13124 as well, we're running Azurite inside a Kubernetes cluster on our dev machines on a different port (9100), which causes the same problem, not finding container references for blobs as the BlobUriBuilder is not able to find the AccountName in the uri. 

Of course, we can fix our local situation by using one of the ports listed in the range mentioned at https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobUriBuilder.cs#L41 , but perhaps another solution could be found as well, for example if the AccountName was set before, to attempt to find the AccountName in the Uri during parsing?

**Comment by amnguye** [comment]
@wcabus will look into including ports that are different from the currently listed port. Could you create a new issue about this port issue as this is separate bug from this bug? Thanks.
