### ISSUE TITLE
[QUERY] Error in Configuration Builder 'AzureKeyVault'::GetAllValues()

### ISSUE THREAD

**Issue by FirojAktarulIslam** [Azure/azure-sdk-for-net#15536]
**Query/Question**
I am getting following error while app pool is recycled:
An error occurred creating the configuration section handler for connectionStrings: Error in Configuration Builder 'AzureKeyVault'::GetAllValues() (web.config line 24) Error in Configuration Builder 'AzureKeyVault'::GetAllValues() Object reference not set to an instance of an object. 

I followed https://github.com/Azure/azure-sdk-for-net/commit/3a643510066880ee8bffe38c55662e29a6ea6ea4
mentioned in https://github.com/Azure/azure-sdk-for-net/issues/10657. However still same error.

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Secrets  version 4.1.0.0
 - Hosting platform or OS : Windows Server 2012 R2, IIS Version 8.5, 
 - .NET runtime version : v4.7.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
//cc: @pakrym.

**Comment by heaths** [comment]
We don't have any code called `AzureKeyVault` in Azure.Security.KeyVault.Secrets. Can you please list all the packages (at least Azure.* or Microsoft.*) that you are referencing?

**Comment by FirojAktarulIslam** [comment]
Here is the packages that we are using:
```
<?xml version="1.0" encoding="utf-8"?>
<packages>
  <package id="Antlr" version="3.4.1.9004" targetFramework="net472" />
  <package id="Aspose.Words" version="15.3.0" targetFramework="net472" />
  <package id="AutoMapper" version="5.1.1" targetFramework="net472" />
  <package id="Azure.Core" version="1.4.1" targetFramework="net472" />
  <package id="Azure.Data.AppConfiguration" version="1.0.0" targetFramework="net472" />
  <package id="Azure.Identity" version="1.2.3" targetFramework="net472" />
  <package id="Azure.Security.KeyVault.Secrets" version="4.1.0" targetFramework="net472" />
  <package id="bootstrap" version="3.0.0" targetFramework="net472" />
  <package id="CommonServiceLocator" version="1.3" targetFramework="net472" />
  <package id="Dapper" version="1.42" targetFramework="net472" />
  <package id="EntityFramework" version="6.1.3" targetFramework="net472" />
  <package id="EO.Pdf" version="5.0.87" targetFramework="net472" />
  <package id="FileCache" version="1.4.0" targetFramework="net472" />
  <package id="FluentValidation" version="6.2.1.0" targetFramework="net472" />
  <package id="GreenPipes" version="2.1.2" targetFramework="net472" />  
  <package id="IdentityModel" version="1.9.2" targetFramework="net472" />
  <package id="IdentityServer3.AccessTokenValidation" version="2.15.1" targetFramework="net472" />
  <package id="jose-jwt" version="2.0.1" targetFramework="net472" />
  <package id="jQuery" version="1.10.2" targetFramework="net472" />
  <package id="jQuery.Validation" version="1.11.1" targetFramework="net472" />
  <package id="log4net" version="2.0.8" targetFramework="net472" />
  <package id="MassTransit" version="5.1.5" targetFramework="net472" />
  <package id="MassTransit.Log4Net" version="5.1.5" targetFramework="net472" />
  <package id="MassTransit.RabbitMQ" version="5.1.5" targetFramework="net472" />
  <package id="MassTransit.SimpleInjector" version="3.5.7" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights" version="2.10.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.Agent.Intercept" version="2.4.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.DependencyCollector" version="2.10.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.Log4NetAppender" version="2.10.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.PerfCounterCollector" version="2.10.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.SnapshotCollector" version="1.3.4" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.Web" version="2.10.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.WindowsServer" version="2.10.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationInsights.WindowsServer.TelemetryChannel" version="2.10.0" targetFramework="net472" />
  <package id="Microsoft.ApplicationServer.Caching.Client" version="1.0.4657.2" targetFramework="net472" />
  <package id="Microsoft.AspNet.Cors" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.Identity.Core" version="2.2.1" targetFramework="net472" />
  <package id="Microsoft.AspNet.Identity.EntityFramework" version="2.2.1" targetFramework="net472" />
  <package id="Microsoft.AspNet.Identity.Owin" version="2.2.1" targetFramework="net472" />
  <package id="Microsoft.AspNet.Mvc" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.Razor" version="3.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.TelemetryCorrelation" version="1.0.5" targetFramework="net472" />
  <package id="Microsoft.AspNet.Web.Optimization" version="1.1.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Client" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Core" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Cors" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.HelpPage" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.Owin" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebApi.WebHost" version="5.2.3" targetFramework="net472" />
  <package id="Microsoft.AspNet.WebPages" version="3.2.3" targetFramework="net472" />
  <package id="Microsoft.Azure.KeyVault.Core" version="1.0.0" targetFramework="net472" />
  <package id="Microsoft.Bcl.AsyncInterfaces" version="1.0.0" targetFramework="net472" />
  <package id="Microsoft.Configuration.ConfigurationBuilders.Azure" version="2.0.0" targetFramework="net472" />
  <package id="Microsoft.Configuration.ConfigurationBuilders.AzureAppConfiguration" version="1.0.0" targetFramework="net472" />
  <package id="Microsoft.Configuration.ConfigurationBuilders.Base" version="2.0.0" targetFramework="net472" />
  <package id="Microsoft.Data.Edm" version="5.6.3" targetFramework="net472" />
  <package id="Microsoft.Data.OData" version="5.6.3" targetFramework="net472" />
  <package id="Microsoft.Diagnostics.Tracing.EventSource.Redist" version="1.1.28" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Configuration.Binder" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.DependencyInjection.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Logging" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Logging.Abstractions" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Logging.Debug" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Options" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Extensions.Primitives" version="2.2.0" targetFramework="net472" />
  <package id="Microsoft.Identity.Client" version="4.16.1" targetFramework="net472" />
  <package id="Microsoft.Identity.Client.Extensions.Msal" version="2.12.0" targetFramework="net472" />
  <package id="Microsoft.IdentityModel.Protocol.Extensions" version="1.0.2.206221351" targetFramework="net472" />
  <package id="Microsoft.jQuery.Unobtrusive.Validation" version="3.2.3" targetFramework="net472" />
  <package id="Microsoft.Net.Http" version="2.0.20710.0" targetFramework="net472" />
  <package id="Microsoft.Owin" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Cors" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Host.SystemWeb" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.Cookies" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.Facebook" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.Google" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.Jwt" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.MicrosoftAccount" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.OAuth" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Owin.Security.Twitter" version="3.0.1" targetFramework="net472" />
  <package id="Microsoft.Web.Infrastructure" version="1.0.0.0" targetFramework="net472" />
  <package id="Modernizr" version="2.6.2" targetFramework="net472" />
  <package id="NewId" version="3.0.2" targetFramework="net472" />
  <package id="Newtonsoft.Json" version="11.0.2" targetFramework="net472" />
  <package id="Newtonsoft.Json.Bson" version="1.0.1" targetFramework="net472" />
  <package id="Novell.Directory.Ldap.NETStandard" version="3.2.0" targetFramework="net472" />
  <package id="Owin" version="1.0" targetFramework="net472" />
  <package id="Pipelines.Sockets.Unofficial" version="1.0.7" targetFramework="net472" />
  <package id="RabbitMQ.Client" version="5.2.0" targetFramework="net472" />
  <package id="Respond" version="1.2.0" targetFramework="net472" />
  <package id="RestSharp" version="105.0.1" targetFramework="net472" />
  <package id="SimpleInjector" version="3.3.2" targetFramework="net472" />
  <package id="SimpleInjector.Extensions.ExecutionContextScoping" version="3.3.2" targetFramework="net472" />
  <package id="SimpleInjector.Integration.Web" version="3.3.2" targetFramework="net472" />
  <package id="SimpleInjector.Integration.Web.Mvc" version="3.3.2" targetFramework="net472" />
  <package id="SimpleInjector.Integration.WebApi" version="3.3.2" targetFramework="net472" />
  <package id="StackExchange.Redis" version="2.0.519" targetFramework="net472" />
  <package id="Swashbuckle" version="5.6.0" targetFramework="net472" />
  <package id="Swashbuckle.Core" version="5.6.0" targetFramework="net472" />
  <package id="System.Buffers" version="4.5.0" targetFramework="net472" />
  <package id="System.ComponentModel.Annotations" version="4.5.0" targetFramework="net472" />
  <package id="System.Diagnostics.DiagnosticSource" version="4.6.0" targetFramework="net472" />
  <package id="System.Diagnostics.PerformanceCounter" version="4.5.0" targetFramework="net472" />
  <package id="System.IdentityModel.Tokens.Jwt" version="4.0.2.206221351" targetFramework="net472" />
  <package id="System.IO.Compression" version="4.3.0" targetFramework="net472" />
  <package id="System.IO.Pipelines" version="4.5.1" targetFramework="net472" />
  <package id="System.Memory" version="4.5.3" targetFramework="net472" />
  <package id="System.Numerics.Vectors" version="4.5.0" targetFramework="net472" />
  <package id="System.Reflection.Emit.Lightweight" version="4.3.0" targetFramework="net472" />
  <package id="System.Runtime.CompilerServices.Unsafe" version="4.6.0" targetFramework="net472" />
  <package id="System.Security.Cryptography.ProtectedData" version="4.5.0" targetFramework="net472" />
  <package id="System.Spatial" version="5.6.3" targetFramework="net472" />
  <package id="System.Text.Encodings.Web" version="4.6.0" targetFramework="net472" />
  <package id="System.Text.Json" version="4.6.0" targetFramework="net472" />
  <package id="System.Threading.Channels" version="4.5.0" targetFramework="net472" />
  <package id="System.Threading.Tasks.Extensions" version="4.5.2" targetFramework="net472" />
  <package id="System.ValueTuple" version="4.5.0" targetFramework="net472" />
  <package id="WebActivatorEx" version="2.0" targetFramework="net472" />
  <package id="WebGrease" version="1.5.2" targetFramework="net472" />
  <package id="WindowsAzure.Storage" version="9.3.3" targetFramework="net472" />
</packages> 
```

**Comment by FirojAktarulIslam** [comment]
Error stack trace :
```
2020-09-30 10:49:08,484 [15] ERROR (null) (null) > - System.Configuration.ConfigurationErrorsException: An error occurred creating the configuration section handler for connectionStrings: Error in Configuration Builder 'AzureKeyVault'::GetAllValues() (Consumers.exe.Config line 19) ---> System.Exception: Error in Configuration Builder 'AzureKeyVault'::GetAllValues() ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder.GetAllValues(String prefix)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureGreedyInitialized()
   --- End of inner exception stack trace ---
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureGreedyInitialized()
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.ProcessConfigurationSection(ConfigurationSection configSection)
   at System.Configuration.Internal.InternalConfigHost.System.Configuration.Internal.IInternalConfigurationBuilderHost.ProcessConfigurationSection(ConfigurationSection configSection, ConfigurationBuilder builder)
   at System.Configuration.Internal.DelegatingConfigHost.ProcessConfigurationSection(ConfigurationSection configSection, ConfigurationBuilder builder)
   at System.Configuration.BaseConfigurationRecord.CallHostProcessConfigurationSection(ConfigurationSection configSection, ConfigurationBuilder configBuilder)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.CreateSectionImpl(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.CreateSectionWithRestrictedPermissions(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   at System.Configuration.RuntimeConfigurationRecord.CreateSection(Boolean inputIsTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   at System.Configuration.BaseConfigurationRecord.CallCreateSection(Boolean inputIsTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_ConnectionStrings()
```

**Comment by heaths** [comment]
What's the full stack trace? You also reference an issue with concurrency that was fixed, but this is throwing a `NullReferenceException`. From that list I still can't tell exactly which package is throwing the exception.

**Comment by FirojAktarulIslam** [comment]
Stack Trace:
```
2020-10-01 02:22:03,444 [35] ERROR 07a2b44a-2b69-4560-bedf-ba461933a2d4 (null) > - ExceptionMessage: An error occurred creating the configuration section handler for connectionStrings: Error in Configuration Builder 'AzureKeyVault'::GetAllValues() (web.config line 24) CustomException: An error occurred creating the configuration section handler for connectionStrings: Error in Configuration Builder 'AzureKeyVault'::GetAllValues() (web.config line 24)
System.Configuration.ConfigurationErrorsException: An error occurred creating the configuration section handler for connectionStrings: Error in Configuration Builder 'AzureKeyVault'::GetAllValues() (web.config line 24) ---> System.Exception: Error in Configuration Builder 'AzureKeyVault'::GetAllValues() ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder.GetAllValues(String prefix)
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureGreedyInitialized()
   --- End of inner exception stack trace ---
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.EnsureGreedyInitialized()
   at Microsoft.Configuration.ConfigurationBuilders.KeyValueConfigBuilder.ProcessConfigurationSection(ConfigurationSection configSection)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.CreateSectionImpl(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   at System.Configuration.RuntimeConfigurationRecord.RuntimeConfigurationFactory.CreateSectionWithRestrictedPermissions(RuntimeConfigurationRecord configRecord, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   at System.Configuration.RuntimeConfigurationRecord.CreateSection(Boolean inputIsTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   at System.Configuration.BaseConfigurationRecord.CallCreateSection(Boolean inputIsTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, SectionInput sectionInput, Object parentConfig, ConfigXmlReader reader)
   --- End of inner exception stack trace ---
   at System.Configuration.BaseConfigurationRecord.EvaluateOne(String[] keys, SectionInput input, Boolean isTrusted, FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult)
   at System.Configuration.BaseConfigurationRecord.Evaluate(FactoryRecord factoryRecord, SectionRecord sectionRecord, Object parentResult, Boolean getLkg, Boolean getRuntimeObject, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.get_ConnectionStrings()
```
 
 We are seeing the exception coming approx 2 times for each app pool recycle. After that application is able to get KeyVault data.
We are using following configbuilder to read KeyVault data:
	 
<add name="AzureKeyVault" mode="Greedy" vaultName="[VaultName]" type="Microsoft.Configuration.ConfigurationBuilders.AzureKeyVaultConfigBuilder, Microsoft.Configuration.ConfigurationBuilders.Azure, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" />

**Comment by heaths** [comment]
Looking at [the code](https://github.com/aspnet/MicrosoftConfigurationBuilders/blob/v2.0/src/Azure/AzureKeyVaultConfigBuilder.cs#L127-L150), I don't see any obvious reason why a `NullReferenceException` would be thrown. Are you able to get a memory dump or [trace events](https://heaths.dev/azure/2020/02/04/trace-azure-sdk-for-net.html) for the Azure-Core ETW provider (AppInsights, Application Monitor, and others way in Azure or standalone web server can trace ETW sources) and create a bug in https://developercommunity.visualstudio.com/spaces/61/index.html? If you send me the URL, only we can see the attachments. ASP.NET can also take a look since they own that package. Whatever is happening, a `NullReferenceException` should not be thrown.

**Comment by FirojAktarulIslam** [comment]
We are moving to azure app service where AzureKeyVault works. Hence closing the issue.
