### ISSUE TITLE
[BUG] EventProcessorClient - Multiple exceptions causing monitoring to stop on most partitions

### ISSUE THREAD

**Issue by TarekAljabban** [Azure/azure-sdk-for-net#15844]
I'm using `EventProcessorClient` in my service to monitor multiple EventHubs.
Occasionally, `ProcessErrorAsync` is invoked with different types of exceptions. However, these exceptions seemed transient and did not impact the monitoring of EventHubs.

Then one incident happened when a spike of calls to `ProcessErrorAsync` happened with different exceptions. This time monitoring stopped almost completely (most partitions except for few) on the EventHubs of one region (EUS). It seems there was some network issues between my service (in WUS2) and the EventHubs in EUS, so a temporary stoppage of monitoring is expected, but what is not expected the monitoring processors not recovering.

**Exceptions:**
Sharing the call stack of one instance of each exception that occurred when the monitoring stopped:

Exception 1:
```
System.Net.Sockets.SocketException (110): Operation timed out
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, EventHubsTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventPosition, TimeSpan timeout, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.CreateConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventStartingPosition, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c__DisplayClass61_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext()
```

Exception 2 (slightly different call stack from exception 1):
```
System.Net.Sockets.SocketException (110): Operation timed out
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, EventHubsTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventPosition, TimeSpan timeout, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.CreateConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventStartingPosition, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c__DisplayClass61_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext()
```

Exception 3:
```
System.TimeoutException: The operation did not complete within the allocated time 00:00:30 for object tls92030.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.HandleTransportOpened(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.OnTransportOpened(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, EventHubsTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventPosition, TimeSpan timeout, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.CreateConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventStartingPosition, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c__DisplayClass61_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext(),
```

Exception 4:
```
System.TimeoutException: The operation did not complete within the allocated time 00:00:29.9999773 for object session94909.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.EndCreateCbsLink(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateReceivingLinkAsync(AmqpConnection connection, Uri endpoint, EventPosition eventPosition, TimeSpan timeout, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventPosition, TimeSpan timeout, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.CreateConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventStartingPosition, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c__DisplayClass61_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext()
```

Exception 5:
```
System.TimeoutException: The operation did not complete within the allocated time 00:00:00 for object out-connection94300.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, EventHubsTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventPosition, TimeSpan timeout, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.CreateConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventStartingPosition, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c__DisplayClass61_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext(),
```

Exception 6:
```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'sasl84848'.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.HandleTransportOpened(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.OnTransportOpenCompete(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, EventHubsTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventPosition, TimeSpan timeout, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.CreateConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventStartingPosition, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.CreateConsumerLinkAsync(String consumerGroup, String partitionId, EventPosition eventStartingPosition, UInt32 prefetchCount, Nullable`1 ownerLevel, Boolean trackLastEnqueuedEventProperties, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c__DisplayClass61_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c__DisplayClass61_0.<<CreatePartitionProcessor>g__performProcessing|1>d.MoveNext(),
```

Exception 7:
**previous exceptions happened on specific partition. This was the only exception that is not partition specific** 
```
System.InvalidOperationException: A link to connection '19641461' $management node has already been opened.
   at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConnection.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConnection.GetPartitionIdsAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.RunProcessingAsync(CancellationToken cancellationToken)
```

**Environment:**
 - Assembly Azure.Messaging.EventHubs, Version=5.1.0
 - Service running in Azure VMSS.

**Comment by jsquire** [comment]
Hi @TarekAljabban.  Thanks for reaching out and we regret that you're experiencing difficulties.  The exceptions that you've shared indicate that your host environment was experiencing network failures that are causing the event processor to lose connection to the Event Hubs service, fail when attempting to recover, and not receive notification of link status when updated by the service.  

The processor will continue to attempt recovery for as long as it is running, but its ability to do so successfully is subject to the health of the underlying network and the ability of the host process to interact with it.  The processor would detect that it was unable to make forward progress and would surrender ownership of the partitions, which would signal other processors configured to use the same storage location, consumer group, and Event Hub instance that they should take ownership.   

It is difficult to do more than speculate with the information available, but in this case it would seem that the network problems continued to impact the host process after the outage and the processor could not reestablish communication.   The best approach for correcting this type issue would be to consider restarting the host process.

**Comment by TarekAljabban** [comment]
Thanks @jsquire.
I'll keep monitoring my service in case such a problem reoccured and see if I can provide better context then.
