### ISSUE TITLE
[Flaky test] ChainedTokenCredential_UseAzureCliCredential_ParallelCalls

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#16151]
```

Error message
Azure.Identity.AuthenticationFailedException : The ChainedTokenCredential failed due to an unhandled exception: Azure CLI authentication timed out.
----> Azure.Identity.AuthenticationFailedException : Azure CLI authentication timed out.


Stack trace
   at Azure.Identity.ChainedTokenCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/ChainedTokenCredential.cs:line 97
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
   at Azure.Identity.ChainedTokenCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/ChainedTokenCredential.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Identity.Tests.ChainedTokenCredentialLiveTests.<>c__DisplayClass6_0.<<ChainedTokenCredential_UseAzureCliCredential_ParallelCalls>b__1>d.MoveNext() in D:\a\1\s\sdk\identity\Azure.Identity\tests\ChainedTokenCredentialLiveTests.cs:line 172
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Identity.Tests.ChainedTokenCredentialLiveTests.ChainedTokenCredential_UseAzureCliCredential_ParallelCalls() in D:\a\1\s\sdk\identity\Azure.Identity\tests\ChainedTokenCredentialLiveTests.cs:line 175
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted() in D:\a\1\s\src\NUnitFramework\framework\Internal\TaskAwaitAdapter.cs:line 95
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke) in D:\a\1\s\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 60
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 64
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0() in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 58
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\BeforeAndAfterTestCommand.cs:line 73
--AuthenticationFailedException
   at Azure.Identity.AzureCliCredential.RequestCliAccessTokenAsync(Boolean async, String[] scopes, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/AzureCliCredential.cs:line 115
   at Azure.Identity.AzureCliCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/AzureCliCredential.cs:line 89
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex) in /_/sdk/identity/Azure.Identity/src/CredentialDiagnosticScope.cs:line 46
   at Azure.Identity.AzureCliCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/AzureCliCredential.cs:line 94
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
   at Azure.Identity.AzureCliCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/AzureCliCredential.cs:line 69
   at Azure.Identity.ChainedTokenCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken) in /_/sdk/identity/Azure.Identity/src/ChainedTokenCredential.cs:line 85
```

https://dev.azure.com/azure-sdk/public/_build/results?buildId=585070&view=ms.vss-test-web.build-test-results-tab&runId=14345266&resultId=106046&paneView=debug

**Comment by pakrym** [comment]
Another failure: https://dev.azure.com/azure-sdk/public/_build/results?buildId=590791&view=ms.vss-test-web.build-test-results-tab&runId=14434472&resultId=105930&paneView=debug

**Comment by pakrym** [comment]
As well as DefaultAzureCredential_UseAzureCliCredential_ParallelCalls

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=720785&view=ms.vss-test-web.build-test-results-tab&runId=16470680&resultId=105832&paneView=debug

**Comment by pakrym** [comment]
@schaabs @christothes can this test be disabled or fixed?

**Comment by christothes** [comment]
Based on some local testing, I think the issue is that the CLI takes almost exactly 10 seconds to fetch the token and the default timeout is 10 seconds.
https://github.com/Azure/azure-sdk-for-net/blob/c8e73e1e047ad50d44570dbe33773ba86da4e521/sdk/identity/Azure.Identity/src/AzureCliCredential.cs#L30

Increasing the default timeout by a few seconds should fix it. 

@schaabs Any concerns with that?

**Comment by schaabs** [comment]
@christothes I'm not sure this is the problem as this test doesn't actually invoke the CLI but rather uses a test process.
https://github.com/Azure/azure-sdk-for-net/blob/d96810f777a4d8e4ccb46258602db8dbb02d93b6/sdk/identity/Azure.Identity/tests/ChainedTokenCredentialLiveTests.cs#L153-L158
I'm thinking this might be another deadlocking issue with our process handling. Have you been able to repro this locally using this particular test?

**Comment by christothes** [comment]
Thanks - makes sense. The test issue is definitely not related to the timeout then. However, the real timeout seems dangerously close to how long it really takes. As part of this fix, I may go ahead and bump it up anyway.
