### ISSUE TITLE
StandardError has not been redirected from Azure.Identity

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#16211]
**Describe the bug**
Getting this exception when running AzureCliCredential in container with .NET 5.0.

I have Console logging enabled with
`using var listener = AzureEventSourceListener.CreateConsoleLogger();`

I know that I'm getting a 401, but if I don't have logging enabled all I see is StandardError has not been redirected.

```
[Informational] Azure-Core: Request [fac39a0e-3bcb-4e11-bc20-ef12c81adc2c] GET https://memealyzerdevkeyvault.vault.azure.net/secrets/CosmosKey/?api-version=7.1
Accept:application/json
x-ms-client-request-id:fac39a0e-3bcb-4e11-bc20-ef12c81adc2c
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Secrets/4.1.0,(.NET 5.0.0-rc.2.20475.5; Linux 4.19.104-microsoft-standard #1 SMP Wed Feb 19 06:37:35 UTC 2020)
Content-Type:application/json
client assembly: Azure.Security.KeyVault.Secrets
[Warning] Azure-Core: Error response [fac39a0e-3bcb-4e11-bc20-ef12c81adc2c] 401 Unauthorized (00.5s)
Cache-Control:no-cache
Pragma:no-cache
WWW-Authenticate:REDACTED
x-ms-keyvault-region:westus2
x-ms-request-id:REDACTED
x-ms-keyvault-service-version:1.2.41.0
x-ms-keyvault-network-info:conn_type=Ipv4;addr=216.9.29.113;act_addr_fam=InterNetwork;
X-Powered-By:REDACTED
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Date:Fri, 23 Oct 2020 05:03:16 GMT
Content-Length:87
Content-Type:application/json; charset=utf-8
Expires:-1

[Informational] Azure-Identity: AzureCliCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: fac39a0e-3bcb-4e11-bc20-ef12c81adc2c
Unhandled exception. System.InvalidOperationException: StandardError has not been redirected.
   at System.Diagnostics.Process.get_StandardError()
   at Azure.Identity.ProcessService.ProcessWrapper.get_StandardError()
   at Azure.Identity.ProcessRunner.HandleExit()
   at Azure.Identity.ProcessRunner.<StartProcess>b__9_0(Object o, EventArgs e)
   at System.Diagnostics.Process.OnExited()
   at System.Diagnostics.Process.RaiseOnExited()
   at System.Diagnostics.Process.CompletionCallback(Object waitHandleContext, Boolean wasSignaled)
   at System.Threading._ThreadPoolWaitOrTimerCallback.WaitOrTimerCallback_Context_f(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(_ThreadPoolWaitOrTimerCallback helper, Boolean timedOut)
```

**Expected behavior**
What is the expected behavior?

Show the exception, not StandardError has not been redirected.

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

Above.

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create .NET console app
2. Use AzureCliCredential
3. Create docker container with azure cli installed.
4. run it

```
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY . .
RUN dotnet publish "Services/QueueService/QueueService.csproj" -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/runtime:5.0 AS base
RUN curl -sL https://aka.ms/InstallAzureCLIDeb | bash
WORKDIR /app
COPY --from=build /app/publish .
RUN apt-get update 
RUN apt-get install -y --no-install-recommends apt-utils 
RUN apt-get install -y curl unzip procps
RUN curl -sSL https://aka.ms/getvsdbgsh | bash /dev/stdin -v latest -l /publish/vsdbg;
ENTRYPOINT ["dotnet", "QueueService.dll"]

```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 

Azure.Identity

 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]

WSL2

 - IDE and version : [e.g. Visual Studio 16.3]

VS Code

azsdke2e

**Comment by schaabs** [comment]
It looks like we are still getting hits on this issue from our CI.
