### ISSUE TITLE
[BUG] blob length property metadata always -1 using OpenReadAsync 

### ISSUE THREAD

**Issue by HassanBadir** [Azure/azure-sdk-for-net#16260]
**Describe the bug**
We have a code that opens stream for a blob on storage to read its content (steps described below), the blob is a Json file which is sometimes empty, it appears on azure portal with 0B, and can be downloaded and opened.

we always check the blobStream.Length property to know if it's an empty blob or not for handling the file, for some reason no matter if the file empty or not the Length property is -1.

I have read at some places that the -1 is the initialized value of the property, and that FetchAttributesAsync must be called in order to update the metadata .. and I read on Microsoft docs that calling OpenReadAsync automatically calls FetchAttributesAsync, mentioned in these docs under **remarks**:

[OpenReadAsyncDocs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblob.openreadasync?view=azure-dotnet-legacy#Microsoft_Azure_Storage_Blob_CloudBlob_OpenReadAsync_System_Threading_CancellationToken_)

[FetchAttributesAsyncDocs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.storage.blob.cloudblob.fetchattributesasync?view=azure-dotnet-legacy#Microsoft_Azure_Storage_Blob_CloudBlob_FetchAttributesAsync_Microsoft_Azure_Storage_AccessCondition_Microsoft_Azure_Storage_Blob_BlobRequestOptions_Microsoft_Azure_Storage_OperationContext_System_Threading_CancellationToken_)

not sure what's happening, whether the problem is with the FetchAttributes call, or something with opening the stream, and why the Length is -1 always.

**Expected behavior**
the expected behavior is to get length = 0 for empty files and more for non empty files I believe.

**Actual behavior (include Exception or Stack Trace)**
there is no exception thrown (unless we try to read the stream if the file is empty) but its Length property is -1 as I explained above which wrong.

**To Reproduce**

we use Azure.Storage.Blobs, we create a blob client with the connection string, and return the blob stream ..

```
_blobServiceClient = new BlobServiceClient(connectionString);
blobStream = _blobServiceClient.GetBlobContainerClient(container).GetBlobClient(blobName).OpenReadAsync(cancellationToken: cancellationToken);
```

on the stream returned from OpenReadAsync we check the length .. and handle the file.
`if( blobStream.Length == 0 ) continue;`  < -- the length is -1 always

if we try to handling the blob stream on empty file we get the error : 
```
The range specified is invalid for the current size of the resource.
RequestId:73a48285-d01e-0095-0e63-ab0479000000
Time:2020-10-26T06:45:14.1563396Z
Status: 416 (The range specified is invalid for the current size of the resource.)
ErrorCode: InvalidRange

Headers:
Content-Range: bytes */0
x-ms-request-id: 73a48285-d01e-0095-0e63-ab0479000000
x-ms-client-request-id: ae5d7b84-a961-44d1-a876-28ca2a3cec50
x-ms-version: 2019-12-12
x-ms-error-code: InvalidRange
Content-Length: 249
Content-Type: application/xml
Date: Mon, 26 Oct 2020 06:45:13 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
```

this is the Stack Trace
```
at Azure.Storage.Blobs.BlobRestClient.Blob.DownloadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.<DownloadAsync>d__0.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StartDownloadAsync>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadInternal>d__51.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<<OpenReadInternal>b__70_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.LazyLoadingReadOnlyStream`2.<DownloadInternal>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.LazyLoadingReadOnlyStream`2.<ReadInternal>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.LazyLoadingReadOnlyStream`2.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.StreamReader.ReadBuffer()
   at System.IO.StreamReader.ReadLine()
```
.... 

**Environment:**
 - Azure.Storage.Blobs [12.5.1]
- Visual Studio 2019 [16.7.6]
- Windows 10, .NET

**Comment by JimSuplizio** [comment]
Hi @HassanBadir, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
