### ISSUE TITLE
ETag type should have an associated JsonConverted so it can be used with JsonSerializer

### ISSUE THREAD

**Issue by drwill-ms** [Azure/azure-sdk-for-net#16272]
Requested by Azure.DigitalTwins.Core.
 
We were encouraged to use the Azure.Core ETag type for our entity types. Now with the new weak ETag support, we tried to give it a shot. The problem is with client methods that return a <T> that has an ETag property, the ObjectSerializer can't deserialize the response. Here's an example call stack:

```
Could not create digital twin 'BuildingTwin' due to System.Text.Json.JsonException: The JSON value could not be converted to Azure.ETag. Path: $.$etag | LineNumber: 0 | BytePositionInLine: 76.
   at System.Text.Json.ThrowHelper.ThrowJsonException_DeserializeUnableToConvertValue(Type propertyType)
   at System.Text.Json.JsonPropertyInfoNotNullable`4.OnRead(ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonPropertyInfo.Read(JsonTokenType tokenType, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.JsonSerializer.ReadCore(JsonSerializerOptions options, Utf8JsonReader& reader, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadCore(JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& readStack)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Azure.Core.Serialization.JsonObjectSerializer.DeserializeAsync(Stream stream, Type returnType, CancellationToken cancellationToken) in C:\code\Azure\asfn1\sdk\core\Azure.Core\src\Serialization\JsonObjectSerializer.cs:line 67
   at Azure.DigitalTwins.Core.DigitalTwinsClient.CreateDigitalTwinAsync[T](String digitalTwinId, T digitalTwin, CreateDigitalTwinOptions options, CancellationToken cancellationToken) in C:\code\Azure\asfn1\sdk\digitaltwins\Azure.DigitalTwins.Core\src\DigitalTwinsClient.cs:line 245
   at Azure.DigitalTwins.Core.Samples.DigitalTwinsLifecycleSamples.CreateAllTwinsAsync() in C:\code\Azure\asfn1\sdk\digitaltwins\Azure.DigitalTwins.Core\samples\DigitalTwinsClientSample\DigitalTwinsLifecycleSamples.cs:line 256
```

**Comment by tg-msft** [comment]
We should also add a converter for Newtonsoft in our support package.

**Comment by tg-msft** [comment]
And please remove the DigitalTwins temporary converter when we add an official STJ converter.  It won't be breaking because STJ binds tighter to properties than types when resolving converters.  See PR #16439 for specifics.
