### ISSUE TITLE
[Flaky test] FailingAccessTokenBackgroundRefreshProducesEvents

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#16310]
```
Error message
System.InvalidOperationException : Sequence contains no matching element


Stack trace
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Azure.Core.TestFramework.TestEventListener.SingleEventById(Int32 id, Func`2 filter) in D:\a\1\s\sdk\core\Azure.Core.TestFramework\src\TestEventListener.cs:line 32
   at Azure.Core.Tests.EventSourceTests.<FailingAccessTokenBackgroundRefreshProducesEvents>d__24.MoveNext() in D:\a\1\s\sdk\core\Azure.Core\tests\EventSourceTests.cs:line 195
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaitable)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

```

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=599722&view=ms.vss-test-web.build-test-results-tab&runId=14577582&resultId=100797&paneView=debug

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=673625&view=ms.vss-test-web.build-test-results-tab&runId=15785620&resultId=101088&paneView=debug

**Comment by christothes** [comment]
this hasn't failed in a long time
