### ISSUE TITLE
[Kusto/ADX] Database principal assignment fails constantly if tried too early after app registration is created

### ISSUE THREAD

**Issue by viktoreinarsson** [Azure/azure-sdk-for-net#16416]
My team is attempting to create ADX databases for customers onboarded to our solution. What that entails is the following:

1. Create the database
2. Create an app registration in Azure AD
3. Assign the app registration Viewer permission to the database

We have all of the logic for this in place and it works. The only problem that we have is that if we attempt to assign the database permission for the newly created app registration immediately after it is created then we get an error saying 

_"System.Private.CoreLib: Exception while executing function: AssignDatabasePrincipal. Microsoft.Azure.Management.Kusto: [BadRequest] Entity ID '{app-registration-guid}' of type 'AAD Application Id' was not found in AAD tenant '{tenant-id}'._

If we add a sleep for 30 seconds before calling our class that is attempting to assign the permission this works perfectly. This code resides on our OnboardingService.cs:

```csharp
Thread.Sleep(TimeSpan.FromSeconds(30)); 
await this.adxManagementService.AssignDatabasePrincipalPermissionAsync(databaseName, appRegistrationId, appRegistrationName, databasePrincipalRole, databasePrincipalType);
```

So we decided to add a retry mechanism (simple for loop with try catch) to the code where we are assigning the permission This code resides on our AdxManagementService, which has a KustoManagementClient member variable. This is along the lines of what we were attempting to do:

```csharp
for (int i = 0; i < 5; i++)
{
   try
   {
      await client.DatabasePrincipalAssignments.CreateOrUpdateAsync(this.targetAzureDataExplorer.ResourceGroupName, this.targetAzureDataExplorer.ClusterName, databaseName, principalName, databasePrincipalAssignment);
   }
   catch (Exception ex)
   {
      logger.LogInformation(ex, ex.Message);
      Thread.Sleep(TimeSpan.FromSeconds(30));
}
```

The former fix works perfectly while the second retry implementation never works. Any subsequent calls to CreateOrUpdateAsync will fail if the first one did. We thought it was likely that there was some caching going on in the KustoManagementClient so we tried wrapping all usage of it in `using(var client = new KustoManagementClient...)` but to no avail.

Can we invalidate some caching or force a clean retry somehow?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by YalinLi0312** [comment]
There is no caching in client-side. We need some more information to diagnose this issue, can you print out the http request and response in the CloudException which called Request and Response?

**Comment by viktoreinarsson** [comment]
Hi @YalinLi0312,

Sure.

Request:
```json
[JSON]
Method
Method: "POST"
RequestUri: "https://management.azure.com/subscriptions/[subscription-id-removed]/resourceGroups/[resource-group-removed]/providers/Microsoft.Kusto/clusters/[cluster-name-removed]/databases/VKARM2-Telemetry/addPrincipals?api-version=2020-06-14"
Properties
Content: "{
  "value": [
    {
      "role": "Viewer",
      "name": "VKARM2-AppRegistration",
      "type": "App",
      "appId": "[app-id-removed]"
    }
  ]
}"
Headers
x-ms-client-request-id
[0]: "7b57b82f-2129-4cc8-96be-83536c65a8d6"
Accept-Language
[0]: "en-US"
Authorization
[0]: "Bearer [a-long-bearer-token-removed]"
User-Agent
[0]: "FxVersion/4.700.20.41105"
[1]: "OSName/Windows"
[2]: "OSVersion/Microsoft.Windows.10.0.18362"
[3]: "Microsoft.Azure.Management.Kusto.KustoManagementClient/6.0.0.0"
Content-Type
[0]: "application/json; charset=utf-8"
Content-Length
[0]: "180"
```

Response:
```json
[JSON]
StatusCode: 400
ReasonPhrase: "Bad Request"
Content: "{"error":{"code":"400-BadRequest","message":"[BadRequest] Entity ID '[app-registration-id-removed]' of type 'AAD Application Id' was not found in AAD tenant '[tenant-id-removed]."}}"
Headers
Cache-Control
[0]: "no-cache"
Pragma
[0]: "no-cache"
x-ms-request-id
[0]: "caa9630c-b4fd-4b99-8580-8ee311799e6d"
Set-Cookie
[0]: "ARRAffinity=e26452b9ab4162bf874a7a557d2b3213793b954884fe2afaba6f881f8f5285d5;Path=/;HttpOnly;Secure;Domain=armrp-kustorpweu.kusto.windows.net"
[1]: "ARRAffinitySameSite=e26452b9ab4162bf874a7a557d2b3213793b954884fe2afaba6f881f8f5285d5;Path=/;HttpOnly;SameSite=None;Secure;Domain=armrp-kustorpweu.kusto.windows.net"
X-Powered-By
[0]: "ASP.NET"
x-ms-ratelimit-remaining-subscription-writes
[0]: "1196"
x-ms-correlation-request-id
[0]: "b546a54d-2746-4986-b9d5-9321ffe19395"
x-ms-routing-request-id
[0]: "FRANCESOUTH:20201102T113030Z:b546a54d-2746-4986-b9d5-9321ffe19395"
Strict-Transport-Security
[0]: "max-age=31536000; includeSubDomains"
X-Content-Type-Options
[0]: "nosniff"
Date
[0]: "Mon, 02 Nov 2020 11:30:30 GMT"
Content-Length
[0]: "206"
Content-Type
[0]: "application/json; charset=utf-8"
Expires
[0]: "-1"
```

Stack Trace:
   at Microsoft.Azure.Management.Kusto.DatabasesOperations.<AddPrincipalsWithHttpMessagesAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Kusto.DatabasesOperationsExtensions.<AddPrincipalsAsync>d__15.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at HotPathOnboardingService.Infrastructure.Services.AdxManagementService.<AssignDatabasePrincipalPermissionAsync>d__8.MoveNext() in C:\Dev\mc-dataplatform\Services\HotPathOnboardingService\HotPathOnboardingService.Infrastructure\Services\AdxManagementService.cs:line 116

I removed some values and if you are worried that there might be a typo then if I add a sleep of 30-60 seconds then everything works as expected.

**Comment by YalinLi0312** [comment]
Assigned this issue to the service team to take a look.

**Comment by markcowl** [comment]
@astauben @radennis Please take a look at this customer issue

**Comment by viktoreinarsson** [comment]
@jsquire Any update on this issue? Just moved into production and this is causing some problems. Any possible workarounds?

**Comment by astauben** [comment]
Hi @viktoreinarsson , sorry for the late response, I am from ADX team. 
May you please execute both pieces of code (the one that worked and the one that failed) and send the requests and responses again? 
I'll like to take a look on the logs from our side (we no longer have records of the one you sent before)

Thanks,
Assaf.
