### ISSUE TITLE
[Flaky tests] StopProcessingIsSafeToCallInTheErrorHandler and ReadEventsAsyncWithOptionsRespectsTheCacheEventCount 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#16653]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=607618&view=ms.vss-test-web.build-test-results-tab&runId=14716550&resultId=101267&paneView=debug 
```
Error message
The processor should be running.
Expected: Running
But was:  NotRunning


Stack trace
   at Azure.Messaging.EventHubs.Tests.EventProcessorTests.StopProcessingIsSafeToCallInTheErrorHandler(Boolean async) in /home/vsts/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Primitives/EventProcessorTests.StartStop.cs:line 906
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Azure.Messaging.EventHubs.Tests.EventProcessorTests.StopProcessingIsSafeToCallInTheErrorHandler(Boolean async)

```

cc @jsquire

**Comment by jsquire** [comment]
Also investigate:   `ReadEventsAsyncWithOptionsRespectsTheCacheEventCount`  from the run:

https://dev.azure.com/azure-sdk/public/_build/results?buildId=609487&view=ms.vss-test-web.build-test-results-tab&runId=14764332&resultId=104758&paneView=debug
