### ISSUE TITLE
[Question] Service Bus. The operation was canceled and The AMQP object receiver is aborted. Executing Action: AcceptMessageSession

### ISSUE THREAD

**Issue by Marusyk** [Azure/azure-sdk-for-net#16975]
**Describe the bug**
I'm using ServiceBus Topics with session enabled.
I created an event consumer to consume messages from different topics based on examples from [eShopOnContainers ](https://github.com/dotnet-architecture/eShopOnContainers/tree/dev/src/BuildingBlocks/EventBus)project

Actually, everything works fine but not long ago I start to get this error very often.
Could you please suggest what does it mean? 

It's hard to reproduce! Please suggest what is the reason for this error?

**Expected behavior**
No exceptions

**Actual behavior (include Exception or Stack Trace)**

Sometimes (cannot detect the reason) got many errors

> The AMQP object receiver32877 is aborted.
> Exception context for troubleshooting: - Endpoint: te-servicebus-dev.servicebus.windows.net - 
> Entity Path: remote-proxy/Subscriptions/device-consumer - 
> Executing Action: AcceptMessageSession <s:development:Devices Service/Cloud.Common.EventBus.ServiceBusConsumer>
> Microsoft.Azure.ServiceBus.ServiceBusException: The AMQP object receiver32877 is aborted.
>  ---> System.AggregateException: One or more errors occurred. (The AMQP object receiver32877 is aborted.) (The AMQP object receiver32877 is aborted.)
>  ---> System.OperationCanceledException: The AMQP object receiver32877 is aborted.
>    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
>    at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
>    --- End of inner exception stack trace ---
>  ---> (Inner Exception #1) Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: The AMQP object receiver32877 is aborted.
>  ---> System.OperationCanceledException: The AMQP object receiver32877 is aborted.
>    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
>    at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
>    --- End of inner exception stack trace ---<---
> 
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.ServiceBus.SessionClient.AcceptMessageSessionAsync(String sessionId, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.SessionReceivePump.SessionPumpTaskAsync()

also found this

> Microsoft.Azure.ServiceBus.ServiceBusException: The operation was canceled.
>  ---> System.OperationCanceledException: The operation was canceled.
>    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass84_0.<ExecuteRequestResponseAsync>b__1(IAsyncResult a)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ExecuteRequestResponseAsync(AmqpRequestMessage amqpRequestMessage)
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockAsync()
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockAsync()
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockInstrumentedAsync()
>    at Microsoft.Azure.ServiceBus.SessionReceivePump.RenewSessionLockTaskAsync(IMessageSession session, CancellationToken renewLockCancellationToken)

one more

> The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:06d96ebbcd914154a9a65d809aab397a_G1, SystemTracker:gateway7, Timestamp:2020-11-12T08:10:55. Exception context for troubleshooting: - Endpoint: XXX.servicebus.windows.net - Entity Path: device-data/Subscriptions/devices-consumer - Executing Action: AcceptMessageSession <s:development: Service/EOS.Cloud.Common.EventBus.ServiceBusConsumer>
> Microsoft.Azure.ServiceBus.ServiceBusException: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101 TrackingId:06d96ebbcd914154a9a65d809aab397a_G1, SystemTracker:gateway7, Timestamp:2020-11-12T08:10:55
>    at Microsoft.Azure.ServiceBus.SessionClient.AcceptMessageSessionAsync(String sessionId, TimeSpan operationTimeout)
>    at Microsoft.Azure.ServiceBus.SessionReceivePump.SessionPumpTaskAsync()

the last one

> Microsoft.Azure.ServiceBus.ServiceBusException: The operation was canceled.
>  ---> System.OperationCanceledException: The operation was canceled.
>    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass84_0.<ExecuteRequestResponseAsync>b__1(IAsyncResult a)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ExecuteRequestResponseAsync(AmqpRequestMessage amqpRequestMessage)
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockAsync()
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockAsync()
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockInstrumentedAsync()
>    at Microsoft.Azure.ServiceBus.SessionReceivePump.RenewSessionLockTaskAsync(IMessageSession session, CancellationToken renewLockCancellationToken)

**To Reproduce**

Created repo with source code https://github.com/Marusyk/ServiceBus
The exception throws at the line 104 https://github.com/Marusyk/ServiceBus/blob/9be4191329c8ebf4a6afd853988e9068df91d2a6/ServiceBus/Core/ServiceBus/SubscriptionClientFactory.cs#L101-L108

Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Add connection string to appsettings.json
2. Create Topic with Session enabled
3. Run app
4. Send event with proper label

**Environment:**
 - Microsoft.Azure.ServiceBus 4.1.3
 - Hosting platform or OS: docker Linux container

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by Marusyk** [comment]
> Microsoft.Azure.ServiceBus.ServiceBusException: The operation was canceled.
>  ---> System.OperationCanceledException: The operation was canceled.
>    at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.<>c__DisplayClass84_0.<ExecuteRequestResponseAsync>b__1(IAsyncResult a)
>    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
> --- End of stack trace from previous location where exception was thrown ---
>    at Microsoft.Azure.ServiceBus.Core.MessageReceiver.ExecuteRequestResponseAsync(AmqpRequestMessage amqpRequestMessage)
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockAsync()
>    --- End of inner exception stack trace ---
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockAsync()
>    at Microsoft.Azure.ServiceBus.MessageSession.OnRenewSessionLockInstrumentedAsync()
>    at Microsoft.Azure.ServiceBus.SessionReceivePump.RenewSessionLockTaskAsync(IMessageSession session, CancellationToken renewLockCancellationToken)

**Comment by Marusyk** [comment]
Can anyone help?

**Comment by axisc** [comment]
@Marusyk the exception is thrown when you try to renew the session lock. Can you confirm if 
   * There are actually messages on the queue/subscription with the session id that has been locked by the receiver?
   * Have you seen ServerBusy, TimeoutExceptions, Throttling, or LockLost exceptions around the time when you see the OperationCanceledException listed above?

**Comment by Marusyk** [comment]
Hi @axisc,
I don't renew lock by myself. My code

```
var options = new SessionHandlerOptions(ExceptionReceivedHandler)
{
    MaxConcurrentSessions = _options.MaxConcurrentCalls,
    AutoComplete = false
};
SubscriptionClient.RegisterSessionHandler(async (session, message, ct) =>
{
    if (await messageHandler(message) && !ct.IsCancellationRequested)
    {
        await session.CompleteAsync(message.SystemProperties.LockToken);
    }
}, options);
```
Where `messageHandler` is `Func<Message, Task<bool>>`

**Comment by Marusyk** [comment]
Is it ok to use session with Topics? @axisc
For the last hour, I got a lot of unknown errors
<img width="195" alt="Screenshot_1" src="https://user-images.githubusercontent.com/9221694/100244543-b91c0b00-2f3f-11eb-89cb-62c5c1b6a0f6.png">
<img width="864" alt="Screenshot_2" src="https://user-images.githubusercontent.com/9221694/100244552-bae5ce80-2f3f-11eb-849c-a1bc0f617ea9.png">

**Comment by axisc** [comment]
> How can I detect that?

Utilize the [Service Bus explorer](https://docs.microsoft.com/azure/service-bus-messaging/explorer) to see what is on the queue when you start seeing those errors.

> Is it ok to use session with Topics? @axisc

Yes you can use sessions with Topics and Subscriptions.

If you still see these issues, please create a support ticket and we can investigate on the backend.
