### ISSUE TITLE
[BUG] The system cannot find the file specified | NetworkInformationException | at System.Net.NetworkInformation.SystemIPGlobalProperties.GetFixedInfo()

### ISSUE THREAD

**Issue by firephantomassasin** [Azure/azure-sdk-for-net#17498]
### Which service(blob, file, queue, table) does this issue concern?
Azure blob storage

### Which version of the SDK was used?
11.1.7

### Which platform are you using? (ex: .NET Core 2.1)
.NET Framework 4.7.2

### What problem was encountered?

Exception Type: 
NetworkInformationException

Message: 
The system cannot find the file specified

Stack Trace: 
   at System.Net.NetworkInformation.SystemIPGlobalProperties.GetFixedInfo()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.get_FixedInfo()
   at System.Net.NetworkInformation.SystemIPGlobalProperties.get_DomainName()
   at System.Net.CookieContainer..ctor()
   at System.Net.Http.HttpClientHandler..ctor()
   at Microsoft.Azure.Storage.Auth.Protocol.StorageAuthenticationHttpHandler.<>c.<.cctor>b__12_0()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.Storage.Auth.Protocol.StorageAuthenticationHttpHandler.get_Instance()
   at Microsoft.Azure.Storage.Shared.Protocol.HttpClientFactory.<>c.<.cctor>b__5_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.Storage.Shared.Protocol.HttpClientFactory.get_Instance()
   at Microsoft.Azure.Storage.Core.Executor.Executor.<ExecuteAsync>d__1`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Storage.Blob.CloudBlockBlob.<DownloadTextAsync>d__72.MoveNext()

### How can we reproduce the problem in the simplest way?
It is happening when running in azure web app, using P1V3 (Dual core specs), only 1 server is encountering this kind of issue out of 3 servers. We are using VNET integration with WEBSITE_VNET_ROUTE_ALL = 1.

### Have you found a mitigation/solution?
None.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by firephantomassasin** [comment]
@jsquire thank you for responding and looking at my bug. This is a critical bug and its occurring always, I am not sure if there is an bug with azure web app perhaps you could also check and collaborate with azure web app team. Thank you!

**Comment by jsquire** [comment]
Hi @firephantomassasin.  In this case, I'm only acting as first-line triage, routing to the appropriate team for assistance.   The one thing that I'll note is that if you feel this is a critical issue with timing sensitivity, a GitHub issue may not be the best path for support.  Opening a formal support ticket with Azure via the portal will help bring this to the attention of the support team and opens paths for escalation.

**Comment by firephantomassasin** [comment]
@jsquire I also opened a support ticket already with Azure via the Portal as well. But I'm posting this here as well so that the engineers of the SDK could look at it as well. Looking forward to your response.

**Comment by amnguye** [comment]
Hi, I see you created the same issue here https://github.com/Azure/azure-storage-net/issues/1030. That's actually the correct place to create the issue and request feedback, since this repo contains the current and supported version of the library v12.

Marking as duplicate and closing this issue in preference to the other issue. I would encourage you to upgrade if you can to the current latest supported version v12 since v11 is deprecated. 

Please reopen or reply if there are further questions.
