### ISSUE TITLE
[Flaky test] BearerTokenAuthenticationPolicy_GatedConcurrentCallsFailed

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17504]
```

Error message
Expected: <System.InvalidOperationException: Error
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<>c__DisplayClass13_0.<BearerTokenAuthenticationPolicy_GatedConcurrentCallsFailed>b__0(TokenRequestContext r, CancellationToken c) in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 379
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.TokenCredentialStub.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 565
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(HttpMessage message, Boolean async, CancellationToken cancellationToken) in //sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 217
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, Boolean async) in //sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 110
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory1 pipeline, Boolean async) in /_/sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 61 at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory1 pipeline) in //sdk/core/Azure.Core/src/Pipeline/BearerTokenAuthenticationPolicy.cs:line 51
at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken) in //sdk/core/Azure.Core/src/Pipeline/HttpPipeline.cs:line 81
at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipeline pipeline, Action1 requestAction, Boolean bufferResponse, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 32 at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipelineTransport transport, Action1 requestAction, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 43
at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendGetRequest(HttpPipelineTransport transport, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, Uri uri, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 48
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<>c__DisplayClass13_0.<<BearerTokenAuthenticationPolicy_GatedConcurrentCallsFailed>b__1>d.MoveNext() in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 392
--- End of stack trace from previous location where exception was thrown ---
at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter1.GetResult() at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func1 invoke)
at NUnit.Framework.Assert.ThrowsAsync(IResolveConstraint expression, AsyncTestDelegate code, String message, Object[] args)>
But was:  <System.InvalidOperationException: Error
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<>c__DisplayClass13_0.<BearerTokenAuthenticationPolicy_GatedConcurrentCallsFailed>b__0(TokenRequestContext r, CancellationToken c) in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 379
at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.TokenCredentialStub.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken) in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 565
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(HttpMessage message, Boolean async, CancellationToken ca


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.BearerTokenAuthenticationPolicy_GatedConcurrentCallsFailed() in /home/vsts/work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 395
```

**Comment by AlexGhiondea** [comment]
@schaabs can you take a look here?

**Comment by pakrym** [comment]
Another failure: 
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=788273&view=ms.vss-test-web.build-test-results-tab&runId=17411538&resultId=101379&paneView=debug

**Comment by pakrym** [comment]
Hasn't been failing for a while
