### ISSUE TITLE
[BUG] BlobClient.GetProperties and BlobClient.Download not setting BlobErrorCode.InvalidUri for garbled blob name

### ISSUE THREAD

**Issue by joaomsa** [Azure/azure-sdk-for-net#17628]
**Describe the bug**

Calling `BlobClient.GetProperties` or `BlobClient.Download` for a non existent blob throws exceptions without the correct error code `BlobErrorCode.InvalidUri`

**Expected behavior**

`BlobClient.GetProperties` should throw a `RequestFailedException` with `Status` set to 400 and `ErrorCode` set to `BlobErrorCode.InvalidUri`

`BlobClient.Download` should throw a `RequestFailedException` with `Status` set to 400 and `ErrorCode` set to `BlobErrorCode.InvalidUri`

**Actual behavior (include Exception or Stack Trace)**

`BlobClient.GetProperties` throws a `RequestFailedException` with `Status` set to 400 and `ErrorCode`  `null`

```
Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Headers:
Connection: close
Content-Length: 324
Content-Type: text/html; charset=us-ascii
Date: Thu, 17 Dec 2020 18:18:19 GMT
Server: Microsoft-HTTPAPI/2.0

   at Azure.Storage.Blobs.BlobRestClient.Blob.GetPropertiesAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.<GetPropertiesAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<GetPropertiesInternal>d__104.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.GetProperties(BlobRequestConditions conditions, CancellationToken cancellationToken)
   at UserQuery.RunUserAuthoredQuery() in C:\Users\Joao Sa\AppData\Local\Temp\LINQPad5\_moomddfg\query_xnydbj.cs:line 57
```

`BlobClient.Download` throws an `XmlException`

```
System.Xml.XmlException: '"' is an unexpected token. Expecting white space. Line 1, position 50.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.DtdParserProxy.System.Xml.IDtdParserAdapter.Throw(Exception e)
   at System.Xml.DtdParser.ParseExternalId(Token idTokenType, Token declType, String& publicId, String& systemId)
   at System.Xml.DtdParser.ParseInDocumentDtd(Boolean saveInternalSubset)
   at System.Xml.DtdParser.Parse(Boolean saveInternalSubset)
   at System.Xml.DtdParser.System.Xml.IDtdParser.ParseInternalDtd(IDtdParserAdapter adapter, Boolean saveInternalSubset)
   at System.Xml.XmlTextReaderImpl.ParseDtd()
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Azure.Storage.Blobs.BlobRestClient.Blob.DownloadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Blob.<DownloadAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StartDownloadAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadInternal>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download(CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download()
   at UserQuery.RunUserAuthoredQuery() in C:\Users\Joao Sa\AppData\Local\Temp\LINQPad5\_moomddfg\query_iypurw.cs:line 57
```

**To Reproduce**

```
var connstring = "...";
var container = "existing-container";
var garbledBlobName = Encoding.UTF8.GetString(Convert.FromBase64String("77+977+9MWnvv70y77+9embvv71KaO+/vW01bgnvv70KYg=="));

try {
	new BlobClient(connstring, container, garbledBlobName).GetProperties();
} catch (Exception e) {
	e.ToString().Dump();
}


try {
	new BlobClient(connstring, container, garbledBlobName).Download();
} catch (Exception e) {
	e.ToString().Dump();
}

```

**Environment:**
 - Azure.Storage.Blobs 12.7.0
 - Windows 10 .NET Framework 4.8
 - Visual Studio 16.8.3

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi,

For the error/exception thrown when running `BlobClient.GetProperties()` the error you are getting back from the service is
```
Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)
...
```

I was also able to reproduce the same error, I've attached the full response from the storage service here.
```
HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=us-ascii
**Server: Microsoft-HTTPAPI/2.0**
Date: Thu, 24 Dec 2020 00:23:32 GMT
Connection: close
Content-Length: 324

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
```
I don't think setting the error code to a `BlobErrorCode` would be correct because then it would be confusing if the error came from Azure Storage (which it didn't, the server it's sent from is the main "Microsoft-HTTPAPI/2.0", also it would make it easier for someone to debug if its an invalid URI according to azure storage guidelines or Microsoft HTTP API guidelines). We would probably have to set it to a different set of error codes. 

I was also able to reproduce the error you got for `Download` and when I look at the response trace, I got the same response as I did for `GetProperties`. The reason why it shows a different error I believe is because it parses something different with the body.

@seanmcc-msft Should we look to improve the error handling further with being able to parse these XML bodies that don't come from the blob storage? it's looks like it's coming from the server it hits before it gets to blob storage. We don't include the "The request URL is invalid" in the error message for some reason. This information would be helpful for people to figure out what they did wrong.

**Comment by seanmcc-msft** [comment]
@amnguye, I'm not sure this is something we can fix.  The error response from non-Azure Storage sources could be almost anything, and I'm not sure how we would be able to handle that.  @kasobol-msft

**Comment by kasobol-msft** [comment]
This seems to be related https://github.com/Azure/azure-sdk-for-net/issues/19501#issuecomment-805071162

**Comment by seanmcc-msft** [comment]
[Azure.Storage.Blobs v12.9.0-beta.2](https://www.nuget.org/packages/Azure.Storage.Blobs/12.9.0-beta.2) shipped on Marth 9th.
