### ISSUE TITLE
[BUG] Storage Emulator returns 400 for Table storage POST requests with long keys

### ISSUE THREAD

**Issue by madushans** [Azure/azure-sdk-for-net#17653]
**Describe the bug**
When using storage emulator Table API, a 400 response is returned if the combined length of partition key and row key is 225 or more.

This appears to be a bug in Storage Emulator that ships with the SDK. Please let me know if this is the wrong repository. 

**Expected behavior**
No error expected. Both partition key and row key should allow up to 1KiB each, according to [docs](https://docs.microsoft.com/en-us/rest/api/storageservices/understanding-the-table-service-data-model#partitionkey-property).
Also these requests work without errors when pointed to a real Table Storage account in Azure.

**Actual behavior (include Exception or Stack Trace)**
Table Storage Emulator returns "HTTP Error 400. The request URL is invalid.".

**Although creating a new entity on the table with same values via Azure Storage Explorer against the same storage emulator table does not cause any errors.**

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

**Sample Code to reproduce:**
````
var account = CloudStorageAccount.Parse("UseDevelopmentStorage=true");
var client = account.CreateCloudTableClient();
var table = client.GetTableReference("TestTable");
table.CreateIfNotExists();

var item = new DynamicTableEntity(
                partitionKey: "thisis223characterslongLoremIpsumissimplydummytextoftheprintingandtypesettingindustryLoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500swhenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbookI",
                rowKey: "12");

var operation = TableOperation.InsertOrMerge(item);
table.Execute(operation); // Error Here
````

- Same code works without issues when run against a real Azure Table.
- It also works if the row  key OR the partition key had one less character.

**Exception Details from SDK:**

(Removed some path info in the last line)
````
Microsoft.Azure.Cosmos.Table.StorageException: 'The remote server returned an error: (400) Bad Request.'
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.<ExecuteAsync>d__1`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.<>c__DisplayClass0_0`1.<ExecuteSync>b__0()
   at Microsoft.Azure.Cosmos.Table.RestExecutor.Utils.RestUtility.RunWithoutSynchronizationContext[T](Func`1 actionToRun)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableCommand.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.Azure.Cosmos.Table.RestExecutor.TableRestExecutor.ExecuteTableOperation[TResult](TableOperation operation, CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.Azure.Cosmos.Table.TableOperation.Execute(CloudTableClient client, CloudTable table, TableRequestOptions requestOptions, OperationContext operationContext)
   at Microsoft.Azure.Cosmos.Table.CloudTable.Execute(TableOperation operation, TableRequestOptions requestOptions, OperationContext operationContext)
   at TableTest.Program.Main(String[] args) in C:\RedactedPath\TableTest\TableTest\Program.cs:line 20
````

Below is the full request and response captured via Fiddler while the sample code was running.

Request:

````
POST http://127.0.0.1:10002/devstoreaccount1/TestTable(PartitionKey='thisis223characterslongLoremIpsumissimplydummytextoftheprintingandtypesettingindustryLoremIpsumhasbeentheindustrysstandarddummytexteversincethe1500swhenanunknownprintertookagalleyoftypeandscrambledittomakeatypespecimenbookI',RowKey='12') HTTP/1.1
Host: 127.0.0.1:10002
Accept-Charset: UTF-8
MaxDataServiceVersion: 3.0;NetFx
Accept: application/json; odata=minimalmetadata
DataServiceVersion: 3.0;
X-HTTP-Method: MERGE
x-ms-client-request-id: bbfa8502-871c-467c-9339-52afc9d86b0b
User-Agent: Azure-Cosmos-Table/1.0.7 (.NET CLR 3.1.10; Win32NT 6.2.9200.0)
x-ms-version: 2017-07-29
x-ms-date: Sat, 19 Dec 2020 10:55:46 GMT
Authorization: SharedKey devstoreaccount1:o5jSzlpCwNXhQz8/wtD6oI85MsmtvDXHVcVRiPGWza8=
Content-Type: application/json
Content-Length: 2

{}
````

Response:
````
HTTP/1.1 400 Bad Request
Content-Type: text/html; charset=us-ascii
Server: Microsoft-HTTPAPI/2.0
Date: Sat, 19 Dec 2020 10:55:46 GMT
Connection: close
Content-Length: 324

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd">
<HTML><HEAD><TITLE>Bad Request</TITLE>
<META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD>
<BODY><h2>Bad Request - Invalid URL</h2>
<hr><p>HTTP Error 400. The request URL is invalid.</p>
</BODY></HTML>
````

**Environment:**
 -  Library `Microsoft.Azure.Cosmos.Table 1.0.8`
 - Attempted above code in a console app and a Azure Functions app on `netcoreapp3.1` and a console app on `net5.0`
 - Microsoft Visual Studio Community 2019 Version 16.8.3
 -  `AzureStorageEmulator.exe status` output
````
Windows Azure Storage Emulator 5.10.0.0 command line tool
IsRunning: True
BlobEndpoint: http://127.0.0.1:10000/
QueueEndpoint: http://127.0.0.1:10001/
TableEndpoint: http://127.0.0.1:10002/
````
 - `dotnet --info` output

````
.NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.101\

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab

.NET SDKs installed:
  2.1.801 [C:\Program Files\dotnet\sdk]
  2.2.401 [C:\Program Files\dotnet\sdk]
  5.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
````

**Workarounds**
Use a real Azure Storage Account instead of the emulator.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.  Please be aware that due to the holidays, responses may be delayed.

**Comment by madushans** [comment]
hi. this issue is not attached to a pull request. I believe this is pending follow up from the SDK team.

**Comment by christothes** [comment]
@amishra-dev Could you take a look at this and route it appropriately? Thanks!

**Comment by kwill-MSFT** [comment]
@christothes, @amishra-dev, any update on this?  I am hitting the same issue.

**Comment by christothes** [comment]
@kwill-MSFT Would Azurite work for you instead? https://github.com/Azure/Azurite

**Comment by arnoldpistorius** [comment]
We are experiencing this bug as well. We use Table storage with Orleans for grain storage. The Azure Storage Emulator raises 400 bad request errors on the long keys.

Tried to use Azurite as well, but that seems to give 409 response at some point, with error 

```{"odata.error":{"code":"EntityAlreadyExists","message":{"lang":"en-US","value":"The specified entity already exists.\nRequestId:537e16bc-ca9e-4d4a-8437-448325323ef0\nTime:2021-07-23T07:11:28.134Z"}}}```

Only real Table storage on Azure seems to work flawless.

**Comment by christothes** [comment]
@arnoldpistorius If you are experiencing this with Azurite, please open an issue over there so that they can take a look - https://github.com/Azure/Azurite/issues

**Comment by arnoldpistorius** [comment]
FYI https://github.com/Azure/Azurite/issues/946
