### ISSUE TITLE
Keyvault Sovereign test failure

### ISSUE THREAD

**Issue by tzhanl** [Azure/azure-sdk-for-net#17829]
use this issue to track keyvault sovereign test failures.

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=677066&view=results

@danieljurek @benbp @jongio

**Comment by heaths** [comment]
This requires infrastructure changes which @benbp is working on.

**Comment by tzhanl** [comment]
test VerifyCancelCertificateOperation always in all job in china cloud

**Comment by benbp** [comment]
The build has been deleted so I'm not sure what this issue is about. @tzhanl can you be more descriptive in the issue description and title?

**Comment by heaths** [comment]
That test frequently fails because of timing issues. I've made several changes already to try to combat it, but it's especially problematic. @tzhanl are you saying it's still failing even recently? Changes I have made see this fail *much* less in AzureCloud, at least.

**Comment by tzhanl** [comment]
@heaths it failed in 2/21: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=745075&view=results

all Job in China Cloud failed:

2021-02-22T02:14:08.9916889Z   Failed VerifyCancelCertificateOperation [4 s]
2021-02-22T02:14:08.9918040Z   Error Message:
2021-02-22T02:14:08.9919053Z      Expected exception OperationCanceledException not thrown. Operation status: inProgress, error: 
2021-02-22T02:14:08.9920121Z   Expected: <System.OperationCanceledException>
2021-02-22T02:14:08.9920903Z   But was:  null
2021-02-22T02:14:08.9921239Z 
2021-02-22T02:14:08.9921841Z   Stack Trace:
2021-02-22T02:14:08.9923060Z      at Azure.Security.KeyVault.Certificates.Tests.CertificateClientLiveTests.VerifyCancelCertificateOperation() in /mnt/vss/_work/1/s/sdk/keyvault/Azure.Security.KeyVault.Certificates/tests/CertificateClientLiveTests.cs:line 109

**Comment by tzhanl** [comment]
@heaths , same failure today https://dev.azure.com/azure-sdk/internal/_build/results?buildId=765075&view=results

**Comment by heaths** [comment]
Seems Key Vault is taking longer than expected to cancel the operation; however, this is not a priority right now. I'll resolve this as soon as possible.

**Comment by heaths** [comment]
A similar failure on mac, but not necessarily sovereign-specific:
```
Error message
System.Threading.Tasks.TaskCanceledException : A task was canceled.


Stack trace
   at Azure.Core.OperationHelpers.DefaultWaitForCompletionAsync[TResult](Operation`1 operation, TimeSpan pollingInterval, CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationHelpers.cs:line 53
   at System.Threading.Tasks.ValueTask`1.get_Result()
```

**Comment by heaths** [comment]
Duplicate of #17718
