### ISSUE TITLE
[BUG] Azure.Messaging.EventHubs: System.InvalidOperationException: 'Operation is not valid due to the current state of the object.'

### ISSUE THREAD

**Issue by devedse** [Azure/azure-sdk-for-net#17835]
**Describe the bug**
Executing the following code with version 5.2.0 of Azure.Messaging.EventHubs results in an exception:

![image](https://user-images.githubusercontent.com/2350015/103913726-28714700-5109-11eb-932e-2d106effc2a1.png)

```
var producer = new EventHubProducerClient(ConfigStuff.connectionString, ConfigStuff.eventHubName);
var partitions = await producer.GetPartitionIdsAsync();
```

Exception:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
```

This exception only occurs for .NET 5.0

**Expected behavior**
I would expect this code to work without throwing an error

**Actual behavior (include Exception or Stack Trace)**

Stacktrace:
```
System.InvalidOperationException: Operation is not valid due to the current state of the object.
   at Microsoft.Azure.Amqp.Transport.TransportStream.Flush()
   at System.IO.Stream.<>c.<FlushAsync>b__39_0(Object state)
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at System.Net.Security.SslStream.EndAuthenticateAsClient(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.Transport.TlsTransport.HandleOpenComplete(IAsyncResult result, Boolean syncComplete)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.HandleTransportOpened(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.OnTransportOpened(IAsyncResult result)
--- End of stack trace from previous location ---
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, EventHubsTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenManagementLinkAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConnection.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConnection.GetPartitionIdsAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.GetPartitionIdsAsync(CancellationToken cancellationToken)
   at EventSender.Program.Main(String[] args) in C:\XBDR\Tests\EventSender\EventSender\Program.cs:line 21
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Install `Azure.Messaging.EventHubs` version 5.2.0 nuget package
2. Run code as mentioned above

**Environment:**
 - Name and version of the Library package used: `Azure.Messaging.EventHubs 5.2.0`
 - Hosting platform or OS and .NET runtime version:
 ```
.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.22 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - IDE and version:
```
Microsoft Visual Studio Enterprise 2019
Version 16.8.3
```

**Comment by devedse** [comment]
I saw some previous issues regarding this were already closed, but the bug doesn't seem to be resolved:
https://github.com/Azure/azure-sdk-for-net/issues/14068
https://github.com/Azure/azure-sdk-for-net/issues/13899

Manually installing the latest version of `Microsoft.Azure.Amqp` resolves this issue:
```
Install-Package Microsoft.Azure.Amqp
```

**Comment by jsquire** [comment]
Hi @devedse.   Thank you for your feedback and we regret that you're experiencing difficulties.  As you noted in the issues that you linked, this behavior was due to a bug in the AMQP library that Event Hubs is using as a transport.   The version of the AMQP library that 5.2.0 was packaged with is affected by that bug.   The 5.3.0 line, currently in beta, uses a newer dependency that resolves the issue.

As you noted, the work around for using 5.2.0 with .NET 5 is to manually install the latest `Microsoft.Azure.Amqp` package.

**Comment by fwaris** [comment]
I tried to update the codebase from .net 3.1 to 5.0 and ran into this issue.  

After reading this post, I tested with the 5.3 beta version of the EventsHubs and the issue seems to be resolved.

**Comment by isaacabraham** [comment]
I don't think that this issue should be closed whilst it's still an active problem?

**Comment by jsquire** [comment]
Hi @isaacabraham.  This was closed because there is a known workaround for 5.2 and earlier versions and has already been corrected in the 5.3 line.

**Comment by isaacabraham** [comment]
@jsquire Ah. I pulled down EventHubs this weekend and had this issue (and resolved it by manually pulling the AMQP dependency) - I guess nuget didn't bring down the beta version though, just the full 5.2 release.

**Comment by jsquire** [comment]
@isaacabraham:  Fair; it's ideal and not obvious, but we hit a bit of a snag with scheduling a patch release for 5.2.  We'll be releasing 5.3 for GA this week, so the pain should be short-lived.

**Comment by isaacabraham** [comment]
No worries. nuget refs in F# scripts are really making it much, much easier and more accessible to quickly try out libraries like this (in combination with Farmer to spin up the resources first, of course ;-)).

**Comment by FrederikVigen** [comment]
I had exactly the same issue on this for .net 6.0 in Azure Functions with just the boilerplate code for .net 6.0 not in isolated process:
```
[FunctionName("Function1")]
public static void Run([ServiceBusTrigger("myTopicName", "mySubscription", Connection = "test")]string mySbMsg, ILogger log)
{
    log.LogInformation($"C# ServiceBus topic trigger function processed message: {mySbMsg}");
}
```

**Comment by bqstony** [comment]
@jsquire I have also the error. Created a EventHub Trigger for IotHub from template in VS2022

```c#
#    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.EventHubs" Version="4.2.0" />
#    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />
using IoTHubTrigger = Microsoft.Azure.WebJobs.EventHubTriggerAttribute;

using Microsoft.Azure.WebJobs;
using Microsoft.Azure.WebJobs.Host;
using Microsoft.Azure.EventHubs;
using System.Text;
using System.Net.Http;
using Microsoft.Extensions.Logging;

namespace FunctionApp1
{
    public class Function1
    {
        private static HttpClient client = new HttpClient();
        
        [FunctionName("Function1")]
        public void Run([IoTHubTrigger("messages/events", Connection = "EventHubConnectionString", ConsumerGroup = "iot-euw-iotdatastorage-prod-func")]EventData message, ILogger log)
        {
            log.LogInformation($"C# IoT Hub trigger function processed a message: {Encoding.UTF8.GetString(message.Body.Array)}");
        }
    }
}
```


The error output ist:

```bash
For detailed output, run func with --verbose flag.
[2021-12-09T12:44:04.197Z] The listener for function 'Function1' was unable to start.
[2021-12-09T12:44:04.199Z] The listener for function 'Function1' was unable to start. Microsoft.Azure.EventHubs.Processor: Encountered error while fetching the list of EventHub PartitionIds. Microsoft.Azure.Amqp: Operation is not valid due to the current state of the object.
[2021-12-09T12:44:06.244Z] The listener for function 'Function1' was unable to start.
[2021-12-09T12:44:06.245Z] The listener for function 'Function1' was unable to start. Microsoft.Azure.EventHubs.Processor: Encountered error while fetching the list of EventHub PartitionIds. Microsoft.Azure.Amqp: Operation is not valid due to the current state of the object.
[2021-12-09T12:44:08.424Z] Host lock lease acquired by instance ID '00000000000000000000000001684FDD'.[2021-12-09T12:44:10.414Z] The listener for function 'Function1' was unable to start.

[2021-12-09T12:44:11.267Z] The listener for function 'Function1' was unable to start. Microsoft.Azure.EventHubs.Processor: Encountered error while fetching the list of EventHub PartitionIds. Microsoft.Azure.Amqp: Operation is not valid due to the current state of the object.
```

after adding the reference to ` <PackageReference Include="Microsoft.Azure.Amqp" Version="2.5.8" />` explizit as @devedse said, it works now
