### ISSUE TITLE
[Flaky test] Flush_Blocks

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#17879]
```
Error message
Expected: 768
But was:  767


Stack trace
   at Azure.Search.Documents.Tests.BatchingTests.<Flush_Blocks>d__29.MoveNext() in D:\vss-agent-2.179.0\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 714
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.InvokeMoveNext(Object stateMachine)

```
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=677639&view=ms.vss-test-web.build-test-results-tab&runId=15843588&resultId=109861&paneView=debug

**Comment by JoshLove-msft** [comment]
This was marked as ignored in https://github.com/Azure/azure-sdk-for-net/pull/25927.
Closing
