### ISSUE TITLE
[Microsoft.Azure.ServiceBus] Spewing exceptions when internet connection lost, causing high CPU

### ISSUE THREAD

**Issue by johnknoop** [Azure/azure-sdk-for-net#17884]
Hi

I use the `ExceptionReceivedHandler` on the `MessageHandlerOptions` that is passed into `IReceiverClient.RegisterMessageHandler`, so that I can log when there is an error happening.

When my internet connection drops, this callback is fired off continuously without any delay in between, causing my CPU to spike.

The exception in this case is `Microsoft.Azure.ServiceBus.ServiceBusCommunicationException` (stack trace below), but I'm not sure if that's relevant.

I'm guessing you have a loop somewhere which tries to reconnect, and throws this exception if it fails. Could you maybe throttle the reconnect or something? I don't see a benefit of receiving this exception ten thousand times per second, compared to maybe ten times per second.

> Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: Name or service not known ErrorCode: HostNotFound
 ---> System.Net.Sockets.SocketException (0xFFFDFFFF): Name or service not known
   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Core.MessageReceiver.GetSessionReceiverLinkAsync(TimeSpan serverWaitTime)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.SessionClient.AcceptMessageSessionAsync(String sessionId, TimeSpan operationTimeout)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.SessionClient.AcceptMessageSessionAsync(String sessionId, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.SessionReceivePump.SessionPumpTaskAsync()

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@johnknoop the default retry policy has an exponential back off, so it should not throw that many exceptions. Any chance you have retry policy override in place?

**Comment by johnknoop** [comment]
@axisc 

I use the exponential backoff retry policy, but with custom delays:

```cs
new RetryExponential(TimeSpan.FromSeconds(1), TimeSpan.FromSeconds(30), 5)
```

**Comment by axisc** [comment]
@johnknoop  can I ask you to open a support ticket? that would give us a chance to review your backend logs and identify if something needs to be triaged.

**Comment by johnknoop** [comment]
@axisc Sure! You mean a support ticket with Azure, or do you mean here at GitHub?

**Comment by axisc** [comment]
support ticket with Azure 👍
