### ISSUE TITLE
[FEATURE REQ] Microsoft.Azure.ServiceBus - Separate OperationTimeout to allow for consistent retries

### ISSUE THREAD

**Issue by JoshKeegan** [Azure/azure-sdk-for-net#18001]
**Library or service name.**
Microsoft.Azure.ServiceBus
 
**Is your feature request related to a problem? Please describe.**
I am trying to use the `TopicClient` to send messages with a custom `RetryPolicy` to do something that I expected to be simple: I want to retry failures (at least ones that should be retried) 3 times, with a 3 second timeout for each attempt, and a 3 second delay between each attempt.

The problem is that `TopicClient.OperationTimeout` appears to be enforced for both the timeout of an individual retry attempt, and also for the overall operation to send the message. So for my use case I would want to set `TopicClient.OperationTimeout` to 3 seconds so that each individual attempt doesn't go on for too long, but doing so means that when the first attempt times out, the next two attempts won't get to happen as the overall 3 second time has now elapsed.

To solve this problem, I think `TopicClient.OperationTimeout` needs separating into two timeout values, one for individual retry attempts and one for the overall operation (which could potentially be optional).

**Example**
I've created a small sample app to demonstrate retries not happenning for cases where the individual attempt times out (e.g. failure to connect to host), and also show that the retries work as I need for operations that timeout quickly (e.g. failure to resolve hostname):
```cs
using System;
using System.Threading.Tasks;
using Microsoft.Azure.ServiceBus;
using Serilog;

namespace ServiceBusRetriesTimeoutRepro
{
    public static class Program
    {
        public static async Task Main()
        {
            ILogger log = new LoggerConfiguration()
                .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss:fff} {Level:u3}] {Message:lj}{NewLine}{Exception}")
                .CreateLogger();

            log.Information("No such host (fails fast)...");
            await run(log, "Endpoint=sb://asdf.servicebus.windows.net/;SharedAccessKeyName=fghj;SharedAccessKey=klzx;EntityPath=MustHaveOneOfThese;");

            log.Information("Host exists, not a service bus (times out)...");
            await run(log, "Endpoint=sb://google.co.uk/;SharedAccessKeyName=fghj;SharedAccessKey=klzx;EntityPath=MustHaveOneOfThese;");
        }

        private static async Task run(ILogger log, string connStr)
        {
            ITopicClient topicClient = new TopicClient(new ServiceBusConnectionStringBuilder(connStr),
                new RetryFixedPolicy(3, TimeSpan.FromMilliseconds(100), log))
            {
                OperationTimeout = TimeSpan.FromSeconds(4)
            };

            Message message = new Message
            {
                Body = new byte[] { 1, 2, 3 }
            };

            log.Information("Starting to send message");

            try
            {
                await topicClient.SendAsync(message);
            }
            catch (Exception e)
            {
                log.Error(e, "An exception occurred whilst sending message");
            }

            log.Information("End");
        }
    }

    public class RetryFixedPolicy : RetryPolicy
    {
        private readonly int maxRetries;
        private readonly TimeSpan delayBetweenAttempts;
        private readonly ILogger log;

        public RetryFixedPolicy(int maxRetries, TimeSpan delayBetweenAttempts, ILogger log)
        {
            if (maxRetries <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(maxRetries), "Must retry at least once");
            }
            if (delayBetweenAttempts < TimeSpan.Zero)
            {
                throw new ArgumentOutOfRangeException(nameof(delayBetweenAttempts),
                    "Cannot have a negative delay between retry attempts");
            }

            this.maxRetries = maxRetries;
            this.delayBetweenAttempts = delayBetweenAttempts;
            this.log = log ?? throw new ArgumentNullException(nameof(log));
        }

        protected override bool OnShouldRetry(TimeSpan remainingTime, int currentRetryCount, out TimeSpan retryInterval)
        {
            if (currentRetryCount > maxRetries)
            {
                log.Error("Reached max retries ({MaxRetries}). Will not retry again", maxRetries);

                retryInterval = TimeSpan.Zero;
                return false;
            }

            log.Information("Retrying sending to service bus. Retry {CurrentRetryCount}/{MaxRetries}",
                currentRetryCount, maxRetries);

            retryInterval = delayBetweenAttempts;
            return true;
        }
    }
}
```

This produces the output:
```
[14:59:48:990 INF] No such host (fails fast)...
[14:59:49:017 INF] Starting to send message
[14:59:49:078 INF] Retrying sending to service bus. Retry 1/3
[14:59:49:187 INF] Retrying sending to service bus. Retry 2/3
[14:59:49:299 INF] Retrying sending to service bus. Retry 3/3
[14:59:49:412 ERR] Reached max retries (3). Will not retry again
[14:59:49:413 ERR] An exception occurred whilst sending message
Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: No such host is known. ErrorCode: HostNotFound
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at ServiceBusRetriesTimeoutRepro.Program.run(ILogger log, String connStr) in C:\code\ServiceBusRetriesTimeoutRepro\ServiceBusRetriesTimeoutRepro\Program.cs:line 40
[14:59:49:432 INF] End
[14:59:49:433 INF] Host exists, not a service bus (times out)...
[14:59:49:433 INF] Starting to send message
[14:59:53:448 INF] Retrying sending to service bus. Retry 1/3
[14:59:53:449 ERR] An exception occurred whilst sending message
Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at ServiceBusRetriesTimeoutRepro.Program.run(ILogger log, String connStr) in C:\code\ServiceBusRetriesTimeoutRepro\ServiceBusRetriesTimeoutRepro\Program.cs:line 40
[14:59:53:452 INF] End

C:\code\ServiceBusRetriesTimeoutRepro\ServiceBusRetriesTimeoutRepro\bin\Debug\netcoreapp3.1\ServiceBusRetriesTimeoutRepro.exe (process 25404) exited with code 0.
Press any key to close this window . . .
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by axisc** [comment]
@JoshKeegan  not sure I fully follow. The retry policy is for the operation (Send), while the timeout applies to the operation and the retry.

The default retry policy utilizes an **exponential backoff** policy to avoid the situation that you are seeing.

**Comment by JoshKeegan** [comment]
@axisc the issue is that there is no timeout on an individual retry attempt, without which you don't have full control over your retries (so in the second scenario there are no retries).

RE the default retry policy: the same issue occurs there, although it requires a slightly modified version of the `RetryExponential` class to add logging (and also remove internal dependencies), here's the code illustrating that:
```cs
using System;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.Azure.ServiceBus;
using Serilog;

namespace ServiceBusRetriesTimeoutRepro
{
    public static class Program
    {
        public static async Task Main()
        {
            ILogger log = new LoggerConfiguration()
                .WriteTo.Console(outputTemplate: "[{Timestamp:HH:mm:ss:fff} {Level:u3}] {Message:lj}{NewLine}{Exception}")
                .CreateLogger();

            log.Information("No such host (fails fast)...");
            await run(log, "Endpoint=sb://asdf.servicebus.windows.net/;SharedAccessKeyName=fghj;SharedAccessKey=klzx;EntityPath=MustHaveOneOfThese;");

            log.Information("Host exists, not a service bus (times out)...");
            await run(log, "Endpoint=sb://google.co.uk/;SharedAccessKeyName=fghj;SharedAccessKey=klzx;EntityPath=MustHaveOneOfThese;");
        }

        private static async Task run(ILogger log, string connStr)
        {
            RetryPolicy fixedRetryPolicy = new RetryFixedPolicy(3, TimeSpan.FromMilliseconds(100), log);
            RetryPolicy exponentialBackoffRetryPolicy = new CustomRetryExponential(TimeSpan.FromMilliseconds(10),
                TimeSpan.FromMilliseconds(10), TimeSpan.FromMilliseconds(10), 3, log);

            ITopicClient topicClient = new TopicClient(new ServiceBusConnectionStringBuilder(connStr),
                // Swap retry policies here
                exponentialBackoffRetryPolicy)
            {
                OperationTimeout = TimeSpan.FromSeconds(4)
            };

            Message message = new Message
            {
                Body = new byte[] { 1, 2, 3 }
            };

            log.Information("Starting to send message");

            try
            {
                await topicClient.SendAsync(message);
            }
            catch (Exception e)
            {
                log.Error(e, "An exception occurred whilst sending message");
            }

            log.Information("End");
        }
    }

    /// <summary>
    /// Copy of RetryExponential with added logging to demonstrate issue
    /// </summary>
    public sealed class CustomRetryExponential : RetryPolicy
    {
        private static readonly ThreadLocal<Random> concurrentRandom = new ThreadLocal<Random>(() => new Random());
        private readonly ILogger log;

        public CustomRetryExponential(TimeSpan minimumBackoff, TimeSpan maximumBackoff, TimeSpan deltaBackoff, int maxRetryCount, ILogger log)
        {
            this.log = log;
            //TimeoutHelper.ThrowIfNonPositiveArgument(deltaBackoff, nameof(deltaBackoff));
            //TimeoutHelper.ThrowIfNegativeArgument(minimumBackoff, nameof(minimumBackoff));
            //TimeoutHelper.ThrowIfNonPositiveArgument(maximumBackoff, nameof(maximumBackoff));

            //if (maxRetryCount <= 0)
            //{
            //    throw new ArgumentOutOfRangeException(
            //        nameof(maxRetryCount),
            //        Resources.ArgumentMustBePositive.FormatForUser(nameof(maxRetryCount)));
            //}

            //if (minimumBackoff >= maximumBackoff)
            //{
            //    throw new ArgumentException(Resources.ExponentialRetryBackoffRange.FormatForUser(minimumBackoff, maximumBackoff));
            //}

            this.MinimalBackoff = minimumBackoff;
            this.MaximumBackoff = maximumBackoff;
            this.DeltaBackoff = deltaBackoff;
            this.MaxRetryCount = maxRetryCount;
        }

        /// <summary>
        /// Minimum backoff interval.
        /// </summary>
        /// <value>The minimum backoff interval.</value>
        public TimeSpan MinimalBackoff { get; }

        /// <summary>
        /// Gets or sets the maximum backoff interval.
        /// </summary>
        /// <value>The maximum backoff interval.</value>
        public TimeSpan MaximumBackoff { get; }

        /// <summary>
        /// Gets or sets the backoff interval associated with the retry.
        /// </summary>
        /// <value>The backoff interval associated with the retry.</value>
        public TimeSpan DeltaBackoff { get; }

        /// <summary>
        /// Gets or sets the maximum number of allowed retries.
        /// </summary>
        /// <value>The maximum number of allowed retries.</value>
        public int MaxRetryCount { get; }

        /// <summary>
        /// Called to see if a retry should be performed.
        /// </summary>
        /// <param name="remainingTime">The remaining time before the timeout expires.</param>
        /// <param name="currentRetryCount">The number of attempts that have been processed.</param>
        /// <param name="retryInterval">The amount of time to delay before retry.</param>
        protected override bool OnShouldRetry(TimeSpan remainingTime, int currentRetryCount, out TimeSpan retryInterval)
        {
            if (currentRetryCount > this.MaxRetryCount)
            {
                log.Error("Reached max retries ({MaxRetries}). Will not retry again", MaxRetryCount);

                retryInterval = TimeSpan.Zero;
                return false;
            }

            // Logic: - first use currentRetryCount to calculate the size of the interval.
            //        - then get the interval in terms of sleep time (between min and max sleep time)
            //        - if interval to large to fit inside remainingTime, we quit.
            var randomizedInterval = concurrentRandom.Value.Next((int)(this.DeltaBackoff.TotalMilliseconds * 0.8), (int)(this.DeltaBackoff.TotalMilliseconds * 1.2));
            double increment = (Math.Pow(2, currentRetryCount) - 1) * randomizedInterval;
            double timeToSleepMsec = Math.Min(this.MinimalBackoff.TotalMilliseconds + increment, this.MaximumBackoff.TotalMilliseconds);
            retryInterval = TimeSpan.FromMilliseconds(timeToSleepMsec);

            log.Information("Retrying sending to service bus. Retry {CurrentRetryCount}. Interval {RetryInterval}",
                currentRetryCount, retryInterval);

            return true;
        }
    }

    public class RetryFixedPolicy : RetryPolicy
    {
        private readonly int maxRetries;
        private readonly TimeSpan delayBetweenAttempts;
        private readonly ILogger log;

        public RetryFixedPolicy(int maxRetries, TimeSpan delayBetweenAttempts, ILogger log)
        {
            if (maxRetries <= 0)
            {
                throw new ArgumentOutOfRangeException(nameof(maxRetries), "Must retry at least once");
            }
            if (delayBetweenAttempts < TimeSpan.Zero)
            {
                throw new ArgumentOutOfRangeException(nameof(delayBetweenAttempts),
                    "Cannot have a negative delay between retry attempts");
            }

            this.maxRetries = maxRetries;
            this.delayBetweenAttempts = delayBetweenAttempts;
            this.log = log ?? throw new ArgumentNullException(nameof(log));
        }

        protected override bool OnShouldRetry(TimeSpan remainingTime, int currentRetryCount, out TimeSpan retryInterval)
        {
            if (currentRetryCount > maxRetries)
            {
                log.Error("Reached max retries ({MaxRetries}). Will not retry again", maxRetries);

                retryInterval = TimeSpan.Zero;
                return false;
            }

            log.Information("Retrying sending to service bus. Retry {CurrentRetryCount}/{MaxRetries}",
                currentRetryCount, maxRetries);

            retryInterval = delayBetweenAttempts;
            return true;
        }
    }
}
```

Which outputs:
```
[11:38:20:843 INF] No such host (fails fast)...
[11:38:20:876 INF] Starting to send message
[11:38:20:975 INF] Retrying sending to service bus. Retry 1. Interval 00:00:00.0100000
[11:38:21:004 INF] Retrying sending to service bus. Retry 2. Interval 00:00:00.0100000
[11:38:21:018 INF] Retrying sending to service bus. Retry 3. Interval 00:00:00.0100000
[11:38:21:033 ERR] Reached max retries (3). Will not retry again
[11:38:21:035 ERR] An exception occurred whilst sending message
Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: No such host is known. ErrorCode: HostNotFound
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at ServiceBusRetriesTimeoutRepro.Program.run(ILogger log, String connStr) in C:\code\ServiceBusRetriesTimeoutRepro\ServiceBusRetriesTimeoutRepro\Program.cs:line 45
[11:38:21:058 INF] End
[11:38:21:058 INF] Host exists, not a service bus (times out)...
[11:38:21:059 INF] Starting to send message
[11:38:25:065 INF] Retrying sending to service bus. Retry 1. Interval 00:00:00.0100000
[11:38:25:066 ERR] An exception occurred whilst sending message
Microsoft.Azure.ServiceBus.ServiceBusCommunicationException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ErrorCode: TimedOut
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at Microsoft.Azure.ServiceBus.ServiceBusConnection.CreateConnectionAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Amqp.AmqpLinkCreator.CreateAndOpenAmqpLinkAsync()
   at Microsoft.Azure.ServiceBus.Core.MessageSender.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   --- End of inner exception stack trace ---
   at Microsoft.Azure.ServiceBus.Core.MessageSender.OnSendAsync(IList`1 messageList)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout)
   at Microsoft.Azure.ServiceBus.Core.MessageSender.SendAsync(IList`1 messageList)
   at ServiceBusRetriesTimeoutRepro.Program.run(ILogger log, String connStr) in C:\code\ServiceBusRetriesTimeoutRepro\ServiceBusRetriesTimeoutRepro\Program.cs:line 45
[11:38:25:069 INF] End

C:\code\ServiceBusRetriesTimeoutRepro\ServiceBusRetriesTimeoutRepro\bin\Debug\netcoreapp3.1\ServiceBusRetriesTimeoutRepro.exe (process 15316) exited with code 0.
Press any key to close this window . . .
```

So it doesn't matter which retry policy is used, the same issue exists because there is no control over the timeout of an individual retry attempt.

**Comment by axisc** [comment]
I see. Yes, we don't have a way to define granular timeout for each retry attempt. It is meant to simplify the configuration.

I would instead recommend reducing the number of retries, which can be done by adjusting the retry policy.

hope this helps.

**Comment by JoshKeegan** [comment]
Hi @axisc,
I don't think reducing the number of retries would help. In the second scenario in my example code (hostname resolves but service bus port cannot be connected to) no retries occur. Whatever the number of retries is set to, this problem will happen as the library waits for `ITopicClient.OperationTimeout` to be reached before terminating the initial attempt. 

Perhaps I didn't initially highlight this strongly enough, but without any control over the timeout of an individual attempt I believe retries are broken due to there being cases where retries just won't happen.

**Comment by axisc** [comment]
The issue here is that there are certain error conditions where retry will not help. If those error conditions are identified, the subsequent retries should be stopped.

We currently tag this on an Exception level, but there is probably value in enabling client overrides when required.

Let me take this as a feature request and add it to the backlog.

**Comment by ramya-rao-a** [comment]
@JoshKeegan Please note that a newer package `Azure.Messaging.ServiceBus` is available as of November 2020. While the older package `Microsoft.Azure.ServiceBus` will continue to receive critical bug fixes, we strongly encourage you to upgrade. Read the [migration guide](https://aka.ms/azsdk/net/migrate/sb)  for more details.

The [`ServiceBusClient` ](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusclient?view=azure-dotnet)in the newer SDK allows you to provide custom retry policy that will let you customize timeouts for individual retry attempts. You might want to take a look at
- [Samples for Azure.Messaging.ServiceBus](https://docs.microsoft.com/en-us/samples/azure/azure-sdk-for-net/azuremessagingservicebus-samples/)
- [The retry options you can customize](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.servicebus.servicebusretryoptions?view=azure-dotnet)


@shankarsama Is this something you are still considering for Microsoft.Azure.ServiceBus package? If not, then we can close this issue.

**Comment by ramya-rao-a** [comment]
Thanks for your patience @JoshKeegan 

Closing this issue as there are no new features planned for `Microsoft.Azure.ServiceBus`. Please do try the newer `Azure.Messaging.ServiceBus` package as mentioned in the previous comment and share any feedback you have.
