### ISSUE TITLE
[BUG] CreateIfNotExistsAsync fails intermittently

### ISSUE THREAD

**Issue by petro2050** [Azure/azure-sdk-for-net#18033]
I keep getting the below exception intermittently. This is happening when I invoke `CreateIfNotExistsAsync` on `BlobContainerClient`. The container name has a random Guid in it, so it should be a unique name every time the code is executed. I have no idea why I'm getting an `InvalidHeaderValue` error code. I don't set this header anywhere in my code.

```
Azure.RequestFailedException: The value for one of the HTTP headers is not in the correct format.
RequestId:f2845b3b-b01e-0035-594d-ede902000000
Time:2021-01-18T03:56:14.9233616Z
Status: 400 (The value for one of the HTTP headers is not in the correct format.)
ErrorCode: InvalidHeaderValue

Additional Information:
HeaderName: x-ms-version
HeaderValue: 2020-04-08

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: f2845b3b-b01e-0035-594d-ede902000000
Date: Mon, 18 Jan 2021 03:56:14 GMT
Content-Length: 329
Content-Type: application/xml

   at Azure.Storage.Blobs.BlobRestClient.Container.CreateAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.Container.CreateAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, PublicAccessType access, String version, Nullable`1 timeout, IDictionary`2 metadata, String requestId, String defaultEncryptionScope, Nullable`1 preventEncryptionScopeOverride, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.CreateInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken, String operationName)
   at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsInternal(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExistsAsync(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, CancellationToken cancellationToken)

```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi, the issue you are running into is not related to `CreateIfNotExistsAsync`, it's something related to the service due to the error you are getting. We are working on a change to resolve the intermittent problem you are running into. I will update you when it should be or when it gets resolved.

Sorry for the inconvenience.

**Comment by Kravca** [comment]
Im getting same error messages using latest SDK 12.8.0. In my case I'm getting this for BlobDownload, BlobUpload, Container listing and probably other operations. Important note, this happens only against recently created storage accounts (January 2021), old storage accounts do not complain about the header.

**Comment by amnguye** [comment]
Hi, the fix on the service is coming out soon. This is not an SDK issue. I will let you know as soon I know that this fix is out. Thanks for your patience.

**Comment by Kravca** [comment]
For the ones looking for temporary workarounds. Its either create new storage account and you might get lucky (according to my stats its 2% bad luck), or rollback to SDK 12.7.

**Comment by seanmcc-msft** [comment]
Service version 2020-04-08 fully round out several months ago, this should no longer be an issue.

**Comment by bfmsoft** [comment]
The emulator doesn't understand the new version.  So when you try to use the preview of the C# nuget package it fails when trying to connect to the emulator.  This is latest version of VS2022 preview...
