### ISSUE TITLE
[BUG] [Servicebus|Azure.Messaging.ServiceBus] CreateMessageBatchAsync does not calculate the size correctly 

### ISSUE THREAD

**Issue by reza-esfandyari** [Azure/azure-sdk-for-net#18038]
Here is the sample code: 
I am not sure if the method is not calculating the size correctly or there is some mismatch between the way that CreateMessageBatchAsync and SendMessagesAsync validate the size 

```csharp
            for (var i = 0; i < integrationEvents.Length; i++)
            {
                if (!messageBatch.TryAddMessage((GenerateMessage(integrationEvents[i]))))
                {
                    try
                    {
                        sender.SendMessagesAsync(messageBatch).GetAwaiter().GetResult();
                    }
                    catch (Exception e)
                    {
                        _logger.LogError(e,
                            "ServiceBus - Failed to send the message");
                    }
                    
                    geBatch.Dispose();
                    messageBatch = sender.CreateMessageBatchAsync().GetAwaiter().GetResult();

                    if (!messageBatch.TryAddMessage((GenerateMessage(integrationEvents[i]))))
                    {
                        Console.WriteLine($"Failed to fit message number in a batch {i}");
                        break;
                    }
                }

            }

            try
            {
                sender.SendMessagesAsync(messageBatch).GetAwaiter().GetResult();
                messageBatch.Dispose();
            }
            catch (Exception e)
            {
                _logger.LogError(e,
                    "ServiceBus - Failed to send the message");
            }
```
![image](https://user-images.githubusercontent.com/9850812/104983054-9e12c800-59d1-11eb-86c3-817a5e6a1020.png)

![image](https://user-images.githubusercontent.com/9850812/104983111-ba166980-59d1-11eb-9d69-0e4d5c655807.png)

```
Azure.Messaging.ServiceBus.ServiceBusException: The message (id:56329192, size:293920 bytes) is larger than is currently allowed (262144 bytes). (MessageSizeExceeded)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(Func`1 messageFactory, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(Func`1 messageFactory, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c__DisplayClass18_0.<<SendBatchAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation(Func`2 operation, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusSender.SendMessagesAsync(ServiceBusMessageBatch messageBatch, CancellationToken cancellationToken)
   at Adia.Core.IntegrationService.ServiceBus.EventBusServiceBus.Publish(IEnumerable`1 events, QueueOrTopicName queueOrTopicName) in D:\repos\Adia-Service-Bulk-Timesheet-Validation\Source\Adia.Core\IntegrationService\ServiceBus\EventBusServiceBus.cs:line 136
```

there is not much in message custom property but I assume when the batch calculate the size it should consider it too
![image](https://user-images.githubusercontent.com/9850812/104983272-124d6b80-59d2-11eb-8e85-dc0eee8c8f28.png)

**Comment by JoshLove-msft** [comment]
@reza-esfandyari, thanks for submitting the issue. Any chance you can include the logic behind your GenerateMessage method? I haven't been able to repro the issue when setting a message body and application properties.

**Comment by reza-esfandyari** [comment]
Hi @JoshLove-msft, Thanks for getting back to me quickly, here is the content

```
 private static ServiceBusMessage GenerateMessage(IntegrationEvent @event)
        {
            var message = new ServiceBusMessage
            {
                MessageId = Guid.NewGuid().ToString(),
                Body = new BinaryData(JsonConvert.SerializeObject(@event)),
                ApplicationProperties =
                {
                    {"EventName", @event.GetType().Name.Replace(IntegrationEventSuffix, "")},
                    {"ServiceName", "TODO"}
                }
            };
            return message;
        }
```

**Comment by JoshLove-msft** [comment]
It looks like the issue is that we are not reserving space for properties that go on the batch envelope, namely the messageId, sessionId, and partitionKey from the first message in the batch. Thanks @jsquire for pointing this out and thank you @reza-esfandyari for submitting the issue! We will get this patched up.

**Comment by reza-esfandyari** [comment]
Thanks, guys. 
any estimate on when I can have the fix @JoshLove-msft? Are you going to update this issue ticket?

**Comment by JoshLove-msft** [comment]
> Thanks, guys.
> any estimate on when I can have the fix @JoshLove-msft? Are you going to update this issue ticket?

Yep, it should be available in our next release which is slated for the second week of Feb.
