### ISSUE TITLE
[BUG] Azure.Storage.Files.Shares.ShareFileClient fails when downloading a 1GiB file

### ISSUE THREAD

**Issue by Mohit-Chakraborty** [Azure/azure-sdk-for-net#18055]
**Describe the bug**
Using a console app to download a 1GiB file by calling `Azure.Storage.Files.Shares.ShareFileClient.DownloadAsync()` results in the server returning an error after running for a while.
The same error occurs when calling `Azure.Storage.Files.Shares.ShareFileClient.Download()`.

**Expected behavior**
File is downloaded successfully

**Actual behavior (include Exception or Stack Trace)**
After running for a while, the server returns an error

Exception: Azure.RequestFailedException: The server is busy.
RequestId:xxx
Time:2021-01-19T19:11:34.1990083Z
Status: 503 (The server is busy.)
ErrorCode: ServerBusy

Headers:
Server: Windows-Azure-File/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: xxx
x-ms-client-request-id: xxx
x-ms-version: 2020-04-08
x-ms-error-code: ServerBusy
Date: Tue, 19 Jan 2021 19:11:33 GMT
Content-Length: 198
Content-Type: application/xml

`  at Azure.Storage.Files.Shares.FileRestClient.File.DownloadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response) in /home/azure-sdk-for-net/sdk/storage/Azure.Storage.Files.Shares/src/Generated/FileRestClient.cs:line 5217
  at Azure.Storage.Files.Shares.FileRestClient.File.DownloadAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, Nullable1 timeout, String range, Nullable1 rangeGetContentHash, String leaseId, Boolean async, String operationName, CancellationToken cancellationToken) in /home/azure-sdk-for-net/sdk/storage/Azure.Storage.Files.Shares/src/Generated/FileRestClient.cs:line 5140
   at Azure.Storage.Files.Shares.ShareFileClient.StartDownloadAsync(HttpRange range, Boolean rangeGetContentHash, Int64 startOffset, ShareFileRequestConditions conditions, Boolean async, CancellationToken cancellationToken) in /home/azure-sdk-for-net/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs:line 1920
   at Azure.Storage.Files.Shares.ShareFileClient.DownloadInternal(HttpRange range, Boolean rangeGetContentHash, ShareFileRequestConditions conditions, Boolean async, CancellationToken cancellationToken) in /home/azure-sdk-for-net/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs:line 1816
   at Azure.Storage.Files.Shares.ShareFileClient.DownloadAsync(HttpRange range, Boolean rangeGetContentHash, ShareFileRequestConditions conditions, CancellationToken cancellationToken) in /home/azure-sdk-for-net/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs:line 1704
   at Azure.Storage.Files.Shares.Perf.Scenarios.DownloadFile.RunAsync(CancellationToken cancellationToken) in /home/azure-sdk-for-net/sdk/storage/Azure.Storage.Files.Shares/perf/Azure.Storage.Files.Shares.Perf/Scenarios/DownloadFile.cs:line 94
   at Azure.Test.Perf.PerfProgram.RunLoopAsync(IPerfTest test, Int32 index, Boolean latency, CancellationToken cancellationToken) in /home/azure-sdk-for-net/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 385
   at Azure.Test.Perf.PerfProgram.RunTestsAsync(IPerfTest[] tests, PerfOptions options, String title, Boolean warmup) in /home/azure-sdk-for-net/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 263
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in /home/azure-sdk-for-net/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 114
`

**To Reproduce**

1. Build and run the [standalone app](https://github.com/Azure/azure-sdk-for-net/tree/master/sdk/storage/Azure.Storage.Files.Shares/perf/Azure.Storage.Files.Shares.Perf) to test the performance of Azure File Shares
> $ dotnet build --configuration Release --framework netcoreapp2.1 sdk/storage/Azure.Storage.Files.Shares/perf/Azure.Storage.Files.Shares.Perf/Azure.Storage.Files.Shares.Perf.csproj
> $ dotnet run --configuration Release --framework netcoreapp2.1 --no-build -p sdk/storage/Azure.Storage.Files.Shares/perf/Azure.Storage.Files.Shares.Perf/Azure.Storage.Files.Shares.Perf.csproj downloadfile -s 1073741824 -p8 -i 1 -d 3600 --status-interval 60

**Environment:**
Azure.Core: 1.8.1.0
Azure.Core.TestFramework: 1.0.0.0
Azure.Storage.Files.Shares: 12.7.0.0
netcoreapp2.1

**Comment by amnguye** [comment]
Hi, So you always get a 503 error when attempting to Download with File Shares? Are there no other error codes that occur when attempting to Download or on your other attempts to Download?

The error code `ServerBusy` could mean that the service or your storage account is getting throttled or something is getting limited. Are you the only one who is attempting to access the storage account? are there other parallel threads going on accessing the storage account?

**Comment by Mohit-Chakraborty** [comment]
I am getting this error when repeatedly downloading a large (1GiB) file over a long period.
If I only run the scenario for say 1 minute, the code works fine.

> Are you the only one who is attempting to access the storage account?

Yes.

> are there other parallel threads going on accessing the storage account?

I have tried the scenario with no parallelization and with multi-core execution. Both give me this error.

> The error code ServerBusy could mean that the service or your storage account is getting throttled or something is getting limited.

Is there a way to diagnose the issue by looking at logs or other info in the Azure Portal? Is there flexibility in setting parameters to reduce throttling?

**Comment by amnguye** [comment]
Mitigated offline. Discussed ways to download the blob with exponential back off after hitting the storage account consecutively receiving the 500.

**Comment by mikeharder** [comment]
I am seeing this issue in the .NET FileShare perf tests as well (scenario "1GB parallel=8").  I understand this may be a service issue, but the equivalent Java perf tests are not hitting this same issue.

@amnguye: Does the .NET FileShare.DownloadAsync() API retry on 503s from the service?  If so, then if I am seeing this error in the perf test logs, it means the client got 503 (or some error) on each retry?

**Comment by JimSuplizio** [comment]
Hi @Mohit-Chakraborty, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
