### ISSUE TITLE
[Stress] NullReferenceException in ShareFileClient.DownloadAsync()

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#18198]
I am able to consistently repro a `NullReferenceException` when running the `ShareFileClient.DownloadAsync()` perf test.  This appears to be a stress bug in either our code or the .NET Framework.

## Repro Steps
1. Create a storage account with `Performance: Premium` and `Account kind: FileStorage`.
2. Create an Azure VM with `Operating System: Linux (ubuntu 18.04)`, `Size: Standard DS3 v2 (4 vcpus, 14 GiB memory)`, and `Accelerated networking: Enabled` (Accelerated networking should be enabled by default).
3. Set environment variables `AZURE_STORAGE_ACCOUNT_NAME` and `AZURE_STORAGE_ACCOUNT_KEY`.
4. `cd sdk/storage/Azure.Storage.Files.Shares/perf/Azure.Storage.Files.Shares.Perf`
5. `dotnet run -c release -f netcoreapp2.1 -- downloadfile -s 10485760 -p 32`

The test should eventually fail with the following exception.  You might need to run several times to trigger the failure.  I believe the test is only failing when the perf framework is stopping either the warmup or the main run (and cancelling the `CancellationToken`), so a more direct repro might be to just repeatedly cancel `ShareFileClient.DownloadAsync()` while downloading.

```
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Net.Http.HttpConnection.ContentLengthReadStream.ReadAsync(Memory`1 buffer, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.ResponseBodyPolicy.CopyToAsync(Stream source, Stream destination, CancellationTokenSource cancellationTokenSource)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Storage.Files.Shares.FileRestClient.DownloadAsync(Nullable`1 timeout, String range, Nullable`1 rangeGetContentMD5, ShareFileRequestConditions leaseAccessConditions, CancellationToken cancellationToken) in /home/mharder/net/sdk/storage/Azure.Storage.Files.Shares/src/Generated/FileRestClient.cs:line 248
   at Azure.Storage.Files.Shares.ShareFileClient.StartDownloadAsync(HttpRange range, Boolean rangeGetContentHash, Int64 startOffset, ShareFileRequestConditions conditions, Boolean async, CancellationToken cancellationToken) in /home/mharder/net/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs:line 1966
   at Azure.Storage.Files.Shares.ShareFileClient.DownloadInternal(HttpRange range, Boolean rangeGetContentHash, ShareFileRequestConditions conditions, Boolean async, CancellationToken cancellationToken) in /home/mharder/net/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs:line 1859
   at Azure.Storage.Files.Shares.ShareFileClient.DownloadAsync(HttpRange range, Boolean rangeGetContentHash, ShareFileRequestConditions conditions, CancellationToken cancellationToken) in /home/mharder/net/sdk/storage/Azure.Storage.Files.Shares/src/ShareFileClient.cs:line 1742
   at Azure.Storage.Files.Shares.Perf.Scenarios.DownloadFile.RunAsync(CancellationToken cancellationToken) in /home/mharder/net/sdk/storage/Azure.Storage.Files.Shares/perf/Azure.Storage.Files.Shares.Perf/Scenarios/DownloadFile.cs:line 94
   at Azure.Test.Perf.PerfProgram.RunLoopAsync(IPerfTest test, Int32 index, Boolean latency, CancellationToken cancellationToken) in /home/mharder/net/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 390
   at Azure.Test.Perf.PerfProgram.RunTestsAsync(IPerfTest[] tests, PerfOptions options, String title, Boolean warmup) in /home/mharder/net/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 268
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in /home/mharder/net/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 117
```

**Comment by pakrym** [comment]
We haven't seen this issue repeat anywhere.
