### ISSUE TITLE
[BUG] Azure.Storage.Blobs.Batch delete requests fail when using a TokenCredential for authorization

### ISSUE THREAD

**Issue by HamsterExAstris** [Azure/azure-sdk-for-net#18265]
**Describe the bug**
When using the `Azure.Storage.Blobs.Batch` .NET SDK to interact with blob storage, authenticating via Azure AD, I am unable to successfully perform operations; the server responds to each request in the batch with 401 Unauthorized.

This is _probably_ not specific to delete requests, but that's all I'm using right now.

**Expected behavior**
In general, that using the batch API works when using a `TokenCredential` to authenticate.

More specifically, the [blob batch API documentation](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch) says that "each subrequest will be authorized and authorized separately", so I believe the `Authorization` header with the bearer token (which *is* being correctly included on the outer HTTP request) needs to be included on each batch when using a `TokenCredential`.

**Actual behavior (include Exception or Stack Trace)**
HTTP request body:
```
--batch_REDACTED
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 0

DELETE /REDACTED/REDACTED HTTP/1.1
x-ms-client-request-id: REDACTED
x-ms-return-client-request-id: true
Content-Length: 0

--batch_REDACTED--
```

HTTP response body:
```
--batchresponse_REDACTED
Content-Type: application/http
Content-ID: 0

HTTP/1.1 401 Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
x-ms-error-code: NoAuthenticationInformation
x-ms-request-id: REDACTED
x-ms-version: 2020-02-10
x-ms-client-request-id: REDACTED
Content-Length: 303
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/REDACTED/oauth2/authorize resource_id=https://storage.azure.com

﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:REDACTED
Time:2021-01-28T19:20:44.1124458Z</Message></Error>
```

Exception stack trace:
```
2) Exception Information
---------------------------------------------
Exception Type: System.AggregateException
InnerExceptions: System.Collections.ObjectModel.ReadOnlyCollection`1[System.Exception]
Message: 100 batch operation(s) failed.
TargetSite: Void MoveNext()
Source: Azure.Storage.Blobs.Batch
HResult: -2146233088

StackTrace Information
---------------------------------------------
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<UpdateOperationResponses>d__24.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<SubmitBatchInternal>d__22.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<DeleteBlobsInteral>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.DeleteBlobs(IEnumerable`1 blobUris, DeleteSnapshotsOption snapshotsOption, CancellationToken cancellationToken)
   at <my code>

3) Exception Information
---------------------------------------------
Exception Type: Azure.RequestFailedException
Status: 401
ErrorCode: NoAuthenticationInformation
Message: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:REDACTED
Time:2021-01-28T19:18:33.2297456Z
Status: 401 (Server failed to authenticate the request. Please refer to the information in the www-authenticate header.)
ErrorCode: NoAuthenticationInformation

Headers:
x-ms-error-code: NoAuthenticationInformation
x-ms-request-id: REDACTED
x-ms-version: 2020-02-10
x-ms-client-request-id: REDACTED
Content-Length: 303
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
WWW-Authenticate: REDACTED

TargetSite: Azure.Response DeleteAsync_CreateResponse(Azure.Core.Pipeline.ClientDiagnostics, Azure.Response)
Source: Azure.Storage.Blobs.Batch
HResult: -2146233088

StackTrace Information
---------------------------------------------
   at Azure.Storage.Blobs.BatchRestClient.Blob.DeleteAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.Specialized.BlobBatch.<DeleteBlob>b__15_0(Response response)
   at Azure.Storage.Blobs.Specialized.DelayedResponse.SetLiveResponse(Response live, Boolean throwOnFailure)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<UpdateOperationResponses>d__24.MoveNext()
-----------------------------------
```

**To Reproduce**
Here is a minimal solution that reproduces the issue: [BlobStorageBatchFailure.zip](https://github.com/Azure/azure-sdk-for-net/files/5894278/BlobStorageBatchFailure.zip)

 You'll need to update the "TODO" entry with the URL to a blob container (i.e. "https://storageaccountname.blob.core.windows.net/storagecontainername") that you can authenticate to via Azure AD.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs.Batch 12.5.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10 .NET Framework 4.8
 - IDE and version : Visual Studio 16.8.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi, can you include the beginning of the request or the full request? A sample request looks like this
https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch#sample-request
Of course please redact the information needed.

I tried reproducing your error with the code you attached however I have been successful in making the requests. Does your call when you go to list blobs in the container return success as well?

**Comment by seanmcc-msft** [comment]
Please reopen if you have further questions.

**Comment by akshay181998** [comment]
@amnguye  could you share me the request option that you have created using h[ttps://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch#sample-request](https://docs.microsoft.com/en-us/rest/api/storageservices/blob-batch#sample-request
)
