### ISSUE TITLE
[BUG] AuthenticationFailedException on WSL when PersistentTokenCache.PersistentTokenCacheOptions is specified

### ISSUE THREAD

**Issue by jongio** [Azure/azure-sdk-for-net#18342]
**Describe the bug**

With this:
```csharp
// 1. Create TokenCredential object with TokenCache set
var credentialOne = new InteractiveBrowserCredential(
    new InteractiveBrowserCredentialOptions
    {
        TokenCache = new PersistentTokenCache(new PersistentTokenCacheOptions() { Name = "AuthenticationRecord.cache" })
    });

// 2. Prompt user to authenticate
AuthenticationRecord authRecordWrite = await credentialOne.AuthenticateAsync();
```

Get this:
```
Exception has occurred: CLR/Azure.Identity.AuthenticationFailedException
An exception of type 'Azure.Identity.AuthenticationFailedException' occurred in System.Private.CoreLib.dll but was not handled in user code: 'InteractiveBrowserCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.'
 Inner exceptions found, see $exception in variables window for more details.
 Innermost exception 	 Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException : Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.VerifyPersistence()
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.VerifyPersistence()
   at Azure.Identity.PersistentTokenCache.<GetCacheHelperAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Identity.PersistentTokenCache.<GetCacheHelperAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Identity.PersistentTokenCache.<RegisterCache>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Azure.Identity.MsalClientBase`1.<GetClientAsync>d__16.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Identity.MsalPublicClient.<AcquireTokenInteractiveAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Identity.InteractiveBrowserCredential.<GetTokenViaBrowserLoginAsync>d__32.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Identity.InteractiveBrowserCredential.<AuthenticateImplAsync>d__30.MoveNext()
```

Remove PersistentTokenCacheOptions and this does not happen.
```csharp
// 1. Create TokenCredential object with TokenCache set
var credentialOne = new InteractiveBrowserCredential(
    new InteractiveBrowserCredentialOptions
    {
        TokenCache = new PersistentTokenCache()
    });
```

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
- Azure Identity 1.4.beta
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
```
AuthenticationRecordTest$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.100
 Commit:    5044b93829

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/5.0.100/

Host (useful for support):
  Version: 5.0.0
  Commit:  cf258a14b7

.NET SDKs installed:
  3.1.404 [/usr/share/dotnet/sdk]
  5.0.100 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.10 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.0 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
 - IDE and version : [e.g. Visual Studio 16.3]

VS CODE

azsdke2e
azsdke2e1

**Comment by schaabs** [comment]
The failure you're seeing is due to Gnome keyring not running on the machine, so the library is not able to encrypt the cache.
>'InteractiveBrowserCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.'

I'm not sure if running Gnome keyring on WSL is possible, but alternatively you can configure the cash to fallback to unencrypted storage when encryption is not available.

```c#
// 1. Create TokenCredential object with TokenCache set
var credentialOne = new InteractiveBrowserCredential(
    new InteractiveBrowserCredentialOptions
    {
        TokenCache = new PersistentTokenCache(new PersistentTokenCacheOptions() { Name = "AuthenticationRecord.cache", AllowUnencryptedStorage = true })
    });

// 2. Prompt user to authenticate
AuthenticationRecord authRecordWrite = await credentialOne.AuthenticateAsync();
``` 

Also depending on the version of WSL you're using the `InteractiveBrowserCredential` might fail due to no default system browser being available. If this is the case these options are also available on the `DeviceCodeCredential`.

**Comment by jongio** [comment]
I'm unable to repro this with the latest beta and new API
```csharp
// 1. Create TokenCredential object with TokenCachePersistenceOptions set
var credentialOne = new InteractiveBrowserCredential(
    new InteractiveBrowserCredentialOptions
    {
        TokenCachePersistenceOptions = new TokenCachePersistenceOptions()
        {
            Name = "AuthenticationRecord.cache"
        }
    });

// 2. Prompt user to authenticate
AuthenticationRecord authRecordWrite = await credentialOne.AuthenticateAsync();
```
