### ISSUE TITLE
[BUG] GenerateSasUri throws an exception when using BlobName

### ISSUE THREAD

**Issue by Diazole** [Azure/azure-sdk-for-net#18626]
**Describe the bug**
The exception `SAS Uri cannot be generated. builder.BlobName cannot be set to create a Name SAS.` is thrown when attempting to generate a SAS Uri using `GenerateSasUri` with a `BlobName`.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs#L3191

**Expected behavior**
A SAS Uri should be generated when the container name and blob name are provided.

**Actual behavior (include Exception or Stack Trace)**

```
System.InvalidOperationException: SAS Uri cannot be generated. builder.BlobName cannot be set to create a Name SAS.
   at Azure.Storage.Blobs.BlobContainerClient.GenerateSasUri(BlobSasBuilder builder)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Serilog.AspNetCore.RequestLoggingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**To Reproduce**
```csharp
private static Uri GetServiceSasUriForBlob(BlobClient blobClient, string storedPolicyName = null)
{
    if (blobClient.CanGenerateSasUri)
    {
        BlobSasBuilder sasBuilder = new BlobSasBuilder()
        {
            BlobContainerName = blobClient.GetParentBlobContainerClient().Name,
            BlobName = blobClient.Name,
            Resource = "b"
        };

        if (storedPolicyName == null)
        {
            sasBuilder.ExpiresOn = DateTimeOffset.UtcNow.AddHours(1);
            sasBuilder.SetPermissions(BlobSasPermissions.Read |
                BlobSasPermissions.Write);
        }
        else
        {
            sasBuilder.Identifier = storedPolicyName;
        }

        Uri sasUri = blobClient.GenerateSasUri(sasBuilder);
        Console.WriteLine("SAS URI for blob is: {0}", sasUri);
        Console.WriteLine();

        return sasUri;
    }
    else
    {
        Console.WriteLine(@"BlobClient must be authorized with Shared Key 
                          credentials to create a service SAS.");
        return null;
    }
}
```

**Environment:**
 - Azure.Storage.Blobs 12.8.0
 - Windows 10 .NET Core 3.1
 - Visual Studio

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by amnguye** [comment]
Hi, your code snippet does not match the stack trace. Your stack trace is showing
```
at Azure.Storage.Blobs.BlobContainerClient.GenerateSasUri(BlobSasBuilder builder)
```
when in your code snippet I see you're only calling `BlobClient.GenerateSasUri`. Can you provide the code snippet that's generating this error?

For clarification as well. When calling `BlobContainerClient.GenerateSasUri` it will generate a Container SAS not a Blob SAS. BlobClient will also produce a Blob SAS not a Container SAS. So if you set the Blob Name in the BlobSasBuilder when attempting to create a container SAS, this error will throw to prevent user error.

**Comment by Diazole** [comment]
Sorry, my bad.

As you say, I was trying to create a Blob SAS using `BlobContainerClient.GenerateSasUri` instead of `BlobClient.GenerateSasUri`.
