### ISSUE TITLE
UpdateRsaHsmKey is failing assertion

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#18800]
The test `UpdateRsaHsmKey` is failing on Windows platforms with:

```
Error message
Expected is <System.Byte[4]>, actual is <System.Byte[3]>
Values differ at index [0]
Expected: 0
But was:  1


Stack trace
   at Azure.Security.KeyVault.Keys.Tests.KeysTestBase.AssertKeysEqual(JsonWebKey exp, JsonWebKey act) in D:\a\_work\1\s\sdk\keyvault\Azure.Security.KeyVault.Keys\tests\KeysTestBase.cs:line 172
   at Azure.Security.KeyVault.Keys.Tests.KeysTestBase.AssertKeyVaultKeysEqual(KeyVaultKey exp, KeyVaultKey act) in D:\a\_work\1\s\sdk\keyvault\Azure.Security.KeyVault.Keys\tests\KeysTestBase.cs:line 160
   at Azure.Security.KeyVault.Keys.Tests.KeyClientLiveTests.<UpdateRsaHsmKey>d__14.MoveNext() in D:\a\_work\1\s\sdk\keyvault\Azure.Security.KeyVault.Keys\tests\KeyClientLiveTests.cs:line 216
```

**Comment by heaths** [comment]
I can't reproduce this locally, but after reviewing re-recorded test data, I wonder if this is the leading 0 being trimmed off for some reason in some cases. The exponent in base64url-encoded text is `AAEAAQ`, which is `byte[] { 0, 1, 0, 1 }`. Given the actual buffer is 1 byte short and starts with a 1, this seems the likely cause. I don't think this is an endian problem either, since we're seeing it across different platforms.

**Comment by heaths** [comment]
Given this isn't repro'ing 100% consistently, I'm wondering if something changed service-side. I'm going to enable content logging for now to examine when this fails.

**Comment by heaths** [comment]
I have a test recording that shows the service response after key creation has exponent {0, 1, 0, 1} but the response after updating the key (just updating the expiration date) is {1, 0, 1}.

**Comment by heaths** [comment]
Removing the test-reliability label since I've worked around this by ignoring the leading zero for the exponent when asserting equivalency. I'm following up with the service team.

**Comment by heaths** [comment]
Discussions indicate this was not intentional, but not really a problem either.
