### ISSUE TITLE
[synapse] MonitorPipelineRuns fails on nightly lane with NRE but not locally

### ISSUE THREAD

**Issue by chamons** [Azure/azure-sdk-for-net#18832]
I am seeing this failure on the nightly lane but not locally, even with a clean new TestResources resource.
```
2021-02-16T19:46:41.3626618Z Microsoft (R) Test Execution Command Line Tool Version 16.8.3
2021-02-16T19:46:41.3627813Z Copyright (c) Microsoft Corporation.  All rights reserved.
2021-02-16T19:46:41.3628264Z 
2021-02-16T19:46:41.4498896Z Starting test execution, please wait...
2021-02-16T19:46:41.4944839Z A total of 1 test files matched the specified pattern.
2021-02-16T19:46:42.2625482Z NUnit Adapter 3.13.0.0: Test execution started
2021-02-16T19:46:42.2773240Z Running all tests in /mnt/vss/_work/1/s/artifacts/bin/Azure.Analytics.Synapse.Monitoring.Tests/Debug/netcoreapp2.1/Azure.Analytics.Synapse.Monitoring.Tests.dll
2021-02-16T19:46:42.4519352Z    NUnit3TestExecutor converted 5 of 5 NUnit test cases
2021-02-16T19:46:45.1327058Z   Failed MonitorPipelineRuns [1 s]
2021-02-16T19:46:45.1328504Z   Error Message:
2021-02-16T19:46:45.1329869Z    System.NullReferenceException : Object reference not set to an instance of an object.
2021-02-16T19:46:45.1330953Z   Stack Trace:
2021-02-16T19:46:45.1332053Z      at Azure.Analytics.Synapse.Monitoring.Samples.Sample1_PipelineMonitoring.MonitorPipelineRuns() in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Monitoring/tests/samples/Sample1_PipelineMonitoring.cs:line 32
2021-02-16T19:46:45.1336576Z   Failed TestListSparkApplications [544 ms]
2021-02-16T19:46:45.1337421Z   Error Message:
2021-02-16T19:46:45.1338200Z    System.ArgumentException : Expected: IEnumerable But was: null
2021-02-16T19:46:45.1338963Z Parameter name: actual
2021-02-16T19:46:45.1339671Z   Stack Trace:
2021-02-16T19:46:45.1340579Z      at NUnit.Framework.Internal.ConstraintUtils.RequireActual[T](Object actual, String paramName, Boolean allowNull)
2021-02-16T19:46:45.1341614Z    at NUnit.Framework.Constraints.CollectionConstraint.ApplyTo[TActual](TActual actual)
2021-02-16T19:46:45.1342560Z    at NUnit.Framework.Constraints.NotConstraint.ApplyTo[TActual](TActual actual)
2021-02-16T19:46:45.1343568Z    at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
2021-02-16T19:46:45.1344861Z    at Azure.Analytics.Synapse.Monitoring.Tests.MonitoringClientLiveTests.TestListSparkApplications() in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Monitoring/tests/MonitoringClientLiveTests.cs:line 43
2021-02-16T19:46:45.1346064Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
2021-02-16T19:46:45.1347017Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2021-02-16T19:46:45.1348021Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2021-02-16T19:46:45.1348995Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
2021-02-16T19:46:45.1350357Z    at NUnit.Framework.Internal.Co
```

Given current investment in Synapse, I'm seeing [LiveOnly] for now.

**Comment by jsquire** [comment]
Given the age of this issue, closing this as stale.  If tests are still failing, please file a new issue.
