### ISSUE TITLE
[QUERY] Search: SearchClient.Search  Value cannot be null. (Parameter 's')

### ISSUE THREAD

**Issue by Valdeminas** [Azure/azure-sdk-for-net#18878]
**Query/Question**
SearchClient.Search sometimes randomly fails with a very unclear error message. Could you give some guidance what could be the problem and how it could be resolved? Retrying the same query, does not replicate the issue :(
Error:
``System.ArgumentNullException: Value cannot be null. (Parameter 's')
   at Azure.Search.Documents.SearchDateTimeConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.JsonPropertyInfo`1.ReadJsonAndSetMember(Object obj, ReadStack& state, Utf8JsonReader& reader)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadCore[TValue](JsonReaderState& readerState, Boolean isFinalBlock, ReadOnlySpan`1 buffer, JsonSerializerOptions options, ReadStack& state, JsonConverter converterBase)
   at System.Text.Json.JsonSerializer.ReadAsync[TValue](Stream utf8Json, Type returnType, JsonSerializerOptions options, CancellationToken cancellationToken)
   at Azure.Search.Documents.Models.SearchResult`1.DeserializeAsync(JsonElement element, ObjectSerializer serializer, JsonSerializerOptions options, Boolean async, CancellationToken cancellationToken)
   at Azure.Search.Documents.Models.SearchResults`1.DeserializeAsync(Stream json, ObjectSerializer serializer, Boolean async, CancellationToken cancellationToken)
   at Azure.Search.Documents.SearchClient.SearchInternal[T](SearchOptions options, String operationName, Boolean async, CancellationToken cancellationToken)``
**Environment:**
- Azure.Search.Documents v11
- .NET SDK 5.0.200-preview.20614.14
- IDE and version : Visual Studio Version 16.9.0 Preview 3.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
From the error message, it looks like the [call to `DateTime.Parse()`](https://github.com/Azure/azure-sdk-for-net/blob/7276cc9b09ee9e97d47f5c0c0b37b5b238e54734/sdk/search/Azure.Search.Documents/src/Serialization/SearchDateTimeConverter.cs#L30) in `SearchDateTimeConverter.Read()` is passing null as the argument.

**Comment by Valdeminas** [comment]
So can we do anything about it or should we wait for a fix on your end?
Also, since the problem appears intermittently, should we be looking for something on our end?
Like records with empty date tame values? Or requests made with some strange datetime culture settings?

**Comment by AlexGhiondea** [comment]
@Valdeminas do you have a small sample that we can run on our end?

**Comment by Valdeminas** [comment]
I can send you the code related to our search service an deserializing the response. However, I don't think I would be able to replicate our index, against which we are running our searches.

Would that work?

**Comment by Mohit-Chakraborty** [comment]
> Also, since the problem appears intermittently, should we be looking for something on our end?
Like records with empty date tame values?

I would think that is the issue.

But then you say,
> Retrying the same query, does not replicate the issue

So, the same call to the service against the same dataset sometimes succeeds?

It would really help if you can reproduce the issue against a small index and dataset. That way we can understand the root cause.

**Comment by Valdeminas** [comment]
Hi.

Yeah. So we notice from the logs, that one user gets this error.
Once we retry the query, the user was using, the error no longer appears.

However, these are not exactly the same datasets.
We have an indexer running on our azure account, so the index is constantly being updated.

However, since you think entries with empty DateTime values might be at fault here, maybe there are states in which our index contains these empty values? And then, once we retry, the indexer has already updated the index, and empty values are no longer present?

I'll investigate this line on our end, and let you know if we come up with anything.

**Comment by Mohit-Chakraborty** [comment]
Thanks. Interested to hear what you find.

**Comment by lucasroccoCM** [comment]
Hi guys! How are you?
I received the same problem described below, and I solved this turning my .NET Class property into Datetime? "Nullable" because, some indexes has null date value. 
{
            "@search.score": 6.1858664,
            "id": "5326",
            "title": "CALENDÁRIO ACADÊMICO 2021.1 EAD (5).pdf",
            "content": "Calendário Acadêmico 21.1 EAD atualizado em 10/06",
            "date": null,
            "url": null
        },

/// <summary>
        /// Data do item indexado
        /// </summary>
        [JsonPropertyName("date")]
        [SearchableField(IsFilterable = true, IsSortable = true)]
        public DateTime? Date { get; set; }

I hope this helped someone.
My best regards,
Lucas Rocco

**Comment by Valdeminas** [comment]
Yup. Sorry it took so long to reply.

In our case, we had a ModifiedDate field which was being set to null initially, and the indexer would sometimes store it as such and we would get the error when trying to deserialize query results containing a null ModifiedDate field.

Making the field nullable in our deserialized results class solved the problem :)

Closing the issue and thanks for the support!

**Comment by Mohit-Chakraborty** [comment]
Thanks for the update @Valdeminas. And thanks @lucasroccoCM for sharing your solution.
It will help future users who find this discussion.
