### ISSUE TITLE
Partition context binding in new webjob event hub extensions

### ISSUE THREAD

**Issue by remoba** [Azure/azure-sdk-for-net#18907]
**Query/Question**
I am not really sure if the new web job event hub extension package is usable yet, but can I still access the partition context when processing a batch of event hub messages? I tried running this piece of code for example

```
public Task MyEventHubListener(
            [EventHubTrigger(
                eventHubName: "",
                Connection = "MyConnection",
                ConsumerGroup = "$Default")] EventData[] eventHubMessages,
            PartitionContext partitionContext,
            CancellationToken cancellationToken)
        {
        }
```

And got this exception:

```
fail: Function.MyEventHubListener[3]
      Executed 'Functions.MyEventHubListener' (Failed, Id=85c28c5b-1fee-4a4d-9846-08151fac91c4, Duration=621ms)
      Microsoft.Azure.WebJobs.Host.FunctionInvocationException: Exception while executing function: Functions.MyEventHubListener
       ---> System.InvalidOperationException: Exception binding parameter 'partitionContext'
       ---> System.InvalidOperationException: Binding data for 'partitionContext' is not of expected type PartitionContext.
         at Microsoft.Azure.WebJobs.Host.Bindings.Data.ClassDataBinding`1.BindAsync(BindingContext context) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\Data\ClassDataBinding.cs:line 65
         at Microsoft.Azure.WebJobs.Host.Triggers.TriggeredFunctionBinding`1.BindCoreAsync(ValueBindingContext context, Object value, IDictionary`2 parameters) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Triggers\TriggeredFunctionBinding.cs:line 97
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.DelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\DelayedException.cs:line 27
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.PrepareParametersAsync() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 892
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 470
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 283
         --- End of inner exception stack trace ---
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 330
         at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 94
```

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.EventHubs 5.0.0-beta.1

**Comment by jsquire** [comment]
//cc: @JoshLove-msft

**Comment by jsquire** [comment]
Hi @remoba.  Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Hey @remoba, thank you for the heads up. 

Can you, please, give us some details about how do you use the `PartitionContext` in your function?

**Comment by remoba** [comment]
Hey @pakrym, I am actually only logging the partition id in there, but just to clarify the entire function `MyEventHubListener` doesn't trigger. I was wondering if I am doing something wrong or if it simply isn't working yet

**Comment by JoshLove-msft** [comment]
Is your function using the [PartitionContext ](https://docs.microsoft.com/en-us/dotnet/api/azure.messaging.eventhubs.consumer.partitioncontext?view=azure-dotnet) (and EventData) from the new EventHubs [library](https://www.nuget.org/packages/Azure.Messaging.EventHubs/)?

**Comment by remoba** [comment]
Hey @JoshLove-msft, yes I do, 
`Azure.Messaging.EventHubs.Consumer.PartitionContext` from assembly `Azure.Messaging.EventHubs, Version=5.3.0.0`

I should have probably mentioned I am not running this on any Azure platform, just a normal executable with the web job SDK.

Also this is unrelated but I've also seen I can no longer bind to configuration values for the `ConsumerGroup` property of the `EventHubTrigger` attribute.

This used to work:

`ConsumerGroup = "%MyConfigSection:MyConfigValue%`

but it no longer does

**Comment by JoshLove-msft** [comment]
Can you provide the function and the config you are using? Also, how can you tell that it is not working?

I just tested this out, and I was able to bind to a consumer group from the config:
```cs 
public static void ProcessSingleEvent(
  [EventHubTrigger(TestHubName, Connection = "TestConnection", ConsumerGroup = "MyConsumerGroup")]
  string evt, 
  DateTime enqueuedTimeUtc, 
  IDictionary<string, object> properties)
```
I verified that the ConsumerGroup value from the config is being passed through to the underlying processor.

**Comment by remoba** [comment]
I am honestly more concerned with the `PartitionContext` issue. I want to use the partition id of the message batch as a dimension in our instrumentation infrastructure, so I correlate metrics to specific partitions. Is the binding to the `PartitionContext` parameter something that is supposed to work right now?

**Comment by pakrym** [comment]
It was supposed to work but doesn't. The fix is in https://github.com/Azure/azure-sdk-for-net/issues/18907

**Comment by remoba** [comment]
@pakrym That's great to hear. Do you know when the next beta package gets pushed to nuget.org? Or is there another way I can consume it?

Also should I open a separate issue for the `ConsumerGroup` configuration binding that I also mentioned here? As far as I understand the issue still exists

**Comment by pakrym** [comment]
>@pakrym That's great to hear. Do you know when the next beta package gets pushed to nuget.org? Or is there another way I can consume it?

There would be another preview early next week but you can also grab a nightly of the https://pkgs.dev.azure.com/azure-sdk/public/_packaging/azure-sdk-for-net/nuget/v3/index.json feed. It might take until tomorrow or later today for a build with #19114 to be produced.

>Also should I open a separate issue for the ConsumerGroup configuration binding that I also mentioned here? As far as I understand the issue still exists

It's fixed in one of the previous PRs.

**Comment by remoba** [comment]
Tried [this nightly](https://dev.azure.com/azure-sdk/public/_packaging?_a=package&feed=azure-sdk-for-net&package=Microsoft.Azure.WebJobs.Extensions.EventHubs&protocolType=NuGet&version=5.0.0-alpha.20210302.1&view=overview) and can confirm both issues are resolved, thank you

**Comment by pakrym** [comment]
Thank you for trying the preview and filing the issue!
