### ISSUE TITLE
EncryptDecryptRoundTrip(RSA-OAEP) failed on macOS on netcoreapp2.1

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#18947]
This isn't a new test, though recently some updates were made to related code. It may be a fluke and I'm working with the service team using the x-ms-request-id buried elsewhere in the logs.

```
Azure.RequestFailedException : Error occurred while decoding OAEP padding.
Status: 400 (Bad Request)
ErrorCode: BadParameter

Content:
{"error":{"code":"BadParameter","message":"Error occurred while decoding OAEP padding."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-keyvault-region: westus2
x-ms-request-id: REDACTED
x-ms-keyvault-service-version: 1.2.164.2
x-ms-keyvault-network-info: conn_type=Ipv4;addr=199.19.85.34;act_addr_fam=InterNetwork;
X-Powered-By: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Tue, 23 Feb 2021 11:43:45 GMT
Content-Length: 89
Content-Type: application/json; charset=utf-8
Expires: -1


Stack trace
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken) in /_/sdk/keyvault/Azure.Security.KeyVault.Shared/src/KeyVaultPipeline.cs:line 266
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TContent,TResult](RequestMethod method, TContent content, Func`1 resultFactory, CancellationToken cancellationToken, String[] path) in /_/sdk/keyvault/Azure.Security.KeyVault.Shared/src/KeyVaultPipeline.cs:line 177
   at Azure.Security.KeyVault.Keys.Cryptography.RemoteCryptographyClient.DecryptAsync(DecryptParameters parameters, CancellationToken cancellationToken) in /_/sdk/keyvault/Azure.Security.KeyVault.Keys/src/Cryptography/RemoteCryptographyClient.cs:line 94
   at Azure.Security.KeyVault.Keys.Cryptography.RemoteCryptographyClient.Azure.Security.KeyVault.Keys.Cryptography.ICryptographyProvider.DecryptAsync(DecryptParameters parameters, CancellationToken cancellationToken) in /_/sdk/keyvault/Azure.Security.KeyVault.Keys/src/Cryptography/RemoteCryptographyClient.cs:line 354
   at Azure.Security.KeyVault.Keys.Cryptography.CryptographyClient.DecryptAsync(DecryptParameters parameters, CancellationToken cancellationToken) in /_/sdk/keyvault/Azure.Security.KeyVault.Keys/src/Cryptography/CryptographyClient.cs:line 397
   at Azure.Security.KeyVault.Keys.Cryptography.CryptographyClient.DecryptAsync(EncryptionAlgorithm algorithm, Byte[] ciphertext, CancellationToken cancellationToken) in /_/sdk/keyvault/Azure.Security.KeyVault.Keys/src/Cryptography/CryptographyClient.cs:line 344
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass2_0`1.<<AwaitAndValidateDiagnosticScope>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/DiagnosticScopeValidatingInterceptor.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, String expectedName, String methodName, Boolean strict) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/DiagnosticScopeValidatingInterceptor.cs:line 112
   at Azure.Security.KeyVault.Keys.Tests.CryptographyClientLiveTests.EncryptDecryptRoundTrip(EncryptionAlgorithm algorithm) in /Users/runner/work/1/s/sdk/keyvault/Azure.Security.KeyVault.Keys/tests/CryptographyClientLiveTests.cs:line 60
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by heaths** [comment]
Haven't seen this fail since. Will keep an eye on it.
