### ISSUE TITLE
[BUG] Azure.Search.Documents.Tests.ManualRetryDelayTests.ClampDelay test case is non deterministic

### ISSUE THREAD

**Issue by m-nash** [Azure/azure-sdk-for-net#19002]
**Describe the bug**
Azure.Search.Documents.Tests.ManualRetryDelayTests.ClampDelay test case sometimes passes and sometimes fails and it appears to be due to a timing issue

**Expected behavior**
Test should be deterministic

**Actual behavior (include Exception or Stack Trace)**
Test passes sometimes and fails others simply by rerunning

**To Reproduce**
Executed the following pipeline https://github.com/Azure/azure-sdk-for-net/pull/18968/checks?check_run_id=1966779626 enough times and you will see it fail randomly.

**Environment:**
N/A

**Comment by Mohit-Chakraborty** [comment]
Thank you for your feedback.  I will take a look.

**Comment by pakrym** [comment]
Another failure https://dev.azure.com/azure-sdk/public/_build/results?buildId=799975&view=ms.vss-test-web.build-test-results-tab&runId=17611868&resultId=110485&paneView=debug

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=827749&view=ms.vss-test-web.build-test-results-tab&runId=18087660&resultId=111976&paneView=debug

```
ClampDelay

Result Details
Failed 24m ago on 63d4e3a7c000000
Duration0:00:00.870
Ownernot available
Date started4/6/2021, 12:14:45 PM
Date completed4/6/2021, 12:14:46 PM
Failing since24m ago
Failing since build20210406.6

Debug

Work items

Attachments

History

Attachments*

Error message
Expected a delay between 248ms and 500ms, not 247
Expected: True
But was:  False


Stack trace
   at Azure.Search.Documents.Tests.ManualRetryDelayTests.ClampDelay() in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/ManualRetryDelayTests.cs:line 79
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by pakrym** [comment]
```
ClampDelay

Result Details
Failed 20m ago on 0c27daacc00000G
Duration0:00:00.843
Ownernot available
Date started4/29/2021, 12:43:13 PM
Date completed4/29/2021, 12:43:14 PM
Failing since20m ago
Failing since build20210429.10

Debug

Work items

Attachments

History

Attachments*

Error message
Expected a delay between 248ms and 500ms, not 247
Expected: True
But was:  False


Stack trace
   at Azure.Search.Documents.Tests.ManualRetryDelayTests.ClampDelay() in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/ManualRetryDelayTests.cs:line 79
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by pakrym** [comment]
```
ClampDelay

Result Details
Failed 46m ago on 27ff5587c000000
Duration0:00:00.770
Ownernot available
Date started5/3/2021, 9:04:54 AM
Date completed5/3/2021, 9:04:55 AM
Failing since46m ago
Failing since build20210503.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected a delay between 248ms and 500ms, not 244
Expected: True
But was:  False


Stack trace
   at Azure.Search.Documents.Tests.ManualRetryDelayTests.ClampDelay() in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/ManualRetryDelayTests.cs:line 79
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
```

**Comment by pakrym** [comment]
```
ClampDelay

Result Details
Failed 12m ago on f345a5adc000002
Duration0:00:02.010
Ownernot available
Date started5/20/2021, 10:22:51 AM
Date completed5/20/2021, 10:22:53 AM
Failing since12m ago
Failing since build20210520.6

Debug

Work items

Attachments

History

Attachments*

Error message
Expected a delay between 248ms and 500ms, not 567
Expected: True
But was:  False


Stack trace
   at Azure.Search.Documents.Tests.ManualRetryDelayTests.ClampDelay() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\ManualRetryDelayTests.cs:line 79
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by pakrym** [comment]
```
ClampDelay

Result Details
Failed 8h ago on 352d277fc000000
Duration0:00:02.390
Ownernot available
Date started6/1/2021, 1:22:43 AM
Date completed6/1/2021, 1:22:45 AM
Failing since8h ago
Failing since build20210601.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected a delay between 248ms and 500ms, not 646
Expected: True
But was:  False


Stack trace
   at Azure.Search.Documents.Tests.ManualRetryDelayTests.<ClampDelay>d__2.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\ManualRetryDelayTests.cs:line 79
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by pakrym** [comment]
@Mohit-Chakraborty can we disable this test, please?
