### ISSUE TITLE
[Flaky Test] ProducerCannotRetrieveMetadataWhenProxyIsInvalid

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#19106]
```

ProducerCannotRetrieveMetadataWhenProxyIsInvalid

Result Details
Failed 24m ago on Mac-1614625516396
Duration0:07:28.150
Ownernot available
Date started3/1/2021, 11:24:05 AM
Date completed3/1/2021, 11:31:33 AM
Failing since24m ago
Failing since build20210301.2

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: instance of <System.Net.WebSockets.WebSocketException> or instance of <System.TimeoutException>
But was:  <System.NullReferenceException: Object reference not set to an instance of an object.
at System.Net.WebSockets.ClientWebSocket.SendAsync(ArraySegment1 buffer, WebSocketMessageType messageType, Boolean endOfMessage, CancellationToken cancellationToken) at Microsoft.Azure.Amqp.Transport.WebSocketTransport.WriteAsync(TransportAsyncCallbackArgs args) at Microsoft.Azure.Amqp.AsyncIO.AsyncBufferWriter.Write(TransportAsyncCallbackArgs args) --- End of stack trace from previous location where exception was thrown --- at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, Uri connectionEndpoint, EventHubsTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout) in /_/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConnectionScope.cs:line 402 at Microsoft.Azure.Amqp.FaultTolerantAmqpObject1.OnCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout) at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout)
at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenManagementLinkAsync(TimeSpan timeout, CancellationToken cancellationToken) in /_/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpConnectionScope.cs:line 243
at Microsoft.Azure.Amqp.FaultTolerantAmqpObject1.OnCreateAsync(TimeSpan timeout) at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton1.GetOrCreateAsync(TimeSpan timeout) at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPartitionPropertiesAsync(String partitionId, EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken) in /_/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpClient.cs:line 330 at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPartitionPropertiesAsync(String partitionId, EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken) in /_/sdk/eventhub/Azure.Messaging.EventHubs/src/Amqp/AmqpClient.cs:line 367 at Azure.Messaging.EventHubs.EventHubConnection.GetPartitionPropertiesAsync(String partitionId, EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken) in /_/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubConnection.cs:line 370 at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.GetPartitionPropertiesAsync(String partitionId, CancellationToken cancellationToken) in /_/sdk/eventhub/Azure.Messaging.EventHubs/src/Producer/EventHubProducerClient.cs:line 439 at Azure.Messaging.EventHubs.Tests.EventHubProducerClientLiveTests.<>c__DisplayClass36_1.<<ProducerCannotRetrieveMetadataWhenProxyIsInvalid>b__2>d.MoveNext() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Producer/EventHubProducerClientLiveTests.cs:line 1188 --- End of stack trace from previous location where exception was thrown --- at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter1.BlockUntilCompleted()
at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
at NUnit.Framework.Internal.ExceptionHelper.RecordException(Delegate parameterlessDelegate, String parameterName)>


Stack trace
   at Azure.Messaging.EventHubs.Tests.EventHubProducerClientLiveTests.ProducerCannotRetrieveMetadataWhenProxyIsInvalid() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Producer/EventHubProducerClientLiveTests.cs:line 1188

```

cc @jsquire

**Comment by jsquire** [comment]
This failure occurred within the AMQP library in a code path not controlled by the test suite or client library.   From inspection, it appears to be a transient network issue, as the other two operations using the same approach passed their assertion.

I'm going to close this for now, but if we continue to see this occur,  I'll open an issue for the AMQP library and ask them to investigate further.
