### ISSUE TITLE
 [search]  Flaky tests in weekly runs

### ISSUE THREAD

**Issue by ShivangiReja** [Azure/azure-sdk-for-net#19148]
Search tests fail in weekly runs with:

  > Error Message:
   Expected exception of type RequestFailedException, not Microsoft.VisualStudio.TestPlatform.TestHost.DebugAssertException: Method <method> failed with '', and was translated to Microsoft.VisualStudio.TestPlatform.TestHost.DebugAssertException to avoid terminating the process hosting the test.
   at Microsoft.VisualStudio.TestPlatform.TestHost.TestHostTraceListener.ShowDialog(String stackTrace, String message, String detailMessage, String _)
   at Azure.Core.Pipeline.ClientDiagnostics.ExtractFailureContent(String content, ResponseHeaders responseHeaders, String& message, String& errorCode, IDictionary`2& additionalInfo) in /_/sdk/search/Azure.Search.Documents/src/Utilities/ClientDiagnostics.ExtractFailureContent.cs:line 56
   at Azure.Core.Pipeline.ClientDiagnostics.CreateRequestFailedExceptionAsync(Response response, String message, String errorCode, IDictionary`2 additionalInfo, Exception innerException) in /_/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs:line 56
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Search.Documents.DocumentsRestClient.AutocompletePostAsync(AutocompleteOptions autocompleteRequest, CancellationToken cancellationToken) in /_/sdk/search/Azure.Search.Documents/src/Generated/DocumentsRestClient.cs:line 477
   at Azure.Search.Documents.SearchClient.AutocompleteInternal(String searchText, String suggesterName, AutocompleteOptions options, Boolean async, CancellationToken cancellationToken) in /_/sdk/search/Azure.Search.Documents/src/SearchClient.cs:line 1093
   at Azure.Search.Documents.SearchClient.AutocompleteAsync(String searchText, String suggesterName, AutocompleteOptions options, CancellationToken cancellationToken) in /_/sdk/search/Azure.Search.Documents/src/SearchClient.cs:line 1067
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass2_0`1.<<AwaitAndValidateDiagnosticScope>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/DiagnosticScopeValidatingInterceptor.cs:line 64
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, String expectedName, String methodName, Boolean strict) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/DiagnosticScopeValidatingInterceptor.cs:line 112
   at Azure.Search.Documents.Tests.AutocompleteTests.<>c__DisplayClass3_0.<<ThrowsWhenNoSuggesterName>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/tests/DocumentOperations/AutocompleteTests.cs:line 58
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Search.Documents.Tests.SearchTestBase.CatchAsync[T](Func`1 action) in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/tests/Utilities/SearchTestBase.cs:line 125
  Stack Trace:
     at Azure.Search.Documents.Tests.SearchTestBase.CatchAsync[T](Func`1 action) in /mnt/vss/_work/1/s/sdk/search/Azure.Search.Documents/tests/Utilities/SearchTestBase.cs:line 125

For more details check here:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=757186&view=results
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=757385&view=results

**Comment by ShivangiReja** [comment]
@Mohit-Chakraborty Search tests are failing in nightly runs
 with `Expected exception of type RequestFailedException, not Microsoft.VisualStudio.TestPlatform.TestHost.DebugAssertException` error, could you please look into that?

For details please check:
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=794596&view=logs&j=68082d65-ebf7-5f3f-494d-d3fd09e80dd6&t=6f6444ca-c101-5878-5224-de85502bb056&l=61164
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=782873&view=logs&j=9f6e9dd9-0daa-5061-5c37-5c529436a384&t=7d15db3d-f1cc-50eb-c1e0-80c490f74744&l=774
* https://dev.azure.com/azure-sdk/internal/_build/results?buildId=794557&view=logs&j=6bc677fc-eaaa-5aa2-d61c-5bfd25cc27a2&t=8fca1c0e-70a0-5cc4-a276-fb966150ba33&l=792

**Comment by Mohit-Chakraborty** [comment]
The above failures were caused in `ExtractFailureContent()` which had an assertion to fail on nested errors.
I see that the code has been refactored and the assertion is no longer there.
So, we are not seeing failures due to this issue. There is a separate issue about handling nested errors.
