### ISSUE TITLE
[Flaky test] StreamCanHoldLongData

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#19182]
```
StreamCanHoldLongData

Result Details
Failed 37m ago on 35527c9ec000000
Duration0:00:34.120
Ownernot available
Date started3/3/2021, 1:20:49 PM
Date completed3/3/2021, 1:21:23 PM
Failing since37m ago
Failing since build20210303.10

Debug

Work items

Attachments

History

Attachments*

Error message
System.AggregateException : One or more errors occurred. (Rethrown)
----> NUnit.Framework.Internal.NUnitException : Rethrown
----> System.OutOfMemoryException : Exception of type 'System.OutOfMemoryException' was thrown.


Stack trace
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at NUnit.Framework.Internal.Commands.TimeoutCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TimeoutCommand.cs:line 102
--NUnitException
   at NUnit.Framework.Internal.Reflect.InvokeMethod(MethodInfo method, Object fixture, Object[] args) in D:\a\1\s\src\NUnitFramework\framework\Internal\Reflect.cs:line 274
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context) in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TestMethodCommand.cs:line 64
   at NUnit.Framework.Internal.Commands.TimeoutCommand.<>c__DisplayClass2_0.<Execute>b__0() in D:\a\1\s\src\NUnitFramework\framework\Internal\Commands\TimeoutCommand.cs:line 102
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--OutOfMemoryException
   at System.Buffers.TlsOverPerCoreLockedStacksArrayPool`1.Rent(Int32 minimumLength)
   at Azure.Storage.Shared.PooledMemoryStream.BufferStreamPartitionInternal(Stream stream, Int64 minCount, Int64 maxCount, Int64 absolutePosition, ArrayPool`1 arrayPool, Nullable`1 maxArrayPoolRentalSize, Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\storage\Azure.Storage.Common\src\Shared\PooledMemoryStream.cs:line 135
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 33
   at Azure.Storage.Tests.PooledMemoryStreamTests.StreamCanHoldLongData() in D:\a\_work\1\s\sdk\storage\Azure.Storage.Common\tests\PooledMemoryStreamTests.cs:line 64

```

@kasobol-msft does this look concerning to you?

**Comment by kasobol-msft** [comment]
We've enabled this test recently hoping that new agents will be large enough to accommodate it. Which build is this?

**Comment by kasobol-msft** [comment]
Maybe we should mark these tests as `[NonParallelizable]` so that demand for resources is less when they run.

**Comment by pakrym** [comment]
PR CI tests
