### ISSUE TITLE
[BUG] DefaultAzureCredential complains about expired refresh token, but does not prompt for interactive auth: "AADSTS70008: The provided authorization code or refresh token has expired due to inactivity. Send a new interactive authorization request for this user and resource.

### ISSUE THREAD

**Issue by ayeltsov** [Azure/azure-sdk-for-net#19201]
**Describe the bug**

Can't get token with DefaultAzureCredential interactive auth.
Note that #11642 talks about similar situation and even has [comment ](https://github.com/Azure/azure-sdk-for-net/issues/11642#issuecomment-624782472) with wording to "treat this authentication mechanism as unavailable in this case and continue with the rest of the DefaultAzureCredential flow rather than failing" - but that has been merged in 1.2, and I'm on 1.3

**Expected behavior**

Upon discovering that cached token is unusable, I expected library to present me with interactive authentication request

**Actual behavior (include Exception or Stack Trace)**

````
Azure.Identity.AuthenticationFailedException
  HResult=0x80131500
  Message=Azure CLI authentication failed due to an unknown error. ERROR: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70008: The provided authorization code or refresh token has expired due to inactivity. Send a new interactive authorization request for this user and resource.\r\nTrace ID: fddb1c98-20a3-400b-9448-a22141cf0300\r\nCorrelation ID: 9c48170d-d932-4cf9-9dd5-13574a735234\r\nTimestamp: 2021-03-04 01:10:05Z","error_codes":[70008],"timestamp":"2021-03-04 01:10:05Z","trace_id":"fddb1c98-20a3-400b-9448-a22141cf0300","correlation_id":"9c48170d-d932-4cf9-9dd5-13574a735234","error_uri":"https://login.microsoftonline.com/error?code=70008"}
Traceback (most recent call last):
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\knack\knack\cli.py", line 206, in invoke
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 346, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\six\six.py", line 693, in reraise
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 320, in execute
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\commands\__init__.py", line 169, in __call__
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\__init__.py", line 440, in default_command_handler
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-profile\azure\cli\command_modules\profile\custom.py", line 61, in get_access_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\_profile.py", line 569, in get_raw_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\azure-cli-core\azure\cli\core\_profile.py", line 880, in retrieve_token_for_user
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\authentication_context.py", line 145, in acquire_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\authentication_context.py", line 128, in _acquire_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\authentication_context.py", line 143, in token_func
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\token_request.py", line 352, in get_token_from_cache_with_refresh
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\token_request.py", line 128, in _find_token_from_cache
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\cache_driver.py", line 199, in find
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\cache_driver.py", line 184, in _refresh_entry_if_necessary
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\cache_driver.py", line 160, in _acquire_new_token_from_mrrt
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\token_request.py", line 138, in _get_token_with_token_response
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\token_request.py", line 344, in _get_token_with_refresh_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\token_request.py", line 113, in _oauth_get_token
  File "C:\Users\VSSADM~1\AppData\Local\Temp\pip-install-e5ce5s7r\adal\adal\oauth2_client.py", line 289, in get_token
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS70008: The provided authorization code or refresh token has expired due to inactivity. Send a new interactive authorization request for this user and resource.\r\nTrace ID: fddb1c98-20a3-400b-9448-a22141cf0300\r\nCorrelation ID: 9c48170d-d932-4cf9-9dd5-13574a735234\r\nTimestamp: 2021-03-04 01:10:05Z","error_codes":[70008],"timestamp":"2021-03-04 01:10:05Z","trace_id":"fddb1c98-20a3-400b-9448-a22141cf0300","correlation_id":"9c48170d-d932-4cf9-9dd5-13574a735234","error_uri":"https://login.microsoftonline.com/error?code=70008"}
  Source=Azure.Identity
  StackTrace:
   at Azure.Identity.AzureCliCredential.<RequestCliAccessTokenAsync>d__21.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.AzureCliCredential.<GetTokenImplAsync>d__20.MoveNext()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.AzureCliCredential.<GetTokenImplAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.AzureCliCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.<GetTokenFromSourcesAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__12.MoveNext()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__12.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at AzureIdentityPlayground.Program.SimpleTest() in C:\Users\ayeltsov\source\repos\AzureIdentityPlayground\Program.cs:line 221
   at AzureIdentityPlayground.Program.Main(String[] args) in C:\Users\ayeltsov\source\repos\AzureIdentityPlayground\Program.cs:line 26

  This exception was originally thrown at this call stack:
    Azure.Identity.AzureCliCredential.RequestCliAccessTokenAsync(bool, string[], System.Threading.CancellationToken)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Azure.Identity.AzureCliCredential.GetTokenImplAsync(bool, Azure.Core.TokenRequestContext, System.Threading.CancellationToken)
    Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(System.Exception)
    Azure.Identity.AzureCliCredential.GetTokenImplAsync(bool, Azure.Core.TokenRequestContext, System.Threading.CancellationToken)
    System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(System.Threading.Tasks.Task)
    System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
    Azure.Identity.AzureCliCredential.GetToken(Azure.Core.TokenRequestContext, System.Threading.CancellationToken)
    Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(Azure.Core.TokenCredential[], Azure.Core.TokenRequestContext, bool, System.Threading.CancellationToken)
    ...
    [Call Stack Truncated]
````

**To Reproduce**

I'm not sure - this probably requires expired token to be present in the token cache, and I'm not sure how to repro that on purpose. This is the code:

````csharp
            DefaultAzureCredential dc1 = new DefaultAzureCredential(includeInteractiveCredentials: true);
            TokenRequestContext trc = new TokenRequestContext(new string[] { "https://cloudbuild.microsoft.com/.default" });
            AccessToken accessToken = dc1.GetToken(trc);
````

**Environment:**
 - Name and version of the Library package used: Azure.Identity 1.3.0
 - Hosting platform or OS and .NET runtime version: Windows 10 20H2 19042.804, .NET FW 4.6.2
 - IDE and version : Visual Studio 16.8.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ayeltsov** [comment]
@christothes - could you please suggest workaround for the interim if anyone runs into the issue?
