### ISSUE TITLE
[Flaky Test] BearerTokenChallengeAuthenticationPolicy_GatedConcurrentCallsFailed

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#19226]
```
BearerTokenChallengeAuthenticationPolicy_GatedConcurrentCallsFailed

Result Details
Failed 2h ago on 61caadedc000002
Duration0:00:02.680
Ownernot available
Date started3/4/2021, 9:58:23 AM
Date completed3/4/2021, 9:58:25 AM
Failing since2h ago
Failing since build20210304.4

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: <System.InvalidOperationException: Error
at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.<>c__DisplayClass13_0.<BearerTokenChallengeAuthenticationPolicy_GatedConcurrentCallsFailed>b__0(TokenRequestContext r, CancellationToken c) in D:\a_work\1\s\sdk\core\Azure.Core\tests\BearerTokenChallengeAuthenticationPolicyTests.cs:line 377
at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.TokenCredentialStub.<>c__DisplayClass0_0.<<-ctor>b__0>d.MoveNext() in D:\a_work\1\s\sdk\core\Azure.Core\tests\BearerTokenChallengeAuthenticationPolicyTests.cs:line 547
--- End of stack trace from previous location where exception was thrown ---
at Azure.Core.Pipeline.BearerTokenChallengeAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken) in D:\a_work\1\s\sdk\core\Azure.Core\src\Shared\BearerTokenChallengeAuthenticationPolicy.cs:line 322
at Azure.Core.Pipeline.BearerTokenChallengeAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async) in D:\a_work\1\s\sdk\core\Azure.Core\src\Shared\BearerTokenChallengeAuthenticationPolicy.cs:line 194
at System.Threading.Tasks.ValueTask1.get_Result() at Azure.Core.Pipeline.BearerTokenChallengeAuthenticationPolicy.AuthenticateRequestAsync(HttpMessage message, TokenRequestContext context, Boolean async) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\BearerTokenChallengeAuthenticationPolicy.cs:line 138 at Azure.Core.Pipeline.BearerTokenChallengeAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory1 pipeline, Boolean async) in D:\a_work\1\s\sdk\core\Azure.Core\src\Shared\BearerTokenChallengeAuthenticationPolicy.cs:line 97
at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipeline pipeline, Action1 requestAction, Boolean bufferResponse, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\SyncAsyncPolicyTestBase.cs:line 28 at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipelineTransport transport, Action1 requestAction, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, CancellationToken cancellationToken) in D:\a_work\1\s\sdk\core\Azure.Core.TestFramework\src\SyncAsyncPolicyTestBase.cs:line 43
at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendGetRequest(HttpPipelineTransport transport, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, Uri uri, CancellationToken cancellationToken) in D:\a_work\1\s\sdk\core\Azure.Core.TestFramework\src\SyncAsyncPolicyTestBase.cs:line 48
at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.<>c__DisplayClass13_0.<<BearerTokenChallengeAuthenticationPolicy_GatedConcurrentCallsFailed>b__1>d.MoveNext() in D:\a_work\1\s\sdk\core\Azure.Core\tests\BearerTokenChallengeAuthenticationPolicyTests.cs:line 390
--- End of stack trace from previous location where exception was thrown ---
at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter1.GetResult() in D:\a\1\s\src\NUnitFramework\framework\Internal\TaskAwaitAdapter.cs:line 99 at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func1 invoke) in D:\a\1\s\src\NUnitFramework\framework\Internal\AsyncToSyncAdapter.cs:line 60
at NUnit.Framework.Assert.ThrowsAsync(IResolveConstraint expression, AsyncTestDelegate code, String message, Object[] args) in D:\a\1\s\src\NUnitFramework\framework\Assert.Exceptions.Async.cs:line 48>
But was:  <System.InvalidOperationException: Error
at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.<>c__DisplayClass13_0.<BearerTokenChallengeAuthenticationPolicy_GatedConcurrentCallsFailed>b__0(TokenRequestContext r, CancellationToken c) in D:\a_work\1\s\sdk\core\Azure.Core\tests\BearerTokenChallengeAuthenticationPolicyTests.cs:lin


Stack trace
   at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.BearerTokenChallengeAuthenticationPolicy_GatedConcurrentCallsFailed() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\BearerTokenChallengeAuthenticationPolicyTests.cs:line 394

```

**Comment by JoshLove-msft** [comment]
Not observed for a while - closing.
