### ISSUE TITLE
[BUG] Azure.Quantum.Jobs:  System.ArgumentOutOfRangeException in Azure.Quantum.Jobs.QuantumJobClient.GetStorageSasUri

### ISSUE THREAD

**Issue by delbert** [Azure/azure-sdk-for-net#19588]
**Describe the bug**
i am running Azure.Quantum.Jobs.Samples / Program.cs

Here is my run output:

Created QuantumJobClient for:
    SubscriptionId: XXX
    ResourceGroup: XXX
    workspaceName: XXX
    location: westus

Getting Container Uri with SAS key...

Unhandled Exception: System.ArgumentOutOfRangeException: The added or subtracted value results in an un-representable DateTime.
Parameter name: t
   at System.DateTime.op_Subtraction(DateTime d, TimeSpan t)
   at System.DateTimeOffset.op_Subtraction(DateTimeOffset dateTimeOffset, TimeSpan timeSpan)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueFromCredentialAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Quantum.Jobs.StorageRestClient.SasUri(BlobDetails blobDetails, CancellationToken cancellationToken)
   at Azure.Quantum.Jobs.QuantumJobClient.GetStorageSasUri(BlobDetails blobDetails, CancellationToken cancellationToken)
   at Azure.Quantum.Jobs.Samples.Program.Main(String[] args)

C:\Users\delbertm\Source\Repos\azure-sdk-for-net\artifacts\bin\Azure.Quantum.Jobs.Samples\Debug\net461\Azure.Quantum.Jobs.Samples.exe (process 29076) exited with code -532462766.

**Expected behavior**
Azure.Quantum.Jobs.Samples / Program.cs runs and runs the Azure Quantum QIO problem in the sample.

**Actual behavior (include Exception or Stack Trace)**
stack trace above

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1.  build the Azure.Quantum.Jobs sln from source
2.  fill in subscription, rg, workspace, and location (using default credential)
3. run

**Environment:**
 - Name and version of the Library package used: Azure.Quantum.Jobs --prerelease -v 1.0.0-beta.1
 - Hosting platform or OS and .NET runtime version
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  2.1.202 [C:\Program Files\dotnet\sdk]
  2.1.522 [C:\Program Files\dotnet\sdk]
  2.1.814 [C:\Program Files\dotnet\sdk]
  3.1.113 [C:\Program Files\dotnet\sdk]
  3.1.407 [C:\Program Files\dotnet\sdk]
  5.0.104 [C:\Program Files\dotnet\sdk]
  5.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
 - IDE and version : Visual Studio 16.9.2

**Comment by jsquire** [comment]
@vxfield:  It looks like we don't yet have triage contacts registered for Quantum;  would you be so kind as to offer your thoughts and help route this in the meantime?

**Comment by vxfield** [comment]
@jsquire, I'm the right person to take issues related to Azure Quantum SDK (all languages).
Let me know how I can register in the triage contacts (or please register me if you can).

**Comment by vxfield** [comment]
@delbert, thanks for reporting the issue.
I'll take a look later this afternoon and see if I can repro it.

**Comment by delbert** [comment]
thanks, @vxfield!

**Comment by vxfield** [comment]
@delbert, I was not quite able to repro the issue.
Instead I'm getting another authentication issue related to the `BearerTokenAuthenticationPolicy` that I think is related to the issue you found.

I'll continue the investigation tomorrow afternoon.

What type of authentication you expect to use with `DefaultAzureCredential`? 
`DefaultAzureCredential` [will try several methods](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) so I just want to double check which method you expecting to use (Service/Principal credentials via environment variables, or the interactive browser / device code authentication, or another method)?

**Comment by delbert** [comment]
interesting, @XField, i am just using the DefaultAzureCredential.  so i'm assuming it defaults to the browser-code-handshake-thingy.  for some reason, it isn't prompting me for the code.  maybe i haven't reached that point, yet?  or maybe a token is cached somehow?  i went through the auth process yesterday, running QIO jobs from Python.

oddly enough, the customer with whom i am doing this project is running into the auth error, below.  not sure if this is what you are seeing, as well?

thanks again for digging into this mystery.

Azure.Identity.AuthenticationFailedException
  HResult=0x80131500
  Message=The DefaultAzureCredential failed due to an unhandled exception:  SharedTokenCacheCredential failed with unhandled exception The authentication request failed due to an unhandled exception.  See inner exception for details..
  EnvironmentCredential is unavailable Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  ].
  ManagedIdentityCredential is unavailable No managed identity endpoint found..
  SharedTokenCacheCredential failed with The authentication request failed due to an unhandled exception.  See inner exception for details..
See inner exception for more detail.
  Source=Azure.Identity
  StackTrace:
   at Azure.Identity.DefaultAzureCredential.<GetTokenAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueFromCredentialAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ValueTaskAwaiter.GetResult()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Quantum.Jobs.StorageRestClient.SasUri(BlobDetails blobDetails, CancellationToken cancellationToken)
   at Azure.Quantum.Jobs.QuantumJobClient.GetStorageSasUri(BlobDetails blobDetails, CancellationToken cancellationToken)
   at Azure.Quantum.Jobs.Samples.Program.Main(String[] args) in C:\Users\jeng397\source\repos\QuantumHello\QIOIntegrationTest\Program.cs:line 45

Inner Exception 1:
AggregateException: The DefaultAzureCredential failed due to an unhandled exception:  SharedTokenCacheCredential failed with unhandled exception The authentication request failed due to an unhandled exception.  See inner exception for details.. (Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  ]) (No managed identity endpoint found.) (The authentication request failed due to an unhandled exception.  See inner exception for details.)

Inner Exception 2:
CredentialUnavailableException: Environment variables not fully configured. AZURE_TENANT_ID and AZURE_CLIENT_ID must be set, along with either AZURE_CLIENT_SECRET or AZURE_USERNAME and AZURE_PASSWORD. Currently set variables [  ]

**Comment by munip** [comment]
I found that the BlobDetails class does not have the BlobName folder set before accessing SasUri. Setting BlobName property fixed this issue.

**Comment by vxfield** [comment]
Apologies about the delay.

PR #19853 will fix the cause of the issue which was an incomplete AAD scope that stopped working since our initial release of this client.

I tested it with both Service Principal authentication (setting environment variables `AZURE_TENANT_ID`, `AZURE_CLIENT_ID` and `AZURE_CLIENT_SECRET`) and also with interactive device authentication (via `az login`).

In case you still find issues, please try clearing the Azure Identity cache from `C:\Users\[username]\AppData\Local\.IdentityService`. For example,I had to clear it to make sure it was using the client secret instead of a cached device authentication.

I'll publish a new version of the package to NuGet as soon as the PR merges. It should go with version `1.0.0-beta.2`. I'll update this issue when the package is released.

**Comment by vxfield** [comment]
@munip, the `GetStorageSasUri` API should be able to work fine without the `BlobName` as long as it has the `ContainerName` (which is mandatory).
In that case the Uri returned will be the Uri of the container including the SAS key.
If you also pass the `BlobName`, in addition to the `ContainerName`, then you would get back the Uri of the blob including the SAS key.

Looking at the stack trace of the issue reported by Delbert we can see we have an underlying authentication issue that happened even before the `GetStorageSasUri` was actually called.

Let me know if you are having a different issue by not setting the `BlobName`.

**Comment by delbert** [comment]
thanks for these updates, XField!  we'll watch for your updates.

**Comment by vxfield** [comment]
@delbert,

The PR #19853 with the fix was merged to `master` branch yesterday.
And we have just released a new version (`1.0.0-beta.2`) of the package to NuGet containing the fix.

https://www.nuget.org/packages/Azure.Quantum.Jobs/1.0.0-beta.2

Let me know if that the new version has fixed the issue you have encountered.

**Comment by delbert** [comment]
thanks, @XField!

we'll give it a try
