### ISSUE TITLE
Passing `--sync` to perf programs throws an exception when printing results

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#19652]
When running `--sync` tests, an exception is thrown when printing results.

For example, running:
```bash
# Not checked in currently, but probably any perf test in our repo will do:
dotnet run --no-build -c release -f netcoreapp3.1 -p sdk\keyvault\Azure.Security.KeyVault.Secrets\perf\Azure.Security.KeyVault.Secrets.Perf.csproj -- ListSecrets --rate 200 --latency --sync
```

Will print toward the end:
```text
=== Results ===
Completed 72 operations in a weighted-average of 10.13s (7.11 ops/s, 0.141 s/op)

=== Latency Distribution ===
 50.000%        131.29ms
 75.000%        157.92ms
 90.000%        176.04ms
 99.000%        238.90ms
 99.900%        238.90ms
 99.990%        238.90ms
 99.999%        238.90ms
100.000%        258.08ms

=== Corrected Latency Distribution ===
Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Azure.Test.Perf.PerfProgram.PrintLatencies(String header, List`1[] latencies) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 358
   at Azure.Test.Perf.PerfProgram.RunTestsAsync(IPerfTest[] tests, PerfOptions options, String title, Boolean warmup) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 330
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 107
=== Cleanup ===
Exception: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Azure.Test.Perf.PerfProgram.PrintLatencies(String header, List`1[] latencies) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 358
   at Azure.Test.Perf.PerfProgram.RunTestsAsync(IPerfTest[] tests, PerfOptions options, String title, Boolean warmup) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 330
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 107
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 139
...................Unhandled exception. System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Azure.Test.Perf.PerfProgram.PrintLatencies(String header, List`1[] latencies) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 358
   at Azure.Test.Perf.PerfProgram.RunTestsAsync(IPerfTest[] tests, PerfOptions options, String title, Boolean warmup) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 330
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 107
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 139
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 157
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 163
   at Azure.Test.Perf.PerfProgram.<>c__DisplayClass9_0.<<Main>b__1>d.MoveNext() in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 45
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Test.Perf.PerfProgram.Main(Assembly assembly, String[] args) in C:\src\azure-sdk-for-net\common\Perf\Azure.Test.Perf\PerfProgram.cs:line 40
   at <Program>$.<<Main>$>d__0.MoveNext() in C:\src\azure-sdk-for-net\sdk\keyvault\Azure.Security.KeyVault.Secrets\perf\Program.cs:line 7
--- End of stack trace from previous location where exception was thrown ---
   at <Program>$.<Main>(String[] args)
.
```

**Comment by mikeharder** [comment]
It looks like the `rate` parameter is not working at all with `sync`.  The `rate` and `latency` parameters are both considered "experimental" in the .NET perf framework.
