### ISSUE TITLE
[Flaky Test] TimeSeriesInsightsQuery_GetEventsLifecycle

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#19685]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=795708&view=ms.vss-test-web.build-test-results-tab&runId=17533290&resultId=143150&paneView=debug

```
Error message
Microsoft.Azure.Devices.Client.Exceptions.UnauthorizedException : CONNECT failed: RefusedNotAuthorized


Stack trace
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenInternalAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.Mqtt.MqttTransportHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ProtocolRoutingDelegatingHandler.OpenAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.<>c__DisplayClass27_0.<<ExecuteWithErrorHandlingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.ErrorDelegatingHandler.ExecuteWithErrorHandlingAsync[T](Func`1 asyncOperation)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass38_0.<<OpenInternalAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.EnsureOpenedAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.<>c__DisplayClass15_0.<<SendEventAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.Azure.Devices.Client.Transport.RetryDelegatingHandler.SendEventAsync(Message message, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Client.InternalClient.SendEventAsync(Message message)
   at Azure.Iot.TimeSeriesInsights.Tests.TimeSeriesInsightsQueryTests.SendEventsToHubAsync(DeviceClient client, TimeSeriesId tsiId, TimeSeriesIdProperty[] timeSeriesIdProperties, Int32 numberOfEventsToSend) in D:\a\_work\1\s\sdk\timeseriesinsights\Azure.Iot.TimeSeriesInsights\tests\TimeSeriesInsightsQueryTests.cs:line 217
   at Azure.Iot.TimeSeriesInsights.Tests.TimeSeriesInsightsQueryTests.TimeSeriesInsightsQuery_GetEventsLifecycle() in D:\a\_work\1\s\sdk\timeseriesinsights\Azure.Iot.TimeSeriesInsights\tests\TimeSeriesInsightsQueryTests.cs:line 48
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

The test might need a `LiveOnly` attribute

**Comment by barustum** [comment]
Taking a look.

**Comment by barustum** [comment]
Fixed
