### ISSUE TITLE
[Flaky Test] BearerTokenChallengeAuthenticationPolicy_CancelledFirstRequestAndCancelledSecondRequest

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#19741]
```
BearerTokenChallengeAuthenticationPolicy_CancelledFirstRequestAndCancelledSecondRequest

Result Details
Failed 51m ago on 261b210fc000000
Duration0:00:00.054
Ownernot available
Date started3/23/2021, 9:22:31 AM
Date completed3/23/2021, 9:22:31 AM
Failing since51m ago
Failing since build20210323.2

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: <System.OperationCanceledException>
But was:  <System.Threading.Tasks.TaskCanceledException: A task was canceled.
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, Boolean async)
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory1 pipeline, Boolean async) at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipeline pipeline, Action1 requestAction, Boolean bufferResponse, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 28
at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipelineTransport transport, Action1 requestAction, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 43 at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendGetRequest(HttpPipelineTransport transport, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, Uri uri, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 48 at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.<>c__DisplayClass18_0.<<BearerTokenChallengeAuthenticationPolicy_CancelledFirstRequestAndCancelledSecondRequest>b__3>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core/tests/BearerTokenChallengeAuthenticationPolicyTests.cs:line 601 --- End of stack trace from previous location where exception was thrown --- at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter1.GetResult()
at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
at NUnit.Framework.Assert.ThrowsAsync(IResolveConstraint expression, AsyncTestDelegate code, String message, Object[] args)>


Stack trace
   at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.BearerTokenChallengeAuthenticationPolicy_CancelledFirstRequestAndCancelledSecondRequest
```

**Comment by pakrym** [comment]
```
BearerTokenChallengeAuthenticationPolicy_CancelledFirstRequestAndCancelledSecondRequest

Result Details
Failed 54m ago on df07ddbbc000000
Duration0:00:00.037
Ownernot available
Date started3/25/2021, 9:08:49 AM
Date completed3/25/2021, 9:08:49 AM
Failing since54m ago
Failing since build20210325.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: <System.OperationCanceledException>
But was:  <System.Threading.Tasks.TaskCanceledException: A task was canceled.
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, Boolean async)
at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory1 pipeline, Boolean async) at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipeline pipeline, Action1 requestAction, Boolean bufferResponse, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 28
at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendRequestAsync(HttpPipelineTransport transport, Action1 requestAction, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 43 at Azure.Core.TestFramework.SyncAsyncPolicyTestBase.SendGetRequest(HttpPipelineTransport transport, HttpPipelinePolicy policy, ResponseClassifier responseClassifier, Boolean bufferResponse, Uri uri, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/SyncAsyncPolicyTestBase.cs:line 48 at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.<>c__DisplayClass18_0.<<BearerTokenChallengeAuthenticationPolicy_CancelledFirstRequestAndCancelledSecondRequest>b__3>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core/tests/BearerTokenChallengeAuthenticationPolicyTests.cs:line 601 --- End of stack trace from previous location where exception was thrown --- at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter1.GetResult()
at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
at NUnit.Framework.Assert.ThrowsAsync(IResolveConstraint expression, AsyncTestDelegate code, String message, Object[] args)>


Stack trace
   at Azure.Core.Tests.BearerTokenChallengeAuthenticationPolicyTests.BearerTokenChallengeAuthenticationPolicy_CancelledFirstRequestAndCancelledSecondRequest() in /mnt/vss/_work/1/s/sdk/core/Azure.Core/tests/BearerTokenChallengeAuthenticationPolicyTests.cs:line 602

```
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=803882&view=ms.vss-test-web.build-test-results-tab&runId=17664530&resultId=102035&paneView=debug
