### ISSUE TITLE
Content null after retry before authentication succeeded

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#19916]
During live Key Vault tests, ran into an exception where the request body to create a key was null (request parameters were provided):
```
[Informational] Azure-Core: Request [405dfb8d-5006-47d4-8012-bc8da6ea3377] POST https://tf17be9f7633d4c85.vault.azure.net/keys/CloudRsaKey-8e8e168f-1b47-439d-8563-675cc3e78499/create?api-version=7.2
Accept:application/json
x-ms-client-request-id:405dfb8d-5006-47d4-8012-bc8da6ea3377
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Keys/4.2.0-alpha.20210329.1,(.NET 5.0.3; Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64)
Content-Type:application/json
client assembly: Azure.Security.KeyVault.Keys
[Informational] Azure-Core: Request [405dfb8d-5006-47d4-8012-bc8da6ea3377] exception Azure.RequestFailedException: Operation timed out (tf17be9f7633d4c85.vault.azure.net:443)
 ---> System.Net.Http.HttpRequestException: Operation timed out (tf17be9f7633d4c85.vault.azure.net:443)
 ---> System.Net.Sockets.SocketException (60): Operation timed out
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async) in /_/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs:line 92
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async) in /_/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs:line 122
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async) in /_/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs:line 45
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async) in /_/sdk/core/Azure.Core/src/Pipeline/Internal/LoggingPolicy.cs:line 79
[Informational] Azure-Core: Request [405dfb8d-5006-47d4-8012-bc8da6ea3377] retry number 1 took 10.7s
[Informational] Azure-Core: Request [405dfb8d-5006-47d4-8012-bc8da6ea3377] POST https://tf17be9f7633d4c85.vault.azure.net/keys/CloudRsaKey-8e8e168f-1b47-439d-8563-675cc3e78499/create?api-version=7.2
Accept:application/json
x-ms-client-request-id:405dfb8d-5006-47d4-8012-bc8da6ea3377
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Keys/4.2.0-alpha.20210329.1,(.NET 5.0.3; Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64)
Content-Type:application/json
client assembly: Azure.Security.KeyVault.Keys
[Warning] Azure-Core: Error response [405dfb8d-5006-47d4-8012-bc8da6ea3377] 401 Unauthorized (00.5s)
Cache-Control:no-cache
Pragma:no-cache
WWW-Authenticate:REDACTED
x-ms-keyvault-region:westus2
x-ms-client-request-id:405dfb8d-5006-47d4-8012-bc8da6ea3377
x-ms-request-id:REDACTED
x-ms-keyvault-service-version:1.2.205.0
x-ms-keyvault-network-info:conn_type=Ipv4;addr=13.105.49.36;act_addr_fam=InterNetwork;
X-Powered-By:REDACTED
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Date:Mon, 29 Mar 2021 11:58:29 GMT
Content-Length:87
Content-Type:application/json; charset=utf-8
Expires:-1

... auth elided for brevity ...

[Informational] Azure-Core: Request [405dfb8d-5006-47d4-8012-bc8da6ea3377] POST https://tf17be9f7633d4c85.vault.azure.net/keys/CloudRsaKey-8e8e168f-1b47-439d-8563-675cc3e78499/create?api-version=7.2
Accept:application/json
x-ms-client-request-id:405dfb8d-5006-47d4-8012-bc8da6ea3377
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Keys/4.2.0-alpha.20210329.1,(.NET 5.0.3; Darwin 19.6.0 Darwin Kernel Version 19.6.0: Tue Jan 12 22:13:05 PST 2021; root:xnu-6153.141.16~1/RELEASE_X86_64)
Authorization:REDACTED
Content-Type:application/json
client assembly: Azure.Security.KeyVault.Keys
[Warning] Azure-Core: Error response [405dfb8d-5006-47d4-8012-bc8da6ea3377] 400 Bad Request (00.0s)
Cache-Control:no-cache
Pragma:no-cache
x-ms-keyvault-region:westus2
x-ms-client-request-id:405dfb8d-5006-47d4-8012-bc8da6ea3377
x-ms-request-id:REDACTED
x-ms-keyvault-service-version:1.2.205.0
x-ms-keyvault-network-info:conn_type=Ipv4;addr=13.105.49.36;act_addr_fam=InterNetwork;
X-Powered-By:REDACTED
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Date:Mon, 29 Mar 2021 11:58:30 GMT
Content-Length:72
Content-Type:application/json; charset=utf-8
Expires:-1
```

**Comment by heaths** [comment]
I wrote a test to debug this. The problem is (and was even before the recent challenge-auth changes) that we save the body content after a 401, make a challenge request, the restore content. However, if the call to `ProcessNext` or `ProcessNextAsync` were to fail and the `RetryPolicy` kicks in, the `HttpMessage.Request.Content` is already null, so saving it again wipes out the previous content.

I'm fixing this for the current code. If we had to backport this to older versions, we could put a `try...finally` around the `ProcessNext(Async)` calls to always restore the content in case of an exception further down the policy chain / stack.

/cc @pakrym @christothes
