### ISSUE TITLE
[BUG] BlobClient.GetBlobClient does not include the blobContainerName into the final url so UploadAsync fails

### ISSUE THREAD

**Issue by BrutalHex** [Azure/azure-sdk-for-net#19984]
**Describe the bug**
I'm trying to upload a blob to **IOT Azure Blob**. this code according to the documents should work :
`
            BlobServiceClient service = new BlobServiceClient(_connectionString);
            BlobContainerClient container = service.GetBlobContainerClient(_containerName);
            await container.CreateAsync();
            BlobClient foo = container.GetBlobClient($"{blob}");
            await foo.UploadAsync(new MemoryStream(Encoding.UTF8.GetBytes("Foo")));
`
but it throws an **ContainerNotFoundException** . when I had checked the Uri property, I found out that the container name was not included into the final Uri. it uses **AccountName** in connection string as a container name and ignores the name that has been set via `service.GetBlobContainerClient` . I have changed the ` container.GetBlobClient($"{blob}")` to 
`  BlobClient foo = container.GetBlobClient($"{containerName}/{blob}");` so it worked.

the interesting point is that the below code throws invalid authentication and ignores the **AccountName** in connection string and it's not being included before container name .

`          BlobServiceClient service = new BlobServiceClient(_connectionString);
            BlobContainerClient container = new BlobContainerClient(_connectionString, _containerName); 
            await container.CreateAsync();
            BlobClient foo = container.GetBlobClient($"{blob}");
            await foo.UploadAsync(new MemoryStream(Encoding.UTF8.GetBytes("Foo")));`

should the **Account Name** being included into the Uri or not ?!!

**Expected behavior**
the blob gets uploaded. 

**Actual behavior (include Exception or Stack Trace)**
throws ContainerNotFoundException .

ExceptionDetails: Exception of type 'Microsoft.Cis.Services.Nephos.Common.Storage.ContainerNotFoundException' was thrown.Microsoft.Cis.Services.Nephos.Common.Storage.ContainerNotFoundException: Exception of type 'Microsoft.Cis.Services.Nephos.Common.Storage.ContainerNotFoundException' was thrown.
 ---> Microsoft.Cis.Services.Nephos.Common.Storage.ContainerNotFoundException: Exception of type 'Microsoft.Cis.Services.Nephos.Common.Storage.ContainerNotFoundException' was thrown.
 ---> Microsoft.Cis.Services.Nephos.Common.Storage.ContainerNotFoundException: Exception of type 'Microsoft.Cis.Services.Nephos.Common.Storage.ContainerNotFoundException' was thrown.
 ---> Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WStoreException: GetBlobContainerPropertiesAsync failed
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WBlobContainer.GetBlobContainerPropertiesAsync(ContainerPropertyNames propertyNames, IContainerCondition conditions, Boolean shouldSkipCacheLookup, Nullable`1 cancelToken)
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WBlobContainer.GetBlobContainerPropertiesAsync(ContainerPropertyNames propertyNames, IContainerCondition conditions, Nullable`1 cancelToken)
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WBaseBlobObject.PutBlobAsync(String contentType, Int64 contentLength, Nullable`1 maxBlobSize, Byte[] serviceMetadata, Byte[] applicationMetadata, Stream inputStream, CrcReaderStream crcReaderStream, Byte[] contentMD5, Boolean invokeGeneratePutBlobServiceMetadata, GeneratePutBlobServiceMetadata generatePutBlobServiceMetadata, ISequenceNumberUpdate sequenceNumberUpdate, OverwriteOption overwriteOption, IBlobObjectCondition condition)
   at Microsoft.AzureStack.Services.Storage.Util.Await(Task t)
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WBaseBlobObject.EndPutBlob(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.ExceptionManager.ReThrowIfWStoreException(Exception e)
   at Microsoft.AzureStack.Services.Storage.FrontEnd.WossProvider.WBaseBlobObject.EndPutBlob(IAsyncResult asyncResult)
   at Microsoft.Cis.Services.Nephos.Storage.Service.ServiceManager.RealServiceManager.PutBlobImpl(IAccountIdentifier identifier, String account, IStorageAccount storageAccount, String container, String blob, Stream inputStream, Int64 contentLength, IPutBlobProperties putBlobProperties, Boolean supportCrc64, Boolean calculateCrc64, Boolean storeCrc64, Boolean verifyCrc64, Boolean calculateMd5, Boolean storeMd5, Boolean verifyMd5, Boolean generationIdEnabled, Boolean isLargeBlockBlobRequest, Boolean is8TBPageBlobAllowed, BlobObjectCondition condition, BlobIdentifier blobIdentifier, OverwriteOption overwriteOption, TimeSpan timeout, RequestContext requestContext, AccessTier accessTier, String blobSasUrl, AsyncIteratorContext`1 context)+MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Storage.Service.ServiceManager.RealServiceManager.EndPutBlob(IAsyncResult asyncResult)
   at Microsoft.Cis.Services.Nephos.Storage.Service.Protocols.Rest.HttpRestProcessor.PutBlobImpl(AsyncIteratorContext`1 async)+MoveNext()
   at AsyncHelper.AsyncIteratorContextBase.ExecuteIterator(Boolean inBegin)
   --- End of inner exception stack trace ---
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.EndPerformOperation(IAsyncResult ar)
   at Microsoft.Cis.Services.Nephos.Common.Protocols.Rest.BasicHttpProcessorWithAuthAndAccountContainer`1.ProcessImpl(AsyncIteratorContext`1 async)+MoveNext()

**To Reproduce**
           BlobServiceClient service = new BlobServiceClient(_connectionString);
            BlobContainerClient container = service.GetBlobContainerClient(_containerName);
            container.Create();
            BlobClient foo = container.GetBlobClient($"{blob}");
            await foo.UploadAsync(new MemoryStream(Encoding.UTF8.GetBytes("Foo")));

**Environment:**
.net core 5 , 
windows , 
Azure.Storage.Blobs Version="12.8.0"
IOT Azure Blob

**Comment by seanmcc-msft** [comment]
Hi, can you post a redacted example of the connection string you are trying to use?

We have multiple unit tests for `BlobContainerClient.GetBlobClient()` that are passing.  The parameter for `GetBlobClient()` is just the blob name, not the container name.

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/storage/Azure.Storage.Blobs/tests/ContainerClientTests.cs#L2418

-Sean

**Comment by BrutalHex** [comment]
sorry, for the late response, this is the connection string. 
![blob](https://user-images.githubusercontent.com/22192883/118165413-f06a6f80-b42c-11eb-8a3a-ecb8c3f65b20.jpg)
