### ISSUE TITLE
[Storage] DataLake 10MB upload/download fails with "Invalid request URI" on netcoreapp2.1

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#20032]
At https://github.com/Azure/azure-sdk-for-net/commit/b39e230c8eff7e61bd803d9deea198401967e49f, DataLake 10MB upload/download on netcoreapp2.1 fails with:

```
Exception: Azure.RequestFailedException: Value for one of the query parameters specified in the request URI is invalid.
Status: 400 (Value for one of the query parameters specified in the request URI is invalid.)
ErrorCode: InvalidQueryParameterValue

   at Azure.Storage.Files.DataLake.PathRestClient.FlushDataAsync(Nullable`1 timeout, Nullable`1 position, Nullable`1 retainUncommittedData, Nullable`1 close, Nullable`1 contentLength, Byte[] contentMD5, String leaseId, String cacheControl, String contentType, String contentDisposition, String contentEncoding, String contentLanguage, String ifMatch, String ifNoneMatch, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeFileClient.FlushInternal(Int64 position, Nullable`1 retainUncommittedData, Nullable`1 close, PathHttpHeaders httpHeaders, DataLakeRequestConditions conditions, Boolean async, CancellationToken cancellationToken) in /home/mharder/net/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs:line 2201
   at Azure.Storage.Files.DataLake.DataLakeFileClient.<>c__DisplayClass89_0.<<GetPartitionedUploaderBehaviors>b__1>d.MoveNext() in /home/mharder/net/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs:line 4334
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Storage.PartitionedUploader`2.UploadInternal(Stream content, TServiceSpecificArgs args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeFileClient.StagedUploadInternal(Stream content, DataLakeFileUploadOptions options, Boolean async, CancellationToken cancellationToken) in /home/mharder/net/sdk/storage/Azure.Storage.Files.DataLake/src/DataLakeFileClient.cs:line 3529
   at Azure.Storage.Files.DataLake.Perf.Scenarios.Read.GlobalSetupAsync() in /home/mharder/net/sdk/storage/Azure.Storage.Files.DataLake/perf/Azure.Storage.Files.DataLake.Perf/Scenarios/Read.cs:line 80
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in /home/mharder/net/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 94
```

The threshold to trigger this issue is exactly `10,000,000`.  If size is `9,999,999` or less the request succeeds, but `10,000,000` or higher fails.

The same perf test runs successfully on `Azure.Storage.Files.DataLake@12.6.1`, and on netcoareapp3.1 or higher.

## Minimal Repro Console App
https://github.com/mikeharder/datalake-upload

## Perf Test Code
https://github.com/Azure/azure-sdk-for-net/blob/2c338d26571f4ee84c3c280984af49bcb771fe2a/sdk/storage/Azure.Storage.Files.DataLake/perf/Azure.Storage.Files.DataLake.Perf/Scenarios/Read.cs#L70-L81

**Comment by seanmcc-msft** [comment]
@mikeharder, could you post the code snippet you used to re-produce?

**Comment by kasobol-msft** [comment]
Seems that here https://github.com/Azure/azure-sdk-for-net/blob/2c338d26571f4ee84c3c280984af49bcb771fe2a/sdk/storage/Azure.Storage.Files.DataLake/perf/Azure.Storage.Files.DataLake.Perf/Scenarios/Read.cs#L80

**Comment by seanmcc-msft** [comment]
I'm unable to repo:

```
        [Test]
        public async Task UploadAsync_MinStream()
        {
            // Arrange
            await using DisposingFileSystem test = await GetNewFileSystem();
            DataLakeFileClient file = test.FileSystem.GetFileClient(GetNewFileName());

            var data = GetRandomBuffer(10 * Constants.MB);

            // Act
            using (var stream = new MemoryStream(data))
            {
                await file.UploadAsync(stream, true);
            }

            // Assert
            using var actual = new MemoryStream();
            await file.ReadToAsync(actual);
            TestHelper.AssertSequenceEqual(data, actual.ToArray());
        }
```

**Comment by mikeharder** [comment]
The exception is actually from `GlobalSetup()`, but it's calling the same `UploadAsync()`.

**Comment by kasobol-msft** [comment]
There's a problem in generated code that formats `long` in scientific notation.
```
PATCH https://mharderdatalake.dfs.core.windows.net/279e0b01-fdb1-4f53-a5b4-ced9da0b79cd/rezet1tm.het?action=flush&position=1.048576E%2B07 HTTP/1.1
```

https://github.com/Azure/azure-sdk-for-net/blob/64f911d255455c20c4385465c9ecb409fbabaf9e/sdk/storage/Azure.Storage.Files.DataLake/src/Generated/PathRestClient.cs#L279-L282

**Comment by mikeharder** [comment]
Fixed in https://github.com/Azure/autorest.csharp/pull/1118.  Waiting for fix to flow to `azure-sdk-for-net` repo.
