### ISSUE TITLE
[BUG] TableServiceClient rejects AccountName + SharedAccessSignature (SAS) connection string

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#20082]
**Describe the bug**
Azure.Data.Tables

**Expected behavior**
When providing a connection string of the following format:
`AccountName={storage account name};SharedAccessSignature={sas}`
or
`AccountName={storage account name};SharedAccessSignature=?{sas}`

I expect:
- Azure public (global) cloud to be used, i.e. `https://{storage account name}.table.core.windows.net/` endpoint
- The provided SAS should be used to authorize the requests.

This works on Blobs, Queues, and Tables in the old SDK (WindowsAzure.Storage), in Azure.Storage.Blobs, and in Azure.Storage.Queues. But it does not work on Azure.Data.Tables.

I think the bug is somewhere in here:
https://github.com/Azure/azure-sdk-for-net/blob/ab9962ee17ea84f3be1aa7f00a0e1354d7c7affc/sdk/tables/Azure.Data.Tables/src/TableConnectionString.cs#L188-L191

**Actual behavior (include Exception or Stack Trace)**
```
Unhandled exception. System.ArgumentException: Connection string parsing error
   at Azure.Data.Tables.TableConnectionString.Parse(String connectionString)
   at Azure.Data.Tables.TableServiceClient..ctor(String connectionString, TableClientOptions options)
   at Azure.Data.Tables.TableServiceClient..ctor(String connectionString)
   at ConsoleApp7.Program.Main(String[] args) in C:\Users\joelv\Desktop\ConsoleApp7\ConsoleApp7\Program.cs:line 39
   at ConsoleApp7.Program.<Main>(String[] args)
```

**To Reproduce**

```csharp
using System;
using System.Threading.Tasks;
using Azure.Data.Tables;
using Azure.Storage.Blobs;
using Azure.Storage.Queues;
using Microsoft.WindowsAzure.Storage;

namespace ConsoleApp7
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var connectionString = "AccountName=myaccount;SharedAccessSignature=mysas";

            Console.Write("Starting old Blobs SDK... ");
            await CloudStorageAccount.Parse(connectionString).CreateCloudBlobClient().ListContainersSegmentedAsync(currentToken: null);
            Console.WriteLine("done.");

            Console.Write("Starting old Queues SDK... ");
            await CloudStorageAccount.Parse(connectionString).CreateCloudQueueClient().ListQueuesSegmentedAsync(currentToken: null);
            Console.WriteLine("done.");

            Console.Write("Starting old Tables SDK... ");
            await CloudStorageAccount.Parse(connectionString).CreateCloudTableClient().ListTablesSegmentedAsync(currentToken: null);
            Console.WriteLine("done.");

            Console.WriteLine();

            Console.Write("Starting new Blobs SDK... ");
            await new BlobServiceClient(connectionString).GetBlobContainersAsync().GetAsyncEnumerator().MoveNextAsync();
            Console.WriteLine("done.");

            Console.Write("Starting new Queues SDK... ");
            await new QueueServiceClient(connectionString).GetQueuesAsync().GetAsyncEnumerator().MoveNextAsync();
            Console.WriteLine("done.");

            Console.Write("Starting new Tables SDK... ");
            await new TableServiceClient(connectionString).GetTablesAsync().GetAsyncEnumerator().MoveNextAsync();
            Console.WriteLine("done.");
        }
    }
}
```

**Environment:**
 - Name and version of the Library package used: Azure.Data.Tables 12.0.0-beta.6
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows 10, .NET 5
 - IDE and version : VS 16.9

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
