### ISSUE TITLE
[QUERY] Container exists, but upload failing with  "Azure.RequestFailedException: The specified container does not exist."

### ISSUE THREAD

**Issue by BrettThib** [Azure/azure-sdk-for-net#20187]
**Query/Question**
I'm having trouble determining why my BlockBlobClient.UploadAsync method is failing with "Azure.RequestFailedException: The specified container does not exist." when it does in fact exist.  The code has worked previously with the same Container, so this has me a bit stumped.   Hoping someone can look at my request ID and provide some additional info.  Thank you in advance.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Blobs v12.8.0.0
 - Hosting platform or OS and .NET runtime version: Windows 10 .NET Framework 4.8
 - IDE and version : Visual Studio Version 16.8.4

Here is the exception:
```
 System.AggregateException: One or more errors occurred. ---> Azure.RequestFailedException: The specified container does not exist.
RequestId:e993a8d9-901e-008a-2ab4-2b178e000000
Time:2021-04-07T13:47:48.2916558Z
Status: 404 (The specified container does not exist.)
ErrorCode: ContainerNotFound

Headers:
x-ms-request-id: e993a8d9-901e-008a-2ab4-2b178e000000
x-ms-client-request-id: eafd5120-f75e-4e0d-b42a-a73e0a37ba2a
x-ms-version: 2020-04-08
x-ms-error-code: ContainerNotFound
Content-Length: 225
Content-Type: application/xml
Date: Wed, 07 Apr 2021 13:47:48 GMT
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0

   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.UploadAsync_CreateResponse(ClientDiagnostics clientDiagnostics, Response response)
   at Azure.Storage.Blobs.BlobRestClient.BlockBlob.<UploadAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<UploadInternal>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<>c__DisplayClass54_0.<<GetPartitionedUploaderBehaviors>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.PartitionedUploader`2.<UploadInternal>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<UploadAsync>d__24.MoveNext()
   --- End of inner exception stack trace ---
```

Here is my client:
![image](https://user-images.githubusercontent.com/66392777/113880435-18f1b080-9781-11eb-8d4a-c241a6127002.png)

From Azure Portal:
![image](https://user-images.githubusercontent.com/66392777/113881210-d9779400-9781-11eb-9c60-9d915b3b6147.png)

**Comment by BrettThib** [comment]
Disregard.  I found my issue.  I wasn't creating my client correctly....note the null Name property in my screen.
