### ISSUE TITLE
[Storage] BlobContainerClient.GetBlobsAsync() throws XmlException

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#20374]
While running a perf test for `GetBlobsAsync()`, the following exception was thrown:

```
Exception: System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not closed: Last-Modified, Properties, Blob, Blobs, EnumerationResults. Line 1, position 243679.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
   at System.Xml.XmlTextReaderImpl.ThrowUnclosedElements()
   at System.Xml.XmlTextReaderImpl.ParseElementContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
   at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r, LoadOptions o)
   at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
   at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
   at Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegmentAsync(String prefix, String marker, Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, CancellationToken cancellationToken) in /home/mharder/net-mh/sdk/storage/Azure.Storage.Blobs/src/Generated/ContainerRestClient.cs:line 1220
   at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken) in /home/mharder/net-mh/sdk/storage/Azure.Storage.Blobs/src/BlobContainerClient.cs:line 2502
   at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken) in /home/mharder/net-mh/sdk/storage/Azure.Storage.Blobs/src/Models/GetBlobsAsyncCollection.cs:line 44
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.GetAsyncEnumerator(CancellationToken cancellationToken) in /home/mharder/net-mh/sdk/storage/Azure.Storage.Common/src/Shared/StorageCollectionEnumerator.cs:line 203
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.Storage.Blobs.Perf.Scenarios.GetBlobs.RunAsync(CancellationToken cancellationToken) in /home/mharder/net-mh/sdk/storage/Azure.Storage.Blobs/perf/Azure.Storage.Blobs.Perf/Scenarios/GetBlobs.cs:line 46
   at Azure.Storage.Blobs.Perf.Scenarios.GetBlobs.RunAsync(CancellationToken cancellationToken) in /home/mharder/net-mh/sdk/storage/Azure.Storage.Blobs/perf/Azure.Storage.Blobs.Perf/Scenarios/GetBlobs.cs:line 46
   at Azure.Test.Perf.PerfProgram.RunLoopAsync(IPerfTest test, Int32 index, Boolean latency, CancellationToken cancellationToken) in /home/mharder/net-mh/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 466
   at Azure.Test.Perf.PerfProgram.RunTestsAsync(IPerfTest[] tests, PerfOptions options, String title, Boolean warmup) in /home/mharder/net-mh/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 344
   at Azure.Test.Perf.PerfProgram.Run(Type testType, PerfOptions options) in /home/mharder/net-mh/common/Perf/Azure.Test.Perf/PerfProgram.cs:line 111
```

This only repro'd once in many thousands of API calls.  This is the first time I've seen this after months of running `GetBlobs` perf tests, so it might be a recent regression.

I suspect the client received a partial response body from the service, since the exception message indicates `Line 1, position 243679`.

We might be able to repro this using https://github.com/Azure/azure-sdk-tools/tree/master/tools/http-fault-injector to simulate a partial response.

Possibly related: #19501, #10294

**Comment by mikeharder** [comment]
I was able to repro this exception message using the following response from `http-fault-injector`:

```
pn: Partial Response (full headers, 50% of body), then finish normally
```

Typically, when the Storage service sends a partial response, the TCP connection is aborted or reset.  Which corresponds to these options which cause the `BlobContainerClient` to retry instead of throwing this exception:

```
pc: Partial Response (full headers, 50% of body), then close (TCP FIN)
pa: Partial Response (full headers, 50% of body), then abort (TCP RST)
```

However, I think it should be possible for the Storage service to send a partial response then finish normally, which would explain this exception.
