### ISSUE TITLE
[BUG] Pipeline.RetryPolicy does not retry after SocketException

### ISSUE THREAD

**Issue by ymarcov** [Azure/azure-sdk-for-net#20979]
**Describe the bug**
`SocketException`s such as those generated by `ECONNRESET` (Connection Reset) errors are not retried by the `RetryPolicy`.
The reason for this is that when run through `HttpClient`, which the `RetryPolicy` wraps, the `SocketException`s are wrapped within `HttpRequestException`s. These are marked as not to be handled by `ResponseClassifier.IsRetriableException`. Hence they are not retried, despite the fact that they encapsulate an `IOException` which *is* meant to be handled by `ResposeClassifier.IsRetriableException`.

In `RetryPolicy.cs`, under `private async ValueTask ProcessAsync(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline, bool async)`, there is the following code:

```csharp
if (lastException != null)
{
    if (shouldRetry && /*WRONG RESULT FROM:*/ message.ResponseClassifier.IsRetriable(message, lastException))
    {
        GetDelay(attempt, out delay);
    }
    else
    {
        // Rethrow a singular exception
        if (exceptions!.Count == 1)
        {
            ExceptionDispatchInfo.Capture(lastException).Throw();
        }

        throw new AggregateException($"Retry failed after {attempt} tries.", exceptions);
    }
}
```

**Expected behavior**
`HttpRequestException`s should be retried.

**Actual behavior (include Exception or Stack Trace)**
They are simply not retried, and the `RetryPolicy` immediately throws them back up instead.

**To Reproduce**
Get any HTTP request to get reset or refused by the peer. It will not be retried.

**Environment:**
 - Azure.Core.dll 1.5.0
 - .NET Core 5.0

**Comment by pakrym** [comment]
>These are marked as not to be handled by ResponseClassifier.IsRetriableException

I'm not sure that's correct. We specifically retry RequestFailedException with status code 0 (0 means we never got the status code like in the SocketExceptions case).

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/ResponseClassifier.cs#L36

There is also a test that simulates this exact situation:

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/tests/HttpPipelineFunctionalTests.cs#L281

**Comment by aelij** [comment]
@pakrym We're referring to `HttpRequestException` thrown from the credential pipeline, not `RequestFailedException`.

Stack trace:

```
System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: Connection reset by peer.
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   --- End of inner exception stack trace ---
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](TIOAdapter adapter, Memory`1 buffer)
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithNtAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean isProxyAuth, HttpConnection connection, HttpConnectionPool connectionPool, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.AuthenticationHelper.SendWithAuthAsync(HttpRequestMessage request, Uri authUri, Boolean async, ICredentials credentials, Boolean preAuthenticate, Boolean isProxyAuth, Boolean doRequestAuth, HttpConnectionPool pool, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Http.HttpManager.ExecuteAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, HttpMethod method)
   at Microsoft.Identity.Client.Http.HttpManager.ExecuteWithRetryAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, HttpMethod method, ICoreLogger logger, Boolean doNotThrow, Boolean retry)
   at Microsoft.Identity.Client.Http.HttpManager.SendPostAsync(Uri endpoint, IDictionary`2 headers, HttpContent body, ICoreLogger logger)
   at Microsoft.Identity.Client.Http.HttpManager.SendPostAsync(Uri endpoint, IDictionary`2 headers, IDictionary`2 bodyParameters, ICoreLogger logger)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint)
   at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.SendTokenRequestAsync(String tokenEndpoint, IDictionary`2 additionalBodyParameters, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Adp.Azure.ClientPinnedCertificateCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(HttpMessage message, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
```

**Comment by ymarcov** [comment]
> > These are marked as not to be handled by ResponseClassifier.IsRetriableException
> 
> I'm not sure that's correct. We specifically retry RequestFailedException with status code 0 (0 means we never got the status code like in the SocketExceptions case).
> 
> https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/src/ResponseClassifier.cs#L36
> 
> There is also a test that simulates this exact situation:
> 
> https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/tests/HttpPipelineFunctionalTests.cs#L281

Isn't the test just checking for a timeout? Is an IO exception actually generated there?
As @aelij says, `HttpRequestException` != `RequestFailedException`.

Perhaps a good test for this case would be to initiate a connection that keeps sending data, and have the server close the socket in the middle. This AFAIK should trigger an RST packet which should result in an IOException. See if that gets retried. Just an idea.

**Comment by pakrym** [comment]
The pipeline is not supposed to retry the exception coming from the `GetTokenAsync`.

It seems you have a custom implementation of TokenCredential - `Microsoft.Azure.Adp.Azure.ClientPinnedCertificateCredential`. The expectation is that credential types would handle retries internaly.

**Comment by ymarcov** [comment]
@pakrym Sounds fair enough. Can I ask, what's the rationale for this, though?

**Comment by pakrym** [comment]
We treat TokenCredential implementation as clients of their own. Every Azure SDK client method would do its retries internally and we expect similar behavior from the TokenCredential implementations. This allows TokenCredential to be used outside of HTTP pipeline (AMQP client auth, SQL client auth, etc.)

**Comment by ymarcov** [comment]
@pakrym  Thank you, that explains it perfectly!
