### ISSUE TITLE
[Flaky Test] BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#21005]
```
BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs

Result Details
Failed 2h ago on 36a07c10c000006
Duration0:00:01.070
Ownernot available
Date started5/11/2021, 11:16:16 AM
Date completed5/11/2021, 11:16:17 AM
Failing since2h ago
Failing since build20210511.13

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: True
But was:  False


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs() in /mnt/vss/_work/1/s/sdk/core/Azure.Core/tests/BearerTokenAuthenticationPolicyTests.cs:line 716
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by pakrym** [comment]
cc @christothes

**Comment by pakrym** [comment]
```
BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs

Result Details
Failed 2h ago on e2c2d09cc000002
Duration0:00:01.917
Ownernot available
Date started5/25/2021, 10:43:24 AM
Date completed5/25/2021, 10:43:26 AM
Failing since2h ago
Failing since build20210525.4

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: True
But was:  False


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\BearerTokenAuthenticationPolicyTests.cs:line 716
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=934951&view=ms.vss-test-web.build-test-results-tab&runId=20051536&resultId=101680&paneView=debug

```
Failed 5h ago on 9acdbe4cc000000
Duration0:00:02.757
Ownernot available
Date started6/8/2021, 3:54:25 AM
Date completed6/8/2021, 3:54:28 AM
Failing since5h ago
Failing since build20210608.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: True
But was:  False


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\BearerTokenAuthenticationPolicyTests.cs:line 716
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
```

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=938660&view=ms.vss-test-web.build-test-results-tab&runId=20120642&resultId=100599&paneView=debug

```
BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs

Result Details
Failed 4h ago on c1f943f4c000000
Duration0:00:01.120
Ownernot available
Date started6/9/2021, 3:43:40 AM
Date completed6/9/2021, 3:43:41 AM
Failing sinceYesterday
Failing since build20210608.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: True
But was:  False


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs>d__20.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\BearerTokenAuthenticationPolicyTests.cs:line 716
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by pakrym** [comment]
@christothes @schaabs can one of you disable the test please considering Alexander is out for a while?

**Comment by christothes** [comment]
I'll take over his PR and merge the fix.

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=981633&view=logs&j=6e2e8c59-a131-5a64-1743-fd2912068bf6

```
BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs

Result Details
Failed 5h ago on d1b24d0cc000002
Duration0:00:01.473
Ownernot available
Date started7/2/2021, 3:43:50 AM
Date completed7/2/2021, 3:43:52 AM
Failing since5h ago
Failing since build20210702.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: True
But was:  False


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs>d__20.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\BearerTokenAuthenticationPolicyTests.cs:line 728
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1022747&view=ms.vss-test-web.build-test-results-tab&runId=22005434&resultId=102584&paneView=debug

```
Error message
Expected: True
But was:  False


Stack trace
   at Azure.Core.Tests.BearerTokenAuthenticationPolicyTests.<BearerTokenAuthenticationPolicy_BackgroundRefreshCancelledAndLogs>d__20.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core\tests\BearerTokenAuthenticationPolicyTests.cs:line 728
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)

```

**Comment by JoshLove-msft** [comment]
Looks like this was fixed.
