### ISSUE TITLE
[BUG] ITableEntity interface does not describe runtime requires (Timestamp set is actually needed)

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#21023]
**Describe the bug**
As of version 12.0.0-beta.8 of Azure.Data.Tables, the property setter on `Timestamp` was removed from the interface. When querying for an entity type that doesn't have the setter implemented, an exception is thrown due to the missing setter. Presumably the reflection-ey code that materializes the entity is expecting to set the timestamp value returned in the HTTP response.

If the setter is added -- implementing `Timestamp { get; set; }` for a `Timestamp { get; }` interface -- the problem is resolved.

**Expected behavior**
I think the interface should represent what is actually needed by the `TableClient.QueryAsync<T>(...)` method. Either the setter should not be called if not present (a bit weird since it would be like a hidden feature to have the timestamp populated when implemented) or the setter should be included in the interface.

**Actual behavior (include Exception or Stack Trace)**
```
Unhandled exception. System.ArgumentException: Property set method not found.
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, BindingFlags invokeAttr, Binder binder, Object[] index, CultureInfo culture)
   at System.Reflection.RuntimePropertyInfo.SetValue(Object obj, Object value, Object[] index)
   at System.Reflection.PropertyInfo.SetValue(Object obj, Object value)
   at Azure.Data.Tables.DictionaryTableExtensions.<>c.<.cctor>b__8_12(PropertyInfo property, Object propertyValue, Object result)
   at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntity[T](IDictionary`2 entity, PropertyInfo[] properties)
   at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntityList[T](IReadOnlyList`1 entityList)
   at Azure.Data.Tables.TableClient.<>c__DisplayClass44_0`1.<<QueryAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at ConsoleApp1.Program.Main(String[] args) in C:\z\trash\2021-05-11\ConsoleApp1\ConsoleApp1\Program.cs:line 18
   at ConsoleApp1.Program.<Main>(String[] args)
```

**To Reproduce**
```csharp
using Azure;
using Azure.Data.Tables;
using System;
using System.Threading.Tasks;

namespace ConsoleApp1
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var tableServiceClient = new TableServiceClient("UseDevelopmentStorage=true");
            var tableClient = tableServiceClient.GetTableClient("testissue21023");
            await tableClient.CreateIfNotExistsAsync();
            var entity = new TestEntity { PartitionKey = "pk", RowKey = "rk" };
            await tableClient.UpsertEntityAsync(entity, TableUpdateMode.Replace);

            await tableClient.QueryAsync<TestEntity>().GetAsyncEnumerator().MoveNextAsync();
        }
    }

    class TestEntity : ITableEntity
    {
        public string PartitionKey { get; set; }
        public string RowKey { get; set; }
        public DateTimeOffset? Timestamp { get; }
        public ETag ETag { get; set; }
    }
}
```

**Environment:**
 - Name and version of the Library package used: Azure.Data.Tables 12.0.0-beta.8
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows, .NET 5.0.300-preview.21228.15
 - IDE and version : VS 16.10 preview

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Thanks @joelverhagen - I actually ran into this recently also and agree it is a bad experience. We initially removed it because the Timestamp value, if set, is ignored by the service. I'll get this fixed before the next release.
