### ISSUE TITLE
[BUG] ManagedIdentityCredential does not extract response content when throwing an exception

### ISSUE THREAD

**Issue by henriblMSFT** [Azure/azure-sdk-for-net#21079]
**Describe the bug**
Exception when calling the managed service identity server do not contain the response content. But that response content contains useful information information to diagnose the problem.

**Expected behavior**
The exception thrown should contain the content of the HttpResponse.
For example, performing this call on an Azure App Service with no system assigned managed identity return this response
`http://127.0.0.1:41556/MSI/token/?api-version=2017-09-01&resource=https%3A%2F%2management.azure.net`

HttpStatusCode: 400
Content: 
```json
{"StatusCode":400,"Message":"No MSI found for specified ClientId/ResourceId.","CorrelationId":"00000000-0000-0000-0000-000000000000"}
```
**Actual behavior (include Exception or Stack Trace)**
The exception throw has the following information:
```
Type: Azure.RequestFailedException
Message: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Thu, 13 May 2021 21:08:39 GMT
Content-Length: 133

StackTrace:
   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
```
**To Reproduce**
Execute the following on an Azure App Service without a system assigned managed identity
```csharp
var credential = new Azure.Identity.ManagedIdentityCredential();
credential.GetToken();
```
**Environment:**
 -  Package used: `Azure.Identity 1.4.0 `
 - Hosting platform: `Azure App Service`
 - .NET runtime version
 ```
 dotnet --info
.NET SDK (reflecting any global.json):
 Version:   5.0.201
 Commit:    a09bd5c86c

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\5.0.201\

Host (useful for support):
  Version: 5.0.4
  Commit:  f27d337295

.NET SDKs installed:
  1.1.14 [C:\Program Files (x86)\dotnet\sdk]
  2.1.518 [C:\Program Files (x86)\dotnet\sdk]
  2.1.521 [C:\Program Files (x86)\dotnet\sdk]
  2.1.522 [C:\Program Files (x86)\dotnet\sdk]
  2.2.109 [C:\Program Files (x86)\dotnet\sdk]
  3.1.111 [C:\Program Files (x86)\dotnet\sdk]
  3.1.112 [C:\Program Files (x86)\dotnet\sdk]
  3.1.113 [C:\Program Files (x86)\dotnet\sdk]
  5.0.201 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.26 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.4 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @henriblMSFT - Do you get the additional context needed with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/e4c4e7f3985e73fb1e0ad56af1ba6bccf5bfe867/sdk/core/Azure.Core/samples/Diagnostics.md)?

**Comment by henriblMSFT** [comment]
Are you suggesting enabling this:
```csharp
SecretClientOptions options = new SecretClientOptions()
{
    Diagnostics =
    {
        IsLoggingContentEnabled = true
    }
};
```
From my brief step through the code the failure content is not extracted at all because there is no override of the ExtractErrorContent method for ClientDiagnostics.
[ManagedIdentitySource. HandleResponseAsync](
https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/identity/Azure.Identity/src/ManagedIdentitySource.cs#L55)
calls 
[Pipeline.Diagnostics.CreateRequestFailedExceptionAsync](https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L53)

which then calls 
[ExtractErrorContent ](https://github.com/Azure/azure-sdk-for-net/blob/850df4dc21246f6d216e8ed472313b741a8362b7/sdk/core/Azure.Core/src/Shared/ClientDiagnostics.cs#L45)

I could not find a speicifc implementation of `ClientDiagnostics `for `Azure.Identity`

**Comment by christothes** [comment]
Here is an example:

```c#
var options = new DefaultAzureCredentialOptions{
    Diagnostics  = {
	IsLoggingContentEnabled = true
    }
};
```

**Comment by henriblMSFT** [comment]
There is no additional information likely because ExtractErrorContent is not overwritten.
```csharp
var options = new DefaultAzureCredentialOptions
{
    Diagnostics = {
        IsLoggingContentEnabled = true
    }
};

var cred = new DefaultAzureCredential(options);

var context = new TokenRequestContext(new[] { "https://manangement.azure.com/.default" });
try
{
    cred.GetToken(context);
}
catch(Exception ex)
{
    Console.WriteLine("Failed to acquire token: " + ex.ToString());
}
```
```
.\msi_failure.exe
Failed to acquire token: Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Tue, 18 May 2021 02:51:12 GMT
Content-Length: 133

 ---> Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Tue, 18 May 2021 02:51:12 GMT
Content-Length: 133

   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Identity.ManagedIdentityCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
```

**Comment by christothes** [comment]
Hi @henriblMSFT - It looks like you didn't add a logger. For example:

```c#
// Setup a listener to monitor logged events.
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
```

https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md

**Comment by henriblMSFT** [comment]
Enabling content logging does output the content but I think this misses the point of this bug. 

A user of the Azure.Identity library shouldn't have to enable diagnostics logging and capture this diagnostics in order to view this message, it should be part of the exception message or exception data.

As I mentioned earlier enabling diagnostic logging in our existing application isn't as simple as flipping a switch, our changes need to go through 2 separate pull request, a listener to pipe the AzureEventSource to application insights has to be added, and a settings to enable this flag on demand has to be created. That's a lot of work for something that could be handled by the framework.

For reference, adding
```csharp
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
```
produces the following logs
```
[Informational] Azure-Identity: DefaultAzureCredential.GetToken invoked. Scopes: [ https://manangement.azure.com/.default ] ParentRequestId: 
[Informational] Azure-Identity: EnvironmentCredential.GetToken invoked. Scopes: [ https://manangement.azure.com/.default ] ParentRequestId: 
[Informational] Azure-Identity: EnvironmentCredential.GetToken was unable to retrieve an access token. Scopes: [ https://manangement.azure.com/.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
[Informational] Azure-Identity: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://manangement.azure.com/.default ] ParentRequestId: 
[Informational] Azure-Core: Request [cffd0b24-9524-40ce-9963-c10521513040] GET http://127.0.0.1:41734/MSI/token/?api-version=REDACTED&resource=REDACTED
secret:REDACTED
x-ms-client-request-id:cffd0b24-9524-40ce-9963-c10521513040
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.0,(.NET 5.0.4; Microsoft Windows 10.0.14393)
client assembly: Azure.Identity
[Warning] Azure-Core: Error response [cffd0b24-9524-40ce-9963-c10521513040] 400 Bad Request (00.2s)
Date:Tue, 18 May 2021 15:30:53 GMT
Content-Length:133

[Informational] Azure-Core: Error response [cffd0b24-9524-40ce-9963-c10521513040] content: 7B22537461747573436F6465223A3430302C224D657373616765223A224E6F204D534920666F756E6420666F722073706563696669656420436C69656E7449642F5265736F7572636549642E222C22436F7272656C6174696F6E4964223A2266336339616563302D376661322D343138342D616430662D306336386365356663373438227D
[Informational] Azure-Identity: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://manangement.azure.com/.default ] ParentRequestId:  
```
if you then manually decode the Cotent hex you get
```json
{"StatusCode":400,"Message":"No MSI found for specified ClientId/ResourceId.","CorrelationId":"f3c9aec0-7fa2-4184-ad0f-0c68ce5fc748"}
```

**Comment by christothes** [comment]
Thanks @henriblMSFT - Thanks for the feedback and for confirming that the logging does expose this error message indirectly. This additional context makes the problem very clear.

I'll take this issue as a feature request to expose that error text more directly.
