### ISSUE TITLE
[Flaky test] Champion_BasicCheckpointing

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#21228]
```
Champion_BasicCheckpointing

Result Details
Failed 7h ago on 76d1bd8bc000000
Duration0:00:01.123
Ownernot available
Date started5/20/2021, 1:24:22 AM
Date completed5/20/2021, 1:24:23 AM
Failing since7h ago
Failing since build20210520.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: 489
But was:  1001


Stack trace
   at Azure.Search.Documents.Tests.BatchingTests.<Champion_BasicCheckpointing>d__17.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 394
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Search.Documents.Tests.BatchingTests.<Champion_BasicCheckpointing>d__17.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Search.Documents.Tests.BatchingTests.<Champion_BasicCheckpointing>d__17.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 395
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
```

**Comment by Mohit-Chakraborty** [comment]
@pakrym - I don't see any failures of `Champion_BasicCheckpointing` either in the Core or Search CI pipeline. Where I can get the link to a run with a failure of this test?

**Comment by pakrym** [comment]
I'll make sure to add it next time.

**Comment by Mohit-Chakraborty** [comment]
Closing for now. Will reopen if there are additional reports of this test failing.

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_test/analytics?definitionId=1180&contextType=build

**Comment by Mohit-Chakraborty** [comment]
Thanks, I favorited the Core and Search pipelines. I see there are public and internal pipelines.
Based on your comments in #21515, I am reopening this.

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=945668&view=ms.vss-test-web.build-test-results-tab&runId=20253758&resultId=112091&paneView=debug

```
Champion_BasicCheckpointing

Result Details
Failed 26m ago on 55e25914c000003
Duration0:00:01.253
Ownernot available
Date started6/14/2021, 9:38:19 AM
Date completed6/14/2021, 9:38:21 AM
Failing since26m ago
Failing since build20210614.1

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: 489
But was:  707


Stack trace
   at Azure.Search.Documents.Tests.BatchingTests.Champion_BasicCheckpointing() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 392
   at Azure.Search.Documents.Tests.BatchingTests.Champion_BasicCheckpointing() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 395
   at Azure.Search.Documents.Tests.BatchingTests.Champion_BasicCheckpointing() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 395
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```
