### ISSUE TITLE
[ACR] Address failing nightly tests

### ISSUE THREAD

**Issue by annelo-msft** [Azure/azure-sdk-for-net#21236]
The .NET ACR library nightly tests have been failing non-deterministically since 05/13, with what looks like an error in the mangement-plane Track 1 library with the import image operation (see below).  If the image cannot be imported, the test will fail.

The goal of this issue is to understand why this started recently and resolve the issue so that the ACR nightly tests pass consistently again.

``` Failed CanDeleteRepostitory [21 s]
  Error Message:
   Microsoft.Rest.Azure.CloudException : Long running operation failed with status 'BadRequest'.
  Stack Trace:
     at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.CheckErrorStatusAndThrowAsync(HttpRequestMessage request, HttpResponseMessage response)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.GetRawAsync(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.UpdateResourceFromPollingUri(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.LROPollState`2.Poll(Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.StartPollingAsync()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.BeginLROAsync()
   at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody,THeader](IAzureClient client, AzureOperationResponse`2 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody](IAzureClient client, AzureOperationResponse`1 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.Azure.AzureClientExtensions.GetPostOrDeleteOperationResultAsync(IAzureClient client, AzureOperationResponse response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerRegistry.RegistriesOperations.ImportImageWithHttpMessagesAsync(String resourceGroupName, String registryName, ImportImageParameters parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerRegistry.RegistriesOperationsExtensions.ImportImageAsync(IRegistriesOperations operations, String resourceGroupName, String registryName, ImportImageParameters parameters, CancellationToken cancellationToken)
   at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryRecordedTestBase.ImportImage(String registry, String repository, List`1 tags) in /mnt/vss/_work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRegistryRecordedTestBase.cs:line 72
   at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryClientLiveTests.CanDeleteRepostitory() in /mnt/vss/_work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRegistryClientLiveTests.cs:line 120
   at Azure.Containers.ContainerRegistry.Tests.ContainerRegistryClientLiveTests.CanDeleteRepostitory() in /mnt/vss/_work/1/s/sdk/containerregistry/Azure.Containers.ContainerRegistry/tests/ContainerRegistryClientLiveTests.cs:line 151
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by jsquire** [comment]
Given the age of this issue, I'm going to close it as stale.  If tests continue to fail, please file a new issue.
