### ISSUE TITLE
[Flaky test] CreatePartitionProcessorDoesNotAllowReadingLastEventPropertiesWithNoConsumer

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#21295]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=909400&view=ms.vss-test-web.build-test-results-tab&runId=19572950&resultId=105153&paneView=debug

```
CreatePartitionProcessorDoesNotAllowReadingLastEventPropertiesWithNoConsumer

Result Details
Failed 1h ago on Mac-1621873089053
Duration0:00:00.824
Ownernot available
Date started5/24/2021, 10:14:07 AM
Date completed5/24/2021, 10:14:07 AM
Failing since1h ago
Failing since build20210524.2

Debug

Work items

Attachments

History

Attachments*

Error message
System.AggregateException : One or more errors occurred. (Object reference not set to an instance of an object.)
----> System.NullReferenceException : Object reference not set to an instance of an object.


Stack trace
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at Azure.Messaging.EventHubs.Tests.EventProcessorTests.CreatePartitionProcessorDoesNotAllowReadingLastEventPropertiesWithNoConsumer() in /Users/runner/work/1/s/sdk/eventhub/Azure.Messaging.EventHubs/tests/Primitives/EventProcessorTests.PartitionProcessing.cs:line 253
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
--NullReferenceException
   at Azure.Messaging.EventHubs.Primitives.EventProcessor`1.<>c.<CreatePartitionProcessor>b__62_2(Object state) in /_/sdk/eventhub/Azure.Messaging.EventHubs/src/Primitives/EventProcessor.cs:line 697
   at System.Threading.CancellationTokenSource.CallbackNode.<>c.<ExecuteCallback>b__9_0(Object s)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)

```

cc @jsquire

**Comment by jsquire** [comment]
fixed by #21441
