### ISSUE TITLE
[Flaky Test] Event Hubs Function Bindings:  `EventHub_InitialOffsetFromEnqueuedTime`

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#21298]
# Summary

This test has been observed to be intermittently failing in nightly runs;  failures are transient and a re-run usually resolves the issue.  Now that the bindings have reached a level of stability, we should investigate and stabilize.

# Details

```text
2021-05-24T09:41:02.0880370Z   Failed EventHub_InitialOffsetFromEnqueuedTime [37 s]
2021-05-24T09:41:02.0882550Z   Error Message:
2021-05-24T09:41:02.0883630Z      Expected: True
2021-05-24T09:41:02.0884710Z   But was:  False
2021-05-24T09:41:02.0886010Z 
2021-05-24T09:41:02.0887110Z   Stack Trace:
2021-05-24T09:41:02.0888710Z      at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.EventHub_InitialOffsetFromEnqueuedTime() in /Users/runner/work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 434
2021-05-24T09:41:02.0890660Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
2021-05-24T09:41:02.0892220Z    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
2021-05-24T09:41:02.0893780Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2021-05-24T09:41:02.0895200Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
2021-05-24T09:41:02.0896670Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2021-05-24T09:41:02.0898130Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
2021-05-24T09:41:02.0899730Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Example Run:**
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=909026&view=ms.vss-test-web.build-test-results-tab&runId=19565498&resultId=102010&paneView=debug

**Comment by jsquire** [comment]
//cc: @pakrym, @JoshLove-msft
