### ISSUE TITLE
[Flaky Test] Event Hubs Function Bindings: Failures in UsGov and China Clouds

### ISSUE THREAD

**Issue by jsquire** [Azure/azure-sdk-for-net#21300]
# Summary

For the last two weeks, the suite of tests for the Event Hubs function bindings has been failing in the USGov and China clouds.   The impacted tests vary, but reruns have not been able to clear the failures across the entire suite.  Failures do not appear to consistently impact a specific test nor resource;  sometimes the storage account cannot be reached, other times it presents as a socket error which may indicate the Event Hubs instance is not reachable.  

Unsure if these are related to the Functions service or general network stability.   The tests from the other Event Hubs library do not appear to be suffering the same failure pattern during these runs.  

Perhaps we should consider alternate data centers.

# Details

```text
2021-05-23T09:14:01.1010122Z   Failed CanSendAndReceive_AccountName_InConfiguration [31 s]
2021-05-23T09:14:01.1012330Z   Error Message:
2021-05-23T09:14:01.1014019Z    Microsoft.Azure.WebJobs.Host.Listeners.FunctionListenerException : The listener for function 'EventHubTestSingleDispatchJobWithConnection.ProcessSingleEvent' was unable to start.
2021-05-23T09:14:01.1015905Z   ----> System.AggregateException : Retry failed after 6 tries.
2021-05-23T09:14:01.1017360Z   ----> Azure.RequestFailedException : The remote name could not be resolved: 'blbtb737c2cd8cac4e0f.blob.core.windows.net'
2021-05-23T09:14:01.1018874Z   ----> Azure.RequestFailedException : The remote name could not be resolved: 'blbtb737c2cd8cac4e0f.blob.core.windows.net'
2021-05-23T09:14:01.1020427Z   ----> Azure.RequestFailedException : The remote name could not be resolved: 'blbtb737c2cd8cac4e0f.blob.core.windows.net'
2021-05-23T09:14:01.1021949Z   ----> Azure.RequestFailedException : The remote name could not be resolved: 'blbtb737c2cd8cac4e0f.blob.core.windows.net'
2021-05-23T09:14:01.1023228Z   ----> Azure.RequestFailedException : The remote name could not be resolved: 'blbtb737c2cd8cac4e0f.blob.core.windows.net'
2021-05-23T09:14:01.1024301Z   ----> Azure.RequestFailedException : The remote name could not be resolved: 'blbtb737c2cd8cac4e0f.blob.core.windows.net'
2021-05-23T09:14:01.1025144Z   Stack Trace:
2021-05-23T09:14:01.1026181Z      at Microsoft.Azure.WebJobs.Host.RecoverableException.TryRecover(ILogger logger) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Exceptions\RecoverableException.cs:line 81
2021-05-23T09:14:01.1027662Z    at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.<StartAsync>d__13.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 81
2021-05-23T09:14:01.1028831Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1029746Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1030647Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1031864Z    at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.<StartAsync>d__12.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 61
2021-05-23T09:14:01.1033048Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1034089Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1034997Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1036214Z    at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.<StartAsync>d__4.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\CompositeListener.cs:line 39
2021-05-23T09:14:01.1037378Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1038231Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1039211Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1040470Z    at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.<StartAsyncCore>d__8.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\ListenerFactoryListener.cs:line 47
2021-05-23T09:14:01.1041795Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1042833Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1043794Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1045015Z    at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.<StartAsync>d__5.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\ShutdownListener.cs:line 29
2021-05-23T09:14:01.1046172Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1047008Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1047910Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1049177Z    at Microsoft.Azure.WebJobs.JobHost.<StartAsyncCore>d__21.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 99
2021-05-23T09:14:01.1050265Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1051092Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1051984Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1052852Z    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
2021-05-23T09:14:01.1054190Z    at Microsoft.Azure.WebJobs.Host.EndToEndTests.WebJobsEventHubTestBase.BuildHost[T](Action`1 configurationDelegate, Action`1 preStartCallback) in D:\a\_work\1\s\sdk\eventhub\Microsoft.Azure.WebJobs.Extensions.EventHubs\tests\WebJobsEventHubTestBase.cs:line 95
2021-05-23T09:14:01.1055886Z    at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.<AssertCanSendReceiveMessage>d__17.MoveNext() in D:\a\_work\1\s\sdk\eventhub\Microsoft.Azure.WebJobs.Extensions.EventHubs\tests\EventHubEndToEndTests.cs:line 253
2021-05-23T09:14:01.1057110Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1057934Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1058809Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1059741Z    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
2021-05-23T09:14:01.1060967Z    at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.<CanSendAndReceive_AccountName_InConfiguration>d__14.MoveNext() in D:\a\_work\1\s\sdk\eventhub\Microsoft.Azure.WebJobs.Extensions.EventHubs\tests\EventHubEndToEndTests.cs:line 222
2021-05-23T09:14:01.1062226Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1063053Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1063935Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1064885Z    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2021-05-23T09:14:01.1065738Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
2021-05-23T09:14:01.1066578Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2021-05-23T09:14:01.1067474Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
2021-05-23T09:14:01.1068416Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2021-05-23T09:14:01.1069501Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
2021-05-23T09:14:01.1070563Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
2021-05-23T09:14:01.1071438Z --AggregateException
2021-05-23T09:14:01.1072193Z    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1073046Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1073965Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1074863Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1075795Z    at Azure.Storage.Blobs.BlobRestClient.Container.<CreateAsync>d__0.MoveNext()
2021-05-23T09:14:01.1076663Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1077509Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1078393Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1079388Z    at Azure.Storage.Blobs.BlobContainerClient.<CreateInternal>d__61.MoveNext()
2021-05-23T09:14:01.1080359Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1081214Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1082108Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1083063Z    at Azure.Storage.Blobs.BlobContainerClient.<CreateIfNotExistsInternal>d__60.MoveNext()
2021-05-23T09:14:01.1083925Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1084755Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1085625Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1086536Z    at Azure.Storage.Blobs.BlobContainerClient.<CreateIfNotExistsAsync>d__58.MoveNext()
2021-05-23T09:14:01.1087402Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1088238Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1089224Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1090192Z    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
2021-05-23T09:14:01.1091367Z    at Azure.Messaging.EventHubs.Processor.BlobsCheckpointStore.<CreateIfNotExistsAsync>d__5.MoveNext() in /_/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/BlobsCheckpointStore.cs:line 83
2021-05-23T09:14:01.1092480Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1093322Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1094197Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1095141Z    at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
2021-05-23T09:14:01.1096265Z    at Microsoft.Azure.WebJobs.EventHubs.EventHubListener.<StartAsync>d__10.MoveNext() in /_/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/src/Listeners/EventHubListener.cs:line 74
2021-05-23T09:14:01.1097437Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1098277Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1099269Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1100493Z    at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.<StartAsync>d__13.MoveNext() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 69
2021-05-23T09:14:01.1101538Z --RequestFailedException
2021-05-23T09:14:01.1102302Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessInternal>d__7.MoveNext()
2021-05-23T09:14:01.1103168Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1104079Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1104956Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1105865Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessAsync>d__6.MoveNext()
2021-05-23T09:14:01.1106721Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1107545Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1108432Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1109454Z    at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
2021-05-23T09:14:01.1110344Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1111257Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1112139Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1113039Z    at Azure.Core.Pipeline.LoggingPolicy.<ProcessAsync>d__9.MoveNext()
2021-05-23T09:14:01.1115624Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1116458Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1117340Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1118248Z    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1119180Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1120012Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1120878Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1121829Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<<ProcessAsync>g__ProcessAsyncInner|4_0>d.MoveNext()
2021-05-23T09:14:01.1122741Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1123664Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1124787Z    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1125823Z --RequestFailedException
2021-05-23T09:14:01.1127026Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessInternal>d__7.MoveNext()
2021-05-23T09:14:01.1128339Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1129682Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1131003Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1132432Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessAsync>d__6.MoveNext()
2021-05-23T09:14:01.1134628Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1135917Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1137264Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1138645Z    at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
2021-05-23T09:14:01.1140077Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1141307Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1142630Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1144061Z    at Azure.Core.Pipeline.LoggingPolicy.<ProcessAsync>d__9.MoveNext()
2021-05-23T09:14:01.1145399Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1146704Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1148074Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1149603Z    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1150987Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1152267Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1153609Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1155076Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<<ProcessAsync>g__ProcessAsyncInner|4_0>d.MoveNext()
2021-05-23T09:14:01.1156150Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1157096Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1157920Z    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1158642Z --RequestFailedException
2021-05-23T09:14:01.1159479Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessInternal>d__7.MoveNext()
2021-05-23T09:14:01.1160343Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1161178Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1162053Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1162954Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessAsync>d__6.MoveNext()
2021-05-23T09:14:01.1163873Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1164730Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1165621Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1166513Z    at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
2021-05-23T09:14:01.1167366Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1168194Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1169126Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1170036Z    at Azure.Core.Pipeline.LoggingPolicy.<ProcessAsync>d__9.MoveNext()
2021-05-23T09:14:01.1170884Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1171821Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1172986Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1173930Z    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1174850Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1176073Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1176962Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1177931Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<<ProcessAsync>g__ProcessAsyncInner|4_0>d.MoveNext()
2021-05-23T09:14:01.1178916Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1179769Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1180583Z    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1181302Z --RequestFailedException
2021-05-23T09:14:01.1182060Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessInternal>d__7.MoveNext()
2021-05-23T09:14:01.1182927Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1183782Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1184719Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1185619Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessAsync>d__6.MoveNext()
2021-05-23T09:14:01.1186486Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1187326Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1188201Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1189205Z    at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
2021-05-23T09:14:01.1190062Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1190985Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1191852Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1192766Z    at Azure.Core.Pipeline.LoggingPolicy.<ProcessAsync>d__9.MoveNext()
2021-05-23T09:14:01.1193644Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1194471Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1195344Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1196254Z    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1197128Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1197940Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1198815Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1199919Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<<ProcessAsync>g__ProcessAsyncInner|4_0>d.MoveNext()
2021-05-23T09:14:01.1200840Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1201658Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1202465Z    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1203173Z --RequestFailedException
2021-05-23T09:14:01.1203980Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessInternal>d__7.MoveNext()
2021-05-23T09:14:01.1204857Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1205678Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1206548Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1207470Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessAsync>d__6.MoveNext()
2021-05-23T09:14:01.1208691Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1209608Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1210480Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1211359Z    at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
2021-05-23T09:14:01.1212219Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1213066Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1213928Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1214780Z    at Azure.Core.Pipeline.LoggingPolicy.<ProcessAsync>d__9.MoveNext()
2021-05-23T09:14:01.1215601Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1216409Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1217279Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1218191Z    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1219180Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1226371Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1227296Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1228273Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<<ProcessAsync>g__ProcessAsyncInner|4_0>d.MoveNext()
2021-05-23T09:14:01.1229350Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1230304Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1231124Z    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1231897Z --RequestFailedException
2021-05-23T09:14:01.1232850Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessInternal>d__7.MoveNext()
2021-05-23T09:14:01.1233773Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1234613Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1235480Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1236381Z    at Azure.Core.Pipeline.HttpWebRequestTransport.<ProcessAsync>d__6.MoveNext()
2021-05-23T09:14:01.1237231Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1238069Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1239039Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1239956Z    at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
2021-05-23T09:14:01.1240801Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1241636Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1242507Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1243387Z    at Azure.Core.Pipeline.LoggingPolicy.<ProcessAsync>d__9.MoveNext()
2021-05-23T09:14:01.1244312Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1245136Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1246028Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1246947Z    at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
2021-05-23T09:14:01.1247830Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1249127Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1250043Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2021-05-23T09:14:01.1251008Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<<ProcessAsync>g__ProcessAsyncInner|4_0>d.MoveNext()
2021-05-23T09:14:01.1251930Z --- End of stack trace from previous location where exception was thrown ---
2021-05-23T09:14:01.1252770Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2021-05-23T09:14:01.1253599Z    at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
```

**Example Run:**
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=908432&view=ms.vss-test-web.build-test-results-tab&runId=19560138&resultId=102062&paneView=debug

**Comment by jsquire** [comment]
//cc: @pakrym, @JoshLove-msft

**Comment by jsquire** [comment]
This appears to be fixed; some timeouts still occur randomly, but patterns of flakiness have been addressed.
