### ISSUE TITLE
[QUERY] Unauthorized exception when using DefaultAzureCredential with only AzureCliCredential enabled

### ISSUE THREAD

**Issue by hitochan777** [Azure/azure-sdk-for-net#21453]
**Query/Question**

I am using `DefaultAzureCredential` from `Azure.Identity` with only `AzureCliCredential` enabled to allow authentication to Azure Active Directory using Azure CLI to obtain an access token.

Then an instance of `RegistryManager` for IoTHub is created with the credential to get a list of devices registered in a specific IoTHub resource.

The code is shown below:

```csharp
namespace default_azure_credential_repro
{
    using System;
    using System.Threading.Tasks;
    using Microsoft.Azure.Devices;
    using Azure.Identity;
    class Program
    {
        static async Task Main(string[] args)
        {
            var credential = new DefaultAzureCredential(
                new DefaultAzureCredentialOptions {
                    ExcludeVisualStudioCredential = true,
                    ExcludeVisualStudioCodeCredential = true,
                    ExcludeAzurePowerShellCredential = true,
                    ExcludeEnvironmentCredential = true,
                    ExcludeSharedTokenCacheCredential = true,
                    ExcludeManagedIdentityCredential = true,
                }
            );
    		var hostName = "{host name here}";
            var manager = RegistryManager.Create(hostName, credential);
            var query = manager.CreateQuery("select * from devices", 100);
            while (query.HasMoreResults) {
                foreach (var device in await query.GetNextAsTwinAsync()) {
                    Console.WriteLine(device.DeviceId);
                }
            }
        }
    }
}

```

When I ran the code above, I got the following error, indicating that the access token does not have the permission to call API required to query devices.

```
Unhandled exception. Microsoft.Azure.Devices.Common.Exceptions.UnauthorizedException: {"Message":"{\"errorCode\":401003,\"trackingId\":\"{trackingIdHere}\",\"message\":\"Principal live.com#myemailaddress@example.com is not authorized for POST on /devices/query due to no assigned permissions\",\"timestampUtc\":\"2021-05-29T13:33:29.0065016Z\"}","ExceptionMessage":""}
```

But I am able to list devices with az cli using the following command.

```
$ az iot hub device-identity list -n {resource name here}
```

Why does my program fail but running az cli succeeds?
Thanks in advance.

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
    - Azure.Identity" Version 1.4.0
    - Microsoft.Azure.Devices" Version 1.34.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
   ```
    $ dotnet --info         
    .NET SDK (reflecting any global.json):
     Version:   5.0.202
     Commit:    db7cc87d51
    
    Runtime Environment:
     OS Name:     ubuntu
     OS Version:  20.04
     OS Platform: Linux
     RID:         ubuntu.20.04-x64
     Base Path:   /usr/share/dotnet/sdk/5.0.202/
    
    Host (useful for support):
      Version: 5.0.5
      Commit:  2f740adc14
    
    .NET SDKs installed:
      5.0.202 [/usr/share/dotnet/sdk]
    
    .NET runtimes installed:
      Microsoft.AspNetCore.App 3.1.14 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.AspNetCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
      Microsoft.NETCore.App 3.1.14 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
      Microsoft.NETCore.App 5.0.5 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
    
    To install additional .NET runtimes or SDKs:
      https://aka.ms/dotnet-download
   ```

 - IDE and version : [e.g. Visual Studio 16.3]
   VSCode 1.56.2

**Comment by christothes** [comment]
Hi @hitochan777 Are you able to acquire a token by running the following at the command line?

` az account get-access-token`

If so, does the following code return a token?

```c#
var cred = new AzureCliCredential();
var token = cred.GetToken(new TokenRequestContext(new[] { "https://storage.azure.com/.default" }), default);
Console.WriteLine($"[TOKEN] {token.Token}");
```

If both of these work, it seems that the credential is working properly. Could you provide a full stack from the error you are seeing and also enable logging for both the credential and the client you are using? 
Details on how to enable logging can be found [here.](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)

**Comment by hitochan777** [comment]
@christothes 
Getting access token in both ways worked.

> Could you provide a full stack from the error you are seeing and also enable logging for both the credential and the client you are using?

I was only able to figure out how to enable logging for `DefaultAzureCredential` and here's the log.

```
[Informational] Azure-Identity: DefaultAzureCredential.GetToken invoked. Scopes: [ https://iothubs.azure.net/.default ] ParentRequestId: 
[Informational] Azure-Identity: AzureCliCredential.GetToken invoked. Scopes: [ https://iothubs.azure.net/.default ] ParentRequestId: 
[Informational] Azure-Identity: AzureCliCredential.GetToken succeeded. Scopes: [ https://iothubs.azure.net/.default ] ParentRequestId:  ExpiresOn: 2021-06-10T14:22:15.3523770+00:00
[Informational] Azure-Identity: DefaultAzureCredential.GetToken succeeded. Scopes: [ https://iothubs.azure.net/.default ] ParentRequestId:  ExpiresOn: 2021-06-10T14:22:15.3523770+00:00
Unhandled exception. Microsoft.Azure.Devices.Common.Exceptions.UnauthorizedException: {"Message":"ErrorCode:IotHubUnauthorized;Principal live.com#{MY EMAIL ADDRESS HERE} is not authorized for POST on /devices/query due to no assigned permissions","ExceptionMessage":"Tracking ID:aa676e936038496cb8eecab2147cc73f-G:10-TimeStamp:06/10/2021 13:41:24"}
   at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpClient httpClient, HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`2 isMappedToException, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.HttpClientHelper.ExecuteAsync(HttpMethod httpMethod, Uri requestUri, Func`3 modifyRequestMessageAsync, Func`3 processResponseMessageAsync, IDictionary`2 errorMappingOverrides, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.HttpClientHelper.PostAsync[T](Uri requestUri, T entity, IDictionary`2 errorMappingOverrides, IDictionary`2 customHeaders, MediaTypeHeaderValue customContentType, ICollection`1 customContentEncoding, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.HttpRegistryManager.ExecuteQueryAsync(String sqlQueryString, Nullable`1 pageSize, String continuationToken, CancellationToken cancellationToken)
   at Microsoft.Azure.Devices.Query.GetNextAsync(QueryOptions options)
   at Microsoft.Azure.Devices.Query.GetAndCastNextResultAsync[T](QueryResultType type, QueryOptions options)
   at Microsoft.Azure.Devices.Query.GetNextAsTwinAsync(QueryOptions options)
   at Microsoft.Azure.Devices.Query.GetNextAsTwinAsync()
   at default_azure_credential_repro.Program.Main(String[] args) in /home/foobar/developer/default-azure-credential-repro/Program.cs:line 33
   at default_azure_credential_repro.Program.<Main>(String[] args)
```

By the way what I found is that the above program worked when I assign IoT Hub Data Contributor role to the principal and re-logged in on azure CLI.
But that is strange because the principal is global administrator of the tenant and it should have right to do basically everything (if my understanding is correct). Why do I have to assign specific role?

**Comment by christothes** [comment]
> By the way I found that the code above worked after I assigned IoT Hub Data Contributor role to the principal and re-logged in on azure CLI.
But that is strange because the principal is global administrator of the tenant and it should have right to do basically everything (if my understanding is correct). Why do I have to assign specific role?

In my experience, the explicit resource role or permission assignment is always necessary.

It sounds like your issue is resolved, so I'll close this out. Please re-open if you still feel this is unresolved.

**Comment by hitochan777** [comment]
> In my experience, the explicit resource role or permission assignment is always necessary.

I see. Thank you for your help!
