### ISSUE TITLE
[BUG] - Search API returns socket exception

### ISSUE THREAD

**Issue by amitkub** [Azure/azure-sdk-for-net#21457]
**Describe the bug**
We run the Azure cognitive search api to create indexrs and get the below exception:
```text
-> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
2021-05-31T00:20:00.7280530Z  ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
2021-05-31T00:20:00.7281464Z  ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
at Azure.Search.Documents.Indexes.SearchIndexerClient.CreateIndexerAsync(SearchIndexer indexer, CancellationToken cancellationToken)
```

**Expected behavior**
What is the expected behavior? An indexer created

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior? exception thrown 

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. call the indexer creation

**Environment:**
 - Name and version of the Library package used: [e.g. Azure.Storage.Blobs 12.2.0] 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): [e.g. Azure AppService or Windows 10 .NET Framework 4.8]
 - IDE and version : [e.g. Visual Studio 16.3]
nuget v11.1.1
Azure.search.documents

full stack trace:
```text
2021-05-31T00:20:00.7278125Z Unhandled exception. System.AggregateException: Retry failed after 4 tries. (The operation was canceled.) (The operation was canceled.) (The operation was canceled.) (The operation was canceled.)
2021-05-31T00:20:00.7279288Z  ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
2021-05-31T00:20:00.7280530Z  ---> System.IO.IOException: Unable to read data from the transport connection: The I/O operation has been aborted because of either a thread exit or an application request..
2021-05-31T00:20:00.7281464Z  ---> System.Net.Sockets.SocketException (995): The I/O operation has been aborted because of either a thread exit or an application request.
2021-05-31T00:20:00.7282059Z    --- End of inner exception stack trace ---
2021-05-31T00:20:00.7282582Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
2021-05-31T00:20:00.7283452Z    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.GetResult(Int16 token)
2021-05-31T00:20:00.7284044Z    at System.Net.Security.SslStream.<FillBufferAsync>g__InternalFillBufferAsync|215_0[TReadAdapter](TReadAdapter adap, ValueTask`1 task, Int32 min, Int32 initial)
2021-05-31T00:20:00.7285284Z    at System.Net.Security.SslStream.ReadAsyncInternal[TReadAdapter](TReadAdapter adapter, Memory`1 buffer)
2021-05-31T00:20:00.7286108Z    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
2021-05-31T00:20:00.7286584Z    --- End of inner exception stack trace ---
2021-05-31T00:20:00.7287098Z    at System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
2021-05-31T00:20:00.7288046Z    at System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-05-31T00:20:00.7290288Z    at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
2021-05-31T00:20:00.7290893Z    at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-05-31T00:20:00.7291470Z    at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
2021-05-31T00:20:00.7292060Z    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
2021-05-31T00:20:00.7292542Z    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message)
2021-05-31T00:20:00.7293074Z    at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
2021-05-31T00:20:00.7293673Z    at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
2021-05-31T00:20:00.7294261Z    at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
2021-05-31T00:20:00.7294828Z    at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
2021-05-31T00:20:00.7295385Z    at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
2021-05-31T00:20:00.7295924Z    at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
2021-05-31T00:20:00.7296457Z    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
2021-05-31T00:20:00.7296912Z    --- End of inner exception stack trace ---
2021-05-31T00:20:00.7297336Z    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
2021-05-31T00:20:00.7298061Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
2021-05-31T00:20:00.7298617Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
2021-05-31T00:20:00.7299175Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
2021-05-31T00:20:00.7299725Z    at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
2021-05-31T00:20:00.7300249Z    at Azure.Search.Documents.IndexersRestClient.CreateAsync(SearchIndexer indexer, CancellationToken cancellationToken)
2021-05-31T00:20:00.7300846Z    at Azure.Search.Documents.Indexes.SearchIndexerClient.CreateIndexerAsync(SearchIndexer indexer, CancellationToken cancellationToken)
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Mohit-Chakraborty** [comment]
@amitkub - can you provide more details on this -
1. How often are you hitting this issue?
1. Does the operation succeed on retry?

Also, please look at the discussion and workaround discussed in #9212. See if modifying the `Transport` and `Retry` properties on `SearchClientOptions` resolves the issue.

**Comment by amitkub** [comment]
Retry didn't work
I will try to change the transport in the next few days and confirm if this works or not.

**Comment by Mohit-Chakraborty** [comment]
@amitkub, did you get a chance to try the workarounds. Specifically, modifying [**both** the `Transport` and `Retry` properties](https://github.com/Azure/azure-sdk-for-net/issues/9212#issuecomment-678548888) on `SearchClientOptions`?
