### ISSUE TITLE
[Flaky test] Dispose_Blocks

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#21515]
```
Dispose_Blocks

Result Details
Failed Yesterday on Mac-1622588845670
Duration0:00:00.296
Ownernot available
Date started6/1/2021, 5:33:19 PM
Date completed6/1/2021, 5:33:19 PM
Failing sinceYesterday
Failing since build20210601.8

Debug

Work items

Attachments

History

Attachments*

Error message
Expected: 768
But was:  767


Stack trace
   at Azure.Search.Documents.Tests.BatchingTests.Dispose_Blocks() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 759
   at Azure.Search.Documents.Tests.BatchingTests.Dispose_Blocks() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 762
   at Azure.Search.Documents.Tests.BatchingTests.Dispose_Blocks() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 762
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by Mohit-Chakraborty** [comment]
@pakrym, I looked at the [30 day historical data](https://dev.azure.com/azure-sdk/public/_test/analytics?definitionId=509&contextType=build) for the 'net - search - ci' pipeline and don't see `Dispose_Blocks` as one of the failing tests.
Do you have the build link for the failure and a way to see the test result trend?

**Comment by pakrym** [comment]
It failed as part of core PR runs (Core runs all the tests)

**Comment by Mohit-Chakraborty** [comment]
Thanks.
Looking at [the data](https://dev.azure.com/azure-sdk/public/_test/analytics?definitionId=297&contextType=build) in 'net - core - ci', `Dispose_Blocks` failed 1 out of 1668 runs with a pass rate of 99.94% in the past 30 days.

I am inclined to not investigate this at the moment. Will revisit if the test starts failing regularly.

**Comment by Mohit-Chakraborty** [comment]
Based on the run data, this test seems very stable. Closing the issue for now, will reopen if there are continuing failures.

**Comment by pakrym** [comment]
>Based on the run data, this test seems very stable. Closing the issue for now, will reopen if there are continuing failures.

It's not. The failure is easily reproducible.

I'm not sure that closing flaky test issues because they are not annoying enough is the right thing to do. Even low-probability flaky tests add up when we have thousands of tests.

Core CI run is 30 minutes a single test failure requires a rerun it adds up./

**Comment by Mohit-Chakraborty** [comment]
> It's not. The failure is easily reproducible.

I was going by the test run results. What do you mean by this?

> Core CI run is 30 minutes a single test failure requires a rerun; it adds up.

That is fair. I am reopening this issue.

**Comment by pakrym** [comment]
>I was going by the test run results. What do you mean by this?

I mean it was very easy to reproduce the failure locally by wrapping the test body in 

```C#
            while (true)
            {
                StartTestRecording();
				....
			}
```

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1231206&view=ms.vss-test-web.build-test-results-tab&runId=26417474&resultId=118279&paneView=debug

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1242018&view=ms.vss-test-web.build-test-results-tab&runId=26628554&resultId=118147&paneView=debug

**Comment by JoshLove-msft** [comment]
This test has been marked as ignored in https://github.com/Azure/azure-sdk-for-net/pull/25927
Closing.
