### ISSUE TITLE
[BUG] EventSourceException thrown on requests when using AddAzureClients

### ISSUE THREAD

**Issue by ghelyar** [Azure/azure-sdk-for-net#21544]
**Describe the bug**
Please provide the description of issue you're seeing.

**Expected behavior**
Requests complete without exceptions

**Actual behavior (include Exception or Stack Trace)**
```
[Informational] Azure-Core: Request [a556ef5f-9aa2-45c6-9ccd-7fe1ab23595b] GET https://xxx.queue.core.windows.net/?comp=list
x-ms-version:2018-11-09
x-ms-client-request-id:a556ef5f-9aa2-45c6-9ccd-7fe1ab23595b
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Storage.Queues/12.6.2,(.NET 5.0.6; Microsoft Windows 10.0.19042)
x-ms-date:Thu, 03 Jun 2021 09:59:26 GMT
Authorization:REDACTED
client assembly: Azure.Storage.Queues
[LogAlways] Azure-Core: ERROR: Exception during EventSource.OnEventWritten: Object reference not set to an instance of an object.
System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.<LogEvent>b__5_0(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.LogEvent(EventWrittenEventArgs eventData)
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.<.ctor>b__4_0(EventWrittenEventArgs e, String s)
   at Azure.Core.Diagnostics.AzureEventSourceListener.OnEventWritten(EventWrittenEventArgs eventData)
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
   --- End of inner exception stack trace ---
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, UInt32* osThreadId, DateTime* timeStamp, Guid* activityID, Guid* childActivityID, Object[] args)
   at System.Diagnostics.Tracing.EventSource.WriteEventVarargs(Int32 eventId, Guid* childActivityID, Object[] args)
   at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, Object[] args)
   at Azure.Core.Diagnostics.AzureCoreEventSource.Request(String requestId, String method, String uri, String headers, String clientAssembly)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.LoggingPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Storage.Queues.QueueRestClient.Service.ListQueuesSegmentAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String prefix, String marker, Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Queues.QueueServiceClient.GetQueuesInternal(String marker, QueueTraits traits, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Queues.Models.GetQueuesAsyncCollection.GetNextPageAsync(String continuationToken, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at ...
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

This fails (logs above):
```csharp
using var listener = AzureEventSourceListener.CreateConsoleLogger();
var services = new ServiceCollection();
services.AddAzureClients(builder =>
{
    builder.AddQueueServiceClient(connectionString);
});
using var provider = services.BuildServiceProvider(true);
var client = provider.GetRequiredService<QueueServiceClient>();
Console.WriteLine($"There are {client.GetQueues().Count()} queues");
```

Adding `builder.ConfigureDefaults(o => o.Diagnostics.IsLoggingEnabled = false);` makes it work for this particular case.

However, it does not make it work everywhere. This still fails (run from LINQPad, so `DefaultAzureCredential` will fail to get a token):
```csharp
using var listener = AzureEventSourceListener.CreateConsoleLogger();
var services = new ServiceCollection();
services.AddAzureClients(builder =>
{
    builder.AddQueueServiceClient(new Uri("https://xxx.queue.core.windows.net/"));
    builder.UseCredential(new DefaultAzureCredential());
    builder.ConfigureDefaults(o =>
    {
        o.Diagnostics.IsDistributedTracingEnabled = false;
        o.Diagnostics.IsLoggingContentEnabled = false;
        o.Diagnostics.IsTelemetryEnabled = false;
        o.Diagnostics.IsLoggingEnabled = false;
    });
});
using var provider = services.BuildServiceProvider(true);
var client = provider.GetRequiredService<QueueServiceClient>();
Console.WriteLine($"There are {client.GetQueues().Count()} queues");
```

Logs:
```
[Informational] Azure-Identity: Azure.Identity.DefaultAcureCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 74762f91-468c-48fc-95de-c9aef8ad876d
[LogAlways] Azure-Identity: ERROR: Exception during EventSource.OnEventWritten: Object reference not set to an instance of an object.
System.Diagnostics.Tracing.EventSourceException: An error occurred when writing to a listener.
 ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.<LogEvent>b__5_0(String name)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.LogEvent(EventWrittenEventArgs eventData)
   at Microsoft.Extensions.Azure.EventSourceLogForwarder.<.ctor>b__4_0(EventWrittenEventArgs e, String s)
   at Azure.Core.Diagnostics.AzureEventSourceListener.OnEventWritten(EventWrittenEventArgs eventData)
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
   --- End of inner exception stack trace ---
   at System.Diagnostics.Tracing.EventSource.DispatchToAllListeners(Int32 eventId, EventWrittenEventArgs eventCallbackArgs)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, UInt32* osThreadId, DateTime* timeStamp, Guid* activityID, Guid* childActivityID, Object[] args)
   at System.Diagnostics.Tracing.EventSource.WriteToAllListeners(Int32 eventId, Guid* activityID, Guid* childActivityID, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEventWithRelatedActivityIdCore(Int32 eventId, Guid* relatedActivityId, Int32 eventDataCount, EventData* data)
   at System.Diagnostics.Tracing.EventSource.WriteEvent(Int32 eventId, String arg1, String arg2, String arg3)
   at Azure.Identity.AzureIdentityEventSource.GetToken(String method, String scopes, String parentRequestId)
   at Azure.Identity.AzureIdentityEventSource.GetToken(String method, TokenRequestContext context)
   at Azure.Identity.CredentialPipeline.StartGetTokenScope(String fullyQualifiedMethod, TokenRequestContext context)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(Boolean isAsync, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequest(HttpMessage message, TokenRequestContext context)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthorizeRequest(HttpMessage message)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Storage.Queues.QueueRestClient.Service.ListQueuesSegmentAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String version, String prefix, String marker, Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Queues.QueueServiceClient.GetQueuesInternal(String marker, QueueTraits traits, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Queues.Models.GetQueuesAsyncCollection.GetNextPageAsync(String continuationToken, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at ...
```

Also note that this works absolutely fine:
```csharp
var client = new QueueServiceClient(connectionString);
Console.WriteLine($"There are {client.GetQueues().Count()} queues");
```

Adding/Removing `using var listener = AzureEventSourceListener.CreateConsoleLogger();` does not make any difference to any of these.

**Environment:**
 - Name and version of the Library package used: Azure.Storage.Queues 12.6.2, Microsoft.Extensions.Azure 1.0.0, Microsoft.Extensions.DependencyInjection 5.0.1
 - Hosting platform or OS and .NET runtime version: Windows 10, .NET 5.0.6
 - IDE and version : LINQPad 6.13.13 x64

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by jsquire** [comment]
@pakrym:  I'm not sure if this is something in the Storage client library, Azure.Core, or the extensions.   Would you mind sharing your thoughts and looping in the storage team if needed?

**Comment by pakrym** [comment]
Thank you, Jesse, this looks like a bug in Microsoft.Extensions.Azure.

**Comment by pakrym** [comment]
@ghelyar are you able to try the https://www.nuget.org/packages/Microsoft.Extensions.Azure/1.1.0-beta.3 version of the package and see if the error still reproduces?

**Comment by ghelyar** [comment]
Seems to be fixed in Microsoft.Extensions.Azure 1.1.0-beta.3 or one of the updated dependencies it brings in.

I didn't realise Microsoft.Extensions.Azure 1.0.0 was so old. Will 1.1.0 be released any time soon? I can't use pre-release packages in production, and the only stable release has quite a severe bug in it, so the whole package is currently unusable for me.

Also, `Azure.Identity` does not respect the `Diagnostics.Is*Enabled = false` flags even on the latest versions of these packages.

**Comment by pakrym** [comment]
>Will 1.1.0 be released any time soon? 

Yes, the plan is this week.

**Comment by pakrym** [comment]
The package is out. https://www.nuget.org/packages/Microsoft.Extensions.Azure/1.1.0
