### ISSUE TITLE
Fetching topics having slashes raises an Argument exception

### ISSUE THREAD

**Issue by arahimee** [Azure/azure-sdk-for-net#21647]
**Describe the bug**
Having a topic endpoint with slashes in the name under a service bus namespace, while fetching it with IServiceBusNamespace.Topics it gives an ArgumentException with message `The specified ID is not a valid Azure resource ID.`

**Expected behavior**
I can fetch all the topics regardless of having slashes in their names.

**Actual behavior (include Exception or Stack Trace)**
at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceId..ctor(String id)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceId.FromString(String id)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.IndependentChildImpl`7.SetParentName(InnerResourceT inner)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.IndependentChildImpl`7.SetInner(InnerResourceT inner)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IndexableRefreshableWrapper`2..ctor(String name, InnerResourceT innerObject)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4..ctor(String name, InnerResourceT innerObject)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5..ctor(String name, InnerResourceT innerObject)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.IndependentChildImpl`7..ctor(String name, InnerResourceT innerObject, ManagerT manager)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.IndependentChildResourceImpl`7..ctor(String name, InnerModelT innerObject, ManagerT manager)
   at Microsoft.Azure.Management.ServiceBus.Fluent.TopicImpl..ctor(String resourceGroupName, String namespaceName, String name, Region region, TopicInner inner, IServiceBusManager manager)
   at Microsoft.Azure.Management.ServiceBus.Fluent.TopicsImpl.WrapModel(TopicInner inner)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<>c__DisplayClass15_0.<<LoadPage>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.<>c__DisplayClass21_0.<<AddCollection>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.AddCollection(IPage`1 currentPage, PagedCollection`2 pagedCollection, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPageWithWrapModelAsync(Func`2 listInnerAsync, Func`3 listInnerNext, Func`3 wrapModelAsync, Boolean loadAllPages, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.PagedCollection`2.LoadPage(Func`2 listInnerAsync, Func`3 listInnerNext, Func`2 wrapModel, Boolean loadAllPages, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ServiceBus.Fluent.ServiceBusChildResourcesImpl`6.ListAsync(Boolean loadAllPages, CancellationToken cancellationToken)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create a topic under an azure service bus namespace with slashes in the name (e.g sample/topic)
2. Then fetch the topics with `IServiceBusNamespace.Topics` and then you get an error

**Environment:**
 - Microsoft.Azure.Management.ServiceBus.Fluent 1.37.1

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by yungezz** [comment]
hi @weidongxu-microsoft could you help on the Fluent issue? thanks

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by weidongxu-microsoft** [comment]
User need to use `~` for `/`. However this still require upgrade the service version to 2017-04-01 or above, which contains massive breaking changes to SDK.

Suggestion is to wait for next generation of .NET SDK https://azure.github.io/azure-sdk/releases/latest/mgmt/dotnet.html

**Comment by weidongxu-microsoft** [comment]
New SDK at https://aka.ms/azsdk/dotnet/mgmt
