### ISSUE TITLE
HttpMockServer.Initialize results in null reference exception

### ISSUE THREAD

**Issue by rohmano** [Azure/azure-sdk-for-net#2180]
public static void Initialize(string callerIdentity, string testIdentity)
results in "Object reference not set to an instance of an object." at 
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity)

FileSystemUtilsObject is not initialized before accessing.

**Comment by shahabhijeet** [comment]
@rohmano can you give us more information.
Could you give us the version of the HttpRecorder that you are using.
Would be great if you can provide us a code snippet that results in NullRef exeception

**Comment by shahabhijeet** [comment]
@rohmano please reopen if you still see the issue.
