### ISSUE TITLE
Unable to deploy using ARM template by passing the content of the json file.

### ISSUE THREAD

**Issue by rshirani** [Azure/azure-sdk-for-net#2190]
Hi folks,

I am trying to do a deployment but rather than passing the TemplateLink and ParametersLink, I'd rather passing the content. When I do so however I get an error as follows. What I do right now is simply loading the content of my template file

```
    public static Object GetTemplate() {
        return File.ReadAllText( @"E:\OfficialTemp\tmplt.json" ); }

    public static Object GetParameters(){
        return File.ReadAllText( @"E:\OfficialTemp\params.json"); }
```

and then in my main:

```
        deployment.Properties = new DeploymentProperties
        {
            Mode = DeploymentMode.Incremental,
            Template = GetTemplate(),
            Parameters = GetParameters(),
        };
         var resourceManagementClient = new ResourceManagementClient( credential )
        { SubscriptionId = subscriptionId };

        return await resourceManagementClient.Deployments.CreateOrUpdateAsync(
          groupName,
          deploymentName,
          deployment );
```

I'd like to mention that my tmplt.json and params.json are exactly the file that I used to in my deployment using the URI so I do not think that is an issue. (I get the error even when I use the values stated for template and parameters files in https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-csharp-template/)      

Error: System.AggregateException: One or more errors occurred. ---> Microsoft.Rest.Azure.CloudException: The request content was invalid and could not be deserialized: 'Error converting value "

---

}" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Templates.Schema.Template'. Path 'properties.template', line 3, position 23171.'.
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication1.Program.<CreateTemplateDeploymentAsync>d__3.MoveNext() in

**Comment by devigned** [comment]
Check out this sample: https://azure.microsoft.com/en-us/documentation/samples/resource-manager-dotnet-template-deployment/.

I believe you need something like below:

```csharp
var templateParams = JObject.Parse(File.ReadAllText( @"E:\OfficialTemp\params.json")); }

var deployParams = new Deployment{
    Properties = new DeploymentProperties{
        Template = JObject.Parse(File.ReadAllText(templateFileLocation)),
        Parameters = templateParams,
        Mode = DeploymentMode.Incremental
    }
};
```

**Comment by rshirani** [comment]
Thanks @devigned , it seems a bit tricky as we can pass string for template but not the parameter. I modified to this and now passes the json issue. Thanks for the link. That said I get a new exception (Long running operation failed with status 'Failed'). Should I just retry or you have any other recommendations?

public static async Task<DeploymentExtended> CreateTemplateDeploymentAsync(
   TokenCredentials credential, 
   string groupName, 
   string deploymentName, 
   string subscriptionId)
   {
     Console.WriteLine("Creating the template deployment...");
     var templateParams = new Dictionary<string, Dictionary<string, object>>{
       { "adminPassword", new Dictionary<string, object>{{"value","Azure1234567"}}},
       { "adminUserName", new Dictionary<string, object>{{"value", "davidmu" } }}
     };

     var deployment = new Deployment();
     deployment.Properties = new DeploymentProperties
     {
       Mode = DeploymentMode.Incremental,
       Template = JObject.Parse(File.ReadAllText("Templates\\CreateVMTemplate2.json")),
       Parameters = templateParams
     };
     var resourceManagementClient = new ResourceManagementClient(credential) { SubscriptionId = subscriptionId };
     return await resourceManagementClient.Deployments.CreateOrUpdateAsync(groupName, deploymentName, deployment);
    }

**Comment by rshirani** [comment]
Here is the full exception:

Creating the resource group...
Succeeded
Creating the template deployment...
Error: System.AggregateException: One or more errors occurred. ---> Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Failed'.
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication1.Program.<CreateTemplateDeploymentAsync>d__3.MoveNext() in C:\Users\rostams\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 151
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at ConsoleApplication1.Program.Main(String[] args) in C:\Users\rostams\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 49
---> (Inner Exception #0) Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Failed'.
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPutOrPatchOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ConsoleApplication1.Program.<CreateTemplateDeploymentAsync>d__3.MoveNext() in C:\Users\rostams\documents\visual studio 2015\Projects\ConsoleApplication1\ConsoleApplication1\Program.cs:line 151<---

**Comment by rshirani** [comment]
Created a new issue to track this: https://github.com/Azure/azure-sdk-for-net/issues/2194.

**Comment by devigned** [comment]
I think this code will work better with the http://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json format.

```csharp
// NOTE: If you would like to read the template parameters from a parameters.json file 
//        (like: https://github.com/Azure/azure-quickstart-templates/blob/master/101-vm-simple-linux/azuredeploy.parameters.json),
//        then you can use the following code to read the JSON, extract the parameters and then convert them to the required structure.

var templateString = File.ReadAllText(Path.GetFullPath("template_params.json"));
var templateParamsObj = JObject.Parse(templateString)["parameters"];
templateParams = templateParamsObj.ToObject<Dictionary<string, Dictionary<string, object>>>();
Write("{0}", JsonConvert.SerializeObject(templateParams));
```

**Comment by devigned** [comment]
I agree that it's a bit tricky. We need to have better typing on this.

@markcowl, @sphibbs, @kirthik, @vivsriaus and @tbombach could we improve: https://github.com/Azure/azure-rest-api-specs/blob/master/arm-resources/resources/2016-02-01/swagger/resources.json#L1778-L1789 ? It would be great to have a stronger typed representation of Template and Parameter on DeploymentPropertiesExtended to ensure we are push toward the path of success.

Perhaps this would call for an externally defined type which provides some intelligence to construction, validation, serialization and deserialization.

**Comment by adrianhall** [comment]
This is an old issue.  Is it still relevant?
