### ISSUE TITLE
[Flaky Test] Azure.Search.Documents.Tests.ManualRetryDelayTests.AddsMoreDelay

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#22107]
```
2021-06-23T18:21:58.7823421Z   Failed AddsMoreDelay [1 s]
2021-06-23T18:21:58.7841181Z   Error Message:
2021-06-23T18:21:58.7867497Z      Expected a delay between 148ms and 500ms, not 817
2021-06-23T18:21:58.7881297Z   Expected: True
2021-06-23T18:21:58.7882537Z   But was:  False
2021-06-23T18:21:58.7883342Z 
2021-06-23T18:21:58.7884357Z   Stack Trace:
2021-06-23T18:21:58.7885798Z      at Azure.Search.Documents.Tests.ManualRetryDelayTests.AddsMoreDelay() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\ManualRetryDelayTests.cs:line 52
2021-06-23T18:21:58.7887712Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
2021-06-23T18:21:58.7889174Z    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
2021-06-23T18:21:58.7891912Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2021-06-23T18:21:58.7893145Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
2021-06-23T18:21:58.7894311Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2021-06-23T18:21:58.7895111Z    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
2021-06-23T18:21:58.7895807Z    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
```

**Comment by pakrym** [comment]
Dup: https://github.com/Azure/azure-sdk-for-net/issues/18570

**Comment by JoshLove-msft** [comment]
Not observed for a while - closing.
