### ISSUE TITLE
[BUG] can't peek/cancel scheduled messages from queue in send disabled state

### ISSUE THREAD

**Issue by JonasSamuelsson** [Azure/azure-sdk-for-net#22454]
I have a service bus queue that's in active use that I want to recreate to disable duplicate detection.
My plan is to stop the queue from accepting new messages, drain it and store all messages to blob storage, recreate, and then write the messages back to the queue.

I'm using [Azure.Messaging.ServiceBus v7.2.0](https://www.nuget.org/packages/Azure.Messaging.ServiceBus/7.2.0).
Reading active messages using `receiver.ReceiveMessageAsync(...)`/`receiver.CompleteMessageAsync(receivedMessage)` works fine but `receiver.PeekMessageAsync(...)` throws a `Azure.Messaging.ServiceBus.ServiceBusException` saying that `Messaging entity '{...}' is currently disabled for Send operations`.
This is not what I expected, can you confirm if my assumptions are correct or not?

From what can see the only way to then cancel the peeked scheduled message is by using `sender.CancelScheduledMessageAsync(peekedMessage.SequenceNumber)`, is this correct?
Since I have to use the sender for this I'm kind of worried that this won't work event if I'm able to use peek to access scheduled messages.
Is this the right way to do what I want to do or is there a better way?

**Stack trace:**
```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<PeekMessagesAsync>d__55.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<PeekMessagesInternalAsync>d__44.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<PeekMessageAsync>d__42.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at ServiceBusMessagingEntityRebuilder.Program.<Main>d__0.MoveNext() in C:\dev\temp\ServiceBusMessagingEntityRebuilder\ServiceBusMessagingEntityRebuilder\Program.cs:line 52
```

**Code:**
```csharp
var connectionString = "...";
var queueName = "test";
var adminClient = new ServiceBusAdministrationClient(connectionString);
var msgClient = new ServiceBusClient(connectionString);
var sender = msgClient.CreateSender(queueName);
var receiver = msgClient.CreateReceiver(queueName);

if (await adminClient.QueueExistsAsync(queueName))
{
   await adminClient.DeleteQueueAsync(queueName);
}

await adminClient.CreateQueueAsync(queueName);

await sender.SendMessagesAsync(new[]
{
   new ServiceBusMessage
   {
      MessageId = "1"
   },
   new ServiceBusMessage
   {
      MessageId = "2",
      ScheduledEnqueueTime = DateTimeOffset.UtcNow.AddHours(1)
   }
});

var queueProperties = await adminClient.GetQueueAsync(queueName);
queueProperties.Value.Status = EntityStatus.SendDisabled;
await adminClient.UpdateQueueAsync(queueProperties);

var receivedMessage = await receiver.ReceiveMessageAsync(TimeSpan.FromSeconds(1));
await receiver.CompleteMessageAsync(receivedMessage);

var peekedMessage = await receiver.PeekMessageAsync(0);
await sender.CancelScheduledMessageAsync(peekedMessage.SequenceNumber);
```

**Environment:**
Azure.Messaging.ServiceBus v7.2.0
```
.NET SDK (reflecting any global.json):
 Version:   5.0.301
 Commit:    ef17233f86

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.301\

Host (useful for support):
  Version: 5.0.7
  Commit:  556582d964

.NET SDKs installed:
  5.0.301 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.16 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

**Comment by jsquire** [comment]
//fyi: @JoshLove-msft

**Comment by jsquire** [comment]
The error message and stack trace indicate that the client is reacting to an error returned by the Service Bus broker.  @shankarsama, would you please be so kind as to offer your thoughts on the service behavior and expectations for this scenario?

**Comment by EldertGrootenboer** [comment]
We have opened an investigation task for this in our backlog, and will update this issue when we have more information.

**Comment by yvgopal** [comment]
This is a bug in Azure Service Bus service. Fix is already checked in. It will be rolled out to all regions by the end of this month.
