### ISSUE TITLE
[BUG] Microsoft.Azure.ApplicationInsights.Query 

### ISSUE THREAD

**Issue by karimdabbagh** [Azure/azure-sdk-for-net#22610]
**Describe the bug**
Using ApplicationInsightsDataClient to retrieve the metrics from ApplicationInsights. When trying to retrieve a metric for a timespan that the metric has no value:
If I use 'count' or 'sum' as the aggregation it works fine and returns 0 as the metric value. However, when I use 'avg' or 'min' or 'max' it throws the following exception: "Exception has been thrown by the target of an invocation."

The http call to ApplicationInsight is successful and returns the following:
```
HTTP/1.1 200
content-length: 129
content-type: application/json; charset=utf-8

{
  "value": {
    "start": "2021-07-09T23:45:18.672Z",
    "end": "2021-07-12T23:45:18.672Z",
    "customMetrics/TestMetricAppInsight": {
      "avg": null
    }
  }
}
```
However, the SDK is not able to handle the above result.

I looked at the SDK code and it looks like the following place in the code (BaseMetricInfo.cs) causing this issue:
```
[OnDeserialized]
        internal void InitMetricFields(StreamingContext context)
        {
            var additionalProperties = GetAdditionalProperties();

            if (additionalProperties != null)
            {
                foreach (var additionalProp in additionalProperties)
                {
                    if (additionalProp.Value is object)
                    {
                        var dict = additionalProp.Value as JObject;
                        if (dict == null) continue;

                        MetricId = additionalProp.Key;

                        foreach (var prop in dict.Properties())
                        {
                            MetricValues.Add(prop.Name, prop.Value.Value<float>());
                        }
                    }
                }
            }
        }
```

As can be seen, it does not check whether `prop.Value` is null or not and thats whats causing it. Looks like the SDK doesnt account for `null `value coming from the service. The reason that it works for 'count' and 'sum' is that the service doesnt return `null `in those cases. If the metric is not having any values for a certain timespan the service returns 0 for both 'count' and 'sum' aggregation (and not `null`).

So, a solution could be to change the following line
`MetricValues.Add(prop.Name, prop.Value.Value<float>());`
to
`MetricValues.Add(prop.Name, prop.Value.Value<float?>() ?? 0);`

**Expected behavior**
I am expecting for avg, min or max to also get 0 for the metric value if the metric doesnt have any value in that timespan.

**Actual behavior (include Exception or Stack Trace)**
When the underlying service returns null in the response The SDK will end up with the following exceptions:
   ```
at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture) in /_/src/System.Private.CoreLib/src/System/Reflection/RuntimeMethodInfo.cs:line 469
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters) in /_/src/System.Private.CoreLib/shared/System/Reflection/MethodBase.cs:line 54
   at Newtonsoft.Json.Serialization.JsonContract.<>c__DisplayClass57_0.<CreateSerializationCallback>b__0(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonContract.InvokeOnDeserialized(Object o, StreamingContext context)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserialized(JsonReader reader, JsonContract contract, Object value)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Deserialize(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.ApplicationInsights.Query.Metrics.<GetWithHttpMessagesAsync>d__10.MoveNext() in F:\src\azure-sdk-for-net\sdk\applicationinsights\Microsoft.Azure.ApplicationInsights.Query\src\Generated\Metrics.cs:line 309
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 563
   at Microsoft.Azure.ApplicationInsights.Query.MetricsExtensions.<GetAsync>d__9.MoveNext() in F:\src\azure-sdk-for-net\sdk\applicationinsights\Microsoft.Azure.ApplicationInsights.Query\src\Generated\MetricsExtensions.cs:line 186
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw() in /_/src/System.Private.CoreLib/shared/System/Runtime/ExceptionServices/ExceptionDispatchInfo.cs:line 63
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 180
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 151
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult() in /_/src/System.Private.CoreLib/shared/System/Runtime/CompilerServices/TaskAwaiter.cs:line 369
   at AppInsightsSDKDemo.Program.<Main>d__0.MoveNext() in F:\src\test\appInsight\Program.cs:line 64
```

**To Reproduce**
```
namespace AppInsightsSDKDemo
{
    using System;
    using Microsoft.Azure.ApplicationInsights.Query;
    using Microsoft.Rest.Azure.Authentication;
    class Program
    {
        static void Main(string[] args)
        {
            var appId = "{appId}";
            var clientId = "{aadClientAppId}";
            var clientSecret = "{aadAppkey}";

            var domain = "{aadTenantId}";
            var authEndpoint = "https://login.microsoftonline.com";
            var tokenAudience = "https://api.applicationinsights.io/";

            var adSettings = new ActiveDirectoryServiceSettings
            {
                AuthenticationEndpoint = new Uri(authEndpoint),
                TokenAudience = new Uri(tokenAudience),
                ValidateAuthority = true
            };
            
            // Authenticate with client secret (app key)
            var creds = ApplicationTokenProvider.LoginSilentAsync(domain, clientId, clientSecret, adSettings).GetAwaiter().GetResult();

            // Instantiate a client with credentials
            var client = new ApplicationInsightsDataClient(creds);

            // Execute a query with Application Insights application Id
            var results = client.Query.Execute(appId, "union * | limit 5");

            for (var i = 0; i < results.Tables[0].Rows.Count; i++) {
                // Do something with query results
                Console.WriteLine(String.Join("    ", results.Tables[0].Rows[i]));
            }
        }
    }
}
```

Using the above code (as well as valid AppInsights credentials) try to get a metric value for a metric that doesnt exist for a certain timespan.

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.ApplicationInsights.Query 1.0 
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):  Windows 10 .NET Core 3.1
 - IDE and version : 16.10.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by scottaddie** [comment]
Support for the `Microsoft.Azure.ApplicationInsights.Query` package ended on March 31st. It has been deprecated in favor of [Azure.Monitor.Query](https://www.nuget.org/packages/Azure.Monitor.Query). We recommend migrating to continue receiving support. To assist in that migration, see [this migration guide](https://aka.ms/azsdk/net/migrate/ai-monitor-query).
