### ISSUE TITLE
[BUG] Azure.Identity.AuthenticationFailedException : AzurePowerShellCredential authentication failed: String '14-7-2021 06:36:10 +00:00' was not recognized as a valid DateTime

### ISSUE THREAD

**Issue by dcanamares** [Azure/azure-sdk-for-net#22638]
**Describe the bug**
I'm running some integration tests on Azure Pipelines, it was working fine until 13 of July (code was released at the beginning of July). These tests connect to an azure subscription to get some values from an Azure KeyVault. I don't send any datetime and I didn't see any way to send a date or a specific format. The issue happens running the tests in the  pipeline but it doesn't happen running the tests on a local machine.

I ran a Get-Culture command and the value is:
LCID             Name             DisplayName                                                                          
                                                                      
1043             nl-NL            Dutch (Netherlands)  

**Expected behavior**
Connect to key vault and retrieve the secrets.

**Actual behavior (include Exception or Stack Trace)**
From day 1 to day 12 of a month pipeline can connect to Azure keyvault and gets the secrets stored, from day 13 to 31 of a month pipelines throws and exception because the format of the date is dd-MM-yyyy.

Error Message:
   Azure.Identity.AuthenticationFailedException : AzurePowerShellCredential authentication failed: String '14-7-2021 06:36:10 +00:00' was not recognized as a valid DateTime.
---- System.FormatException : String '14-7-2021 06:36:10 +00:00' was not recognized as a valid DateTime.
  Stack Trace:
     at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.AzurePowerShellCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.AzurePowerShellCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthorizeRequestOnChallengeAsyncInternal(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.GetPageAsync[T](Uri firstPageUri, String nextLink, Func`1 itemFactory, String operationName, CancellationToken cancellationToken)
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()

**To Reproduce**
Configuration :
```
            var configBuilder = new ConfigurationBuilder()
                .AddJsonFile("testsettings.json", true)
                .AddEnvironmentVariables();

            var builtConfig = configBuilder.Build();

            Configuration = configBuilder
                .AddAzureKeyVault(new Uri(builtConfig["key_vault_azure_uri"]), new DefaultAzureCredential())
                .Build();
```
To get a secret:
` var secret= Configuration["secret_key"]`

**Environment:**
 - The project is on Net Core 2.2
 - Azure.Identity 1.4.0, Azure.Security.KeyVault.Secrets  4.2.0, 
 - Pipelines run in a hosted agent with Windows Server 2019
 - Visual Studio PRO 2019 16.8.1.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by brwilkinson** [comment]
@christothes this update was merged to identity 1.4.1 is that correct?

I seem to have some further reports of this when using:

```powershell
get-culture

LCID             Name             DisplayName
----             ----             -----------
8192             en-DK            English (Denmark)
```

```log
Unhandled exception: Azure.Identity.AuthenticationFailedException: The ChainedTokenCredential failed due to an unhandled exception: AzurePowerShellCredential authentication failed: String '13/10/2021 06.54.13 +00:00' was not recognized as a valid DateTime.
 ---> Azure.Identity.AuthenticationFailedException: AzurePowerShellCredential authentication failed: String '13/10/2021 06.54.13 +00:00' was not recognized as a valid DateTime.
```

**Comment by JohnGalt1717** [comment]
Pretty sure  that this fix is what broke culture invariant mode in .NET apps.  Please address or revert as you broke a HUGE portion of  .net apps that use docker as a result of this.

**Comment by JohnGalt1717** [comment]
Because the default for all .net containers is invariant culture only, and if you don't do this, you increase the size of your containers by 30-40%. (aside from breaking it)  And of course you then have to install the dependencies in your container which are intentionally left out by the .net containers for this very reason.

**Comment by christothes** [comment]
Hi @JohnGalt1717 - 
The storage library you are referencing in the referenced issue doesn't appear to be the latest version (it mentions Microsoft.Azure.Storage.* rather than Azure.Storage.*). The Azure.Identity package is not a direct dependency for either package nor does the stack in that issue involve Azure.Identity.

However, You'll find references to Culture in many places besides this specific fix https://grep.app/search?q=CultureInfo.CurrentCulture&filter[repo][0]=Azure/azure-sdk-for-net&filter[path][0]=sdk/ so reverting this won't be of much help if your environment requires strict invariant culture.
