### ISSUE TITLE
[BUG] Service Bus: Cannot bind parameter 'collector' to type IAsyncCollector`1 in Azure Functions v3

### ISSUE THREAD

**Issue by thomasvdb** [Azure/azure-sdk-for-net#22790]
**Describe the bug**
We are upgrading from the Microsoft.Azure.ServiceBus NuGet package to Azure.Messaging.ServiceBus in our projects.
For our Azure Functions project (v3) we upgraded the Microsoft.Azure.WebJobs.Extensions.ServiceBus NuGet package to 5.0.0-beta.5

We updated the Function with the new classes:

```csharp
public async Task Run(
[ServiceBusTrigger("...", "...", Connection = "...")] ServiceBusReceivedMessage message, 
[ServiceBus("...", Connection = "...")] IAsyncCollector<ServiceBusMessage> collector)
{
    [...]
}
```

When starting the Function project however I receive the following error:
`Microsoft.Azure.WebJobs.Host: Cannot bind parameter 'collector' to type IAsyncCollector``1. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).`

**Expected behavior**
According to [the documentation](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre#sending-multiple-messages) this should work with the setup given above.

**Actual behavior (include Exception or Stack Trace)**
```text
Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexingException: Error indexing method 'MyFunction'
 ---> System.InvalidOperationException: Cannot bind parameter 'collector' to type IAsyncCollector`1. Make sure the parameter Type is supported by the binding. If you're using binding extensions (e.g. Azure Storage, ServiceBus, Timers, etc.) make sure you've called the registration method for the extension(s) in your startup code (e.g. builder.AddAzureStorage(), builder.AddServiceBus(), builder.AddTimers(), etc.).
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsyncCore(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 259
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 149
   --- End of inner exception stack trace ---
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexMethodAsync(MethodInfo method, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 157
   at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.IndexTypeAsync(Type type, IFunctionIndexCollector index, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 85
```

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.0.0-beta.5 and Azure.Messaging.ServiceBus 7.2.1
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
```text
 .NET SDK (reflecting any global.json):
 Version:   5.0.101
 Commit:    d05174dc5a

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  11.0
 OS Platform: Darwin
 RID:         osx.11.0-x64
 Base Path:   /usr/local/share/dotnet/sdk/5.0.101/

Host (useful for support):
  Version: 5.0.1
  Commit:  b02e13abab
```
 - IDE and version : JetBrains Rider 2021.1.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @thomasvdb,
I haven't been able to reproduce this issue. Could you include your csproj, function.json, and host.json? Also, if you remove the ServiceBus attribute do you get the same error (just trying to pinpoint whether the issue is with that attribute in particular or something else)?

**Comment by thomasvdb** [comment]
Hi @JoshLove-msft,

**host.json**
```
{
  "version": "2.0",
  "logging": {
    "logLevel": {
      "default":  "Information"
    },
    "extensions": {
      "queues": {
        "batchSize": 5,
        "newBatchThreshold": 0
      }
    }
  }
}
```

**function.json**
No function.json is included in the project

**csproj**

```
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <ProjectGuid>{EB1CF94B-F428-4FDA-88EE-ED2FB5374950}</ProjectGuid>
    <TargetFramework>netcoreapp3.1</TargetFramework>
    <AzureFunctionsVersion>V3</AzureFunctionsVersion>
    <AssemblyVersion>9.9.9.9</AssemblyVersion>
    <Authors>...</Authors>
    <Company>...</Company>
    <Product>Private Accounting Functions</Product>
    <Version>1.0.0</Version>
    <LangVersion>9</LangVersion>
    <UserSecretsId>...</UserSecretsId>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="10.0.0" />
    <PackageReference Include="AutoMapper.Extensions.Microsoft.DependencyInjection" Version="8.0.1" />
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="MediatR" Version="9.0.0" />
    <PackageReference Include="MediatR.Extensions.Microsoft.DependencyInjection" Version="9.0.0" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.SqlDatabase.ElasticScale.Client" Version="2.3.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="5.0.0-beta.5" />
    <PackageReference Include="Microsoft.Extensions.Azure" Version="1.1.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="3.1.8" />
    <PackageReference Include="Microsoft.Extensions.Configuration.UserSecrets" Version="3.1.0" />
    <PackageReference Include="Microsoft.Extensions.Options" Version="3.1.9" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="3.0.9" />
    <PackageReference Include="Serilog" Version="2.10.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="3.0.1" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.ApplicationInsights" Version="3.1.0" />
    <PackageReference Include="Serilog.Sinks.Console" Version="3.1.1" />
    <PackageReference Include="Serilog.Sinks.File" Version="3.1.1" />
  </ItemGroup>
  <ItemGroup>
    <None Update="host.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.development.json">
      <DependentUpon>appsettings.json</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="appsettings.test.json">
      <DependentUpon>appsettings.json</DependentUpon>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="local.settings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="[Removed reference for obvious reasons]" />
    <ProjectReference Include="[Removed reference for obvious reasons]" />
    <ProjectReference Include="[Removed reference for obvious reasons]j" />
    <ProjectReference Include="[Removed reference for obvious reasons]" />
    <ProjectReference Include="[Removed reference for obvious reasons]" />
  </ItemGroup>
</Project>
```

I must say that I can't reproduce it in an Azure Function from scratch so I will try to eliminate some parts of the existing Azure Function so see were the issue could be.

**Comment by thomasvdb** [comment]
@JoshLove-msft Sorry to bother you about this issue. It seems a "Clean and rebuild" solved the issue 🤦 
Issue still persisted with everything stripped out which did me think about the "Clean" option.

One question though, do you have any idea when this package will go out of beta?
