### ISSUE TITLE
[AppConfiguration] test failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#22828]
AppConfiguration nightly test runs are failing with:

> Error Message
> Azure.RequestFailedException : Service request failed.
> Status: 412 (Precondition Failed)
> 
> Headers:
> Server: openresty/1.17.8.2
> Date: Thu, 10 Jun 2021 10:25:11 GMT
> Connection: keep-alive
> retry-after-ms: REDACTED
> x-ms-request-id: ae9497b6-2f19-4d64-8c70-8d42e3a38142
> x-ms-client-request-id: 1bebbc98-4a1f-4788-aadf-f32085a1b565
> x-ms-correlation-request-id: ae9497b6-2f19-4d64-8c70-8d42e3a38142
> Access-Control-Allow-Origin: *
> Access-Control-Allow-Credentials: true
> Access-Control-Expose-Headers: REDACTED
> Strict-Transport-Security: max-age=15724800; includeSubDomains
> Content-Length: 0
> 
> Stack Trace
> at Azure.Data.AppConfiguration.ConfigurationClient.GetConfigurationSetting(String key, String label, Nullable`1 acceptDateTime, MatchConditions conditions, CancellationToken cancellationToken) in /_/sdk/appconfiguration/Azure.Data.AppConfiguration/src/ConfigurationClient.cs:line 620
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /Users/runner/work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 165
>    at Azure.Data.AppConfiguration.Tests.ConfigurationLiveTests.GetSettingWithIfMatch_Matches() in /Users/runner/work/1/s/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationLiveTests.cs:line 678
>    at Azure.Data.AppConfiguration.Tests.ConfigurationLiveTests.GetSettingWithIfMatch_Matches() in /Users/runner/work/1/s/sdk/appconfiguration/Azure.Data.AppConfiguration/tests/ConfigurationLiveTests.cs:line 688
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=941398&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=993964&view=results
- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1011358&view=results

**Comment by jsquire** [comment]
Given the age of this issue, I'm going to close it as stale.  If tests continue to fail, please file a new issue.
