### ISSUE TITLE
[Search] AddsDelay test failing in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#23038]
Search nightly test runs are failing with:

> Error message
> Expected a delay between 70ms and 500ms, not 1236
> Expected: True
> But was:  False
> 
> 
> Stack trace
>    at Azure.Search.Documents.Tests.ManualRetryDelayTests.AddsDelay() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/ManualRetryDelayTests.cs:line 29
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
>    at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
> 

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1023087&view=results

@jsquire for notification.

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1248436&view=ms.vss-test-web.build-test-results-tab&runId=26776574&resultId=116972&paneView=debug

```
AddsDelay

Result Details
Failed 39m ago on 84971604c000000
Duration0:00:00.780
Ownernot available
Date started12/14/2021, 10:42:00 AM
Date completed12/14/2021, 10:42:01 AM
Failing since39m ago
Failing since build20211214.7

Debug

Work items

Attachments

History

Attachments*

Error message
Expected a delay between 70ms and 500ms, not 578
Expected: True
But was:  False


Stack trace
   at Azure.Search.Documents.Tests.ManualRetryDelayTests.<AddsDelay>d__0.MoveNext() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\ManualRetryDelayTests.cs:line 29
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
```
