### ISSUE TITLE
[Eventhub] test failing in nightly runs

### ISSUE THREAD

**Issue by Tianyun-G** [Azure/azure-sdk-for-net#23045]
Eventhub nightly test runs are failing with:

> Error message
> Expected: some item equal to "Microsoft.Azure.WebJobs.EventHubs.EventHubListener.EventProcessor"
> But was:  < "Host.Startup", "Azure.Messaging.EventHubs", "Azure.Messaging.EventHubs", "Azure.Core", "Azure.Core", "Azure.Messaging.EventHubs", "Azure.Messaging.EventHubs", "Azure.Messaging.EventHubs", "Azure.Messaging.EventHubs", "Azure.Messaging.EventHubs"... >
> 
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.EndToEndTests.EventHubEndToEndTests.EventHub_PocoBinding() in /mnt/vss/_work/1/s/sdk/eventhub/Microsoft.Azure.WebJobs.Extensions.EventHubs/tests/EventHubEndToEndTests.cs:line 62
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=981586&view=results

**Comment by jsquire** [comment]
Hi @Tianyun-G: and @v-xuto:  Thank you for filing this, but there is no need to monitor Event Hubs and we'd appreciate if you did not file issues for this service going forward.  This version of the library is not owned by our team, and we're actively monitoring runs for those versions that are.

//cc: @maririos

**Comment by jsquire** [comment]
Closing this as a duplicate of several internally tracked test issues that we've opened with the team that owns `Microsoft.Azure.EventHubs`.
