### ISSUE TITLE
[BUG] ManagedIdentityCredential authentication failed. "No connection could be made"

### ISSUE THREAD

**Issue by tyh77** [Azure/azure-sdk-for-net#23256]
**Describe the bug**
Exception encountered:
> Azure.Identity.AuthenticationFailedException: 'ManagedIdentityCredential authentication failed: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342))'

**Expected behavior**
Managed Identity Credential SHOULD fail BUT fall back to Visual Studio Credential for local development purposes.

**Actual behavior (include Exception or Stack Trace)**
Managed Identity Credential fails but DOES NOT fall back to Visual Studio Credential because a `AuthenticationFailedException` is thrown, instead of `CredentialUnavailableException` - which I believe should enable the DefaultAzureCredential to skip ManagedIdentityCredential.

**To Reproduce**
Attempting to obtain Key Vault Secret by authenticating with DefaultAzureCredential but to no avail:
```csharp
_keyVaultSecretClient = new SecretClient(new Uri(endpoint), new DefaultAzureCredential(), secretClientOptions);
```

Setting ManagedIdentity ClientId manually as `null` doesn't do anything to fix the issue either. I suspect that DefaultAzureCredential is not skipping ManagedIdentityCredential provider because it's sensing a partial credential that is being provided. **But I'm not sure why this is happening**

**Environment:**
 - Packages
```
[net5.0]: 
Top-level Package                              Requested   Resolved
Azure.Identity                               1.4.1       1.4.1
Azure.Security.KeyVault.Certificates         4.2.0       4.2.0
Azure.Security.KeyVault.Secrets              4.2.0       4.2.0
Microsoft.AspNetCore.OData                   8.0.1       8.0.1
Microsoft.Data.SqlClient                     3.0.0       3.0.0
Microsoft.EntityFrameworkCore.Design         5.0.8       5.0.8
Microsoft.EntityFrameworkCore.SqlServer      5.0.8       5.0.8
```
 - Hosting platform or OS and .NET runtime version:
```
.NET SDK (reflecting any global.json):
 Version:   5.0.400
 Commit:    d61950f9bf

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\5.0.400\

Host (useful for support):
  Version: 5.0.9
```
 - IDE and version : **VS19 v16.11.0**

**Comment by tyh77** [comment]
### Full Stack Trace Below:
```
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.ManagedIdentityCredential.<GetTokenImplAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Identity.ManagedIdentityCredential.<GetTokenAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueFromCredentialAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<AuthenticateAndAuthorizeRequestAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.<AuthorizeRequestOnChallengeAsyncInternal>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.RedirectPolicy.<ProcessAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.Pipeline.HttpPipeline.<SendRequestAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__29.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__21`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.Security.KeyVault.Secrets.SecretClient.<GetSecretAsync>d__8.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
```

**Comment by tyh77** [comment]
For now, the only workaround I have come up with is to use preprocessor directives to manually exclude MI when debugging locally. But I feel that this defeats the purpose of using DefaultAzureCredential in the first place.

```csharp
defaultAzureCredentialOptions.ExcludeManagedIdentityCredential = true;
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @yh77 - 
Would you mind providing the logging output after reproducing this with [logging enabled](https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/core/Azure.Core/samples/Diagnostics.md)? That should provide some more context about how DefaultAzureCredential selected the credential.

**Comment by tyh77** [comment]
@christothes I redacted the Key Vault URI for security, otherwise the rest is verbatim from the console log
```
[Informational] Azure-Core: Request [d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95] GET https://<VAULT-URI>/secrets/SqlServer-ConnectionString/?api-version=7.2
Accept:application/json
x-ms-client-request-id:d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Secrets/4.2.0,(.NET 5.0.9; Microsoft Windows 10.0.19043)
Content-Type:application/json
client assembly: Azure.Security.KeyVault.Secrets
[Warning] Azure-Core: Error response [d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95] 401 Unauthorized (00.4s)
Cache-Control:no-cache
Pragma:no-cache
WWW-Authenticate:REDACTED
x-ms-keyvault-region:westus
x-ms-client-request-id:d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95
x-ms-request-id:51fc44a9-7e00-4a0e-955f-f2242af2b23e
x-ms-keyvault-service-version:1.9.48.0
x-ms-keyvault-network-info:conn_type=Ipv4;addr=67.183.153.138;act_addr_fam=InterNetwork;
X-Powered-By:REDACTED
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Date:Wed, 11 Aug 2021 22:15:53 GMT
Content-Length:97
Content-Type:application/json; charset=utf-8
Expires:-1

[Informational] Azure-Identity: DefaultAzureCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95
[Informational] Azure-Identity: EnvironmentCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95
[Informational] Azure-Identity: EnvironmentCredential.GetToken was unable to retrieve an access token. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95 Exception: Azure.Identity.CredentialUnavailableException (0x80131500): EnvironmentCredential authentication unavailable. Environment variables are not fully configured.
[Informational] Azure-Identity: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] GET http://localhost:50342/?api-version=REDACTED&resource=REDACTED
secret:REDACTED
x-ms-client-request-id:76165a70-7470-4f27-802b-ee69b50a1664
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.1,(.NET 5.0.9; Microsoft Windows 10.0.19043)
client assembly: Azure.Identity
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] exception Azure.RequestFailedException: No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] retry number 1 took 04.1s
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] GET http://localhost:50342/?api-version=REDACTED&resource=REDACTED
secret:REDACTED
x-ms-client-request-id:76165a70-7470-4f27-802b-ee69b50a1664
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.1,(.NET 5.0.9; Microsoft Windows 10.0.19043)
traceparent:00-f04f49734f75294db8d2cc6ef0bf6056-653724b72d74de40-00
client assembly: Azure.Identity
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] exception Azure.RequestFailedException: No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] retry number 2 took 04.0s
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] GET http://localhost:50342/?api-version=REDACTED&resource=REDACTED
secret:REDACTED
x-ms-client-request-id:76165a70-7470-4f27-802b-ee69b50a1664
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.1,(.NET 5.0.9; Microsoft Windows 10.0.19043)
traceparent:00-f04f49734f75294db8d2cc6ef0bf6056-653724b72d74de40-00
client assembly: Azure.Identity
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] exception Azure.RequestFailedException: No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] retry number 3 took 04.0s
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] GET http://localhost:50342/?api-version=REDACTED&resource=REDACTED
secret:REDACTED
x-ms-client-request-id:76165a70-7470-4f27-802b-ee69b50a1664
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.4.1,(.NET 5.0.9; Microsoft Windows 10.0.19043)
traceparent:00-f04f49734f75294db8d2cc6ef0bf6056-653724b72d74de40-00
client assembly: Azure.Identity
[Informational] Azure-Core: Request [76165a70-7470-4f27-802b-ee69b50a1664] exception Azure.RequestFailedException: No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|283_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.DefaultConnectAsync(SocketsHttpConnectionContext context, CancellationToken cancellationToken)
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(Func`3 callback, DnsEndPoint endPoint, HttpRequestMessage requestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsyncCore(HttpRequestMessage request, HttpCompletionOption completionOption, Boolean async, Boolean emitTelemetryStartStop, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[Informational] Azure-Identity: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95 Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342))
 ---> System.AggregateException (0x80131500): Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342))
 ---> Azure.RequestFailedException (0x80131500): No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Http.HttpRequestException (0x80004005): No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it.
[Informational] Azure-Identity: DefaultAzureCredential.GetToken was unable to retrieve an access token. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: d2a1c790-7da1-4f3b-8eee-4c2b9f4aed95 Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342))
 ---> System.AggregateException (0x80131500): Retry failed after 4 tries. Retry settings can be adjusted in ClientOptions.Retry. (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342)) (No connection could be made because the target machine actively refused it. (localhost:50342))
 ---> Azure.RequestFailedException (0x80131500): No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Http.HttpRequestException (0x80004005): No connection could be made because the target machine actively refused it. (localhost:50342)
 ---> System.Net.Sockets.SocketException (0x80004005): No connection could be made because the target machine actively refused it.
 ```

**Comment by christothes** [comment]
Do you have any of these environment variables set?

MSI_ENDPOINT
IMDS_ENDPOINT
AZURE_POD_IDENTITY_AUTHORITY_HOST

**Comment by tyh77** [comment]
I don't believe so. 

This is a nearly brand new repo created from scratch not too long ago. There are virtually no configurations defined in either the launchSettings.json, .csproj, or appsettings.json (assuming these are all the possible places that Azure SDK can possible pick up from)

![image](https://user-images.githubusercontent.com/25734254/129123144-49636b91-148a-42c7-9415-35ef7d8f702b.png)

**Comment by christothes** [comment]
You would inherit them from the general environment. Could you confirm they are not set for either system or user environment variables? #feedback

**Comment by tyh77** [comment]
Ah yes. By system/user environment variables, you mean the Windows env vars?

I found MSI_ENDPOINT in my user variables and removed it - now it works.

That being said though, have no idea how my user environment variables were ever configured like so - this was the case on both my machines but I never touch those.

**Comment by christothes** [comment]
Glad that resolved it!
