### ISSUE TITLE
[BUG] Batch blob deletion fails with HTTP code 412 when ETag checking is enabled and storage has blob versioning enabled

### ISSUE THREAD

**Issue by jikspiir** [Azure/azure-sdk-for-net#23319]
Posting on behalf of @dacspiir and @adzspiir. 
We have been asked to open the issue here as the follow-up to the support ticket: **TrackingID#2107270050001045**

**Technical area and API documentation in question**
Azure SDK and Azure Blob Storage
[BlobBatch.DeleteBlob](https://docs.microsoft.com/en-us/javascript/api/@azure/storage-blob/blobbatch?view=azure-node-latest#deleteBlob_BlobClient__BlobDeleteOptions_)

**Describe the bug**
When working with blob storage, submitting a batch deletion where ETag checking is enabled (see example)
`batch.DeleteBlob("test", item.Name, DeleteSnapshotsOption.None, new BlobRequestConditions { IfMatch = item.Properties.ETag  });` will result in response code **412 (The condition specified using HTTP conditional header(s) is not met.)**

This only happens when the storage account has the "**Enable versioning for blobs**" option enabled. Using other values of `DeleteSnapshotsOption` does not resolve the issue.

**Expected behavior**
Blobs are deleted.

**Actual behavior**
An exception is thrown upon submitting the batch.

**Example Response**

```
Headers:
x-ms-error-code: ConditionNotMet
x-ms-request-id: 8def3893-a01e-00a4-4d38-8949fb1e27d5
x-ms-version: 2020-08-04
x-ms-client-request-id: 9a4a0c80-666f-4025-9826-8194286c46da
Content-Length: 253
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
) (The condition specified using HTTP conditional header(s) is not met.
RequestId:8def3893-a01e-00a4-4d38-8949fb1e27d6
Time:2021-08-04T13:57:13.1333214Z
Status: 412 (The condition specified using HTTP conditional header(s) is not met.)
ErrorCode: ConditionNotMet
 
Content:
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.
RequestId:8def3893-a01e-00a4-4d38-8949fb1e27d6
Time:2021-08-04T13:57:13.1333214Z</Message></Error>
```
**Example Stack Trace**
```
   at Azure.Storage.Blobs.Specialized.BlobBatch.<DeleteBlob>b__23_0(Response response)
   at Azure.Storage.Blobs.Specialized.DelayedResponse.SetLiveResponse(Response live, Boolean throwOnFailure)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(IList`1 messages, Response rawResponse, Stream responseContent, String responseContentType, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(IList`1 messages, Response rawResponse, Stream responseContent, String responseContentType, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.SubmitBatchInternal(BlobBatch batch, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.SubmitBatchAsync(BlobBatch batch, Boolean throwOnAnyFailure, CancellationToken cancellationToken)
   at TestBatchDelete.TestClass.DeleteAllBlobs(Boolean triggerBug) in C:\Users\Dani\RiderProjects\TMP\TestBatchDelete\TestBatchDelete\TestClass.cs:line 65
   at TestBatchDelete.TestClass.DeleteAllBlobs(Boolean triggerBug) in C:\Users\Dani\RiderProjects\TMP\TestBatchDelete\TestBatchDelete\TestClass.cs:line 50
   at TestBatchDelete.TestClass.RunTest() in C:\Users\Dani\RiderProjects\TMP\TestBatchDelete\TestBatchDelete\TestClass.cs:line 38
   at TestBatchDelete.Program.Main(String[] args) in C:\Users\Dani\RiderProjects\TMP\TestBatchDelete\TestBatchDelete\Program.cs:line 11
   at TestBatchDelete.Program.<Main>(String[] args)
---> (Inner Exception #1) Azure.RequestFailedException: The condition specified using HTTP conditional header(s) is not met.
```

**To Reproduce**
The below code is the minimal reproduction case that can be used to trigger the issue assuming the requirements have been met.

**csproj**
```csharp
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <TargetFramework>net5.0</TargetFramework>
    </PropertyGroup>
    <ItemGroup>
      <PackageReference Include="Azure.Storage.Blobs" Version="12.9.1" />
      <PackageReference Include="Azure.Storage.Blobs.Batch" Version="12.6.0" />
    </ItemGroup>
</Project>
```

**.cs**
```csharp
using System;
using System.IO;
using System.Threading.Tasks;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;

namespace TestBatchDelete
{
    internal class Program
    {
        private static async Task Main(string[] args)
        {
            var tc = new TestClass();
            await tc.RunTest();
        }
    }

    public class TestClass
    {
        private readonly BlobServiceClient _client;

        public TestClass()
        {
            _client = new BlobServiceClient(
                "connectionStringToAStorageAccountWithBlobVersioningEnabled");
        }

        public async Task RunTest()
        {
            // clear out old run (this works)
            await DeleteAllBlobs(false);

            // create demo files
            Console.WriteLine("Creating");
            for (var i = 0; i < 2; i++)
            {
                var memoryStream = new MemoryStream(new byte[] { 1, 2, 3, 4, 5 });
                var returnedInfo = await _client.GetBlobContainerClient("test").GetBlobClient("test" + i)
                    .UploadAsync(memoryStream);
                await memoryStream.DisposeAsync();
            }

            // delete files triggering the bug
            await DeleteAllBlobs(true);
        }

        private async Task DeleteAllBlobs(bool triggerBug)
        {
            Console.WriteLine("Deleting");
            var blobEnumerable = _client
                .GetBlobContainerClient("test")
                .GetBlobsAsync()
                .AsPages(null, 200);

            var batchClient = _client.GetBlobBatchClient();
            await foreach (var t in blobEnumerable)
            {
                if (t.Values.Count == 0)
                    break;
                var batch = batchClient.CreateBatch();
                foreach (var item in t.Values)
                    batch.DeleteBlob("test",
                        item.Name,
                        DeleteSnapshotsOption.None,
                        // BUG: Here below if we specify a matching etag (triggerBug=true) then the blobs will not be deleted.
                        new BlobRequestConditions { IfMatch = triggerBug ? item.Properties.ETag : null });

                // here blob storage service returns a "precondition failed" error instead of deleting the blobs.
                await batchClient.SubmitBatchAsync(batch, true);
            }
        }
    }
}
```

**Environment:**
- Azure.Storage.Blobs, 12.9.1
- Azure.Storage.Blobs.Batch, 12.6.0
- dotnet, 5.0.201
- Rider 2021.2, macOS Big Sur

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 92a1ce81-8222-ede3-2afb-63fc6ac19fee
* Version Independent ID: 9af6b596-9e70-d49a-1f6d-2b87bbc89128
* Content: [BlobBatch.DeleteBlob Method (Azure.Storage.Blobs.Specialized) - Azure for .NET Developers](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.specialized.blobbatch.deleteblob?view=azure-dotnet#Azure_Storage_Blobs_Specialized_BlobBatch_DeleteBlob_System_Uri_Azure_Storage_Blobs_Models_DeleteSnapshotsOption_Azure_Storage_Blobs_Models_BlobRequestConditions_)
* Content Source: [xml/Azure.Storage.Blobs.Specialized/BlobBatch.xml](https://github.com/Azure/azure-docs-sdk-dotnet/blob/master/xml/Azure.Storage.Blobs.Specialized/BlobBatch.xml)
* Service: **azure**
* GitHub Login: @rloutlaw
* Microsoft Alias: **routlaw**

**Comment by amishra-dev** [comment]
Thanks for reporting this to us @jikspiir (Jiri), I will track down the support ticket.

**Comment by amishra-dev** [comment]
@seanmcc-msft can you please try this sample out on Monday. Looks like an interaction issue between versioning and batch delete with etag check.

**Comment by seanmcc-msft** [comment]
Hi,

Unfortunately, I am unable to re-produce on the main branch.  I am running again a storage account with Blob Versioning enabled:
```
        [RecordedTest]
        public async Task Delete_GetProperties()
        {
            BlobServiceClient blobServiceClient = GetServiceClient_SharedKey();
            await using DisposingContainer test = await GetTestContainerAsync();
            AppendBlobClient appendBlobClient = InstrumentClient(test.Container.GetAppendBlobClient(GetNewBlobName()));
            await appendBlobClient.CreateAsync();

            List<BlobItem> blobItems = new List<BlobItem>();
            await foreach (BlobItem blobItem in test.Container.GetBlobsAsync())
            {
                blobItems.Add(blobItem);
            }

            BlobBatchClient blobBatchClient = blobServiceClient.GetBlobBatchClient();
            using BlobBatch batch = blobBatchClient.CreateBatch();
            Response[] responses = new Response[]
            {
                batch.DeleteBlob(test.Container.Name, blobItems[0].Name, DeleteSnapshotsOption.None, new BlobRequestConditions { IfMatch = blobItems[0].Properties.ETag })
            };
            Response response = await blobBatchClient.SubmitBatchAsync(batch, true);
        }
```

In Fiddler:
```
POST https://seanmcccanary3.blob.core.windows.net/?comp=batch HTTP/1.1
x-ms-version: 2020-10-02
Accept: application/xml
Content-Type: multipart/mixed; boundary=batch_7f5dfc4a-4f65-4b95-839a-dac1842c5a63
x-ms-client-request-id: c2f23939-11c5-4bd7-ba97-54ed403fb52a
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.10.0-alpha.20210817.1 (.NET Framework 4.8.4300.0; Microsoft Windows 10.0.19043 )
x-ms-date: Tue, 17 Aug 2021 15:55:19 GMT
Authorization: [auth]
Host: seanmcccanary3.blob.core.windows.net
Content-Length: 498
Expect: 100-continue

--batch_7f5dfc4a-4f65-4b95-839a-dac1842c5a63
Content-Type: application/http
Content-Transfer-Encoding: binary
Content-ID: 0

DELETE /test-container-bc14d38c-ed1c-4824-a0a7-7587bd45afcc/test-blob-7167ce7c-16ae-46a5-9d2e-1a04ce261ed1 HTTP/1.1
If-Match: 0x8D961976824FCE9
Accept: application/xml
Authorization: [auth]
x-ms-date: Tue, 17 Aug 2021 15:55:19 GMT
Content-Length: 0

--batch_7f5dfc4a-4f65-4b95-839a-dac1842c5a63--

HTTP/1.1 202 Accepted
Transfer-Encoding: chunked
Content-Type: multipart/mixed; boundary=batchresponse_ae961a55-1654-4eb5-9819-bb337ac06d8f
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: c503349a-601e-0022-3480-931fdd000000
x-ms-version: 2020-10-02
x-ms-client-request-id: c2f23939-11c5-4bd7-ba97-54ed403fb52a
Date: Tue, 17 Aug 2021 15:55:18 GMT

149
--batchresponse_ae961a55-1654-4eb5-9819-bb337ac06d8f
Content-Type: application/http
Content-ID: 0

HTTP/1.1 202 Accepted
x-ms-delete-type-permanent: true
x-ms-request-id: c503349a-601e-0022-3480-931fdd1ef666
x-ms-version: 2020-10-02
Server: Windows-Azure-Blob/1.0

--batchresponse_ae961a55-1654-4eb5-9819-bb337ac06d8f--
0
```

-Sean

**Comment by jikspiir** [comment]
Hey Sean,

Thank you for your reply and code example, we will definitely look into it! @dacspiir could you take look at the provided sample share your findings as well?

**Comment by dacspiir** [comment]
Hello,
After spending quite a bit of time in investigating this issue and setting up your test framework to use live resources, I finally managed to get to what seemed to be the problem that made the test case difficult to reproduce.
It seems that the first ever batch delete operation will work, but all the successive ones on the same container will all fail.

Here is a test for you that reproduces the issue in your test suite.

```csharp
        [RecordedTest]
        public async Task DAC_Test3()
        {
            BlobServiceClient blobServiceClient = GetServiceClient_SharedKey();
            await using DisposingContainer test = await GetTestContainerAsync();

            async Task RunTestOnce()
            {
                AppendBlobClient appendBlobClient = InstrumentClient(test.Container.GetAppendBlobClient("hey"));
                await appendBlobClient.CreateAsync();

                List<BlobItem> blobItems = new List<BlobItem>();
                await foreach (BlobItem blobItem in test.Container.GetBlobsAsync())
                {
                    blobItems.Add(blobItem);
                }

                BlobBatchClient blobBatchClient = blobServiceClient.GetBlobBatchClient();
                using BlobBatch batch = blobBatchClient.CreateBatch();
                Response[] responses = new Response[]
                {
                    batch.DeleteBlob(test.Container.Name, blobItems[0].Name, DeleteSnapshotsOption.None,
                        new BlobRequestConditions {IfMatch = blobItems[0].Properties.ETag})
                };
                Response response = await blobBatchClient.SubmitBatchAsync(batch, true);
            }

            await RunTestOnce(); // this works
            await RunTestOnce(); // this doesn't, as any new batch delete operation will fail after the first one.
        }
```

The issue was hidden in the test suite because the containers are not reused and so it was not triggering the bug.
Our test code was instead triggering the bug.

This now seems very much a backend issue, so this bug might be the not appropriate place to report this, if this is the case can you please direct me or forward this to the appropriate team?
Thank you!

**Comment by seanmcc-msft** [comment]
Hi @dacspiir, 

Thanks for the repo, I can now re-produce the bug.  I think this may indicate a minor bug in the storage service, I've reached out to our backend teams and will post here again when I have more information.

-Sean

**Comment by dacspiir** [comment]
Hi @seanmcc-msft, sorry to ping you directly. Do you have any update on this?
Thanks for your help!
Daniele

**Comment by amishra-dev** [comment]
@seanmcc-msft any update?

**Comment by dacspiir** [comment]
We are also still waiting for an update when available.

**Comment by hiteshsharma-msft** [comment]
@dacspiir Storage team is actively working on it. We will update you asap.
As a workaround, Will it be feasible, in your scenario, to directly delete the blob (https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobcontainerclient.deleteblob?view=azure-dotnet) instead of blobbatchclient?
