### ISSUE TITLE
[BUG] MSI AuthenticationFailedException when deploying to Azure

### ISSUE THREAD

**Issue by sauravbhattacharya001** [Azure/azure-sdk-for-net#23363]
I am getting the following AuthenticationFailedExceptionerror for an MSI based app when deployed to Azure. 

```
Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Headers:
Content-Length: 133
Date: Mon, 16 Aug 2021 22:04:55 GMT
---> Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Headers:
Content-Length: 133
Date: Mon, 16 Aug 2021 22:04:55 GMT

at Azure.Identity.ManagedIdentitySource.<HandleResponseAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Azure.Identity.ManagedIdentitySource.<AuthenticateAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Azure.Identity.ManagedIdentityClient.<AuthenticateAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Azure.Identity.ManagedIdentityCredential.<GetTokenImplAsync>d__9.MoveNext()
--- End of inner exception stack trace ---
at Microsoft.Azure.Cosmos.TokenCredentialCache.<RefreshCachedTokenWithRetryHelperAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.TokenCredentialCache.<GetTokenAsync>d__18.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.AuthorizationTokenProviderTokenCredential.<AddAuthorizationHeaderAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.GatewayAccountReader.<GetDatabaseAccountAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
at Microsoft.Azure.Cosmos.Routing.GlobalEndpointManager.GetAccountPropertiesHelper.<GetAndUpdateAccountPropertiesAsync>d__13.MoveNext()
```

This is the init code:

        CosmosClient client = new CosmosClient(AppSettings.Get.CosmosDB_Endpoint.Value, new DefaultAzureCredential(), GetCosmosClientOptions());
     

**Environment summary**
SDK Version: 1.3.0 (with Azure Cosmos 3.20.1)
OS Version Windows
IDE Visual Studio 16.9

**Comment by sauravbhattacharya001** [comment]
Needed to set the `AZURE_CLIENT_ID` environment variable.
