### ISSUE TITLE
[QUERY] Exception when migrating from ADAL to MSAL for Managed Identity resources (Azure.Identity library)

### ISSUE THREAD

**Issue by shahriak** [Azure/azure-sdk-for-net#23381]
**Query/Question**
Hello,

I am seeing the following exception after migrating to Azure.Identity as part of ADAl to MSAL migration. Here's the error message I am seeing:

```
2021-08-17 23:09:09.613287: An error occurred while starting the application.
2021-08-17 23:09:09.613318: ArgumentException: Connection string RunAs=App;AppId=436b3fb3-eb25-42ae-a376-d50202efbf86 is not valid. Must contain 'TenantId' attribute and it must not be empty.
2021-08-17 23:09:09.613352: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.ValidateAttribute(Dictionary<string, string> connectionSettings, string attribute, string connectionString)
2021-08-17 23:09:09.613381:
2021-08-17 23:09:09.613405:
2021-08-17 23:09:09.613422:
2021-08-17 23:09:09.613449: ArgumentException: Connection string RunAs=App;AppId=436b3fb3-eb25-42ae-a376-d50202efbf86 is not valid. Must contain 'TenantId' attribute and it must not be empty.
2021-08-17 23:09:09.613473:
2021-08-17 23:09:09.613594:
2021-08-17 23:09:09.613621: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.ValidateAttribute(Dictionary<string, string> connectionSettings, string attribute, string connectionString)
2021-08-17 23:09:09.613653:
2021-08-17 23:09:09.613678:
2021-08-17 23:09:09.613701:
2021-08-17 23:09:09.613733: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.Create(string connectionString, string azureAdInstance)
2021-08-17 23:09:09.613755:
2021-08-17 23:09:09.613771:
2021-08-17 23:09:09.613791:
2021-08-17 23:09:09.613814: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider..ctor(string connectionString, string azureAdInstance)
2021-08-17 23:09:09.613835:
2021-08-17 23:09:09.613931:
2021-08-17 23:09:09.613961:
2021-08-17 23:09:09.613980: Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationOptions..ctor(string vault)
2021-08-17 23:09:09.614003:
2021-08-17 23:09:09.614021:
2021-08-17 23:09:09.614042:
2021-08-17 23:09:09.614061: Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, string vault, IKeyVaultSecretManager manager)
2021-08-17 23:09:09.614083:
2021-08-17 23:09:09.614101:
2021-08-17 23:09:09.614122:
2021-08-17 23:09:09.614140: CCP.PTT.TrustDomainService.Program+<>c.<CreateHostBuilder>b__1_0(HostBuilderContext context, IConfigurationBuilder config) in Program.cs
2021-08-17 23:09:09.614161:
2021-08-17 23:09:09.614178:
2021-08-17 23:09:09.614198:
2021-08-17 23:09:09.614219: Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
2021-08-17 23:09:09.614243:
2021-08-17 23:09:09.614270:
2021-08-17 23:09:09.614290:
2021-08-17 23:09:09.614307: Microsoft.Extensions.Hosting.HostBuilder.Build()
2021-08-17 23:09:09.614327:
2021-08-17 23:09:09.614356:
2021-08-17 23:09:09.614376:
2021-08-17 23:09:09.614394: CCP.PTT.TrustDomainService.Program.Main(string[] args) in Program.cs
2021-08-17 23:09:09.614416:
2021-08-17 23:09:09.614433:
2021-08-17 23:09:09.614446:
2021-08-17 23:09:09.614468: CCP.PTT.TrustDomainService.Program.<Main>(string[] args)
2021-08-17 23:09:09.614485:
2021-08-17 23:09:09.614505:
2021-08-17 23:09:09.614522:
2021-08-17 23:09:09.614543:
2021-08-17 23:09:09.614560:
2021-08-17 23:09:09.614580:
2021-08-17 23:09:09.614597:
2021-08-17 23:09:09.614617:
2021-08-17 23:09:09.614634: Show raw exception details
2021-08-17 23:09:09.614655:
2021-08-17 23:09:09.614673:
2021-08-17 23:09:09.614713: System.ArgumentException: Connection string RunAs=App;AppId=436b3fb3-eb25-42ae-a376-d50202efbf86 is not valid. Must contain 'TenantId' attribute and it must not be empty. at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.ValidateAttribute(Dictionary`2 connectionSettings, String attribute, String connectionString) at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderFactory.Create(String connectionString, String azureAdInstance) at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider..ctor(String connectionString, String azureAdInstance) at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationOptions..ctor(String vault) at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, String vault, IKeyVaultSecretManager manager) at CCP.PTT.TrustDomainService.Program.<>c.<CreateHostBuilder>b__1_0(HostBuilderContext context, IConfigurationBuilder config) in C:\source\CCP.PTT.TrustDomainService\Program.cs:line 62 at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration() at Microsoft.Extensions.Hosting.HostBuilder.Build() at CCP.PTT.TrustDomainService.Program.Main(String[] args) in C:\source\CCP.PTT.TrustDomainService\Program.cs:line 32 at CCP.PTT.TrustDomainService.Program.<Main>(String[] args)
2021-08-17 23:09:09.614758:
2021-08-17 23:09:09.614776:
2021-08-17 23:09:09.614796:
2021-08-17 23:09:09.614825:
2021-08-17 23:09:09.614845:
2021-08-17 23:09:09.614862:
2021-08-17 23:09:09.614896: .NET 5.0.7 X86 v5.0.0.0    |   Microsoft.AspNetCore.Hosting version 5.0.7+67acc3d331454956fc06d6de2218a625e3e596f8    |    Microsoft Windows 10.0.14393    |   Need help?
2021-08-17 23:09:09.614925:
```

Here's my code changes:
```c#
    using System;
    using System.Threading.Tasks;
    using AspNetCoreRateLimit;
    using Azure.Core;
    using Azure.Identity;
    using Azure.Security.KeyVault.Secrets;
    using CCP.PTT.TrustDomainService.Data.Infrastructure;
    using Microsoft.AspNetCore.Hosting;
    using Microsoft.Extensions.Configuration;
    using Microsoft.Extensions.Configuration.AzureKeyVault;
    using Microsoft.Extensions.DependencyInjection;
    using Microsoft.Extensions.Hosting;

      private static IHostBuilder CreateHostBuilder(string[] args)
        {
            // For local debugging, az login is required for authentication.
            return Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((context, config) =>
                {
                    var builtConfig = config.Build();

                    var defaultClientCredentialOptions = new DefaultAzureCredentialOptions { ExcludeSharedTokenCacheCredential = true };
                    var credential = new DefaultAzureCredential(defaultClientCredentialOptions);

                    string keyVaultName = builtConfig["KeyVault:Name"];
                    string endpointSuffix = builtConfig["EndpointSuffix:Name"];
                    var keyVaultClient = new UnifiedKeyVaultClient($"https://{keyVaultName}{endpointSuffix}", credential);

                    config.AddAzureKeyVault(
                        $"https://{keyVaultName}{endpointSuffix}", new DefaultKeyVaultSecretManager());
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });
        }
```

This is the link that mentioned about the Managed Identity changes for Azure resources:
https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0#use-managed-identities-for-azure-resources

One thing about the documentation, as mentioned below the "KeyVaultSecretManager" does not seem to compile, I tried the DefaultKeyVaultSecretManager as well but still same issue.
                config.AddAzureKeyVault(secretClient, new KeyVaultSecretManager());

Other docs followed:
https://docs.microsoft.com/en-us/dotnet/api/overview/azure/app-auth-migration

**Environment:**
Name and version of the Library package used: Azure.Identity: 1.4.1, Azure.Security.KeyVault.Secrets: 4.2.0, Azure.Security.KeyVault.Certificates: 4.2.0
Hosting platform or OS and .NET runtime version (dotnet --info output for .NET Core projects):
.NET SDK (reflecting any global.json):  Version: 5.0.303  Commit: 6409b42649  Runtime Environment:  OS Name: Windows  OS Version: 10.0.19043  OS Platform: Windows  RID: win10-x64  Base Path: C:\Program Files\dotnet\sdk\5.0.303\  Host (useful for support):  Version: 5.0.9  Commit: 208e377a53  .NET SDKs installed:  3.0.103 [C:\Program Files\dotnet\sdk]  3.1.412 [C:\Program Files\dotnet\sdk]  5.0.104 [C:\Program Files\dotnet\sdk]  5.0.302 [C:\Program Files\dotnet\sdk]  5.0.303 [C:\Program Files\dotnet\sdk]  .NET runtimes installed:  Microsoft.AspNetCore.All 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]  Microsoft.AspNetCore.All 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]  Microsoft.AspNetCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.AspNetCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]  Microsoft.NETCore.App 2.1.28 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 2.1.29 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 2.2.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.NETCore.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]  Microsoft.WindowsDesktop.App 3.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Microsoft.WindowsDesktop.App 3.1.5 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Microsoft.WindowsDesktop.App 3.1.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Microsoft.WindowsDesktop.App 3.1.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Microsoft.WindowsDesktop.App 5.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]  Microsoft.WindowsDesktop.App 5.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
IDE and version : [e.g. Visual Studio 16.3]
Visual Studio 16.10.4

**Comment by christothes** [comment]
Hi @shahriak - For the reference to `KeyVaultSecretManager` - do you have a reference to the following NuGet package? https://www.nuget.org/packages/Azure.Extensions.AspNetCore.Configuration.Secrets/

#feedback

**Comment by shahriak** [comment]
@christothes Yes, I am using version 1.2.1:
	  <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.1" />

**Comment by christothes** [comment]
> @christothes Yes, I am using version 1.2.1:
> ` <PackageReference Include="Azure.Extensions.AspNetCore.Configuration.Secrets" Version="1.2.1" /> `

Thanks - you mentioned that you were unable to compile if you tried to use `KeyVaultSecretManager` - what error do you get?

**Comment by shahriak** [comment]
Ok, here's the documentation I am following https://docs.microsoft.com/en-us/aspnet/core/security/key-vault-configuration?view=aspnetcore-5.0#use-managed-identities-for-azure-resources

Here's what my looks like now:
```

   private static IHostBuilder CreateHostBuilder(string[] args)
        {
            // For local debugging, az login is required for authentication.
            return Host.CreateDefaultBuilder(args)
                .ConfigureAppConfiguration((context, config) =>
                {
                    var builtConfig = config.Build();
                    // Setup a listener to monitor logged events.
                    using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();

                    var defaultClientCredentialOptions = new DefaultAzureCredentialOptions { ExcludeSharedTokenCacheCredential = true };
                    var credential = new DefaultAzureCredential(defaultClientCredentialOptions);

                    SecretClientOptions options = new SecretClientOptions()
                    {
                        Diagnostics =
                        {
                            IsLoggingContentEnabled = true,
                            LoggedHeaderNames = { "x-ms-request-id" },
                            LoggedQueryParameters = { "api-version" }
                        },
                    };


                    string keyVaultName = builtConfig["KeyVault:Name"];
                    string endpointSuffix = builtConfig["EndpointSuffix:Name"];
                    var keyVaultClient = new UnifiedKeyVaultClient($"https://{keyVaultName}{endpointSuffix}", credential, null, options);

                    config.AddAzureKeyVault(
                        $"https://{keyVaultName}{endpointSuffix}",
                        new DefaultKeyVaultSecretManager());
                })
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder.UseStartup<Startup>();
                });

```

The problem I am running into now is not being able to pass the keyVaultClient inside the AddAzureKeyVault method.
I get this error when I try the following: CS1503: Argument 3: cannot convert from Azure.Security.KeyVault.Secrets.SecretClient, CS1503: Argument 4: Cannot convert from Microsoft.Extensions.Config.AzureKeyVault.DefaultKeyVaultSecretManager..
                    config.AddAzureKeyVault(
                        $"https://{keyVaultName}{endpointSuffix}", keyVaultClient.SecretClient, new DefaultKeyVaultSecretManager());

**Comment by heaths** [comment]
Are you using the [Microsoft.Extensions.Azure](https://nuget.org/packages/Microsoft.Extensions.Azure) extensions? There should be an `AddSecretClient` as [described here](https://docs.microsoft.com/samples/azure/azure-sdk-for-net/app-secrets-configuration/?tabs=visualstudio#:~:text=caching%20clients).

These are new extensions to correspond to our new Azure.* packages.

**Comment by shahriak** [comment]
@christothes Cleaning the project and doing a rebuild fixed the compilation issue and testing the changes locally also works , but I am running into another issue after deploying the changes:

An error occurred while starting the application.
RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Wed, 18 Aug 2021 19:19:01 GMT
Content-Length: 133
Azure.Identity.ManagedIdentitySource.HandleResponseAsync(bool async, TokenRequestContext context, Response response, CancellationToken cancellationToken)

AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Wed, 18 Aug 2021 19:19:01 GMT
Content-Length: 133
Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)

RequestFailedException: Service request failed. Status: 400 (Bad Request) Headers: Date: Wed, 18 Aug 2021 19:19:01 GMT Content-Length: 133
Azure.Identity.ManagedIdentitySource.HandleResponseAsync(bool async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Identity.ManagedIdentitySource.AuthenticateAsync(bool async, TokenRequestContext context, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Identity.ManagedIdentityClient.AuthenticateAsync(bool async, TokenRequestContext context, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(bool async, TokenRequestContext requestContext, CancellationToken cancellationToken)

Show raw exception details
Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Wed, 18 Aug 2021 19:19:01 GMT
Content-Length: 133

   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed. Status: 400 (Bad Request) Headers: Date: Wed, 18 Aug 2021 19:19:01 GMT Content-Length: 133
Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(bool async, TokenRequestContext requestContext, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, bool async, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(bool async, TokenRequestContext requestContext, CancellationToken cancellationToken)
Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(bool async, TokenRequestContext requestContext, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Core.Pipeline.BearerTokenAuthenticationPolicy+AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, bool async, CancellationToken cancellationToken)
Azure.Core.Pipeline.BearerTokenAuthenticationPolicy+AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, bool async)
Azure.Core.Pipeline.BearerTokenAuthenticationPolicy+AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, bool async)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()
Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthorizeRequestOnChallengeAsyncInternal(HttpMessage message, bool async)
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline, bool async)
Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline, bool async)
Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline, bool async)
Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory<HttpPipelinePolicy> pipeline, bool async)
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable+ConfiguredValueTaskAwaiter.GetResult()
Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
System.Threading.Tasks.ValueTask<TResult>.get_Result()
System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable<TResult>+ConfiguredValueTaskAwaiter.GetResult()
Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
Azure.Security.KeyVault.KeyVaultPipeline.GetPageAsync<T>(Uri firstPageUri, string nextLink, Func<T> itemFactory, string operationName, CancellationToken cancellationToken)
Azure.Core.PageResponseEnumerator+FuncAsyncPageable<T>.AsPages(string continuationToken, Nullable<int> pageSizeHint)
Azure.Core.PageResponseEnumerator+FuncAsyncPageable<T>.AsPages(string continuationToken, Nullable<int> pageSizeHint)
Azure.AsyncPageable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
Azure.AsyncPageable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
Azure.AsyncPageable<T>.GetAsyncEnumerator(CancellationToken cancellationToken)
Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.LoadAsync()
Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.LoadAsync()
Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.Load()
Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList<IConfigurationProvider> providers)
Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
Microsoft.Extensions.Hosting.HostBuilder.Build()
CCP.PTT.TrustDomainService.Program.Main(string[] args) in Program.cs
CCP.PTT.TrustDomainService.Program.<Main>(string[] args)

Show raw exception details
Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Wed, 18 Aug 2021 19:19:01 GMT
Content-Length: 133

 ---> Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Headers:
Date: Wed, 18 Aug 2021 19:19:01 GMT
Content-Length: 133

   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthorizeRequestOnChallengeAsyncInternal(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.GetPageAsync[T](Uri firstPageUri, String nextLink, Func`1 itemFactory, String operationName, CancellationToken cancellationToken)
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.Extensions.Hosting.HostBuilder.BuildAppConfiguration()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CCP.PTT.TrustDomainService.Program.Main(String[] args) in C:\source\CCP.PTT.TrustDomainService\Program.cs:line 34
   at CCP.PTT.TrustDomainService.Program.<Main>(String[] args)
.NET 5.0.7 X86 v5.0.0.0    |   Microsoft.AspNetCore.Hosting version 5.0.7+67acc3d331454956fc06d6de2218a625e3e596f8    |    Microsoft Windows 10.0.14393    |   Need help?

**Comment by shahriak** [comment]
@heaths No, I could not find any documentation with the changes you mentioned above. Is this required for Managed Identity for Azure App Services?

**Comment by heaths** [comment]
Based on your image:

![image](https://user-images.githubusercontent.com/1532486/129964145-ff233a10-a8b3-4b25-b85c-264162bc1307.png)

It seems you're calling the old extension methods to add a `SecretClient`. You need to use the newer extension methods. But it would also help to look at the method signature. I assume it takes an `IKeyVaultClient` or something like that, which is the old Microsoft.Azure.KeyVault that is deprecated.

**Comment by shahriak** [comment]
I found a similar issue on the above error message I posted: https://github.com/Azure/azure-sdk-for-net/issues/13564. Adding an env variable AZURE_CLIENT_ID and setting it to the Managed Identity client id solved the issue. Thank you for your help! @christothes @heaths
