### ISSUE TITLE
[Flaky Test] Storage Function Bindings: CanExtendVisibilityTimeoutMultipleTimes

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#23705]
**Error message**
Expected: True
But was:  False

**Stack trace**
   at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Tests.UpdateQueueMessageVisibilityCommandTests.CanExtendVisibilityTimeoutMultipleTimes() in /mnt/vss/_work/1/s/sdk/storage/Microsoft.Azure.WebJobs.Extensions.Storage.Queues/tests/UpdateQueueMessageVisibilityCommandTests.cs:line 51
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1075739&view=ms.vss-test-web.build-test-results-tab&runId=23316068&resultId=123571&paneView=debug

**Comment by jaschrep-msft** [comment]
Test is currently playback only. The forces that cause flakiness in live determined to be beyond our control. Closing.
