### ISSUE TITLE
No registered resource provider found for type 'locations/deletedVaults' 

### ISSUE THREAD

**Issue by mtucker2112** [Azure/azure-sdk-for-net#23760]
When running:

`var response = Subscription.GetDeletedVaults().GetIfExists(KeyVaultName);`

**Expected behavior**
To get a valid response, in this case I have a soft-deleted vault with KeyVaultName.

**Actual behavior**

No registered resource provider found for location '8968220f-66ac-4d06-a0dd-88eb77f6a833' and API version '2021-04-01-preview' for type 'locations/deletedVaults'. The supported api-versions are '2016-10-01, 2018-02-14-preview, 2018-02-14, 2019-09-01, **2020-04-01-preview, 2021-04-01-preview, 2021-06-01-preview**'. The supported locations are 'northcentralus, eastus, northeurope, westeurope, eastasia, southeastasia, eastus2, centralus, southcentralus, westus, japaneast, japanwest, australiaeast, australiasoutheast, brazilsouth, centralindia, southindia, westindia, canadacentral, canadaeast, uksouth, ukwest, westcentralus, westus2, koreacentral, koreasouth, francecentral, australiacentral, uaenorth, southafricanorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest'.
Status: 400 (Bad Request)
ErrorCode: NoRegisteredProviderFound

**_Does Azure.ResourceManager.KeyVault 1.0.0-beta.1 include use one of the API versions listed above?_** 

```
at Azure.ResourceManager.KeyVault.DeletedVaultsRestOperations.Get(String location, String vaultName, CancellationToken cancellationToken)
at Azure.ResourceManager.KeyVault.DeletedVaultContainer.GetIfExists(String vaultName, CancellationToken cancellationToken)
at TenantHub.Lib.MrsHelper.CreateKeyVault() in C:\Users\admin\source\repos\TenantHub\TenantHub.Lib\MrsHelper.cs:line 309
```

**Environment:**
 - Windows 10, .NET 4.7.2, Visual Studio 2019
 
**Packages**
Azure.Identity
1.5.0-beta.3

Azure.ResourceManager
1.0.0-beta.2

Azure.ResourceManager.AppConfiguration
1.0.0-preview.1

Azure.ResourceManager.Communication
1.0.0-beta.3

Azure.ResourceManager.Compute
1.0.0-beta.1

Azure.ResourceManager.Dns
1.0.0-preview.1

Azure.ResourceManager.EventHubs
1.0.0-preview.1

Azure.ResourceManager.Insights
1.0.0-preview.1

Azure.ResourceManager.KeyVault
1.0.0-beta.1

Azure.ResourceManager.Network
1.0.0-beta.1

Azure.ResourceManager.Resources
1.0.0-preview.2

Azure.ResourceManager.Storage
1.0.0-preview.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by AlexGhiondea** [comment]
@allenjzhang any ideas?

**Comment by VladimirKhvostov** [comment]
Hello,
I hit similar issue:
```CSharp
DeletedVaultCollection deletedVaults = armClient.GetDefaultSubscription().GetDeletedVaults();
int count = 0;

try
{
    foreach (DeletedVault deletedVault in deletedVaults)
    {
        Console.WriteLine(deletedVault.Id);
        ++count;
    }
}
catch (Exception ex)
{
    Console.WriteLine(ex);
}
```
fails reporting the following error:
```
System.ArgumentException: Invalid resource type Microsoft.KeyVault/locations/deletedVaults expected Microsoft.KeyVault/deletedVaults
   at Azure.ResourceManager.Core.ArmResource.ValidateResourceType(ResourceIdentifier identifier)
   at Azure.ResourceManager.Core.ArmResource..ctor(ClientContext clientContext, ResourceIdentifier id)
   at Azure.ResourceManager.Core.ArmResource..ctor(ArmResource parentOperations, ResourceIdentifier id)
   at Azure.ResourceManager.KeyVault.DeletedVault..ctor(ArmResource options, DeletedVaultData resource)
   at Azure.ResourceManager.KeyVault.DeletedVaultCollection.<>c__DisplayClass15_0.<GetAll>b__2(DeletedVaultData value)
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Azure.Core.Page.FromValues[T](IEnumerable`1 values, String continuationToken, Response response)
   at Azure.ResourceManager.KeyVault.DeletedVaultCollection.<>c__DisplayClass15_0.<GetAll>g__FirstPageFunc|0(Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.<>c__DisplayClass2_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.FuncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Pageable`1.GetEnumerator()+MoveNext()
   at Program.<Main>$(String[] args) in W:\vk\KeyVaultCleaner\KeyVaultCleaner\Program.cs:line 16
```

**Comment by ArthurMa1978** [comment]
@HarveyLink Minghao please help to check this issue

**Comment by ArthurMa1978** [comment]
Test does not cover Get on DeletedVaults, might be a bug

**Comment by HarveyLink** [comment]
Link issue https://github.com/Azure/autorest.csharp/issues/1685

**Comment by HarveyLink** [comment]
Shoule be fixed in latest beta version, @mtucker2112 could you please try this new version https://www.nuget.org/packages/Azure.ResourceManager.KeyVault/1.0.0-beta.4
