### ISSUE TITLE
ServiceBus MessageLock Exception if awaiting all CompleteAsync tasks at once

### ISSUE THREAD

**Issue by jblanchet** [Azure/azure-sdk-for-net#24060]
Using Azure.Messaging.ServiceBus v7.3.0. When calling `ServiceBusReceiver.CompleteMessageAsync()`, storing the resulting task into a collection and then awaiting all with await `Task.WhenAll(completionTasks);` eg:
```
foreach (var message in messagesToComplete)
{
  completionTasks.Add(ServiceBusReceiver.CompleteMessageAsync(message));
}
await Task.WhenAll(completionTasks);
```
This will result in a MessageLock exception when running on Azure (and sometimes locally):

```
2021-09-16T18:48:00Z   [Information]   Attempting to complete 576 messages.
2021-09-16T18:48:04Z   [Error]   Exception while completing messages: Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue, or was received by a different receiver instance. (MessageLockLost)
2021-09-16T18:48:04Z   [Verbose]   Oldest message is locked until: 09/16/2021 18:48:30 +00:00
2021-09-16T18:48:04Z   [Verbose]   Youngest message is locked until: 09/16/2021 18:48:30 +00:00
```
Note the timestamp of when that happened and the locked until messages below. They still had 26 seconds before timing out.

Switching to looping through the collection of message to complete and awaiting each one, eg:

```
foreach (var message in messagesToComplete)
{
  await ServiceBusReceiver.CompleteMessageAsync(message);
}
```

This solved the issue and the locking behaves as expected.

**Comment by JoshLove-msft** [comment]
Hi @jblanchet - do you have the full stack trace of the exception that you are getting? I'm wondering if we are being disconnected by the service.

**Comment by JoshLove-msft** [comment]
Also, in order to repro - you are attempting to complete 576 messages?

**Comment by jblanchet** [comment]
Hi @JoshLove-msft - stack trace is here:

```
at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ThrowLockLostException()
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.DisposeMessageAsync(Guid lockToken, Outcome outcome, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteInternalAsync(Guid lockToken, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<CompleteAsync>b__40_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.CompleteAsync(Guid lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.CompleteMessageAsync(Guid lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.CompleteMessageAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
   at [My calling code]
```

> Also, in order to repro - you are attempting to complete 576 messages?

I have an azure function on a timer trigger which picks up messages from a service bus queue and batches them together for further processing. The bigger the batch, the better the data processing, so I try to get it between 300 and 1200 messages. Maybe that's a bad idea? The completing of all the messages is not particularly fast.

**Comment by JoshLove-msft** [comment]
Any chance you can enable SDK logging?
```c#
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);
```

**Comment by JoshLove-msft** [comment]
> The bigger the batch, the better the data processing, so I try to get it between 300 and 1200 messages. Maybe that's a bad idea? The completing of all the messages is not particularly fast.

I do think that is quite a bit of messages if the lock duration is 30s, but given that it works when you await each completion, I suspect something else may be going on to cause it to fail when you add the tasks all at once.

**Comment by jblanchet** [comment]
> Any chance you can enable SDK logging?
> 
> ```cs
> using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);
> ```

This would be tough as the conditions to recreate the problem result in bad data going to our ETL. It really only happens when running on Azure (as opposed to locally running the function).

**Comment by JoshLove-msft** [comment]
Hi @jblanchet I was able to repro the issue and it seems that the service is throttling the requests if they happen too quickly. I believe the service may queue the requests internally when this happens. I am reaching out to the service team to see if there is any way we can detect when this is happening on the client.

**Comment by JoshLove-msft** [comment]
@DorothySun216 is investigating this - apparently 1 message gets throttled and all subsequent messages get removed from the unsettled map so they can no longer be settled. 

Need to double check with the Track 2 SDK because when testing this I didn't see a throttling exception - only lock lost.

**Comment by shlomiassaf** [comment]
This looks like a serious issue, are you planning to prioritize it?

**Comment by JoshLove-msft** [comment]
> This looks like a serious issue, are you planning to prioritize it?

We will need to check with the service team again on this - hopefully we'll have an update this week.

**Comment by JoshLove-msft** [comment]
The dev investigating this is currently out of the office, but we should have an update next week.

**Comment by JoshLove-msft** [comment]
Actually, it looks like our retry policy was not correctly backing off when being throttled by the service - after fixing this I could no longer repro.
