### ISSUE TITLE
[QUERY] TimeoutException continuously happened

### ISSUE THREAD

**Issue by kekatahi** [Azure/azure-sdk-for-net#24210]
**Query/Question**
We have eventhub upgrade and TmeoutException occurred. 
TimeoutException continued until restarting the client IIS and this issue was mitigated after restarting.
This issue happened frequently from August 7th.

Here is code snippet
```
try
{
    FooTrace.Info("IM00002", $"sendToEventHub {eventData.PartitionKey}");
    eventHubInfo.Client.Send(eventData);
}
catch (MessagingException me)
{
    if (me.IsTransient == false)
    {
        FooTrace.Error("EM00001", me, "sendToEventHub error. " + eventHubInfo.Client.Path);
        throw;
    }
    FooTrace.Info("IM00001", me, "sendToEventHub busy. " + eventHubInfo.Client.Path);
    throw new LdcIfException(LdcStatusCode.ServiceUnavailable, "eventhub is busy.");
}
catch (TimeoutException te)
{
    FooTrace.Info("IM00001", te, "sendToEventHub timeout. " + eventHubInfo.Client.Path);
    // operation timeout default 1 min
    throw new LdcIfException(LdcStatusCode.ServiceUnavailable, "eventhub timeout.");
}
```

Stack Trace
```
System.TimeoutException: The operation has timed out. Reference:af2766695b4145db817366c851cbcf92_G5, TrackingId:N/A, Timestamp:8/22/2021 3:55:34 AM ---> System.TimeoutException: The operation has timed out.
   at Microsoft.ServiceBus.Messaging.SingletonManager`1.EndGetInstance(IAsyncResult asyncResult)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessageSender.SendAsyncResult.<>c.<GetAsyncSteps>b__11_1(SendAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.Amqp.AmqpMessageSender.OnEndSendEventData(IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.ServiceBus.Common.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.ServiceBus.Messaging.EventHubClient.Send(EventData data)
   at Panasonic.Pcpf.Ldc.LdcIf.Common.M2MHandler.SendToEventHub(LdcPacket packet, String senderId, String serviceType, String senderType, EventHubClientInfo eventHubInfo)
```

We use the very old client library and plan to upgrade it . Actually , we are  very aware of that we need to upgrade the SDK version. But we are looking for the confirmation the issue was solved in the latest version before the upgrading.

If you know the similar issue which TimeoutException continuously happen until app restarted and it resolved, please let me know.

**Environment:**
 - Name and version of the Library package used: WindowsAzure.ServiceBus 4.1.6
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects): Windows Server 2016、 .NET Framework 4.6.2
 - IDE and version : Visual Studio Professional 2017 Version 15.9.26

**Comment by jsquire** [comment]
//fyi:  @serkantkaraca,  this inquiry is about the `WindowsAzure.ServiceBus` package.

**Comment by serkantkaraca** [comment]
@kekatahi, that exception you provided looks like a client-side timeout. In fact, issues being recovered after restarting the clients also supports the point. Given that this is a client-side timeout there can be various root-causes here. You should look these things at bare minimum:

- High CPU
- Low available memory
- High thread count
- Thread pool deprivation
- Network issues

See if the issue reproduces ever again and try to collect a process dump for further investigation. And also, check the VM's health where client is running.

**Comment by kekatahi** [comment]
@serkantkaraca Thank you for checking. 
We've already done VM level investigation and we think this is SDK issue. 
We really hope to upgrade the SDK. Before that,
We just wanted to know that are there any similar issue knowledge in SDK team not the trouble shooting step.

**Comment by serkantkaraca** [comment]
It is always recommended to stay up to date with the latest version of an SDK. There are numerous fixes and improvements in the client code past 3 years and you well may be hitting one of those. Please upgrade to the latest release at https://www.nuget.org/packages/WindowsAzure.ServiceBus/6.2.0

**Comment by kekatahi** [comment]
Thank you for checking . We will upgrade the SDK.
