### ISSUE TITLE
[Flaky test] LoadBalancingAppliesTheBalancedStrategy 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#24343]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1120361&view=ms.vss-test-web.build-test-results-tab&runId=24269142&resultId=105837&paneView=debug

```
LoadBalancingAppliesTheBalancedStrategy

Result Details
Failed Yesterday on a1870e20c000000
Duration0:00:23.973
Ownernot available
Date started9/29/2021, 2:07:52 PM
Date completed9/29/2021, 2:08:16 PM
Failing sinceYesterday
Failing since build20210929.4

Debug

Work items

Attachments

History

Attachments*

Error message
There should be a single owned partition.
Expected: 1
But was:  2


Stack trace
   at Azure.Messaging.EventHubs.Tests.EventProcessorTests.LoadBalancingAppliesTheBalancedStrategy() in D:\a\_work\1\s\sdk\eventhub\Azure.Messaging.EventHubs\tests\Primitives\EventProcessorTests.MainProcessingLoop.cs:line 1801
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
```
cc @jsquire

**Comment by jsquire** [comment]
Fixed by #24525.
