### ISSUE TITLE
[Failing test] OpenTelemetryTests.ProofOfConcept fails in live tests

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#24362]
```
Azure.Monitor.OpenTelemetry.Exporter.Integration.Tests.OpenTelemetryTests.ProofOfConcept

Result Details
Failed 42m ago on 4b3fb25dc000000
Duration0:00:00.447
Ownernot available
Date started10/1/2021, 9:20:46 AM
Date completed10/1/2021, 9:20:46 AM
Failing since26m ago
Failing since build20211001.2

Debug

Work items

Attachments

History

Attachments*

Error message
test project did not capture telemetry
Expected: True
Actual:   False


Stack trace
   at Azure.Monitor.OpenTelemetry.Exporter.Integration.Tests.OpenTelemetryTests.<ProofOfConcept>d__3.MoveNext() in D:\a\_work\1\s\sdk\monitor\Azure.Monitor.OpenTelemetry.Exporter\tests\Integration.Tests\OpenTelemetryTests.cs:line 47
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

```

cc @vishweshbankwar

**Comment by pakrym** [comment]
Fails in recorded runs as well: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1123650&view=ms.vss-test-web.build-test-results-tab&runId=24345602&resultId=113694&paneView=debug
