### ISSUE TITLE
[Failing test] VerifyLogExporter fails in live test runs

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#24360]
```
Failed to query telemetry. This is not necessarily a test failure and could be a result of an ingestion delay.
Expected: not null
But was:  null


Stack trace
   at Azure.Monitor.OpenTelemetry.Exporter.Integration.Tests.FunctionalTests.AzureMonitorTestBase.FetchTelemetryAsync() in /mnt/vss/_work/1/s/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Integration.Tests/FunctionalTests/AzureMonitorTestBase.cs:line 110
   at Azure.Monitor.OpenTelemetry.Exporter.Integration.Tests.FunctionalTests.AzureMonitorLogExporterLiveTests.VerifyLogExporter() in /mnt/vss/_work/1/s/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Integration.Tests/FunctionalTests/AzureMonitorLogExporterLiveTests.cs:line 53
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

cc @vishweshbankwar

**Comment by jsquire** [comment]
Closing as stale; if tests are still failing, the folks watching nightly runs will open a new issue to track.
