### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by kaboing** [Azure/azure-sdk-for-net#24385]
**Describe the bug**
I get a timeout while creating Azure Container Instances

**Expected behavior**
Being able to configure the timeout

**Actual behavior (include Exception or Stack Trace)**

```
      An unhandled exception has occurred while executing the request.
Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Canceled'.
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.PutLRO`2.CheckForErrors()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.StartPollingAsync()
   at Microsoft.Rest.ClientRuntime.Azure.LRO.AzureLRO`2.BeginLROAsync()
   at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody,THeader](IAzureClient client, AzureOperationResponse`2 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.Azure.AzureClientExtensions.GetLongRunningOperationResultAsync[TBody](IAzureClient client, AzureOperationResponse`1 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Rest.Azure.AzureClientExtensions.GetPutOrPatchOperationResultAsync[TBody](IAzureClient client, AzureOperationResponse`1 response, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroupsOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String containerGroupName, ContainerGroupInner containerGroup, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroupsOperationsExtensions.CreateOrUpdateAsync(IContainerGroupsOperations operations, String resourceGroupName, String containerGroupName, ContainerGroupInner containerGroup, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ContainerInstance.Fluent.ContainerGroupImpl.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IResourceCreator<IResourceT>.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.ExecuteNodeTaskAsync(DAGNode`1 node, CancellationToken cancellationToken)
   at ServerScaling.Controllers.HostingController.DeployAsync(Guid guid) in C:\source\hosting\api\ServerScaling\ServerScaling\Controllers\HostingController.cs:line 169
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. ```
var azure = new AsyncLazy<IAzure>(() => Microsoft.Azure.Management.Fluent.Azure
    .Configure()
    .WithLogLevel(HttpLoggingDelegatingHandler.Level.BodyAndHeaders)
    .Authenticate(credentials)
    .WithDefaultSubscriptionAsync());

IAzure az = await azure.GetValueAsync();

await az.ContainerGroups.Define()....CreateAsync();
```

**Environment:**
 - Microsoft.Azure.Management.Fluent 1.38.0
 - dotnet 5.0.4
 - VS 16.11.2

**Comment by kaboing** [comment]
If I do a GET request on the rest API to query the job, I get the same status message with the mispelled Canceled
```
{
    "id": "/subscriptions/e34a295b-b6c9-4f9c-b5ae-0377689f4e49/resourceGroups/hosting/providers/Microsoft.ContainerInstance/containerGroups/enzo-studios--demo-game-for-oss",
    "status": "Canceled",
    "startTime": "2021-10-04T12:19:57.8007717Z"
}
```

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by weidongxu-microsoft** [comment]
Local test is good

```
StatusCode: 200, ReasonPhrase: 'OK', Version: 1.1, Content: System.Net.Http.HttpConnectionResponseContent, Headers:
{
  Cache-Control: no-cache
  Pragma: no-cache
  Vary: Accept-Encoding
  x-ms-request-id: westus3:6654be9f-9369-4b8d-88fc-305163c713d7
  x-ms-ratelimit-remaining-subscription-reads: 11997
  x-ms-correlation-request-id: f1c14920-396b-484c-8d54-adad8fc933b0
  x-ms-routing-request-id: SOUTHEASTASIA:20220117T013131Z:f1c14920-396b-484c-8d54-adad8fc933b0
  Strict-Transport-Security: max-age=31536000; includeSubDomains
  X-Content-Type-Options: nosniff
  Date: Mon, 17 Jan 2022 01:31:30 GMT
  Content-Length: 1137
  Content-Type: application/json; charset=utf-8
  Expires: -1
}

Body:
{
{"properties":{"provisioningState":"Succeeded","containers":[{"name":"tomcat","properties":{"image":"tomcat","ports":[{"protocol":"TCP","port":8080}],"environmentVariables":[{"name":"ENV1","value":"value1"}],"instanceView":{"restartCount":0,"currentState":{"state":"Running","startTime":"2022-01-17T01:31:10.53Z","detailStatus":""}},"resources":{"requests":{"memoryInGB":1.5,"cpu":1.0}}}}],"restartPolicy":"Never","ipAddress":{"ports":[{"protocol":"TCP","port":8080}],"ip":"20.106.110.65","type":"Public","dnsNameLabel":"cg1weidxu","dnsNameLabelReusePolicy":"Unsecure","fqdn":"cg1weidxu.westus3.azurecontainer.io"},"osType":"Linux","volumes":[{"name":"emptydir1","emptyDir":{}}],"instanceView":{"events":[],"state":"Running"}},"identity":{"principalId":"6a556569-c9ef-4ba2-970f-7831351de3f5","tenantId":"72f988bf-86f1-41af-91ab-2d7cd011db47","type":"SystemAssigned"},"id":"/subscriptions/ec0aa5f7-9e78-40c9-85cd-535c6305b380/resourceGroups/javarg1weidxu/providers/Microsoft.ContainerInstance/containerGroups/cg1weidxu","name":"cg1weidxu","type":"Microsoft.ContainerInstance/containerGroups","location":"westus3","tags":{"tag1":"value1"}}
}
```
