### ISSUE TITLE
[BUG] Exception retrieving examples from LUIS with Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.LUISAuthoringClient 

### ISSUE THREAD

**Issue by ddo88** [Azure/azure-sdk-for-net#24455]
**Description**
Hi, **Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.LUISAuthoringClient.Examples.ListAsync**
 fails when try to retrieve data

**Expected behavior**
should retrieve the list of examples

**Actual behavior (include Exception or Stack Trace)**
When I try to get the list of LUIS examples, it throws an exception wher indicates that the id it tries to return is greater than int32, when checking the LabeledUtterance and LabelExampleResponse class I see that the id is indeed an int32? 
on the image can see that try ot cast 5259086643 as Int32 and throws the exception 

![imagen](https://user-images.githubusercontent.com/885227/136086768-7ac3ada7-e678-4d74-8cb3-57cf958c87f8.png)

System.AggregateException
  HResult=0x80131500
  Mensaje = One or more errors occurred. (Unable to deserialize the response.)
  Origen = System.Private.CoreLib
  Seguimiento de la pila:
   en System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   en System.Threading.Tasks.Task`1.get_Result()
   en LuisConsole.Program.Main(String[] args) en C:\Users\ddurano\source\repos\ConsoleApp2\LuisConsole\Program.cs: línea 30

  Esta excepción se generó originalmente en esta pila de llamadas:
    [Código externo]

Excepción interna 1:
SerializationException: Unable to deserialize the response.

Excepción interna 2:
JsonReaderException: JSON integer 5259086643 is too large or small for an Int32. Path '[0].id', line 1, position 17.

![imagen](https://user-images.githubusercontent.com/885227/135933187-4f617ec9-fcba-4e47-8e31-06c7b3a44163.png)

![imagen](https://user-images.githubusercontent.com/885227/135933205-c946474c-5414-4c4a-a272-10f842f0709a.png)

What is the actual behavior?

**To Reproduce**

![imagen](https://user-images.githubusercontent.com/885227/136086835-a1accc84-dbb8-4e99-af46-5148df703351.png)

**Environment:**
 - Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring [3.1.0]
 - Windows 10 [.NET 5.0]
 - IDE and version : [Microsoft Visual Studio Community 2022 Preview ]

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team best able to assist.

**Comment by ddo88** [comment]
I create this pr [fix LabeledUtterance Id property from Int32? to Long? ](https://github.com/Azure/azure-sdk-for-net/pull/24456url) for try to solve this bug

**Comment by agentschmitt** [comment]
I have the issue with integer overflow in LabelUtterance too on a production system.

I tried also with latest preview version 3.2.0-preview4, but it only has fix for LabelExampleResponse which fixes adding.
see https://github.com/Azure/azure-sdk-for-net/issues/18041#issuecomment-765668823

But i really need a fix for the get api to receive the LabelUtterance. I found there was a PR to fix it, but there was no reaction on it and was closed. see https://github.com/Azure/azure-sdk-for-net/pull/24456
@MahmoudYounes @cahann Can you maybe have a look at that?

Stacktrace:
`Microsoft.Rest.SerializationException: Unable to deserialize the response.
 ---> Newtonsoft.Json.JsonReaderException: JSON integer 2149417471 is too large or small for an Int32. Path '[0].id', line 1, position 17.
   at Newtonsoft.Json.JsonTextReader.ParseReadNumber(ReadType readType, Char firstChar, Int32 initialPosition)
   at Newtonsoft.Json.JsonTextReader.ReadNumberValue(ReadType readType)
   at Newtonsoft.Json.JsonTextReader.ReadAsInt32()
   at Newtonsoft.Json.JsonReader.ReadForType(JsonContract contract, Boolean hasConverter)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.CognitiveServices.Language.LUIS.Authoring.Examples.ListWithHttpMessagesAsync(Guid appId, String versionId, Nullable`1 skip, Nullable`1 take, Nullable`1 enableNestedChildren, Dictionary`2 customHeaders, CancellationToken cancellationToken)`

**Comment by agentschmitt** [comment]
I opened a PR to update the api specs that are used to generate the luis api client.

**Comment by cahann** [comment]
@moabba to signoff

**Comment by asturm0** [comment]
Hello @agentschmitt,
thank you very much for your contribution and hopefully this problem will be fixed soon. However, I am actually blocked by it, so I wanted to compile the SDK for C# myself. I assume you were in a similar situation, so I wanted to ask you how it is possible to generate a package? I saw that autorest is used, so I tried running the following. 
`autorest readme.md --tag=authoring_3_0_preview --csharp --csharp-sdks-folder=output`.
Unfortunately, autorest encounters an error (plugin modelerfour reported failure  - not able to process media type JSON at this moment). I have never worked with autorest before, so I was hoping you could give me (and maybe others) a little tip on how to generate a package.

**Comment by agentschmitt** [comment]
Hi @asturm0 i dont know the exactly command i used but i was able to build it Ehen running Autorest in legacy Mode so it uses c# Client 2 instead of 3.
I have an fork of the SDK too with the updated Client. https://github.com/SamhammerAG/azure-sdk-for-net/commit/718cce652600c455599ba9c73e3ebbbc48325fca
Hope that helps you. I was able to build a nuget package from this one and used that until we geht a fix.

**Comment by ziyadss** [comment]
Released version 3.2.0-preview.5 that fully addresses the bug.
