### ISSUE TITLE
[BUG]  "Azure.Identity.AuthenticationFailedException : ManagedIdentityCredential authentication failed: Cannot access a closed Stream" after update Azure.Identity from 1.4.0 or 1.4.1 to 1.5.0 beta 

### ISSUE THREAD

**Issue by dcanamares** [Azure/azure-sdk-for-net#24688]
I have a bunch of integration tests that get secrets from an Azure keyvault. When I run these tests on my machine tests work as expected and pass, but when these tests run in a Azure DevOps pipeline they are failing with the exception   Azure.Identity.AuthenticationFailedException : ManagedIdentityCredential authentication failed: Cannot access a closed Stream.

The issue is happening only with 1.5.0 beta version, I rollback the version to 1.4.1 and 1.4.0 and in tests run well on the Azure Devops pipeline.

The code failing is:

```csharp
            Configuration = configBuilder
                .AddAzureKeyVault(new Uri(builtConfig["key_vault_name"]), new DefaultAzureCredential())
                .Build();
```

This code is inside a class to initialize the tests.

**Expected behavior**
To run the tests in the pipeline in the same way than in a local machine.

**Actual behavior (include Exception or Stack Trace)**

```text
  Error Message:
   Azure.Identity.AuthenticationFailedException : ManagedIdentityCredential authentication failed: Cannot access a closed Stream.
---- System.ObjectDisposedException : Cannot access a closed Stream.
  Stack Trace:
     at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.AuthorizeRequestOnChallengeAsyncInternal(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.GetPageAsync[T](Uri firstPageUri, String nextLink, Func`1 itemFactory, String operationName, CancellationToken cancellationToken)
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()

----- Inner Stack Trace -----
   at System.IO.MemoryStream.set_Position(Int64 value)
   at Azure.Identity.ManagedIdentitySource.GetMessageFromResponse(Response response, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
```

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create an integration tests that call to Azure keyvault to retrieve some secrets.

```csharp
            var configBuilder = new ConfigurationBuilder()
                .AddEnvironmentVariables();

            var builtConfig = configBuilder.Build();

            Configuration = configBuilder
                .AddAzureKeyVault(new Uri(builtConfig["key_vault_name"]), new DefaultAzureCredential())
                .Build();
```

 - Azure.Identity 1.5.0 beta (tested with beta 3 and beta 4)
 - .NET Core 3.1.  Azure DevOps pipeline running on WIndows Server 2019

**Comment by christothes** [comment]
Hi @dcanamares - 
Do you have an example of an end to end code example that reproduces this issue? The code snippet in this issue seems to just define the construction of a `KeyClient`.

**Comment by dcanamares** [comment]
Hi @schaabs I have tested with Azure.Identity -version 1.5.0-alpha.20211013.1 and it is working well. Thank you very much, I will wait for the final release.
