### ISSUE TITLE
[feature] allow empty segment ID when parsing resource identifier

### ISSUE THREAD

**Issue by archerzz** [Azure/azure-sdk-for-net#24807]
# Description

The [bgpServiceCommunities](https://github.com/Azure/azure-rest-api-specs/blob/23a907284a522b84444181cb808af7266c6f1694/specification/network/resource-manager/Microsoft.Network/stable/2021-02-01/serviceCommunity.json#L37) API in Network will return `ID` like below.
```
{
    "value": [
        {
            "name": "Exchange",
            "id": "/subscriptions//resourceGroups//providers/Microsoft.Network/bgpServiceCommunities/Exchange",
            "type": "Microsoft.Network/bgpServiceCommunities",
            "properties": {
```

The subscription ID and resource group name are empty. That will cause error when parsing the return value:
```
Failed BGPCommunityApiTest [6 s]
  Error Message:
   System.ArgumentOutOfRangeException : Invalid resource id.
Parameter name: resourceId
  Stack Trace:
     at Azure.ResourceManager.ResourceIdentifier.Init(ResourceIdentifier parent, ResourceType resourceType, String name, Boolean isChild)
   at Azure.ResourceManager.ResourceIdentifier.AppendNext(ResourceIdentifier parent, List`1 parts)
   at Azure.ResourceManager.Network.Models.BgpServiceCommunity.DeserializeBgpServiceCommunity(JsonElement element) in C:\Users\mingzhehuang\workspaces\azure\azure-sdk-for-net\sdk\network\Azure.ResourceManager.Network\src\Generated\Models\BgpServiceCommunity.Serialization.cs:line 102
   at Azure.ResourceManager.Network.Models.BgpServiceCommunityListResult.DeserializeBgpServiceCommunityListResult(JsonElement element) in C:\Users\mingzhehuang\workspaces\azure\azure-sdk-for-net\sdk\network\Azure.ResourceManager.Network\src\Generated\Models\BgpServiceCommunityListResult.Serialization.cs:line 32
```

I think we should allow empty ID values. If the return value is like this, then the service should consume it correctly as well.

[Note]: Migrated from [ADO 6161](https://dev.azure.com/azure-mgmt-ex/DotNET%20Management%20SDK/_workitems/edit/6161/)

**Comment by archerzz** [comment]
After discussion, we decided to add a directive in `autorest.csharp` to omit inheritance type replacement, so that `BgpServiceCommunity` can skip inheriting `Resource`.
