### ISSUE TITLE
[Microsoft.Rest.ClientRuntime] Exception thrown when deserializing JSON with null values

### ISSUE THREAD

**Issue by Nking92** [Azure/azure-sdk-for-net#2501]
While re-recording tests for the Websites SDK, exceptions are being thrown when deserializing JSON in responses from the server. I poked around the ClientRuntime code a bit and issue seems to be happening in TransformationJsonConverter at this line: 

https://github.com/Azure/azure-sdk-for-net/blob/87cc2693e61b95f3345c663caf98ddec94418afd/src/ClientRuntime/Microsoft.Rest.ClientRuntime/Serialization/TransformationJsonConverter.cs#L93

Adding "&& propertyValueToken.Type != JTokenType.Null" inside the if statement seemed to fix the issue.

Here is a stack trace and copy of the response data for reference.

Test Name:         WebSites.Tests.ScenarioTests.WebSiteSlotScenarioTests.CreateAndDeleteWebSiteSlot
Test FullName:  WebSites.Tests.ScenarioTests.WebSiteSlotScenarioTests.CreateAndDeleteWebSiteSlot
Test Source:       E:\FileStore\Code\azure-sdk-for-net\src\ResourceManagement\WebSite\WebSite.Tests\ScenarioTests\WebSiteSlot.ScenarioTests.cs : line 146
Test Outcome:  Failed
Test Duration:    0:00:18.671

Result StackTrace:            

```
at Microsoft.Azure.Management.WebSites.WebAppsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__10.MoveNext() in E:\FileStore\Code\azure-sdk-for-net\src\ResourceManagement\WebSite\Microsoft.Azure.Management.Websites\Generated\WebAppsOperations.cs:line 1040
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.WebSites.WebAppsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__9.MoveNext() in E:\FileStore\Code\azure-sdk-for-net\src\ResourceManagement\WebSite\Microsoft.Azure.Management.Websites\Generated\WebAppsOperations.cs:line 809
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.<CreateOrUpdateAsync>d__9.MoveNext() in E:\FileStore\Code\azure-sdk-for-net\src\ResourceManagement\WebSite\Microsoft.Azure.Management.Websites\Generated\WebAppsOperationsExtensions.cs:line 265
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.WebSites.WebAppsOperationsExtensions.CreateOrUpdate(IWebAppsOperations operations, String resourceGroupName, String name, Site siteEnvelope, Nullable`1 skipDnsRegistration, Nullable`1 skipCustomDomainVerification, Nullable`1 forceDnsRegistration, String ttlInSeconds) in E:\FileStore\Code\azure-sdk-for-net\src\ResourceManagement\WebSite\Microsoft.Azure.Management.Websites\Generated\WebAppsOperationsExtensions.cs:line 226
   at WebSites.Tests.ScenarioTests.WebSiteSlotScenarioTests.CreateAndDeleteWebSiteSlot() in E:\FileStore\Code\azure-sdk-for-net\src\ResourceManagement\WebSite\WebSite.Tests\ScenarioTests\WebSiteSlot.ScenarioTests.cs:line 180
   at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in E:\FileStore\Code\azure-sdk-for-net\src\ClientRuntime\Microsoft.Rest.ClientRuntime\Serialization\TransformationJsonConverter.cs:line 54
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer) in E:\FileStore\Code\azure-sdk-for-net\src\ClientRuntime\Microsoft.Rest.ClientRuntime\Serialization\TransformationJsonConverter.cs:line 95
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings) in E:\FileStore\Code\azure-sdk-for-net\src\ClientRuntime\Microsoft.Rest.ClientRuntime\Serialization\SafeJsonConvert.cs:line 37
   at Microsoft.Azure.Management.WebSites.WebAppsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__10.MoveNext() in E:\FileStore\Code\azure-sdk-for-net\src\ResourceManagement\WebSite\Microsoft.Azure.Management.Websites\Generated\WebAppsOperations.cs:line 1031
Result Message:               
Unable to deserialize the response.
Error reading JObject from JsonReader. Current JsonReader item is not an object: Null. Path 'properties.siteConfig', line 1, position 1628.
```

Raw response data from the server:

```
{
   "id":"/subscriptions/0d3ae56c-deaf-4982-b514-33d016d4a683/resourceGroups/csmrg9558/providers/Microsoft.Web/sites/csmws9935",
   "name":"csmws9935",
   "type":"Microsoft.Web/sites",
   "location":"South Central US",
   "tags":null,
   "properties":{
      "name":"csmws9935",
      "state":"Running",
      "hostNames":[
         "csmws9935.azurewebsites.net"
      ],
      "webSpace":"csmrg9558-SouthCentralUSwebspace",
      "selfLink":"https://waws-prod-sn1-059.api.azurewebsites.windows.net:454/subscriptions/0d3ae56c-deaf-4982-b514-33d016d4a683/webspaces/csmrg9558-SouthCentralUSwebspace/sites/csmws9935",
      "repositorySiteName":"csmws9935",
      "owner":null,
      "usageState":0,
      "enabled":true,
      "adminEnabled":true,
      "enabledHostNames":[
         "csmws9935.azurewebsites.net",
         "csmws9935.scm.azurewebsites.net"
      ],
      "siteProperties":{
         "metadata":null,
         "properties":[

         ],
         "appSettings":null
      },
      "availabilityState":0,
      "sslCertificates":null,
      "csrs":[

      ],
      "cers":null,
      "siteMode":null,
      "hostNameSslStates":[
         {
            "name":"csmws9935.azurewebsites.net",
            "sslState":0,
            "ipBasedSslResult":null,
            "virtualIP":null,
            "thumbprint":null,
            "toUpdate":null,
            "toUpdateIpBasedSsl":null,
            "ipBasedSslState":0,
            "hostType":0
         },
         {
            "name":"csmws9935.scm.azurewebsites.net",
            "sslState":0,
            "ipBasedSslResult":null,
            "virtualIP":null,
            "thumbprint":null,
            "toUpdate":null,
            "toUpdateIpBasedSsl":null,
            "ipBasedSslState":0,
            "hostType":1
         }
      ],
      "computeMode":null,
      "serverFarm":null,
      "serverFarmId":"/subscriptions/0d3ae56c-deaf-4982-b514-33d016d4a683/resourceGroups/csmrg9558/providers/Microsoft.Web/serverfarms/csmwhp8892",
      "reserved":false,
      "lastModifiedTimeUtc":"2016-10-25T19:51:50.4166667",
      "storageRecoveryDefaultState":"Running",
      "contentAvailabilityState":0,
      "runtimeAvailabilityState":0,
      "siteConfig":null,
      "deploymentId":"csmws9935",
      "trafficManagerHostNames":null,
      "sku":"Standard",
      "premiumAppDeployed":null,
      "scmSiteAlsoStopped":false,
      "targetSwapSlot":null,
      "hostingEnvironment":null,
      "hostingEnvironmentProfile":null,
      "microService":"WebSites",
      "gatewaySiteName":null,
      "clientAffinityEnabled":true,
      "clientCertEnabled":false,
      "hostNamesDisabled":false,
      "domainVerificationIdentifiers":null,
      "kind":null,
      "outboundIpAddresses":"40.124.12.75,13.65.98.160,13.65.37.54,13.85.79.179,13.85.78.254",
      "containerSize":0,
      "dailyMemoryTimeQuota":0,
      "suspendedTill":null,
      "siteDisabledReason":0,
      "functionExecutionUnitsCache":null,
      "maxNumberOfWorkers":null,
      "homeStamp":"waws-prod-sn1-059",
      "cloningInfo":null,
      "hostingEnvironmentId":null,
      "tags":null,
      "resourceGroup":"csmrg9558",
      "defaultHostName":"csmws9935.azurewebsites.net"
   }
}
```

**Comment by olydis** [comment]
So the actual problem seems to be that `JObject.Load(JsonReader reader)` does not return `null` if the `reader` has a `JsonToken.Null` as next token (see stack trace, that's where stuff finally blows up).
Your proposed check absolutely works in this scenario as it prevents `ReadJson` to be called recursively on the property that will cause this bug (here: `siteConfig`).

I suggest the right way to handle this is to accompany all `JObject.Load`s with a check for null:
```C#
if (reader.TokenType == JsonToken.Null)
{
    return null;
}
JObject jsonObject = JObject.Load(reader);
```

**Comment by cormacpayne** [comment]
@Nking92 we have published ClientRuntime with the changes in the PR by @olydis 

https://www.nuget.org/packages/Microsoft.Rest.ClientRuntime.Azure/3.3.4
