### ISSUE TITLE
[BUG] Failure when a Uri with a double slash between the storage endpoint and container name is passed to the Storage Client

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-sdk-for-net#25051]
**Describe the bug**
Getting the following exception when trying to download blobs using AzureSasCredential or AzurePowerShellCredential:
```
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
</Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue /><Reason /></Error>
```

**To Reproduce**
The following code fails in the call to the Download() method when using AzureSasCredential and AzurePowerShellCredential (listing containers and blobs works fine).
All operations work fine when using the connection string.

```
			var accountName = "";
			var accessKey = "";
			var connectionString = $"DefaultEndpointsProtocol=https;AccountName={accountName};" +
				$"AccountKey={accessKey};EndpointSuffix=core.windows.net";

			//var credential = new AzureSasCredential("");
			//var storageUrl = $"https://{accountName}.blob.core.windows.net/";

			var serviceClient = new BlobServiceClient(connectionString);
			//var serviceClient = new BlobServiceClient(new(storageUrl), credential);

			foreach (var container in serviceClient.GetBlobContainers())
			{
				Console.WriteLine(container.Name);
				var containerClient = new BlobContainerClient(connectionString, container.Name);
				//var containerClient = new BlobContainerClient(new Uri($"{storageUrl}/{container.Name}"), credential);
				foreach (var blob in containerClient.GetBlobs())
				{
					Console.WriteLine($"\t{blob.Name}");
					var blobClient = containerClient.GetBlobClient(blob.Name);
					var response = blobClient.Download();
					using var reader = new StreamReader(response.Value.Content);
					reader.ReadToEnd();
				}
			}

```

**Environment:**
Azure.Storage.Blobs 12.10.0
Azure.Identity 1.5.0

**Comment by andrei-faber** [comment]
PS stack trace
```
   at Azure.Storage.Blobs.BlobRestClient.Download(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadInternal(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download(CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.Download()
...
```

**Comment by SaurabhSharma-MSFT** [comment]
@andrei-faber We are looking into this and get back to you.

**Comment by SaurabhSharma-MSFT** [comment]
@andrei-faber How are you generating the AzureSasCredential as SAS credential expects a SAS token. Can you please share the code.

**Comment by andrei-faber** [comment]
@SaurabhSharma-MSFT manually via the portal. It does work for listing blobs.
Also, plz note that same bug happens when using AzurePowerShellCredential.

**Comment by andrei-faber** [comment]
PS StorageSharedKeyCredential throws same error, with same storage name and access key as used in the connection string (that works)

**Comment by amnguye** [comment]
> PS StorageSharedKeyCredential throws same error, with same storage name and access key as used in the connection string (that works)

Sounds like something is different in the endpoint that's being passed then. Let's take this offline, I will send you an email @andrei-faber

**Comment by amnguye** [comment]
Came to a conclusion offline. Looks like there's a bug within the BlobUriBuilder which is triggered when a customer passes the Uri with a double slash between the Blob Endpoint and the container name.
e.g. https://{accountName}.blob.core.windows.net**//**{containerName}

This is due to the parsing method, we see the container name to be between two slashes but since there isn't, we assumed there's no container name. Thus causing the error above, since it creates a blob URL that no longer has the container name (or blob name).

Looking into considering a fix into all the {storageService}UriBuilders.

As a mitigation, the appended slash must be removed.
e.g. var containerClient = new BlobContainerClient(new Uri($"{storageUrl}{container.Name}")

**Comment by djj0809** [comment]
I ran into this one as well, thanks for pointing out this bug.
