### ISSUE TITLE
Azure.Storage.Blobs.ServiceRestClient.GetUserDelegationKey : System.ObjectDisposedException: Cannot access a closed Stream

### ISSUE THREAD

**Issue by cvakarna** [Azure/azure-sdk-for-net#25207]
we are facing an exception while generating the SAS Token using GetUserDelegationKey, Here is the exception that we are getting on concurrent requests.

```text
System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Write(ReadOnlySpan`1 buffer)
   at System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   at System.IO.StreamWriter.Dispose(Boolean disposing)
   at System.Xml.XmlTextWriter.Close()
   at Azure.Core.XmlWriterContent.Dispose()
   at Azure.Core.Pipeline.HttpClientTransport.PipelineRequest.Dispose()
   at Azure.Core.HttpMessage.Dispose()
   at Azure.Storage.Blobs.ServiceRestClient.GetUserDelegationKey(KeyInfo keyInfo, Nullable`1 timeout, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetUserDelegationKeyInternal(Nullable`1 startsOn, DateTimeOffset expiresOn, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetUserDelegationKey(Nullable`1 startsOn, DateTimeOffset expiresOn, CancellationToken cancellationToken)
   at service.mediastorage.DefsultCredntialStorageService.GetUrlWithAccessToken(String url, Double expiredInHours)
   at service.services.VideoService.Convert(Video video) in /home/vsts/work/Source/service.services/VideoService.cs:line 456
   at System.Linq.Enumerable.SelectListIterator`2.ToList()
   at service.services.VideoService.GetVideosByPaginationaAsync(VideoFilterQueryParams filterParameters, LoggedInUserInfo loggedInUserInfo) in /home/vsts/work/Source/service.services/VideoService.cs:line 175
   at service.api.Controllers.VideoController.GetVideosByPaginationAsync(VideoFilterQueryParams videoFilterQueryParameters) in /home/vsts/work/Source/service.api/Controllers/VideoController.cs:line 216
```

The following code is using to generate sastoken

```csharp
       public  string GetUrlWithAccessToken(string url, double expiredInHours = 0)
        {
            if (string.IsNullOrEmpty(url)) return null;
            var uri = new Uri(url);

            var blobClient = new BlobClient(uri, GetDefaultCredentials());
            var blobServiceClient = GetBlobServiceClient(_amsSettings.StorageEndPointUrl);

            UserDelegationKey userDelegationKey =  blobServiceClient.GetUserDelegationKey(DateTimeOffset.UtcNow,
                                                                               DateTimeOffset.UtcNow.AddHours(1));
            string sasTokenUrl = GetBlobUrlWithAccessToken(userDelegationKey, blobClient, url, expiredInHours);
            return sasTokenUrl;
        }
		
		 private string GetBlobUrlWithAccessToken(UserDelegationKey userDelegationKey, BlobClient blobClient,string url,double expiredInHours)
        {
            // Create a SAS token
            BlobSasBuilder sasBuilder = new BlobSasBuilder()
            {
                BlobContainerName = blobClient.GetParentBlobContainerClient().Name,
                BlobName = blobClient.Name,
                Resource = "b"
            };

          
            sasBuilder.ExpiresOn = DateTimeOffset.UtcNow.AddHours(expiredInHours);
            sasBuilder.SetPermissions(BlobSasPermissions.Read);

            // Add the SAS token to the container URI.
            BlobUriBuilder blobUriBuilder = new BlobUriBuilder(blobClient.Uri)
            {
                // Specify the user delegation key.
                Sas = sasBuilder.ToSasQueryParameters(userDelegationKey,
                                                      blobClient.AccountName)
            };
            var sasToken = blobUriBuilder.Sas.ToString();
            return url + "?" + sasToken;
        }
```

Can help me regarding this, where is the issue?

**Comment by SaurabhSharma-MSFT** [comment]
@cvakarna We are looking into it and get back to you.

**Comment by cvakarna** [comment]
any findings on this issue @SaurabhSharma-MSFT

**Comment by amnguye** [comment]
What are the authentication details in your method called
GetBlobServiceClient on line 7 (Looks like you're calling a stand alone method not from the SDK, since its not calling from a SDK API object)

hopefully it looks like this?
`BlobServiceClient blobClient = new BlobServiceClient(new Uri(blobEndpoint), new DefaultAzureCredential());`

please confirm

**Comment by cvakarna** [comment]
Hi @amnguye  
we are using Managed Identity, the answer for your question is yes
GetBlobServiceClient  method code is same as you mentioned. 

`BlobServiceClient blobClient = new BlobServiceClient(new Uri(blobEndpoint), new DefaultAzureCredential());
`

**Comment by cvakarna** [comment]
after updating latest version of **Azure.Identity**  its giving meaningful exception states that 

```
Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 429 ( )
```

Updated version:
**Azure.Identity   -  1.5.0**

**Comment by amishra-dev** [comment]
Identity folks, can you help?

**Comment by christothes** [comment]
Hi @cvakarna - Can you enable logging for the credential and post the relevant output? Details here:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/README.md#logging
