### ISSUE TITLE
[QUERY]Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.MSILoginException for token_type property not found in the response.

### ISSUE THREAD

**Issue by PrachiJagtapTR** [Azure/azure-sdk-for-net#25248]
**Query/Question**
I'm using  user managed identity to get azure credentials.
var credential = SdkContext.AzureCredentialsFactory
                    .FromUserAssigedManagedServiceIdentity (
                        "user MI clientid",
                        MSIResourceType.AppService,
                        AzureEnvironment.AzureGlobalCloud); 

```to get azure AzureCredentials. 
However  I'm getting the MSILoginException , can someone help me with this?

**Environment:**
 - Microsoft.Azure.Management.ResourceManager.Fluent  1.0.0.66
 -  Azure AppService

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by auditio** [comment]
Running into Bad Request error while trying to Authenticate via Managed Identity in application hosted in docker container within App Service as well:

Azure.Identity.AuthenticationFailedException: ManagedIdentityCredential authentication failed: Service request failed.
Status: 400 (Bad Request)

Content:


Headers:
Date: Thu, 06 Jan 2022 17:46:25 GMT
Server: Kestrel
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
 ---> Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Content:


Headers:
Date: Thu, 06 Jan 2022 17:46:25 GMT
Server: Kestrel
Transfer-Encoding: chunked
Content-Type: application/json; charset=utf-8

   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---

**Comment by weidongxu-microsoft** [comment]
For .NET, the development focus has shifted to the next generation of Azure SDKs which follows the new SDK guideline and introduces a set of important new features. Those new packages are currently in preview state and we are actively working on making it production ready. You can visit this link here to see the latest .NET packages:
https://devblogs.microsoft.com/azure-sdk/october-2020-management-ga/

We have also published a few blog posts on why we are doing this:
https://devblogs.microsoft.com/azure-sdk/introducing-new-previews-for-azure-management-libraries/

With this background, .NET Fluent is currently in a low maintenance mode, and we mostly do security and bug fixes. It is subject to deprecation in the future when the new set of .NET packages become Generally Available (GA). Please let us know if there are further questions, thanks!

**Comment by weidongxu-microsoft** [comment]
Also we do not explicit support combine use of new Azure.Identity with old Fluent SDK.

Please do use the new SDK here https://aka.ms/azsdk/dotnet/mgmt
