### ISSUE TITLE
[BUG] Exception when downloading contents of blob

### ISSUE THREAD

**Issue by adaml984** [Azure/azure-sdk-for-net#25430]
Hello
**Describe the bug**
I get exception when I try to download the contents of the blob stored on Azure Blob storage container.

**Expected behavior**
Downloading files without exceptions.

**Actual behavior (include Exception or Stack Trace)**
Azure.RequestFailedException: Value for one of the query parameters specified in the request URI is invalid.
RequestId:752460f7-a01e-0021-392f-dd15d0000000
Time:2021-11-19T10:26:03.9095937Z
Status: 400 (Value for one of the query parameters specified in the request URI is invalid.)
ErrorCode: InvalidQueryParameterValue

Additional Information:
QueryParameterName: comp
QueryParameterValue:
Reason:

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>InvalidQueryParameterValue</Code><Message>Value for one of the query parameters specified in the request URI is invalid.
RequestId:752460f7-a01e-0021-392f-dd15d0000000
Time:2021-11-19T10:26:03.9095937Z</Message><QueryParameterName>comp</QueryParameterName><QueryParameterValue /><Reason /></Error>

Headers:
Server: Microsoft-HTTPAPI/2.0
x-ms-request-id: 752460f7-a01e-0021-392f-dd15d0000000
x-ms-client-request-id: 3d632ee4-01db-429a-8c76-a878056c7a18
x-ms-error-code: InvalidQueryParameterValue
Date: Fri, 19 Nov 2021 10:26:03 GMT
Content-Length: 351
Content-Type: application/xml

   at Azure.Storage.Blobs.BlobRestClient.DownloadAsync(String snapshot, String versionId, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentMD5, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingAsync(HttpRange range, BlobRequestConditions conditions, Boolean rangeGetContentHash, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.PartitionedDownloader.DownloadToAsync(Stream destination, BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StagedDownloadAsync(Stream destination, BlobRequestConditions conditions, StorageTransferOptions transferOptions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(Stream destination, BlobRequestConditions conditions, StorageTransferOptions transferOptions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(Stream destination, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(Stream destination)

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

1. Create azure storage accout, container and queue under it
2. Create function that is triggered by storage queue message
3. Put some json files in container
4. Send message to queue
5. wait for result

Here's code i use:
....
var blobContainerClient =
            new BlobContainerClient(_settingsProvider.AzureStorageConnectionString, GetContainerName(path)); //works
        var blobs = blobContainerClient.GetBlobs();  //works
....
var blobClient = blobContainerClient.GetBlobClient(blobItem.Name);
                    await using var memStream = new MemoryStream();
                    await blobClient.DownloadToAsync(memStream); //this line throws an exception
....
**Environment:**
 NET 6.0,
 Visual Studio 2022
 Nugets:
 <PackageReference Include="Microsoft.AspNetCore.AzureKeyVault.HostingStartup" Version="2.0.4" />
    <PackageReference Include="Microsoft.Azure.Functions.Extensions" Version="1.1.0" />
    <PackageReference Include="Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0" />
    <PackageReference Include="Microsoft.NET.Sdk.Functions" Version="4.0.1" />

**Comment by adaml984** [comment]
Nugets:
"Microsoft.Azure.Functions.Extensions" Version="1.1.0"
"Microsoft.Azure.WebJobs.Extensions.Storage" Version="5.0.0"
"Microsoft.NET.Sdk.Functions" Version="4.0.1"

**Comment by adaml984** [comment]
I've found the issue, it was on mi side. We can close this "bug".
