### ISSUE TITLE
[Flaky Test] Champion_BasicCheckpointing

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#25444]
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1206187&view=ms.vss-test-web.build-test-results-tab&runId=25960692&resultId=116513&paneView=debug

```

Error message
Expected: 489
But was:  500


Stack trace
   at Azure.Search.Documents.Tests.BatchingTests.Champion_BasicCheckpointing() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 385
   at Azure.Search.Documents.Tests.BatchingTests.Champion_BasicCheckpointing() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 390
   at Azure.Search.Documents.Tests.BatchingTests.Champion_BasicCheckpointing() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\BatchingTests.cs:line 390
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by JoshLove-msft** [comment]
Marked as ignored in https://github.com/Azure/azure-sdk-for-net/pull/25927
