### ISSUE TITLE
[BUG] Could not load file or assembly 'System.Text.Json'

### ISSUE THREAD

**Issue by penihel** [Azure/azure-sdk-for-net#25649]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Describe the bug

Run a .net 4.8 application without .net 3.5 installed

### Expected behavior

Run normally

### Actual behavior

```
Could not load file or assembly 'System.Text.Json, Version=4.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' ou uma de suas dependências. O sistema não pode encontrar o arquivo especificado.

   at Azure.Core.Pipeline.StorageClientDiagnostics.ExtractFailureContent(String content, ResponseHeaders responseHeaders, String& message, String& errorCode, IDictionary`2& additionalInfo)
   at Azure.Core.Pipeline.ClientDiagnostics.CreateRequestFailedException(Response response, String message, String errorCode, IDictionary`2 additionalInfo, Exception innerException)
   at Azure.Storage.Blobs.ContainerRestClient.Create(Nullable`1 timeout, IDictionary`2 metadata, Nullable`1 access, String defaultEncryptionScope, Nullable`1 preventEncryptionScopeOverride, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.<CreateInternal>d__53.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.<CreateIfNotExistsInternal>d__52.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.CreateIfNotExists(PublicAccessType publicAccessType, IDictionary`2 metadata, BlobContainerEncryptionScopeOptions encryptionScopeOptions, CancellationToken cancellationToken)
   at Implanta.Common.ArquivosAnexos.AzureStorage.BlobStorageManager.Upload(String databaseName, String containerName, String virtualPathAndBlobFileName, Byte[] cotentBytes, String contentType) in D:\Repos\implantanet\implantanet-web-repo\src\Common\Implanta.Common.ArquivosAnexos.AzureStorage\BlobStorageManager.cs:line 81
```

### Reproduction Steps

Run a .net 4.8 application without .net 3.5 installed

### Environment

SDK do .NET (refletindo qualquer global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Ambiente de runtime:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
  
  
  And Here .NET Framework Installed
  
  ComputerName : localhost
>=4.x        : 4.8 or later
v4\Client    : Installed
v4\Full      : Installed
v3.5         : Not installed (no key)
v3.0         : Not installed (no key)
v2.0.50727   : Not installed (no key)
v1.1.4322    : Not installed (no key)
Ping         : True
Error        :

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pakrym** [comment]
Hm, `System.Text.Json` should be bundled next to your app.exe. How are you publishing and starting the application?

**Comment by penihel** [comment]
hi,

so if "System.Text.Json should be bundled next to your app.exe".
then "System.Text.Json" must be an explicit dependency

I use "Azure.Storage.Blobs" in asp.net 4.8 project, running in IIS 1.0

When i publish de project, there is no "System.Text.Json" assembly, unless I explicitly install the "System.Text.Json" package from nuget.


But, the error ocorrors just if the .net 3.5 is not installed.

Im my production server, there is no .net 3.5. 

So I am required to explicitly install the "System.Text.Json" package.

and i dont think this is the expected behavior

**Comment by pakrym** [comment]
>then "System.Text.Json" must be an explicit dependency

It is a transitive dependency. Azure.Storage.Blobs -> Azure.Core -> System.Text.Json. Do you have Azure.Core dll in your output directory?

**Comment by penihel** [comment]
>It is a transitive dependency. Azure.Storage.Blobs -> Azure.Core -> System.Text.Json. Do you have Azure.Core dll in your output directory?

Yes, i do
![image](https://user-images.githubusercontent.com/1167747/144499025-5693a2c4-f177-4e0c-a3d0-48e975644cea.png)

**Comment by pakrym** [comment]
Hm, for some reason you get all the transitives but not System.Text.Json. Can you share your csproj content or a simplified version of it that results in a publish without System.Text.JSon.

**Comment by pakrym** [comment]
Are you sure 3.5 is the only difference between environments? System.Text.Json was never included in any .NET Framework distribution. Something else must be registering it in GAC

**Comment by penihel** [comment]
What I'm sure of is that when I installed .NET 3.5, it worked.

I tested it in an approval environment, and the same issue also occurred, and it was only resolved when .NET 3.5 was installed

**Comment by annelo-msft** [comment]
Closing this issue since there hasn't been activity on it for a long time.

If you're still experiencing the problem and would like to continue working toward resolution, please feel free to reopen the issue.
