### ISSUE TITLE
[Flaky Test] Flush_Blocks

### ISSUE THREAD

**Issue by JoshLove-msft** [Azure/azure-sdk-for-net#25727]
[Flush_Blocks](https://dev.azure.com/azure-sdk/public/_build/results?buildId=1232483&view=ms.vss-test-web.build-test-results-tab&runId=26441358&resultId=117637&paneView=debug)

```
Expected: 768
But was:  767


Stack trace
   at Azure.Search.Documents.Tests.BatchingTests.Flush_Blocks() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 708
   at Azure.Search.Documents.Tests.BatchingTests.Flush_Blocks() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 712
   at Azure.Search.Documents.Tests.BatchingTests.Flush_Blocks() in /Users/runner/work/1/s/sdk/search/Azure.Search.Documents/tests/Batching/BatchingTests.cs:line 712
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by JoshLove-msft** [comment]
Looks like this one has been flaky for a while - https://github.com/Azure/azure-sdk-for-net/issues/17879

**Comment by JoshLove-msft** [comment]
Marked as ignored in https://github.com/Azure/azure-sdk-for-net/pull/25927

**Comment by Mohit-Chakraborty** [comment]
I have disabled the tests for now - https://github.com/Azure/azure-sdk-for-net/commit/8c772fe103e0ba0e2b0ea6f75e6f1933f067f54f
