### ISSUE TITLE
[BUG] TableClient.GenerateSasUri throws when client is made from TableServiceClient.GetTableClient

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#25881]
### Library name and version

Azure.Data.Tables 12.3.0

### Describe the bug

I am trying to create a service SAS using `TableClient.GenerateSasUri`. It throws an error when the `TableClient` comes from `TableServiceClient.GetTableClient` but works fine when you activate the table client directly.

### Expected behavior

The service SAS should be generated. 

### Actual behavior

An exception is thrown.

```
Unhandled exception. System.InvalidOperationException: GenerateSasUri requires that this client be constructed with a credential type other than TokenCredential in order to sign the SAS token.
   at Azure.Data.Tables.TableClient.GenerateSasUri(TableSasBuilder builder)
   at Azure.Data.Tables.TableClient.GenerateSasUri(TableSasPermissions permissions, DateTimeOffset expiresOn)
   at Program.<Main>$(String[] args) in C:\Users\joelv\Desktop\AzuriteSample\AzuriteSample\Program.cs:line 7
   at Program.<Main>(String[] args)
```

### Reproduction Steps

```csharp
var tableClientA = new TableServiceClient("UseDevelopmentStorage=true");
// This next line works fine as a workaround but means you have to plumb the connection string/credential
// var tableA = new TableClient("UseDevelopmentStorage=true", "table0");
var tableA = tableClientA.GetTableClient("table0");
var tableUri = tableA.GenerateSasUri(TableSasPermissions.Read, DateTimeOffset.UtcNow.AddDays(7));
```

Maybe this is related?
![image](https://user-images.githubusercontent.com/94054/145757637-164d90f6-9cde-4a97-8b56-b1921a4a4500.png)

### Environment

```
.NET SDK (reflecting any global.json):
 Version:   6.0.100
 Commit:    9e8b04bbff

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.100\

Host (useful for support):
  Version: 6.0.0
  Commit:  4822e3c3aa

.NET SDKs installed:
  3.1.415 [C:\Program Files\dotnet\sdk]
  5.0.100 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.403 [C:\Program Files\dotnet\sdk]
  6.0.100-preview.7.21379.14 [C:\Program Files\dotnet\sdk]
  6.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0-preview.7.21378.6 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0-preview.7.21377.19 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.21 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0-preview.7.21378.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

IDE: VS 2022 17.1.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by LeaShallev** [comment]
+1 for the same problem.
