### ISSUE TITLE
[BUG] Cognitive Translator SDK fails on Mac OS: MissingMethodException

### ISSUE THREAD

**Issue by chriswendt1** [Azure/azure-sdk-for-net#25963]
### Library name and version

Cognitive-Translator SDK 1.0.0-beta 6

### Describe the bug

Compiled as .Net 5, the SDK produces following error when running on Mac OS.
Same code works fine running on Windows.

Chriss-MacBook-Air:DocTr chriswendt$ dotnet doctr.dll formats
```
**Unhandled exception. System.MissingMethodException: Method not found: 'System.Collections.Generic.IReadOnlyList`1<Azure.AI.Translation.Document.FileFormat> DocumentTranslationService.Core.DocumentTranslationService.get_FileFormats()'.**
   at DocumentTranslation.CLI.Program.<>c.<<Main>b__1_19>d.MoveNext()
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at DocumentTranslation.CLI.Program.<>c.<Main>b__1_19(CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplicationExtensions.<>c__DisplayClass8_0.<<OnExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
   at McMaster.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at DocumentTranslation.CLI.Program.Main(String[] args) in D:\Users\wendt\source\repos\DocumentTranslation\DocumentTranslation.CLI\Program.cs:line 347
```
Abort trap: 6
Chriss-MacBook-Air:DocTr chriswendt$ 

------------

Here is the client function invoking the SDK:
```
      private async Task<IReadOnlyList<FileFormat>> GetFormatsInternal()
        {
            if (String.IsNullOrEmpty(AzureResourceName)) throw new CredentialsException("name");
            for (int i = 0; i < 3; i++)
            {
                Azure.Response<IReadOnlyList<FileFormat>> result = null;
                try
                {
                    result = await documentTranslationClient.GetSupportedDocumentFormatsAsync();
                }
                catch (Azure.RequestFailedException ex)
                {
                    if (ex.Status == 401 || ex.Status == 403) throw;
                }

                if (result?.Value.Count > 0)
                {
                    Debug.WriteLine($"GetFormats: Response: {JsonSerializer.Serialize(result, new JsonSerializerOptions() { IncludeFields = true })}");
                    FileFormats = result.Value;
                    foreach (var item in result.Value)
                    {
                        foreach (string ext in item.FileExtensions)
                        {
                            Extensions.Add(ext.ToLowerInvariant());
                        }
                    }
                    OnFileFormatsUpdate?.Invoke(this, EventArgs.Empty);
                    return FileFormats;
                }
                else
                {
                    Debug.WriteLine("GetFormatsInternal: Get file formats failed.");
                    await Task.Delay(1000);
                }
            }
            return null;
        }

```

### Expected behavior

No runtime error.

### Actual behavior

Runtime error MissingMethodException

### Reproduction Steps

Invoke GetSupportedDocumentFormatsAsync of the SDK on Mac OS with .Net 5 installed.

### Environment

Mac OS X newest update, .Net 5 runtime installed.

**Comment by AlexGhiondea** [comment]
@chriswendt1 this error seems to point to an issue with this type: `DocumentTranslationService`. That type is not an Azure SDK type so I wonder if this might be a deployment/packaging issue.

Could you take a look in the deployment folder for the app and check to see if the assembly that would contain that type has the `FileFormats` property?

**Comment by chriswendt1** [comment]
Thanks for the hint. Indeed it was a version mismatch. My mistake.
Apologies for the erroneous submission.

**Comment by AlexGhiondea** [comment]
Not a problem! Glad this helped! 🙂.
