### ISSUE TITLE
Rest ClientRuntime does not retry on WebException/SocketException

### ISSUE THREAD

**Issue by dotdot2** [Azure/azure-sdk-for-net#2607]
Socket exception like these should be retried. Looks like the  RetryDelegatingHandler does not handle this case.

Exception Type: System.Net.WebException
Status: ReceiveFailure
Ex
ception Type: System.Net.Sockets.SocketException
ErrorCode: 10054
SocketErrorCode: ConnectionReset
NativeErrorCode: 10054

Type: System.Net.Http.HttpRequestException
Message: An error occurred while sending the request.
ToString: System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a receive. ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host. ---> System.Net.Sockets.SocketException: An existing connection was forcibly closed by the remote host
   at System.Net.Sockets.NetworkStream.EndRead(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.Security._SslStream.EndRead(IAsyncResult asyncResult)
   at System.Net.TlsStream.EndRead(IAsyncResult asyncResult)
   at System.Net.Connection.ReadCallback(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
   at MyNamespace.RequestTracingHandler.<SendAsync>d__0.MoveNext() in D:\bt\787201\repo\src\Components\IdentityManager\ResourceProviders\RequestTracingHandler.cs:line 38
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.ResourcesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__10.MoveNext()
   at Microsoft.Azure.Management.ResourceManager.ResourcesOperationsExtensions.<CreateOrUpdateAsync>d__11.MoveNext()

**Comment by twitchax** [comment]
Application code should decide which errors are amenable to a retry: closing as won't fix.

**Comment by dotdot2** [comment]
This is not good design. Client runtime library must retry transport exceptions. moreover it must wrap lower level exceptions into client runtime e exceptions.


Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by twitchax** [comment]
> moreover it must wrap lower level exceptions into client runtime e exceptions.

We make a point of _not_ wrapping lower level exceptions so as to not introduce unnecessary exception obfuscation.

> This is not good design. Client runtime library must retry transport exceptions.

A client runtime library may choose which transport exceptions make sense to retry by default.  As a low-level management API, we do note plan on adding retry logic for transport exceptions encountered due to possible network failures.

@selvasingh, might this retry logic be a good candidate for fluent APIs since they are higher level?
