### ISSUE TITLE
[FormRecognizer] RecognizeCustomFormsOperationCanPollFromNewObject failing intermittently in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#26134]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Invalid model created with ID bfad8f96-3f97-400e-a03d-0fdd307aa65a
> Status: 200 (OK)
> ErrorCode: 3013
> 
> Additional Information:
> error-0: 3013: Operation exceeded maximum processing time.
> 
> Content:
> 
> Headers:
> ms-azure-ai-errorcode: REDACTED
> x-envoy-upstream-service-time: 38
> apim-request-id: 07147a7d-807e-4bf9-ad21-f8a3f3a64574
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Fri, 31 Dec 2021 06:11:22 GMT
> Content-Length: 268
> Content-Type: application/json; charset=utf-8
> 
> Data:
> error-0: 3013: Operation exceeded maximum processing time.
> 
> 
> Stack trace
>    at Azure.Core.OperationInternalBase.ApplyStateAsync(Boolean async, Response response, Boolean hasCompleted, Boolean hasSucceeded, RequestFailedException requestFailedException, Boolean throwIfFailed) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 207
>    at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 191
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 173
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 80
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 142
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 167
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 145
>    at Azure.AI.FormRecognizer.Training.CreateCustomFormModelOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormTrainingClient/CreateCustomFormModelOperation.cs:line 73
>    at Azure.AI.FormRecognizer.Tests.DisposableTrainedModel.TrainModelAsync(FormTrainingClient trainingClient, Uri trainingFilesUri, Boolean useTrainingLabels, String modelName) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Infrastructure/DisposableTrainedModel.cs:line 56
>    at Azure.AI.FormRecognizer.Tests.FormRecognizerLiveTestBase.CreateDisposableTrainedModelAsync(Boolean useTrainingLabels, ContainerType containerType, String modelName) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/Infrastructure/FormRecognizerLiveTestBase.cs:line 131
>    at Azure.AI.FormRecognizer.Tests.FormRecognizerOperationsLiveTests.RecognizeCustomFormsOperationCanPollFromNewObject() in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/FormRecognizerModels/FormRecognizerOperationsLiveTests.cs:line 100
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1269748&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Given the age of this issue, I'm going to close it as stale.  If tests continue to fail, please file a new issue.

**Comment by kinelski** [comment]
Opened https://github.com/Azure/azure-sdk-for-net/issues/29343 with more info.
