### ISSUE TITLE
[BUG] VM Creation from Gallery Image fails

### ISSUE THREAD

**Issue by Kolky** [Azure/azure-sdk-for-net#26210]
### Library name and version

Microsoft.Azure.Management.Fluent, 1.38.0

### Describe the bug

I'm trying to create a VM in C# with the Fluent API using a VM Gallery Image. Note that I verified all resources exist!

```
            var galleryImage = await azure.GalleryImages.GetByGalleryAsync(resourceGroup.Name, "..", "..", cancellationToken);
            var galleryImageLatestVersion = galleryImage.ListVersions()
                .OrderByDescending(x => Version.Parse(x.Name))
                .FirstOrDefault();

            var virtualMachine = await azure.VirtualMachines.Define("..")
                .WithRegion(region)
                .WithExistingResourceGroup(resourceGroup)
                .WithExistingPrimaryNetworkInterface(networkInterface)
                .WithWindowsGalleryImageVersion(galleryImageLatestVersion!.Id)
                .WithAdminUsername("..")
                .WithAdminPassword("..")
                .WithSize(VirtualMachineSizeTypes.StandardD2sV3)
                .CreateAsync(cancellationToken);
```

### Expected behavior

The VM is created.

### Actual behavior

I get an exception:

```
Microsoft.Rest.Azure.CloudException: Parameter 'osProfile' is not allowed.
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String vmName, VirtualMachineInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String vmName, VirtualMachineInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperationsExtensions.CreateOrUpdateAsync(IVirtualMachinesOperations operations, String resourceGroupName, String vmName, VirtualMachineInner parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineImpl.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IResourceCreator<IResourceT>.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.ExecuteNodeTaskAsync(DAGNode`1 node, CancellationToken cancellationToken)
   at HolodeckPortal.Server.Services.VmService.CreateVmTask(VmDetails vmDetails, CancellationToken cancellationToken) in C:\Users\kolka\source\repos\HolodeckPortal\Server\Services\VmService.cs:line 121
   at HolodeckPortal.Server.BackgroundTaskQueueServiceHost.ExecuteAsync(CancellationToken stoppingToken) in C:\Users\kolka\source\repos\HolodeckPortal\Server\BackgroundTaskQueueService.cs:line 54
```

### Reproduction Steps

See code above.

### Environment

ASP.NET Core 6.0 app hosted in Azure App Service on Linux.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@Kolky the Microsoft.Azure.Management.Fluent is going to retired soon, would you like to try it by using the new sdk https://www.nuget.org/packages/Azure.ResourceManager.Compute/1.0.0-beta.5
@weidongxu-microsoft please take look this fluent issue and check if this is sdk issue or service issue

**Comment by weidongxu-microsoft** [comment]
Fluent SDK is in maintenance mode and will not add new feature. Please check the new SDK refed by Arthur in above comment.

**Comment by Kolky** [comment]
Ok, too bad. I liked they way it looked in code. But I guess it was not very flexible as the new one which allows Linq e.d.

Tried the library @ArthurMa1978 suggested, that works! Thanks!
