### ISSUE TITLE
[BUG] Resource creation fails with Status 400 MissingApiVersionParameter

### ISSUE THREAD

**Issue by phmcder** [Azure/azure-sdk-for-net#26234]
### Library name and version

Azure.ResourceManager.Resources 1.0.0-beta.5

### Describe the bug

I am testing the creation of resources by creating a new `microsoft.managedidentity/userAssignedIdentities` resource as an exmaple.  

The creation call is to `Azure.ResourceManager.Resources.GenericResourceCollection.CreateOrUpdateAsync()`

The resource is being created successfully but if I set the `waitForCompletion: true` then the operation returns a 400 (Bad Request) with ErrorCode of MissingApiVersionParameter

After doing some test debugging I have found the issue relates to the value of _nextRequestUri being set in the class `Azure.Core .NextLinkOperationImplementation`. In the function `GetHeaderSource`, the `nextRequestUri` is being set to the absolute value of the requestUri, stripping the QuaryParameters including the `api-version`, causing the exception when finally called. 
`nextRequestUri = requestUri.AbsoluteUri;`

I can't see a workaround for this issue (apart from not waiting)  but also have no idea what impact making a change at this low level would have.

Any Ideas? 

### Expected behavior

Resource creation succeeds with status 200

### Actual behavior

An exception is thrown when requesting the status of the resource generation

`<Azure.RequestFailedException: The api-version query parameter (?api-version=) is required for all requests.
Status: 400 (Bad Request)
ErrorCode: MissingApiVersionParameter

Content:
{"error":{"code":"MissingApiVersionParameter","message":"The api-version query parameter (?api-version=) is required for all requests."}}

   at Azure.Core.OperationInternalBase.ApplyStateAsync(Boolean async, Response response, Boolean hasCompleted, Boolean hasSucceeded, RequestFailedException requestFailedException, Boolean throwIfFailed) in C:\azure-sdk-for-net2\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 207
   at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in C:\azure-sdk-for-net2\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 191
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in C:\azure-sdk-for-net2\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 173
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in C:\azure-sdk-for-net2\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 80
   at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in C:\azure-sdk-for-net2\sdk\core\Azure.Core\src\Shared\OperationInternalBase.cs:line 142
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in C:\azure-sdk-for-net2\sdk\core\Azure.Core\src\Shared\OperationInternalOfT.cs:line 167
   at Azure.Core.OperationOrResponseInternals`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken) in C:\Users\pmcdermott\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20211228.3\content\Generator.Shared\OperationOrResponseInternalsOfT.cs:line 63
   at Azure.Core.OperationOrResponseInternals`1.WaitForCompletionAsync(CancellationToken cancellationToken) in C:\Users\pmcdermott\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20211228.3\content\Generator.Shared\OperationOrResponseInternalsOfT.cs:line 56
   at Azure.ResourceManager.Resources.GenericResourceCollection.CreateOrUpdateAsync(String resourceId, GenericResourceData parameters, Boolean waitForCompletion, CancellationToken cancellationToken) in C:\azure-sdk-for-net2\sdk\resourcemanager\Azure.ResourceManager\src\Resources\PseudoGenerated\GenericResourceCollection.cs:line 356`

### Reproduction Steps

The exception only throws when creating the resource, not during Gets. Make sure to delete between attempts

`string rgName = "myRgName";
string msiName = "myMsiName";

Location location = Location.WestUS2;
ResourceType MSIType = new ResourceType("microsoft.managedidentity/userAssignedIdentities");

ArmClientOptions armOptions = new ArmClientOptions();
armOptions.ApiVersions.SetApiVersion(MSIType, "2018-11-30");

ArmClient armClient = new ArmClient(new DefaultAzureCredential(), armOptions);
Subscription subscription = await armClient.GetDefaultSubscriptionAsync();
ResourceGroupCollection rgCollection = subscription.GetResourceGroups();

ResourceGroupCreateOrUpdateOperation lro = await rgCollection.CreateOrUpdateAsync(rgName, new ResourceGroupData(location));
ResourceGroup resourceGroup = lro.Value;
GenericResourceCollection grCollection = subscription.GetGenericResources();

string resourceId = $"{resourceGroup.Id}/providers/{MSIType}/{msiName}";
GenericResourceData resource = new GenericResourceData(location);
ResourceCreateOrUpdateByIdOperation op = await grCollection.CreateOrUpdateAsync(resourceId, resource, waitForCompletion: true);`

### Environment

dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.101\

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  2.2.207 [C:\Program Files\dotnet\sdk]
  3.1.404 [C:\Program Files\dotnet\sdk]
  5.0.102 [C:\Program Files\dotnet\sdk]
  5.0.402 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.8 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 3.1.20 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.2 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
This could be related to https://github.com/Azure/azure-sdk-for-net/issues/25411 and a fix is in  progress.
