### ISSUE TITLE
[BUG] Importing certificates into Azure KeyVault fails due to no private key even when private key exists (C#)

### ISSUE THREAD

**Issue by shahriak** [Azure/azure-sdk-for-net#26492]
### Library name and version

Azure.Security.KeyVault.Certificates 4.2.0

### Describe the bug

I'm trying to import a self-signed certificate into KeyVault. When I do, it fails with a 400 BadRequest error and the message:       "Azure.RequestFailedException: No certificate with private key found in the specified X.509 certificate content. Please specify X.509 certificate content with only one certificate containing private key."

### Expected behavior

The import should be successful as I have debugged and checked that the HasPrivateKey field is true and the Private key exists

### Actual behavior

Logs:
```
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/2 GET https://localhost:5001/api/values - - - 404 0 - 57.9879ms
fail: CCP.PTT.TrustDomainService.Filters.TrustDomainServiceExceptionFilterAttribute[0]
      Encountered an unhandled exception
      Azure.RequestFailedException: No certificate with private key found in the specified X.509 certificate content. Please specify X.509 certificate content with only one certificate containing private key.
      Status: 400 (Bad Request)
      ErrorCode: BadParameter

      Content:
      {"error":{"code":"BadParameter","message":"No certificate with private key found in the specified X.509 certificate content. Please specify X.509 certificate content with only one certificate containing private key."}}

      Headers:
      Cache-Control: no-cache
      Pragma: no-cache
      x-ms-keyvault-region: westus2
      x-ms-client-request-id: ee74452f-c31b-44f6-8320-579c0284e120
      x-ms-request-id: a630ea5b-7c4a-404a-80d0-4cb6aa159e8b
      x-ms-keyvault-service-version: 1.9.264.1
      x-ms-keyvault-network-info: conn_type=Ipv4;addr=1.1.1.1;act_addr_fam=InterNetwork;
      X-Powered-By: REDACTED
      Strict-Transport-Security: REDACTED
      X-Content-Type-Options: REDACTED
      Date: Thu, 20 Jan 2022 02:17:04 GMT
      Content-Length: 218
      Content-Type: application/json; charset=utf-8
      Expires: -1

         at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
         at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TContent,TResult](RequestMethod method, TContent content, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
         at Azure.Security.KeyVault.Certificates.CertificateClient.ImportCertificateAsync(ImportCertificateOptions importCertificateOptions, CancellationToken cancellationToken)
         at CCP.PTT.TrustDomainService.Data.Infrastructure.KeyVaultX509CertificateRepository.SaveAsync(String name, X509Certificate2Collection collection) in C:\Repos\Commerce.TrustDomainService\CCP.PTT.TrustDomainService.Data.Infrastructure\KeyVaultX509CertificateRepository.cs:line 133
         at CCP.PTT.TrustDomainService.Data.Certificates.MeshCertificateService.MintRootCertificateAsync(String rootName) in C:\Repos\Commerce.TrustDomainService\CCP.PTT.TrustDomainService.Data\Certificates\MeshCertificateService.cs:line 135
         at CCP.PTT.TrustDomainService.Controllers.RootCertificatesController.PostAsync(String rootName) in C:\Repos\Commerce.TrustDomainService\CCP.PTT.TrustDomainService\Controllers\Roots\Certificates\RootCertificatesController.cs:line 143
         at lambda_method468(Closure , Object )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
info: Microsoft.AspNetCore.Mvc.Infrastructure.SystemTextJsonResultExecutor[1]
      Executing JsonResult, writing value of type 'Microsoft.RestApi.Model.ApiError'.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action CCP.PTT.TrustDomainService.Controllers.RootCertificatesController.PostAsync (CCP.PTT.TrustDomainService) in 22112.2216ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'CCP.PTT.TrustDomainService.Controllers.RootCertificatesController.PostAsync (CCP.PTT.TrustDomainService)'
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished HTTP/1.1 POST https://localhost:5001/roots/commerce-mesh-osm/certificates/ application/json 0 - 500 - application/json;+charset=utf-8 23461.3218ms
```

### Reproduction Steps

I am using the below code in C# to generate the self-signed certificate:

```
                using RSA rsa = RSA.Create(keySize);
                rsa.ExportParameters(true);

                CertificateRequest certificateRequest = new CertificateRequest(subjectName, rsa, HashAlgorithmName.SHA256, RSASignaturePadding.Pkcs1);

                certificateRequest.CertificateExtensions.Add(
                    new X509BasicConstraintsExtension(true, false, 0, true));

                // subject key identifier must NOT be marked critical: https://www.ietf.org/rfc/rfc3280.txt
                certificateRequest.CertificateExtensions.Add(
                    new X509SubjectKeyIdentifierExtension(certificateRequest.PublicKey, false));

                certificateRequest.CertificateExtensions.Add(
                    new X509KeyUsageExtension(
                        X509KeyUsageFlags.KeyCertSign |
                        X509KeyUsageFlags.CrlSign,
                        true));

                X509Certificate2 c = certificateRequest.CreateSelfSigned(NotBefore, expirationDate);
                return c;
```

// Code to import certificate onto AKV:

```
        public async Task SaveAsync(string name, X509Certificate2Collection collection)
        {
            if (string.IsNullOrWhiteSpace(name))
            {
                throw new NullOrWhitespaceBadArgumentException(nameof(name));
            }

            if (collection == null)
            {
                throw new NullOrWhitespaceBadArgumentException(nameof(collection));
            }

            byte[] certificate = null;
            foreach (X509Certificate2 x509 in collection)
            {
                certificate = x509?.RawData;
            }

            if (certificate == null || certificate.Length < 1)
            {
                throw new ArgumentNullException(nameof(certificate));
            }

            ImportCertificateOptions options = new ImportCertificateOptions(name, certificate);
            await this.keyVaultClient.CertificateClient.ImportCertificateAsync(options);
        }

```
### Environment

Visual Studio 16.11.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The output from `X509Certificate2.RawData` does not include the private key. Instead, you'll want to use `X509Certificate2.Export(X509CertificateType.Pkcs12)`.

I can update the docs for `Import` with an example if you think that would help.
