### ISSUE TITLE
[communication service ] : Identity sdk call failed to run in a custom .net framework 4.6.1appDomain aside with .net framework 4.5.2 asp.net app.

### ISSUE THREAD

**Issue by chrisAlio** [Azure/azure-sdk-for-net#26513]
**Library name and version**
Azure.Communication.Identity 1.0.1

**Describe the bug**
Environment: .net framework 4.5.2 asp.net application calls sdk api, CreateUserAsync(), which wrapped in a custom .net framework 4.6.1 appDomain object, the side-by-side approach.  The api execution in the sandbox appDomin failed with error:  ` ---> Azure.RequestFailedException: The underlying connection was closed: An unexpected error occurred on a send.`

The code was developed with C# 5 within .net framework 4.5.2 in VS2019 professional. OS is Windows10.

**Expected behavior**
It was expected to work

**Actual behavior:**
```text
Message: 
    Test method InsideAllphaseTests.Util.ACSClient.ACSCallerTests.TestCreateUserCallId_ReturnsTrue threw exception: 
    System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.AggregateException: One or more errors occurred. ---> System.AggregateException: Retry failed after 4 tries. ---> Azure.RequestFailedException: The underlying connection was closed: An unexpected error occurred on a send.
  Stack Trace: 
    <ProcessInternal>d__7.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <ProcessAsync>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <ProcessAsync>d__5.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <ProcessAsync>d__3.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    ValueTask.ThrowIfCompletedUnsuccessfully()
    <ProcessAsync>d__11.MoveNext()
     --- End of inner exception stack trace ---
    <ProcessAsync>d__11.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <CreateAsync>d__6.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    <CreateUserAsync>d__14.MoveNext()
    --- End of stack trace from previous location where exception was thrown ---
    TaskAwaiter.ThrowForNonSuccess(Task task)
    TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
    TaskAwaiter`1.GetResult()
    <<CreateUserIdentity>b__6_0>d.MoveNext()
     --- End of inner exception stack trace ---
    Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
    Task`1.GetResultCore(Boolean waitCompletionNotification)
    Task`1.get_Result()
    **ACSCallClient.CreateUserIdentity()**
     --- End of inner exception stack trace ---
    RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
    RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
    RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
    MethodBase.Invoke(Object obj, Object[] parameters)
    ACSCaller.CreateUserCallId()
    ACSCallerTests.TestCreateUserCallId_ReturnsTrue() line 16
```
Reproduction Steps
```csharp
 public string CreateUserIdentity()
{
            try
            {
                // Create an identity
                Task<Azure.Response<CommunicationUserIdentifier>> task = Task.Run<Azure.Response<CommunicationUserIdentifier>>(async () => await client.CreateUserAsync());
                var identity = task.Result.Value;

                return identity.Id;
            }
            catch
            {
                throw;
            }
  }
```
see description

**Comment by chrisAlio** [comment]
Tested a bit more, it seems that if I wrapped these function calls in a Class Library/.dll for other layer of application to consume, then I got this connection closed error when call the functions in the dll, here is bit more information:
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
   at Azure.Communication.Identity.CommunicationIdentityRestClient.Create(IEnumerable`1 createTokenWithScopes, CancellationToken cancellationToken)
   at Azure.Communication.Identity.CommunicationIdentityClient.**CreateUse**r(CancellationToken cancellationToken)
   at InsideAllphase.ACS.CallClient.ACSCallClient.CreateUserIdentity()
   at InsideAllphaseTests.Util.ACSClient.ACSCallerTests.TestCreateUserCallId_ReturnsTrue() in C:\TFS\dev\2022.02\IALib\InsideAllphase\InsideAllphaseTests\Util\ACSClient\ACSCallerTests.cs:line 16

Did I missed anything ?

**Comment by chrisAlio** [comment]
A bit more info.

  at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at InsideAllphase.ACS.CallClient.ACSCallClient.CreateUserIdentity()
   at InsideAllphase.Util.ACSClientNS.ACSCaller.CreateUserCallId() in ....\Util\ACSClient\ACSCaller.cs:line 34
   at InsideAllphaseTests.Util.ACSClient.ACSCallerTests.TestCreateUserCallId_ReturnsTrue() in ......\Util\ACSClient\ACSCallerTests.cs:line 16

The code works if not wrapped by Class Library.
