### ISSUE TITLE
[BUG] VaultCollection.CreateOrUpdate got JSON exception

### ISSUE THREAD

**Issue by hachiang-msft** [Azure/azure-sdk-for-net#26526]
### Library name and version

Azure.ResourceManager.KeyVault 1.0.0-beta.5

### Describe the bug

Get json parsing exception when send CreateOrUpdate to a existed vault.
Exception message:
```
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.
```
StackTrace
```
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at Azure.ResourceManager.KeyVault.Models.VaultCreateOrUpdateOperation.Azure.Core.IOperationSource<Azure.ResourceManager.KeyVault.Vault>.CreateResultAsync(Response response, CancellationToken cancellationToken)
   at Azure.Core.OperationInternals`1.Azure.Core.IOperation<T>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(TimeSpan pollingInterval, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(TimeSpan pollingInterval, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken)
```

### Expected behavior

Should be success or other clear error message

### Actual behavior

Failed when getting operation state

### Reproduction Steps

```
            var vaults = resourceGroup.GetVaults();
            var properties = new VaultProperties(new Guid(TestConfiguration.SapSPTenantId), new global::Azure.ResourceManager.KeyVault.Models.Sku(SkuFamily.A, SkuName.Standard))
            {
                EnabledForDeployment = true,
                EnablePurgeProtection = true
            };
            properties.AccessPolicies.Add(new AccessPolicyEntry(
                new Guid(TestConfiguration.SapSPTenantId),
                TestConfiguration.SapSPObjectId,
                new Permissions
                {
                    Keys = { new KeyPermissions("all") },
                    Secrets = { new SecretPermissions("all") }
                }));
            var parameters = new VaultCreateOrUpdateParameters(region, properties);
            Vault v = null;
            try
            {
                v = vaults.CreateOrUpdate(resourceName, parameters).WaitForCompletionAsync().Result.Value;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
            }
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Yao725** [comment]
Hey @hachiang-msft , the method `CreateOrUpdate` has a parameter named `waitForCompletion` which controls the behavior to call or not call `WaitForCompletion` inside the method. And in 1.0.0-beta.5 this parameter is set to `true` by default, so you don't need  to call `WaitForCompletion` by yourself.

I think here are two options to change the code, one is:
```csharp
v = vaults.CreateOrUpdate(resourceName, parameters).Value
```

And another is:
```csharp
v = vaults.CreateOrUpdate(resourceName, parameters, false).WaitForCompletionAsync().Result.Value;
```

**Comment by hachiang-msft** [comment]
Hi @Yao725,
Your solution works, thanks a lot.

I also have a similar issue when working with GenericResource and 2 options you mentioned still getting same exception.
Since current GitHub issue is created for KeyVault package, please let me know whether I need create another issue for different package or it's okay to redirect this issue.

```
var resource = this.subscription.GetGenericResources().Get(GetCogSvcResouceId(accountName, resourceGroupName)).Value;
            
var data = new GenericResourceData(location)
{
    Properties = new JsonObject() {{
        "encryption", new JsonObject()
        {
            {"keySource", "Microsoft.KeyVault"},
            {"keyVaultProperties", new JsonObject(){
                { "keyName", keyName},
                { "keyVaultUri", vaultUri},
                { "keyVersion", keyVersion}
            }},
        }}}
};

return resource.Update(data).Value;
```
Exception looks similar.
```
Message:
The input does not contain any JSON tokens. Expected the input to start with a valid JSON token, when isFinalBlock is true. LineNumber: 0 | BytePositionInLine: 0.

Stack:
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(Stream utf8Json, JsonDocumentOptions options)
   at Azure.ResourceManager.Resources.Models.ResourceUpdateByIdOperation.Azure.Core.IOperationSource<Azure.ResourceManager.Resources.GenericResource>.CreateResult(Response response, CancellationToken cancellationToken)
   at Azure.Core.OperationInternals`1.Azure.Core.IOperation<T>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.UpdateStateAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken)
   at Azure.Core.OperationOrResponseInternals.UpdateStatus(CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.Models.ResourceUpdateByIdOperation.UpdateStatus(CancellationToken cancellationToken)
   at Azure.ResourceManager.Core.ResourceManagerExtensions.WaitForCompletion[T](Operation`1 operation, TimeSpan pollingInterval, CancellationToken cancellationToken)
   at Azure.ResourceManager.Core.ResourceManagerExtensions.WaitForCompletion[T](Operation`1 operation, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.GenericResource.Update(GenericResourceData parameters, Boolean waitForCompletion, CancellationToken cancellationToken)
   at Microsoft.CognitiveServices.ResourceProvisioning.Tests.Helpers.AzureResourceHelper.SetCogSvcCmk(String keyName, String keyVersion, String vaultUri, String accountName, String resourceGroupName, String location) in D:\Repos\API-Face-RPE\src\RpExtension.EndToEndTests\AzureResourceHelper.cs:line 139
```
I'm using `Azure.ResourceManager 1.0.0-beta.7`

**Comment by Yao725** [comment]
@hachiang-msft , no need to create a new issue and I will take a look at what happened, thanks!

**Comment by Yao725** [comment]
Hey @hachiang-msft , unfortunately I can't repro your issue, the set of cognitive service encryption requires enabling customer-managed keys feature which my test sub doesn't support now. 

I'm wondering if you could provide me with the detailed Https log. Here is the sample code that forwards the log to the console.
```csharp
using Azure.Identity;
using Azure.ResourceManager;
using Azure.Core.Diagnostics;
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger(EventLevel.Verbose);
ArmClientOptions options = new ArmClientOptions()
{
    Diagnostics =
    {
        IsLoggingContentEnabled = true
    }
};
ArmClient armClient = new ArmClient(new DefaultAzureCredential(), options);
```

**Comment by hachiang-msft** [comment]
Hi @Yao725 

Please refer to following log

```
[Informational] Azure-Core: Request [23e3cba9-8385-4d04-95e3-e56f7577586f] PATCH https://management.azure.com/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/resourceGroups/cmk-test/providers/Microsoft.CognitiveServices/accounts/cmkdev6eceaaf060-cogSvc?api-version=REDACTED
Accept:REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Authorization:REDACTED
Content-Type:REDACTED
client assembly: Azure.ResourceManager
[Verbose] Azure-Core: Request [23e3cba9-8385-4d04-95e3-e56f7577586f] content: {"properties":{"encryption":{"keySource":"Microsoft.KeyVault","keyVaultProperties":{"keyName":"cmkdev6eceaaf060-cogSvc","keyVaultUri":"https://cmkdev6eceaaf060-kv.vault.azure.net/","keyVersion":"a4678ae405b442de9aaded5e0aa33921"}}},"location":"eastus2euap"}
[Informational] Azure-Core: Response [23e3cba9-8385-4d04-95e3-e56f7577586f] 202 Accepted (03.3s)
Cache-Control:REDACTED
Pragma:REDACTED
ETag:REDACTED
Location:REDACTED
X-Content-Type-Options:REDACTED
x-ms-request-id:REDACTED
azure-asyncoperation:REDACTED
x-envoy-upstream-service-time:REDACTED
Server:REDACTED
x-ms-ratelimit-remaining-subscription-writes:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-routing-request-id:REDACTED
Strict-Transport-Security:REDACTED
Date:REDACTED
Content-Length:REDACTED
Content-Type:REDACTED
Expires:REDACTED

[Verbose] Azure-Core: Response [23e3cba9-8385-4d04-95e3-e56f7577586f] content: {"id":"/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/resourceGroups/cmk-test/providers/Microsoft.CognitiveServices/accounts/cmkdev6eceaaf060-cogSvc","name":"cmkdev6eceaaf060-cogSvc","type":"Microsoft.CognitiveServices/accounts","etag":"\"4001b55d-0000-3400-0000-620ccbf90000\"","location":"eastus2euap","sku":{"name":"E0"},"kind":"Face","tags":{"owner":"faceapi"},"properties":{"endpoint":"https://eastus2euap.api.cognitive.microsoft.com/","provisioningState":"Accepted","internalId":"05b8a7db3b8f43abbac5b63e9a38218d","dateCreated":"2022-02-16T10:01:24.9440048Z","callRateLimit":{"rules":[{"key":"face","renewalPeriod":1,"count":15,"dynamicThrottlingEnabled":false,"matchPatterns":[{"path":"face/*","method":"*"}]},{"key":"container.billing","renewalPeriod":10,"count":500,"dynamicThrottlingEnabled":false,"matchPatterns":[{"path":"billing/*","method":"*"}]},{"key":"default","renewalPeriod":1,"count":15,"dynamicThrottlingEnabled":false,"matchPatterns":[{"path":"*","method":"*"}]}]},"isMigrated":false,"encryption":{"keySource":"Microsoft.KeyVault","keyVaultProperties":{"keyName":"cmkdev6eceaaf060-cogSvc","keyVersion":"a4678ae405b442de9aaded5e0aa33921","keyVaultUri":"https://cmkdev6eceaaf060-kv.vault.azure.net/"}},"privateEndpointConnections":[],"publicNetworkAccess":"Enabled","capabilities":[{"name":"VirtualNetworks"},{"name":"Container","value":"Face.*,Face.Face"},{"name":"CustomerManagedKey"}],"endpoints":{"Face":"https://eastus2euap.api.cognitive.microsoft.com/"}},"identity":{"principalId":"619e9724-5bc7-4610-8308-3baea3442cc2","tenantId":"72f988bf-86f1-41af-91ab-2d7cd011db47","type":"SystemAssigned"},"systemData":{"lastModifiedBy":"ea8aeaaa-547a-433a-8227-8bed9cd6e92c","lastModifiedByType":"Application","lastModifiedAt":"2022-02-16T10:03:37.8129656Z"}}
[Warning] Azure-Core: Response [23e3cba9-8385-4d04-95e3-e56f7577586f] took 03.3s
[Informational] Azure-Core: Request [b28d6b04-37ac-4a0e-a1f9-4ef599377749] GET https://management.azure.com/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb?api-version=REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Authorization:REDACTED
client assembly: Azure.ResourceManager
[Informational] Azure-Core: Response [b28d6b04-37ac-4a0e-a1f9-4ef599377749] 200 OK (00.2s)
Cache-Control:REDACTED
Pragma:REDACTED
X-Content-Type-Options:REDACTED
x-ms-request-id:REDACTED
x-envoy-upstream-service-time:REDACTED
Server:REDACTED
x-ms-ratelimit-remaining-subscription-reads:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-routing-request-id:REDACTED
Strict-Transport-Security:REDACTED
Date:REDACTED
Content-Length:REDACTED
Content-Type:REDACTED
Expires:REDACTED

[Verbose] Azure-Core: Response [b28d6b04-37ac-4a0e-a1f9-4ef599377749] content: {"id":"/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb","name":"dbee36d8-1cd4-4ec4-bc5c-214a354b5adb","status":"Updating","startTime":"2022-02-16T10:03:39Z"}
[Informational] Azure-Core: Request [cca8a12a-ec46-4a8d-be42-6d293bbd6ef4] GET https://management.azure.com/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb?api-version=REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Authorization:REDACTED
client assembly: Azure.ResourceManager
[Informational] Azure-Core: Response [cca8a12a-ec46-4a8d-be42-6d293bbd6ef4] 200 OK (00.2s)
Cache-Control:REDACTED
Pragma:REDACTED
X-Content-Type-Options:REDACTED
x-ms-request-id:REDACTED
x-envoy-upstream-service-time:REDACTED
Server:REDACTED
x-ms-ratelimit-remaining-subscription-reads:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-routing-request-id:REDACTED
Strict-Transport-Security:REDACTED
Date:REDACTED
Content-Length:REDACTED
Content-Type:REDACTED
Expires:REDACTED

[Verbose] Azure-Core: Response [cca8a12a-ec46-4a8d-be42-6d293bbd6ef4] content: {"id":"/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb","name":"dbee36d8-1cd4-4ec4-bc5c-214a354b5adb","status":"Updating","startTime":"2022-02-16T10:03:39Z"}
[Informational] Azure-Core: Request [ddef729b-05c7-4b3c-816c-abe7eaf4bce1] GET https://management.azure.com/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb?api-version=REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Authorization:REDACTED
client assembly: Azure.ResourceManager
[Informational] Azure-Core: Response [ddef729b-05c7-4b3c-816c-abe7eaf4bce1] 200 OK (00.2s)
Cache-Control:REDACTED
Pragma:REDACTED
X-Content-Type-Options:REDACTED
x-ms-request-id:REDACTED
x-envoy-upstream-service-time:REDACTED
Server:REDACTED
x-ms-ratelimit-remaining-subscription-reads:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-routing-request-id:REDACTED
Strict-Transport-Security:REDACTED
Date:REDACTED
Content-Length:REDACTED
Content-Type:REDACTED
Expires:REDACTED

[Verbose] Azure-Core: Response [ddef729b-05c7-4b3c-816c-abe7eaf4bce1] content: {"id":"/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb","name":"dbee36d8-1cd4-4ec4-bc5c-214a354b5adb","status":"Updating","startTime":"2022-02-16T10:03:39Z"}
[Informational] Azure-Core: Request [e1e11357-1598-480c-b356-c1162cee42b9] GET https://management.azure.com/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb?api-version=REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Authorization:REDACTED
client assembly: Azure.ResourceManager
[Informational] Azure-Core: Response [e1e11357-1598-480c-b356-c1162cee42b9] 200 OK (00.2s)
Cache-Control:REDACTED
Pragma:REDACTED
X-Content-Type-Options:REDACTED
x-ms-request-id:REDACTED
x-envoy-upstream-service-time:REDACTED
Server:REDACTED
x-ms-ratelimit-remaining-subscription-reads:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-routing-request-id:REDACTED
Strict-Transport-Security:REDACTED
Date:REDACTED
Content-Length:REDACTED
Content-Type:REDACTED
Expires:REDACTED

[Verbose] Azure-Core: Response [e1e11357-1598-480c-b356-c1162cee42b9] content: {"id":"/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb","name":"dbee36d8-1cd4-4ec4-bc5c-214a354b5adb","status":"Succeeded","startTime":"2022-02-16T10:03:39Z","endTime":"2022-02-16T10:03:43Z"}
[Informational] Azure-Core: Request [22325466-c16e-4c1c-a136-616cb807767b] GET https://management.azure.com/subscriptions/49251be0-1acb-46f1-b9ea-6221412f6e9a/providers/Microsoft.CognitiveServices/locations/eastus2euap/operationResults/dbee36d8-1cd4-4ec4-bc5c-214a354b5adb?api-version=REDACTED&operationResultResponseType=REDACTED
x-ms-client-request-id:REDACTED
x-ms-return-client-request-id:REDACTED
User-Agent:REDACTED
Authorization:REDACTED
client assembly: Azure.ResourceManager
[Informational] Azure-Core: Response [22325466-c16e-4c1c-a136-616cb807767b] 200 OK (00.2s)
Cache-Control:REDACTED
Pragma:REDACTED
X-Content-Type-Options:REDACTED
x-ms-request-id:REDACTED
x-envoy-upstream-service-time:REDACTED
Server:REDACTED
x-ms-ratelimit-remaining-subscription-reads:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-routing-request-id:REDACTED
Strict-Transport-Security:REDACTED
Date:REDACTED
Expires:REDACTED
Content-Length:REDACTED

[Verbose] Azure-Core: Response [22325466-c16e-4c1c-a136-616cb807767b] content: 
```

**Comment by Yao725** [comment]
Hi @hachiang-msft , I believe that your cognitive service account should has been updated with this request. However there is something wrong with the long running operation status update which coming from the last request in your log. You can see that the last response is empty.

Can your upgrade the version  of Azure.ResourceManager to 1.0.0-beta.8, in which we have an optimization for the long running operation logic? And FYI, in the newer version we introduced some [breaking changes](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager_1.0.0-beta.8/sdk/resourcemanager/Azure.ResourceManager/CHANGELOG.md)

Please have a try and let me know if it works, thanks!

**Comment by hachiang-msft** [comment]
No more exception from Azure.ResourceManager 1.0.0-beta.8 when updating resource successfully.

Thanks for your help!

**Comment by Yao725** [comment]
Thanks for your feedback, I will close this issue. Feel free to open a new one when you meet other issue.
