### ISSUE TITLE
[BUG] InteractiveBrowserCredential authentication failed: Persistence check failed. Data was written but it could not be read.

### ISSUE THREAD

**Issue by adriancuadrado** [Azure/azure-sdk-for-net#26552]
### Library name and version

Azure.Identity 1.5.0

### Describe the bug

When I use `InteractiveBrowserCredential`, a browser opens as expected. But when I use `DefaultAzureCredential` with `includeInteractiveCredentials: true` I get this error:
```
Unhandled exception. Azure.Identity.AuthenticationFailedException: InteractiveBrowserCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
 ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.VerifyPersistence()
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.VerifyPersistence()
   at Azure.Identity.MsalCacheHelperWrapper.VerifyPersistence()
   at Azure.Identity.TokenCache.GetCacheHelperAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.TokenCache.GetCacheHelperAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.TokenCache.RegisterCache(Boolean async, ITokenCache tokenCache, CancellationToken cancellationToken)
   at Azure.Identity.MsalClientBase`1.GetClientAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveCoreAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenViaBrowserLoginAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.ResourceManager.Resources.SubscriptionsRestOperations.ListAsync(CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.SubscriptionCollection.<>c__DisplayClass9_0.<<GetAllAsync>g__FirstPageFunc|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.ResourceManager.Core.SharedExtensions.FirstOrDefaultAsync[TSource](AsyncPageable`1 source, Func`2 predicate, CancellationToken token)
   at Azure.ResourceManager.Core.SharedExtensions.FirstOrDefaultAsync[TSource](AsyncPageable`1 source, Func`2 predicate, CancellationToken token)
   at Azure.ResourceManager.ArmClient.GetDefaultSubscriptionAsync(CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /home/adrian/temp/AZ-204/consoleApp/Program.cs:line 6
   at Program.<Main>(String[] args)
```

### Expected behavior

The browser should open and ask for my credentials.

### Actual behavior

I get this error:
```
Unhandled exception. Azure.Identity.AuthenticationFailedException: InteractiveBrowserCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
 ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheStorage.VerifyPersistence()
   at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.VerifyPersistence()
   at Azure.Identity.MsalCacheHelperWrapper.VerifyPersistence()
   at Azure.Identity.TokenCache.GetCacheHelperAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.TokenCache.GetCacheHelperAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.TokenCache.RegisterCache(Boolean async, ITokenCache tokenCache, CancellationToken cancellationToken)
   at Azure.Identity.MsalClientBase`1.GetClientAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveCoreAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenViaBrowserLoginAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.InteractiveBrowserCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.ResourceManager.Resources.SubscriptionsRestOperations.ListAsync(CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.SubscriptionCollection.<>c__DisplayClass9_0.<<GetAllAsync>g__FirstPageFunc|0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.ResourceManager.Core.SharedExtensions.FirstOrDefaultAsync[TSource](AsyncPageable`1 source, Func`2 predicate, CancellationToken token)
   at Azure.ResourceManager.Core.SharedExtensions.FirstOrDefaultAsync[TSource](AsyncPageable`1 source, Func`2 predicate, CancellationToken token)
   at Azure.ResourceManager.ArmClient.GetDefaultSubscriptionAsync(CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /home/adrian/temp/AZ-204/consoleApp/Program.cs:line 6
   at Program.<Main>(String[] args)
```

### Reproduction Steps

In WSL, create a new console application with `dotnet new console`, install these packages and run the project.

Packages:
* [Azure.Identity](https://www.nuget.org/packages/Azure.Identity)
* [Azure.ResourceManager](https://www.nuget.org/packages/Azure.ResourceManager)
* [Azure.ResourceManager.Resources](https://www.nuget.org/packages/Azure.ResourceManager.Resources)

Code:
```csharp
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;

var armClient = new ArmClient(new DefaultAzureCredential(includeInteractiveCredentials: true));
Subscription subscription = await armClient.GetDefaultSubscriptionAsync();
Console.WriteLine(subscription.Id);
```

Run the project:
```sh
dotnet run
```

PS: I am using dotnet 6.0.101

### Environment

```sh
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
I am using WSL.

VSCode version: 1.63.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @adriancuadrado 
This occurs because internally `DefaultAzureCredential` configures the persistent token cache, which requires LibSecret to be configured. As a workaround, you could construct your own credential using `ChainedTokenCredential`. https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#define-a-custom-authentication-flow-with-the-chainedtokencredential

**Comment by adriancuadrado** [comment]
Dumb question: How do I configure LibSecret?

**Comment by christothes** [comment]
> Dumb question: How do I configure LibSecret?

I couldn't tell you 😄 I've never configured it myself. My guess is that you have to setup D-Bus though based on the error message.  Does `ChainedTokenCredential` work for you though?

**Comment by adriancuadrado** [comment]
According to [this documentation](https://docs.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet) _DefaultAzureCredential_ attempts these credential types in order:
* EnvironmentCredential
* ManagedIdentityCredential
* SharedTokenCacheCredential
* VisualStudioCredential
* VisualStudioCodeCredential
* AzureCliCredential
* AzurePowerShellCredential
* InteractiveBrowserCredential
I tried this code to attempt the same with _ChainedTokenCredential_, but when it tries _ManagedIdentityCredential_ it gets stuck forever. If I remove _ManagedIdentityCredential_ from the list of credential types to attempt from the _ChainedTokenCredential_, it correctly opens the web browsers, but then I get the same error I get here: https://github.com/Azure/azure-sdk-for-net/issues/26553

This is the code I used with _ChainedTokenCredential_:
```csharp
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;

var armClient = new ArmClient(
    new ChainedTokenCredential(
        new TokenCredential[]{
            new EnvironmentCredential(),
            // new ManagedIdentityCredential(),
            new SharedTokenCacheCredential(),
            new VisualStudioCredential(),
            new VisualStudioCodeCredential(),
            new AzureCliCredential(),
            new AzurePowerShellCredential(),
            new InteractiveBrowserCredential()
        }
    )
);
Subscription subscription = await armClient.GetDefaultSubscriptionAsync();
Console.WriteLine(subscription.Id);
```

**Comment by adriancuadrado** [comment]
If it **is** a requirement for the _DefaultAzureCredential_ to work to have LibSecret configured, shouldn't this be mentioned in the documentation? It wouldn't make sense however, because what does _DefaultAzureCredential_ have that my _ChainedTokenCredential_ in the previous comment doesn't to have it asking for LibSecret to be configured? If my _ChainedTokenCredential_ didn't ask for it, _DefaultAzureCredential_ shouldn't have to ask for it too. If _DefaultAzureCredential_ needs it, my _ChainedTokenCredential_ should need it too.

Conclusion: Even if you can use _ChainedTokenCredential_ as a workaround, IMHO there must be a bug over here that needs some fixing.

**Comment by christothes** [comment]
> If it **is** a requirement for the _DefaultAzureCredential_ to work to have LibSecret configured, shouldn't this be mentioned in the documentation? It wouldn't make sense however, because what does _DefaultAzureCredential_ have that my _ChainedTokenCredential_ in the previous comment doesn't to have it asking for LibSecret to be configured? If my _ChainedTokenCredential_ didn't ask for it, _DefaultAzureCredential_ shouldn't have to ask for it too. If _DefaultAzureCredential_ needs it, my _ChainedTokenCredential_ should need it too.
> 
> Conclusion: Even if you can use _ChainedTokenCredential_ as a workaround, IMHO there must be a bug over here that needs some fixing anyways.

The difference is that `DefaultAzureCredential` configures the token cache by default, which requires LibSecret to protect the cache on disk.

I agree that there is a bug here, and I created and linked #26575 to track this. I'll go ahead and close this issue if the only remaining issue is represented in #26553 .
