### ISSUE TITLE
[BUG] System.InvalidOperationException: No subscriptions found for the given credentials

### ISSUE THREAD

**Issue by adriancuadrado** [Azure/azure-sdk-for-net#26553]
### Library name and version

Azure.ResourceManager.Resources 1.0.0-beta.5

### Describe the bug

My program reports an error saying that I don't have subscriptions, but I do have a subscription.

### Expected behavior

My program should print the Id of my subscription.

### Actual behavior

It reports an error saying that I don't have subscriptions, but I do have a subscription.
```
Unhandled exception. System.InvalidOperationException: No subscriptions found for the given credentials
   at Azure.ResourceManager.ArmClient.GetDefaultSubscriptionAsync(CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in /home/adrian/temp/AZ-204/consoleApp/Program.cs:line 6
   at Program.<Main>(String[] args)
```

### Reproduction Steps

1. Create a new console project with `dotnet new console`
1. Add the following NuGet packages:
    * [Azure.Identity](https://www.nuget.org/packages/Azure.Identity)
    * [Azure.ResourceManager](https://www.nuget.org/packages/Azure.ResourceManager)
    * [Azure.ResourceManager.Resources](https://www.nuget.org/packages/Azure.ResourceManager.Resources)
1. Copy and paste this code:
```csharp
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;

var armClient = new ArmClient(new InteractiveBrowserCredential());
Subscription subscription = await armClient.GetDefaultSubscriptionAsync();
Console.WriteLine(subscription.Id);
```

This command demonstrates that I have multiple subscriptions:
```
$ az account list --all --query '[].{isDefault: isDefault, name: name, state: state}'
[
  {
    "isDefault": false,
    "name": "Pase para Azure: patrocinio",
    "state": "Disabled"
  },
  {
    "isDefault": true,
    "name": "Pase para Azure: patrocinio",
    "state": "Enabled"
  }
]
```
I think the problem must be with `InteractiveBrowserCredential`, because when I use `DefaultAzureCredential` instead and I execute `dotnet run` in the same terminal I executed `az login` I get the subscription id without problems.

### Environment

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.101
 Commit:    ef49f6213a

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  20.04
 OS Platform: Linux
 RID:         ubuntu.20.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.101/

Host (useful for support):
  Version: 6.0.1
  Commit:  3a25a7f1cc

.NET SDKs installed:
  6.0.101 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.1 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```
I am using WSL.
VSCode version: 1.63.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@adriancuadrado did you get browser popup and say 'Authentication complete. You can return to the application. Feel free to close this browser tab.' ?
I can't repo this issue in my machine which I also have multiple subscriptions.

**Comment by adriancuadrado** [comment]
@ArthurMa1978 Yes I got that from the web browser. Is there a way to securely provide temporal access to someone in your team to see if the error can be reproduced with my account?

**Comment by adriancuadrado** [comment]
I did some research capturing the requests and responses of my program using the Postman "Capturing requests via proxy" feature, but only some POST requests to https://vortex.data.microsoft.com/collect/v1 and a POST request to https://clients4.google.com/chrome-sync/command/?client=Google+Chrome&client_id=... were captured. The clients4.google.com request had some unintelligible data in the POST body.

**Comment by christothes** [comment]
I can't reproduce this on Windows - is it specific to WSL?

**Comment by adriancuadrado** [comment]
I just checked now and apparently this also happens in Windows, not only inside WSL.

**Comment by djarvis** [comment]
I was having this same issue and couldn't figure out why even when I see the tenant with GetTenants(), doing a tenant.GetSubscriptions() it doesn't refer to the subscriptions of THAT TENANT which one would logically assume.  I had to specify:

`new ArmClient(new InteractiveBrowserCredential(new InteractiveBrowserCredentialOptions() { TenantId = "<<home tenant ID returned by az login>>" }))`

And then I got to see those subscriptions.

**Comment by christothes** [comment]
Thanks @djarvis - @adriancuadrado , does specifying the tenantId work for you as well?

**Comment by adriancuadrado** [comment]
@christothes Yes it does. But specifying the tenant id should not be mandatory, right?

**Comment by christothes** [comment]
> @christothes Yes it does. But specifying the tenant id should not be mandatory, right?

I think it depends on what your default tenant is for the account, Is the home tenant of the user that you authenticated with the same as the one you specified?

I'm also curious if the following code produces the expected tenant Id:

```c#
var tenants = armClient.GetTenants();
foreach (var t in tenants)
{
	Console.WriteLine($"{t.Data.DisplayName} - {t.Data.TenantId}");
}
```

And one last thing, the Azure.ResourceManager package released version 1.0.0 recently - do you get any different results with it?

**Comment by adriancuadrado** [comment]
@christothes

> Is the home tenant of the user that you authenticated with the same as the one you specified?

Yes
> 
> I'm also curious if the following code produces the expected tenant Id:
> 
> ```cs
> var tenants = armClient.GetTenants();
> foreach (var t in tenants)
> {
>     Console.WriteLine($"{t.Data.DisplayName} - {t.Data.TenantId}");
> }
> ```
> 

```cs
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;

var armClient = new ArmClient(new InteractiveBrowserCredential());
var tenants = armClient.GetTenants();
foreach (var t in tenants)
{
    Console.WriteLine($"{t.Data.DisplayName} - {t.Data.TenantId}");
}
```

```sh
$ dotnet run
Default Directory - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
Contoso Marketing Company - xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```
I censored the ids just in case, but they are a bunch of numbers and characters. The same ones that show up in Azure Portal.

> And one last thing, the Azure.ResourceManager package released version 1.0.0 recently - do you get any different results with it?

Nope

**Comment by adriancuadrado** [comment]
Wait, I forgot to mention the azure subscription that I had enabled had become disabled:
```sh
$ az account list --all --query '[].{isDefault: isDefault, name: name, state: state}'
[
  {
    "isDefault": true,
    "name": "Pase para Azure: patrocinio",
    "state": "Disabled"
  }
]
```
But it is marked as default anyways so it shouldn't matter. Besides, I had this error even when the state was "Enabled" as I show in the reproduction steps of this issue.

**Comment by christothes** [comment]
Could you reproduce with the following changes?
```c#
using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
var options = new InteractiveBrowserCredentialOptions();
options.Diagnostics.IsAccountIdentifierLoggingEnabled = true;
var armClient = new ArmClient(new InteractiveBrowserCredential(options));
```

This should produce a log output like this:

```
[Informational] Azure-Identity: AzureCliCredential.GetToken invoked. Scopes: [ https://management.azure.com//.default ] ParentRequestId: 9e5d8def-f810-4a28-ae93-da32d0b80222
[Informational] Azure-Identity: Client ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. Tenant ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx. User Principal Name: <your username> Object ID: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
```

Is the tenantId there the one you expected that contains the subscriptions?

**Comment by adriancuadrado** [comment]
@christothes

```cs
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.Resources;
using Azure.Core.Diagnostics;

using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();
var options = new InteractiveBrowserCredentialOptions();
options.Diagnostics.IsAccountIdentifierLoggingEnabled = true;
var armClient = new ArmClient(new InteractiveBrowserCredential(options));
```

I executed `dotnet run` but got no output at all.

**Comment by christothes** [comment]
oh - sorry, you should also include the part that gathers the Subscription 😄 

```c#
var subscription = await armClient.GetDefaultSubscriptionAsync();
Console.WriteLine(subscription.Id);
```

**Comment by adriancuadrado** [comment]
@christothes I got lots of output. I did Ctrl+F and searched the id of my subscription id and found nothing. Same with the tenant id.

**Comment by christothes** [comment]
Is there a line that contains: `Azure-Identity: Client ID:` ? It should look like my example, but with different guid values.

One other thing to note, this logging requires Azure.Identity version 1.6.0

**Comment by adriancuadrado** [comment]
@christothes Yes, but for some reason the ids are not the ones I expected them to be.

**Comment by adriancuadrado** [comment]
@christothes It's late here and I'm going to bed. I won't be available until tomorrow 9/April/2022 at 19:00 CEST aprox. Send me messages if you want but don't expect them to be answered until then. Bye.

**Comment by christothes** [comment]
Hi @adriancuadrado  - It seems that you are using a Live account, if the tenantId is `F8CDEF31-A31E-4B4A-93E4-5F571E91255A` (live.com tenant id). 

Are you logging into an AAD tenant in which this live account is guested? If so, the issue is that AAD is defaulting to this live account tenant, and you'll need to tell it which tenantId you intend to target. If this account were a native AAD account to the target tenant, I believe you would not need to specify the tenantId.

**Comment by adriancuadrado** [comment]
@christothes I think I am having trouble understanding what you say. The only tenant that I have is "Default Directory". I used to have another, but I removed it yesterday. The 2 subscriptions that I get running `az account list --all` are from the "Default Directory" anyways.

**Comment by christothes** [comment]
Is the account you are logging into the browser prompt with a Live account or a native AAD account?

**Comment by adriancuadrado** [comment]
@christothes It's a GitHub account actually.

**Comment by christothes** [comment]
> @christothes It's a GitHub account actually.

Because the home tenant of the account (the live.com tenant) is different than the target tenant that you intend to list subscriptions for, the target tenantId must be specified in the credential. This is unfortunately a quirk with live accounts.

**Comment by Stordlord** [comment]
Should be Authorized

**Comment by adriancuadrado** [comment]
@christothes If by saying "the target tenantId must be specified in the credential" you meant that I have to specify the `--tenant` parameter when running `az login` then it didn't work. I ran `az login --tenant 5c41...` and then `dotnet run`, but I am still having trouble. If you meant that I have to specify the tenant in the code like this:
```csharp
new ArmClient(new InteractiveBrowserCredential(new InteractiveBrowserCredentialOptions() { TenantId = "<<home tenant ID returned by az login>>" }))
```
then I think this kind of behaviour should be documented. Also I don't understand what exactly should be authorized accourding to @Stordlord.

**Comment by christothes** [comment]
Yes, the latter. Thanks for the feedback! We'll look at improving the documentation for this scenario.

**Comment by isaacrlevin** [comment]
From reading through this issue, it seems that InteractiveBrowserCredential DOES NOT WORK for non-AAD accounts. Is this correct? If so, is there a known workaround? Long story short I don't want to depend on the Azure CLI

**Comment by christothes** [comment]
> From reading through this issue, it seems that InteractiveBrowserCredential DOES NOT WORK for non-AAD accounts. Is this correct? If so, is there a known workaround? Long story short I don't want to depend on the Azure CLI

No, that's not correct. But you would need to specify the AAD tenantId of the Azure resource you are authenticating to in the credential options.

**Comment by isaacrlevin** [comment]
Am I able to get the tenant ID based on the browser context?

**Comment by christothes** [comment]
> Am I able to get the tenant ID based on the browser context?

Could you explain what you mean by the browser context?

Some Azure services advertise the correct tenantId as an Oauth challenge and will do the right thing, assuming your user account has access to the resource in question. However, only a handful of them do this today (Storage, KeyVault, Tables)

**Comment by isaacrlevin** [comment]
Without hardcoding it, how do I get the tenant ID? Is there a call I can make?

**Comment by isaacrlevin** [comment]
@christothes I see there is a GetTenants() method but I need an ArmClient to do that. I am seeing if I try to get a list of subs from a picked tenant none get returned. Do I need to set something on ArmClient? Here is some sample code


```csharp
var _credential = new InteractiveBrowserCredential();
var _armClient = new ArmClient(_credential);
var tenants = _armClient.GetTenants().ToList();

var subs = tenants.FirstOrDefault().GetSubscriptions().ToList();

// subs is empty here

````

**Comment by tdwright** [comment]
@isaacrlevin If you are still having issues with this, I posted a workaround to Stackoverflow: https://stackoverflow.com/a/72699716/50151

**Comment by tdwright** [comment]
@christothes I think the issue here is that, when we're designing applications for distribution to client users, we don't know in advance whether a) they'll be using a MS (or other federation provider) account and b) what the correct tenant ID would be. There doesn't seem to be any way within the SDK to list all the AAD tenant IDs associated with a user.

**Comment by tdwright** [comment]
@christothes Thanks for the reply. I think the problem arises when we don't/can't know the correct tenant ID ahead of time. If I authenticate interactively, all I get is the user's primary tenant. There is no way of interrogating for resources in other tenants, which would be a precursor to identifying which tenant to specify.

To paint a picture for you, my scenarios is an installer application, where the first step is to allow the user to select a subscription in which to create some resources. I can send them to log in interactively, but if they are have a Live/MS account, they'll have a different tenant ID to any of their subscriptions, which means I hit a wall.

Frankly, I think the behaviour is already correct in most cases - normally I probably wouldn't want to see a bunch of tenant IDs for each directory a user is a guest in. I think, though, that the way Live/MS accounts are handled is a problematic exception to this. It's a non-intuitive hurdle that will disproportionally affect users who have least experience with AD.

**Comment by tdwright** [comment]
Thanks @christothes - you've nailed the use case I'm aiming for.

One issue I have is with the last line of your reply - how do I use the tenant ID to list the subs, or do anything else with it? It feels like I need to create a new ArmClient. What's the easiest way of doing this without prompting the user to login again? (I can see that there are some tenant ID related properties in the `DefaultAzureCredentialOptions` class, but it's not obvious which to use...

**Comment by tdwright** [comment]
@christothes That works, but means I'm triggering an interactive login twice. Is there some way to do the same thing more "quietly"?

I've tried using the `DefaultAzureCredential` as below....

```
var armclient2 = new armclient(new defaultazurecredential(new defaultazurecredentialoptions
{
    interactivebrowsertenantid = tenantid, 
    sharedtokencachetenantid = tenantid,
    excludevisualstudiocodecredential = true,
    excludevisualstudiocredential = true
}));
```
But I get an error about the grant having expired.

Is there some way of recycling the token from the first time I call `InteractiveBrowserCredential`, whilst specifying a tenant ID?

**Comment by christothes** [comment]
Unfortunately, they are two different tokens.

**Comment by tdwright** [comment]
I see. This sort of loops back to my earlier point that this behavior is sort of broken for users who are guests in their the tenant that holds their subscription(s) - e.g. those who sign in with an MS / Live account. 

This probably isn't the place to make these suggestions (please feel free to point me to somewhere more appropriate), but the following feel like sensible improvements:
1. When the user has zero subscriptions in their default tenant, but has exactly one other tenant containing some subscriptions, select this one automatically. This would solve the (I would guess pretty common) situation of MS / Live accounts owning subscriptions.
2. Have some mechanism on the login screen to allow the user to specify which tenant to use, when doing an interactive login.
3. Provide some mechanism of hopping from one tenant to another after the user has authenticated. My question about re-using a token was aiming towards this, but clearly wasn't quite right. Since I can move between tenants in the portal, it feels like it should be possible to do something similar using the SDK.

**Comment by tdwright** [comment]
Is there a proper place to make suggestions? I feel like original "bug" is working as designed, but there's still some options for making the experience more seamless.

**Comment by adriancuadrado** [comment]
@christothes I'm reading the thread and if my understanding is correct you added the _needs-author-feedback_ label because you needed more feedback from @tdwright. If that's the case then I'd like to remember you that the label won't go away until not @tdwright, but the original author of the issue answers. I think you have to ask @tdwright to create a separate issue to keep discussing with him his problems.
