### ISSUE TITLE
[QUERY] DefaultAzureCredential fails to re-authenticate when debugging locally

### ISSUE THREAD

**Issue by dmitrymal** [Azure/azure-sdk-for-net#26798]
### Library name and version

Azure.Identity 1.5.0

### Query/Question

We are using DefaultAzureCredential to authorize az-f() calls. In particular, we use the following code:
```
var blobServiceClient = new BlobServiceClient(new Uri(_options.StorageServiceUri),
       new DefaultAzureCredential());
```
It works perfectly as described. However, for one of the older projects that I have't used for awhile, I now get this error when I debug my az function locally: 
ResponseBody: {"error":"invalid_grant","error_description":"AADSTS700082: **The refresh token has expired due to inactivity.** The token was issued on _older date_ and was inactive for 90.00:00:00.\r\nTrace ID: dd2f0ca1-8033-4a28-9383-20b08d4f0901\r\nCorrelation ID: 87a5c127-edf2-43d1-89f0-3f6eb3b5082b\r\nTimestamp: 2022-02-03 22:13:22Z","error_codes":[700082],"timestamp":"2022-02-03 22:13:22Z","trace_id":"dd2f0ca1-8033-4a28-9383-20b08d4f0901","correlation_id":"87a5c127-edf2-43d1-89f0-3f6eb3b5082b","error_uri":"https://login.microsoftonline.com/error?code=700082","suberror":"bad_token"} 

Here is more of a callstack:
[2022-02-03T22:13:25.593Z] Correlation ID: 87a5c127-edf2-43d1-89f0-3f6eb3b5082b
[2022-02-03T22:13:25.593Z] Timestamp: 2022-02-03 22:13:22Z
[2022-02-03T22:13:25.593Z]    at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
[2022-02-03T22:13:25.593Z]    at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
[2022-02-03T22:13:25.593Z]    at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeaders)
[2022-02-03T22:13:25.594Z]    at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
[2022-02-03T22:13:25.594Z]    at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
[2022-02-03T22:13:25.594Z]    at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
[2022-02-03T22:13:25.594Z]    at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary 2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancellationToken)
[2022-02-03T22:13:25.595Z]    at Microsoft.Identity.Client.Internal.Requests.ByRefreshTokenRequest.ExecuteAsync(CancellationToken cancellationToken)
[2022-02-03T22:13:25.595Z]    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
[2022-02-03T22:13:25.595Z]    at Microsoft.Identity.Client.ApiConfig.Executors.ClientApplicationBaseExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenByRefreshTokenParameters refreshTokenParameters, CancellationToken cancellationToken)
[2022-02-03T22:13:25.595Z]    at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder 1 builder, Boolean async, CancellationToken cancellationToken)
[2022-02-03T22:13:25.595Z]    at Azure.Identity.MsalPublicClient.AcquireTokenByRefreshTokenCoreAsync(String[] scopes, String claims, String refreshToken, AzureCloudInstance azureCloudInstance, String tenant, Boolean async, CancellationToken cancellationToken)
[2022-02-03T22:13:25.595Z]    at Azure.Identity.MsalPublicClient.AcquireTokenByRefreshTokenAsync(String[] scopes, String claims, String refreshToken, AzureCloudInstance azureCloudInstance, String tenant, Boolean async, CancellationToken cancellationToken)
[2022-02-03T22:13:25.596Z]    at Azure.Identity.VisualStudioCodeCredential.GetTokenImplAsync(TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
[2022-02-03T22:13:25.596Z]      StatusCode: 400 

I searched everywhere, but I could not find where Visual Studio for Mac keeps the tokens. 
**Does anybody know how I can force Visual Studio for Mac to re-authenticate or delete the refresh token?** Thank you!

### Environment

Visual Studio for Mac, netcoreapp3.1, Azure Function project

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team members best able to assist.

**Comment by christothes** [comment]
Hi @dmitrymal I suspect that you are getting the credential from another source. This can be validated by enabling logging on the credential. You can find details on how to enable it [here](https://github.com/Azure/azure-sdk-for-net/tree/main/sdk/identity/Azure.Identity#logging).
