### ISSUE TITLE
Cosmos table endpoints fail auth with SAS authentication when table name contains upper case letters

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#26800]
### Library name

Azure.Data.Tables

### Please describe the feature.

According to the [SAS token spec](https://docs.microsoft.com/en-us/rest/api/storageservices/create-service-sas), "If the signed resource is a table, assure the table name is lower-case in the canonicalized format."

When attempting to use a SAS token with a cosmos table that is not fully lower case, the following exception occurs:

```
The input authorization token can't serve the request. The wrong key is being used or the expected payload is not built as per the protocol. For more info: https://aka.ms/cosmosdb-tsg-unauthorized. Server used the following payload to sign: 'r


2040-01-01T01:01:00Z
/table/<myaccount>/testtable84g9j7yja

2019-07-07



'
ActivityId: d41a38dd-dcdd-4f90-aaa7-a4cd292d7821, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.19041.0
RequestID:d41a38dd-dcdd-4f90-aaa7-a4cd292d7821
```

**Comment by galvesribeiro** [comment]
I can confirm and I'm having the same problem. The old SDK based on CosmosDB SDK allowed our tables to have upper case letters and never complained. We've just switched to this one and now I'm facing this issue as well and I can't "rename" the tables. Because of that, I had to revert to previous version of Microsoft Orleans since it use the old CosmosDB libraries and renaming a collection is not allowed...

@jsquire / @christothes  do we have any ETA when this would be fixed?

Thanks!

**Comment by galvesribeiro** [comment]
And for the sake of reference, this is what I get:

```
fail: Orleans.Runtime.SiloLifecycleSubject[100450]
      MembershipTableManager failed to start due to errors at stage RuntimeGrainServices (8000): Orleans.Runtime.OrleansException: Exception trying to create or connect to the Azure table: Authorization header doesn't confirm to the required format. Please verify and try again.
      ActivityId: fde84e4d-cdbf-481e-8a90-804422174901, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.19041.0
      RequestID:fde84e4d-cdbf-481e-8a90-804422174901
      
      Status: 401 (Unauthorized)
      ErrorCode: Unauthorized
      
      Content:
      {"odata.error":{"code":"Unauthorized","message":{"lang":"en-us","value":"Authorization header doesn't confirm to the required format. Please verify and try again.\r\nActivityId: fde84e4d-cdbf-481e-8a90-804422174901, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.19041.0\nRequestID:fde84e4d-cdbf-481e-8a90-804422174901\n"}}}
      
      
      Headers:
      Date: Tue, 08 Mar 2022 17:10:48 GMT
      Transfer-Encoding: chunked
      x-ms-request-id: fde84e4d-cdbf-481e-8a90-804422174901
      Content-Type: application/json; odata=minimalmetadata
      
       ---> Azure.RequestFailedException: Authorization header doesn't confirm to the required format. Please verify and try again.
      ActivityId: fde84e4d-cdbf-481e-8a90-804422174901, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.19041.0
      RequestID:fde84e4d-cdbf-481e-8a90-804422174901
      
      Status: 401 (Unauthorized)
      ErrorCode: Unauthorized
      
      Content:
      {"odata.error":{"code":"Unauthorized","message":{"lang":"en-us","value":"Authorization header doesn't confirm to the required format. Please verify and try again.\r\nActivityId: fde84e4d-cdbf-481e-8a90-804422174901, documentdb-dotnet-sdk/2.14.0 Host/64-bit MicrosoftWindowsNT/10.0.19041.0\nRequestID:fde84e4d-cdbf-481e-8a90-804422174901\n"}}}
      
      Headers:
      Date: Tue, 08 Mar 2022 17:10:48 GMT
      Transfer-Encoding: chunked
      x-ms-request-id: fde84e4d-cdbf-481e-8a90-804422174901
      Content-Type: application/json; odata=minimalmetadata
      
         at Azure.Data.Tables.TableRestClient.CreateAsync(TableProperties tableProperties, Nullable`1 responsePreference, QueryOptions queryOptions, CancellationToken cancellationToken)
         at Azure.Data.Tables.TableClient.CreateIfNotExistsAsync(CancellationToken cancellationToken)
         at Orleans.Clustering.AzureStorage.AzureTableDataManager`1.InitTableAsync() in /_/src/Azure/Shared/Storage/AzureTableDataManager.cs:line 87
         at Orleans.AzureUtils.OrleansSiloInstanceManager.GetManager(String clusterId, ILoggerFactory loggerFactory, AzureStorageOperationOptions options) in /_/src/Azure/Orleans.Clustering.AzureStorage/OrleansSiloInstanceManager.cs:line 53
         --- End of inner exception stack trace ---
         at Orleans.AzureUtils.OrleansSiloInstanceManager.GetManager(String clusterId, ILoggerFactory loggerFactory, AzureStorageOperationOptions options) in /_/src/Azure/Orleans.Clustering.AzureStorage/OrleansSiloInstanceManager.cs:line 59
         at Orleans.Runtime.MembershipService.AzureBasedMembershipTable.InitializeMembershipTable(Boolean tryInitTableVersion) in /_/src/Azure/Orleans.Clustering.AzureStorage/AzureBasedMembershipTable.cs:line 41
         at Orleans.Runtime.MembershipService.MembershipTableManager.Start() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 164
         at Orleans.Runtime.MembershipService.MembershipTableManager.<>c__DisplayClass54_0.<<Orleans-ILifecycleParticipant<Orleans-Runtime-ISiloLifecycle>-Participate>g__OnRuntimeGrainServicesStart|0>d.MoveNext() in /_/src/Orleans.Runtime/MembershipService/MembershipTableManager.cs:line 859
      --- End of stack trace from previous location ---
         at Orleans.Runtime.SiloLifecycleSubject.MonitoredObserver.OnStart(CancellationToken ct) in /_/src/Orleans.Runtime/Lifecycle/SiloLifecycleSubject.cs:line 116
```

**Comment by christothes** [comment]
We just released this fix today - https://www.nuget.org/packages/Azure.Data.Tables/12.5.0

**Comment by galvesribeiro** [comment]
Hello! @christothes is this planned to be resolved somewhere? Thanks

**Comment by christothes** [comment]
fixed by https://github.com/Azure/azure-sdk-for-net/pull/26802
