### ISSUE TITLE
[Flaky Test] Azure.Search.Documents.Tests.ManualRetryDelayTests.AddsMoreDelay()

### ISSUE THREAD

**Issue by christothes** [Azure/azure-sdk-for-net#27050]
### Library name

Azure.Search.Documents

### Please describe the feature.

Expected a delay between 148ms and 500ms, not 821
Expected: True
But was:  False

```
Stack trace
   at Azure.Search.Documents.Tests.ManualRetryDelayTests.AddsMoreDelay() in D:\a\_work\1\s\sdk\search\Azure.Search.Documents\tests\Batching\ManualRetryDelayTests.cs:line 53
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
```
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1371453&view=ms.vss-test-web.build-test-results-tab&runId=28754284&resultId=116651&paneView=debug

**Comment by pallavit** [comment]
Opportunistically closing all the 6 months old test reliability bugs to flush the system of older issues.
