### ISSUE TITLE
[BUG] System.ArgumentNullException: Value cannot be null. (Parameter 'queueName') when running in node functions app

### ISSUE THREAD

**Issue by ksstott** [Azure/azure-sdk-for-net#27164]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.0.0

### Describe the bug

We are writing a node based function app importing Microsoft.Azure.WebJobs.Extensions.Storage.Queues 5.0.0 via the Microsoft.Azure.Functions.ExtensionBundle extension bundle in our host.json however we cannot get our functions app to run successfully with a queue trigger function

### Expected behavior

Functions run successfully

### Actual behavior

```
[2022-02-23T17:08:14.183Z] A host error has occurred during startup operation '6ce5d430-f5a3-4772-bcdd-bd9e00f16456'.
[2022-02-23T17:08:14.184Z] System.ArgumentNullException: Value cannot be null. (Parameter 'queueName')
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Extensions.Storage.Common.HostQueueNames.IsHostQueue(String queueName)
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Listeners.QueueListenerFactory.CreateQueueProcessor(QueueClient queue, QueueClient poisonQueue, ILoggerFactory loggerFactory, IQueueProcessorFactory queueProcessorFactory, QueuesOptions queuesOptions, IMessageEnqueuedWatcher sharedWatcher)
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Listeners.QueueListenerFactory.CreateAsync(CancellationToken cancellationToken)
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Extensions.Storage.Queues.Triggers.QueueTriggerBinding.CreateListenerAsync(ListenerFactoryContext context)
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Host.Indexers.FunctionIndexer.ListenerFactory.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Indexers\FunctionIndexer.cs:line 474
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Host.Listeners.HostListenerFactory.CreateAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\HostListenerFactory.cs:line 71
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\ListenerFactoryListener.cs:line 45
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.StartAsync(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Listeners\ShutdownListener.cs:line 29
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.JobHost.StartAsyncCore(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 97
[2022-02-23T17:08:14.188Z]    at Microsoft.Azure.WebJobs.Script.ScriptHost.StartAsyncCore(CancellationToken cancellationToken) in D:\a\1\s\src\WebJobs.Script\Host\ScriptHost.cs:line 273
[2022-02-23T17:08:14.189Z]    at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[2022-02-23T17:08:14.189Z]    at Microsoft.Azure.WebJobs.Script.WebHost.WebJobsScriptHostService.UnsynchronizedStartHostAsync(ScriptHostStartupOperation activeOperation, Int32 attemptCount, JobHostStartupMode startupMode) in D:\a\1\s\src\WebJobs.Script.WebHost\WebJobsScriptHostService.cs:line 292
[2022-02-23T17:08:14.215Z] Stopping JobHost
System.ArgumentNullException: Value cannot be null. (Parameter 'provider')
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Azure.Functions.Cli.Actions.HostActions.StartHostAction.RunAsync() in D:\a\1\s\src\Azure.Functions.Cli\Actions\HostActions\StartHostAction.cs:line 354
   at Azure.Functions.Cli.ConsoleApp.RunAsync[T](String[] args, IContainer container) in D:\a\1\s\src\Azure.Functions.Cli\ConsoleApp.cs:line 66
```

### Reproduction Steps

Create a node functions app and add this to host.json
```
"extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.3.0, 4.0.0)"
  }
```

Create a function with a function.json that looks like this:
```json
{
  "bindings": [
    {
      "name": "queueItem",
      "type": "queueTrigger",
      "direction": "in",
      "queueName": "delete",
      "connection": "AzureStorage"
    }
  ],
  "scriptFile": "../dist/delete/index.js"
}
```

attempt to run with `CLI_DEBUG=1 func start --verbose`

### Environment

node 16
azure functions tools v4

**Comment by SaurabhSharma-MSFT** [comment]
@ksstott I have tried this in my local environment, and it is working fine.
![image](https://user-images.githubusercontent.com/38112130/155434034-e1821f97-8209-43dd-b49b-3ddba7d4b875.png)

Can you please check what all extensions version you have in your local environment?
![image](https://user-images.githubusercontent.com/38112130/155433872-f6bb6e55-4e0c-46df-a375-8707f98b0084.png)

**Comment by kvigor** [comment]
I have the same issue.
Azure.Data.Tables 12.4.3
Microsoft.Azure.Functions.Extensions 1.1.0
And these 2 from a legacy package reference: Microsoft.Azure.Search (10.1.0) | WinfowsAzure.Storage 9.3.3

**Comment by SaurabhSharma-MSFT** [comment]
Hi @ksstott, @kvigor 
1. Is it time triggered, or direct Queue triggered?
2. the error says the queue name is null, cam u makes sure you are passing the queue name
3. Can u run the function app in local dev machine as part of local debug and check?

Thanks
Saurabh

**Comment by kvigor** [comment]
Timer Trigger.

I've resolved the...

"Value cannot be null. (Parameter 'queueName') error as tied to dev settings being added to staging settings. I don't ever swap those slots and the Azure activity logs don't even show the settings in staging being updated which is fishy. But, I still have an issue with the second part of that issue going on.

When our Messaging API published messages to the queue and subsequent blob store the Azure Function app seems to not be able to access it as shown below.

***@***.***

**Comment by kvigor** [comment]
Sorry I had to delete the previous message I thought is was a correspondence our support ticket we have open with MS on this issue.

1) Yes this is a timer trigger 
2) This queue name was erroneous, and this queue error is fixed.
3) I can no longer run locally, however, sometimes the Azure function runs fine and other times it just errors out. This makes it hard to debug especially when I'm not changing the payload sent to the queue.

**Comment by SaurabhSharma-MSFT** [comment]
@kvigor Thanks for the confirmation.  We are proceeding with the closure of this case. Thanks.
