### ISSUE TITLE
Azure.Messaging.ServiceBus.ServiceBusException: System.Net.Sockets.SocketException (110): Operation timed out

### ISSUE THREAD

**Issue by krishnad1982** [Azure/azure-sdk-for-net#27205]
Hi, 
I use the below code to schedule the messages in Azure Web Job ServiceBusTrigger. However I am getting the below error immediately after starting the AKS containers
Azure.Messaging.ServiceBus" Version="7.5.0" 
```
var client = new ServiceBusClient(ConnectionString);
                        var sender = client.CreateSender(TopicName);
                        var scheduledMessage = new ServiceBusMessage(message);
                        await sender.ScheduleMessageAsync(scheduledMessage, DateTimeOffset.UtcNow.AddMinutes(_serviceBusConfig.ScheduledEnqueueTimeInMinutes));
                        await messageActions.CompleteMessageAsync(message);
```

Azure.Messaging.ServiceBus.ServiceBusException: Operation timed out ErrorCode: TimedOut (ServiceCommunicationProblem)
 ---> System.Net.Sockets.SocketException (110): Operation timed out
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, ServiceBusTransportType transportType, IWebProxy proxy, String scopeIdentifier, TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenManagementLinkAsync(String entityPath, String identifier, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.OpenManagementLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.ManagementUtilities.ExecuteRequestResponseAsync(AmqpConnectionScope connectionScope, FaultTolerantAmqpObject`1 managementLink, AmqpRequestMessage amqpRequestMessage, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.ScheduleMessageInternalAsync(IReadOnlyList`1 messages, TimeSpan timeout, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.ScheduleMessageInternalAsync(IReadOnlyList`1 messages, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<ScheduleMessagesAsync>b__24_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.ScheduleMessagesAsync(IReadOnlyList`1 messages, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusSender.ScheduleMessagesAsync(IEnumerable`1 messages, DateTimeOffset scheduledEnqueueTime, CancellationToken cancellationToken)

**Comment by jsquire** [comment]
Hi @krishnad1982.  Thank you for reaching out and we regret that you're experiencing difficulties.  The stack trace and error message indicate that the Service Bus clients are unable to establish a connection to Service Bus.

When this occurs, it is normally due to the host environment blocking the AMQP ports (5671, 5672).    Specifying the web sockets transport can often help.   I've included an example of doing so below.

You mention using a `ServiceBusTrigger` but the snippet that you shared shows creating the client manually.   Can you help me understand a more about your scenario?  

**Creating a client**

```csharp
var options = new ServiceBusClientOptions
{
    TransportType = ServiceBusTransportType.AmqpWebSockets
};

var client = new ServiceBusClient("<< CONNECTION STRING >>", options);
```

**Configuring host.json for a trigger**

```json
{
  "extensions": {
    "serviceBus": {
      "transportType" : "amqpWebSockets"          
  }
}
```

**Comment by krishnad1982** [comment]
Using the normal service bus trigger to receive the messages and scheduling messages for 2 hour(pushing messages back to the same Topic). After the schedule expiry, we use the same trigger to receive and process the messages.

Below mentioned trigger was working without any issues. It started failing after the scheduling part was introduced into the codebase. 
Current settings 
```
builder.AddServiceBus((options) =>
                    {
                        options.AutoCompleteMessages= false;
                        options.MaxConcurrentCalls = 5;
                    });
```
```
 [FunctionName(nameof(Process))]
        public async Task Process(
            [ServiceBusTrigger("%Topic%", "%Subscription%", Connection = "Connection ")]
            ServiceBusReceivedMessage message,
            ServiceBusMessageActions messageActions)
        {
            if (message.LockedUntil > DateTimeOffset.UtcNow)
            {
                try
                {                   
                    var cancelledMessage = message.Deserialize<MessageModel<OrderMessage>>();
                    if (message.ScheduledEnqueueTime != default && message.ScheduledEnqueueTime.ToUnixTimeSeconds() > 0)
                    {
                        await _orderCancelledProcessor.Process(cancelledMessage.Payload);
                        await messageActions.CompleteMessageAsync(message);
                   }
                    else
                    {
                        var client = new ServiceBusClient(ConnectionString);
                        var sender = client.CreateSender(TopicName);
                        var scheduledMessage = new ServiceBusMessage(message);
                        await sender.ScheduleMessageAsync(scheduledMessage, DateTimeOffset.UtcNow.AddMinutes(_serviceBusConfig.ScheduledEnqueueTimeInMinutes));
                        await messageActions.CompleteMessageAsync(message);
                   }
                }
                catch (Exception ex)
                {
                    if (message.DeliveryCount > MaximumDeliveryCount)
                    {
                       await messageActions.DeadLetterMessageAsync(message, "Exceeded Maximum Retries");
                        return;
                    }
                }
            }
            else
            {
                _logger.LogWarning("Lock expired before starting to process, message was returned to subscription.");
            }
        }
```

**Comment by jsquire** [comment]
Hi @krishnad1982.   Thank you for the additional context.   I notice that you're creating a new `ServiceBusClient`  and `ServiceBusSender` each time the `else` condition is triggered, and that they're not being closed or disposed.   This will cause the network resources to be orphaned without being cleaned up.   _(it is also going to perform poorly because the connection and link have to be created and authorized for each use.)_

That will consume resources and occupy a socket until the connection idles out and is force-closed by the service after ~20 minutes.  I suspect that the timeout you're seeing is due to the host not having available sockets to use.   

I'd suggest treating the client and sender as singletons, reusing them across invocations.  Assuming that the Service Bus instance and topic are the same as the one the trigger is configured to use, I believe that you can bind directly to a sender and allow Functions to manage the lifetime.   Doing so would look something like:

```csharp
[FunctionName(nameof(Process))]
public async Task Process(
    [ServiceBusTrigger("%Topic%", "%Subscription%", Connection = "Connection ")]
    ServiceBusReceivedMessage message,
    ServiceBusMessageActions messageActions,
    ServiceBusSender sender)
```

Unfortunately, I'm not in the position to verify that I'm remembering correctly at the moment and apologize if I'm mistaken.   If you're using a different downstream Service Bus/topic or if I'm incorrect, it appears that you've already got the structure in place to manually register the client and sender for DI, based on your use of the `builder`.    I'm happy to suggest an example of doing so if you'd like.

Would you mind testing with either the singleton client/sender or by explicitly closing or disposing in your `else` block after sending completing the message and let us know if freeing up the sockets resolves the issue?

**Comment by krishnad1982** [comment]
Hey @jsquire 
Thanks for the swift reply. I could not bind the ServiceBusSender directly "**_Cannot bind parameter 'sender' to type ServiceBusSender_**". However, I managed to use it with ServiceBus Trigger as mentioned below.
I will update once done with my testing.
```
public async Task ProcessOrderCancelled(
            [ServiceBusTrigger("%Topic%", "%Subscription%", Connection = "Connection ")]
            ServiceBusReceivedMessage message,
            ServiceBusMessageActions messageActions, 
            [ServiceBus(""%Topic%", Connection = "Connection"] ServiceBusSender sender)
        { }
```

**Comment by krishnad1982** [comment]
Hi @jsquire ,
All sorted. I have tested and confirmed that the issue is no longer exists. Thanks.

**Comment by jsquire** [comment]
Glad to hear that things worked out.
