### ISSUE TITLE
[BUG] BlobClient.UploadAsync throws BlobAlreadyExists, whilst the blob does not already exist.

### ISSUE THREAD

**Issue by JulianSarkinovic** [Azure/azure-sdk-for-net#27264]
### Library name and version

Azure.Storage.Blobs 12.10.0

### Describe the bug

[BlobClient.UploadAsync(Stream, Boolean, CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#azure-storage-blobs-blobclient-uploadasync(system-io-stream-system-boolean-system-threading-cancellationtoken)) is throwing _Azure.RequestFailedException: The specified blob already exists._ whilst the blob does not already exist.

On 16 parallel tasks per 35 parallel running Azure Batch nodes, I am await BlobClient.UploadAsync'ing blobs to a single Standard_LRS Storage Account. The blobs are relatively small (~50 KiB), so even though each upload is awaited, there may still be around 50 uploads per second per task, adding up to ~25k uploads per second. The total uploads are only about 200-300k. The names are quite similar, but always have a unique combination of some number-task number.

### Expected behavior

No BlobAlreadyExists.

### Actual behavior

Azure.RequestFailedException: The specified blob already exists.
RequestId:97fb7466-d01e-002c-0257-2d111d000000
Time:2022-03-01T10:33:15.0647648Z
Status: 409 (The specified blob already exists.)
ErrorCode: BlobAlreadyExists

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobAlreadyExists</Code><Message>The specified blob already exists.
RequestId:97fb7466-d01e-002c-0257-2d111d000000
Time:2022-03-01T10:33:15.0647648Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: 97fb7466-d01e-002c-0257-2d111d000000
x-ms-client-request-id: *
x-ms-version: 2020-10-02
x-ms-error-code: BlobAlreadyExists
Date: Tue, 01 Mar 2022 10:33:15 GMT
Content-Length: 220
Content-Type: application/xml

   at Azure.Storage.Blobs.BlockBlobRestClient.UploadAsync(Int64 contentLength, Stream body, Nullable`1 timeout, Byte[] transactionalContentMD5, String blobContentType, String blobContentEncoding, String blobContentLanguage, Byte[] blobContentMD5, String blobCacheControl, IDictionary`2 metadata, String leaseId, String blobContentDisposition, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 tier, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, String blobTagsString, Nullable`1 immutabilityPolicyExpiry, Nullable`1 immutabilityPolicyMode, Nullable`1 legalHold, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.UploadInternal(Stream content, BlobHttpHeaders blobHttpHeaders, IDictionary`2 metadata, IDictionary`2 tags, BlobRequestConditions conditions, Nullable`1 accessTier, BlobImmutabilityPolicy immutabilityPolicy, Nullable`1 legalHold, IProgress`1 progressHandler, String operationName, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.<>c__DisplayClass62_0.<<GetPartitionedUploaderBehaviors>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Storage.PartitionedUploader`2.UploadInternal(Stream content, TServiceSpecificArgs args, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadInternal(Stream content, BlobUploadOptions options, Boolean async, CancellationToken cancellationToken)

### Reproduction Steps

Bombard a Storage Account with 250k [BlobClient.UploadAsync(Stream, Boolean, CancellationToken)](https://docs.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobclient.uploadasync?view=azure-dotnet#azure-storage-blobs-blobclient-uploadasync(system-io-stream-system-boolean-system-threading-cancellationtoken)) calls from 500 parallel threads with 50 KiB blobs, unique but similar blob names and overwrite set to false.

### Environment

Windows 10, .NET 5.

**Comment by SaurabhSharma-MSFT** [comment]
@JulianSarkinovic Routing this to services team to provide you suggestions on this.

**Comment by amnguye** [comment]
This does not seem like an SDK issue rather it seems like a service issue. The SDK returns back the error BlobAlreadyExists from the service, which means if you say that the blob did not already exist prior to the upload call to create the blob, then we need assistance from the Service.

Please submit an Azure Support Request to seek assistance for support on the service.
https://docs.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request
