### ISSUE TITLE
[Tables] CanSaveJObjectAndLoadJObject(ExtensionT1,Extension) failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#27354]
Tables nightly test runs are failing with:

> Error message
> Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: AddEntityProgramT1`1.Call
> ----> System.InvalidOperationException : Error while handling parameter $return after function returned:
> ----> Microsoft.Azure.Cosmos.Table.StorageException : A task was canceled. (HTTP status code 306: . )
> ----> Microsoft.Azure.Cosmos.Table.StorageException : A task was canceled.
> ----> System.Threading.Tasks.TaskCanceledException : A task was canceled.
> 
> 
> Stack trace
>    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 343
>    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.TryExecuteAsync(IFunctionInstance functionInstance, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 105
>    at Microsoft.Azure.WebJobs.Host.Executors.ExceptionDispatchInfoDelayedException.Throw() in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\ExceptionDispatchInfoDelayedException.cs:line 28
>    at Microsoft.Azure.WebJobs.JobHost.CallAsyncCore(IFunctionDefinition function, Object functionKey, IDictionary`2 arguments, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 241
>    at Microsoft.Azure.WebJobs.JobHost.CallAsync(MethodInfo method, IDictionary`2 arguments, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 204
>    at Microsoft.Azure.WebJobs.Extensions.Tables.Tests.TablesLiveTestBase.CallAsync(Type funcType, String methodName, Object arguments, Action`1 configure) in /mnt/vss/_work/1/s/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/tests/TablesLiveTestBase.cs:line 116
>    at Microsoft.Azure.WebJobs.Extensions.Tables.Tests.TablesLiveTestBase.CallAsync[T](String methodName, Object arguments, Action`1 configure) in /mnt/vss/_work/1/s/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/tests/TablesLiveTestBase.cs:line 97
>    at Microsoft.Azure.WebJobs.Extensions.Tables.Tests.CompatibilityTests.ExtensionT1.Write[T](CompatibilityTests test, T entity) in /mnt/vss/_work/1/s/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/tests/CompatibilityTests.cs:line 535
>    at Microsoft.Azure.WebJobs.Extensions.Tables.Tests.CompatibilityTests.CanSaveJObjectAndLoadJObject(ITablesClient writer, ITablesClient reader) in /mnt/vss/_work/1/s/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/tests/CompatibilityTests.cs:line 225
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> --InvalidOperationException
>    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ParameterHelper.ProcessOutputParameters(CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 952
>    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithWatchersAsync(IFunctionInstanceEx instance, ParameterHelper parameterHelper, ILogger logger, CancellationTokenSource functionCancellationTokenSource) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Executors\FunctionExecutor.cs:line 535
>    at Microsoft.Azure.WebJobs.Host.Executors.FunctionExecutor.ExecuteWithLoggingAsync(IFunctionInstanceEx instance, FunctionStartedMessage message, FunctionInstanceLogEntry instanceLogEntry, ParameterHelper parameterHelper, ILogger logger, CancellationToken cancellationToken) in C:\projects\azure-web

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1406527&view=results

@jsquire for notification.

**Comment by JoshLove-msft** [comment]
Seems to have been a transient failure - passing now.
