### ISSUE TITLE
[Storage] BlobClient.OpenWriteAsync(bool) throws NullReferenceException

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#27831]
## Repro

```c#
var blobClient = new BlobClient(connectionString, "test", "testexception");
var stream = await blobClient.OpenWriteAsync(overwrite: true);
```
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Storage.Blobs.Models.BlobOpenWriteOptionsExtensions.ToBlockBlobOpenWriteOptions(BlobOpenWriteOptions options)
   at Azure.Storage.Blobs.BlobClient.OpenWriteInternal(Boolean overwrite, BlobOpenWriteOptions options, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.OpenWriteAsync(Boolean overwrite, BlobOpenWriteOptions options, CancellationToken cancellationToken)
```

## Workaround
```c#
var stream = await blobClient.OpenWriteAsync(overwrite: true, options: new BlobOpenWriteOptions());
```

**Comment by PramodValavala-MSFT** [comment]
@mikeharder Thanks for the feedback! We will review and address accordingly.

**Comment by PramodValavala-MSFT** [comment]
@mikeharder Apologies for the delay here! This has since been fixed as part of another PR.
