### ISSUE TITLE
[BUG] Enum case rename not supported

### ISSUE THREAD

**Issue by chkeita** [Azure/azure-sdk-for-net#27918]
### Library name and version

Azure.Data.Tables 12.5.0

### Describe the bug

following up on the scenario described [here](https://github.com/Azure/azure-sdk-for-net/issues/27413#issuecomment-1084923049)

> We are porting an existing service that was originally written in python. The column names are all snake_case following the python convention. I would like to have the entity created in C# to follow the PascalCase convention.
Unfortunately, We don't have the option of renaming the column because there are other services that depends on the DB.

We also need to convert the enum cases but when i use the `EnumMemberAttribute` i get an error when reading an entity from the db with `busy` as state.

``` C#
[DataContract]
enum NodeState
{
	[EnumMember(Name= "free")]
        Free,
	[EnumMember(Value = "busy")]
	Busy,
}

record Node : ITableEntity
{
        [DataMember(Name ="pool_name")]
	public string PoolName;
        [DataMember(Name ="machine_id")]
	public Guid MachineID;
	[DataMember(Name ="state")]
	public NodeState State;

       public string PartitionKey { get => PoolName; set => PoolName = value; }
       public string RowKey { get => MachineID.ToString(); set => MachineID = Guid.Parse(value); }
       public Azure.ETag ETag { get; set; }
       DateTimeOffset? ITableEntity.Timestamp { get; set; }
}
```

### Expected behavior

The read should be successful with the state set to `Busy`

### Actual behavior

error : Requested value 'busy' was not found.

```
   at System.Enum.TryParseByName(RuntimeType enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, UInt64& result)
   at System.Enum.TryParseInt32Enum(RuntimeType enumType, ReadOnlySpan`1 value, Int32 minInclusive, Int32 maxInclusive, Boolean ignoreCase, Boolean throwOnFailure, TypeCode type, Int32& result)
   at System.Enum.TryParse(Type enumType, ReadOnlySpan`1 value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at System.Enum.TryParse(Type enumType, String value, Boolean ignoreCase, Boolean throwOnFailure, Object& result)
   at Azure.Data.Tables.TablesTypeBinder.TryGet[T](BoundMemberInfo memberInfo, IDictionary`2 source, T& value)
   at Azure.Monitor.Query.TypeBinder`1.BoundMemberInfo`1.Deserialize(TExchange source, Object o, TypeBinder`1 binderImplementation)
   at Azure.Monitor.Query.TypeBinder`1.BoundTypeInfo.Deserialize[T](TExchange source)
   at Azure.Data.Tables.TableClient.GetEntitiyInternalAsync[T](Boolean async, String partitionKey, String rowKey, IEnumerable`1 select, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.GetEntityAsync[T](String partitionKey, String rowKey, IEnumerable`1 select, CancellationToken cancellationToken)
   at UserQuery.Main(), line 14
```

### Reproduction Steps

```
var node = await tableClient.GetEntityAsync<Node>(<table_name>,<partition_key>);
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.201
 Commit:    ef40e6aa06

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.201\

Host (useful for support):
  Version: 6.0.3
  Commit:  c24d9a9c91

.NET SDKs installed:
  3.1.417 [C:\Program Files\dotnet\sdk]
  5.0.406 [C:\Program Files\dotnet\sdk]
  6.0.201 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.23 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.15 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.3 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by pallavit** [comment]
@christothes could you please take a look and see if it is still an issue?
