### ISSUE TITLE
[BUG] Resource Manager exception when trying to list subscriptions

### ISSUE THREAD

**Issue by fogielpiotr** [Azure/azure-sdk-for-net#28162]
### Library name and version

Azure.ResourceManager 1.0.0

### Describe the bug

When trying to list Locations in SubscriptionResource object error is throwing

### Expected behavior

The function returns locations for subscription

### Actual behavior

System.FormatException: 'Input string was not in a correct format.'
error is throwing 
Stack Trace: 

   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at Azure.ResourceManager.Resources.Models.LocationMetadata.DeserializeLocationMetadata(JsonElement element)
   at Azure.ResourceManager.Resources.Models.LocationExpanded.DeserializeLocationExpanded(JsonElement element)
   at Azure.ResourceManager.Resources.Models.LocationListResult.DeserializeLocationListResult(JsonElement element)
   at Azure.ResourceManager.Resources.SubscriptionsRestOperations.<ListLocationsAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.ResourceManager.Resources.SubscriptionResource.<>c__DisplayClass47_0.<<GetLocationsAsync>g__FirstPageFunc|0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.<AsPages>d__4.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.ThrowForFailedGetResult(Int16 token)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.<AsPages>d__4.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.ThrowForFailedGetResult(Int16 token)
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\Studia\source\repos\ConsoleApp3\ConsoleApp3\Program.cs:line 12
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\Studia\source\repos\ConsoleApp3\ConsoleApp3\Program.cs:line 12

### Reproduction Steps

```
ArmClient client = new ArmClient(new DefaultAzureCredential());

var subscription = await client.GetDefaultSubscriptionAsync();

Console.WriteLine(subscription.Data.DisplayName);

await foreach (var location in subscription.GetLocationsAsync()) //with false/true includedExtendedLocation parameter the same
{
    Console.WriteLine(location.Name);
}
```

### Environment

OS : Windows 10
Project Sdk="Microsoft.NET.Sdk"
net6.0

"Azure.Identity" Version="1.6.0"
"Azure.ResourceManager" Version="1.0.0" 

IDE :
Microsoft Visual Studio Enterprise 2022 (64-bit)
Version 17.1.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArcturusZhang** [comment]
Hey @fogielpiotr sorry for this pending for so long.
I just have a try on my local machine, but the code you provided works well.
I checked the file where the exception was thrown, it has not been updated after the day it was introduced. Therefore if there was an issue, it is still there.
Because this API is listing something on your subscription, the issue might be related with the something on your subscription - is it OK to have the raw response when you call the API? This should help us to debug where it goes wrong.
Here is some guidance on how to enable request/response logging: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/README.md#setting-up-console-logging

**Comment by fogielpiotr** [comment]
Hi guys, 
thank you for the response. Currently, I don't have access to this subscription so we probably can close this ticket if the bug was related to specific subscriptions.
