### ISSUE TITLE
Method not found: 'System.Threading.Tasks.Task`1<!0> 

### ISSUE THREAD

**Issue by RyFive85** [Azure/azure-sdk-for-net#28210]
I'm trying to send a message to a queue from an .NET Framework 4.7.2 app and am getting on the call to sender.SendMessageAsync

`Method not found: 'System.Threading.Tasks.Task`1<!0> Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(System.TimeSpan, System.Threading.CancellationToken)'.`

I am using Azure.Messaging.ServiceBus 7.7.0. We haven't been having this issue for messages sent from our .NET Core 3.1 and .NET 6 function apps.

Is there something additional that needs to be considered when trying from a .NET Framework project?

**Comment by jsquire** [comment]
Hi @RyFive85.  Thank you for reaching out and we regret that you're experiencing difficulties.  It should be possible to use the client library from .NET Framework 4.7.2.   Our test runs include `net461` as a target platform, and they're passing.   I've also attempted to repro locally using `net472` and I'm able to publish and consume messages.

Would you be so kind as to include the set of error details, including the stack trace?   If it is possible for you to package a minimal repro, that would be extremely helpful.  Without the repro, our next best step would be to collect SDK logs so that we can understand the client perspective.  Details for doing so can be found in [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging).

**Comment by RyFive85** [comment]
@jsquire to start, here is the stack trace:

   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchInternalAsync>d__19.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.SendBatchInternalAsync(IEnumerable`1 messages, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendAsync>b__20_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__20`1.<<RunOperation>b__20_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__21`2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__20`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendAsync>d__20.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusSender.<SendMessagesAsync>d__26.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusSender.<SendMessageAsync>d__25.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Cpi.HoneyBee.DataAccess.Helpers.ServiceBusHelper.<SendMessageAsync>d__1.MoveNext() in C:\Users\rdowns\Source\HoneyBee\HoneyBee\Cpi.HoneyBee.DataAccess\Helpers\ServiceBusHelper.cs:line 34

**Comment by RyFive85** [comment]
@jsquire here's a minimal repro of some of our code. There is a commented out line because I've tried both; I wasn't sure if I could just pass an object (that is then converted into a Byte stream) or if it HAD to be a dynamic type before that conversion took place. The try-catch around the SendMessageAsync is just an effort to capture the error for this troubleshooting.

```
if (learnerCourse.EnrollmentID != null)
{
    //await _serviceBusHelper.SendMessageAsync("coursecompletion", new CourseCompletionRequest { UserId = learnerCourse.UserID, EnrollmentId = learnerCourse.EnrollmentID }, token);
    await _serviceBusHelper.SendMessageAsync("coursecompletion", JsonConvert.DeserializeObject<dynamic>(JsonConvert.SerializeObject(new CourseCompletionRequest { UserId = learnerCourse.UserID, EnrollmentId = learnerCourse.EnrollmentID })), token);
}
```

```
public interface IServiceBusHelper
{
    Task SendMessageAsync(string queueName, dynamic content, CancellationToken token);
}

public class ServiceBusHelper : IServiceBusHelper
{
    public ServiceBusHelper()
    {
    }

    public async Task SendMessageAsync(string queueName, dynamic content, CancellationToken token)
    {
        await using (ServiceBusClient client = new ServiceBusClient(ConfigurationManager.AppSettings["ServiceBusConnectionString"]))
        {
            byte[] contextByteStream = Encoding.ASCII.GetBytes(content.ToString());

            ServiceBusSender sender = client.CreateSender(queueName);

            ServiceBusMessage message = new ServiceBusMessage(contextByteStream);

            try
            {
                await sender.SendMessageAsync(message, token);
            }
            catch (Exception ex)
            {

            }
        }
    }
}
```

**Comment by jsquire** [comment]
Thanks, @RyFive85.  Are you able to package that in a small console application that fails in the same way as your application?  Understanding references, versions, and any binding redirects that are defined will be helpful.  In the abstract, I'm not able to repro with the snippets.  

Unrelated to the issue, I did want to mention a note form the snippet.  We'd recommend that you not create a new `ServiceBusSender` for each attempt to send a message.  For efficiency and performance, it would be better to create them once and cache/reuse unless you've got a very high number of queues that you're publishing to where the overhead would be prohibitive.  If you decide to keep creating the sender per-request, be sure that you close or dispose it.  By not doing so, the AMQP link that it uses is orphaned until it times out and the service force-disconnects it.   It also holds unmanaged resources that won't be cleaned up until the client is closed/disposed.

**Comment by RyFive85** [comment]
@jsquire for reasons that I'm unsure of, I built a console app using the same Framework version and C# version and it seemed to work. I tried removing the using around the Service Bus calls and that didn't work. I'm not sure where else to look to see what's different that isn't allowing this to flow.

**Comment by RyFive85** [comment]
It looks like I was able to revert the Azure.Messaging.ServiceBus package to version 7.0.0 and it worked. Not sure what the hang up is, but I guess that'll have to do for now.

**Comment by jsquire** [comment]
I suspect that your application has some conflict in dependencies that is forcing a downgrade of the references used by the Service Bus package.   Normally when we're talking the .NET Framework, this comes from implicit binding redirects added either by another reference or a framework component directing something to the GAC.   In this case, I'm not sure exactly what we'd be looking for, but likely something related to `System.Threading.Tasks.Extensions`, `Microsoft.Bcl.AsyncInterfaces`, or `System.Memory.Data`.

**Comment by RyFive85** [comment]
@jsquire I checked all of the suggested dependencies and I have all the latest versions of all, unless the suggestion is might need an older version. I was able to determine that the break happens somewhere between version 7.2.1 (works) and 7.3.0 (doesn't work) of Azure.Messaging.ServiceBus.

**Comment by JoshLove-msft** [comment]
It sounds like this could be due to the version of [Microsoft.Azure.Amqp](https://www.nuget.org/packages/Microsoft.Azure.Amqp/) that is being pulled in. The Cancellation token support was added in 2.5.3, but it seems your reference is somehow being downgraded (as @jsquire hypothesized). Can you see what version is being used? Can you manually set the version to be the latest (2.5.10) and see if the issue persists?

**Comment by jsquire** [comment]
@RyFive85:  Would you please be so kind as to share your main project file and any app.config-related assets?   I'd like to use them to try and reproduce locally.
