### ISSUE TITLE
[BUG] DefaultAzureCredential function when change to azure china, request scope have issue

### ISSUE THREAD

**Issue by yhs666** [Azure/azure-sdk-for-net#28409]
### Library name and version

Azure.Identity Version=1.6.0.0

### Describe the bug

Authenticate to Azure using environment variables:

setx  AZURE_CLIENT_ID "18fe11b***"
setx  AZURE_CLIENT_SECRET "****************"
setx  AZURE_TENANT_ID "****"
setx  AZURE_SUBSCRIPTION_ID "****"
setx  AZURE_AUTHORITY_HOST  "https://login.chinacloudapi.cn/"

  // Authenticate
  var credential = new DefaultAzureCredential(options);

When request access token, used fiddler capture as below:
![image](https://user-images.githubusercontent.com/3980889/165459817-dd901de0-bf56-40e0-95db-a70b2cc22269.png)

The request scope default used  "**https://management.azure.com//.default**",  But we used **Azure China**.  It's scope should be **https://management.chinacloudapi.cn/**

I can't find anything can change this default scope, Can you help fixed ?

### Expected behavior

Creating a resource group with name: rgnemv55358852fc35a
Azure.Identity.AuthenticationFailedException: ClientSecretCredential authentication failed: AADSTS500011: The resource principal named https://management.azure.com/ was not found in the tenant named Azure CXP. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 7c05fa24-80e8-4ead-bbc0-bf1caa66c600
Correlation ID: a904d2b7-d7af-49e7-9204-bfa509855ed2
Timestamp: 2022-04-27 06:55:58Z
 ---> MSAL.NetCore.4.39.0.0.MsalServiceException:
        ErrorCode: invalid_resource
Microsoft.Identity.Client.MsalServiceException: AADSTS500011: The resource principal named https://management.azure.com/ was not found in the tenant named Azure CXP. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
Trace ID: 7c05fa24-80e8-4ead-bbc0-bf1caa66c600
Correlation ID: a904d2b7-d7af-49e7-9204-bfa509855ed2
Timestamp: 2022-04-27 06:55:58Z
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.HandleTokenRefreshErrorAsync(MsalServiceException e, MsalAccessTokenCacheItem cachedAccessTokenItem)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ClientSecretCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
        StatusCode: 400
        ResponseBody: {"error":"invalid_resource","error_description":"AADSTS500011: The resource principal named https://management.azure.com/ was not found in the tenant named Azure CXP. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.\r\nTrace ID: 7c05fa24-80e8-4ead-bbc0-bf1caa66c600\r\nCorrelation ID: a904d2b7-d7af-49e7-9204-bfa509855ed2\r\nTimestamp: 2022-04-27 06:55:58Z","error_codes":[500011],"timestamp":"2022-04-27 06:55:58Z","trace_id":"7c05fa24-80e8-4ead-bbc0-bf1caa66c600","correlation_id":"a904d2b7-d7af-49e7-9204-bfa509855ed2","error_uri":"https://login.partner.microsoftonline.cn/error?code=500011"}
        Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: a904d2b7-d7af-49e7-9204-bfa509855ed2
x-ms-request-id: 7c05fa24-80e8-4ead-bbc0-bf1caa66c600
x-ms-ests-server: 2.1.12651.7 - CNE2LR2 ProdSlices
x-ms-clitelem: 1,500011,0,,
X-XSS-Protection: 0
Set-Cookie: fpc=AlNs7Ramu6ZBlsYirOVvB_IX11VZAQAAAP3f-tkOAAAA; expires=Fri, 27-May-2022 06:55:58 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=productionb; path=/; secure; samesite=none; httponly, stsservicecookie=estschina; path=/; secure; samesite=none; httponly
Date: Wed, 27 Apr 2022 06:55:58 GMT

   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.ClientSecretCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.EnvironmentCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.EnvironmentCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.EnvironmentCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.ResourceManager.Resources.ResourceGroupsRestOperations.CreateOrUpdateAsync(String resourceGroupName, ResourceGroup parameters, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.ResourceGroupsOperations.CreateOrUpdateAsync(String resourceGroupName, ResourceGroup parameters, CancellationToken cancellationToken)
   at Samples.Utilities.ResourceGroupHelper.CreateOrUpdateResourceGroup(String rgName, String location) in C:\Users\yang\Desktop\azure-samples-net-management\samples\utilities\ResourceGroupHelper.cs:line 33
   at CreateAppConfigurationSample.Program.RunSample(DefaultAzureCredential credential) in C:\Users\yang\Desktop\azure-samples-net-management\samples\appconfiguration\create-app-configuration\Program.cs:line 39
   at CreateAppConfigurationSample.Program.Main(String[] args) in C:\Users\yang\Desktop\azure-samples-net-management\samples\appconfiguration\create-app-configuration\Program.cs:line 21

C:\Users\yang\Desktop\azure-samples-net-management\samples\appconfiguration\create-app-configuration\bin\Debug\netcoreapp3.1\CreateAppConfigurationSample.exe (process 10452) exited with code 0.
To automatically close the console when debugging stops, enable Tools->Options->Debugging->Automatically close the console when debugging stops.

### Actual behavior

default request scope not change to azure china

### Reproduction Steps

chang azure env to azure china. run as below:

` public static async Task Main(string[] args)
        {
            try
            {
                //var options = new DefaultAzureCredentialOptions { AuthorityHost = AzureAuthorityHosts.AzureChina };
                // Authenticate
                var credential = new DefaultAzureCredential();
                await RunSample(credential);
            }
            catch (Exception ex)
            {
                Utilities.Log(ex);
            }
        }

        public static async Task RunSample(DefaultAzureCredential credential)
        {
            string subscriptionId = Environment.GetEnvironmentVariable("AZURE_SUBSCRIPTION_ID");
            string appConfigName = Utilities.RandomResourceName("appcnfg", 20);
            string rgName = Utilities.RandomResourceName("rgNEMV", 24);
            string region = "ChinaNorth2";

            var appConfigManagementClient = new AppConfigurationManagementClient(subscriptionId, credential);
            var configurationStores = appConfigManagementClient.ConfigurationStores;

            await ResourceGroupHelper.CreateOrUpdateResourceGroup(rgName, region);

            // Create an App Configuration
            Utilities.Log("Creating an App Configuration...");

            var configurationStore = new ConfigurationStore(region, new Sku("free"));

            var rawResult = await configurationStores.StartCreateAsync(rgName, appConfigName, configurationStore);
            var appConfiguration = (await rawResult.WaitForCompletionAsync()).Value;

            Utilities.Log("Created App Configuration");
            Utilities.PrintAppConfiguration(appConfiguration);
        }`

### Environment

azure Env: azure china

c# .net6

**Comment by schaabs** [comment]
@yhs666 Sorry you're running into trouble with this. Looks like you're properly setting the `AuthorityHost` of the credential to target azure china, but you also need to set the `Environment` on any management plane clients via `ArmClientOption` or the appropriate derived type for other management plane clients. You didn't include the code which is failing in `ResourceGroupHelper.CreateOrUpdateResourceGroup`, but here's an example of how to specify the `Environment` when creating an `ArmClient` which I'm assuming you're using to create the resource group.

```c#
var credential = new DefaultAzureCredential(new DefaultAzureCredentialOptions { AuthorityHost = AzureAuthorityHosts.AzureChina });

var resourceClient = new ArmClient(credential, "<subscription-id>", new ArmClientOptions { Environment = ArmEnvironment.AzureChina });
```

**Comment by yhs666** [comment]
@schaabs  It's working. Thanks for you update.

**Comment by schaabs** [comment]
@yhs666 glad you were able to get it working, and thanks for reaching out to confirm.
