### ISSUE TITLE
Key Vault ARM tests are throwing NRE

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#28419]
System.NullReferenceException : Object reference not set to an instance of an object.

```
   at Azure.ResourceManager.KeyVault.Tests.ManagedHsmTests.ManagedHsmFull() in /Users/runner/work/1/s/sdk/keyvault/Azure.ResourceManager.KeyVault/tests/ManagedHsmTests.cs:line 45
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by ArthurMa1978** [comment]
All these cases should not be running live, but previously its [Playbackonly] tag was removed by mistake, now it's fixed https://github.com/Azure/azure-sdk-for-net/pull/28408 .
Here the question is all mgmt. test cases are not support live running, so not sure why others are skipped withtout marked as [Playbackonly]. @HarveyLink please help to check.

**Comment by HarveyLink** [comment]
Closed as test passed in current pipeline.
