### ISSUE TITLE
[BUG]BlobServiceClient throws ArgumentOutOfRangeException: Unknown SkuName value.

### ISSUE THREAD

**Issue by sergey-meku** [Azure/azure-sdk-for-net#28581]
### Library name and version

Azure.Storage.Blobs 12.12.0

### Describe the bug

BlobServiceClient.GetAccountInfoAsync throws ArgumentOutOfRangeException

System.ArgumentOutOfRangeException: Unknown SkuName value. (Parameter 'value')
Actual value was Standard_GZRS.
   at Azure.Storage.Blobs.Models.SkuNameExtensions.ToSkuName(String value)
   at Azure.Storage.Blobs.ServiceGetAccountInfoHeaders.get_SkuName()
   at Azure.Storage.Blobs.BlobExtensions.ToAccountInfo(ResponseWithHeaders`1 response)
   at Azure.Storage.Blobs.BlobServiceClient.GetAccountInfoInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetAccountInfoAsync(CancellationToken cancellationToken)

or

System.ArgumentOutOfRangeException: Unknown SkuName value. (Parameter 'value')
Actual value was Standard_RAGZRS.
   at Azure.Storage.Blobs.Models.SkuNameExtensions.ToSkuName(String value)
   at Azure.Storage.Blobs.ServiceGetAccountInfoHeaders.get_SkuName()
   at Azure.Storage.Blobs.BlobExtensions.ToAccountInfo(ResponseWithHeaders`1 response)
   at Azure.Storage.Blobs.BlobServiceClient.GetAccountInfoInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.GetAccountInfoAsync(CancellationToken cancellationToken)

### Expected behavior

No exceptions thrown

### Actual behavior

Excetion thrown

### Reproduction Steps

Call BlobServiceClient.GetAccountInfoAsync for storage account with GZRS or RAGZRS sku.

**Comment by PramodValavala-MSFT** [comment]
@sergey-meku Thanks for bringing this up! We are assigning this to the concerning team for further review.

**Comment by obychyk** [comment]
Hi @PramodValavala-MSFT is there any update on this issue?

We are using Storage Account of type Standard_RAGZRS:
`"sku": {
        "name": "Standard_RAGZRS",
        "tier": "Standard"
    }`

I can see that in [SkuName.cs](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/src/Models/SkuName.cs) there is no such enum option.
