### ISSUE TITLE
[BUG] Vault Creation failed even passed all the required parameters

### ISSUE THREAD

**Issue by Yao725** [Azure/azure-sdk-for-net#28677]
### Library name and version

Azure.ResourceManager.KeyVault 1.0.0-beta.8

### Describe the bug

When creating a vault, following code will fail:
```csharp
ArmClient armClient = new ArmClient(new DefaultAzureCredential());
SubscriptionResource subscription = await armClient.GetDefaultSubscriptionAsync();
var rgLro = await subscription.GetResourceGroups().CreateOrUpdateAsync(WaitUntil.Completed, "testVaultCreate", new ResourceGroupData(AzureLocation.WestUS));
ResourceGroupResource resourceGroup = rgLro.Value;
VaultProperties vaultProperties = new VaultProperties(new Guid("myTenantId"), new KeyVaultSku(KeyVaultSkuFamily.A, KeyVaultSkuName.Standard));
VaultCreateOrUpdateContent content = new VaultCreateOrUpdateContent(AzureLocation.WestUS, vaultProperties);
var vaultLro = await resourceGroup.GetVaults().CreateOrUpdateAsync(WaitUntil.Completed, "testVault", content);
VaultResource vault = vaultLro.Value;
```

### Expected behavior

If `accessPolicies` is a required parameter, we should not have a ctor without this parameter. In contrast, if it is not required, the creationg using the sample code should succeed instead of throwing exception.

### Actual behavior

Creation failed with following message:
```
Azure.RequestFailedException : The parameter accessPolicies is not specified.
Status: 400 (Bad Request)
ErrorCode: BadRequest

Content:
{"error":{"code":"BadRequest","message":"The parameter accessPolicies is not specified."}}

Source=Azure.ResourceManager.KeyVault
  StackTrace:
   at Azure.ResourceManager.KeyVault.VaultsRestOperations.<CreateOrUpdateAsync>d__6.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Azure.ResourceManager.KeyVault.VaultCollection.<CreateOrUpdateAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at SdkTest.Program.<Main>d__0.MoveNext() in C:\Users\yaokou\source\repos\SdkTest\Program.cs:line 40
```

### Reproduction Steps

Using the sample code and `Azure.ResourceManager.KeyVault 1.0.0-beta.8` could repro the issue and get a 400 response.

**Comment by Yao725** [comment]
Close this issue as we have worked around this issue by customization.
