### ISSUE TITLE
Service Bus  :MaxAutoLockRenewalDuration not renewing lock getting MessageLockLost Exception 

### ISSUE THREAD

**Issue by annupriya-shell** [Azure/azure-sdk-for-net#28694]
### Library name and version

Azure.Messaging.ServiceBus 7.8.0

### Describe the bug

  var proc = client.CreateProcessor("managedQueue", options: new ServiceBusProcessorOptions
            {

                AutoCompleteMessages = false,
                PrefetchCount = 1,
                MaxAutoLockRenewalDuration = TimeSpan.FromSeconds(180)
            });
using the following ServiceBusProcessorOptions, message lock duration is set to 30 seconds. Still facing MessageLockLost exception if the message is processed in one minute.

Exception Details : Azure.Messaging.ServiceBus.ServiceBusException: The lock supplied is invalid. Either the lock expired, or the message has already been removed from the queue. For more information please see https://aka.ms/ServiceBusExceptions . Reference:a233b7a0-9a19-4bea-b5c7-ced7b07fa271, TrackingId:56aed59f-3658-4a04-b5ee-4a30529b8fcd_B14, SystemTracker:fps-sbrefactor:Queue:managedqueue, Timestamp:2022-05-11T15:54:30 (MessageLockLost)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.RenewMessageLockInternalAsync(Guid lockToken, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<RenewMessageLockAsync>b__55_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.RenewMessageLockAsync(Guid lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.RenewMessageLockAsync(Guid lockToken, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.RenewMessageLockAsync(ServiceBusReceivedMessage message, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ReceiverManager.RenewMessageLockAsync(ServiceBusReceivedMessage message, CancellationTokenSource cancellationTokenSource)

### Expected behavior

Since the MaxAutoLockRenewalDuration is set to three minutes , the lock should get renewed till 3 minutes and no error should be observed even if the message handler runs upto 3 minutes.

### Actual behavior

MaxAutoLockRenewalDuration is not renewing the lock and the lock lost exception is thrown.

### Reproduction Steps

Created a service bus queue with lock duration of 30 seconds and trying to post a message to the service bus queue. Attaching the git hub url of the sample application.
https://github.com/annupriya-shell/ServiceBusProcessorIssue
The setting of the service bus queue is attached 
![image](https://user-images.githubusercontent.com/102674357/167897632-3837e6ca-3ad7-4c28-a78a-83fea41c423b.png)

### Environment

OS : Windows 10
IDE : Visual Studio 2019
Dotnet Core Version : 3.1
Azure.Messaging.ServiceBus Version="7.8.0"

**Comment by annupriya-shell** [comment]
@Sandeep7OnShell created the issue regarding the service bus locklost exception

**Comment by JoshLove-msft** [comment]
@annupriya-shell, I tried going to the provided repo link and it didn't work. Can you make sure that the repo name is correct and that it is publicly accessible? Can you clarify how you are observing these exceptions? Is your error handler being invoked?

**Comment by JoshLove-msft** [comment]
@annupriya-shell, please make sure there are no secrets in your repo.

**Comment by annupriya-shell** [comment]
@JoshLove-msft  Yes the prefetch count was 1 in the scenario, but I have narrowed down the issue to my system clock time. My system clock time was apparently 40 sec back, so whenever the message was going for lock renewal the lock had expired and was getting this error. Post resetting it back not getting this issue.

**Comment by JoshLove-msft** [comment]
> @JoshLove-msft Yes the prefetch count was 1 in the scenario, but I have narrowed down the issue to my system clock time. My system clock time was apparently 40 sec back, so whenever the message was going for lock renewal the lock had expired and was getting this error. Post resetting the clock not getting this issue.

Ah, thanks for letting us know. This is something that we will need to document in our upcoming troubleshooting guide.
