### ISSUE TITLE
[BUG] Upgrading to WebJobs.Extensions.Storage 5.0.1 breaks Azure Function

### ISSUE THREAD

**Issue by Ansiem** [Azure/azure-sdk-for-net#28693]
### Library name and version

WebJobs.Extensions.Storage 5.0.1

### Describe the bug

Hi,

I have an Azure function app with mulitple functions and some of them use the Storage binding.
When Upgrading to v5.0.0.1 I get the following 403 error even though my connectionString is corect.
I downgraded to v5.0.0 and everything seems to work again.

### Expected behavior

Connection to blob storage.

### Actual behavior

[2022-05-11T15:54:40.069Z] An unhandled exception has occurred. Host is shutting down.
[2022-05-11T15:54:40.071Z] Azure.Storage.Blobs: The value for one of the HTTP headers is not in the correct format.
RequestId:e50c7fae-aaae-4d93-987e-faa4a72e80e2
Time:2022-05-11T15:54:39.987Z
[2022-05-11T15:54:40.072Z] Status: 400 (The value for one of the HTTP headers is not in the correct format.)
[2022-05-11T15:54:40.072Z] ErrorCode: InvalidHeaderValue
[2022-05-11T15:54:40.073Z]
[2022-05-11T15:54:40.073Z] Additional Information:
[2022-05-11T15:54:40.074Z] HeaderName: x-ms-version
[2022-05-11T15:54:40.074Z] HeaderValue: 2021-06-08
[2022-05-11T15:54:40.076Z]
[2022-05-11T15:54:40.077Z] Content:
[2022-05-11T15:54:40.078Z] <?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<Error>
  <Code>InvalidHeaderValue</Code>
  <Message>The value for one of the HTTP headers is not in the correct format.
RequestId:e50c7fae-aaae-4d93-987e-faa4a72e80e2
Time:2022-05-11T15:54:39.987Z</Message>
  <HeaderName>x-ms-version</HeaderName>
  <HeaderValue>2021-06-08</HeaderValue>
</Error>
[2022-05-11T15:54:40.080Z]
[2022-05-11T15:54:40.080Z] Headers:
[2022-05-11T15:54:40.081Z] Server: Azurite-Blob/3.14.1
[2022-05-11T15:54:40.082Z] x-ms-error-code: InvalidHeaderValue
[2022-05-11T15:54:40.083Z] x-ms-request-id: e50c7fae-aaae-4d93-987e-faa4a72e80e2
[2022-05-11T15:54:40.084Z] Date: Wed, 11 May 2022 15:54:39 GMT
[2022-05-11T15:54:40.085Z] Connection: keep-alive
[2022-05-11T15:54:40.086Z] Keep-Alive: REDACTED
[2022-05-11T15:54:40.086Z] Transfer-Encoding: chunked
[2022-05-11T15:54:40.087Z] Content-Type: application/xml
[2022-05-11T15:54:40.088Z] .

### Reproduction Steps

1) Create azure function app
2) Make sure WebJobs.Extensions.Storage 5.0.1 is installed
3) Create azure function with blob storage input
4) Run function

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19042
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.202\

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.4 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

**Comment by mecombem** [comment]
I'm experiencing the same type of issue however downgrading to 5.0.0 does not seem to resolve my issue.  

From debug.log (using local azurite emulator)
2022-05-11T12:33:36.054Z 	 error: ErrorMiddleware: ErrorName=StorageError ErrorMessage=The value for one of the HTTP headers is not in the correct format.  ErrorHTTPStatusCode=400 ErrorHTTPStatusMessage=The value for one of the HTTP headers is not in the correct format. ErrorHTTPHeaders={"x-ms-error-code":"InvalidHeaderValue","x-ms-request-id":"fbd15903-3776-47c8-835f-0852e89726a5"} ErrorHTTPBody="<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?>\n<Error>\n  <Code>InvalidHeaderValue</Code>\n  <Message>The value for one of the HTTP headers is not in the correct format.\nRequestId:fbd15903-3776-47c8-835f-0852e89726a5\nTime:2022-05-11T12:33:36.054Z</Message>\n  <HeaderName>x-ms-version</HeaderName>\n  <HeaderValue>2021-06-08</HeaderValue>\n</Error>" ErrorStack="StorageError: The value for one of the HTTP headers is not in the correct format.\n    at Function.getInvalidHeaderValue (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\errors\\StorageErrorFactory.js:210:16)\n    at Object.checkApiVersion (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\utils\\utils.js:9:45)\n    at blobStorageContextMiddleware (C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:34:21)\n    at C:\\snapshot\\_azure_azurite\\dist\\src\\blob\\middlewares\\blobStorageContext.middleware.js:15:16\n    at Layer.handle [as handle_request] (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\layer.js:95:5)\n    at trim_prefix (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:323:13)\n    at C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:284:7\n    at Function.process_params (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:341:12)\n    at next (C:\\snapshot\\_azure_azurite\\node_modules\\express\\lib\\router\\index.js:275:10)\n    at logger (C:\\snapshot\\_azure_azurite\\node_modules\\morgan\\index.js:144:5)"

From Visual Studio Console output
[2022-05-11T16:32:48.114Z] An unhandled exception has occurred. Host is shutting down.
[2022-05-11T16:32:48.114Z] Azure.Storage.Blobs: Service request failed.
[2022-05-11T16:32:48.115Z] Status: 400 (The value for one of the HTTP headers is not in the correct format.)
[2022-05-11T16:32:48.115Z] ErrorCode: InvalidHeaderValue
[2022-05-11T16:32:48.115Z]
[2022-05-11T16:32:48.116Z] Headers:
[2022-05-11T16:32:48.116Z] Server: Azurite-Blob/3.16.0
[2022-05-11T16:32:48.116Z] x-ms-error-code: InvalidHeaderValue
[2022-05-11T16:32:48.117Z] x-ms-request-id: bce9d214-5df8-49b8-9001-d71e1ae1a101
[2022-05-11T16:32:48.117Z] Date: Wed, 11 May 2022 16:32:48 GMT
[2022-05-11T16:32:48.117Z] Connection: keep-alive
[2022-05-11T16:32:48.118Z] Keep-Alive: REDACTED
[2022-05-11T16:32:48.118Z] .

**Comment by Ansiem** [comment]
@mecombem The issues seemed to be fixed by downgrading to 5.0.0 however I am also getting the error again.

**Comment by BrettBailey** [comment]
If its any help I am seeing same behaviour. I have a blob input binding in a brand new project in vs2022. Running up the function gives same InvalidHeaderValue errors.  Downgrading from v5.0.1 to 5.0.0 then clean and build seems to have sorted it.

**Comment by navba-MSFT** [comment]
@Ansiem Thanks for reaching out to us and sharing this feedback. Looking at the error message its pretty clear that the 400 error status with Invalid Header was due to the x-ms-version: 2021-06-08 being sent by the Blob Storage SDK wasn't matching the version used by the Azurite.

This is a known issue and it is documented [here](https://github.com/Azure/Azurite#api-version-compatible-strategy).
>If an incoming request has a higher API version than Azurite, Azurite will return a InvalidHeaderValue error for x-ms-version (HTTP status code 400 - Bad Request).

You can run the below command to find the version of Azurite.

azurite.exe --version

**Below are the steps that I followed to fix this issue:**
I deleted the contents of the below folder.

C:\Program Files\Microsoft Visual Studio\2022\Professional\Common7\IDE\Extensions\Microsoft\Azure Storage Emulator
C:\Program Files (x86)\Microsoft SDKs\Azure\Storage Emulator

The Storage Emulator is available as part of the [Microsoft Azure SDK](https://azure.microsoft.com/downloads/). You can also install the Storage Emulator by using the [standalone installer](https://go.microsoft.com/fwlink/?linkid=717179&clcid=0x409) (direct download).

I upgraded my Azurite version to the most recent version [3.17.1](https://github.com/Azure/Azurite/releases/tag/v3.17.1) and that resolved the issue.

npm i azurite@3.17.1

Launch Visual Studio again and test the FunctionApp. Hope this helps. Please let me know if you still face this issue. Awaiting your reply.

**Comment by navba-MSFT** [comment]
@Ansiem I wanted to do quick follow-up to check if you had a chance to look at my above comment. Please let us know if you need any further assistance on this. Awaiting your reply.

**Comment by TerrySansom** [comment]
@navba-MSFT  - I followed your suggestion and fixed this issue, spend last half of yesterday on wondering why I was getting a 400.  I have set up many BlobTrigger functions.

**Comment by navba-MSFT** [comment]
@TerrySansom I am glad that my above suggestion helped in solving your issue. 

@Ansiem We will now proceed with closure of this github issue. If you need any further assistance on this issue in future, please feel free to reopen this thread. We would be happy to help.
