### ISSUE TITLE
Why would DefaultAzureCredential not find Visual Studio when I have 3 versions installed?

### ISSUE THREAD

**Issue by shueybubbles** [Azure/azure-sdk-for-net#28776]
### Library name and version

Azure.Identity 1.5.0

### Query/Question

We have tests that rely on DefaultAzureCredential to access Azure Key Vault. On one of my on-premises VMs the tests can't get a credential, even though I am running the test in Visual Studio 2022.
VS is logged in to Azure. How do I figure out why it's not seeing VS?
VS 2022 doesn't have an "Azure Service Authentication" setting in Tools/Options.

![image](https://user-images.githubusercontent.com/2224906/168390478-7278d360-ecb0-49bb-b768-7a60d57ba1c0.png)

```
  Message: 
Test method Microsoft.SqlServer.Test.SMO.GeneralFunctionality.DatabaseSmoTests.Database_transaction_counts threw exception: 
Azure.Identity.CredentialUnavailableException: DefaultAzureCredential failed to retrieve a token from the included credentials. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/defaultazurecredential/troubleshoot
- EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot
- ManagedIdentityCredential authentication unavailable. Multiple attempts failed to obtain a token from the managed identity endpoint.
- No installed instance of Visual Studio was found
- Stored credentials not found. Need to authenticate user in VSCode Azure Account. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/vscodecredential/troubleshoot
- Azure CLI not installed
- PowerShell is not installed. ---> System.AggregateException: Multiple exceptions were encountered while attempting to authenticate. ---> Azure.Identity.CredentialUnavailableException: EnvironmentCredential authentication unavailable. Environment variables are not fully configured. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/environmentcredential/troubleshoot

  Stack Trace: 

...

    ---> (Inner Exception #2) Azure.Identity.CredentialUnavailableException: No installed instance of Visual Studio was found
   at Azure.Identity.VisualStudioCredential.<GetTokenImplAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.VisualStudioCredential.<GetTokenImplAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Identity.VisualStudioCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.<GetTokenFromSourcesAsync>d__15.MoveNext()<---
```

### Environment

Windows 10 with VS 2022 17.2 and VS 2019 16.11.13
VS has my Azure account synced across all devices.

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by mcm2020** [comment]
I am having the same issue

**Comment by schaabs** [comment]
@shueybubbles sorry you're having trouble with this. To get the `Azure Service Authentication` settings page in the options dialog you need to make sure that you have the `Azure development` workload installed. This can be done via the Visual Studio Installer, by modifying your install, 

![image](https://user-images.githubusercontent.com/11322348/170764675-960228f8-2de8-4c8a-8596-41e3213c668f.png)

Then ensure  `Azure developement` workload is installed:

![image](https://user-images.githubusercontent.com/11322348/170765105-38226aef-f67c-456b-ac18-b5d1eb8f21fb.png)

**Comment by christothes** [comment]
Hi @shueybubbles  - Could it be related to which user account is being used? The VS credential relies on this file to find the token provider:

`Users\<user>\AppData\Local\.IdentityService\AzureServiceAuth\tokenprovider.json`

Does the user profile that is running the code have this file?

**Comment by shueybubbles** [comment]
In my case it was the missing Azure Development workload
