### ISSUE TITLE
.NET generator request - handle deserializing string -> DateTimeOffset? when string is empty

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#28979]
### Library name and version

.NET autorest generator

### Describe the bug

We are seeing intermittent live test failures in the .NET Storage live test pipeline around the unit test GetStatisticsAsync - https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1554308&view=ms.vss-test-web.build-test-results-tab&runId=31550042&resultId=105515&paneView=debug
 
Our current theory is that when BlobServiceClient.GetStatisticsAsync() is called on a storage account that is provisioning, LastSyncTime is being returned as an empty string.
 
This is resulting in the following error:

System.FormatException : String '' was not recognized as a valid DateTime.

 

 at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles, TimeSpan& offset)

at System.DateTimeOffset.Parse(String input, IFormatProvider formatProvider, DateTimeStyles styles)

at Azure.Core.TypeFormatters.ParseDateTimeOffset(String value, String format) in /_/microsoft.azure.autorest.csharp/3.0.0-beta.20220505.3/content/Generator.Shared/TypeFormatters.cs:line 130

at Azure.Core.XElementExtensions.GetDateTimeOffsetValue(XElement element, String format) in /_/microsoft.azure.autorest.csharp/3.0.0-beta.20220505.3/content/Generator.Shared/XElementExtensions.cs:line 23

at Azure.Storage.Blobs.Models.BlobGeoReplication.DeserializeBlobGeoReplication(XElement element)in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\Generated\Models\BlobGeoReplication.Serialization.cs:line 26

at Azure.Storage.Blobs.Models.BlobServiceStatistics.DeserializeBlobServiceStatistics(XElement element) in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\Generated\Models\BlobServiceStatistics.Serialization.cs:line 20

at Azure.Storage.Blobs.ServiceRestClient.GetStatistics(Nullable`1 timeout, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\Generated\ServiceRestClient.cs:line 246

at Azure.Storage.Blobs.BlobServiceClient.GetStatisticsInternal(Boolean async, CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\BlobServiceClient.cs:line 1229

at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task) in D:\a\_work\1\s\sdk\core\Azure.Core\src\Shared\TaskExtensions.cs:line 33

at Azure.Storage.Blobs.BlobServiceClient.GetStatistics(CancellationToken cancellationToken) in D:\a\_work\1\s\sdk\storage\Azure.Storage.Blobs\src\BlobServiceClient.cs:line 1145

 

Could we get the .NET code generator updated to handle deserialing and empty string -> DateTimeOffset? to return null?

 

Thanks!

### Expected behavior

.

### Actual behavior

.

### Reproduction Steps

.

**Comment by jsquire** [comment]
I'm going to transfer this to the [autorest.csharp](https://github.com/Azure/autorest.csharp/issues) repository so that the right folks have visibility on this request.
