### ISSUE TITLE
[BUG] Unable to access Azure Table Storage using Visual Studio credentials.

### ISSUE THREAD

**Issue by JeremyTCD** [Azure/azure-sdk-for-net#29024]
### Library name and version

Azure.Identity 1.6.0, Azure.Data.Tables 12.5.0

### Describe the bug

Unable to access Azure Table Storage using Visual Studio credentials.

### Expected behavior

Table storage APIs should not throw authentication exceptions.

### Actual behavior

`CredentialUnavailableException` is thrown.

### Reproduction Steps

Minimal reproduction:

```cs
internal class Program
{
    static async Task Main(string[] _)
    {
        // Enable logging
        using AzureEventSourceListener listener = AzureEventSourceListener.CreateConsoleLogger();

        // Create DefaultAzureCredential with all options disabled other than VS credentials
        var credentials = new DefaultAzureCredential(new DefaultAzureCredentialOptions
        {
            ExcludeEnvironmentCredential = true,
            ExcludeAzureCliCredential = true,
            ExcludeVisualStudioCodeCredential = true,
            ExcludeAzurePowerShellCredential = true,
            ExcludeInteractiveBrowserCredential = true,
            ExcludeManagedIdentityCredential = true,
            ExcludeSharedTokenCacheCredential = true,
            // ExcludeVisualStudioCredential = true
        });

        // Create a table service client
        var tableServiceClient = new TableServiceClient(new Uri("https://pictoriatestinggpv2.table.core.windows.net"), credentials);

        // Attempt to create a table, throws CredentialUnavailableException
        await tableServiceClient.CreateTableIfNotExistsAsync("Test");
    }
}
```

Notes:

- As per guidance [here](https://docs.microsoft.com/en-us/azure/storage/tables/authorize-access-azure-active-directory), I've assigned the "Storage Table Data Contributor" role to my account:
   ```powershell
   PS C:\Users\Jeremy> New-AzRoleAssignment -ObjectId "<redacted>" -RoleDefinitionName "Storage Table Data Contributor" -ResourceGroupName "Pictoria"

  RoleAssignmentName : <redacted>
  RoleAssignmentId   : /subscriptions/<redacted>/resourceGroups/Pictoria/providers/Microsoft.Authorization/roleAssignments/<redacted>
  Scope              : /subscriptions/<redacted>/resourceGroups/Pictoria
  DisplayName        : Jeremy Tan
  SignInName         : jeremytcd_jering.tech#EXT#@jeremytcdjering.onmicrosoft.com
  RoleDefinitionName : Storage Table Data Contributor
  RoleDefinitionId   : <redacted>
  ObjectId           : <redacted>
  ObjectType         : User
  CanDelegate        : False
  Description        :
  ConditionVersion   :
  Condition          :
   ```
- If I disable all options other than PowerShell credentials, the operation succeeds:
   ```cs
    // Create DefaultAzureCredential with all options disabled other than VS credentials
    var credentials = new DefaultAzureCredential(new DefaultAzureCredentialOptions
    {
        ExcludeEnvironmentCredential = true,
        ExcludeAzureCliCredential = true,
        ExcludeVisualStudioCodeCredential = true,
        // PowerShell credentials work
        // ExcludeAzurePowerShellCredential = true,
        ExcludeInteractiveBrowserCredential = true,
        ExcludeManagedIdentityCredential = true,
        ExcludeSharedTokenCacheCredential = true,
        ExcludeVisualStudioCredential = true
    });
   ```
- However, I would like to use VS credentials. Attempting to do so produces the following error logs:
   ```
    [Informational] Azure-Identity: DefaultAzureCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] 
    ParentRequestId: 492caebc-df1b-4cc2-94fc-b6aa5da97509
    [Informational] Azure-Identity: VisualStudioCredential.GetToken invoked. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 492caebc-df1b-4cc2-94fc-b6aa5da97509
    [Informational] Azure-Identity: VisualStudioCredential.GetToken was unable to retrieve an access token. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 492caebc-df1b-4cc2-94fc-b6aa5da97509 Exception: Azure.Identity.CredentialUnavailableException (0x80131500): Process "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS004: Unable to get access token.  'AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '872cd9fa-d31f-45e0-9eab-6e460a02d1f1'(Visual Studio) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
    Trace ID: c570c43e-05dc-46ef-aeb6-2a1c896c1900
    Correlation ID: c3d39bb4-cbec-4cae-b670-2e13ad4639f5
    Timestamp: 2022-05-28 17:21:05Z'.
     ---> System.InvalidOperationException (0x80131509): TS003: Error, TS004: Unable to get access token.  'AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '872cd9fa-d31f-45e0-9eab-6e460a02d1f1'(Visual Studio) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
    Trace ID: c570c43e-05dc-46ef-aeb6-2a1c896c1900
    Correlation ID: c3d39bb4-cbec-4cae-b670-2e13ad4639f5
    Timestamp: 2022-05-28 17:21:05Z'
    [Informational] Azure-Identity: DefaultAzureCredential.GetToken was unable to retrieve an access token. Scopes: [ https://storage.azure.com/.default ] ParentRequestId: 492caebc-df1b-4cc2-94fc-b6aa5da97509 Exception: Azure.Identity.CredentialUnavailableException (0x80131500): Process "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS004: Unable to get access token.  'AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '872cd9fa-d31f-45e0-9eab-6e460a02d1f1'(Visual Studio) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
    Trace ID: c570c43e-05dc-46ef-aeb6-2a1c896c1900
    Correlation ID: c3d39bb4-cbec-4cae-b670-2e13ad4639f5
    Timestamp: 2022-05-28 17:21:05Z'.
     ---> System.InvalidOperationException (0x80131509): TS003: Error, TS004: Unable to get access token.  'AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '872cd9fa-d31f-45e0-9eab-6e460a02d1f1'(Visual Studio) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
    Trace ID: c570c43e-05dc-46ef-aeb6-2a1c896c1900
    Correlation ID: c3d39bb4-cbec-4cae-b670-2e13ad4639f5
    Timestamp: 2022-05-28 17:21:05Z'
    Unhandled exception. Azure.Identity.CredentialUnavailableException: Process "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\Asal\TokenService\Microsoft.Asal.TokenService.exe" has failed with unexpected error: TS003: Error, TS004: Unable to get access token.  'AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '872cd9fa-d31f-45e0-9eab-6e460a02d1f1'(Visual Studio) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
    Trace ID: c570c43e-05dc-46ef-aeb6-2a1c896c1900
    Correlation ID: c3d39bb4-cbec-4cae-b670-2e13ad4639f5
    Timestamp: 2022-05-28 17:21:05Z'.
     ---> System.InvalidOperationException: TS003: Error, TS004: Unable to get access token.  'AADSTS50020: User account '{EmailHidden}' from identity provider 'live.com' does not exist in tenant 'Microsoft Services' and cannot access the application '872cd9fa-d31f-45e0-9eab-6e460a02d1f1'(Visual Studio) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.
    Trace ID: c570c43e-05dc-46ef-aeb6-2a1c896c1900
    Correlation ID: c3d39bb4-cbec-4cae-b670-2e13ad4639f5
    Timestamp: 2022-05-28 17:21:05Z'
       at Azure.Identity.VisualStudioCredential.RunProcessesAsync(List`1 processStartInfos, Boolean async, CancellationToken cancellationToken)
       --- End of inner exception stack trace ---
       at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
       at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
       at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
       at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
       at Azure.Identity.DefaultAzureCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
       at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueFromCredentialAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
       at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
       at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.GetHeaderValueAsync(HttpMessage message, TokenRequestContext context, Boolean async)
       at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AuthenticateAndAuthorizeRequestAsync(HttpMessage message, TokenRequestContext context)
       at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
       at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
       at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
       at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
       at Azure.Data.Tables.TableRestClient.CreateAsync(TableProperties tableProperties, Nullable`1 responsePreference, QueryOptions queryOptions, CancellationToken cancellationToken)
       at Azure.Data.Tables.TableServiceClient.CreateTableIfNotExistsAsync(String tableName, CancellationToken cancellationToken)
       at Learning.AzureTableStorage.Program.Main(String[] _) in C:\Projects\Pictoria\Pictoria.Learning\Learning.AzureTableStorage\Learning.AzureTableStorage\Program.cs:line 30
       at Learning.AzureTableStorage.Program.<Main>(String[] _)
   ```
- As per [this issue](https://github.com/Azure/azure-sdk-for-net/issues/28776#issuecomment-1139897295), I've added the Azure development workload to my VS installation and within VS, I've selected my account under tools > options > Azure Service Authentication > Account Selection. I've re-signed in several times to no avail.

### Environment

Visual Studio 17.2.2

Dotnet:
```
PS C:\Users\Jeremy> dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.300
 Commit:    8473146e7d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19043
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.300\

Host (useful for support):
  Version: 6.0.5
  Commit:  70ae3df4a6
```

**Comment by JeremyTCD** [comment]
Got it working by setting `DefaultAzureCredentialOptions.VisualStudioTenantId` to my AD directory tenant ID.
