### ISSUE TITLE
[BUG] - ServiceBusSessionReceiver logs error when trying to get next session and none is available

### ISSUE THREAD

**Issue by dfaivre-pcs** [Azure/azure-sdk-for-net#29066]
### Library name and version

Azure.Messaging.ServiceBus 7.7.0

### Describe the bug

When creating a `ServiceBusSessionReceiver` using `ServiceBusClient.AcceptNextSessionAsync`, given that there are no available sessions and given that the user code catches and handles the `ServiceBusException (ServiceTimeout)` exception that signifies it, and error is still logged to `Microsoft.Extensions.Logging` and the `Error` level. This causes a large amount of log messages and extra cost in ApplicationInsights, and doesn't seem to warrant the `Error` level, since all that is required is to see if there is a next session available to process.

### DEBUG log from catching the exception when no available sessions are found (user code)
```
[10:41:04 DBG] No unlocked sessions found: workflow-events/processing/processed-layer-input-changed/36e7dd97-ad58-4856-b476-baeb1b4d4757
Azure.Messaging.ServiceBus.ServiceBusException: The operation did not complete within the allocated time 00:01:00 for object receiver126. (ServiceTimeout)
 ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object receiver126.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectAsync(AmqpObject target, TimeSpan timeout, CancellationToken cancellationToken, String entityPath)
   at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, CancellationToken
 cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<OpenLinkAsync>b__72_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenLinkAsync(CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.OpenLinkAsync(CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.CreateSessionReceiverAsync(String entityPath, ServiceBusConnection connection, ServiceBusSessionReceiverOptions options, String sessionId, CancellationToken cancellationToken, Boolean isProcessor)
   at Azure.Messaging.ServiceBus.ServiceBusClient.AcceptNextSessionAsync(String queueName, ServiceBusSessionReceiverOptions options, CancellationToken cancellationToken)
   at PremierCrop.Workflow.Framework.Events.Services.EventSessionManager.RunHandlerAsync(CancellationToken cancellationToken) in C:\dev\pcs\repos\PremierCrop\src\Workflow\PremierCrop.Workflow\Framework\Events\Services\EventSessionManager.cs:line 72
```

### Duplicate ERROR level framework log
```
fail: Azure.Messaging.ServiceBus[79]
      An exception occurred while creating a ServiceBusSessionReceiver (Namespace 'pcs-live-jobs.servicebus.windows.net', Entity path 'workflow-events/processing/processed-layer-input-changed/36e7dd97-ad58-4856-b476-baeb1b4d4757'). Error Message: 'Azure.M
essaging.ServiceBus.ServiceBusException: The operation did not complete within the allocated time 00:01:00 for object receiver134. (ServiceTimeout)
       ---> System.TimeoutException: The operation did not complete within the allocated time 00:01:00 for object receiver134.
         at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
         at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
         at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
         at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
      --- End of stack trace from previous location ---
         at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenAmqpObjectAsync(AmqpObject target, TimeSpan timeout, CancellationToken cancellationToken, String entityPath)
         at Azure.Messaging.ServiceBus.Amqp.AmqpConnectionScope.OpenReceiverLinkAsync(String identifier, String entityPath, TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String sessionId, Boolean isSessionReceiver, Cancellatio
nToken cancellationToken)
         at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenReceiverLinkAsync(TimeSpan timeout, UInt32 prefetchCount, ServiceBusReceiveMode receiveMode, String identifier, CancellationToken cancellationToken)
         at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
         at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
         at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
         at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<OpenLinkAsync>b__72_0>d.MoveNext()
      --- End of stack trace from previous location ---
         at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken)
         at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.OpenLinkAsync(CancellationToken cancellationToken)
         at Azure.Messaging.ServiceBus.ServiceBusReceiver.OpenLinkAsync(CancellationToken cancellationToken)
         at Azure.Messaging.ServiceBus.ServiceBusSessionReceiver.CreateSessionReceiverAsync(String entityPath, ServiceBusConnection connection, ServiceBusSessionReceiverOptions options, String sessionId, CancellationToken cancellationToken, Boolean isProcessor)'
```

### Expected behavior

Only actual `Errors` are logged, especially in noisy code paths. Specifically, when checking if there is an open session to handle, if there isn't one, do not produce error logs.

### Actual behavior

Logs fill up with errors that are not errors

### Reproduction Steps

- Create Service Bus Queue with session enabled
- Create `ServiceBusClient`
- Request `ServiceBusClient.AcceptNextSessionAsync` from created queue

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
