### ISSUE TITLE
Azure client runtime UserAgent header initialization casues exception on Windows Server 2008

### ISSUE THREAD

**Issue by matthchr** [Azure/azure-sdk-for-net#2929]
A customer of ours has hit the following exception when initializing our client:

```
The format of value 'Windows_Server_(R)_2008_Standard' is invalid.
   at System.Net.Http.Headers.HeaderUtilities.CheckValidToken(String value, String parameterName)
   at System.Net.Http.Headers.ProductHeaderValue..ctor(String name, String version)
   at Microsoft.Rest.ServiceClient`1.SetDefaultUserAgentInfo()
   at Microsoft.Rest.ServiceClient`1.SetUserAgent(String productName, String version)
   at Microsoft.Rest.ServiceClient`1.InitializeHttpClient(HttpClientHandler httpClientHandler, DelegatingHandler[] handlers)
   at Microsoft.Azure.Batch.Protocol.BatchServiceClient..ctor(Uri baseUri, ServiceClientCredentials credentials, DelegatingHandler[] handlers)
   at Microsoft.Azure.Batch.ProtocolLayer..ctor(String baseURL, ServiceClientCredentials credentials)
   at Microsoft.Azure.Batch.BatchClient..ctor(BatchSharedKeyCredentials credentials)
   at Microsoft.Azure.Batch.BatchClient.OpenAsync(BatchSharedKeyCredentials credentials)
   at Microsoft.Azure.Batch.BatchClient.Open(BatchSharedKeyCredentials credentials)
   at AzureSDK.Program.TestBatch() in D:\\VisualStudio2015\\AzureSDK\\AzureSDK\\Program.cs:line 56

```

The issue seems to be the value retrieved from `ReadHKLMRegistry(@"SOFTWARE\Microsoft\Windows NT\CurrentVersion", "ProductName")` -- it is: `Windows Server (R) 2008 Enterprise`

I traced this to this code in the client runtime:
```
        private string OsName
        {
            get
            {  
                if(string.IsNullOrEmpty(_osName))
                {
                    _osName = ReadHKLMRegistry(@"SOFTWARE\Microsoft\Windows NT\CurrentVersion", "ProductName");
                }

                // If you want to log OsName in userAgent, it has to be without spaces
                if (!string.IsNullOrEmpty(_osName))
                {
                    _osName = _osName.Replace(" ", "_");
                }

                return _osName;
            }
        }
```

It looks like .NET forbids `(` and `)` in the HTTP headers (see [here](https://github.com/dotnet/corefx/blob/master/src/System.Net.Http/src/System/Net/Http/HttpRuleParser.cs)).

This means that clients can't be used on Win Server 2008 (or any other windows sku that puts a parenthesis in the OsName).

The fix seems to be that we should update the `OsName` property to correctly replace all invalid characters (not just spaces).

**Comment by shahabhijeet** [comment]
Fix in testing
https://github.com/Azure/azure-sdk-for-net/pull/3141

**Comment by ruant** [comment]
@shahabhijeet Why isn't `/` in the list of special chars?

**Comment by ruant** [comment]
After a bit more digging the problem I have isn't 100% matching this one. But really similar.
It's not the OS failing, it's the version of my application that crashes it.

Perhaps `CleanUserAgentInfoEntry` should be run on on `_clientVersion` before returning it.
And add support for `/`

**Comment by ruant** [comment]
https://github.com/Azure/azure-sdk-for-net/pull/4669
