### ISSUE TITLE
[BUG] Simultaneous EventHub healthchecks result in 'This operation is only allowed using a successfully authenticated context.'

### ISSUE THREAD

**Issue by MichalLechowski** [Azure/azure-sdk-for-net#29388]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.EventHubs 5.1.0

### Describe the bug

I have a simple .NET 6 WebJob (Console App) with Kafka input / EventHub output function. Dummy code since I cannot share exact production code for obvious reasons:

```
public async Task KafkaConsumer_OutputEventHubAsync(
        [KafkaTrigger("kafkaserver", "topic", ConsumerGroup = "consumergroup")] KafkaEventData<string, string>[] kafkaEvents,
        [EventHub("eventhubname", Connection = "ehnconnstring")]
        IAsyncCollector<string> outputMessages, ILogger logger)
        {
            foreach (var kafkaEvent in kafkaEvents)
            {
                try
                {
                    await outputMessages.AddAsync(kafkaEvent.Value);
                } 
                catch 
                { 
                    handle_error();
                }
             }
         }

```

So nothing extraordinary here BUT since I have it running in Kubernetes (AKS) and it's set up with autoscaler (KEDA), I also need to check readiness and liveness of Kafka consumers. So readiness probe checks connectivity to Kafka and EventHub, for Kafka everything works fine but for EventHub I get a lot of exceptions "'This operation is only allowed using a successfully authenticated context." and that happens almost always only for topics which are being consumed by multiple consumers at once (autoscaled by KEDA) and that problem doesn't seem to happen if there is only 1 consumer running.

So the logic of readiness healthcheck is a simple TCP listener:

Program.cs registration:

```
services.AddHealthChecks()
            .AddCheck<ReadinessprobeHealthCheck>("readiness_probe_hc");
services.AddHostedService<TcpHealthProbeService>();
```

```
 public class TcpHealthProbeService : BackgroundService
    {
        private readonly TcpListener _listenerReadiness;

        public TcpHealthProbeService(HealthCheckService healthCheckService)
        {
            _healthCheckService = healthCheckService;
            _listenerReadiness = new TcpListener(IPAddress.Any, readyPort);
        }

        protected override async Task ExecuteAsync(CancellationToken stoppingToken)
        {
            await Task.Yield();
            Log.Information("Started health check service.");
            _listenerReadiness.Start();
            while (!stoppingToken.IsCancellationRequested)
            {
                await UpdateHeartbeatAsync(stoppingToken);
                Thread.Sleep(TimeSpan.FromSeconds(30));
            }
            _listenerReadiness.Stop();
        }

private async Task UpdateHeartbeatAsync(CancellationToken token)
        {
            try
            {
                var result = await _healthCheckService.CheckHealthAsync(token);

                if (result.Entries["readiness_probe_hc"].Status != HealthStatus.Healthy)
                {
                    _listenerReadiness.Stop();
                    Log.Error("Service is not ready. Readiness probe failed. Listener stopped.");
                    return;
                }

                _listenerReadiness.Start();
                while (_listenerReadiness.Server.IsBound && _listenerReadiness.Pending())
                {
                    var client = await _listenerReadiness.AcceptTcpClientAsync();
                    try
                    {
                        client.Client.Shutdown(SocketShutdown.Both);   // I tried with or without it, doesn't make any difference
                    }
                    finally
                    {
                        client.Close();
                    }
                }
            }
            catch (Exception ex)
            {
                Log.Error($"An error occurred while checking health probes. Ex: {ex.Message});
            }
        }
```

And finally the EventHub check itself:

```
public class ReadinessprobeHealthCheck : IHealthCheck
    {
        private readonly IConfiguration _configuration;

        public ReadinessprobeHealthCheck(IConfiguration configuration)
        {
            _configuration = configuration;
        }

        public async Task<HealthCheckResult> CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken = new CancellationToken())
        {
                var connectionString = _configuration["ehnconnstring"];
                var eventHubName = _configuration["eventhubname"];
                var eventHubProducer = new EventHubProducerClient(connectionString, eventHubName);
                _ = await eventHubProducer.GetEventHubPropertiesAsync(cancellationToken);
            }
            catch (Exception ex)
            {
                return Task.FromResult(new HealthCheckResult(HealthStatus.Unhealthy, exception: ex)).Result;
            }
            return Task.FromResult(new HealthCheckResult(HealthStatus.Healthy)).Result;
        }
    }
```

And I have similar logic for Kafka consumer, I set up a Kafka consumer and get some metadata and if it gets picked up properly then I consider Kafka available. 

### Expected behavior

GetEventHubPropertiesAsync should always return properties without throwing an error even if there are multiple instances of the same consumer app requesting for it at the same time (which is probably the case, I am not sure).

### Actual behavior

Regularly throwing:
"An exception occurred while retrieving properties for Event Hub: itxpt.sensors.odometer.v1. Error Message: 'This operation is only allowed using a successfully authenticated context." 

And there is like absolutely nothing about such error in the docs, I don't even know where to start. Since that kinda points to authentication, I'll add that I am using SAS policy with all the claims (Listen, Send, Manage) to authenticate to EventHub. It's basically exactly the same as Output trigger of the function.

I am thinking if maybe the readiness probe is triggered too fast but I already delayed it quite a bit and the app doesn't take long to start, in fact it starts pretty quickly. Just for the record configuration of the probe:

```
readinessProbe:
            tcpSocket:
              port: 1000
            initialDelaySeconds: 25   //that should be plenty and it's been increased already, doesn't make any difference
            failureThreshold: 2
            timeoutSeconds: 5
            periodSeconds: 120
```

### Reproduction Steps

Pretty much exact code in description but it won't happen unless you run multiple instances for the same topic at once.

### Environment

AKS on Ubuntu nodes
Kubernetes: 1.22.6
Nodes: AKSUbuntu-1804gen2containerd-2022.05.10
Dotnet: .NET 6 standalone WebJob based on Console App template
Deploy: Docker image

**Comment by jsquire** [comment]
Hi @MichalLechowski.   Thank you for reaching out and we regret that you're experiencing difficulties.  The error message that you shared, "This operation is only allowed using a successfully authenticated context" does not come from the Event Hubs client and is not formatted as I'd expect an Event Hubs service error to be.  Would you please share the full error details (type, message, reason code, inner exception) and stack trace?

There is one thing that jumps out at me from the code that was shared.  In `CheckHealthAsync`, you're creating a new Event Hubs client for each call, but never closing or disposing it.   Each client will create new connection which is then abandoned and will continue to exist util it hits an idle timeout (~20 minutes).   During that time, it is occupying a web socket on your host and since your health probe is firing every 2 minutes this will eventually lead to socket exhaustion and/or hitting the limit for concurrent connections to the Event Hub.

**Comment by MichalLechowski** [comment]
> Hi @MichalLechowski. Thank you for reaching out and we regret that you're experiencing difficulties. The error message that you shared, "This operation is only allowed using a successfully authenticated context" does not come from the Event Hubs client and is not formatted as I'd expect an Event Hubs service error to be. Would you please share the full error details (type, message, reason code, inner exception) and stack trace?
> 
> There is one thing that jumps out at me from the code that was shared. In `CheckHealthAsync`, you're creating a new Event Hubs client for each call, but never closing or disposing it. Each client will create new connection which is then abandoned and will continue to exist util it hits an idle timeout (~20 minutes). During that time, it is occupying a web socket on your host and since your health probe is firing every 2 minutes this will eventually lead to socket exhaustion and/or hitting the limit for concurrent connections to the Event Hub. We would strongly recommend treating the client that you use for health probes as a singleton instance.

Yes, sorry for that mistake, of course in the prod code I use:
`await using var eventHubProducer = new EventHubProducerClient(connectionString, eventHubName);`
so there should be no need to close/dispose the client explicitily.

I added some debug logging and you are right, the error is thrown at:
`await eventHubProducer.GetEventHubPropertiesAsync(cancellationToken);`

But it's not of EventHubsException type. This is what I got catching just Exception:
```
stack at System.Net.Security.SslStream.ThrowNotAuthenticated()
at Microsoft.Azure.Amqp.Transport.TlsTransport.WriteAsync(TransportAsyncCallbackArgs args)
at Microsoft.Azure.Amqp.AsyncIO.AsyncBufferWriter.Write(TransportAsyncCallbackArgs args)
--- End of stack trace from previous location ---
at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.ConnectAsyncResult.End(IAsyncResult result)
at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, Uri connectionEndpoint, EventHubsTransportType transportType, IWebProxy proxy, Int32 sendBufferSizeBytes, Int32 receiveBufferSizeBytes, RemoteCertificateValidationCallback certificateValidationCallback, String scopeIdentifier, TimeSpan timeout)
at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenManagementLinkAsync(TimeSpan timeout, CancellationToken cancellationToken)
at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
at Azure.Messaging.EventHubs.EventHubConnection.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
at Azure.Messaging.EventHubs.Producer.EventHubProducerClient.GetEventHubPropertiesAsync(CancellationToken cancellationToken)
at KafkaToEventHubWebJob.HealthK8s.ReadinessprobeHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /src/KafkaToEventHub/HealthK8s/ReadinessprobeHealthCheck.cs:line 55
at KafkaToEventHubWebJob.HealthK8s.ReadinessprobeHealthCheck.CheckHealthAsync(HealthCheckContext context, CancellationToken cancellationToken) in /src/KafkaToEventHub/HealthK8s/ReadinessprobeHealthCheck.cs:line 55
```

And for the record line 55 is exactly GetEventHubPropertiesAsync() method call. 
Result of exception.GetType() is InvalidOperationException.

Regarding singleton, do you suggest I should create a separate service with EventHub client instance only, register it as singleton and inject it to readiness healthcheck service?

**Comment by jsquire** [comment]
@MichalLechowski:  Can you share a bit more about the host network environment?   This error appears to be coming from the transport, during the SSL handshake.    I'm not sure whether the service is rejecting the connection or it's not making it that far.   Often when we see something similar, it's because there's an intercepting proxy running in the host environment that interferes with the SSL handshake - but you're able to connect+interact with Event Hubs otherwise.

Is there any chance to pull a memory dump from the process when this error is encountered?


> Regarding singleton, do you suggest I should create a separate service with EventHub client instance only, register it as singleton and inject it to readiness healthcheck service?

I don't know enough about the application environment to offer thoughts on implementation.   The simplest approach would be to create it as `static` and let it live until the process is torn down, disposing at that point.

**Comment by jsquire** [comment]
@serkantkaraca, @xinchen10:  I'd appreciate any thoughts that you have on whether this behavior may be the result of the Event Hubs service or not.

**Comment by jsquire** [comment]
Thanks, @MichalLechowski.   I'm glad that you were able to get unblocked.   Since this is related to behavior with the host environment, there's not much to poke at here for client improvements.   I'm going to mark this as addressed and close things out.   Please feel free to unresolve if you'd like to continue the discussion.
