### ISSUE TITLE
Upgrading to Microsoft.Extension.Azure from 1.2.0 causes timeout error when using Azure Service Bus

### ISSUE THREAD

**Issue by web265p3** [Azure/azure-sdk-for-net#29415]
### Library name and version

Microsoft.Extension.Azure 1.2.0

### Describe the bug

I am using Azure Service bus with DI in my ASP.Net Core projects like this:

                services.AddAzureClients(cfg =>
                {
                    cfg.AddServiceBusClient("myConnectionString")
                });

This worked fine until I upgraded to Version 1.2.0 of Microsoft.Extension.Azure from 1.2.0.
Now I get an error message when trying to call my APIs:

info: Azure.Core[18]
      Request [5db8e5bd-b531-462e-9027-c4303dd38eec] exception System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:00:01. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.
       ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
         at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)
         at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
         at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
         at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
         at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         --- End of inner exception stack trace ---
         at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)
         at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)

After Downgrading to 1.1.1 it works again.

### Expected behavior

No Network Timeout

### Actual behavior

App needs many retries for the API endpoint to get executed

### Reproduction Steps

Install Microsoft.Extension.Azure 1.2.0 and Azure.Messaging.ServiceBus 7.8.1

Add to your service collection:

                services.AddAzureClients(cfg =>
                {
                    cfg.AddServiceBusClient("myConnectionString")
                });

Add ServiceBusClient to one of your DI services

Try to launch an API point that needs the DI service with ServiceBusClient

### Environment

Visual Studio 2022

**Comment by jsquire** [comment]
Hi @web265p3.   Thank you for reaching out and we regret that you're experiencing difficulties.  The error in that stack trace indicates an active HTTP call running through Azure Core - which is not something that the component factory that integrates with DI would initiate.   I suspect there may be something deeper going on, possibly related to the version of Azure Core that gets pulled in.

Would you be so kind as to help us understand more about the host application and scenario?   It would be helpful to know:

- What Azure packages are referenced by the project?
- Where in the application does this error surface?   A code snippet would be ideal.
- Can you share the full details of the stack trace, the included bits appear related to a log message from Core, but lack the details to understand what made the call.
- Is "myConnectionString" in the repro steps a hard-coded string in the application, or is configuration being read from somewhere?

**Comment by web265p3** [comment]
- What Azure packages are referenced by the project?

Only Microsoft.Extensions.Azure (latest version) and Azure.Messaging.ServiceBus (7.8.1, but also happens with latest version)

- Where in the application does this error surface? A code snippet would be ideal.
I dont know to be honest. It happens **before** each request, so somewhere in the request pipeline in the internals of asp.net core

- Can you share the full details of the stack trace, the included bits appear related to a log message from Core, but lack the details to understand what made the call.
The whole stack trace is already in my post above. Or where could I get more info?

- Is "myConnectionString" in the repro steps a hard-coded string in the application, or is configuration being read from somewhere?
It usually comes from the keyvault, but the error also happens if I put a raw string inside.

**Comment by jsquire** [comment]
Hi @web265p3.   I'm unable to reproduce with the available information.   I'm successfully able to inject a client using a local connection string as well as one from KeyVault.   In order to investigate, we'll need some additional information:

- Is it possible for you to package a minimal reproduction of the issue so that we can explore it locally?  _(if so, we can talk over the best approach to sharing it)_
- Which .NET runtime is the application targeting?  
- Would you please share your `.csproj` file contents?   I'd like to see the entire set of references.
- Would you please share the full initialization code in your application where you're setting up DI and other registrations?
- Can you confirm the version of the `Azure.Core.dll` that appears in your build output with the 1.2.0 and 1.1.0 configurations?  

- Since you're registering Azure clients, the log forwarder is active.  Can you please look for an entry with the `Azure.Core` source and a event id of 5?  The message will look similar to:  `Request [{0}] {1} {2}\r\n{3}client assembly: {4}`.   This will help us figure out which assembly is sending the request.   We can use the request identifier to correlate with the error log to confirm.

Picking up some previous discussion items:

> What Azure packages are referenced by the project?
>> Only Microsoft.Extensions.Azure (latest version) and Azure.Messaging.ServiceBus (7.8.1, but also happens with latest version)
 
If you're storing things in KeyVault and able to access them, a reference to the KeyVault would be required, either directly or transitively.   Neither of these packages have that.   I've asked for the full list of references which will, hopefully, shed some light.

> Where in the application does this error surface? A code snippet would be ideal.
>> I dont know to be honest. It happens before each request, so somewhere in the request pipeline in the internals of asp.net core

This is interesting.  If I understand correctly, this is occurring as part of the DI process - which would eliminate the Extensions and Service Bus as neither makes HTTP calls.  Given what we know at the moment, it would seem to indicate an issue with KeyVault unless you're making direct use of an Azure client somewhere in the `Startup` area or an action filter or similar.
