### ISSUE TITLE
[App Configuration] CreateOrUpdateTest failing in nightly runs

### ISSUE THREAD

**Issue by v-yilinhu** [Azure/azure-sdk-for-net#29459]
App Configuration nightly test runs are failing with:

> Error message
> System.ArgumentNullException : Value cannot be null. (Parameter 'location')
> 
> 
> Stack trace
>    at Azure.Core.AzureLocation..ctor(String location)
>    at Azure.Core.AzureLocation.op_Implicit(String location)
>    at Azure.ResourceManager.AppConfiguration.Tests.ConfigurationStoreCollectionTests.CreateOrUpdateTest() in /Users/runner/work/1/s/sdk/appconfiguration/Azure.ResourceManager.AppConfiguration/tests/Tests/ConfigurationStoreCollectionTests.cs:line 38
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1662597&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
This is failing due to management issues; it is being tracked elsewhere.
