### ISSUE TITLE
[BUG] QueueClient.UpdateMessage fails with NullReferenceException when message body is not supplied and using client-side encryption

### ISSUE THREAD

**Issue by edgarpalves** [Azure/azure-sdk-for-net#29934]
### Library name and version

Azure.Storage.Queues 12.11.0

### Describe the bug

QueueClient.UpdateMessage throws a NullReferenceException when the queue client has been created with client-side encryption options and when the message body is not provided in the UpdateMessage call (e.g., when updating only the visibility timeout).

This may be a serious issue for anyone moving from the old storage library to the new one due to the recently announced security issue present in the V1 client-side encryption protocol for Azure storage.

The work-around of supplying the message body every time is wasteful when the user only wants to update the visibility timeout and may be prohibitive when dealing with large messages.

### Expected behavior

Message visibility timeout to be updated, message body to not change

### Actual behavior

Message update fails altogether with NullReferenceException when the message body is not supplied

Partial stacktrace:
```
   at Azure.Storage.Queues.QueueClientSideEncryptor.<ClientSideEncryptInternal>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Queues.QueueClient.<UpdateMessageInternal>d__109.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Queues.QueueClient.UpdateMessage(String messageId, String popReceipt, String messageText, TimeSpan visibilityTimeout, CancellationToken cancellationToken)
```

### Reproduction Steps

1. create a queue client with client-side encryption options
2. enqueue a message
3. receive the message
4. update its visibility timeout only (without supplying the message body again)

Partial code:
```csharp
	var encryptionOptions = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V2_0)
	{
		KeyEncryptionKey = ...,
		KeyWrapAlgorithm = ...,
		KeyResolver = ...,
	};

	// Prepare test queue, send single message
	var queue = new QueueClient("UseDevelopmentStorage=true", "testqueue");
	queue = queue.WithClientSideEncryptionOptions(encryptionOptions);
	queue.DeleteIfExists();
	queue.Create();
	queue.SendMessage("test text");

	// Receive that message
	QueueMessage received = queue.ReceiveMessage().Value;
	string popReceipt = received.PopReceipt;

	// Update message (just visibility timeout, not message body)
	UpdateReceipt updateReceipt = queue.UpdateMessage(received.MessageId, popReceipt, visibilityTimeout: TimeSpan.FromSeconds(10)).Value;
	popReceipt = updateReceipt.PopReceipt;

	// Cleanup (not reached due to bug)
	queue.DeleteMessage(received.MessageId, popReceipt);
	queue.Delete();

```

Working LINQPad repro with code above and a wrapper for SymmetricKey for local testing: [queue_update_bug_minimal.zip](https://github.com/Azure/azure-sdk-for-net/files/9125053/queue_update_bug_minimal.zip)

### Environment

Windows 10 .NET Framework 4.
LINQPad 5

**Comment by SaurabhSharma-MSFT** [comment]
@edgarpalves I am seeing the same behavior and redirecting this to services team to investigate.  Thanks.
