### ISSUE TITLE
[BUG] SignalR ServerlessHub with Azure functions dotnet isolated does not work

### ISSUE THREAD

**Issue by bcage29** [Azure/azure-sdk-for-net#30218]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.SignalRService 1.8.0

## Issue
When initialzing the hub context in the StaticServiceHubContextStore class an 'Object reference not set to an instance of an object' is thrown becuase ServiceStoreManager is null.

(IServiceHubContextStore) StaticServiceHubContextStore.ServiceManagerStore.GetOrAddByConnectionStringKey(connectionStringSetting);

```csharp
  using Microsoft.Azure.Functions.Worker;
  using Microsoft.Extensions.Logging;
  using Microsoft.Azure.WebJobs.Extensions.SignalRService;
  using Microsoft.AspNetCore.Http;
  
  namespace Test
  {
      public class TestHub : ServerlessHub
      {
          private readonly ILogger<TestHub> _logger;
  
          public TestHub(
              ILoggerFactory loggerFactory)
          {
              _logger = loggerFactory.CreateLogger<TestHub>();
          }
  
          [Function("negotiate")]
          public async Task<SignalRConnectionInfo> Negotiate([HttpTrigger(AuthorizationLevel.Anonymous)]HttpRequest req)
          {
              return Negotiate("a@a.com");
          }
      }
  }
```

## Stack Trace
```text
[2022-07-29T19:49:54.317Z] Executed 'Functions.negotiate' (Failed, Id=312265fe-c8ab-4a11-aae7-f3db146ecb86, Duration=7897ms)
[2022-07-29T19:49:54.320Z] System.Private.CoreLib: Exception while executing function: Functions.negotiate. System.Private.CoreLib: Result: Failure
Exception: System.NullReferenceException: Object reference not set to an instance of an object.
[2022-07-29T19:49:54.322Z]    at Microsoft.Azure.WebJobs.Extensions.SignalRService.ServerlessHub`1.GetHubContext(IServiceManagerStore serviceManagerStore)
[2022-07-29T19:49:54.325Z]    at Microsoft.Azure.WebJobs.Extensions.SignalRService.ServerlessHub`1..ctor()
[2022-07-29T19:49:54.327Z]    at Test.TestHub..ctor(ITokenValidationService tokenValidationService, ITestService TestService, ILoggerFactory loggerFactory) in C:\git\bcage29\TestIso\TestHub.cs:line 17
[2022-07-29T19:49:54.331Z]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[2022-07-29T19:49:54.338Z]    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2022-07-29T19:49:54.341Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2022-07-29T19:49:54.345Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2022-07-29T19:49:54.348Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2022-07-29T19:49:54.349Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.CreateInstance(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 26
[2022-07-29T19:49:54.350Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 27
[2022-07-29T19:49:54.352Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2022-07-29T19:49:54.353Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167
Stack:    at Microsoft.Azure.WebJobs.Extensions.SignalRService.ServerlessHub`1.GetHubContext(IServiceManagerStore serviceManagerStore)
[2022-07-29T19:49:54.356Z]    at Microsoft.Azure.WebJobs.Extensions.SignalRService.ServerlessHub`1..ctor()
[2022-07-29T19:49:54.357Z]    at Test.TestHub..ctor(ITokenValidationService tokenValidationService, ITestService TestService, ILoggerFactory loggerFactory) in C:\git\bcage29\TestIso\TestHub.cs:line 17
[2022-07-29T19:49:54.358Z]    at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
[2022-07-29T19:49:54.361Z]    at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
[2022-07-29T19:49:54.363Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.ConstructorMatcher.CreateInstance(IServiceProvider provider)
[2022-07-29T19:49:54.364Z]    at Microsoft.Extensions.DependencyInjection.ActivatorUtilities.CreateInstance(IServiceProvider provider, Type instanceType, Object[] parameters)
[2022-07-29T19:49:54.365Z]    at Microsoft.Azure.Functions.Worker.DefaultFunctionActivator.CreateInstance(Type instanceType, FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionActivator.cs:line 23
[2022-07-29T19:49:54.366Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionInvoker`2.CreateInstance(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionInvoker.cs:line 26
[2022-07-29T19:49:54.371Z]    at Microsoft.Azure.Functions.Worker.Invocation.DefaultFunctionExecutor.ExecuteAsync(FunctionContext context) in D:\a\1\s\src\DotNetWorker.Core\Invocation\DefaultFunctionExecutor.cs:line 27
[2022-07-29T19:49:54.373Z]    at Microsoft.Azure.Functions.Worker.OutputBindings.OutputBindingsMiddleware.Invoke(FunctionContext context, FunctionExecutionDelegate next) in D:\a\1\s\src\DotNetWorker.Core\OutputBindings\OutputBindingsMiddleware.cs:line 13
[2022-07-29T19:49:54.376Z]    at Microsoft.Azure.Functions.Worker.GrpcWorker.InvocationRequestHandlerAsync(InvocationRequest request, IFunctionsApplication application, IInvocationFeaturesFactory invocationFeaturesFactory, ObjectSerializer serializer, IOutputBindingsInfoProvider outputBindingsInfoProvider) in D:\a\1\s\src\DotNetWorker.Grpc\GrpcWorker.cs:line 167.
```

### Expected behavior

An error is not thrown.

### Actual behavior

Before hitting the negotiate function the ServerlessHub code is executing and erroring out.

### Reproduction Steps

Create an Azure Function in C# with dotnet isolated. Add the SignalR library and inherit from the ServerlessHub class in the function class.

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22622
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  Not found

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  3.1.421 [C:\Program Files\dotnet\sdk]
  6.0.107 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.27 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info

**Comment by SaurabhSharma-MSFT** [comment]
@bcage29 We are looking into it and get back to you for any additional information.

**Comment by curt-w** [comment]
I'm being impacted by this - tough to find documentation on Azure SignalR + isolated functions... is there another approach without using the ServerlessHub?

**Comment by wojciech-torkowski** [comment]
@SaurabhSharma-MSFT do you have any updates? I'm also impacted by this.

**Comment by Y-Sindo** [comment]
Hi all, serverless hub is not supported in isolated-process model. If you want the similar coding experience in isolated-process, please use [Azure SignalR management SDK](https://github.com/Azure/azure-signalr/blob/dev/docs/management-sdk-guide.md) directly. Azure SignalR management SDK is the base of SignalR extensions and provides more functionalities than SignalR extensions. In this way, you don't need the SignalR extensions anymore. 

The related docs will be updated to clarify the issue. Sorry for the late response.

**Comment by Y-Sindo** [comment]
Now serverless hub is supported in isolated-process model. See https://github.com/aspnet/AzureSignalR-samples/tree/main/samples/DotnetIsolated-ClassBased for a sample.
