### ISSUE TITLE
[BUG] Failed to re-record BlobServiceCors test in BlobContainerTests.cs

### ISSUE THREAD

**Issue by TheOnlyWei** [Azure/azure-sdk-for-net#30324]
### Library name and version

Latest Azure.ResourceManager.Storage

### Describe the bug

Failed to re-record BlobServiceCors test in BlobContainerTests.cs:
https://github.com/Azure/azure-sdk-for-net/blob/a9eaa7b92cb78b1af565c917dd5a756f1f783a0c/sdk/storage/Azure.ResourceManager.Storage/tests/Tests/BlobContainerTests.cs#L514

Error:
```
Failed BlobServiceCors [31 s]
  Error Message:
   Azure.Core.TestFramework.TestRecordingMismatchException : The recording contains no variables.
  Stack Trace:
     at Azure.ResourceManager.Storage.BlobServicesRestOperations.SetServicePropertiesAsync(String subscriptionId, String resourceGroupName, String accountName, BlobServiceData data, CancellationToken cancellationToken) in C:\repo\azure-sdk-for-net\sdk\storage\Azure.ResourceManager.Storage\src\Generated\RestOperations\BlobServicesRestOperations.cs:line 172
   at Azure.ResourceManager.Storage.BlobServiceResource.CreateOrUpdateAsync(WaitUntil waitUntil, BlobServiceData data, CancellationToken cancellationToken) in C:\repo\azure-sdk-for-net\sdk\storage\Azure.ResourceManager.Storage\src\Generated\BlobServiceResource.cs:line 191
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in C:\repo\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 91
--- End of stack trace from previous location ---
   at Azure.Core.TestFramework.InstrumentResultInterceptor.InstrumentOperationInterceptor[T](IInvocation invocation, Func`1 innerTask) in C:\repo\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\InstrumentResultInterceptor.cs:line 105
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in C:\repo\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 91
--- End of stack trace from previous location ---
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in C:\repo\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 142
--- End of stack trace from previous location ---
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in C:\repo\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 166
   at Azure.ResourceManager.Storage.Tests.BlobContainerTests.BlobServiceCors() in C:\repo\azure-sdk-for-net\sdk\storage\Azure.ResourceManager.Storage\tests\Tests\BlobContainerTests.cs:line 549
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

The [RecordedTest] attribute attempted to re-record, but failed: 
Azure.RequestFailedException : The value for one of the XML nodes is not in the correct format.
RequestId:36c7c5e7-d01e-0068-5ab4-a74cdc000000
Time:2022-08-04T03:41:20.1021274Z
Status: 400 (Bad Request)
ErrorCode: ContainerOperationFailure

Content:
{"error":{"code":"ContainerOperationFailure","message":"The value for one of the XML nodes is not in the correct format.\nRequestId:36c7c5e7-d01e-0068-5ab4-a74cdc000000\nTime:2022-08-04T03:41:20.1021274Z"}}

Headers:
Date: Thu, 04 Aug 2022 03:41:19 GMT
Server: Microsoft-Azure-Storage-Resource-Provider/1.0,Microsoft-HTTPAPI/2.0 Microsoft-HTTPAPI/2.0
Cache-Control: no-cache
Pragma: no-cache
x-ms-client-request-id: 383957d2e37799a07854c42ba52ad75e
x-ms-request-id: 6739d080-b70d-48b3-b601-e4bc747d456f
Strict-Transport-Security: REDACTED
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
X-Content-Type-Options: REDACTED
Content-Length: 206
Content-Type: application/json
Expires: -1
```
Was advised to ask Azure SDK C# team to help in re-recording the test for Azure Stack. You need to make this change in the test file by adding the ClientTestFixture and updating the constructor (may need to wait for my PR where I updated the StorageTestBase):
```
    [ClientTestFixture(true, "2021-04-01", "2019-06-01")]
    public class BlobContainerTests : StorageTestBase
    {
        private ResourceGroupResource _resourceGroup;
        private StorageAccountResource _storageAccount;
        private BlobServiceResource _blobService;
        private BlobContainerCollection _blobContainerCollection;
        public BlobContainerTests(bool async, string apiVersion)
        : base(async, BlobContainerResource.ResourceType, apiVersion)
        {
        }
```

Then run:
cd [folder containing azure-sdk-net]\azure-sdk-for-net\sdk\storage\Azure.ResourceManager.Storage
dotnet build
dotnet test --filter "TestCategory!=Live&FullyQualifiedName~Azure.ResourceManager.Storage.Tests.BlobContainerTests" --framework net6.0

### Expected behavior

Should record updated test successfully.

### Actual behavior

Failed to record updated test.

### Reproduction Steps

Make changes to the test and re-record the test:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.ResourceManager.Storage/tests/Tests/BlobContainerTests.cs

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.302
 Commit:    c857713418

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.17763
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.302\

global.json file:
  C:\repo\azure-sdk-for-net\global.json

Host:
  Version:      6.0.7
  Architecture: x64
  Commit:       0ec02c8c96

.NET SDKs installed:
  6.0.302 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

IDE:
Visual Studio Code

Console:
PowerShell Core 7.2.5

**Comment by HarveyLink** [comment]
Hi, @TheOnlyWei ,
Do you have a PR working on this issue? We could take a look and try to fix it on top of that.

**Comment by HarveyLink** [comment]
Close this as not active. Feel free to reopen it if you meet same error again.
