### ISSUE TITLE
[Question] Randomly get "No such host is known"

### ISSUE THREAD

**Issue by anmeng10101** [Azure/azure-sdk-for-net#30555]
### Library name and version

Azure.Search.Documents 11.4.0-beta.2

### Background information:

- SocketException "No such host is known" randomly received while using invoke Azure Search Service via different versions of Azure.Search.Documents.

- The duration of the failed calls are always 3.5 seconds.

- We have multiple services using SDK ran into same failure sometime.  

### Questions:

- Not sure if any other users reported similar issue please?
- How would SDK handle the case like unexpected DNS change please?

### Environment

Hosting platform: Azure AppService

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ShivangiReja** [comment]
@anmeng10101 Could you please attach Exception Log or Stack Trace?

Also, please refer https://docs.microsoft.com/en-us/azure/search/search-limits-quotas-capacity in case you're exceeding any limits.

**Comment by anmeng10101** [comment]
Thanks @ShivangiReja 

Trace:

Azure.RequestFailedException: No such host is known.
 ---> System.Net.Http.HttpRequestException: No such host is known.
 ---> System.Net.Sockets.SocketException (11001): No such host is known.
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Search.Documents.SearchClient.SearchInternal[T](SearchOptions options, String operationName, Boolean async, CancellationToken cancellationToken)

**Comment by ShivangiReja** [comment]
Looking at  https://github.com/dotnet/runtime/issues/31247, seems like this is not specific to the Search client, but an issue in .NET. Could you please check out https://github.com/dotnet/runtime/issues/31247 and see in which version of .NET it's fixed, or what else they have to say about it.
