### ISSUE TITLE
[BUG] Problem with Timestamp

### ISSUE THREAD

**Issue by davidbabayan** [Azure/azure-sdk-for-net#30644]
### Library name and version

Azure.Data.Tables 12.6.1

### Describe the bug

I am trying to add new entity to the table. Here is my code:

```
var table = tableServiceClient.GetTableClient(tableName);
Response response = table.AddEntity(entity);
```

### Expected behavior

It should add entity to the table.

### Actual behavior

```
Unhandled exception. System.NotSupportedException: DateTime 3/1/2013 12:00:00 AM has a Kind of Unspecified. Azure SDK requires it to be UTC. You can call DateTime.SpecifyKind to change Kind property value to DateTimeKind.Utc.
   at Azure.Core.TypeFormatters.ToString(DateTime value, String format)
   at Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, Object value)
   at Azure.Data.Tables.TableRestClient.CreateInsertEntityRequest(String table, Nullable`1 timeout, Nullable`1 responsePreference, IDictionary`2 tableEntityProperties, QueryOptions queryOptions)
   at Azure.Data.Tables.TableRestClient.InsertEntity(String table, Nullable`1 timeout, Nullable`1 responsePreference, IDictionary`2 tableEntityProperties, QueryOptions queryOptions, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.AddEntity[T](T entity, CancellationToken cancellationToken)
   at Models.StorageContext.AddEntity[T](String tableName, T entity) in C:\Users\David Babayan\Source\repos\SqlToStorageTable\Models\StorageContext.cs:line 29
   at Program.<Main>$(String[] args) in C:\Users\David Babayan\Source\repos\SqlToStorageTable\Program.cs:line 35
```

### Reproduction Steps

```
TableServiceClient tableServiceClient = new TableServiceClient(
  new Uri("tableUrl"),
  new TableSharedKeyCredential( "accountName", "accountKey")
);
TableEntity entity = new("partitionValue", "rowKey")
{
  {"Column1", "Value1"},
  {"Column2", "Value2"}
};
string tableName = "TableName";
var table = tableServiceClient.GetTableClient(tableName);
Response response = table.AddEntity(entity);
```

### Environment

dotnet --info results:
Version:   6.0.400
Commit:    7771abd614
OS Name:     Windows
OS Version:  10.0.22000
OS Platform: Windows
RID:         win10-x64

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @davidbabayan  - I'm not able to reproduce this issue with the code snippet you provided. Are you sure your code isn't adding a DateTime value elsewhere?

**Comment by davidbabayan** [comment]
I wrote a console application which takes data from a database and tries to write it to the table. My code is one page I am sure it does not write anywhere.

**Comment by christothes** [comment]
> I wrote a console application which takes data from a database and tries to write it to the table. My code is one page I am sure it does not write anywhere.

It must be writing a datetime value to the entity somewhere. The repro steps, as written above, work as expected.

**Comment by davidbabayan** [comment]
As I learned the problem was not with timestamp property but with another property which was holding date. The documentation does not mention that any property containing date or time should have Utc kind. Maybe it is good idea to mention it there.
