### ISSUE TITLE
[FormRecognizer] ManageCustomModelsAsync failing in nightly runs

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-sdk-for-net#30735]
FormRecognizer nightly test runs are failing with:

> Error message:
>Azure.RequestFailedException : Invalid model created with ID 3b656cfd-43f2-4147-8603-02573ded009d
Status: 200 (OK)
ErrorCode: 3013
Additional Information:
error-0: 3013: Operation exceeded maximum processing time.
Content:
Headers:
ms-azure-ai-errorcode: REDACTED
x-envoy-upstream-service-time: 29
apim-request-id: f14eda15-6569-413a-9d60-4824a50442f3
Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Date: Thu, 25 Aug 2022 05:12:03 GMT
Content-Length: 295
Content-Type: application/json; charset=utf-8
Data:
error-0: 3013: Operation exceeded maximum processing time.
> Stack trace:
> at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 290
   at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 273
   at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 87
   at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 79
   at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 202
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 242
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 177
   at Azure.AI.FormRecognizer.Training.CreateCustomFormModelOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/FormTrainingClient/CreateCustomFormModelOperation.cs:line 73
   at Azure.AI.FormRecognizer.Samples.FormRecognizerSamples.ManageCustomModelsAsync() in /Users/runner/work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/samples/V3.1/Sample7_ManageCustomModelsAsync.cs:line 50
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.<>c__DisplayClass4_0.<PerformWork>b__0()
   at NUnit.Framework.Internal.ContextUtils.<>c__DisplayClass1_0`1.<DoIsolated>b__0(Object _)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at NUnit.Framework.Internal.ContextUtils.DoIsolated(ContextCallback callback, Object state)
   at NUnit.Framework.Internal.ContextUtils.DoIsolated[T](Func`1 func)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1805487&view=results

@jsquire for notification.

**Comment by kinelski** [comment]
Now we only see this error as part of https://github.com/Azure/azure-sdk-for-net/issues/31914, so I believe the occurrence described here was a transient failure. Closing this.
