### ISSUE TITLE
[Synapse] CanCheckPrincipalAccessViaGrowUpHelper failing in nightly runs

### ISSUE THREAD

**Issue by v-jiaodi** [Azure/azure-sdk-for-net#30737]
Synapse nightly test runs are failing with:

> Error message:
>Expected string length 7 but was 10. Strings differ at index 0.
Expected: "Allowed"
But was:  "NotAllowed"
-----------^
> Stack trace:
> at Azure.Analytics.Synapse.AccessControl.Tests.AccessControlClientLiveTests.CanCheckPrincipalAccessViaGrowUpHelper() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.AccessControl\tests\AccessControlClientLiveTests.cs:line 295
   at Azure.Analytics.Synapse.AccessControl.Tests.AccessControlClientLiveTests.CanCheckPrincipalAccessViaGrowUpHelper() in D:\a\_work\1\s\sdk\synapse\Azure.Analytics.Synapse.AccessControl\tests\AccessControlClientLiveTests.cs:line 300
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1807437&view=results

@jsquire for notification.

**Comment by yanjungao718** [comment]
This is not reproduced and all tests passed when investigating, it is likely to be an unstable problem, so now close it and please feel free to open a new one if repro again.
