### ISSUE TITLE
[FormRecognizer] CopyModelTo(False) failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#30905]
FormRecognizer nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : An unexpected error occurred.
> Status: 200 (OK)
> ErrorCode: InternalServerError
> 
> Additional Information:
> AdditionInformation: InternalServerError: An unexpected error occurred.
> 
> Details:
> InternalServerError: An unexpected error occurred.
> 
> Raw:
> {
> "code": "InternalServerError",
> "message": "An unexpected error occurred.",
> "details": [
> {
> "code": "InternalServerError",
> "message": "An unexpected error occurred."
> }
> ]
> }
> 
> Content:
> 
> Headers:
> Transfer-Encoding: chunked
> x-envoy-upstream-service-time: 28
> apim-request-id: e3b22cc2-1fe8-4b9f-a2fd-4e298eefe9fa
> Strict-Transport-Security: max-age=31536000; includeSubDomains; preload
> X-Content-Type-Options: nosniff
> Date: Fri, 02 Sep 2022 04:03:25 GMT
> Content-Type: application/json; charset=utf-8
> 
> Data:
> AdditionInformation: InternalServerError: An unexpected error occurred.
> 
> Details:
> InternalServerError: An unexpected error occurred.
> 
> Raw:
> {
> "code": "InternalServerError",
> "message": "An unexpected error occurred.",
> "details": [
> {
> "code": "InternalServerError",
> "message": "An unexpected error occurred."
> }
> ]
> }
> 
> 
> Stack trace
>    at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 290
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 273
>    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
>    at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 105
>    at Azure.AI.FormRecognizer.DocumentAnalysis.CopyModelToOperation.UpdateStatus(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/CopyModelToOperation.cs:line 160
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, Operation operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken)
>    at Azure.Core.OperationPoller.WaitForCompletion[T](Operation`1 operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken)
>    at Azure.Operation`1.WaitForCompletion(CancellationToken cancellationToken)
>    at Azure.AI.FormRecognizer.DocumentAnalysis.DocumentModelAdministrationClient.CopyModelTo(WaitUntil waitUntil, String modelId, CopyAuthorization target, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/src/DocumentModelAdministrationClient.cs:line 703
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.InstrumentResultInterceptor.InstrumentOperationInterceptor[T](IInvocation invocation, Func`1 innerTask) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/InstrumentResultInterceptor.cs:line 105
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 91
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 142
> --- End of stack trace from previous location where exception was thrown ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 166
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentModelAdministrationClientLiveTests.CopyModelTo(Boolean useTokenCredential) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/DocumentModelAdministrationClient/DocumentModelAdministrationClientLiveTests.cs:line 322
>    at Azure.AI.FormRecognizer.DocumentAnalysis.Tests.DocumentModelAdministrationClientLiveTests.CopyModelTo(Boolean useTokenCredential) in /mnt/vss/_work/1/s/sdk/formrecognizer/Azure.AI.FormRecognizer/tests/DocumentModelAdministrationClient/DocumentModelAdministrationClientLiveTests.cs:line 337
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1826217&view=results

@jsquire for notification.

**Comment by MelMac-Sage** [comment]
Did this get any update? I am getting the same intermittently - on the same documents that worked a couple of minutes previously. Doesnt matter if I try either AnalyzeDocumentAsync with a stream OR AnalyzeDocumentFromUriAsync with file URI ???

**Comment by kinelski** [comment]
> Did this get any update? I am getting the same intermittently - on the same documents that worked a couple of minutes previously. Doesnt matter if I try either AnalyzeDocumentAsync with a stream OR AnalyzeDocumentFromUriAsync with file URI ???

We're not seeing this error in our test pipeline anymore. If you still see it, could you share the error message you're getting? It includes an `apim-request-id` header that can be useful for debugging it on the service side.

**Comment by kinelski** [comment]
@MelMac-Sage Closing this since we're not seeing this failure in our tests anymore, but feel free to open a new issue if you're still having trouble with it.
