### ISSUE TITLE
[BUG] Unable to invoke ContainerServiceManagedClusterCollection.CreateOrUpdate due to API Version Mismatch

### ISSUE THREAD

**Issue by brutusbuckeye** [Azure/azure-sdk-for-net#31121]
### Library name and version

Azure.ResourceManager.ContainerService 1.0.0-beta.2

### Describe the bug

I am unable to create or update AKS clusters using the CreateOrUpdate method on instances of the ContainerServiceManagedClusterCollection. Behind the scenes the operation succeeds and the ARM request is sent to Azure but the API call throws an exception due to an issue with supported API versions on the locations resource type.

### Expected behavior

CreateOrUpdate[Async] call succeeds with no exception thrown.

### Actual behavior

CreateOrUpdate[Async] call throws the following exception when attempting to invoke the CreateOrUpdate[Async] method. Note that the AKS cluster behind the scenes appears to successfully receive the ARM request to update the cluster, but somewhere in the method call chain an exception is hit and causes the overall method to throw
```
Error invoking operation: Exception has been thrown by the target of an invocation.System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
---> Azure.RequestFailedException: The resource type 'locations/operations' could not be found in the namespace 'Microsoft.ContainerService' for api version '2022-04-01'. The supported api-versions are '2016-03-30,2017-08-31'.
Status: 404 (Not Found)
ErrorCode: InvalidResourceType
Content:\r\n{\"error\":{\"code\":\"InvalidResourceType\",\"message\":\"The resource type 'locations/operations' could not be found in the namespace 'Microsoft.ContainerService' for api version '2022-04-01'. The supported api-versions are '2016-03-30,2017-08-31'.\"}}
Headers:\r\nCache-Control: no-cache\r\nPragma: no-cache\r\nx-ms-failure-cause: REDACTED\r\nx-ms-request-id: 969e2b33-559c-4902-ab87-9c8cfa396d58\r\nx-ms-correlation-request-id: REDACTED\r\nx-ms-routing-request-id: REDACTED\r\nStrict-Transport-Security: REDACTED\r\nX-Content-Type-Options: REDACTED\r\nDate: Mon, 12 Sep 2022 17:55:33 GMT\r\nContent-Type: application/json; charset=utf-8\r\nExpires: -1\r\nContent-Length: 244
   at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state)
   at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Core.OperationPoller.WaitForCompletionResponse(OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken)
   at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken)
   at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Core.OperationInternal`1.WaitForCompletion(CancellationToken cancellationToken)
   at Azure.ResourceManager.ContainerService.ContainerServiceArmOperation`1.WaitForCompletion(CancellationToken cancellationToken)
   at Azure.ResourceManager.ContainerService.ContainerServiceManagedClusterCollection.CreateOrUpdate(WaitUntil waitUntil, String resourceName, ContainerServiceManagedClusterData data, CancellationToken cancellationToken)
```

### Reproduction Steps

The following code snippet reproduces the error. In the example I am not modifying any aspects of the AKS cluster for simplicity. But the error is also present if I actually modify properties underneath `.Data` as well.
```
var client = new ArmClient(___my_credentials___, ___my_sub_id___);
SubscriptionResource subscription = GetDefaultSubscription();
ResourceGroupResource resourceGroup = subscription.GetResourceGroup(___my_resource_group_name___);

var collection = resourceGroup.GetContainerServiceManagedClusters();
foreach(var cluster in collection) {
    // This is a no-op as we aren't changing anything but its enough to trigger
    // the exception:
    //    Azure.RequestFailedException: The resource type 'locations/operations' could not be found in the namespace 'Microsoft.ContainerService' 
    //    for api version '2022-04-01'. The supported api-versions are '2016-03-30,2017-08-31'.\r\nStatus: 404 (Not Found)
    collection.CreateOrUpdate(WaitUntil.Completed, cluster.Data.Name, cluster.Data);
}
```

Note the mistmatch between the supported API versions on the `managedClusters` and `locations` resource type:
```
> ((Get-AzResourceProvider -Location eastus -ProviderNamespace ` Microsoft.ContainerService).ResourceTypes | Where-Object ResourceTypeName -eq ` managedClusters).ApiVersions
2022-08-02-preview
2022-08-01
2022-07-02-preview
2022-07-01
2022-06-02-preview
2022-06-01
2022-05-02-preview
2022-04-02-preview
2022-04-01
2022-03-02-preview
2022-03-01
2022-02-02-preview
2022-02-01
2022-01-02-preview
2022-01-01
2021-11-01-preview
2021-10-01
2021-09-01
2021-08-01
2021-07-01
2021-05-01
2021-03-01
2021-02-01
2020-12-01
2020-11-01
2020-09-01
2020-07-01
2020-06-01
2020-04-01
2020-03-01
2020-02-01
2020-01-01
2019-11-01
2019-10-01
2019-08-01
2019-06-01
2019-04-01
2019-02-01
2018-08-01-preview
2018-03-31
2017-08-31
```

```
> ((Get-AzResourceProvider -Location eastus -ProviderNamespace ` Microsoft.ContainerService).ResourceTypes | Where-Object ResourceTypeName -eq ` locations).ApiVersions
2017-08-31
2017-01-31
2016-09-30
2016-03-30
2015-11-01-preview
```

### Environment

`dotnet --info` returns the following:
```
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c
```

I am using Azure.ResourceManager.ContainerService v1.0.0-beta.2

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
We've fixed the issue in the stable version. Please try with `Azure.ResourceManager.ContainerService 1.1.0`.
