### ISSUE TITLE
[BUG] Unable to get reference to AKS cluster that is using Managed Identity

### ISSUE THREAD

**Issue by brutusbuckeye** [Azure/azure-sdk-for-net#31233]
### Library name and version

Azure.ResourceManager.ContainerService 1.0.0-beta.2

### Describe the bug

I am unable to get a reference to an AKS cluster that is using Managed Identity (https://learn.microsoft.com/en-us/azure/aks/use-managed-identity). When the ContainerServiceManagedClusterResource attempts to instantiate an object using the JSON data that is returned from the Microsoft.ContainerService managedClusters API an exception is thrown.

### Expected behavior

Able to reference an AKS cluster that is configured to use managed identify with no errors or excpetions.

### Actual behavior

When the library attempts to create an object to type ContainerServiceManagedClusterResource for a corresponding AKS cluster that is using managed service identity an exception is thrown:

```
System.FormatException
  HResult=0x80131537
  Message=One of the identified items was in an invalid format.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.JsonElement.GetGuid()
   at Azure.ResourceManager.ContainerService.Models.ManagedClusterServicePrincipalProfile.DeserializeManagedClusterServicePrincipalProfile(JsonElement element) in C:\xxxxxxxxxxx\sdk\containerservice\Azure.ResourceManager.ContainerService\src\Generated\Models\ManagedClusterServicePrincipalProfile.Serialization.cs:line 37
   at Azure.ResourceManager.ContainerService.ContainerServiceManagedClusterData.DeserializeContainerServiceManagedClusterData(JsonElement element) in C:\xxxxxxxxxxx\sdk\containerservice\Azure.ResourceManager.ContainerService\src\Generated\Models\ContainerServiceManagedClusterData.Serialization.cs:line 434
   at Azure.ResourceManager.ContainerService.Models.ManagedClusterListResult.DeserializeManagedClusterListResult(JsonElement element) in C:\xxxxxxxxxxx\sdk\containerservice\Azure.ResourceManager.ContainerService\src\Generated\Models\ManagedClusterListResult.Serialization.cs:line 33
   at Azure.ResourceManager.ContainerService.ManagedClustersRestOperations.ListByResourceGroup(String subscriptionId, String resourceGroupName, CancellationToken cancellationToken) in C:\xxxxxxxxxxx\sdk\containerservice\Azure.ResourceManager.ContainerService\src\Generated\RestOperations\ManagedClustersRestOperations.cs:line 253
   at Azure.ResourceManager.ContainerService.ContainerServiceManagedClusterCollection.<>c__DisplayClass10_0.<GetAll>g__FirstPageFunc|0(Nullable`1 pageSizeHint) in C:\xxxxxxxxxxx\sdk\containerservice\Azure.ResourceManager.ContainerService\src\Generated\ContainerServiceManagedClusterCollection.cs:line 238
   at Azure.Core.PageableHelpers.<>c__DisplayClass5_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint) in C:\xxxxxxxxxxxxx\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20220905.1\content\Generator.Shared\PageableHelpers.cs:line 45
   at Azure.Core.PageableHelpers.FuncPageable`1.<AsPages>d__4.MoveNext() in C:\Users\xxxxxxxxxxxxx\.nuget\packages\microsoft.azure.autorest.csharp\3.0.0-beta.20220905.1\content\Generator.Shared\PageableHelpers.cs:line 220
   at Azure.Pageable`1.<GetEnumerator>d__8.MoveNext()
   at Program.<Main>$(String[] args) in c:\xxxxxxxxxxxxxxxxxxxxxx\Program.cs:line 19

  This exception was originally thrown at this call stack:
    [External Code]
    Azure.ResourceManager.ContainerService.Models.ManagedClusterServicePrincipalProfile.DeserializeManagedClusterServicePrincipalProfile(System.Text.Json.JsonElement) in ManagedClusterServicePrincipalProfile.Serialization.cs
    Azure.ResourceManager.ContainerService.ContainerServiceManagedClusterData.DeserializeContainerServiceManagedClusterData(System.Text.Json.JsonElement) in ContainerServiceManagedClusterData.Serialization.cs
    Azure.ResourceManager.ContainerService.Models.ManagedClusterListResult.DeserializeManagedClusterListResult(System.Text.Json.JsonElement) in ManagedClusterListResult.Serialization.cs
    Azure.ResourceManager.ContainerService.ManagedClustersRestOperations.ListByResourceGroup(string, string, System.Threading.CancellationToken) in ManagedClustersRestOperations.cs
    Azure.ResourceManager.ContainerService.ContainerServiceManagedClusterCollection.GetAll.__FirstPageFunc|0(int?) in ContainerServiceManagedClusterCollection.cs
    Azure.Core.PageableHelpers.CreateEnumerable.AnonymousMethod__0(string, int?) in PageableHelpers.cs
    Azure.Core.PageableHelpers.FuncPageable<T>.AsPages(string, int?) in PageableHelpers.cs
    [External Code]
    Program.<Main>$(string[]) in Program.cs
```

The problematic function appears to be [ManagedClusterServicePrincipalProfile.Serialization.cs:29](https://github.com/Azure/azure-sdk-for-net/blob/826006ef4eeadf776563573ca8115dd7f3c81734/sdk/containerservice/Azure.ResourceManager.ContainerService/src/Generated/Models/ManagedClusterServicePrincipalProfile.Serialization.cs#L29) as the value of `clientId` is `msi` which is not a valid GUID as the code expects

### Reproduction Steps

Create a cluster with managed identity enabled:
```
az group create --name myResourceGroup --location eastus
az aks create -g myResourceGroup -n myClusterWithMSI --enable-managed-identity
```

Then run the following code snippet to access the cluster using the azure sdk for dot net:
```
ArmClient client = new ArmClient(new DefaultAzureCredential());
SubscriptionResource subscription = client.GetSubscriptionResource(SubscriptionResource.CreateResourceIdentifier("----- subscription id -----"));
ResourceGroupResource resourceGroup = subscription.GetResourceGroup("myResourceGroup");

// getting a reference to a cluster with MSI triggers an exception
ContainerServiceManagedClusterResource cluster = resourceGroup.GetContainerServiceManagedCluster("myClusterWithMSI");
```

### Environment

dotnet --info returns the following:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.401
 Commit:    0906eae6f8

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.401\

global.json file:
  Not found

Host:
  Version:      6.0.9
  Architecture: x64
  Commit:       163a63591c
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by brutusbuckeye** [comment]
This PR may have fixed the issue: https://github.com/Azure/azure-sdk-for-net/pull/30671, but I have not verified.

**Comment by ArcturusZhang** [comment]
Hi @brutusbuckeye sorry for the inconvenience but did you try if the new version could solve your issue?
