### ISSUE TITLE
InvalidCastException when instrumenting Operation<AsyncPageable<BinaryData>>

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#31325]
I'm getting an exception from an automatically (or even manually) instrumented `Operation<AsyncPageable<BinaryData>>` when running synchronously:

```C#
Operation<AsyncPageable<BinaryData>> updateSourcesOperation = await Client.UpdateSourcesAsync(WaitUntil.Completed, testProjectName, updateSourcesRequestContent);
```

The exception:

```text
    System.InvalidOperationException : Expected scope QuestionAnsweringAuthoringClient.UpdateSources to be marked as failed but it succeeded
Exception: System.InvalidCastException: Unable to cast object of type 'System.Threading.Tasks.Task`1[Azure.Operation`1[Azure.Pageable`1[System.BinaryData]]]' to type 'System.Threading.Tasks.Task`1[Azure.Operation`1[Azure.AsyncPageable`1[System.BinaryData]]]'.
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in C:\src\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 0
--- End of stack trace from previous location ---
   at Azure.Core.TestFramework.InstrumentResultInterceptor.InstrumentOperationInterceptor[T](IInvocation invocation, Func`1 innerTask) in C:\src\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\InstrumentResultInterceptor.cs:line 105
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in C:\src\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 91
--- End of stack trace from previous location ---
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in C:\src\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 142
--- End of stack trace from previous location ---
   at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in C:\src\azure-sdk-for-net\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 166

  Stack Trace: 
DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) line 207
QuestionAnsweringAuthoringClientLiveTests.DeployProject() line 80
...
```

The key issue here is the second line:
```text
Exception: System.InvalidCastException: Unable to cast object of type 'System.Threading.Tasks.Task`1[Azure.Operation`1[Azure.Pageable`1[System.BinaryData]]]' to type 'System.Threading.Tasks.Task`1[Azure.Operation`1[Azure.AsyncPageable`1[System.BinaryData]]]'.
```

Perhaps this is a corner case in the fix that resolved #26334?

**Comment by pallavit** [comment]
@heaths could you share the repro steps please.

**Comment by heaths** [comment]
The stack trace had the information Josh needed when he asked me to open this, specifically:

> Unable to cast object of type 'System.Threading.Tasks.Task`1[Azure.Operation`1[Azure.Pageable`1[System.BinaryData]]]' to type 'System.Threading.Tasks.Task`1[Azure.Operation`1[Azure.AsyncPageable`1[System.BinaryData]]]'

The problem is that the interceptor wasn't handling operations of pageables correctly.
