### ISSUE TITLE
How to construct a client secret credential without providing a client secret

### ISSUE THREAD

**Issue by calebkiage** [Azure/azure-sdk-for-net#31499]
### Library name and version

Azure.Identity 1.7.0

### Query/Question

We are working on a CLI tool that has a login command in which the user provides a client id and a client secret to fetch the token and we enable token caching. Other commands need an access token that is stored in the cache. Can we instantiate a `ClientSecretCredential` class without providing the client secret and get a token from the store after the first log in that fetches the access token?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @calebkiage 
I believe you'd want the [SharedTokenCacheCredential](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/src/Credentials/SharedTokenCacheCredential.cs) for this kind of scenario. You may also want to take a look at these samples for token cache persistence https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md#persisting-user-authentication-data

**Comment by calebkiage** [comment]
Hey @christothes, thanks for suggesting the use of the shared token cache. I believe it might be the way to go save for a problem resolving a token from the cache. My scenario is when there's a token in the cache that has both the access token and the refresh token expired. Since the retrieved token will be invalid, I prompt the user to log in again. When the user logs in, they are given a new token that is stored in the cache. In this scenario of multiple matching tokens, the shared token credential fails with a message:

```
[Error] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.10 Microsoft Windows 10.0.22621 [10-27 16:59:04.60 - fc73b842-086f-4087-9923-7cce66b123f6] Multiple access tokens found for matching authority, client_id, user and scopes.
[Error] Azure-Identity: False MSAL 4.39.0.0 MSAL.NetCore .NET 6.0.10 Microsoft Windows 10.0.22621 [10-27 16:59:04.64 - fc73b842-086f-4087-9923-7cce66b123f6] Exception type: Microsoft.Identity.Client.MsalClientException
, ErrorCode: multiple_matching_tokens_detected

   at Microsoft.Identity.Client.TokenCache.GetSingleResult(AuthenticationRequestParameters requestParams, IReadOnlyList`1 filteredItems)
   at Microsoft.Identity.Client.TokenCache.Microsoft.Identity.Client.ITokenCacheInternal.FindAccessTokenAsync(AuthenticationRequestParameters requestParams)
   at Microsoft.Identity.Client.Cache.CacheSessionManager.FindAccessTokenAsync()
   at Microsoft.Identity.Client.Internal.Requests.Silent.CacheSilentStrategy.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.Silent.SilentRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
[Informational] Azure-Identity: SharedTokenCacheCredential.GetToken was unable to retrieve an access token. Scopes: [  ] ParentRequestId: common Exception: Azure.Identity.AuthenticationFailedException (0x80131500): SharedTokenCacheCredential authentication failed: The cache contains multiple tokens satisfying the requirements. Try to clear token cache.
 ---> Microsoft.Identity.Client.MsalClientException (0x80131500): The cache contains multiple tokens satisfying the requirements. Try to clear token cache.
```

Azure identity doesn't offer an API to clear the cache based on the response to issue #31499

**Comment by calebkiage** [comment]
It doesn't look like the `SharedTokenCredential` has access to tokens stored in the `IConfidentialClientApplication.AppTokenCache` :-(

**Comment by christothes** [comment]
The other route you could go is to use `InteractiveBrowserCredential` and persist the `AuthenciationRecord` for subsequent auth attempts. See the following sample for details:
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/identity/Azure.Identity/samples/ClientSideUserAuthentication.md#persisting-user-authentication-data

**Comment by calebkiage** [comment]
@christothes, we already have InteractiveBrowserCredential working. We need a client secret credential to cater for unattended scenarios on the CLI.

**Comment by christothes** [comment]
In order to cache the credentials across runs of the CLI, you'll need to cache an `AuthenticationRecord`. Only the interactive credentials (`UserNamePassword`, `InteractiveBrowserCredential`, and `DeviceCodeCredential` support returning this.

In your scenario, if the user has the ClientId and ClientSecret, why not use the EnvironmentCredential instead?

**Comment by calebkiage** [comment]
@christothes, the client certificate credential and client secret credential classes support token caching as well according to the docs. I've confirmed this is true with the client certificate. Is it that the shared token credential can't access the cache?
The environment credential support is planned as well. So, are we saying the client secret credential won't support our use case for the moment?

**Comment by christothes** [comment]
Although they support caching, they cannot be constructed without first providing credentials. The interactive credential types mentioned above do not require this. But if the user has access to a client secret, any of the mentioned credentials can be used, but this defeats the purpose of the caching. Most CLIs that cache credentials begin the workflow with an interactive credential prompt, which is then cached for future invocations.
