### ISSUE TITLE
[BUG] CertificateClient.ImportCertificateAsync returning : Only .pfx and .pem files are supported.

### ISSUE THREAD

**Issue by filmar25** [Azure/azure-sdk-for-net#31509]
### Library name and version

Azure.KeyVault.Certificates v4.4.0

### Describe the bug

Hi,

I have pass many hours now to make it working, but I am not able to do it.

There is my code :

```
                var pfx = certificate.Export(X509ContentType.Pkcs12, pwd);

                var importCertificateOptions = new ImportCertificateOptions(name, pfx)
                {
                    Password = pwd,
                    Policy = new CertificatePolicy()
                    {
                        ContentType = CertificateContentType.Pkcs12,
                        Exportable = true
                    },
                    Enabled = true
                };

                await certificateClient.ImportCertificateAsync(importCertificateOptions);
```

Here "certificate" is a X509Certificate2 containing private and public key received from LetsEncrypt.

I made a test to be sure that the PFX is really good. I save the bytes on disk in a file name Test.Pfx and I can import this pfx via the Azure Portal. So the PFX generated by the Export is good.

I don't understand the StackTrace of the error. Why X509Certificate2FromFileProvider, I am using a bytes array :

   at Azure.Identity.X509Certificate2FromFileProvider.GetCertificateAsync(Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.<CreateClientAsync>d__16.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Identity.MsalClientBase`1.<GetClientAsync>d__20.MoveNext()
   at Azure.Identity.MsalConfidentialClient.<AcquireTokenForClientCoreAsync>d__18.MoveNext()
   at Azure.Identity.MsalConfidentialClient.<AcquireTokenForClientAsync>d__17.MoveNext()
   at Azure.Identity.ClientCertificateCredential.<GetTokenAsync>d__25.MoveNext()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.ClientCertificateCredential.<GetTokenAsync>d__25.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueFromCredentialAsync>d__9.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__6.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__6.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<AuthenticateAndAuthorizeRequestAsync>d__12.MoveNext()
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.<AuthorizeRequestOnChallengeAsyncInternal>d__10.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
   at Azure.Core.Pipeline.RedirectPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__11.MoveNext()
   at Azure.Core.Pipeline.HttpPipeline.<SendRequestAsync>d__18.MoveNext()
   at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__29.MoveNext()
   at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__19`2.MoveNext()
   at Azure.Security.KeyVault.Certificates.CertificateClient.<ImportCertificateAsync>d__35.MoveNext()
   
   Also, the Application Identity that I am using has all permissions on Secrets and Certificates.

### Expected behavior

I was suppose to follow the documentation and import a PFX to Azure KeyVault Certificates

### Actual behavior

Using the SDK, I got error : Only .pfx and .pem files are supported.

### Reproduction Steps

Create a X509Certificate2 containing private key and try to use ClientCertificate.ImportCertificateAsync to import it to Azure KeyVault Certificates

### Environment

ASP.NET Core .NET 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by heaths** [comment]
The stack trace shows a failure to authenticate using a client credential, which your code sample does not show. How did you construct your `certificateClient`? The call to import the certificate isn't even getting through because of the authentication error.

/cc @schaabs

**Comment by filmar25** [comment]
Thank you @jsquire and @heaths for your answer !

Thank you @heaths to get me orientated !

You are right, it was my TokenCredential that was wrong. I use ClientCertificateCredential instead of ClientSecretCredential.

Thank you very much !!!
