### ISSUE TITLE
[BUG] JSON deserialization error when creating a new `AppCertificate`

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-sdk-for-net#31701]
### Library name and version

Azure.ResourceManager.AppService 1.0.0

### Describe the bug

AppCertificate fails with a JSON deserialization error when creating a new AppCertificate, Azure Portal shows that the certificate was created successfully and Azure Resource Manager API also returns success, but the SDK internal deserialization fails.

### Expected behavior

We expect the certificate to be created successfully and the information we have created to be returned.

### Actual behavior

JSON deserialization error. The resource creation itself succeeds.

### Stacktrace

```
System.ArgumentException: Value cannot be an empty string. (Parameter 'resourceId')
   at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppService.AppCertificateData.DeserializeAppCertificateData(JsonElement element)
   at Azure.ResourceManager.AppService.CertificatesRestOperations.CreateOrUpdateAsync(String subscriptionId, String resourceGroupName, String name, AppCertificateData data, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppService.AppCertificateCollection.CreateOrUpdateAsync(WaitUntil waitUntil, String name, AppCertificateData data, CancellationToken cancellationToken)
```

### Repro code

```csharp
using System.Security.Cryptography.X509Certificates;

using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.AppService;
using Azure.ResourceManager.Resources;

var armClient = new ArmClient(new AzureCliCredential());

var subscription = await armClient.GetDefaultSubscriptionAsync();

ResourceGroupResource resourceGroup = await subscription.GetResourceGroupAsync("rg-cert-test");

WebSiteResource webSite = await resourceGroup.GetWebSiteAsync("app-cert-test-01");

var certificates = resourceGroup.GetAppCertificates();

var certificate = new X509Certificate2(File.ReadAllBytes(@"cert-test.pfx"), (string?)null, X509KeyStorageFlags.Exportable);

var pfx = certificate.Export(X509ContentType.Pfx, "P@ssw0rd");

// throw exception
var result = await certificates.CreateOrUpdateAsync(Azure.WaitUntil.Completed, "cert-test-01", new AppCertificateData(webSite.Data.Location)
{
    Password = "P@ssw0rd",
    PfxBlob = pfx,
    ServerFarmId = webSite.Data.AppServicePlanId
});

Console.WriteLine(result.Value.Id);
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by xboxeer** [comment]
@shibayan  can you debug mode of SDK and share us the raw JSON responses when you are calling createorupdate method? It appears the resourceId is missing in the returned json.
You can enable debug mode by set up the option parameters when you are construct ArmClient
```csharp
options.Diagnostics.IsLoggingContentEnabled=true;
options.Diagnostics.IsLoggingEnabled=true;
```

**Comment by shibayan** [comment]
@xboxeer The JSON response of the method call that raises the exception is retrieved.

```
[Informational] Azure-Core: Response [026d2932-7e80-4938-bcaf-9a4b2a0d7c0c] 200 OK (01.5s)
Cache-Control:no-cache
Pragma:no-cache
Warning:REDACTED
Strict-Transport-Security:REDACTED
x-ms-request-id:0811116a-12a6-4e15-a19c-96f96c7b0acf
Server:Microsoft-IIS/10.0
X-AspNet-Version:REDACTED
X-Powered-By:REDACTED
x-ms-ratelimit-remaining-subscription-writes:REDACTED
x-ms-correlation-request-id:REDACTED
x-ms-routing-request-id:REDACTED
X-Content-Type-Options:REDACTED
Date:Fri, 21 Oct 2022 06:16:11 GMT
Content-Length:826
Content-Type:application/json
Expires:-1

[Verbose] Azure-Core: Response [026d2932-7e80-4938-bcaf-9a4b2a0d7c0c] content: {"id":"/subscriptions/6f43ad45-521d-4bd7-9d01-f95a290041fe/resourceGroups/DaruTest-RG/providers/Microsoft.Web/certificates/cert-test-01","name":"cert-test-01","type":"Microsoft.Web/certificates","location":"centralus","tags":{},"properties":{"password":null,"friendlyName":"","subjectName":"acmebot.daruyanagi.work","hostNames":["acmebot.daruyanagi.work"],"pfxBlob":null,"siteName":null,"selfLink":null,"issuer":"R3","issueDate":"2022-10-15T14:04:20+00:00","expirationDate":"2023-01-13T14:04:19+00:00","thumbprint":"3D4B30B72A3120361FE77F739D26AB803E375CF9","valid":null,"toDelete":null,"cerBlob":null,"publicKeyHash":null,"hostingEnvironment":null,"hostingEnvironmentProfile":null,"keyVaultId":"","keyVaultSecretName":"","webSpace":"DaruTest-RG-CentralUSwebspace","serverFarmId":null,"tags":{},"resourceGroup":"DaruTest-RG"}}
```

```
Unhandled exception. System.ArgumentException: Value cannot be an empty string. (Parameter 'resourceId')
   at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppService.AppCertificateData.DeserializeAppCertificateData(JsonElement element)
   at Azure.ResourceManager.AppService.CertificatesRestOperations.CreateOrUpdateAsync(String subscriptionId, String resourceGroupName, String name, AppCertificateData data, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppService.AppCertificateCollection.CreateOrUpdateAsync(WaitUntil waitUntil, String name, AppCertificateData data, CancellationToken cancellationToken)
   at Program.<Main>$(String[] args) in C:\Users\shibayan\source\repos\ConsoleApp55\ConsoleApp55\Program.cs:line 36
   at Program.<Main>(String[] args)
```

**Comment by xboxeer** [comment]
@shibayan , the exception is because the keyVaultId in json is empty and SDK is trying to use it to generate a resourceidentifier for keyvault, hence we throw this exception.
So in this case, is your certificate not bind to a key vault? if so, you can use Azure SDK Http Pipeline to by pass this exception
1. Refer to this code to write a policy: https://github.com/Azure/azure-sdk-for-net/blob/91ab305069bf3b4e14f1f206b31cf2aa6d2d64d4/common/ManagementTestShared/Redesign/ResponseNullFilterPolicy.cs
2. Instantiate the policy and register that policy in ArmClient through ArmClient option, you can refer the code here: https://github.com/Azure/azure-sdk-for-net/blob/91ab305069bf3b4e14f1f206b31cf2aa6d2d64d4/common/ManagementTestShared/Redesign/ManagementRecordedTestBase.cs#L89

You can use policy to check the raw response and make changes to the raw json to have the line `"keyvaultid":""` removed. 

Meanwhile, we'll have a fix to our SDK so that we won't throw exception when the property value is empty string

**Comment by xboxeer** [comment]
Great to hear the workaround worked! 
If you have any other feedback to our Azure SDK, feel free to let us know in this [survey](https://www.surveymonkey.com/r/YSYFMFF)

**Comment by BastienPerdriau** [comment]
Hi,

I have this exact same error at the moment.
I hope that a new version will fix this.

However, thank tou @shibayan for the workaround you found, I will test it right away.
