### ISSUE TITLE
[BUG] Azure.Monitor.Ingestion failing live tests

### ISSUE THREAD

**Issue by vishweshbankwar** [Azure/azure-sdk-for-net#31727]
### Library name and version

Azure.Monitor.Ingestion

### Describe the bug

Live tests are failing with following error

  Error Message:
   System.InvalidOperationException : Unable to find environment variable MONITOR_AZURE_MONITOR_INGESTION_DATA_COLLECTION_ENDPOINT or AZURE_MONITOR_INGESTION_DATA_COLLECTION_ENDPOINT required by test.
Make sure the test environment was initialized using the eng/common/TestResources/New-TestResources.ps1 script.
  Stack Trace:
     at Azure.Core.TestFramework.TestEnvironment.EnsureValue(String name, String value) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/TestEnvironment.cs:line 536
   at Azure.Core.TestFramework.TestEnvironment.GetRecordedVariable(String name, Action`1 options) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/TestEnvironment.cs:line 466
   at Azure.Core.TestFramework.TestEnvironment.GetRecordedVariable(String name) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/TestEnvironment.cs:line 451
   at Azure.Monitor.Ingestion.Tests.MonitorIngestionTestEnvironment.get_DCREndpoint() in /mnt/vss/_work/1/s/sdk/monitor/Azure.Monitor.Ingestion/tests/MonitorIngestionTestEnvironment.cs:line 14
   at Azure.Monitor.Ingestion.Tests.MonitorIngestionLiveTest.CreateClient(HttpPipelinePolicy policy) in /mnt/vss/_work/1/s/sdk/monitor/Azure.Monitor.Ingestion/tests/MonitorIngestionLiveTest.cs:line 35
   at Azure.Monitor.Ingestion.Tests.MonitorIngestionLiveTest.ValidInputFromArrayAsJsonWithMultiBatchWithGzip() in /mnt/vss/_work/1/s/sdk/monitor/Azure.Monitor.Ingestion/tests/MonitorIngestionLiveTest.cs:line 121
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
  Failed ValidInputFromArrayAsJsonWithSingleBatchWithGzip [1 ms]
  Error Message:
  

### Expected behavior

Pass

### Actual behavior

Fail

### Reproduction Steps

Run monitor live tests. Reproduced while running tests using /azp run net - monitor - tests on https://github.com/Azure/azure-sdk-for-net/pull/31608

**Comment by nisha-bhatia** [comment]
The live test pipeline has been created

**Comment by vishweshbankwar** [comment]
@nisha-bhatia - Could you please confirm what is the new way to force live tests on PR
I just tried /azp run net - monitor - tests and it is not working https://github.com/Azure/azure-sdk-for-net/pull/31608#issuecomment-1286114659

**Comment by nisha-bhatia** [comment]
> @nisha-bhatia - Could you please confirm what is the new way to force live tests on PR I just tried /azp run net - monitor - tests and it is not working [#31608 (comment)](https://github.com/Azure/azure-sdk-for-net/pull/31608#issuecomment-1286114659)

The pipeline has now been split into the three SDKs within monitor. To run the Ingestion tests for example, call 
/azp run net - Azure.Monitor.Ingestion - tests
and for Query tests call:
/azp run net - Azure.Monitor.Query - tests
