### ISSUE TITLE
[BUG] Bulk Archive throws exception: Expected 94300 responses for the batch request, not 1.

### ISSUE THREAD

**Issue by LeonB87** [Azure/azure-sdk-for-net#32179]
### Library name and version

Azure.Storage.Blobs.Batch 12.11.0

### Describe the bug

I'm using a slightly altered version of Microsofts Bulk archive found [on the docs](https://learn.microsoft.com/en-us/azure/storage/blobs/archive-blob?tabs=azure-portal#bulk-archive) 

I'm trying to archive a specific set of blobs that are in virtual folders. When submitting the batch job, An exception is thrown.

message:
```log
Invalid response
Status: 202 (Accepted)

Headers:
Transfer-Encoding: chunked
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: bfaf37d6-e01e-0063-208c-ebeefd000000
x-ms-version: 2021-10-04
x-ms-client-request-id: b79b526a-5ad4-4e91-81fe-002c5bb9efef
Date: Sat, 29 Oct 2022 11:48:23 GMT
Content-Type: multipart/mixed; boundary=batchresponse_f453577e-10e5-43b3-8f08-61a3fe63f847
```

Inner exception
```log
Expected 94300 responses for the batch request, not 1.
```

stack trace
```log
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<UpdateOperationResponses>d__38.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<SubmitBatchInternal>d__36.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<SetBlobsAccessTierInteral>d__44.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<SetBlobsAccessTierAsync>d__43.MoveNext()
   at Program.<<<Main>$>g__BulkArchiveContainerContents|0_0>d.MoveNext() in D:\GIT Repositories\BlobStorageBulkArchiver\BlobStorageBulkArchiver\BlobStorageBulkArchiver\Program.cs:line 60
```

the code I'm running:

```c#
using Azure;
using Azure.Identity;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;
using System.Text.RegularExpressions;

Console.WriteLine("Starting...");

await BulkArchiveContainerContents("storageaccountName", "containerName", "^(202[0-1])|^201[0-9]");

static async Task BulkArchiveContainerContents(string accountName, string containerName, string regex)
{
    string containerUri = string.Format("https://{0}.blob.core.windows.net/{1}",
                                    accountName,
                                    containerName);

    // Get container client, using Azure AD credentials.
    BlobUriBuilder containerUriBuilder = new(new Uri(containerUri));
    BlobContainerClient blobContainerClient = new(containerUriBuilder.ToUri(),
                                                                      new DefaultAzureCredential());

    // Get URIs for blobs in this container and add to stack.
    var blobs = new List<Uri>();
    var excludedBlobs = new List<Uri>();
    try
    {
        await foreach (var item in blobContainerClient.GetBlobsAsync())
        {
            var match = Regex.Match(item.Name, regex, RegexOptions.IgnoreCase);
            if (match.Success)
            {
                blobs.Add(blobContainerClient.GetBlobClient(item.Name).Uri);
            } else
            {
                excludedBlobs.Add(blobContainerClient.GetBlobClient(item.Name).Uri);
            }
        }

        Console.WriteLine($"Found a total of '{blobs.Count}' blobs and excluded '{excludedBlobs.Count}'");

        if (blobs.Count >= 1)
        {
            Console.WriteLine($"Example of included file: '{blobs.Last().AbsolutePath}'");
        }
        
        if (excludedBlobs.Count >= 1)
        {
            Console.WriteLine($"Example of excluded file: '{excludedBlobs.Last().AbsolutePath}'");
        }

        // Get the blob batch client.
        BlobBatchClient blobBatchClient = blobContainerClient.GetBlobBatchClient();

        Console.WriteLine("Press any key to continue"); 
        var reply = Console.ReadLine();
        _ = await blobBatchClient.SetBlobsAccessTierAsync(blobUris: blobs, accessTier: AccessTier.Archive);
    }
    catch (RequestFailedException e)
    {
        Console.WriteLine(e.Message);
    }
}
```
the amount of files that are to be archived is 94300.

Even though an "accepted" is returned, the blobs are not archived. I created a new storage account with a similar structure, but only a few files, and that works without an issue.

I tried changing the regex to ^2019 which included 6973 files. A similar Exception was thrown

### Expected behavior

blobs should be archived.

### Actual behavior

blobs are not archived and an exception is thrown

### Reproduction Steps

unknown how to simply reproduce.

### Environment

- Windows 11
- .NET 6.0
- StorageV2 
- Blob Soft Delete Enabled
- Contianer Soft Delete Enabled
- Versioning Enabled
- Change Log Enabled

**Comment by navba-MSFT** [comment]
@LeonB87 Thanks for reaching out to us and reporting this issue. I am unable to reproduce this issue. Since your goal is to bulk archive the storage blobs, Could you try the built-in feature of Azure Storage - [Blob Lifecycle Management (BLM) policy](https://learn.microsoft.com/en-us/azure/storage/blobs/archive-blob?tabs=azure-portal#step-1-create-the-rule-and-specify-the-blob-type) and check if that helps ? Awaiting your reply.
