### ISSUE TITLE
NullReferenceException in RetryDelegatingHandler when concurrent requests are retried

### ISSUE THREAD

**Issue by chrisvanderpennen** [Azure/azure-sdk-for-net#3224]
Tested against Microsoft.Rest.ClientRuntime 2.3.7 / Net452
Environment: i7-4770, Windows 7, NET 4.6.1, VS2017 update 2

When making concurrent requests to a server intermittently returning timeout errors, RetryDelegatingHandler sometimes throws NullReferenceException.  I suspect a request task is being preempted just before https://github.com/Azure/azure-sdk-for-net/blob/vs17Dev/src/SdkCommon/ClientRuntime/ClientRuntime/RetryDelegatingHandler.cs#L112 and another is raising `this.Retrying`, causing all `responseMessage` closures to be set to null before their status code can be read.

I have been able to reliably reproduce the error with the following MSTest case:

```csharp
using System.Collections.Generic;
using System.Diagnostics;
using System.Net;
using System.Net.Http;
using System.Threading;
using System.Threading.Tasks;

using Microsoft.Rest;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace MinimalReproduction {

    [TestClass]
    public class RetryDelegatingHandlerRace
    {

        [TestMethod]
        public async Task ConcurrentGrindRetryDelegatingHandler() {
            var handler = 
                new SendableHandler(new RetryDelegatingHandler(new GenerateFailureHandler()));
            var tasks = new List<Task<HttpResponseMessage>>();
            var stopwatch = Stopwatch.StartNew();
            do {
                await Task.WhenAll(tasks);
                tasks.Clear();
                for (var i = 0; i < 100; i++) {
                    tasks.Add(
                        handler.SendAsync(
                            new HttpRequestMessage(HttpMethod.Get, "http://localhost"),
                            CancellationToken.None));
                }
            }
            while (stopwatch.ElapsedMilliseconds < 10000);
        }

        private class GenerateFailureHandler : DelegatingHandler {
            protected override async Task<HttpResponseMessage> SendAsync(
                HttpRequestMessage request,
                CancellationToken cancellationToken) {
                await Task.Yield();
                return new HttpResponseMessage(HttpStatusCode.GatewayTimeout);
            }
        }

        private class SendableHandler : DelegatingHandler {
            public SendableHandler(HttpMessageHandler innerHandler) : base(innerHandler) { }

            public new Task<HttpResponseMessage> SendAsync(
                HttpRequestMessage request,
                CancellationToken cancellationToken) {
                return base.SendAsync(request, cancellationToken);
            }
        }
    }
}
```

**Comment by alex-zyl** [comment]
Our team had also faced with this issue on our non-prod environments during load testing
Stacktrace: 
```
System.NullReferenceException:
   at Microsoft.Rest.RetryDelegatingHandler+<>c__DisplayClass11_0+<<SendAsync>b__1>d.MoveNext (Microsoft.Rest.ClientRuntime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.Rest.RetryDelegatingHandler+<SendAsync>d__11.MoveNext (Microsoft.Rest.ClientRuntime, Version=2.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Net.Http.HttpClient+<FinishSendAsync>d__58.MoveNext (System.Net.Http, Version=4.1.1.1, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.Azure.Search.DocumentsOperations+<DoContinueSearchWithHttpMessagesAsync>d__21`3.MoveNext (Microsoft.Azure.Search, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification (mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
   at Microsoft.Azure.Search.DocumentsOperationsExtensions+<SearchAsync>d__15.MoveNext (Microsoft.Azure.Search, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35)
```

**Comment by grahambunce** [comment]
Still happening - any idea if this will be fixed?


Azure Search SDK which uses this throws NullReferenceException

`at Microsoft.Rest.RetryDelegatingHandler.<>c__DisplayClass11_0.<<SendAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.RetryDelegatingHandler.<SendAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Azure.Search.DocumentsOperations.<DoContinueSearchWithHttpMessagesAsync>d__21`3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Search.DocumentsOperationsExtensions.<SearchAsync>d__15.MoveNext()`

**Comment by shahabhijeet** [comment]
@chrisvanderpennen @grahambunce Extreamly sorry for not addressing this issue earlier.
We are in process of taking a look at our current code base and are prioritizing things that needs to be either revisited or re-written.
This particular error is around our policies and the extensibility provided to apply policies (especially retry policies) to RPs for individual needs.
I will be tackling that entire stack as soon as our deliverables are finished for Ignite.
I know this is not a good answer, but would appreciate your patience.
Please do let me know if this is causing any major issues and we can prioritize this much sooner.

**Comment by alex-zyl** [comment]
@shahabhijeet 
Is there any progress regarding this issue? NRE still occur in the latest package version

**Comment by VaclavK** [comment]
@shahabhijeet I am seeing following stracktrace with KeyVaultClient (3.0.3)->RestClientRuntime (2.3.19)
under **.net core 2.2**

seems this could be same issue - do you prefer new issue?

at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken)

my scenario  - Polly around GetSecretWithHttpMessageAsync - this is done after secret is recovered and effectively waits till the secret becomes available (there is a delay between recovery returning response and secret being "available")

     var response = await Policy
                .Handle<KeyVaultErrorException>(r =>
                    r.Response.StatusCode == HttpStatusCode.NotFound ||
                    r.Response.StatusCode == HttpStatusCode.Conflict)
                .Or<HttpRequestWithStatusException>(r => r.StatusCode == HttpStatusCode.NotFound || r.StatusCode == HttpStatusCode.Conflict)
                .WaitAndRetryForeverAsync(w => TimeSpan.FromMilliseconds(recoveryLoopWaitTime))
                .ExecuteAsync(() => client.GetSecretWithHttpMessagesAsync(keyVaultUrl, secretName,string.Empty /*latest*/));

**Comment by Petermarcu** [comment]
KeyVault has had a new library released https://www.nuget.org/packages/Azure.Security.KeyVault.Secrets/4.0.3 and its associated packages for Keys and Certificates. Search is also being rewritten and a preview has shipped here. https://www.nuget.org/packages/Azure.Search.Documents/1.0.0-preview.2 

Long story short, we are replanting all of the Azure libraries over time on top of a new, more reliable platform that is built for concurrency and thread safety. It also supports a customizable policy pipeline. Addressing this issue in the older client runtime is likely not something that we're going to be able to address. Please try the newer versions of the libraries that are based on Azure.Core and file new issues if you encounter problems.
