### ISSUE TITLE
KeyVault Management tests failing on latest vs17Dev branch

### ISSUE THREAD

**Issue by rijethma** [Azure/azure-sdk-for-net#3234]
Error:

System.NotSupportedException occurred
  HResult=0x80131515
  Message=Username/Password login is supported only in NET45 projects
  Source=<Cannot evaluate the exception source>
  StackTrace:
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.Login()
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironment.RecorderModeSettings()
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.TestEnvironmentFactory.GetTestEnvironment()
   at KeyVault.Management.Tests.KeyVaultTestBase..ctor(MockContext context) in C:\repo\github\azure-sdk-for-net\src\SDKs\KeyVault\Management\KeyVaultManagement.Tests\KeyVaultTestBase.cs:line 45
   at KeyVault.Management.Tests.VaultOperationsTest.KeyVaultManagementVaultCreateUpdateDelete() in C:\repo\github\azure-sdk-for-net\src\SDKs\KeyVault\Management\KeyVaultManagement.Tests\VaultOperationsTest.cs:line 25

File: https://github.com/Azure/azure-sdk-for-net/blob/vs17Dev/src/SDKs/KeyVault/Management/KeyVaultManagement.Tests/KeyVaultTestBase.cs#L45

What happening here? We're just using test framework: TestEnvironmentFactory.GetTestEnvironment()

Anything  changed? What is the fix?

**Comment by shahabhijeet** [comment]
@rijethma so coupel of reasons:
1. Azure Cloud no longer supports username/password in production (unless it's org Id)
2. ADAL no longer supports username/password in .NET core assemblies

So we had no choice but to remove that support.

You have two options:
1) Run your test in .NET 45+ (which I assume you are doing)
2) Start using Service Principle/Secret for your .NET core scenarios

**Comment by markcowl** [comment]
Closed as resolved.
