### ISSUE TITLE
[BUG] Azure.Data.Tables.GetEntityAsync randomly failed to send request

### ISSUE THREAD

**Issue by northtyphoon** [Azure/azure-sdk-for-net#32455]
### Library name and version

Azure.Data.Tables.12.6.1

### Describe the bug

Our service runs on linux asp.net 6.0 container. We frequently ran into a connection issue when querying table entity through `Azure.Data.Tables.TableClient.GetEntityAsync`.

When it worked, `GetEntityAsync` can finish in milliseconds. When it didn't work, `GetEntityAsync` was just timed out after 15 seconds (we passed a cancellation token with 15 second timeout). 

When the issue occurred, we tried to capture tcpdump to the target table service, but we didn't observe any traffic. We ran `curl` on the same container and could successfully connect to the target table service and tcpdump was also able to capture the traffic.

It led us to think `GetEntityAsync` for some reason was stuck somewhere before even attempting to connect to the table service.

Is there any additional diagnostic logs we can collect to troubleshoot the issue?

Here is the call stack.

 ---> System.Threading.Tasks.TaskCanceledException: The operation was canceled.
   at Azure.Core.CancellationHelper.ThrowOperationCanceledException(Exception innerException, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Data.Tables.TableRestClient.QueryEntityWithPartitionAndRowKeyAsync(String table, String partitionKey, String rowKey, Nullable`1 timeout, QueryOptions queryOptions, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.GetEntitiyInternalAsync[T](Boolean async, String partitionKey, String rowKey, IEnumerable`1 select, CancellationToken cancellationToken)
   at Azure.Data.Tables.TableClient.GetEntityAsync[T](String partitionKey, String rowKey, IEnumerable`1 select, CancellationToken cancellationToken)

### Expected behavior

see above

### Actual behavior

see above

### Reproduction Steps

see above

### Environment

.net 6.0.9
linux container mcr.microsoft.com/dotnet/aspnet:6.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @northtyphoon - Based on the stack, it does appear that we are timing out while trying to buffer the response stream from the service. About the only thing I could recommend is to enable logging and open a ticket with the service team with the given request Id so that they can investigate if there was a service issue.
