### ISSUE TITLE
Cancelling HttpPipeline.Send() can fail by disposing stream during read

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#32577]
Run the following app (or clone https://github.com/mikeharder/http-pipeline-send-cancel):

```c#
using Azure.Core;
using Azure.Core.Pipeline;
using Microsoft.AspNetCore.Builder;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using System.Net;
using System.Threading;

namespace HttpPipelineSendCancel
{
    internal class Program
    {
        // Config
        private const int MinDelayMilliseconds = 1;
        private const int MaxDelayMilliseconds = 20;
        private const int ResponseSize = 10_000_000;

        private static readonly string _response = new string('a', ResponseSize);
        private static readonly HttpPipeline _pipeline = HttpPipelineBuilder.Build(new TestClientOptions());

        static async Task Main()
        {
            Console.WriteLine("Starting web server...");
            await new WebHostBuilder()
                .UseKestrel()
                .Configure(app => app.Run(async context =>
                {
                    await context.Response.WriteAsync(_response);
                }))
                .Build()
                .StartAsync();

            var random = new Random();
            while (true)
            {
                var delay = random.Next(MinDelayMilliseconds, MaxDelayMilliseconds);
                using (var cts = new CancellationTokenSource(millisecondsDelay: delay))
                {
                    try
                    {
                        var message = CreateMessage();
                        _pipeline.Send(message, cts.Token);
                        Console.WriteLine($"[{DateTime.Now:hh:mm:ss.fff}] completed");
                    }
                    catch (TaskCanceledException)
                    {
                        Console.WriteLine($"[{DateTime.Now:hh:mm:ss.fff}] cancelled");
                    }
                }
            }
        }

        private static HttpMessage CreateMessage()
        {
            var message = _pipeline.CreateMessage();
            message.Request.Uri.Reset(new Uri("https://localhost:5001"));
            return message;
        }

        private class TestClientOptions : ClientOptions { }
    }
}
```

The app should fail pretty quickly with the following exception.  If it doesn't fail, try modifying `MinDelayMilliseconds`, `MaxDelayMilliseconds`, or `ResponseSize` as appropriate for your dev machine.

```
Unhandled exception. System.NotSupportedException:  This method may not be called when another read operation is pending.
   at System.Net.Security.SslStream.ReadAsyncInternal[TIOAdapter](Memory`1 buffer, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at System.Net.Security.SslStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at System.IO.Stream.Read(Span`1 buffer)
   at System.Net.Http.HttpConnection.Read(Span`1 destination)
   at System.Net.Http.HttpConnection.ChunkedEncodingReadStream.Read(Span`1 buffer)
   at System.Net.Http.HttpBaseStream.Read(Byte[] buffer, Int32 offset, Int32 count)
   at Azure.Core.Pipeline.ResponseBodyPolicy.CopyTo(Stream source, Stream destination, CancellationTokenSource cancellationTokenSource)
   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted(ValueTask task)
   at Azure.Core.Pipeline.ResponseBodyPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.LoggingPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
```

We believe the bug is our code can call Dispose() concurrently with Read():

https://github.com/Azure/azure-sdk-for-net/blob/785c355bde40ae4b59d922611666f52b16074e6e/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs#L80

Ideally, this would throw an `ObjectDisposedException`, but it throws the "nested read" exception instead due to https://github.com/dotnet/runtime/issues/78586.

**Comment by mikeharder** [comment]
@JoshLove-msft: Can we get this fixed in the next release of Azure.Core?  It's impacting at least one storage customer (see #31570).

**Comment by JoshLove-msft** [comment]
I don't see why not - it should be a matter of just duplicating the logic we have [here](https://github.com/Azure/azure-sdk-for-net/blob/785c355bde40ae4b59d922611666f52b16074e6e/sdk/core/Azure.Core/src/Pipeline/Internal/ResponseBodyPolicy.cs#L106-L109) for NotSupportedException
