### ISSUE TITLE
[BUG] VMSS extension can not be created as part of the VMSS Creation request 

### ISSUE THREAD

**Issue by desokey** [Azure/azure-sdk-for-net#32599]
### Library name and version

Azure.ResourceManager.Compute

### Describe the bug

When creating new VMSS using CreateOrUpdate method , and adding CustomScript extension as part of VirtualMachinecaleetData object , 
Creation faild 

### Expected behavior

Successful Creation 

### Actual behavior

Object reference not set to an instance of an object. , it complians about a null collection,

   at Azure.ResourceManager.Compute.VirtualMachineScaleSetExtensionData.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
   at Azure.ResourceManager.Compute.Models.VirtualMachineScaleSetExtensionProfile.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
   at Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, IUtf8JsonSerializable value)
   at Azure.ResourceManager.Compute.Models.VirtualMachineScaleSetVmProfile.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetData.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
   at Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, IUtf8JsonSerializable value)
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetsRestOperations.CreateCreateOrUpdateRequest(String virtualMachineScaleSetName, String subscriptionId, String resourceGroupName, VirtualMachineScaleSetData data)
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetsRestOperations.<CreateOrUpdateAsync>d__9.MoveNext()
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetCollection.<CreateOrUpdateAsync>d__5.MoveNext()

### Reproduction Steps

```csharp
vmssModel.ExtensionProfile = new VirtualMachineScaleSetExtensionProfile()
                        {
                            Extensions =
                           {
                                 new VirtualMachineScaleSetExtensionData("CustomScript")
                                {
                                       AutoUpgradeMinorVersion = true,
                                       EnableAutomaticUpgrade = false,
                                       Settings = BinaryData.FromObjectAsJson(new
                                          {}),
                                       ProvisionAfterExtensions= {},
                                       ProtectedSettings = BinaryData.FromObjectAsJson(new
                                        {
                                               
                                        }),
                                       Publisher = "Microsoft.Azure.Extensions",
                                       ExtensionType = "CustomScript",
                                       TypeHandlerVersion = "2.1"
                                 }
                           }
                        },
```

### Environment

Dotnet

**Comment by desokey** [comment]
Just to save the team some time , here is my investigation so far 
1- The Request complains about the ProvisionAfterExtensions property being null, if you skip this check , you will face another issue , it will complain about the name of the extension is not provided although it is provided in the payload but the Writer does not write the name property in this method Azure.ResourceManager.Compute.Models.VirtualMachineScaleSetExtensionProfile.Azure.Core.IUtf8JsonSerializable.Write
