### ISSUE TITLE
[BUG] AppCertificateCollection.CreateOrUpdate fails with `Value cannot be an empty string. (Parameter 'resourceId')`

### ISSUE THREAD

**Issue by m8rmclaren** [Azure/azure-sdk-for-net#32763]
### Library name and version

Azure.ResourceManager.AppService v1.0.0

### Describe the bug

I'm trying to upload a user PFX certificate to Azure App Service using the `AppCertificateCollection.CreateOrUpdate` operation, but am getting an exception stating `Value cannot be an empty string. (Parameter 'resourceId')`. I discovered that this exception is thrown by `AppCertificateData.DeserializeAppCertificateData` when it de-serializes Azure's response to the CreateOrUpdate request. Below is a raw JSON response from Azure:
```json
{
    "id": "/subscriptions/9a3b9f67-507a-4c11-a580-782aa8cff16a/resourceGroups/Dev_ResourceGroup/providers/Microsoft.Web/certificates/B894ACABCEE0F1486F2E8041D37220EEDF2B00A5",
    "name": "B894ACABCEE0F1486F2E8041D37220EEDF2B00A5",
    "type": "Microsoft.Web/certificates",
    "location": "centralus",
    "tags": {},
    "properties": {
        "password": null,
        "friendlyName": "",
        "subjectName": "foobar",
        "hostNames": [
            "foobar"
        ],
        "pfxBlob": null,
        "siteName": null,
        "selfLink": null,
        "issuer": "foobar",
        "issueDate": "2022-11-29T21:28:42+00:00",
        "expirationDate": "2027-11-29T21:28:42+00:00",
        "thumbprint": "B894ACABCEE0F1486F2E8041D37220EEDF2B00A5",
        "valid": null,
        "toDelete": null,
        "cerBlob": null,
        "publicKeyHash": null,
        "hostingEnvironment": null,
        "hostingEnvironmentProfile": null,
        "keyVaultId": "",
        "keyVaultSecretName": "",
        "webSpace": "SE-CentralUSwebspace-Linux",
        "serverFarmId": null,
        "tags": {},
        "resourceGroup": "Dev_ResourceGroup"
    }
}
```
The JSON response contains null fields, which `AppCertificateData.DeserializeAppCertificateData` discovers and throws an exception. Since de-serialization occurs after the request is successfully submitted, my PFX certificate is uploaded to Azure and is usable.

### Expected behavior

I expect `AppCertificateCollection.CreateOrUpdate` to upload my PFX certificate to my Azure App Service and not throw an exception. 

### Actual behavior

Stack trace:
```
Value cannot be an empty string. (Parameter 'resourceId')
   at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppService.AppCertificateData.DeserializeAppCertificateData(JsonElement element)
   at Azure.ResourceManager.AppService.CertificatesRestOperations.CreateOrUpdate(String subscriptionId, String resourceGroupName, String name, AppCertificateData data, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppService.AppCertificateCollection.CreateOrUpdate(WaitUntil waitUntil, String name, AppCertificateData data, CancellationToken cancellationToken)
```

### Reproduction Steps

```c#
resourceId = new ResourceIdentifier("<App Service resource ID>");

// Configure client
ArmClient client= new ArmClient(new DefaultAzureCredential());
Subscription subscription = ArmClient.GetSubscriptions().Get(resourceId.SubscriptionId);
ResourceGroup resourceGroup = Subscription.GetResourceGroup(ResourceId.ResourceGroupName);

// Get app service data
WebSiteResource site = client.GetWebSiteResource(resourceId).Get();
AzureLocation location = site.Data.Location;
ResourceIdentifier appServicePlanId = site.Data.AppServicePlanId;

// Get certificate collection
AppCertificateCollection collection = ResourceGroup.GetAppCertificates();
try
{
    // Create certificate data object
    var certData = new AppCertificateData(location)
    {
        Password = password,
        PfxBlob = cert.Export(X509ContentType.Pfx, password),
        ServerFarmId = appServicePlanId,
    };
    
    // Use collection object to create certificate
    AppCertificateResource result = collection.CreateOrUpdate(WaitUntil.Completed, cert.Thumbprint, certData).Value;
}
catch (ArgumentException e)
{
    Console.Write($"Failed to upload certificate: {e.Message}\n{e.StackTrace}\n");
}
```

### Environment

Platform:
```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19044
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.31 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
IDE version:
Visual Studio 17.4.1

**Comment by m8rmclaren** [comment]
Hello! Is there any update on this?

**Comment by xboxeer** [comment]
Hi @m8rmclaren , we have an issue tracking this: https://github.com/Azure/autorest.csharp/issues/2802
Meanwhile there is a workaround to by pass the empty string issue
1. Refer to this code to write a policy: https://github.com/Azure/azure-sdk-for-net/blob/91ab305069bf3b4e14f1f206b31cf2aa6d2d64d4/common/ManagementTestShared/Redesign/ResponseNullFilterPolicy.cs
2. Instantiate the policy and register that policy in ArmClient through ArmClient option, you can refer the code here: https://github.com/Azure/azure-sdk-for-net/blob/91ab305069bf3b4e14f1f206b31cf2aa6d2d64d4/common/ManagementTestShared/Redesign/ManagementRecordedTestBase.cs#L89

You can use policy to check the raw response and make changes to the raw json to have the line `"keyvaultid":""` removed.
