### ISSUE TITLE
[Synapse] QuerySessions failing in nightly runs

### ISSUE THREAD

**Issue by AFengKK** [Azure/azure-sdk-for-net#32836]
Synapse nightly test runs are failing with:

> Error message
> Azure.RequestFailedException : Service request failed.
> Status: 500 (Internal Server Error)
> 
> Content:
> {
> "code": "InternalServerError",
> "message": "Context creation failure for session=30d3c881-fd98-4558-b7ae-a6ce2bf48079",
> "target": null,
> "details": null,
> "error": null
> }
> 
> Headers:
> Server: Kestrel Microsoft-HTTPAPI/2.0
> Strict-Transport-Security: REDACTED
> x-ms-correlation-request-id: REDACTED
> x-ms-failure-cause: REDACTED
> x-ms-request-id: b6c6ea7d-946e-4fce-a216-7eae168e7f25
> x-ms-client-request-id: ca18bd20-ee7c-49c3-8803-3b948f1449e6
> Date: Thu, 01 Dec 2022 19:51:35 GMT
> Content-Length: 179
> Content-Type: application/json; charset=utf-8
> 
> Expected: greater than or equal to 1
> But was:  0
> 
> Stack trace
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionRestClient.DeleteDataFlowDebugSession(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionRestClient.cs:line 289
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionClient.DeleteDataFlowDebugSession(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionClient.cs:line 127
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 120
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 171
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.ValidateDiagnosticScope[T](Func`1 action, MethodInfo methodInfo, String source) in /mnt/vss/_work/1/s/sdk/core/Azure.Core.TestFramework/src/Instrumentation/DiagnosticScopeValidatingInterceptor.cs:line 201
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.DisposableDataFlowDebugSession.DisposeAsync() in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 51
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 103
>    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 103
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
> 1)    at Azure.Analytics.Synapse.Artifacts.Tests.DataFlowDebugSessionClientLiveTests.QuerySessions() in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/tests/DataFlowDebugSessionClientLiveTests.cs:line 103
> 
> 2)    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionRestClient.DeleteDataFlowDebugSession(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionRestClient.cs:line 289
>    at Azure.Analytics.Synapse.Artifacts.DataFlowDebugSessionClient.DeleteDataFlowDebugSession(DeleteDataFlowDebugSessionRequest request, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/synapse/Azure.Analytics.Synapse.Artifacts/src/Generated/DataFlowDebugSessionClient.cs:line 127
> --- End of stack trace from previous location ---
>    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass4_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in /mnt/vss/_work/1/s/sdk/c

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2025556&view=results

@jsquire for notification.

**Comment by jsquire** [comment]
Synapse is owned by the service team and has multiple GH test issues open.   Since they do not use GH for work tracking, there's little value in keeping issues for each individual test.   Closing this out.
