### ISSUE TITLE
[FEATURE REQ] Allow HTTP SAS URLs for localhost

### ISSUE THREAD

**Issue by joelverhagen** [Azure/azure-sdk-for-net#32861]
### Library name

Azure.Data.Tables

### Please describe the feature.

In Azure.Data.Tables (tested (12.7.1), it's possible to create a SAS URL that cannot be used. The following exception is thrown:

Message: **Cannot use TokenCredential without HTTPS.**

```
System.ArgumentException: Cannot use TokenCredential without HTTPS. (Parameter 'endpoint')
   at Azure.Data.Tables.TableServiceClient..ctor(Uri endpoint, TableClientOptions options)
   at Program.<Main>$(String[] args) in C:\z\Trash\2022-12-04\ConsoleApp1\ConsoleApp1\Program.cs:line 18
   at Program.<Main>(String[] args)

```
Here's a repro:
```csharp
using Azure.Data.Tables;
using Azure.Data.Tables.Sas;
using Microsoft.WindowsAzure.Storage.Table;

// Make the SAS
var tableServiceClient = new TableServiceClient("UseDevelopmentStorage=true");
var table = tableServiceClient.GetTableClient("test");
var sasUri = table.GenerateSasUri(TableSasPermissions.Read, DateTimeOffset.UtcNow.AddDays(7));

Console.WriteLine(sasUri.AbsoluteUri.ToString());

// WindowsAzure.Storage
var older = new CloudTable(sasUri);
Console.WriteLine("Using older SDK...");
Console.WriteLine(await older.ExistsAsync());

// Azure.Data.Tables
var newer = new TableServiceClient(sasUri);
Console.WriteLine("Using newer SDK...");
Console.WriteLine(await newer.GetPropertiesAsync());
```

This restriction makes total sense for production scenarios, but for testing scenarios, HTTPS is a painful hurdle. I propose that the HTTPS restriction is disabled when the host is `localhost` or `127.0.0.1`.

Azurite uses HTTP by default. To make Azurite use HTTPS, it's not easy:
https://learn.microsoft.com/en-us/azure/storage/common/storage-use-azurite?tabs=visual-studio#certificate-configuration-https. There's several challenges like making your PC trust the Azurite cert and telling Azurite to use a specific cert which is impossible/hard for the Azurite VS Code extension.

![image](https://user-images.githubusercontent.com/94054/205520216-a1c25a4e-01dd-407a-90e0-98e753f85e7c.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
