### ISSUE TITLE
[BUG] BlobClient performs only a partial upload of a stream when client side encryption is enabled and the stream is buffered

### ISSUE THREAD

**Issue by goodmanmd** [Azure/azure-sdk-for-net#32958]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Describe the bug

In certain scenarios where a `Stream` is seekable, its `Length` property may be non-zero, but not reflect the actual full length of the stream because the stream has not yet been fully read.  This is the case, for example, in the `Microsoft.AspNetCore.WebUtilities.FileBufferingReadStream` class in ASP.NET Core 6.

The code in `BlobClient.StagedUploadInternal` relies on the value stream's `Length` property when client side encryption is enabled:

```
if (UsingClientSideEncryption)
{
    options ??= new BlobUploadOptions();

    // if content length was known, we retain that for dividing REST requests appropriately
    expectedContentLength = content.GetLengthOrDefault();
    IClientSideEncryptor encryptor = ClientSideEncryption.GetClientSideEncryptor();
    if (expectedContentLength.HasValue)
    {
        expectedContentLength = encryptor.ExpectedOutputContentLength(expectedContentLength.Value);
    }
    (content, options.Metadata) = await new BlobClientSideEncryptor(encryptor)
        .ClientSideEncryptInternal(content, options.Metadata, async, cancellationToken).ConfigureAwait(false);
}
```

As a result, when the stream is passed to the `BlobClient` via the `UploadAsync` method, the resulting blob contains only the bytes up to the stream's `Length` rather than the full contents of the stream.

### Expected behavior

Full contents of the stream is encrypted and uploaded to Azure Storage, and can subsequently be downloaded and decrypted successfully.

### Actual behavior

Only the portion of the stream that has already been read / buffered is uploaded to Azure Storage.  As a result, a subsequent download of the same blob may be incomplete, or more likely, fail because decryption fails with the following stack trace (depending on encryption type)

For v1 encryption
```
System.Security.Cryptography.CryptographicException: Padding is invalid and cannot be removed.
   at Internal.Cryptography.UniversalCryptoDecryptor.GetPaddingLength(ReadOnlySpan`1 block)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(ReadOnlySpan`1 inputBuffer, Span`1 outputBuffer)
   at Internal.Cryptography.UniversalCryptoDecryptor.UncheckedTransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at Internal.Cryptography.UniversalCryptoTransform.TransformFinalBlock(Byte[] inputBuffer, Int32 inputOffset, Int32 inputCount)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlockAsync(Boolean useAsync, CancellationToken cancellationToken)
   at System.Security.Cryptography.CryptoStream.FlushFinalBlock()
   at Azure.Storage.Blobs.PartitionedDownloader.FlushFinalIfNecessaryInternal(Stream destination, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.PartitionedDownloader.DownloadToAsync(Stream destination, BlobRequestConditions conditions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StagedDownloadAsync(Stream destination, BlobRequestConditions conditions, IProgress`1 progressHandler, StorageTransferOptions transferOptions, DownloadTransferValidationOptions transferValidationOverride, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(Stream destination, BlobRequestConditions conditions, StorageTransferOptions transferOptions, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(Stream destination, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(Stream destination)
```

For v2 encryption
```
System.Security.Cryptography.CryptographicException: The computed authentication tag did not match the input authentication tag.
   at System.Security.Cryptography.AeadCommon.Decrypt(SafeKeyHandle keyHandle, ReadOnlySpan`1 nonce, ReadOnlySpan`1 associatedData, ReadOnlySpan`1 ciphertext, ReadOnlySpan`1 tag, Span`1 plaintext, Boolean clearPlaintextOnFailure)
   at Azure.Storage.Cryptography.GcmAuthenticatedCryptographicTransform.TransformAuthenticationBlock(ReadOnlySpan`1 input, Span`1 output)
   at Azure.Storage.Cryptography.AuthenticatedRegionCryptoStream.FlushFinalInternal(Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.PartitionedDownloader.FlushFinalIfNecessaryInternal(Stream destination, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.PartitionedDownloader.DownloadToAsync(Stream destination, BlobRequestConditions conditions, CancellationToken cancellationToken)
```

### Reproduction Steps

This is a sample method in an ASP.NET Core 6 web API.  The use case is a POST method that passes request body content on to blob storage, with client side encryption enabled.

```
[HttpPost]
public async Task<IActionResult> MyWebApiMethod(CancellationToken cancellationToken)
{
    //Enable buffering on Request.Body, which replaces the underlying stream object
    //with an instance of FileBufferingReadStream. Per the XmlDoc Summary of
    //FileBufferingReadStream in ASP.NET Core 6:
    //
    //The total bytes read from and buffered by the stream so far, it will not represent the full
    //data length until the stream is fully buffered. e.g. using <c>stream.DrainAsync()</c>.
    Request.EnableBuffering();
    var buffer = new char[2048];
    using var reader = new StreamReader(Request.Body, Encoding.UTF8, leaveOpen: true);

    //read part of the request body, to do some input validation for example
    var bytesRead = await reader.ReadAsync(buffer, 0, buffer.Length);
    
    //at this point, Request.Body.Length will equal buffer.Length (i.e. 2048)
    //but assume the Request Body that was POSTed was actually larger (e.g. 4000 bytes)

    Request.Body.Seek(0, SeekOrigin.Begin);

    var tokenCredential = new DefaultAzureCredential();
    var cryptoClient = new CryptographyClient(new Uri("KEY URI HERE"), tokenCredential);
    var keyResolver = new KeyResolver(tokenCredential);

    var encryptionOptions = new ClientSideEncryptionOptions(ClientSideEncryptionVersion.V2_0)
    {
        KeyEncryptionKey = cryptoClient,
        KeyResolver = keyResolver,
        KeyWrapAlgorithm = KeyWrapAlgorithm.RsaOaep.ToString()
    };

    var blobClientOptions = new SpecializedBlobClientOptions { ClientSideEncryption = encryptionOptions };

    var blobServiceClient = new BlobServiceClient(new Uri("BLOB SERVICE URI HERE"), tokenCredential, blobClientOptions);
    var containerClient = blobServiceClient.GetBlobContainerClient("CONTAINERNAME");
    var blobClient = containerClient.GetBlobClient("BLOBNAME");

    //Since Request.Body.Length has a non-zero value, the client encryption
    //code will now assume this is the total length of the stream content.
    //Uncommenting the line below will resolve the issue because the DrainAsync
    //method ensures the entire Request stream is read, thus ensuring
    //the value Request.Body.Length matches the actual length of the stream
    //await Request.Body.DrainAsync(cancellationToken);

    await blobClient.UploadAsync(Request.Body, cancellationToken);

    return Accepted();
}
```

### Environment

.NET SDK (reflecting any global.json):
 Version:   6.0.403
 Commit:    2bc18bf292

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.403\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

Visual Studio Professional 2022 - 17.4.2

**Comment by navba-MSFT** [comment]
Adding Service team to look into this. 

@xgithubtriage Could you please look into this once you get a chance ? Thanks in advance.

**Comment by radmint** [comment]
@navba-MSFT we are also getting this issue in Azure.Storage.Blobs v12.13.0, is there any update to this investigation?
