### ISSUE TITLE
[BUG] Custom Timeout doesn't work in Azure.Messaging.EventHubs (5.7.4)

### ISSUE THREAD

**Issue by sharmilamuthukrishnan** [Azure/azure-sdk-for-net#33031]
We are using the package Azure.Messaging.EventHubs version 5.7.4. And the CancellationToken Timeout is not working correctly with Azure.Messaging.EventHub, irrespective of whatever the cancellationToken timeout we set , it will always takes around 2 to 3 seconds and throws task canceled exception when the Azure Event Hub is taking time to respond back or got any issues.

```
private async Task SendBatchAsync(EventDataBatch batch)
{
            var stopWatch = Stopwatch.StartNew();
            try
            {
                _logger.MemberEntry("Sending batch of messages having {message_count} messages, size: {message_size_bytes} bytes",
                    new object[] { batch.Count, batch.SizeInBytes });
                using var cancellationTokenSource = new CancellationTokenSource();
                cancellationTokenSource.CancelAfter(TimeSpan.FromSeconds(4));
                await _eventHubProducer.SendAsync(batch, cancellationTokenSource.Token);
            }
            catch (Exception ex)
            {
                _logger.Error("Send batch failed for the event_hub {event_hub} with {exception}",
                    new object[] { _eventHubProducer.FullyQualifiedNamespace, ex });
                throw;
            }
            finally
            {
                _logger.MemberExit("Send batch completed for the event_hub {event_hub} in {elapsedmillisecond} ms",
                    new object[] { _eventHubProducer.FullyQualifiedNamespace, stopWatch.ElapsedMilliseconds });
            }
        }
```

Also, sometimes when the batch size is more, it takes more time to publish events. Example, when the batch size is around 1012618 bytes, I am getting TaskCanceledException after 2003 milliseconds. And when I retried after a second, it succeeded within 150 milliseconds.

**Comment by jsquire** [comment]
Hi @sharmilamuthukrishnan.  Thank you for reaching out and we regret that you're experiencing difficulties.   The Event Hubs clients do their best to honor cancellation tokens, though doing so is intentionally not precise nor guaranteed.   When clients are performing operations, they prioritize ensuring that data and the state of the client are not corrupted and will honor cancellation at points where it is safe to do so.   This means that cancellation may take longer than the period in your token or that an operation may already be at a point where it cannot be cancelled.

If you're looking for more precise control over network operations, I'd suggest configuring the `TryTimeout`, as demonstrated in [Configuring the timeout used for Event Hubs service operations](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#configuring-the-timeout-used-for-event-hubs-service-operations).  However, it is important to note that the timeout is also governed by protecting data from corruption.

One other thing that Is worth noting from your sample, is that 4 seconds is well below the recommended threshold for ensuring application health.  Because connections are established as needed, some `SendAsync` calls may take extra time to open the connection, send authorization, and then send your batch of events.   The default timeout for network operations is 60 seconds and we would recommend not going less than 30 seconds to avoid finding yourself in the state where events can never be published.

**Comment by sharmilamuthukrishnan** [comment]
Hi @jsquire,
Thank you for the quick response and suggestion. I tried to use CustomRetryPolicy as suggested in the link  [Configuring the timeout used for Event Hubs service operations](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#configuring-the-timeout-used-for-event-hubs-service-operations).  This is the sample snippet :

```
using Azure.Messaging.EventHubs;
using Honeywell.Forge.Logger.Core.Extensions;
using Microsoft.Extensions.Logging;
using System;
using System.Threading.Tasks;

namespace iotvnext.annotationpointhistorystreamer.EventHub
{
    internal class CustomEventHubRetryPolicy : EventHubsRetryPolicy
    {
        private readonly int waitTimeInMilliSeconds;
        private readonly ILogger<CustomEventHubRetryPolicy> _logger;
       
        public CustomEventHubRetryPolicy(int waitTimeInMilliSeconds, ILogger<CustomEventHubRetryPolicy> logger)
        {
            this.waitTimeInMilliSeconds = waitTimeInMilliSeconds;
            _logger = logger;
        }

        public override TimeSpan? CalculateRetryDelay(Exception lastException, int attemptCount)
        {
            if(attemptCount > 3)
            {
                _logger.Warning(
                       "Exception occured while publishing annotation and already retried to publish annotation.| RetryCount:{RetryCount} | Exception: {Exception}",
                       new object[] { attemptCount, lastException });
                return null;
            }

            var isTransientException = ((lastException is EventHubsException ehe) && ehe.IsTransient) ||
                                       lastException is TaskCanceledException || 
                                       lastException is TimeoutException;

            TimeSpan ? retryTimeSpan = isTransientException ? TimeSpan.FromSeconds(1) : default(TimeSpan?);

            if (isTransientException)
            {
                _logger.Warning(
                      "Exception occured while publishing annotation.Retrying to publish annotation.| RetryCount:{RetryCount} | Exception: {Exception} | IsTransient: {IsTransient}",
                      new object[] { attemptCount, lastException, isTransientException });
            }
            else
            {
                _logger.Warning(
                        "Exception occured while publishing annotation.But not retrying to publish annotation.| RetryCount:{RetryCount} | Exception: {Exception} | IsTransient: {IsTransient}",
                        new object[] { attemptCount, lastException, isTransientException });
            }
            return retryTimeSpan;
        }

        public override TimeSpan CalculateTryTimeout(int attemptCount) => TimeSpan.FromMilliseconds(30000);
    }
}
```
But 2 strange things observed here :
1.  Even though the TryTimeout is given as 30 seconds, we are getting  TimeoutException even after 2 seconds : 
```
System.TimeoutException: The operation did not complete within the allocated time 00:00:02 for object message.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.SendingAmqpLink.<>c.<SendMessageAsync>b__12_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(IReadOnlyCollection`1 messages, String partitionKey, CancellationToken cancellationToken)
```
2. To check the behavior of this custom retry policy on non-transient errors, I have disabled all public network access to this event hub and tried to publish the message. So this , I am getting below exception :

```
System.UnauthorizedAccessException: Put token failed. status-code: 401, status-description: Ip has been prevented to connect to the endpoint.
           For more information see:
           Virtual Network service endpoints:
              Event Hubs: https://go.microsoft.com/fwlink/?linkid=2044192
              Service Bus: https://go.microsoft.com/fwlink/?linkid=2044235
           IP Filters:
              Event Hubs:  https://go.microsoft.com/fwlink/?linkid=2044428
              Service Bus: https://go.microsoft.com/fwlink/?linkid=2044183
     TrackingId:678b6993-3a35-4184-81a4-4790b2a5d230_G15S1, SystemTracker:historyparsertesting.servicebus.windows.net:historyparsertesting, Timestamp:2022-12-16T05:26:27.
For troubleshooting information, see https://aka.ms/azsdk/net/eventhubs/exceptions/troubleshoot
 ---> Microsoft.Azure.Amqp.AmqpException: Put token failed. status-code: 401, status-description: Ip has been prevented to connect to the endpoint.
           For more information see:
           Virtual Network service endpoints:
              Event Hubs: https://go.microsoft.com/fwlink/?linkid=2044192
              Service Bus: https://go.microsoft.com/fwlink/?linkid=2044235
           IP Filters:
              Event Hubs:  https://go.microsoft.com/fwlink/?linkid=2044428
              Service Bus: https://go.microsoft.com/fwlink/?linkid=2044183
     TrackingId:678b6993-3a35-4184-81a4-4790b2a5d230_G15S1, SystemTracker:historyparsertesting.servicebus.windows.net:historyparsertesting, Timestamp:2022-12-16T05:26:27.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.AmqpCbsLink.EndSendToken(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c.<SendTokenAsync>b__4_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.RequestAuthorizationUsingCbsAsync(AmqpConnection connection, CbsTokenProvider tokenProvider, Uri endpoint, String audience, String resource, String[] requiredClaims, TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateSendingLinkAsync(AmqpConnection connection, Uri endpoint, TransportProducerFeatures features, PartitionPublishingOptions options, TimeSpan operationTimeout, TimeSpan linkTimeout, String linkIdentifier, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenProducerLinkAsync(String partitionId, TransportProducerFeatures features, PartitionPublishingOptions options, TimeSpan operationTimeout, TimeSpan linkTimeout, String linkIdentifier, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.CreateLinkAndEnsureProducerStateAsync(String partitionId, String producerIdentifier, PartitionPublishingOptions partitionOptions, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.CreateLinkAndEnsureProducerStateAsync(String partitionId, String producerIdentifier, PartitionPublishingOptions partitionOptions, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(IReadOnlyCollection`1 messages, String partitionKey, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
```
and retried for 3 times. But ideally its a non-transient error, right? so it shouldn't be retried.

**Comment by sharmilamuthukrishnan** [comment]
Thanks @jsquire for your response, it helped a lot.
