### ISSUE TITLE
[BUG] Always get deserialization errors in `ContainerAppData`

### ISSUE THREAD

**Issue by shibayan** [Azure/azure-sdk-for-net#33185]
### Library name and version

Azure.ResourceManager.AppContainers 1.0.0

### Describe the bug

Trying to get a list of Container Apps using the SDK always seems to throw a deserialization error. Information on the exceptions is as follows.

```
System.UriFormatException
  HResult=0x80131537
  Message=Invalid URI: The format of the URI could not be determined.
  Source=System.Private.Uri
  Stack Trace:
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.AppContainers.ContainerAppData.DeserializeContainerAppData(JsonElement element)
   at Azure.ResourceManager.AppContainers.Models.ContainerAppCollection.DeserializeContainerAppCollection(JsonElement element)
   at Azure.ResourceManager.AppContainers.ContainerAppsRestOperations.<ListBySubscriptionAsync>d__6.MoveNext()
   at Azure.ResourceManager.AppContainers.SubscriptionResourceExtensionClient.<>c__DisplayClass39_0.<<GetContainerAppsAsync>g__FirstPageFunc|0>d.MoveNext()
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.<AsPages>d__4.MoveNext()
   at Azure.Core.PageableHelpers.FuncAsyncPageable`1.<AsPages>d__4.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.MoveNext()
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.MoveNext()
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Program.<<Main>$>d__0.MoveNext() (C:\Users\shibayan\source\repos\ConsoleApp60\ConsoleApp60\Program.cs):行 11
   at Program.<<Main>$>d__0.MoveNext() (C:\Users\shibayan\source\repos\ConsoleApp60\ConsoleApp60\Program.cs):行 11
```

I think the most likely cause is the part of the `DeserializeContainerAppData` implementation that treats `OutboundIPAddresses` as `Uri`. It appears that `OutboundIPAddresses` cannot be represented using the `Uri` class, since they are IP address-only values.

https://github.com/Azure/azure-sdk-for-net/blob/20d964afdfc27c3420623133c8dfc05bf12ce833/sdk/containerapps/Azure.ResourceManager.AppContainers/src/Generated/Models/ContainerAppData.Serialization.cs#L261

### Expected behavior

The list of Container Apps can be obtained without any errors.

### Actual behavior

An exception is always thrown in the deserialize method.

### Reproduction Steps

Repro code

```csharp
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.AppContainers;

var armClient = new ArmClient(new AzureCliCredential());

var subscription = await armClient.GetDefaultSubscriptionAsync();

await foreach (var containerApp in subscription.GetContainerAppsAsync())
{
    Console.WriteLine(containerApp.Data.Id);
}
```

**Comment by ArthurMa1978** [comment]
@shibayan the [1.0.1](https://www.nuget.org/packages/Azure.ResourceManager.AppContainers/1.0.1) fixed this issue, thank you for reporting it.
