### ISSUE TITLE
Missing OS Disk Size on many VMs

### ISSUE THREAD

**Issue by brharr** [Azure/azure-sdk-for-net#3318]
I am creating a Auditing based application where I am gathering information about a customer's IaaS architecture. When I pull the information about the OS Disk, in most cases the DiskSizeinGB property off of the IVirtualMachine.StorageProfile.OSDisk object as well as the IVirtualMachine.OSDiskSize property are returning either 0 or null. However, the values absolutely exist within the portal. 

What is really weird is that is not ever VM. I have two virtual appliances that actually do return OS Disk sizes where as all other VMs that were created do not. I do not feel comfortable releasing this to the customer base without this information. Can someone please help here?

Thanks,
Brian CSA MIcrosoft

**Comment by martinsawicki** [comment]
1. Can you pls check if: `IVirtualMachine.Inner.StorageProfile.OsDisk.DiskSizeGB` is null or 0 as well?  If so, then Azure is not returning this info to the SDK.
2.  When and how were these VMs created?  Or specifically: do they use the Managed disks feature or the old Unmanaged?
3. Which version of the SDK are you using?

**Comment by brharr** [comment]
Martin,


  1.  I did what you suggested and unfortunately the value comes back as null.
  2.  All of these VMs were created within the last month and all of them are using Managed Disks
  3.  As for the SDK, the Fluent version is 1.0.0

One other things to point out is that this is only true for the OS Disk. All of the Data Disks come through with all of the correct information.

Any ideas or thoughts?

Thanks,
Brian

**Comment by martinsawicki** [comment]
The fact you're getting nulls even from they inners indicates Azure is not returning this info in the context your code is calling for it. The fact you're using managed disks is also very relevant.

Now, are these VMs in a *Running* state at the time you're querying them, or some other state?  (Managed disk size would not be available through this API if the VM is not running).

Also, if these are managed disks, then the preferred way to get information about them is actually via the Managed Disks API, not so much the VM (which was originally designed on the service-side for the unmanaged scenario, and there have been service-side issues with getting Managed disk info using that API).

The info you get from the Managed Disks API on the other hand does not depend on the state of the VM. You'd just use the `IVirtualMachine.OSDiskId` to get the ID of the disk resource to query for and then call the Disks API for it. For example:

```csharp
var osDisk = azure.Disks.GetById(virtualMachine.OSDiskId);
```

To see more sample/test code that does something related, see: https://github.com/Azure/azure-sdk-for-net/blob/Fluent/src/ResourceManagement/Azure.Fluent/Fluent.Tests/Compute/VirtualMachineManagedDiskOperationsTests.cs

Pls let me know if this winds up helping.

**Comment by brharr** [comment]
Martin,

First of all, all of the VMs are Stopped to keep my costs down as I develop this application. So that does answer one of the questions. However, your suggestion to just pull the Disk and get the information that way caused a completely new problem. When I run the following command:

var osDisk = azure.Disks.GetById(vm.OSDiskId);

I get the following exception which doesn’t make any sense considering that the resourceGroupName parameter is not a requirement in the function:

Unhandled Exception: Microsoft.Rest.ValidationException: 'resourceGroupName' cannot be null.
   at Microsoft.Azure.Management.Compute.Fluent.DisksOperations.<GetWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.DisksOperationsExtensions.<GetAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.DisksImpl.<GetInnerByGroupAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<GetByResourceGroupAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<GetByIdAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.GetById(String id)
   at AzureIaaSAudit_ConsoleCore.Program.CreateVMEntity(IVirtualMachine vm, Azure azure) in C:\Users\brharr\OneDrive - Microsoft\Development\AzureIaaSAudit-ConsoleCore\Program.cs:line 255
   at AzureIaaSAudit_ConsoleCore.Program.Main(String[] args) in C:\Users\brharr\OneDrive - Microsoft\Development\AzureIaaSAudit-ConsoleCore\Program.cs:line 128

So now I am in an even worse state than I was before.

Thanks,
Brian

**Comment by martinsawicki** [comment]
can you pls say what your vm.OSDiskId actually returns in that case?  (the actual value)

**Comment by martinsawicki** [comment]
(you can replace subscription ID or other confidential parts of the string with X's - i just need to see the format of the ID. The error you're seeing hints at a problem with the structure of that ID. We have a number of tests testing that without issues, so it'd be interesting to understand if there are circumstances that trigger some misbehavior there)

**Comment by brharr** [comment]
So I added in a Console.Writeln statement to my code to get the OSDiskId and apparently it is only failing on a single OS Disk. Here is ID of the one that is causing the Exception:

/subscriptions/XXXXXXXX-XXXX-4b05-b32c-e96edf011ed4/resourceGroups/AzureIaaS-Audit/providers/Microsoft.Compute/disks/vm-linux-non-lb_OsDisk_1_de95028bdbe94fd6b1675f5ca0fdf4ef

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#54
