### ISSUE TITLE
[QUERY] Azure.Storage.Blobs ReleaseLock with RequestConditions not Working

### ISSUE THREAD

**Issue by anime-shed** [Azure/azure-sdk-for-net#33278]
### Library name and version

Azure.Storage.Blobs 12.14.1

### Query/Question

I used  this as a referenceto change my legacy code to v12 library:

![image](https://user-images.githubusercontent.com/67512697/210413156-682f9bda-bbbf-4f15-9586-02b70fd8ce23.png)

## Legacy Code
```
private async Task ReleaseLock(T Id, Guid leaseId)
{
    var blob = _container.GetBlockBlobReference(Id.ToString());
    if (_mutex.WaitOne())
    {
        try
        {
            
                try
                {
                    await blob.ReleaseLeaseAsync(AccessCondition.GenerateLeaseCondition(leaseId));
                }
                catch (Exception ex)
                {
                    await _logger.SendToSlack(ex, $"Error releasing lock - {ex.Message}");
                }
        }
        finally
        {
            _mutex.Set();
        }
    }
}
```
## Azure Storage v12 
```
private async Task ReleaseLock(T Id, Guid leaseId)
{
    var blobClient = _container.GetBlobClient(Id.ToString());
    if (_mutex.WaitOne())
    {
        try
        {
            var blobLeaseClient = entry.BlobClient.GetBlobLeaseClient();
            RequestConditions requestConditions = new RequestConditions();
            requestConditions.IfMatch = new ETag(leaseId);
            var blobLeaseResponse = await blobLeaseClient.ReleaseAsync(requestConditions);
        }
        catch (Exception ex)
        {
            await _logger.SendToSlack(ex, $"Error releasing lock - {ex.Message}");
        }
        finally
        {
            _mutex.Set();
        }
    }
}
```

But this does not work and keep giving me 

```
"Azure.RequestFailedException: The condition specified using HTTP conditional header(s) is not met.
RequestId:db99d634-301e-0061-6677-1fba7e000000
Time:2023-01-03T13:29:16.2805735Z
Status: 412 (The condition specified using HTTP conditional header(s) is not met.)
ErrorCode: ConditionNotMet

Content:
<?xml version="1.0" encoding="utf-8"?><Error><Code>ConditionNotMet</Code><Message>The condition specified using HTTP conditional header(s) is not met.
RequestId:db99d634-301e-0061-6677-1fba7e000000
Time:2023-01-03T13:29:16.2805735Z</Message></Error>

Headers:
Server: Windows-Azure-Blob/1.0,Microsoft-HTTPAPI/2.0
x-ms-request-id: db99d634-301e-0061-6677-1fba7e000000
x-ms-client-request-id: d919940f-fcbe-48ed-af17-decc58f3368a
x-ms-version: 2021-10-04
x-ms-error-code: ConditionNotMet
Date: Tue, 03 Jan 2023 13:29:15 GMT
Content-Length: 252
Content-Type: application/xml

   at Azure.Storage.Blobs.BlobRestClient.RenewLeaseAsync(String leaseId, Nullable`1 timeout, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.RenewInternal(RequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobLeaseClient.RenewAsync(RequestConditions conditions, CancellationToken cancellationToken)"
```

### Environment
```
.NET SDK:
 Version:   7.0.101
 Commit:    bb24aafa11

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.101\

Host:
  Version:      7.0.1
  Architecture: x64
  Commit:       97203d38ba

.NET SDKs installed:
  7.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.32 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```

**Comment by navba-MSFT** [comment]
@anime-shed Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@anime-shed I looked at the backend logs, and seems like the request failed due to the invalid conditional header. Could you please leverage the below .NET **v12** sample code instead and let me know if that works ?

```
using System;
using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Reflection.Metadata;
using System.Text;
using System.Threading.Tasks;
using Azure;
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using Azure.Storage.Blobs.Specialized;

namespace BlobSample
{
    internal class Program
    {
        static async Task Main(string[] args)
        {
            // Replace these values with your own storage account information.
            string storageAccountName = "MyStorageAccountName";
            string storageAccountKey = "MyStorageAccountKey";

            // Create a blob service client.
            BlobServiceClient serviceClient = new BlobServiceClient(
                $"DefaultEndpointsProtocol=https;AccountName={storageAccountName};AccountKey={storageAccountKey}");

            // Get a reference to the container that contains the blob you want to release the lock on.
            BlobContainerClient container = serviceClient.GetBlobContainerClient("MyContainerName");

            // Get a reference to a blob
            BlobClient blobClient = container.GetBlobClient("MyBlobName");

            BlobLeaseClient blobLeaseClient = blobClient.GetBlobLeaseClient();

            BlobLease blobLease = await blobLeaseClient.AcquireAsync(TimeSpan.FromSeconds(60));

            // Set the request condition to include the lease ID.
            BlobUploadOptions blobUploadOptions = new BlobUploadOptions()
            {
                Conditions = new BlobRequestConditions()
                {
                    LeaseId = blobLease.LeaseId
                }
            };

            MemoryStream stream = new MemoryStream(Encoding.ASCII.GetBytes("Hello World"));
            await blobClient.UploadAsync(stream, blobUploadOptions);
            Console.WriteLine("Uploading to Blob storage as blob:\t {0} with Lease ID: {1} \n ", blobClient.Uri, blobLease.LeaseId);
            Console.WriteLine("Click Enter to Release the lease");
            Console.ReadLine();
            try
            {
                await blobLeaseClient.ReleaseAsync();

                Console.WriteLine("Succesfully Released the Lease from the blob", blobClient.Uri);
            }
            catch (RequestFailedException ex)
            {
                Console.WriteLine(ex.Message);   
            }
            Console.ReadLine();
        }
    }
}
```

**Comment by anime-shed** [comment]
Hi @navba-MSFT Thanks for the quick response
I tried something on similar lines
```
private async Task ReleaseLock(T Id, Guid leaseId, ETag etag)
{
    var blobClient = _container.GetBlobClient(Id.ToString());
    if (_mutex.WaitOne())
    {
       try
        {
            var blobLeaseClient = blobClient.GetBlobLeaseClient(leaseId);
            var requestConditions = new BlobRequestConditions() { IfMatch = etag, LeaseId = leaseId };
            var blobLeaseResponse = await blobLeaseClient.ReleaseAsync(requestConditions);
        }
        catch (Exception ex)
        {
            await _logger.SendToSlack(ex, $"Error releasing lock - {ex.Message}");
        }
        finally
        {
            _mutex.Set();
        }
    }
}
```

But, I have some questions:
>  ``var blobLeaseClient = blobClient.GetBlobLeaseClient(leaseId);``
Does it require the `leaseId` or will it automatically get the correct `blobLeaseClient` from the `blobClient`

> ``var requestConditions = new BlobRequestConditions() { IfMatch = etag, LeaseId = leaseId };``
`BlobRequestConditions() { IfMatch = etag}` and `BlobRequestConditions() { LeaseId = leaseId}` will be good enough conditions and only one will suffice.

**Comment by navba-MSFT** [comment]
@anime-shed Sending the below details, Please see the **x-ms-lease-action** and **x-ms-lease-id** for each of the function call. In my sample code, I didn't pass the lease ID for the GetBlobLeaseClient( ) function call. You can see that in my below [successful repro](https://github.com/Azure/azure-sdk-for-net/issues/33278#issuecomment-1370531101), the same lease id was used for **Acquire** and **Release**.

> **BlobLease blobLease = await blobLeaseClient.AcquireAsync(TimeSpan.FromSeconds(60));**

PUT https://MyStorageAccount.blob.core.windows.net/test/source.txt?comp=lease HTTP/1.1
**_x-ms-lease-action: acquire_**
x-ms-lease-duration: 60
**_x-ms-proposed-lease-id: 3bf369d4-093c-424e-b75d-ca2f7977076b_**
x-ms-version: 2021-10-04
Accept: application/xml
x-ms-client-request-id: 8a9a39d0-7612-46cc-8c05-977c084ec579
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.14.1 (.NET 7.0.1; Microsoft Windows 10.0.22621)
x-ms-date: Thu, 05 Jan 2023 06:23:56 GMT
Authorization: SharedKey MyStorageAccount:Xf42gmxTU6qbbsZxS/zoCvZCObxiaoaqYOR0vUn/QAE=
Content-Length: 0



**_>   var blobLeaseResponse = await blobLeaseClient.ReleaseAsync();_**
    
PUT https://MyStorageAccount.blob.core.windows.net/test/source.txt?comp=lease HTTP/1.1
**_x-ms-lease-action: release
x-ms-lease-id: 3bf369d4-093c-424e-b75d-ca2f7977076b_**
x-ms-version: 2021-10-04
Accept: application/xml
x-ms-client-request-id: b8b516c8-37aa-4bc7-830f-75dbd6a57b2b
x-ms-return-client-request-id: true
User-Agent: azsdk-net-Storage.Blobs/12.14.1 (.NET 7.0.1; Microsoft Windows 10.0.22621)
x-ms-date: Thu, 05 Jan 2023 06:24:30 GMT
Authorization: SharedKey MyStorageAccount:4zxzZCjHbr9gLrAoDmxsoAeeTN7TY+8YdRdsP5P2p+U=
Content-Length: 0


Also is there a specific reason why you are using both Etag and Lease together ? If your intention is to achieve the concurrency,  then either use Etag for [Optimistic concurrency](https://learn.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet#optimistic-concurrency) or Lease for[Pessimistic concurrency](https://learn.microsoft.com/en-us/azure/storage/blobs/concurrency-manage?tabs=dotnet#pessimistic-concurrency-for-blobs).

**Comment by anime-shed** [comment]
Thank you, Will close this now since I have no more doubts for now and I see where I may have miss understood some things.
