### ISSUE TITLE
Azure storage blob trigger unhandled exception causing the host to crash

### ISSUE THREAD

**Issue by rarayudu** [Azure/azure-sdk-for-net#33344]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Storage Version 5.X.X

### Describe the bug

An unhandled exception because of authentication issues in the Azure Storage Blob trigger is causing the entire host to crash. This causing issues as other valid functions in the same application are not executing as the host is continuously crashing. Azure Service Bus extension handles this well and does not make the entire host to crash.

The background listener for the blob trigger function is raising a host level unhandled exception because it can’t communicate with storage to scan for blob updates.

Exception Details:

   at async Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegmentAsync(String prefix,String marker,Nullable`1 maxresults,IEnumerable`1 include,Nullable`1 timeout,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker,BlobTraits traits,BlobStates states,String prefix,Nullable`1 pageSizeHint,Boolean async,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken,Nullable`1 pageSizeHint,Boolean async,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at async Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.AsPages[T](String continuationToken,Nullable`1 pageHintSize)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at async Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.AsPages[T](String continuationToken,Nullable`1 pageHintSize)
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy.PollNewBlobsAsync(BlobContainerClient container,ContainerScanInfo containerScanInfo,String clientRequestId,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy.PollAndNotify(BlobContainerClient container,ContainerScanInfo containerScanInfo,List`1 failedNotifications,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Blobs.Listeners.ScanBlobScanLogHybridPollingStrategy.ExecuteAsync(CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at async Microsoft.Azure.WebJobs.Extensions.Storage.Common.Timers.TaskSeriesTimer.RunAsync(CancellationToken cancellationToken)

### Expected behavior

Host shouldn't crash for these exceptions and should allow the host to start to execute other valid triggers if any.

### Actual behavior

Host crashes and continuously recycling when using Azure Blob trigger with an Unauthorized connection string

### Reproduction Steps

Create an Azure Storage Blob trigger with an Unauthorized connection string

**Comment by navba-MSFT** [comment]
@rarayudu Thanks for reaching out to us and reporting this issue. We are looking into this issue and we will provide an update.

**Comment by navba-MSFT** [comment]
@rarayudu I am unable to reproduce this issue at my end by following your above mentioned steps. While I used the `unauthorized` connection string in my sample code, I get the **expected** error message as shown below:

> **[2023-01-10T13:23:57.886Z] The 'Function1' function is in error: Microsoft.Azure.WebJobs.Host: Error indexing method 'Function1'. Microsoft.Azure.WebJobs.Extensions.Storage: Storage account connection string for 'AzureWebJobsStorage' is invalid.**
