### ISSUE TITLE
Some Azure.Monitor.OpenTelemetry.Exporter tests fail under net7.0

### ISSUE THREAD

**Issue by heaths** [Azure/azure-sdk-for-net#33403]
When testing #32814 I found a few tests for `Azure.Monitor.OpenTelemetry.Exporter` are failing only under net7.0 with an error like:

> *Error message*
>
> System.FormatException : The format of value '' is invalid.
>
> *Stack trace*
>
>    at System.Net.Http.Headers.HttpHeaderParser.ParseValue(String value, Object storeValue, Int32& index)
   at System.Net.Http.Headers.HttpHeaders.ParseAndAddValue(HeaderDescriptor descriptor, HeaderStoreItemInfo info, String value)
   at System.Net.Http.Headers.HttpHeaders.Add(HeaderDescriptor descriptor, String value)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.CookieContainerHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Testing.Handlers.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Azure.Monitor.OpenTelemetry.Exporter.Integration.Tests.RequestTelemetryTests.VerifyRequestTelemetry() in /mnt/vss/_work/1/s/sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/tests/Integration.Tests/RequestTelemetryTests.cs:line 58
--- End of stack trace from previous location ---

From similar reports on GitHub, this most often seems to be a case where code assumed some value it's adding to headers was non-empty, and the fix has been to make sure the value to add (perhaps part of a header value collection) isn't empty. However, during initial investigation I found no code in _sdk/monitor/Azure.Monitor.OpenTelemetry.Exporter/src_ that could convevably add an empty header name or value, nor anything in the related _tests_ folder. I fear this may be some middleware that hopefully just needs to be updated.

**Comment by TimothyMothra** [comment]
@heaths you mentioned a few tests, but only quoted the one "VerifyRequestTelemetry".
I understand you've been working on the net7 support for a while now. I'm okay with disabling our failing tests to unblock your effort.

CC @rajkumar-rangaraj

**Comment by heaths** [comment]
Tests include:

* Azure.Monitor.OpenTelemetry.Exporter.Integration.Tests.BasicTests.VerifyRequest
* Azure.Monitor.OpenTelemetry.Exporter.Integration.Tests.RequestTelemetryTests.VerifyRequestTelemetry

**Comment by TimothyMothra** [comment]
These are the integration tests; the unit test invokes a request to a web app and verify that a valid RequestTelemetry is generated.

These tests are failing because the request fails to invoke. Tests fail on this line: `var response = await client.GetAsync(request);`.

This affects net7 only, and the fix is to update the dependency:
```
  <ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" VersionOverride="7.0.0" />
  </ItemGroup>
```

I want to avoid conflicts, so I'll wait for Heath's PR to merge and then I'll submit a PR with the fix. :)

**Comment by heaths** [comment]
I plan to merge EOW this week or early next week after our normal shipping cycle.

**Comment by heaths** [comment]
Please be sure to remove the `Skip` where I ignored those two tests.

**Comment by heaths** [comment]
@TimothyMothra my PR to build tests for `net7.0;net6.0[;net461]` is now merged.
