### ISSUE TITLE
[BUG] unable to batch delete a blob with Chinese characters in the name

### ISSUE THREAD

**Issue by blushingpenguin** [Azure/azure-sdk-for-net#33444]
### Library name and version

Azure.Storage.Blobs.Batch 12.11.0

### Describe the bug

Unable to batch delete a blob with Chinese characters in the name where the name is returned by GetBlobs

### Expected behavior

Should be able to delete the blob

### Actual behavior

Status: 400 (The request URI is invalid.)
ErrorCode: InvalidUri

is returned

### Reproduction Steps

Create a blob storage service and obtain an authenticated BlobServiceClient (the first line does this for me). Then run the code below which will create a blob, list the blob, then delete the listed blob using the batch API. This fails, but deleting the listed blob using DeleteBlob succeeds

```c#
private async Task BadNameTest()
{
    var blobServiceClient = _blobServiceClientFactory.Create(_fileUploadStorageUrl);
    var blobContainerClient = blobServiceClient.GetBlobContainerClient("upload");
    var badName = "サービスガイド（奉行クラウド／奉行クラウドEdge共通）.pdf";
    await blobContainerClient.UploadBlobAsync(badName, new MemoryStream(new byte[] { 1, 2, 3 }));
    var batchClient = new BlobBatchClient(blobServiceClient);
    var urls = new List<Uri>();
    await foreach (var page in blobContainerClient.GetBlobsAsync(prefix: badName).AsPages())
    {
        foreach (var blob in page.Values)
        {
            var blobClient = blobContainerClient.GetBlobClient(blob.Name);
            urls.Add(blobClient.Uri);
            Console.WriteLine(blobClient.Uri);
        }
    }
    try
    {
        await batchClient.DeleteBlobsAsync(urls);
    }
    catch (Exception e)
    {
        Console.WriteLine(e);
    }
    await blobContainerClient.DeleteBlobAsync(badName);
}
```

result:

```
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidUri</Code><Message>The request URI is invalid.
RequestId:7d5544f9-701e-0043-5e51-26981d1e9172
Time:2023-01-12T06:43:30.2840237Z</Message></Error>

Headers:
x-ms-request-id: 7d5544f9-701e-0043-5e51-26981d1e9172
Content-Length: 207
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
)
 ---> Azure.RequestFailedException: The request URI is invalid.
RequestId:7d5544f9-701e-0043-5e51-26981d1e9172
Time:2023-01-12T06:43:30.2840237Z
Status: 400 (The request URI is invalid.)
ErrorCode: InvalidUri

Content:
<?xml version="1.0" encoding="utf-8"?>
<Error><Code>InvalidUri</Code><Message>The request URI is invalid.
RequestId:7d5544f9-701e-0043-5e51-26981d1e9172
Time:2023-01-12T06:43:30.2840237Z</Message></Error>

Headers:
x-ms-request-id: 7d5544f9-701e-0043-5e51-26981d1e9172
Content-Length: 207
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0

   at Azure.Storage.Blobs.Specialized.BlobBatch.<DeleteBlob>b__23_0(Response response)
   at Azure.Storage.Blobs.Specialized.DelayedResponse.SetLiveResponse(Response live, Boolean throwOnFailure)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(IList`1 messages, Response rawResponse, Stream responseContent, String responseContentType, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(IList`1 messages, Response rawResponse, Stream responseContent, String responseContentType, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.SubmitBatchInternal(BlobBatch batch, Boolean throwOnAnyFailure, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.DeleteBlobsInteral(IEnumerable`1 blobUris, DeleteSnapshotsOption snapshotsOption, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.DeleteBlobsAsync(IEnumerable`1 blobUris, DeleteSnapshotsOption snapshotsOption, CancellationToken cancellationToken)
```

### Environment

```
.NET SDK (reflecting any global.json):
 Version:   6.0.404
 Commit:    be4f3ec411

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.404/

global.json file:
  Not found

Host:
  Version:      6.0.13
  Architecture: x64
  Commit:       1af80ba017
```

**Comment by navba-MSFT** [comment]
@blushingpenguin Thanks for reaching out to us and reporting this issue. I was able to repro this issue at my end using your sample code. 
I looked at the backend logs and seems like the failure was due to the URL containing an Unicode Ascii restricted Character. I So I renamed your file and this worked for me. This is the blob name I used: `サービスガイド（奉行クラウ行クラウドEdge共通）.pdf`

More Info [here](https://learn.microsoft.com/en-us/rest/api/storageservices/naming-and-referencing-containers--blobs--and-metadata). 
```
A blob name must conform to the following naming rules:

- A blob name can contain any combination of characters.
- A blob name must be at least one character long and cannot be more than 1,024 characters long, for blobs in Azure Storage.
- The Azure Storage emulator supports blob names up to 256 characters long. For more information, see [Use the Azure storage emulator for development and testing](https://learn.microsoft.com/en-us/azure/storage/common/storage-use-emulator).
- Blob names are case-sensitive.
- Reserved URL characters must be properly escaped.
- The number of path segments comprising the blob name cannot exceed 254. A path segment is the string between consecutive delimiter characters (e.g., the forward slash '/') that corresponds to the name of a virtual directory.

```

**Comment by blushingpenguin** [comment]
@navba-MSFT why is this tagged needs-author-feedback? It's either a bug that the blob gets created in the first place by the normal (not batch API), or it's a bug that it can't be deleted by the batch api, or it's a bug in the documentation about what is allowed. 
This problem also occurs for blob names with empty segments, something else which according to the documentation linked above is "not allowed" (but can be done).

**Comment by navba-MSFT** [comment]
@blushingpenguin Thanks for getting back. I am discussing this internally with the Storage SDK Devs. I will get back to you with an update.

**Comment by amnguye** [comment]
Looks like there's a problem in the SDK with how the blob name is being added to the Batch of blobs to delete. I'm assuming what's happening is that the name isn't getting encoding however I just want to confirm that if we encode the blob name that that would resolve the issue.

Have you tried encoding the blob name before calling BlobBatch.DeleteBlob(<blob uri>) ?

I will update when I have narrowed down what needs to be done and where the right place is to encode the blob name in the blob batch request.

**Comment by blushingpenguin** [comment]
@amnguye I'm happy to try that, but how should it be encoded? (If you want to try it yourself, there is code to reproduce the problem at the top of the issue, you just need to supply an authentication BlobServiceClient).
