### ISSUE TITLE
[BUG] Cannot retrieve Operational Insights Workspaces in `East US`

### ISSUE THREAD

**Issue by droyad** [Azure/azure-sdk-for-net#33536]
### Library name and version

Azure.ResourceManager.OperationalInsights 1.0.0

### Describe the bug

In some regions (e.g. `East US`) retrieving Operational Insights Workspaces throws:

```
System.FormatException: One of the identified items was in an invalid format.
   at System.Text.Json.ThrowHelper.ThrowFormatException()
   at System.Text.Json.JsonElement.GetDateTimeOffset()
   at Azure.ResourceManager.OperationalInsights.Models.OperationalInsightsWorkspaceSku.DeserializeOperationalInsightsWorkspaceSku(JsonElement element)
   at Azure.ResourceManager.OperationalInsights.OperationalInsightsWorkspaceData.DeserializeOperationalInsightsWorkspaceData(JsonElement element)
   at Azure.ResourceManager.OperationalInsights.WorkspacesRestOperations.GetAsync(String subscriptionId, String resourceGroupName, String workspaceName, CancellationToken cancellationToken)
   at Azure.ResourceManager.OperationalInsights.OperationalInsightsWorkspaceCollection.GetAsync(String workspaceName, CancellationToken cancellationToken)
   at Azure.ResourceManager.OperationalInsights.OperationalInsightsExtensions.GetOperationalInsightsWorkspaceAsync(ResourceGroupResource resourceGroupResource, String workspaceName, CancellationToken cancellationToken)
 ```
 
 However in `Australia East` it works fine.

I've traced the code and it looks like it the API returns:
```
{ "name": "pergb2018", "lastSkuUpdate": "Tue, 17 Jan 2023 06:33:30 GMT"    }
```

Which can't be parsed as it expects an ISO formatted date

### Expected behavior

The date is parsed correctly and the workspace is retrieved

### Actual behavior

An exception is thrown

### Reproduction Steps

```
var client = new ArmClient(new DefaultAzureCredential());
var subscription = client.GetSubscriptionResource(SubscriptionResource.CreateResourceIdentifier(subscriptionId));
var resourceGroup = subscription.GetResourceGroups().CreateOrUpdate(WaitUntil.Completed, "repro", new ResourceGroupData("East US"));
var workspace = resourceGroup.Value.GetOperationalInsightsWorkspaces().CreateOrUpdate(WaitUntil.Completed, "repro", new OperationalInsightsWorkspaceData("East US"));

resourceGroup.Value.GetOperationalInsightsWorkspace("repro");
```

**Comment by droyad** [comment]
I ran it against all the regions, and it's only `US East`:

```
East US Failed
East US 2 Success
South Central US Success
West US 2 Success
West US 3 Success
Australia East Success
Southeast Asia Success
North Europe Success
Sweden Central Success
UK South Success
West Europe Success
Central US Success
South Africa North Success
Central India Success
East Asia Success
Japan East Success
Korea Central Success
Canada Central Success
France Central Success
Germany West Central Success
Norway East Success
Switzerland North Success
UAE North Success
Brazil South Success
```

**Comment by fengzhou-msft** [comment]
@sameergMS @dadunl please help check if there is a disrepancy in the datetime format of the `lastSkuUpdate` property of `WorkspaceSku` between the `East US` location and others. The .NET SDK assumes that they all follow `ISO 8601 format`.

**Comment by waldyhester** [comment]
### Look at these requests and see that the datetime props are of different standards, this only happens in the region EASTUS


**Request to eastus**
https://management.azure.com/subscriptions/{HIDE}/resourcegroups/{HIDE}/providers/Microsoft.OperationalInsights/workspaces/{HIDE}?api-version=2022-10-01

**Response body**
```
{
  "properties": {
    "source": "Azure",
    "customerId": "{HIDE}",
    "provisioningState": "Succeeded",
    "sku": {
      "name": "pergb2018",
      "lastSkuUpdate": "Tue, 31 Jan 2023 14:29:38 GMT"
    },
    "retentionInDays": 30,
    "features": {
      "legacy": 0,
      "searchVersion": 1,
      "enableLogAccessUsingOnlyResourcePermissions": true
    },
    "workspaceCapping": {
      "dailyQuotaGb": -1,
      "quotaNextResetTime": "Wed, 01 Feb 2023 08:00:00 GMT",
      "dataIngestionStatus": "RespectQuota"
    },
    "publicNetworkAccessForIngestion": "Enabled",
    "publicNetworkAccessForQuery": "Enabled",
    "createdDate": "Tue, 31 Jan 2023 14:29:38 GMT",
    "modifiedDate": "Tue, 31 Jan 2023 14:32:11 GMT"
  },
  "id": "/subscriptions/{HIDE}/resourcegroups/rg-monitoring/providers/microsoft.operationalinsights/workspaces/{HIDE}",
  "name": "DefaultWorkspaceName",
  "type": "Microsoft.OperationalInsights/workspaces",
  "location": "eastus",
  "tags": {}
}
```

**Request to eastus2**
https://management.azure.com/subscriptions/{HIDE}/resourcegroups/{HIDE}/providers/Microsoft.OperationalInsights/workspaces/{HIDE}?api-version=2022-10-01

**Response body**
```
{
  "properties": {
    "customerId": "14fc6ea8-c94a-481c-b94c-cc34b5ef14e5",
    "provisioningState": "Succeeded",
    "sku": {
      "name": "PerGB2018",
      "lastSkuUpdate": "2023-01-31T15:01:27.5666098Z"
    },
    "retentionInDays": 30,
    "features": {
      "legacy": 0,
      "searchVersion": 1,
      "enableLogAccessUsingOnlyResourcePermissions": true
    },
    "workspaceCapping": {
      "dailyQuotaGb": -1,
      "quotaNextResetTime": "2023-01-31T20:00:00Z",
      "dataIngestionStatus": "RespectQuota"
    },
    "publicNetworkAccessForIngestion": "Enabled",
    "publicNetworkAccessForQuery": "Enabled",
    "createdDate": "2023-01-31T15:01:27.5666098Z",
    "modifiedDate": "2023-01-31T15:01:27.5666098Z"
  },
  "location": "eastus2",
  "tags": {},
  "id": "/subscriptions/a9c45a84-03e2-414d-b570-3600c814a622/resourceGroups/RG-Monitoring/providers/Microsoft.OperationalInsights/workspaces/DefaultWorkspaceOpIn02",
  "name": "DefaultWorkspaceOpIn02",
  "type": "Microsoft.OperationalInsights/workspaces"
}
```
