### ISSUE TITLE
[BUG] OperationalInsightsExtensions.GetOperationalInsightsWorkspaces throws an exception

### ISSUE THREAD

**Issue by Avisharper** [Azure/azure-sdk-for-net#33571]
### Library name and version

Azure.ResourceManager.OperationalInsights 1.0.0

### Describe the bug

When getting workspaces there is a System.FormatException: 'One of the identified items was in an invalid format.'
This is from deserializing DateTimeOffset.
See similar [issue](https://github.com/Azure/azure-sdk-for-net/issues/31011) in a different package
Might be worth checking other packages as well.

Call stack (See code in repro section)

   at System.Text.Json.ThrowHelper.ThrowFormatException()
   at System.Text.Json.JsonElement.GetDateTimeOffset()
   at Azure.ResourceManager.OperationalInsights.Models.OperationalInsightsWorkspaceSku.DeserializeOperationalInsightsWorkspaceSku(JsonElement element)
   at Azure.ResourceManager.OperationalInsights.OperationalInsightsWorkspaceData.DeserializeOperationalInsightsWorkspaceData(JsonElement element)
   at Azure.ResourceManager.OperationalInsights.Models.WorkspaceListResult.DeserializeWorkspaceListResult(JsonElement element)
   at Azure.ResourceManager.OperationalInsights.WorkspacesRestOperations.List(String subscriptionId, CancellationToken cancellationToken)
   at Azure.ResourceManager.OperationalInsights.SubscriptionResourceExtensionClient.<>c__DisplayClass32_0.<GetOperationalInsightsWorkspaces>g__FirstPageFunc|0(Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.<>c__DisplayClass5_0`1.<CreateEnumerable>b__0(String continuationToken, Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.FuncPageable`1.<AsPages>d__4.MoveNext()
   at Azure.Pageable`1.<GetEnumerator>d__8.MoveNext()

### Expected behavior

No exceptions.
Get the collection of workspaces

### Actual behavior

FormatException

### Reproduction Steps

```
const string subscriptionId = "<subscription id>";
TokenCredential tokenCredential = new DefaultAzureCredential();
var armClient = new ArmClient(tokenCredential, subscriptionId);
var sub = armClient.GetSubscriptionResource(SubscriptionResource.CreateResourceIdentifier(subscriptionId));
var res = await sub.GetAsync(); // Not required
sub = res.Value; // Not required
await foreach (var ws in sub.GetOperationalInsightsWorkspacesAsync(CancellationToken.None))
{
    Console.WriteLine(ws);
}
```

### Environment

SDK Version: 7.0.102
Visual Studio 2022 Version 17.4.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by fengzhou-msft** [comment]
@Avisharper this issue seems similar to #33536. Did you also use the `East US` location?

**Comment by Avisharper** [comment]
@fengzhou-msft - Yes it is similar, though the call is to get all workspaces for a subscription and we have workspaces in multiple regions including East US 2, East US 2 Euap
