### ISSUE TITLE
Problem while creating a VM

### ISSUE THREAD

**Issue by lowleveldesign** [Azure/azure-sdk-for-net#3359]
I try to create a new Linux in an existing VNet (`virtualMachineVnet`) using the Fluent API and I receive the "CloudException: Cannot parse the request" exception. The code for creating the machine looks as follows:

```csharp
var baseName = Guid.NewGuid().ToString("n");
jumpBoxName = baseName + "-vm";

jumpBox = await azure.VirtualMachines.Define(jumpBoxName)
                     .WithRegion(virtualMachineVnet.RegionName)
                     .WithExistingResourceGroup(resourceGroupName)
                     .WithExistingPrimaryNetwork(virtualMachineVnet)
                     .WithSubnet(virtualMachineSubnet.Name)
                     .WithPrimaryPrivateIPAddressDynamic()
                     .WithNewPrimaryPublicIPAddress(
                          azure.PublicIPAddresses.Define(baseName + "-ip")
                                .WithRegion(virtualMachineVnet.RegionName)
                                .WithExistingResourceGroup(resourceGroupName)
                                .WithDynamicIP()
                                .WithLeafDomainLabel("ip-" + baseName)
                      )
                     .WithPopularLinuxImage(KnownLinuxVirtualMachineImage.UbuntuServer14_04_Lts)
                     .WithRootUsername(rootUsername)
                     .WithSsh(sshPublicKey)
                     .WithSize(VirtualMachineSizeTypes.StandardA0)
                     .CreateAsync(cancellationToken);
```
The exception: 
```
Microsoft.Rest.Azure.CloudException: Cannot parse the request.
   at Microsoft.Azure.Management.Network.Fluent.NetworkInterfacesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Network.Fluent.NetworkInterfacesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Network.Fluent.NetworkInterfacesOperationsExtensions.<CreateOrUpdateAsync>d__5.MoveNext()
...
{stripped}
```
I traced the requests in BurpSuite and noticed that the failing request has the following body (dotted unimportant parts):
```json
{
  "properties": {
    "ipConfigurations": [
      {
        "properties": {
          "privateIPAllocationMethod": "Dynamic",
          "subnet": {
            "id": "/subscriptions/.../resourceGroups/azrdp/providers/Microsoft.Network/virtualNetworks/azrdp-vnet/subnets/default"
          },
          "publicIPAddress": {
            "properties": {
              "publicIPAllocationMethod": "Dynamic",
              "publicIPAddressVersion": "IPv4",
              "dnsSettings": {
                "domainNameLabel": "ip-ac220a2fca0645f4bc86308ef0aa5320",
                "fqdn": "ip-ac220a2fca0645f4bc86308ef0aa5320.westeurope.cloudapp.azure.com"
              },
              "idleTimeoutInMinutes": 4,
              "resourceGuid": "...",
              "provisioningState": "Succeeded"
            },
            "etag": "W/\"...\"",
            "location": "westeurope",
            "tags": {}
          }
        },
        "name": "primary"
      }
    ],
    "dnsSettings": {}
  },
  "location": "westeurope",
  "tags": {}
}
```
and the response was:
```json
HTTP/1.1 400 Bad Request
...
{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": [
      {
        "code": "MissingJsonReferenceId",
        "message": "Value for reference id is missing. Path properties.ipConfigurations[0].properties.publicIPAddress."
      }
    ]
  }
}
```
Thanks for checking this out.

**Comment by hovsepm** [comment]
@lowleveldesign are you using v1.1?

**Comment by lowleveldesign** [comment]
Sorry for not specifying this. I am using the version from the Nuget package 1.1.0. Strangely, the assembly full name is: **Microsoft.Azure.Management.Fluent, Version=1.0.0.60, Culture=neutral, PublicKeyToken=31bf3856ad364e35**, but the file and product version is **1.1.0.0**.

The project source code is on github: https://github.com/lowleveldesign/azrdp. The assemblies are in the binaries folder in the azrdp project (I know I know, but I had a reason to do that). I'm using VS2015.

**Comment by hovsepm** [comment]
fix published to nuget. Please upgrade to version 1.1.1.

**Comment by lowleveldesign** [comment]
Thank you for the fix, but it seems that it is not present in the 1.1.1 version of the assemblies (my problem persists). Also, I checked the latest version of the [NetworkInterfaceIPConfigurationInner.cs](https://github.com/Azure/azure-sdk-for-net/blob/Fluent/src/ResourceManagement/Network/Microsoft.Azure.Management.Network.Fluent/Generated/Models/NetworkInterfaceIPConfigurationInner.cs) and it does not contain the fix (PublicIPAddress property is still the SubResource and should be [PublicAddressInner](https://github.com/Azure/azure-sdk-for-net/commit/830596d1caeb783f4e364de723322e274b5cb250#diff-6a1676902fea6e50a284c30f65139070)). Maybe I am missing something, but it seems that the merge did not land in the Fluent branch.
