### ISSUE TITLE
[BUG] System.InvalidOperationException: '' is not a valid value for a partition key or row key thrown when using Extensions.Table package with Azure functions output binding

### ISSUE THREAD

**Issue by kshyju** [Azure/azure-sdk-for-net#33902]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.Table 1.0.0

### Describe the bug

When using this package in the azure functions context to save data to the table using function's output bindings, an invalid operation [exception is thrown ](https://github.com/Azure/azure-sdk-for-net/blob/f79888a2068d2abc7aa0997b0599250d0bf55db6/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/src/TableClientHelpers.cs#L82)with below stack trace (trimmed to keep it only the relevant stack from this package).

> System.InvalidOperationException: '' is not a valid value for a partition key or row key.
         at Microsoft.Azure.WebJobs.Extensions.Tables.TableClientHelpers.ValidateAzureTableKeyValue(String value) in C:\Dev\OSS\azure-sdk-for-net\sdk\tables\Microsoft.Azure.WebJobs.Extensions.Tables\src\TableClientHelpers.cs:line 86
         at Microsoft.Azure.WebJobs.Extensions.Tables.TableEntityWriter.AddAsync(TableEntity item, CancellationToken cancellationToken) in C:\Dev\OSS\azure-sdk-for-net\sdk\tables\Microsoft.Azure.WebJobs.Extensions.Tables\src\TableEntityWriter.cs:line 58
         at Microsoft.Azure.WebJobs.Host.Bindings.TypedAsyncCollectorAdapter`3.AddAsync(TSrc item, CancellationToken cancellationToken) in C:\projects\azure-webjobs-sdk-rqm4t\src\Microsoft.Azure.WebJobs.Host\Bindings\AsyncCollector\TypedAsyncCollectorAdapter.cs:line 40
         at Microsoft.Azure.WebJobs.Script.Binding.FunctionBinding.BindAsyncCollectorAsync[T](BindingContext context) in C:\Dev\OSS\azure-functions-host\src\WebJobs.Script\Binding\FunctionBinding.cs:line 199

I did a bit of debugging and found the following.

1. TableEntityWriter.AddAsync is called with an instance of TableEntity and the PartitiionKey property was read and passed to ` TableClientHelpers.ValidateAzureTableKeyValue`. The exception is thrown from that method since the value passed is `null`.

![image](https://user-images.githubusercontent.com/144469/216867597-0881b2a4-3b33-4607-aa0b-c73c356ad805.png)

2. [PocoTableEntityConverter.Convert](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.DataProtectionBackup_1.1.0/sdk/tables/Microsoft.Azure.WebJobs.Extensions.Tables/src/PocoToTableEntityConverter.cs#L29) method is responsible for creating this tableEntity instance from the payload data passed (from functions code). The input passed to the Convert method is a byte array representation of the JSON string. I dropped a custom version of the dll with some debugging code added(_forked from Azure.ResourceManager.DataProtectionBackup_1.1.0 tag_) to confirm the byte array is valid (was able to convert back to same JSON string).  See below screenshot.

![image](https://user-images.githubusercontent.com/144469/216866665-c2380242-51bb-4c78-9348-56c2bde14598.png)

So looks like something wrong going on within the Serialize method call where it fails to set this properties?

### Expected behavior

The data should be saved to the Table storage without any exception.

### Actual behavior

An exception is thrown because the `PartitionKey` propery is not populated in the `TableEntity` instnace.

### Reproduction Steps

Create a dotnet 7 isolated azure function with an http trigger and add TableStorage output binding to write to a storage table. Below is the relevant http trigger from my repro.

```
[Function("Function1")]
[TableOutput("MemberInventory", Connection = "MyStorageConnStr")]
public async Task<MemberInventorySave> Run([HttpTrigger(AuthorizationLevel.Anonymous, "get", "post")] HttpRequestData req)
{
    return new MemberInventorySave
    {
        PartitionKey = "foo",
        RowKey = Guid.NewGuid().ToString(),
        YearlySetupId = "bar",
        TenantId = Guid.NewGuid(),
    };
}
```
Create the MemberInventorySave POCO with the above properties.  
Run the function, execute http trigger and you should see the exception.

Package references used in the isolated function app.
```
<PackageReference Include="Microsoft.Azure.Functions.Worker" Version="1.10.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Http" Version="3.0.13" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Extensions.Tables" Version="1.0.0" />
<PackageReference Include="Microsoft.Azure.Functions.Worker.Sdk" Version="1.7.0" />
```

### Environment

Locally reproes in Win11. VS 17.4.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by nusliew** [comment]
I also encountered the same issue from **Java** Function App with outputbinding to Azure Tables.
![image](https://user-images.githubusercontent.com/15899755/219853006-cd5261af-7311-45a4-8481-e3cc2bf12a4b.png)
![image](https://user-images.githubusercontent.com/15899755/219853066-d8d55868-12d2-4f19-a634-94a2185ccb23.png)

Before output value to Azure Tables, I make sure the value: p has valid value and print to logs, but it still occurred below error.
>> person.setValue(p);

Microsoft.Azure.WebJobs.Host.FunctionInvocationException : Exception while executing function: Functions.HttpTriggerJava1 ---> System.InvalidOperationException : **'' is not a valid value for a partition key or row key.**
   at Microsoft.Azure.WebJobs.Extensions.Tables.TableClientHelpers.ValidateAzureTableKeyValue(String value)
   at async Microsoft.Azure.WebJobs.Extensions.Tables.TableEntityWriter.AddAsync(TableEntity item,CancellationToken cancellationToken)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

===
**General information**
Java Function App (Windows / P1V2) with an http trigger and add TableStorage output binding to write to a storage table.
Language: Java 8
===
**Extension package:**
Loaded extension 'AzureTables' (1.0.0.0)
===
**Host.json**
{
  "version": "2.0",
  "extensionBundle": {
    "id": "Microsoft.Azure.Functions.ExtensionBundle",
    "version": "[3.*, 4.0.0)"
  } 
}
====
**Java Function App sample code:**
@FunctionName("HttpTriggerJava1")
    public HttpResponseMessage run(
            @HttpTrigger(name = "req", methods = {HttpMethod.GET, HttpMethod.POST}, authLevel = AuthorizationLevel.FUNCTION) HttpRequestMessage<Optional<String>> request,
            @TableOutput(name="person", tableName="JamesTablesTest", connection="StorageTableConnection") OutputBinding<Person> person,
            final ExecutionContext context) {
        context.getLogger().info("Java HTTP trigger processed a request.");

        // Parse query parameter
        String query = request.getQueryParameters().get("name");
        String name = request.getBody().orElse(query);


        String httpbody = request.getQueryParameters().get("name");
        Person p = new Person(httpbody + "Partition", httpbody + "Row", httpbody + "Name");
        context.getLogger().info("Name: " + p.Name);
        context.getLogger().info("PartitionKey: " + p.PartitionKey);
        context.getLogger().info("RowKey: " + p.RowKey);
        person.setValue(p);

        if (name == null) {
            return request.createResponseBuilder(HttpStatus.BAD_REQUEST).body("Please pass a name on the query string or in the request body").build();
        } else {
            return request.createResponseBuilder(HttpStatus.OK).body("Hello, " + name).build();
        }
        
    }


    public static class Person {
        public String PartitionKey;
        public String RowKey;
        public String Name;

        public Person(String p, String r, String n) {
            this.PartitionKey = p;
            this.RowKey = r;
            this.Name = n;
        }
    }
===

**[ASK]**
What reason cause this issue? Is there any workaround to mitigate it? Thanks for your help!

**Comment by skrim** [comment]
I encountered this issue also and this might assist in the right direction. I noticed that if I add `RowKey` and `PartitionKey` to the `TableOutputAttribute`, like this ...

```csharp
[TableOutput(nameof(Scene), "asd", "asd")]
```

...a row appears in the table storage with the example keys, but it contains the following fields:

`PartitionKey`, `RowKey`, `Timestamp`, `Length`, `LongLength`, `Rank`, `SyncRoot`, `IsReadOnly`, `IsFixedSize`, `IsSynchronized` (looks like an `Array` derivative).

And interestingly, `SyncRoot` contains the data object I originally tried to save as JSON in a Base64 encoded string.

**Comment by JoshLove-msft** [comment]
It appears that the issue is that when using the isolated worker extension, the output content always comes in as a byte array. The extension then treats the byte array as if it defined a POCO model, which explains the behavior @skrim reported. I'm inclined to think that there is no valid use case for outputting a byte array, whether using in process or out of process. So perhaps we could always treat a byte array as UTF-8 JSON bytes. @christothes any thoughts on whether there is some other usage for outputting a byte array to a Table?

**Comment by JoshLove-msft** [comment]
My understanding is that the ability to manipulate the output payload in an out-of-process extension is not yet supported, which would be a prerequisite to making the Tables output attribute work without losing data in the form of type information. 
/cc @fabiocav @liliankasem in case I am missing a way to enable this now.

**Comment by JoshLove-msft** [comment]
Chatted with @fabiocav and he recommended we investigate using Middleware in the isolated worker to mutate the payload as needed. So in order to fix this issue we will need changes in both the host extension and the isolated worker extension.

**Comment by mikem-MS** [comment]
> I encountered this issue also and this might assist to the right direction. I noticed that if I add `RowKey` and `PartitionKey` to the `TableOutputAttribute`, like this ...
> 
> ```cs
> [TableOutput(nameof(Scene), "asd", "asd")]
> ```
> 
> ...a row appears in the table storage with the example keys, but it contains the following fields:
> 
> `PartitionKey`, `RowKey`, `Timestamp`, `Length`, `LongLength`, `Rank`, `SyncRoot`, `IsReadOnly`, `IsFixedSize`, `IsSynchronized` (looks like an `Array` derivative).
> 
> And interestingly, `SyncRoot` contains the data object I originally tried to save as JSON in a Base64 encoded string.

Using the Python worker (v1 model) in Azure Functions with a table storage output binding for an HTTP triggered function, I am encountering this same issue, after having passed the "is not a valid value" error.  There appears to be no way to insert an entity into table storage with additional non-key columns in this scenario.  What is inserted are all the columns skrim noted above.  Is it safe to say that there is no current workaround for this scenario?  It looks like I will have to use the SDK instead of bindings, which also enables me to edit existing entities, so probably would have moved that way anyway.

**Comment by JoshLove-msft** [comment]
This issue should be fixed from the extension host side now. For the language worker side, the outputted entities should be enriched with Odata annotations to not lose any type information. I've created a separate issue in the .NET worker repo - https://github.com/Azure/azure-functions-dotnet-worker/issues/1405 to track this.

**Comment by Catastrophe1** [comment]
Hi @JoshLove-msft 
Has the issue been fixed for Java language worker? What will be the version for the extension that includes the fix?

**Comment by JoshLove-msft** [comment]
The issue is fixed in the extension, but I'm not sure when a new release of the Java worker that targets the new version of the extension will be available. @fabiocav can you answer this question?

**Comment by Catastrophe1** [comment]
@fabiocav Hi Fab, would be appreciate if you can share when the fix will be applied in the latest version.
