### ISSUE TITLE
Fluent - having trouble understanding "Changing property 'computerName' is not allowed."

### ISSUE THREAD

**Issue by awesley** [Azure/azure-sdk-for-net#3433]
Hiya,

I am creating VMs from a stored Image like below.  Every now and again, my requests fail with the exception (a complete stack is provided below the code snippet).  Due to the inconsistency of this, I am struggling to understand the problem.  As you can see I certainly am defining a name for my VM and this seems to work a majority of the time.  

I would appreciate any additional insight into this exception. 

```
            var vm = await this.azure

                .VirtualMachines

                .Define(vmName)

                .WithRegion(region)

                .WithExistingResourceGroup(resourceGroupName)

                .WithExistingPrimaryNetwork(network)

                .WithSubnet(subNetName)

                .WithPrimaryPrivateIPAddressDynamic()

                .WithoutPrimaryPublicIPAddress()

                .WithWindowsCustomImage(image)

                .WithAdminUsername(adminUserName)

                .WithAdminPassword(adminPassword)

                .WithSize(vmSize)

                .WithNewStorageAccount(storageAccountName)

                .WithTag(TagKeyNames.StorageAccountId, storageAccount.Id)

                .CreateAsync();
```

```
Microsoft.Rest.Azure.CloudException occurred
  HResult=0x80131500
  Message=Changing property 'computerName' is not allowed.
  Source=Microsoft.Azure.Management.Compute.Fluent
  StackTrace:
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__20.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperationsExtensions.<CreateOrUpdateAsync>d__3.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineImpl.<CreateResourceAsync>d__151.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LLamasoft.Compute.Provisioning.Azure.AzureInstanceCreator.<CreateVirtualMachine>d__4.MoveNext()
```

**Comment by anuchandy** [comment]
Resource name (vm name) and computer name are two different properties of the VM resource. When you call CreateAsync a random computer name will be generated for the VM.

Are you trying to call CreateAsync with a vm-name when there is already a vm exists with the same name in the same resource group? If so this is expected because underneath we do a PUT and if resource already exists azure consider it as an update request. Calling CreateAsync in this case cause doing a PUT with random computer name (that is different from the current computer name) and changing computer name is not allowed for an existing VM.

**Comment by awesley** [comment]
That is in fact what was happening.  I have a class responsible for naming these VMs (they are rapidly created, used, and torn down in our application) and the convention for naming was creating collisions.  

Thank you!
