### ISSUE TITLE
[QUERY] InvalidRequestFormat empty error when creating NetworkInterface - how to troubleshoot?

### ISSUE THREAD

**Issue by steven-hyland** [Azure/azure-sdk-for-net#34349]
### Library name and version

Azure.ResourceManager.Network 1.1.1

### Query/Question

I am running into an error trying to create a network interface with libraries `Azure.ResourceManager@1.4.0` and `Azure.ResourceManager.Network@1.1.1`.

Here is the code. All of the calls are authenticated correctly, and succeed up until the `CreateOrUpdateAsync()` call:

```
var subnetResponse = await vnet.GetSubnetAsync("<redacted>");
SubnetResource subnet = subnetResponse.Value;

var newNic = new NetworkInterfaceData {
    NicType = Azure.ResourceManager.Network.Models.NetworkInterfaceNicType.Standard,
    EnableAcceleratedNetworking = false,
    EnableIPForwarding = false,
    Location = resourceGroup.Data.Location,
};
newNic.IPConfigurations.Add(new NetworkInterfaceIPConfigurationData {
    PrivateIPAllocationMethod = Azure.ResourceManager.Network.Models.NetworkIPAllocationMethod.Dynamic,
    Primary = true,
    Subnet = subnet.Data,
});
var nicResponse = await (await resourceGroup.GetNetworkInterfaces().CreateOrUpdateAsync(
    WaitUntil.Completed,
    "<redacted>",
    newNic
)).WaitForCompletionAsync();
```

At this point an exception is thrown with 400 Bad Request from the endpoint the libraries are hitting. Here is the relevant error message:

```
Azure.RequestFailedException: Cannot parse the request.
Status: 400 (Bad Request)
ErrorCode: InvalidRequestFormat

Content:
{
  "error": {
    "code": "InvalidRequestFormat",
    "message": "Cannot parse the request.",
    "details": []
  }
}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-request-id: b3faae70-0394-4058-b628-226e9fb911e2
x-ms-client-request-id: a6c118ee-f5c8-45fe-8555-5f70eb163204
Strict-Transport-Security: REDACTED
Server: Microsoft-HTTPAPI/2.0,Microsoft-HTTPAPI/2.0
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
X-Content-Type-Options: REDACTED
Date: Fri, 17 Feb 2023 22:37:48 GMT
Content-Length: 124
Content-Type: application/json; charset=utf-8
Expires: -1

   at Azure.ResourceManager.Network.NetworkInterfacesRestOperations.CreateOrUpdateAsync(String subscriptionId, String resourceGroupName, String networkInterfaceName, NetworkInterfaceData data, CancellationToken cancellationToken)
   at Azure.ResourceManager.Network.NetworkInterfaceCollection.CreateOrUpdateAsync(WaitUntil waitUntil, String networkInterfaceName, NetworkInterfaceData data, CancellationToken cancellationToken)
```

So the problem here is I don't know what to fix, or which fields are missing, or why this can't be parsed, because the request response `details` is empty.

Is there a documentation page or other official MS source that lists exactly which fields are required in `NetworkInterfaceData` in order for it to be created correctly? I've been digging through the documentation pages and haven't found anything. While some fields are marked `readonly`, that only goes so far.

If not, then how can I proceed with troubleshooting this issue?

### Environment

Output of `dotnet --info`:

```
.NET SDK (reflecting any global.json):
 Version:   6.0.406   
 Commit:    2988897946

Runtime Environment:  
 OS Name:     Windows 
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.406\

global.json file:
  Not found

Host:
  Version:      6.0.14
  Architecture: x64
  Commit:       2a90daa2cc
```

IDE is VS Code, latest version.

**Comment by ArcturusZhang** [comment]
Hi @steven-hyland thanks for this issue.
I am not quite sure where exactly goes wrong in your code, everything looks fine.
But it is more probable that this is an issue on the service side because they are not giving proper error messages.

Is there any chance we could have a raw http request payload for your request here? That would help us debug where is the problem

**Comment by steven-hyland** [comment]
@ArcturusZhang Hello, thanks for the tip! Here is the raw payload:

```
{"location":"eastus2","properties":{"ipConfigurations":[{"properties":{"privateIPAllocationMethod":"Dynamic","subnet":{"id":"/subscriptions/6e7f4b45-aff8-43c4-843f-4227b9f7ad8b/resourceGroups/PPG-NETWORKING-DEV-RG/providers/Microsoft.Network/virtualNetworks/vnet-dev-use2-001/subnets/snet-privatelink-use2-dev-01","name":"snet-privatelink-use2-dev-01","type":"Microsoft.Network/virtualNetworks/subnets","properties":{"addressPrefix":"10.144.9.0/25","routeTable":{"id":"/subscriptions/6e7f4b45-aff8-43c4-843f-4227b9f7ad8b/resourceGroups/rg-networking-use2-dev-01/providers/Microsoft.Network/routeTables/route-vnet-dev-use2-001","properties":{}},"serviceEndpoints":[],"delegations":[],"privateEndpointNetworkPolicies":"Disabled","privateLinkServiceNetworkPolicies":"Enabled"}},"primary":true}}],"enableAcceleratedNetworking":false,"enableIPForwarding":false,"nicType":"Standard"}}
```

With nicer formatting:
```
{
  "location": "eastus2",
  "properties": {
    "ipConfigurations": [
      {
        "properties": {
          "privateIPAllocationMethod": "Dynamic",
          "subnet": {
            "id": "/subscriptions/6e7f4b45-aff8-43c4-843f-4227b9f7ad8b/resourceGroups/PPG-NETWORKING-DEV-RG/providers/Microsoft.Network/virtualNetworks/vnet-dev-use2-001/subnets/snet-privatelink-use2-dev-01",
            "name": "snet-privatelink-use2-dev-01",
            "type": "Microsoft.Network/virtualNetworks/subnets",
            "properties": {
              "addressPrefix": "10.144.9.0/25",
              "routeTable": {
                "id": "/subscriptions/6e7f4b45-aff8-43c4-843f-4227b9f7ad8b/resourceGroups/rg-networking-use2-dev-01/providers/Microsoft.Network/routeTables/route-vnet-dev-use2-001",
                "properties": {}
              },
              "serviceEndpoints": [],
              "delegations": [],
              "privateEndpointNetworkPolicies": "Disabled",
              "privateLinkServiceNetworkPolicies": "Enabled"
            }
          },
          "primary": true
        }
      }
    ],
    "enableAcceleratedNetworking": false,
    "enableIPForwarding": false,
    "nicType": "Standard"
  }
}
```

Let me know if I can provide any other info.

**Comment by navba-MSFT** [comment]
@steven-hyland Could you compare the above request headers with the Sample Request Headers mentioned in the below link ? 


[Create network interface](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-interfaces/create-or-update?tabs=HTTP#create-network-interface)
[Create network interface with Gateway Load Balancer Consumer configured](https://learn.microsoft.com/en-us/rest/api/virtualnetwork/network-interfaces/create-or-update?tabs=HTTP#create-network-interface-with-gateway-load-balancer-consumer-configured)

**Comment by steven-hyland** [comment]
@navba-MSFT I don't see headers mentioned in those links you provided, do you mean the request bodies?

I don't have direct control over the request bodies - I am not calling the management endpoints directly, I am using the `Azure.ResourceManager` libraries, as described above. 

From a comparison I can see that the request bodies the above code generates are more verbose than the examples given. Are you suggesting that there is too much information included? What should I do to troubleshoot - just experiment with removing fields until it works?

**Comment by steven-hyland** [comment]
Alright, well, I did some experimentation, and the issue seems to be that I was leaving out the `name` property of the included ip configuration.

So adding this to the above code now works:
```
newNic.IPConfigurations.Add(new NetworkInterfaceIPConfigurationData {
    PrivateIPAllocationMethod = Azure.ResourceManager.Network.Models.NetworkIPAllocationMethod.Dynamic,
    Primary = true,
    Subnet = subnet.Data,
    Name = "ipconfig1", // adding this is now working
});
```

@navba-MSFT @ArcturusZhang thank you for the guidance. Are you able to take this forward with the team to correct the error message in this instance? Let me know if anything is needed from me to make that happen.

**Comment by navba-MSFT** [comment]
@steven-hyland Thanks for getting back. I am glad that the issue is fixed and you are unblocked. I am adding the service team to look into your ask about `NetworkInterfaceIPConfigurationData`.

**Comment by navba-MSFT** [comment]
@aznetsuppgithub Could you please look into this issue ? Thanks.

**Comment by steven-hyland** [comment]
I noticed this has the `needs-author-feedback` label, based on the above conversation I don't think there's anything else I can provide at this time. Let me know if that's wrong.
