### ISSUE TITLE
ServiceBusTrigger with a ReceiveBatchAsync throws TaskCanceledException when Function App is inactive

### ISSUE THREAD

**Issue by rejidasan-gd** [Azure/azure-sdk-for-net#34360]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus Version=5.8.1

### Describe the bug

We have an Azure Function that listens on a ServiceBusTrigger via a batched trigger. When there is no continuous flow of messages, looks like the Trigger shuts down. But when it does that, it throws a `TaskCanceledException`
The trigger looks like this
```
 [FunctionName("my_function")]
 public async Task Run([ServiceBusTrigger("q.topic.mytopic", "q.subscription.mysubscription", Connection = "ServiceBusConnection", AutoCompleteMessages = false)] ServiceBusReceivedMessage[] messages,            ServiceBusMessageActions messageActions)
```

Full Exception:
```
q.topic.mytopic/Subscriptions/q.subscription.mysubscription-d48eed0c-a31e-42ef-912d-a06edfdc118c: ReceiveBatchAsync Exception: System.Threading.Tasks.TaskCanceledException: A task was canceled.
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.ReceivingAmqpLink.EndReceiveMessages(IAsyncResult result, IEnumerable`1& messages)
   at Microsoft.Azure.Amqp.ReceivingAmqpLink.<>c.<ReceiveMessagesAsync>b__27_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsyncInternal(Int32 maxMessages, Nullable`1 maxWaitTime, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<ReceiveMessagesAsync>b__41_0>d.MoveNext()
--- End of stack trace from previous location ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.RunOperation[T1,TResult](Func`4 operation, T1 t1, TransportConnectionScope scope, CancellationToken cancellationToken, Boolean logRetriesAsVerbose)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.ReceiveMessagesAsync(Int32 maxMessages, Nullable`1 maxWaitTime, Boolean isProcessor, CancellationToken cancellationToken).
```
 I see that the same issue was reported by some time back here https://github.com/Azure/azure-sdk-for-net/issues/31508

### Expected behavior

The ServiceBusTriggers gets shutdown without throwing exceptions or ServiceBusTrigger remains active always without shutting down

### Actual behavior

The ServiceBusTriggers gets shutdown with throwing exceptions

### Reproduction Steps

Set up a ServiceBusTrigger with a Batched operation and let it remain idle for a while without any messages. After a while it shuts down along with throwing the above exception

### Environment

Azure Functions latest version
.Net 6

**Comment by rejidasan-gd** [comment]
The same issue was reported some time back here https://github.com/Azure/azure-sdk-for-net/issues/31508

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
