### ISSUE TITLE
[BUG] Azure Data Lake SDK throws a JsonReaderException if a non-successful “ListPaths” response contains a malformed JSON body

### ISSUE THREAD

**Issue by natinimni** [Azure/azure-sdk-for-net#34468]
### Library name and version

Azure.Storage.Files.DataLake 12.12.1 (& earlier)

### Describe the bug

The SDK does not seem to gracefully handle responses that contain a malformed JSON body. We've encountered this situation in our production environment. 
 
Consider the following code sample*, in which I simulate a response with malformed body by using `DataLakeClientOptions.Transport`:

```
static int GetNumberOfPathsTest(Uri adlDirecetoryUri, TokenCredential tokenCredential)
{
    var handler = new SimulateResponseWithMalformedJsonHttpClientHandler();

    var client = new DataLakeDirectoryClient(adlDirecetoryUri, tokenCredential,
        new DataLakeClientOptions
        {
            Transport = new HttpClientTransport(handler)
        });

    return client.GetPaths().Count();
}

public class SimulateResponseWithMalformedJsonHttpClientHandler : HttpClientHandler
{
    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        var response = new HttpResponseMessage(HttpStatusCode.InternalServerError);
        response.Content = new StringContent("{Malformed JSON}", Encoding.UTF8, "application/json");
        return Task.FromResult(response);
    }
}
```

When executed, the SDK throws the following exception:
```
System.Text.Json.JsonReaderException: 'M' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Azure.Core.Pipeline.StorageClientDiagnostics.ExtractFailureContent(String content, ResponseHeaders responseHeaders, IDictionary`2& additionalInfo)
   at Azure.Core.Pipeline.ClientDiagnostics.CreateRequestFailedException(Response response, ResponseError error, IDictionary`2 additionalInfo, Exception innerException)
   at Azure.Storage.Files.DataLake.FileSystemRestClient.ListPaths(Boolean recursive, Nullable`1 timeout, String continuation, String path, Nullable`1 maxResults, Nullable`1 upn, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeFileSystemClient.<GetPathsInternal>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Files.DataLake.Models.GetPathsAsyncCollection.<GetNextPageAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.<GetEnumerator>d__5.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.GetNumberOfPathsTest(Uri adlDirecetoryUri, TokenCredential tokenCredential)
```

Looking at the source code, it seems that `StorageClientDiagnostics` is overriding its base class’s `ExtractFailureContent` method, but unlike the overridden method, it is not wrapped with a try-catch block.
This means that if a non-successful response contains a malformed JSON body, the call to `JsonDocument.Parse(content)` will throw an exception which will not be handled.   

*Note that the code sample above won't work if compiled in .NET Core, due to a different unrelated issue: #34466

### Expected behavior

Malformed server responses should be handled gracefully. 

### Actual behavior

The SDK throws a System.Text.Json.JsonReaderException (see details above).

### Reproduction Steps

Compile the code snippet above using .NET Framework and execute.
Note that the code sample above won't work if compiled in .NET Core, due to a different unrelated issue: #34466

**Comment by navba-MSFT** [comment]
Adding Service team to look into this. 

@sumantmehtams Could you please look into this once you get a chance ?

cc @amnguye @seanmcc-msft

**Comment by amnguye** [comment]
@jsquire @JoshLove-msft Looks like they there's an ask to improve the error handling when there's malform JSON.

IMO the stack trace is clear to me that the response body json being returned from the pipeline is incorrect however I'm assuming to other customers and the OP it's not clear to them. Is there a way we can improve it?

**Comment by jsquire** [comment]
@m-nash:  Would you offer thoughts on Amanda's question?  I believe this would fall into the generator's patterns for serialization, no?

**Comment by m-nash** [comment]
@amnguye can you help me understand what additional information you would expect from the error?

The example above shows that the json was
`"{Malformed JSON}"` 
and the error said
`System.Text.Json.JsonReaderException: 'M' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.`

**Comment by amnguye** [comment]
I think @natinimni 's request is that they would like for the Error message to say that the `Response` from the service had Malformed JSON. To them the stack trace and the exception message is them is not clear to them what went wrong in the SDK, whether the response returned an error or if the JSON itself was malformed.

@natinimni  feel free to chime in about your experience.

**Comment by JoshLove-msft** [comment]
One thing to note is that the referenced type StorageClientDiagnostics doesn't exist anymore - it was deleted in https://github.com/Azure/azure-sdk-for-net/pull/33001. The issue is that the old diagnostics code did not have robust handling for when the response from the service was not valid based on the content type. The [new code](https://github.com/Azure/azure-sdk-for-net/pull/33001/files#diff-be372afcb3d72f4c9117fde61c8892937a9481d845e10ffdc08360e6744a3d6fR78) does a try/catch so this should no longer happen.

**Comment by natinimni** [comment]
Thank you @JoshLove-msft. The new code you linked seem was merged some 3 months ago, but seemingly only to a forked repo (as far as I can tell). Moreover, I don't see that a try-catch was added in the flow described by this bug - for DataLake SDK, indeed that PR replaced StorageClientDiagnostics with ClientDiagnostics, but  ClientDiagnostics.CreateRequestFailedException() is calling ReadContentAsync() which attempts to read the response's content while relying on the response's ContentType header as the format (which will fail) - non of this code is try-catch'ed... but I might be missing something here.
Assuming I'm wrong and that this issue was indeed fixed 3 months ago - when should I expect it to reach the next version of the DataLake NuGet?

**Comment by JoshLove-msft** [comment]
The code linked was merged into main. This was already shipped in [12.13.0](https://www.nuget.org/packages/Azure.Storage.Files.DataLake/12.13.0). The code has been moved (yet again) to [RequestFailedException](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/RequestFailedException.cs#L265), but it does have try/catch to handle exceptions.

**Comment by natinimni** [comment]
Hi @JoshLove-msft , this issue is not resolved - using the repro code provided above still reproduce the issue, even when using the latest SDK (Azure.Storage.Files.DataLake 12.14.0). The SDK still throws a System.Text.Json.JsonReaderException (see details above).

**Comment by JoshLove-msft** [comment]
@natinimni, can you share the new stack trace? The original one in the issue description contains StorageClientDiagnostics which has been deleted.

**Comment by natinimni** [comment]
Hi @JoshLove-msft - of course! thank you for looking into this :) 
It seems that in the new stack trace `StorageClientDiagnostics.ExtractFailureContent` was replaced by `RequestFailedException.GetRequestFailedException`:

```
System.Text.Json.JsonReaderException: 'M' is an invalid start of a property name. Expected a '"'. LineNumber: 0 | BytePositionInLine: 1.
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(Stream utf8Json, JsonDocumentOptions options)
   at Azure.Core.Pipeline.StorageRequestFailedDetailsParser.TryParse(Response response, ResponseError& error, IDictionary`2& data)
   at Azure.RequestFailedException.GetRequestFailedExceptionContent(Response response)
   at Azure.Core.Pipeline.ClientDiagnostics.CreateRequestFailedException(Response response, ResponseError error, IDictionary`2 additionalInfo, Exception innerException)
   at Azure.Storage.Files.DataLake.FileSystemRestClient.ListPaths(Boolean recursive, Nullable`1 timeout, String continuation, String path, Nullable`1 maxResults, Nullable`1 upn, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeFileSystemClient.<GetPathsInternal>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Files.DataLake.Models.GetPathsAsyncCollection.<GetNextPageAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.<GetEnumerator>d__5.MoveNext()
   at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args)
```
