### ISSUE TITLE
[QUERY] Receiving error while using Azure.Messaging.EventHubs.Consumer.EventHubConsumerClient.GetPartitionIdsAsync: 'System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.'

### ISSUE THREAD

**Issue by dddat1017** [Azure/azure-sdk-for-net#34640]
### Library name and version

Azure.Messaging.EventHubs

### Query/Question

Hi,

I'm using the EventHubConsumerClient to read events from an event hub. For some reason, I keep running into this error from time to time:
```
System.IO.IOException:  Received an unexpected EOF or 0 bytes from the transport stream.
   at System.Net.Security.SslStream.<FillHandshakeBufferAsync>g__InternalFillHandshakeBufferAsync|189_0[TIOAdapter](TIOAdapter adap, ValueTask`1 task, Int32 minSize)
   at System.Net.Security.SslStream.ReceiveBlobAsync[TIOAdapter](TIOAdapter adapter)
   at System.Net.Security.SslStream.ForceAuthenticationAsync[TIOAdapter](TIOAdapter adapter, Boolean receiveFirst, Byte[] reAuthenticationData, Boolean isApm)
   at System.Threading.Tasks.TaskToApm.End(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.Transport.TlsTransport.HandleOpenComplete(IAsyncResult result, Boolean syncComplete)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.OpenAsyncResult.End(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpObject.EndOpen(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.HandleTransportOpened(IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.TlsTransportInitiator.OnTransportOpened(IAsyncResult result)
--- End of stack trace from previous location ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.Transport.AmqpTransportInitiator.<>c.<ConnectAsync>b__17_1(IAsyncResult r)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateAndOpenConnectionAsync(Version amqpVersion, Uri serviceEndpoint, Uri connectionEndpoint, EventHubsTransportType transportType, IWebProxy proxy, Int32 sendBufferSizeBytes, Int32 receiveBufferSizeBytes, RemoteCertificateValidationCallback certificateValidationCallback, String scopeIdentifier, TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenManagementLinkAsync(TimeSpan operationTimeout, TimeSpan linkTimeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpClient.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConnection.GetPropertiesAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConnection.GetPartitionIdsAsync(EventHubsRetryPolicy retryPolicy, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Consumer.EventHubConsumerClient.GetPartitionIdsAsync(CancellationToken cancellationToken)
```

Here is a snippet of the code I'm using:
```
var connectionString = "<< CONNECTION STRING FOR THE EVENT HUBS NAMESPACE >>";
var eventHubName = "<< NAME OF THE EVENT HUB >>";
var consumerGroup = EventHubConsumerClient.DefaultConsumerGroupName;

var consumer = new EventHubConsumerClient(
    consumerGroup,
    connectionString,
    eventHubName);

try
{
    using CancellationTokenSource cancellationSource = new CancellationTokenSource();
    cancellationSource.CancelAfter(TimeSpan.FromSeconds(30));

    string firstPartition = (await consumer.GetPartitionIdsAsync(cancellationSource.Token)).First();
    EventPosition startingPosition = GetLastStoredPosition();

    var eventCount = 0;
    var options = new ReadEventOptions
    {
        MaximumWaitTime = TimeSpan.FromSeconds(5)
    };

    await foreach (PartitionEvent partitionEvent in consumer.ReadEventsFromPartitionAsync(
        firstPartition,
        startingPosition,
        options))
    {
        if (partitionEvent.Data != null)
        {
            string readFromPartition = partitionEvent.Partition.PartitionId;
            ReadOnlyMemory<byte> eventBodyBytes = partitionEvent.Data.EventBody.ToMemory();

            Debug.WriteLine($"Read event of length { eventBodyBytes.Length } from { readFromPartition }");
            eventCount++;
            if (eventCount >= 5)
                {
                    break;
                }
            }
        else
        {
            break;
        }
    }
}
finally
{
    await consumer.CloseAsync();
}
```

For more context, this code is invoked concurrently across many many threads. I have a feeling it might have something to do with the closing of the consumer? Please help, thanks!

**Comment by jsquire** [comment]
Hi @dddat1017.  Thank you for reaching out and we regret that you're experiencing difficulties.  The error indicates that a connection was closed while it was in the middle of being created and the transport aborted due to an unexpected state.  This could be due to a transient network failure, host environment issue, or the application closing/disposing the client while a service call was being made.

From your description of concurrent invocation, it seems that the latter is most likely in your scenario.  That said, I don't see how your code snippet is being invoked concurrently, so if each thread is using its own consumer, it is likely one of the other scenarios that I listed.   Can you share an illustration of how this code is invoked concurrently?

**Comment by dddat1017** [comment]
This snippet of code is encapsulated in a function which gets invoked when we spawn a bunch of threads. So, each thread should be using its own consumer and closing said consumer once the thread is done with it (in the finally block). If due to transient network failure or host environment issue, is there any way we could prevent this? I can confirm that it is not always happening but would like to know if there's a way to drastically reduce its occurrence. Thanks!

**Comment by jsquire** [comment]
There's not much that can be done for any kind of network failure.   The Event Hubs client library has little insight or influence into this particular exception as it is taking place in the .NET runtime network stack via its interaction with the AMQP transport library.   I don't think that we'd learn much from capturing SDK logs, as it is not in control at this point in time.

One thing that could be a contributor is the amount of concurrency that you're using.  How many threads are you running concurrently and how many CPU cores are on the host?  

If you're using a number of background tasks much larger than the number of available CPU cores in your host, then async continuations are being queued.  Since there is no fairness in scheduling, the order that each will be resumed is indeterminate.   Some may be lively; some may stall for long periods.   Since you're setting cancellation at 30 seconds, it may be possible that some tasks are unable to open connections before the token signals and, due to a paused continuation, the AMQP transport aborts the network in an unexpected state.

Another could be contention in the network stack itself; each consumer that you open creates an individual connection to the Event Hubs service.  Depending on the host's network hardware, the number of concurrent background threads, and the bandwidth of the host, it may be possible that some attempts at opening a connection get aborted by the CLR or host OS due to resource contention.   Here, again, it would be good to know the concurrency.

I'd also mention that the pattern for creating consumers that you're using isn't advised.  You'll pay a hefty cost creating/destroying them.   We advise creating one client per connection that you need and treating that as a singleton for the lifetime of your application.  You can concurrently call `ReadEventsFromPartitionAsync` from different threads and each will have its own reader (and AMQP link).   Here, again, I don't know the degree of concurrency that you're using, but most application scenarios are just fine with a single connection or a small pool of less than 10.

**Comment by dddat1017** [comment]
Thanks for the detailed response. In which case, I believe caching the client and re-using it would be a good approach here. The only thing is, what if I don't want to cache the client for the lifetime of the application (like the docs say)? I was wondering if I could cache it in-memory (using something simple like `IMemoryCache`) with a fairly short sliding expiration of 1hr or so, how can I dispose of it upon eviction? From the docs here: https://learn.microsoft.com/en-us/aspnet/core/performance/caching/memory?view=aspnetcore-7.0#memorycacheentryoptions, I can set a `PostEvictionDelegate` but since calling dispose/close on the client is async, this wouldn't work. Any advice? Thanks a lot for all your help!

**Comment by jsquire** [comment]
There's little benefit to destroying the client unless you're in a memory-constrained environment- like an IoT device or embedded system.  The service connection will idle-out after a period of inactivity.  By default, this is a minimum of 60 seconds and maximum of 30 minutes but can be adjusted in the `EventHubConnectionOptions`, similar to [this sample](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/eventhub/Azure.Messaging.EventHubs/samples/Sample02_EventHubsClients.md#using-web-sockets).   This cleans up all network resources and recreates them the next time a service operation is invoked.

I'd very much like to understand more about your end-to-end scenario.
