### ISSUE TITLE
[BUG] Get 404 while waiting delete eventhub namespace complete

### ISSUE THREAD

**Issue by linsqi** [Azure/azure-sdk-for-net#34671]
### Library name and version

Azure.ResourceManager.EventHubs 1.0.0

### Describe the bug

As title, getting 404 while waiting delete eventhub namespace to complete. See stacktrace below, let me know if any further information is needed.

```targetRegion : SOUTHCENTRALUS, exception : Inner Exception: Azure.RequestFailedException: The Resource 'Microsoft.EventHub/namespaces/pvtli-iothub-ns-hub0301-08-10-49992b256d' under resource group 'Default-EventHub-SouthCentralUS' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix
Status: 404 (Not Found)
ErrorCode: ResourceNotFound
Content:
{"error":{"code":"ResourceNotFound","message":"The Resource 'Microsoft.EventHub/namespaces/pvtli-iothub-ns-hub0301-08-10-49992b256d' under resource group 'Default-EventHub-SouthCentralUS' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"}}
Headers:
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-request-id: 102ebea4-3d16-4865-be79-0feb85fcf13c
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Content-Length: 273
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Date: Thu, 02 Mar 2023 05:45:28 GMT
Expires: -1
   at Azure.Core.OperationInternal`1.GetResponseFromState(OperationState`1 state)
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternal.<UpdateStatusAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.ResourceManager.EventHubs.EventHubsNamespaceResource.<DeleteAsync>d__36.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Internal.Azure.Devices.Common.AzureServiceManagement.Clients.AzureResourceManagerEventHubClient.<DeleteNamespaceIfExistsAsync>d__8.MoveNext() in C:\__w\1\s\common\Microsoft.Internal.Azure.Devices.Common.AzureServiceManagement\Clients\AzureResourceManagerEventHubClient.cs:line 143
--- End of stack trace from previous location where exception was thrown ---```

### Expected behavior

No error in eventhub namespace deletion and while waiting delete completion.

### Actual behavior

Get 404 while waiting delete eventhub namespace complete.

### Reproduction Steps

Delete eventhub namespace with WaitUntil.Completed option.

### Environment

_No response_

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by linsqi** [comment]
any update?

**Comment by ArthurMa1978** [comment]
Hi @linsqi, please confirm if the eventhub namespace `Microsoft.EventHub/namespaces/pvtli-iothub-ns-hub0301-08-10-49992b256d` was exised under resource group `Default-EventHub-SouthCentralUS` in your subs.

**Comment by live1206** [comment]
@linsqi I tried to create and delete an EventHub  namespace multiple times locally, did not get any 404 error.
@lsqi07 As you mentioned it throwed randomly, did you see a pattern of this throw? And how random is it, like 1 of 10? I tried for 5 times in a loop.

**Comment by ArthurMa1978** [comment]
> @linsqi Linshen Qi FTE I tried to create and delete an EventHub namespace multiple times locally, did not get any 404 error. @lsqi07 As you mentioned it threw randomly, did you see a pattern of the throw? And how random is it, like 1 of 10? I tried for 5 times in a loop.

This might be an issue from service side, please contact service for more info.
