### ISSUE TITLE
[BUG] DefaultAzureCredential throws when azd is not installed

### ISSUE THREAD

**Issue by KrzysztofCwalina** [Azure/azure-sdk-for-net#34702]
### Library name and version

Azure.Identity 1.9.0-beta.2

### Describe the bug

I tried to use DefaultAzureCredentail on a machine that does not have azd installed. I am getting the following exception:

Azure.Identity.AuthenticationFailedException
  HResult=0x80131500
  Message=Azure Developer CLI authentication failed due to an unknown error. Please visit https://aka.ms/azure-dev for installation instructions and then, once installed, authenticate to your Azure account using 'azd login'. Error: unknown command "auth" for "azd"
Run 'azd --help' for usage.
  Source=Azure.Identity
  StackTrace:
   at Azure.Identity.AzureDeveloperCliCredential.<RequestCliAccessTokenAsync>d__33.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Identity.AzureDeveloperCliCredential.<GetTokenImplAsync>d__32.MoveNext()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.AzureDeveloperCliCredential.<GetTokenImplAsync>d__32.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
   at Azure.Identity.AzureDeveloperCliCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.DefaultAzureCredential.<GetTokenFromSourcesAsync>d__14.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__12.MoveNext()
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.DefaultAzureCredential.<GetTokenImplAsync>d__12.MoveNext()
   ...

### Expected behavior

The credential should not fail when azd is not installed. It should behave as if the user is not logged into azd, i.e. continue with the credential chain

### Actual behavior

exception, see above. 

### Reproduction Steps

install Azure.Identity 1.9.0-beta.2
run the following code on a machine without azd installed:

var c = new DefaultAzureCredential();
var token = c.GetToken(...);

**Comment by jsquire** [comment]
//cc: @christothes

**Comment by christothes** [comment]
It seems like azd is installed but is not recognizing the `azd auth` command.

```
Error: unknown command "auth" for "azd"
Run 'azd --help' for usage.
```

This could have been an unexpected change to azd's commands. I'll look into this a bit further.

**Comment by schaabs** [comment]
Seems like an older version of azd before the auth command was added.
