### ISSUE TITLE
[BUG] Unexpected type for header

### ISSUE THREAD

**Issue by kevinharing** [Azure/azure-sdk-for-net#34784]
### Library name and version

Azure.Core 1.29.0

### Describe the bug

After upgrading to `Azure.Core` 1.29.0 (required by `Microsoft.Extensions.Azure` 1.6.2) we repeatedly receive this error:

```
System.InvalidOperationException: Unexpected type for header : 
 at Azure.Core.Pipeline.HttpClientTransport.PipelineRequest.GetHttpHeaderValue(String headerName, Object value)
 at Azure.Core.Pipeline.HttpClientTransport.PipelineRequest.EnumerateHeaders()+MoveNext()
 at Azure.Core.Diagnostics.AzureCoreEventSource.FormatHeaders(IEnumerable`1 headers, HttpMessageSanitizer sanitizer)
 at Azure.Core.Diagnostics.AzureCoreEventSource.Request(Request request, String assemblyName, HttpMessageSanitizer sanitizer)\n at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
 at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
 at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)\n at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
 at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
 at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
 at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.SendHttpRequestAsync(Request request, CancellationToken cancellationToken)\n at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.GetEntityAsync(String entityPath, String query, Boolean enrich, CancellationToken cancellationToken)
 at Azure.Messaging.ServiceBus.Administration.ServiceBusAdministrationClient.GetQueueAsync(String name, CancellationToken cancellationToken)
```

This does not happen locally. It only occurs when running in a container in AKS using managed identity credentials. Downgrading to `Azure.Core` 1.28.0 and `Microsoft.Extensions.Azure` 1.6.0 solves the issue. If it helps we're using `Azure.Messaging.ServiceBus` 7.12.0.

### Expected behavior

No errors.

### Actual behavior

See bug description.

### Reproduction Steps

See bug description.

**Comment by jsquire** [comment]
//cc: @annelo-msft, @christothes

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
This appears to be a new exception added in https://github.com/Azure/azure-sdk-for-net/pull/34195

**Comment by kevinharing** [comment]
> This appears to be a new exception added in #34195

Yes, I noticed that as well. A lot of changes in that space.

**Comment by JoshLove-msft** [comment]
I haven't been able to repro yet, but I wonder if we need to use `IList<string>` rather than `List<string>` here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L509

**Comment by kevinharing** [comment]
I can confirm it has been fixed in `Azure.Core` 1.30.0.

**Comment by stevendarby** [comment]
We're still getting an "Unexpected type for header" exception and I think it's when `value` is null, which is not handled in this switch expression
https://github.com/Azure/azure-sdk-for-net/blob/c03b37ccd7aa206b8a6c9f303b18d23ee093532b/sdk/core/Azure.Core/src/Pipeline/HttpClientTransport.cs#L506-L511
Which for us is a breaking change in a minor package update...
