### ISSUE TITLE
[BUG] [DataMovement] Uploads does not accept sizes larger than a long (e.g. 3GB+)

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#34794]
### Library name and version

Azure.Storage.DataMovement; Azure.Storage.DataMovement.Blobs

### Describe the bug

Datamovement cannot handle file sizes larger than what a `long` can handle (e.g. 3GB+).

### Expected behavior

The Upload succeeds.

### Actual behavior

Various Symptoms include overflow errors and out of range errors

```
Exception occured with TransferId: cb94e3e9-5fed-4c51-bdd5-b1c0d91b46aa,Source Resource: C:\YanTry\4.5GB Media File.mp4, +Destination Resource: 8334177/4.5GB Media File.mp4,Exception Message: Specified argument was out of the range of valid values.
Parameter name: minimumLength,StackTrace:    at System.Buffers.DefaultArrayPool`1.Rent(Int32 minimumLength)
   at Azure.Storage.Shared.PartitionedStream.<BufferStreamPartitionInternal>d__16.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.DataMovement.StreamToUriJobPart.<GetOffsetPartitionInternal>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Azure.Storage.DataMovement.StreamToUriJobPart.<InitialUploadCall>d__6.MoveNext(),InnerException
```

### Reproduction Steps

n/a

**Comment by amnguye** [comment]
Looking into ways we can expand for upload sizes larger than `long`
