### ISSUE TITLE
[BUG] Add support for China East 3 and China North 3

### ISSUE THREAD

**Issue by nimitpatel-ms** [Azure/azure-sdk-for-net#34818]
### Library name and version

Azure.Core 1.29.0

### Describe the bug

Please support China East 3 and China North 3 in the [AzureLocation.cs](https://github.com/Azure/azure-sdk-for-net/blob/Azure.Core_1.29.0/sdk/core/Azure.Core/src/AzureLocation.cs) file. An error is thrown when we attempt to get list of accounts in China 3.

### Expected behavior

Error should not be thrown. A list of accounts should be returned.

### Actual behavior

The following error is thrown:

System.ArgumentNullException: Value cannot be null.
Parameter name: location

### Reproduction Steps

A subscription with storage accounts in China East 3 and China North 3.
```c#
var tokenCredentials = "<token Credentials object>";
var subscriptionId = "<subscription id string>";
var cancellationToken = "<cancellation token object>";

var client = new ArmClient(
                tokenCredentials,
                string.Empty,
                new ArmClientOptions()
                {
                    Environment = ArmEnvironment.AzureChina
                });

var sub = client.GetSubscriptionResource(SubscriptionResource.CreateResourceIdentifier(subscriptionId));
var accountEnumerator = sub.GetStorageAccountsAsync(cancellationToken).GetAsyncEnumerator(cancellationToken);
while (await accountEnumerator.MoveNextAsync().ConfigureAwait(false))
{
           var account = accountEnumerator.Current;
           var displayName = account.Data.Location.DisplayName;
           var location = account.Data.Location.Name;
}
```

**Comment by jsquire** [comment]
//cc: @annelo-msft, @christothes, @JoshLove-msft

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @nimitpatel-ms 
Can you share the stack trace from the exception you are seeing? 

`AzureLocation` should be [constructable with any arbitrary location name](https://github.com/Azure/azure-sdk-for-net/blob/f288f55241fb6651f757a02672f0612d35495657/sdk/core/Azure.Core/src/AzureLocation.cs#L306), even if it's not included as a static member.

**Comment by nimitpatel-ms** [comment]
The stack trace doesn't point to a line of code, after that it only shows the name of the function which is running the code.
WithRetryAsync is our internal function that is running the code. We don't get an option to construct AzureLocation. 

I am guessing it is generated by the result of (await accountEnumerator.MoveNextAsync().ConfigureAwait(false)) when it creates a StorageAccountResource object. It might be passing in China East 3 location that is not supported or something.

System.ArgumentNullException: Value cannot be null.
Parameter name: location
   at Microsoft.Dynamics.ManagementServices.Aether.ClientShared.Helper.<WithRetryAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Dynamics.ManagementServices.Aether.Providers.ARMProvider.ARMProvider.<GetNumAccountsInRegion>d__18.MoveNext()

**Comment by nimitpatel-ms** [comment]
That is the name of our service. ARMProvider is the class in our service that runs the code.

**Comment by christothes** [comment]
Are you able to reproduce this in isolation using just ArmClient?

**Comment by nimitpatel-ms** [comment]
@christothes It's not possible to reproduce locally because China is a sovereign geo. Storage account in China North 3 or China East 3 cannot be created. We also don't have a test subscription in China.

**Comment by christothes** [comment]
> @christothes It's not possible to reproduce locally because China is a sovereign geo. Storage account in China North 3 or China East 3 cannot be created. We also don't have a test subscription in China.

I have the same dilemma 😄

**Comment by annelo-msft** [comment]
We're closing this since we're unable to reproduce the issue.
