### ISSUE TITLE
[BUG] Transient issue with getting back 403 AuthenticationFailed using Azure.Storage.Blobs v12.15.0

### ISSUE THREAD

**Issue by amnguye** [Azure/azure-sdk-for-net#35009]
### Library name and version

Azure.Storage.Blobs v12.15.0

### Describe the bug

When upgrading from v12.14.1 to v12.15.0, there's a transient issue where on certain storage accounts (may be independent of the storage account .. still investigating), they start getting more AuthenticationFailed (403) on certain requests. When the operation is retried it seems to work.

```
ErrorCode -- AuthenticationFailed
Status -- 403
Message -- Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
Time:2023-03-10T09:42:13.5959481Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed
```

```
AuthenticationErrorDetail: Authentication scheme Bearer is not supported in this version.
```

Confirmed that Azure.Core upgrade to v1.29.0 is not the cause of the issue.
Confirmed the upgrade to Azure.Identity to 1.8.2 is not the issue.

TODO: link related github issue of client request id mismatch error here

### Expected behavior

Upgrading does not cause transient issues.

### Actual behavior

Upgrading to v12.15.0 causes authentication failed issues.

### Reproduction Steps

Call any APIs like `Download` or `Upload` however the issue is transient so it may be harder to track down.

**Comment by amnguye** [comment]
If anyone else hits the same issue and is able to get logs with the "x-ms-request-id" is available in the logs please put them here so it can help with investigating the issue.

Also if anyone has a reproducable code snippet or environment please let us know as well, as the issue is transient.

**Comment by amnguye** [comment]
Looks like this issue was resolved in Azure.Core 1.30 and was not a Azure.Storage.Blobs issue.

Related PR: https://github.com/Azure/azure-sdk-for-net/pull/34800

We will be updating our next release to point at the latest Azure.Core release.

Please upgrade to Azure.Core 1.30 to resolve the issue.

**Comment by amnguye** [comment]
When available please upgrade to Azure.Storage.Blobs v12.5.1 which points at Azure.Storage.Common v12.14.1 which points at Azure.Core 1.30.

**Comment by faix** [comment]
@amnguye one of our internal customers hit this again after we had upgraded to the mentioned packages. So far it has only happened once. But it seems to indicate the issue might not have been resolved fully. 

Azure.RequestFailedException: Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature. RequestId:459e9189-e01e-0029-77ee-92f0ed000000 Time:2023-05-30T12:02:45.7905030Z Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.) ErrorCode: AuthenticationFailed Additional Information: AuthenticationErrorDetail: SAS identifier cannot be found for specified signed identifier Headers: x-ms-request-id: 459e9189-e01e-0029-77ee-92f0ed000000 x-ms-error-code: AuthenticationFailed Date: Tue, 30 May 2023 12:02:45 GMT Server: Microsoft-HTTPAPI/2.0 Content-Length: 437 Content-Type: application/xml
   at Azure.Storage.Blobs.BlobRestClient.<DownloadAsync>d__8.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StartDownloadAsync>d__66.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<>c__DisplayClass65_0.<<DownloadStreamingInternal>b__1>d.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Core.Pipeline.RetriableStream.RetriableStreamImpl.<RetryAsync>d__12.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Core.Pipeline.RetriableStream.RetriableStreamImpl.<ReadAsync>d__11.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.IO.Stream.<CopyToAsyncInternal>d__27.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.PartitionedDownloader.<CopyToAsync>d__12.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.PartitionedDownloader.<>c__DisplayClass9_0.<<DownloadToAsync>g__ConsumeQueuedTask|0>d.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Azure.Storage.Blobs.PartitionedDownloader.<DownloadToAsync>d__9.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StagedDownloadAsync>d__94.MoveNext() 
   --- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__89.MoveNext()

**Comment by amnguye** [comment]
Looks like this issue is unrelated to the original issue.

The original issue had specific symptoms and was unrelated to the SAS. If you look at the fix, it was originally related to the transient error of the http header being overwritten. Since a SAS is a query to the URL and not an HTTP header, I would mark this as a completely different issue.

If you look at the error that the service is giving back it's a
`AuthenticationErrorDetail: SAS identifier cannot be found for specified signed identifier`.

While the original error happening here was `Authentication scheme Bearer is not supported in this version.`

Similar symptoms of transient and a 403 Authentication Failure but probably a different cause.

Looking at the request id, it looks like the original SAS is missing a expirey time. Expirey times are required for a SAS when generating one. Since the original issue was overwriting the original value and not omitting the value entirely, doesn't look related to the original issue.

Please open a new github issue and tag me if this is still an issue for you. Thanks in advance.

**Comment by faix** [comment]
thanks! will follow up with how we are generating the SAS!
