### ISSUE TITLE
Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure

### ISSUE THREAD

**Issue by HeroSpha** [Azure/azure-sdk-for-net#3505]
I have a backend app (api app) that interacts with the database, it copy and creates database. When i use swagger to test my backend it works without any problem. But the error appears when i use my web app client(Asp.net core). When i try to perform the same action, it fails to create database. I searched all my apps for the reference to the version of the runtime mentioned, i could not find it. The question is why my webapp throws an exception
below is my error log
```
"An error has occurred.","exceptionMessage":
"Could not load file or assembly 'Microsoft.Rest.ClientRuntime.Azure, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. 
The system cannot find the file specified.","exceptionType":"System.IO.FileNotFoundException","stackTrace":"   
   at Events_Tenant.Common.Helpers.Helper.CreateDatabase(ApplicationConfig appConfig, CatalogConfig catalogConfig, TenantServerConfig tenantServerConfig, String tenantName)
   at Events_Tenant.Common.Helpers.Helper.<RegisterNewTenant>d__17.MoveNext() in C:\\Users\\DigiHelp IT\\Desktop\\DigiApp\\DigiHelpApp\\src\\Events-Tenant.Common\\Helpers\\Helper.cs:line 228
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at BackendApp.Controllers.HelperController.<RegisterTenant>d__4.MoveNext() in C:\\Users\\DigiHelp IT\\Desktop\\DigiApp\\DigiHelpApp\\BackendApp\\Controllers\\HelperController.cs:line 33
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.TaskHelpersExtensions.<CastToObject>d__3`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ApiControllerActionInvoker.<InvokeActionAsyncCore>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Controllers.ActionFilterResult.<ExecuteAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Http.Dispatcher.HttpControllerDispatcher.<SendAsync>d__1.MoveNext()"
```

**Comment by hovsepm** [comment]
@HeroSpha Which Azure SDK Library are you using?

**Comment by HeroSpha** [comment]
I have fixed the issue, i realised my backend was referencing the Runtime version 3.8.8 which is already referenced in the common project..
