### ISSUE TITLE
[BUG] Azure.ResourceManager.AppPlatform can't work due to UUID format

### ISSUE THREAD

**Issue by ChenTanyi** [Azure/azure-sdk-for-net#35061]
### Library name and version

azure.resourcemanager.appplatform 1.0.1

### Describe the bug

`client.GetAppPlatformServiceResource(id).Get()` get service failed. Maybe it is due to the some service doesn't return UUID in "serviceId" field

for example, here is one of my failed Azure Spring Apps API response:
```JSON
{
    "id": "/subscriptions/***/resourceGroups/***/providers/Microsoft.AppPlatform/Spring/***",
    "location": "eastus2euap",
    "name": "***",
    "properties": {
        "fqdn": "***.azuremicroservices.io",
        "networkProfile": {
            "outboundIPs": {
                "publicIPs": [
                    "20.47.146.102"
                ]
            },
            "outboundType": "loadBalancer"
        },
        "powerState": "Running",
        "provisioningState": "Succeeded",
        "serviceId": "79d502c7359c4afc99095965f28ca37f",
        "version": 3,
        "zoneRedundant": false
    },
    "sku": {
        "name": "B0",
        "tier": "Basic"
    },
    "systemData": {
        "createdAt": "2022-03-21T06:19:40.3152314Z",
        "createdBy": "***",
        "createdByType": "User",
        "lastModifiedAt": "2022-03-21T06:19:40.3152314Z",
        "lastModifiedBy": "***",
        "lastModifiedByType": "User"
    },
    "tags": {},
    "type": "Microsoft.AppPlatform/Spring"
}
```

### Expected behavior

Service should get successfully

### Actual behavior

```
[xUnit.net 00:00:02.28]     test.UnitTest1.Test1 [FAIL]
  Failed test.UnitTest1.Test1 [1 s]
  Error Message:
   System.FormatException : One of the identified items was in an invalid format.
  Stack Trace:
     at System.Text.Json.JsonElement.GetGuid()
   at Azure.ResourceManager.AppPlatform.Models.AppPlatformServiceProperties.DeserializeAppPlatformServiceProperties(JsonElement element)
   at Azure.ResourceManager.AppPlatform.AppPlatformServiceData.DeserializeAppPlatformServiceData(JsonElement element)
   at Azure.ResourceManager.AppPlatform.ServicesRestOperations.Get(String subscriptionId, String resourceGroupName, String serviceName, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppPlatform.AppPlatformServiceCollection.Get(String serviceName, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppPlatform.AppPlatformExtensions.GetAppPlatformService(ResourceGroupResource resourceGroupResource, String serviceName, CancellationToken cancellationToken)
   at test.UnitTest1.Test1() in /root/test/UnitTest1.cs:line 24
   at test.UnitTest1.Test1() in /root/test/UnitTest1.cs:line 16
--- End of stack trace from previous location ---
```

### Reproduction Steps

In above

### Environment

container: mcr.microsoft.com/dotnet/sdk:6.0
```
.NET SDK (reflecting any global.json):
 Version:   6.0.202
 Commit:    f8a55617d2

Runtime Environment:
 OS Name:     debian
 OS Version:  11
 OS Platform: Linux
 RID:         debian.11-x64
 Base Path:   /usr/share/dotnet/sdk/6.0.202/

Host (useful for support):
  Version: 6.0.4
  Commit:  be98e88c76

.NET SDKs installed:
  6.0.202 [/usr/share/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.4 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET runtimes or SDKs:
  https://aka.ms/dotnet-download
```

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by archerzz** [comment]
Talked with @ChenTanyi In this case, the returned `serviceId` has two formats:
- `77af734a-f643-467d-a31f-f873b15cc869`
- `79d502c7359c4afc99095965f28ca37f`

That actually doesn't violate their [swagger definition](https://github.com/Azure/azure-rest-api-specs/blob/c94569d116a82ee11a94c5dfb190650dd675a1bf/specification/appplatform/resource-manager/Microsoft.AppPlatform/stable/2022-12-01/appplatform.json#L6396-L6400) which doesn't specify the format.
![image](https://user-images.githubusercontent.com/4516/226916913-a5e1a1c5-ff45-4a0b-a5b5-f40cf50198b6.png)

**Comment by dingmeng-xue** [comment]
Service Id should be an unique string generated by service. ASA team will update swagger description. Please assume it is just a string rather than GUID.
