### ISSUE TITLE
[Text Analytics] AnalyzeOperationWithMultipleActions failing in nightly runs

### ISSUE THREAD

**Issue by Menghua1** [Azure/azure-sdk-for-net#35272]
TextanAlytics nightly test runs are failing with:

> Error message
> System.ArgumentOutOfRangeException : Unknown State value. (Parameter 'value')
> Actual value was partiallyCompleted.
> 
> 
> Stack trace
>    at Azure.AI.TextAnalytics.Legacy.Models.StateExtensions.ToState(String value) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics.Legacy.Shared/src/Generated/Models/State.Serialization.cs:line 35
>    at Azure.AI.TextAnalytics.Legacy.AnalyzeJobState.DeserializeAnalyzeJobState(JsonElement element) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics.Legacy.Shared/src/Generated/Models/AnalyzeJobState.Serialization.cs:line 103
>    at Azure.AI.TextAnalytics.Legacy.TextAnalyticsRestClient.AnalyzeStatusAsync(String jobId, Nullable`1 showStats, Nullable`1 top, Nullable`1 skip, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics.Legacy.Shared/src/Generated/TextAnalyticsRestClient.cs:line 152
>    at Azure.AI.TextAnalytics.ServiceClients.LegacyServiceClient.AnalyzeStatusAsync(String jobId, Nullable`1 showStats, Nullable`1 top, Nullable`1 skip, IDictionary`2 idToIndexMap, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/ServiceClients/LegacyServiceClient.cs:line 1367
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.Azure.Core.IOperation<Azure.AsyncPageable<Azure.AI.TextAnalytics.AnalyzeActionsResult>>.UpdateStateAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeActionsOperation.cs:line 287
>    at Azure.Core.OperationInternal`1.UpdateStatusAsync(Boolean async, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 260
>    at Azure.Core.OperationInternalBase.UpdateStatusAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 87
>    at Azure.Core.OperationPoller.WaitForCompletionAsync(Boolean async, OperationInternalBase operation, Nullable`1 suggestedInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 79
>    at Azure.Core.OperationInternalBase.WaitForCompletionResponseAsync(Boolean async, Nullable`1 pollingInterval, String scopeName, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 202
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(Boolean async, Nullable`1 pollingInterval, CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 242
>    at Azure.Core.OperationInternal`1.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 177
>    at Azure.AI.TextAnalytics.AnalyzeActionsOperation.WaitForCompletionAsync(CancellationToken cancellationToken) in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/src/AnalyzeActionsOperation.cs:line 210
>    at Azure.AI.TextAnalytics.Tests.AnalyzeOperationTests.AnalyzeOperationWithMultipleActions() in /mnt/vss/_work/1/s/sdk/textanalytics/Azure.AI.TextAnalytics/tests/AnalyzeOperationTests.cs:line 211
>    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
>    at NUnit.Framework.Internal.MessagePumpStrategy.NoMessagePumpStrategy.WaitForCompletion(AwaitAdapter awaiter)
>    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
>    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)

For more details check here:

- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=2668895&view=results

@jsquire for notification.

**Comment by joseharriaga** [comment]
This was a transient service issue that hasn't repro'd in a while now.
