### ISSUE TITLE
[BUG] Confusing error message in Azure.ResourceManager.TrafficManager: PATCH vs PUT

### ISSUE THREAD

**Issue by cizra** [Azure/azure-sdk-for-net#35300]
### Library name and version

Azure.ResourceManager.TrafficManager 1.0.0

### Describe the bug

I'm trying to set the priorities of an Azure Traffic Manager profile, but I'm getting an error message that hints at a bug in Azure.ResourceManager.TrafficManager - it's apparently using the wrong HTTP method.

### Expected behavior

The REST API request towards Azure ResourceManager should succeed, and Traffic Manager endpoints' priority should get modified.

### Actual behavior

```
$ AZURE_TENANT_ID=xxxx dotnet run
TM hasData=True name=myAtmProfile TM num of endpoints=2
EP=MyEndpointName prio=1 status=Online weight=1
EP=MyEndpointName2 prio=2 status=Online weight=1
Unhandled exception. Azure.RequestFailedException: The 'endpoints' property cannot be specified when updating a profile using PATCH. Please use PUT to update the profile instead.
Status: 400 (Bad Request)
ErrorCode: BadRequest

Content:
{"error":{"code":"BadRequest","message":"The 'endpoints' property cannot be specified when updating a profile using PATCH. Please use PUT to update the profile instead."}}

Headers:
Cache-Control: private
X-Content-Type-Options: REDACTED
Strict-Transport-Security: REDACTED
x-ms-request-id: 31a87cad-627b-48bf-83e9-bfd7ded778f2
Server: Microsoft-IIS/10.0
X-AspNet-Version: REDACTED
X-Powered-By: REDACTED
x-ms-ratelimit-remaining-subscription-resource-requests: REDACTED
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Date: Mon, 03 Apr 2023 13:47:29 GMT
Content-Length: 171
Content-Type: application/json; charset=utf-8

   at Azure.ResourceManager.TrafficManager.ProfilesRestOperations.Update(String subscriptionId, String resourceGroupName, String profileName, TrafficManagerProfileData data, CancellationToken cancellationToken)
   at Azure.ResourceManager.TrafficManager.TrafficManagerProfileResource.Update(TrafficManagerProfileData data, CancellationToken cancellationToken)
   at Program.<<Main>$>g__Update|0_1(ResourceIdentifier atmResourceId, <>c__DisplayClass0_0& ) in Program.cs:line 25
   at Program.<Main>$(String[] args) in Program.cs:line 10

### Reproduction Steps

```csharp
using Azure.Core;
using Azure.Identity;
using Azure.ResourceManager;
using Azure.ResourceManager.TrafficManager;

var armClient = new ArmClient(new DefaultAzureCredential(true));
var atmResourceId = TrafficManagerProfileResource.CreateResourceIdentifier(subscriptionId: "MY SUBSCRIPTION ID", resourceGroupName: "MY RESOURCE GROUP", profileName: "MY ATM PROFILE");

Print(atmResourceId);
Update(atmResourceId);
Print(atmResourceId);

void Print(ResourceIdentifier atmResourceId)
{
    var tm = armClient.GetTrafficManagerProfileResource(atmResourceId).Get().Value;
    Console.WriteLine($"TM hasData={tm.HasData} name={tm.Data.Name} TM num of endpoints={tm.Data.Endpoints.Count}");
    foreach (var ep in tm.Data.Endpoints)
        Console.WriteLine($"EP={ep.Name} prio={ep.Priority} status={ep.EndpointMonitorStatus} weight={ep.Weight}");
}

void Update(ResourceIdentifier atmResourceId)
{
    var tm = armClient.GetTrafficManagerProfileResource(atmResourceId).Get().Value;
    tm.Data.Endpoints[0].Priority += 2;
    tm.Update(tm.Data);
}
```

### Environment

Hosting platform: console app on a dev box.
IDE and version: dotnet command line on Linux, Visual Studio 2022 on Windows have the same behavior.

```
$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.405
 Commit:    27ab36058b

Runtime Environment:
 OS Name:     nixos
 OS Version:  22.11
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /nix/store/b9hr18bqz7c291psihs0hl7p84qhj8ib-dotnet-sdk-6.0.405/sdk/6.0.405/

global.json file:
  Not found

Host:
  Version:      6.0.13
  Architecture: x64
  Commit:       1af80ba017

.NET SDKs installed:
  6.0.405 [/nix/store/b9hr18bqz7c291psihs0hl7p84qhj8ib-dotnet-sdk-6.0.405/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.13 [/nix/store/b9hr18bqz7c291psihs0hl7p84qhj8ib-dotnet-sdk-6.0.405/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.13 [/nix/store/b9hr18bqz7c291psihs0hl7p84qhj8ib-dotnet-sdk-6.0.405/shared/Microsoft.NETCore.App]

Download .NET:
  https://aka.ms/dotnet-download

Learn about .NET Runtimes and SDKs:
  https://aka.ms/dotnet/runtimes-sdk-info
```

**Comment by cizra** [comment]
Actually this code works:
```csharp
void Update(ResourceIdentifier atmResourceId)
{
    var tm = armClient.GetTrafficManagerProfileResource(atmResourceId).Get().Value;
    // tm.Data.Endpoints[0].Priority += 2;
    // tm.Update(tm.Data); <- crashes
    var ep = tm.GetTrafficManagerEndpoint("azureEndpoints", tm.Data.Endpoints[0].Name).Value;
    ep.Data.Priority += 2;
    ep.Update(ep.Data);
}
```

I find that the SDK is very short on documentation and code samples.
Also, may we please get a less confusing error message?

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @cizra , Thank you for using Azure SDK for .NET.
The error message is returned from service side.
In this case, if the `Patch - Update` method is not support by the service, we could try to use `Put - CreateOrUpdate` method.
Since you have solved the the problem, I'll close the issue.
Feel free to reopen it if you have any further questions.
