### ISSUE TITLE
[QUERY] Using ARM Client for HTTP based ARM endpoint

### ISSUE THREAD

**Issue by StutiSri** [Azure/azure-sdk-for-net#35343]
### Library name and version

Azure.ResourceManager 1.4.0.0

### Query/Question

I have an Http ArmEndpoint, for which I create an ARM client as below
ArmEnvironment env = new (new Uri("https://armvm9689538-ulooq5ckpyyjg.southcentralus.cloudapp.azure.com"), "https://management.azure.com/");
var armClientOptions = new ArmClientOptions() { Environment = env };
_armClient = new ArmClient(
                    new DefaultAzureCredentials(),
                    subscriptionId,
                    armClientOptions);

The creation is successful, but when I try to access any resource this is the exception I get.
**Function call** - _armClient.GetDefaultSubscriptionAsync();
**Exception**
System.AggregateException: One or more errors occurred. (Bearer token authentication is not permitted for non TLS protected (https) endpoints.)
       ---> System.InvalidOperationException: Bearer token authentication is not permitted for non TLS protected (https) endpoints.
         at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
         at Azure.ResourceManager.Resources.SubscriptionsRestOperations.GetAsync(String subscriptionId, CancellationToken cancellationToken)
         at Azure.ResourceManager.Resources.SubscriptionResource.GetAsync(CancellationToken cancellationToken)
         at Azure.ResourceManager.ArmClient.GetDefaultSubscriptionAsync(CancellationToken cancellationToken)
         at Microsoft.Azure.Compute.Aurora.ScenarioTests.TestCommon.AuroraARMClient.GetSubscriptionResourceAsync(String subscriptionId) in <our class name>

I checked in the SDK and BearerTokenAuthenticationPolicy is explicitly added to the HttpPipeline and this policy enforces the URL to be an HTTPs one. Is there a way to use ARM Client for an HTTP based ARM endpoint?

### Environment

Windows 11
.Net Version: 6
Visual Studio 17.5

**Comment by jsquire** [comment]
Hi @StutiSri.  Thank you for reaching out and we regret that you're experiencing difficulties.  By design, it is not possible to use the Azure SDK clients with HTTP to protect the security of credentials.  To my knowledge, there are no public ARM endpoints that support HTTP; all should be using SSL.    Can you please help me understand the your end-to-end scenario?

**Comment by StutiSri** [comment]
Hi @jsquire, we have decided to switch from an http to an https endpoint. Closing this issue.
