### ISSUE TITLE
Exception occurs when trying to get all subscription regions with the default Russian culture set

### ISSUE THREAD

**Issue by PrettyAndHandsome** [Azure/azure-sdk-for-net#35365]
Steps to reproduce: 

1. set culture to Russian (ru-RU) using, for example, Thread.CurrentThread.CurrentCulture
2. call `var regions = (await client.GetDefaultSubscriptionAsync()).GetLocations().ToList();` where client is Azure.ResourceManager.ArmClient

Actual result: 
`System.FormatException: The input string '-79.8164' was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, ReadOnlySpan`1 value, TypeCode type)
   at System.Double.Parse(String s)
   at Azure.ResourceManager.Resources.Models.LocationMetadata.DeserializeLocationMetadata(JsonElement element)
   at Azure.ResourceManager.Resources.Models.LocationExpanded.DeserializeLocationExpanded(JsonElement element)
   at Azure.Core.PageableHelpers.PageableImplementation`1.GetEnumerator()+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Program.<Main>$(String[] args) in W:\KYC\Utils\Utils\AzureDomainPlayground\Program.cs:line 33
   at Program.<Main>(String[] args)
`

Expected to return a list of azure regions.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
Thank you @PrettyAndHandsome for reporting this important issue!
To handle Json content in the response, the SDK uses [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json), like this case it calls the [JsonElement.GetDouble](https://learn.microsoft.com/en-us/dotnet/api/system.text.json.jsonelement.getdouble) to deserialize the value from Json string.
But unfortunately, the  [System.Text.Json](https://learn.microsoft.com/en-us/dotnet/api/system.text.json) doesn't support CultureInfo option](https://github.com/dotnet/runtime/issues/1366).

We're considering better ways to fix this issue, and we'll let you know once have any update.

**Comment by ArthurMa1978** [comment]
Hey @preetibayasMS ,
I appreciate your feedback, after discussion we think this is a new feature instead of a bug, so I’m going to close this issue for now, and opened a new issue here https://github.com/Azure/autorest.csharp/issues/3651 to track.
If you have any concerns or questions, please feel free to comment on this thread and reopen the issue. I’ll be happy to help you further. Thank you for your understanding and cooperation.
I'm closing this issue as this is a new feature that I

**Comment by ArthurMa1978** [comment]
Fixes in https://github.com/Azure/azure-sdk-for-net/pull/49560.
