### ISSUE TITLE
[BUG] Azure.Search throws when retrieving a SearchIndex created using an encryption key without `accessCredentials` set

### ISSUE THREAD

**Issue by annanakashimo** [Azure/azure-sdk-for-net#35397]
**Describe the bug**
Retrieving an `Azure.Search.Documents.Indexes.Models.SearchIndex` using `Azure.Search.Documents.Indexes.Models.SearchIndexClient.GetIndex(string indexName)` throws an exception during JSON deserialization when the index is created using an encryption key without `accessCredentials` set.

**Expected behavior**
According to [the official documentation](https://learn.microsoft.com/en-us/azure/search/search-security-manage-encryption-keys?tabs=portal-pp%2Cmanaged-id-sys), when using "System-managed identity", one should not set `accessCredentials` nor `identity` within the `encryptionKey` object passed in the JSON for creating a new index. Therefore, the corresponding JSON from this index creation should be able to be deserialized without an exception being thrown, as it is valid according to the official spec.

**Actual behavior (include Exception or Stack Trace)**
An exception is thrown during JSON deserialization after calling `Azure.Search.Documents.Indexes.Models.SearchIndexClient.GetIndex(string indexName)`.

A partial stack trace for this exception and other details are as follows:
```
Error message: The requested operation requires an element of type 'Object', but the target element has type 'Null'.
Source: System.Text.Json.Rethrowable
Target site: Void ThrowJsonElementWrongTypeException(System.Text.Json.JsonTokenType, System.Text.Json.JsonTokenType)
Stack Trace:
at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
at Azure.Search.Documents.Indexes.Models.AzureActiveDirectoryApplicationCredentials.DeserializeAzureActiveDirectoryApplicationCredentials(JsonElement element)
at Azure.Search.Documents.Indexes.Models.SearchResourceEncryptionKey.DeserializeSearchResourceEncryptionKey(JsonElement element)
at Azure.Search.Documents.Indexes.Models.SearchIndex.DeserializeSearchIndex(JsonElement element)
at Azure.Search.Documents.IndexesRestClient.Get(String indexName, CancellationToken cancellationToken)
at Azure.Search.Documents.Indexes.SearchIndexClient.GetIndex(String indexName, CancellationToken cancellationToken)
```

**To Reproduce**
Following steps outlined [here](https://learn.microsoft.com/en-us/azure/search/search-security-manage-encryption-keys?tabs=portal-pp%2Cmanaged-id-sys), create a new index using an encryption key relying on "System-managed identity", i.e without including `accessCredentials` or `identity`. Then, attempt to access this index using `Azure.Search.Documents.Indexes.Models.SearchIndexClient.GetIndex(string indexName)`.

**Environment:**

.NET SDK:
 Version:   7.0.102
 Commit:    4bbdd14480

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.14393
 OS Platform: Windows
 RID:         win10-x86
 Base Path:   C:\Program Files (x86)\dotnet\sdk\7.0.102\

Host:
  Version:      7.0.2
  Architecture: x86
  Commit:       d037e070eb

.NET SDKs installed:
  1.1.14 [C:\Program Files (x86)\dotnet\sdk]
  2.1.526 [C:\Program Files (x86)\dotnet\sdk]
  2.2.109 [C:\Program Files (x86)\dotnet\sdk]
  3.1.118 [C:\Program Files (x86)\dotnet\sdk]
  3.1.422 [C:\Program Files (x86)\dotnet\sdk]
  3.1.423 [C:\Program Files (x86)\dotnet\sdk]
  3.1.425 [C:\Program Files (x86)\dotnet\sdk]
  3.1.426 [C:\Program Files (x86)\dotnet\sdk]
  5.0.406 [C:\Program Files (x86)\dotnet\sdk]
  5.0.408 [C:\Program Files (x86)\dotnet\sdk]
  6.0.400 [C:\Program Files (x86)\dotnet\sdk]
  6.0.401 [C:\Program Files (x86)\dotnet\sdk]
  6.0.403 [C:\Program Files (x86)\dotnet\sdk]
  6.0.404 [C:\Program Files (x86)\dotnet\sdk]
  6.0.405 [C:\Program Files (x86)\dotnet\sdk]
  6.0.406 [C:\Program Files (x86)\dotnet\sdk]
  7.0.100 [C:\Program Files (x86)\dotnet\sdk]
  7.0.101 [C:\Program Files (x86)\dotnet\sdk]
  7.0.102 [C:\Program Files (x86)\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.All 2.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 6.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 1.0.16 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 1.1.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.0.9 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.1.30 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.0.3 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.32 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 5.0.17 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.13 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.14 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.1 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.2 [C:\Program Files (x86)\dotnet\shared\Microsoft.NETCore.App]

Other architectures found:
  x64   [C:\Program Files (x86)\dotnet]

Environment variables:
  Not set

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by annanakashimo** [comment]
Pertaining to possible workarounds: I attempted to utilize `accessCredentials`, going through the "Register an app" strategy presented [here](https://learn.microsoft.com/en-us/azure/search/search-security-manage-encryption-keys?tabs=portal-pp%2Cmanaged-id-sys). While the index creation did succeed and index retrieval (through `Azure.Search.Documents.Indexes.Models.SearchIndexClient.GetIndex(string indexName)`) could be performed successfully, the system now fails to retrieve synonym maps due to a similar issue: the stored `applicationSecret` within `accessCredentials` is `null` in the stored index JSON (despite being properly uploaded), and Azure throws an exception, expecting `applicationSecret` to never be `null`.

This could and probably should be a separate bug report, but I just want to clarify that this alternative solution also does not work. This leaves just "User-managed identity" as a possible solution. However, given that it is a brand new feature, I'm concerned that it also won't work, given that these more established features do not function currently. I will investigate and attempt to use this approach nonetheless, however.

**Comment by annanakashimo** [comment]
I was able to resolve the issue by updating Azure.Search.Documents (version=11.4.0) and Azure.Core (version=1.30.0) to the latest version. Our system was utilizing Azure.Search.Documents version=11.1.1 and Azure.Core version=1.21.0.
