### ISSUE TITLE
[BUG] The API version 2021-12-02 is not supported by Azurite

### ISSUE THREAD

**Issue by tnlthanzeel** [Azure/azure-sdk-for-net#35396]
### Library name and version

Azure.Storage.Blobs 12.15.1

### Describe the bug

I have update the my visual studio to the latest version yesterday and suddenly the method var `azResponse = await blobClient.DownloadToAsync(targetStream);` stopped working. 

i found  the below message in the exception

```
Azure.RequestFailedException
  HResult=0x80131500
  Message=The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 
RequestId:464b97a7-707a-4af6-8c25-8cce0e6b42f0
Time:2023-04-06T06:58:42.559Z
Status: 400 (The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. )
ErrorCode: InvalidHeaderValue

Headers:
Server: Azurite-Blob/3.20.1
x-ms-error-code: InvalidHeaderValue
x-ms-request-id: 464b97a7-707a-4af6-8c25-8cce0e6b42f0
Date: Thu, 06 Apr 2023 06:58:42 GMT
Connection: keep-alive
Keep-Alive: REDACTED
Transfer-Encoding: chunked
Content-Type: application/xml

  Source=Azure.Storage.Blobs
  StackTrace:
   at Azure.Storage.Blobs.BlobRestClient.<DownloadAsync>d__8.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StartDownloadAsync>d__66.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadStreamingInternal>d__65.MoveNext()
   at Azure.Storage.Blobs.PartitionedDownloader.<DownloadToAsync>d__9.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StagedDownloadAsync>d__94.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__92.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__84.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__80.MoveNext()
   at VPMS.FuncApp.Services.DocumentRespository.<DownloadDocument>d__3.MoveNext() in C:\Projects\vpms\vpms-legacy\VPMS.AzFunctionApps\VPMS.FuncApp\Services\DocumentRespository.cs:line 27

  This exception was originally thrown at this call stack:
    Azure.Storage.Blobs.BlobRestClient.DownloadAsync(string, string, int?, string, string, bool?, bool?, string, string, Azure.Storage.Blobs.Models.EncryptionAlgorithmTypeInternal?, System.DateTimeOffset?, System.DateTimeOffset?, string, string, string, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(Azure.HttpRange, Azure.Storage.Blobs.Models.BlobRequestConditions, Azure.Storage.DownloadTransferValidationOptions, long, bool, System.Threading.CancellationToken)
    System.Threading.Tasks.ValueTask<TResult>.Result.get()
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadStreamingInternal(Azure.HttpRange, Azure.Storage.Blobs.Models.BlobRequestConditions, Azure.Storage.DownloadTransferValidationOptions, System.IProgress<long>, string, bool, System.Threading.CancellationToken)
    Azure.Storage.Blobs.PartitionedDownloader.DownloadToAsync(System.IO.Stream, Azure.Storage.Blobs.Models.BlobRequestConditions, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.StagedDownloadAsync(System.IO.Stream, Azure.Storage.Blobs.Models.BlobRequestConditions, System.IProgress<long>, Azure.Storage.StorageTransferOptions, Azure.Storage.DownloadTransferValidationOptions, bool, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(System.IO.Stream, Azure.Storage.Blobs.Models.BlobRequestConditions, Azure.Storage.StorageTransferOptions, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(System.IO.Stream, System.Threading.CancellationToken)
    Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadToAsync(System.IO.Stream)
    VPMS.FuncApp.Services.DocumentRespository.DownloadDocument(string, string, System.IO.Stream) in DocumentRespository.cs
```

### Expected behavior

The stram must be downloaded

### Actual behavior

Throws error 

 HResult=0x80131500
  Message=The API version 2021-12-02 is not supported by Azurite. Please upgrade Azurite to latest version and retry. If you are using Azurite in Visual Studio, please check you have installed latest Visual Studio patch. Azurite command line parameter "--skipApiVersionCheck" or Visual Studio Code configuration "Skip Api Version Check" can skip this error. 

### Reproduction Steps

```
public async Task<ResponseResult<Stream>> DownloadDocument(string containerName, string blobName, Stream targetStream)
    {
        try
        {
            var blobContainerClient = GetContainerAsync(containerName);

            var blobClient = blobContainerClient.GetBlobClient(blobName);

            var azResponse = await blobClient.DownloadToAsync(targetStream);

            if (azResponse.IsError) return new(new OperationFailedException("blob", JsonConvert.SerializeObject(azResponse)));

            return new(targetStream);
        }


        catch (Exception ex)
        {
            return new(new OperationFailedException("Blob", JsonConvert.SerializeObject(ex)));
        }
    }
```

### Environment

visual studio enterprise: 17.5.3
azurite version: 3.20.1

**Comment by jsquire** [comment]
This issue has been transferred to the repository where Azureite is maintained as [#1897](https://github.com/Azure/Azurite/issues/1897).   As a workaround in the interim, it is recommended that you explicitly set the version that you'd like to use in the [BlobClientOptions](https://learn.microsoft.com/dotnet/api/azure.storage.blobs.blobclientoptions.-ctor?view=azure-dotnet) when constructing your `BlobClient`.
