### ISSUE TITLE
[BUG] The exception UriFormatException is thrown when receiving an HybridComputeMachineResource.

### ISSUE THREAD

**Issue by simonmen22** [Azure/azure-sdk-for-net#35402]
### Library name and version

Azure.ResourceManager.HybridCompute 1.0.0-beta.2

### Describe the bug

When I try to get an HybridComputeMachineResource from a ResourceGroupResource with GetHybridComputeMachine, the exception UriFormatException is thrown.

The origin of the problem comes from [DeserializeAgentConfiguration](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/hybridcompute/Azure.ResourceManager.HybridCompute/src/Generated/Models/AgentConfiguration.Serialization.cs#L17). It checks whenever proxyUrl is null, but does not check if it's an empty string, so when proxyUrl is empty, the exception is thrown. A quick fix would be to simply check if proxyUrl is empty and assign it to null if it is.

Here is the agentConfiguration of the machine with no proxyUrl:
```
 "agentConfiguration": {
            "proxyUrl": "",
            "incomingConnectionsPorts": [],
            "extensionsAllowList": [],
            "extensionsBlockList": [],
            "proxyBypass": [],
            "extensionsEnabled": "true",
            "guestConfigurationEnabled": "true",
            "configMode": "full"
        },
```

### Expected behavior

The HybridComputeMachineResource should be received.

### Actual behavior

The exception UriFormatException is thrown when an HybridComputeMachineResource is received : 

```
System.UriFormatException: Invalid URI: The URI is empty.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.HybridCompute.Models.AgentConfiguration.DeserializeAgentConfiguration(JsonElement element)
   at Azure.ResourceManager.HybridCompute.Models.MachineProperties.DeserializeMachineProperties(JsonElement element)
   at Azure.ResourceManager.HybridCompute.HybridComputeMachineData.DeserializeHybridComputeMachineData(JsonElement element)
   at Azure.ResourceManager.HybridCompute.MachinesRestOperations.Get(String subscriptionId, String resourceGroupName, String machineName, Nullable`1 expand, CancellationToken cancellationToken)
   at Azure.ResourceManager.HybridCompute.HybridComputeMachineCollection.Get(String machineName, Nullable`1 expand, CancellationToken cancellationToken)
   at Azure.ResourceManager.HybridCompute.HybridComputeExtensions.GetHybridComputeMachine(ResourceGroupResource resourceGroupResource, String machineName, Nullable`1 expand, CancellationToken cancellationToken)
```

### Reproduction Steps

Here is a small code snippet to reproduce the problem.

```
var armClient = new ArmClient(new DefaultAzureCredential());
var subscriptionResource = armClient.GetDefaultSubscription()
var resourceGroup = subscriptionResource.GetResourceGroup(ResourceGroupWithHybridComputeMachine);
var hybridComputeMachineResource = resourceGroup.Value.GetHybridComputeMachine(machineNameWithNoProxyUrl);
```

### Environment

dotnet Version: 6.0.405

**Comment by live1206** [comment]
@simonmen22 Fixed in [Azure.ResourceManager.HybridCompute/1.0.0-beta.3](https://www.nuget.org/packages/Azure.ResourceManager.HybridCompute/1.0.0-beta.3)
