### ISSUE TITLE
Invalid URI: The format of the URI could not be determined.

### ISSUE THREAD

**Issue by campionite** [Azure/azure-sdk-for-net#35526]
### Library name and version

Azure.ResourceManager.DataProtectionBackup 1.1.1

### Query/Question

The error originates from [DataSourceInfo.Serialization.cs](https://github.com/Azure/azure-sdk-for-net/blob/Azure.ResourceManager.DataProtectionBackup_1.1.1/sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Generated/Models/DataSourceInfo.Serialization.cs)(probably on Line#112 -
 `resourceUri = new Uri(property.Value.GetString());`)
Here is the code snippet that throws the exception - 
`

               var resourceId = DataProtectionBackupVaultResource.CreateResourceIdentifier(
                                _subscriptionId,
                                _resourceGroupName,
                                _vaultName);
                var resource =
                    _armClient.GetDataProtectionBackupVaultResource(resourceId
                        );

                var backupVault = await resource.GetAsync();

                var backupInstancesCollection = backupVault.Value.GetDataProtectionBackupInstances().GetAllAsync();
`

Here is another code snippet that throws the same exception.
`

                 var resourceId = DataProtectionBackupInstanceResource.CreateResourceIdentifier(
                                _subscriptionId,
                                _resourceGroupName,
                                _vaultName,
                                _backupInstanceName);
                var resource =
                    _armClient.GetDataProtectionBackupInstanceResource(resourceId
                        );
               
                var backupInstance = await resource.GetAsync();

`
Both the snippets provided are trying to get a BackupInstanceResource object

Based on my research, the resourceUri property that gets returned in the REST api call is not a valid Uri. In the Azure portal it shows up like this. _Added placeholders to show some confidential Ids_.
`"resourceUri": "/subscriptions/{subscriptionId}/resourceGroups/myRg/providers/Microsoft.Storage/storageAccounts/samplestorageaccount"`

### Environment

Microsoft Visual Studio Enterprise 2022 (64-bit) - Current
Version 17.2.5

![image](https://user-images.githubusercontent.com/8433828/231568900-4c0ccdbe-37b9-483a-abc6-0588176ccd8a.png)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by campionite** [comment]
Please see the stack trace of the exception - 
`
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.DataProtectionBackup.Models.DataSourceInfo.DeserializeDataSourceInfo(JsonElement element)
   at Azure.ResourceManager.DataProtectionBackup.Models.DataProtectionBackupInstanceProperties.DeserializeDataProtectionBackupInstanceProperties(JsonElement element)
   at Azure.ResourceManager.DataProtectionBackup.DataProtectionBackupInstanceData.DeserializeDataProtectionBackupInstanceData(JsonElement element)
   at Azure.ResourceManager.DataProtectionBackup.BackupInstancesRestOperations.<GetAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable 1.ConfiguredTaskAwaiter.GetResult()
   at Azure.ResourceManager.DataProtectionBackup.DataProtectionBackupInstanceResource.<GetAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter 1.GetResult()
   at AzureBlobStorageDemo.Tests.AzureBlobStorageDemoTests.<BackupInstanceNotNull>d__14.MoveNext() in C:\repos\version3\AzureBlobStorageDemo\AzureBlobStorageDemo.Tests\AzureBlobStorageDemoTests.cs:line 181
`

**Comment by HarveyLink** [comment]
Hi @campionite , thank you for the feedback.
We'll apply a hotfix for this issue.

**Comment by HarveyLink** [comment]
[Azure.ResourceManager.DataProtectionBackup](https://www.nuget.org/packages/Azure.ResourceManager.DataProtectionBackup) new package released.
