### ISSUE TITLE
[QUERY] What is the configuration structure for configuring the `OpenAIClient`?

### ISSUE THREAD

**Issue by Swimburger** [Azure/azure-sdk-for-net#35962]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.5

### Query/Question

I'm currently configuring the OpenAIClient by registering it into DI like this:

```csharp
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder.AddOpenAIClient(
        new Uri(builder.Configuration["Azure:OpenAI:Endpoint"]),
        new AzureKeyCredential(builder.Configuration["Azure:OpenAI:ApiKey"])
    );
});
```

I know there's also an overload to pass in configuration like this:

```csharp
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder.AddOpenAIClient(builder.Configuration.GetSection("Azure:OpenAI"));
});
```

But I don't know how to configure the `Endpoint` and `ApiKey` with this overload. 
So what should my configuration structure look like to configure it like the first sample?

Ideally, this would work with .NET's autoreloading configuration, so I can swap API keys without having to restart my application.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by IEvangelist** [comment]
After looking a bit at this @Swimburger - there are some folks speculating that if you were to configure a section like this:

```json
{
  "Azure": {
    "OpenAI": {
      "Endpoint": "< your endpoint >",
      "Crendtial": "< your credential >"
    }
  }
}
```

And then get the section by its name:

```cs
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder.AddOpenAIClient(
        builder.Configuration.GetSection("Azure:OpenAI"));

    // This section would be the following values:
    // {
    //  "Endpoint": "< your endpoint >",
    //  "Crendtial": "< your credential >"
    // }
});
```

Notice that the property names match the parameter names of the corresponding parameterized call, I wonder if that's how it maps? 

```cs
builder.Services.AddAzureClients(clientBuilder =>
{
    clientBuilder.AddOpenAIClient(
        endpoint: new Uri(builder.Configuration["Azure:OpenAI:Endpoint"]),
        credential: new AzureKeyCredential(builder.Configuration["Azure:OpenAI:ApiKey"])
    );
});
```

Also, see here, as a somewhat related sample: https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection#configure-a-new-retry-policy

**Comment by Swimburger** [comment]
Doing that I get the following error when making the API calls:

```
Azure.RequestFailedException: Principal does not have access to API/Operation.
      Status: 401 (PermissionDenied)
      ErrorCode: PermissionDenied

      Content:
      {"error":{"code":"PermissionDenied","message": "Principal does not have access to API/Operation."}}
```

**Comment by joseharriaga** [comment]
Hello, @Swimburger. If you're getting that error, it sounds to me like the endpoint was passed down correctly, but the API key wasn't (otherwise I would expect a different error, e.g. a 404 Not Found).

Here are two ideas to try:
1. I see that in @IEvangelist's example there's a typo in "Crendtial". Could you fix the typo and try again?
2. Alternatively, looking at the [OpenAIClient constructor](https://github.com/Azure/azure-sdk-for-net/blob/09d945f5647a9116aaed0bd01f80adecf2220115/sdk/openai/Azure.AI.OpenAI/src/Custom/OpenAIClient.cs#L50), I see that the parameter is called "keyCredential". Could you try calling it that in your configuration file instead of calling it "Credential" and try again?

**Comment by Swimburger** [comment]
I noticed the typo and corrected it in my code, but no luck. `keyCredential` and `KeyCredential` don't work either.

Same error, but I also found these additional logs.
```
fail: Azure.Identity[10]
      False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.22621 [05/09 16:11:10.59 - 79ca63d8-8102-4555-8f62-ae854d3caab8] Exception type: Microsoft.Identity.Client.MsalUiRequiredExc
eption
      , ErrorCode: invalid_grant
      HTTP StatusCode 400
      CorrelationId 79ca63d8-8102-4555-8f62-ae854d3caab8

fail: Azure.Identity[10]
      False MSAL 4.39.0.0 MSAL.NetCore .NET 7.0.5 Microsoft Windows 10.0.22621 [05/09 16:11:10.60 - 79ca63d8-8102-4555-8f62-ae854d3caab8] Exception type: Microsoft.Identity.Client.MsalUiRequiredExc
eption
      , ErrorCode: invalid_grant
      HTTP StatusCode 400
      CorrelationId 79ca63d8-8102-4555-8f62-ae854d3caab8

         at Microsoft.Identity.Client.OAuth2.OAuth2Client.ThrowServerException(HttpResponse response, RequestContext requestContext)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.CreateResponse[T](HttpResponse response, RequestContext requestContext)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.ExecuteRequestAsync[T](Uri endPoint, HttpMethod method, RequestContext requestContext, Boolean expectErrorsOn200OK, Boolean addCommonHeader
s)
         at Microsoft.Identity.Client.OAuth2.OAuth2Client.GetTokenAsync(Uri endPoint, RequestContext requestContext, Boolean addCommonHeaders)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendHttpAndClearTelemetryAsync(String tokenEndpoint, ICoreLogger logger)
         at Microsoft.Identity.Client.OAuth2.TokenClient.SendTokenRequestAsync(IDictionary`2 additionalBodyParameters, String scopeOverride, String tokenEndpointOverride, CancellationToken cancella
tionToken)
         at Microsoft.Identity.Client.Internal.Requests.ByRefreshTokenRequest.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
info: Azure.Identity[3]
      VisualStudioCodeCredential.GetToken was unable to retrieve an access token. Scopes: [ https://cognitiveservices.azure.com/.default ] ParentRequestId: ecca2bf3-5bc9-4113-9981-86f5553230a4 Exce
ption: Azure.Identity.CredentialUnavailableException (0x80131500): VisualStudioCodeCredential authentication unavailable. Token acquisition failed. Ensure that you have authenticated in VSCode Azur
e Account. See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/vscodecredential/troubleshoot
       ---> Microsoft.Identity.Client.MsalUiRequiredException (0x80131500): AADSTS700082: The refresh token has expired due to inactivity. The token was issued on 2022-01-10T00:35:27.8835132Z and w
as inactive for 90.00:00:00.
      Trace ID: da974c39-7834-4981-8fdd-984b2a9f2200
      Correlation ID: 79ca63d8-8102-4555-8f62-ae854d3caab8
      Timestamp: 2023-05-09 16:11:10Z

```

**Comment by joseharriaga** [comment]
Looping in the OpenAI team - /cc: @jpalvarezl, @trrwilson

**Comment by sjkp** [comment]
Doesnt seem like that overload works unless you have already registered the OpenAIClient with your DI container 
````
 public static class AzureOpenAIClientBuilderExtensions
  {
    /// <summary> Registers a <see cref="T:Azure.AI.OpenAI.OpenAIClient" /> instance. </summary>
    /// <param name="builder"> The builder to register with. </param>
    /// <param name="endpoint">
    /// Supported Cognitive Services endpoints (protocol and hostname, for example:
    /// https://westus.api.cognitive.microsoft.com).
    /// </param>
    /// <param name="credential"> A credential used to authenticate to an Azure Service. </param>
    public static IAzureClientBuilder<OpenAIClient, OpenAIClientOptions> AddOpenAIClient<TBuilder>(this TBuilder builder, Uri endpoint, AzureKeyCredential credential) where TBuilder : IAzureClientFactoryBuilder
    {
      return builder.RegisterClientFactory<OpenAIClient, OpenAIClientOptions>((Func<OpenAIClientOptions, OpenAIClient>) (options => new OpenAIClient(endpoint, credential, options)));
    }

    /// <summary> Registers a <see cref="T:Azure.AI.OpenAI.OpenAIClient" /> instance. </summary>
    /// <param name="builder"> The builder to register with. </param>
    /// <param name="endpoint">
    /// Supported Cognitive Services endpoints (protocol and hostname, for example:
    /// https://westus.api.cognitive.microsoft.com).
    /// </param>
    public static IAzureClientBuilder<OpenAIClient, OpenAIClientOptions> AddOpenAIClient<TBuilder>(this TBuilder builder, Uri endpoint) where TBuilder : IAzureClientFactoryBuilderWithCredential
    {
      return builder.RegisterClientFactory<OpenAIClient, OpenAIClientOptions>((Func<OpenAIClientOptions, TokenCredential, OpenAIClient>) ((options, cred) => new OpenAIClient(endpoint, cred, options)), true);
    }

    /// <summary> Registers a <see cref="T:Azure.AI.OpenAI.OpenAIClient" /> instance. </summary>
    /// <param name="builder"> The builder to register with. </param>
    /// <param name="configuration"> The configuration values. </param>
    public static IAzureClientBuilder<OpenAIClient, OpenAIClientOptions> AddOpenAIClient<TBuilder, TConfiguration>(this TBuilder builder, TConfiguration configuration) where TBuilder : IAzureClientFactoryBuilderWithConfiguration<TConfiguration>
    {
      return builder.RegisterClientFactory<OpenAIClient, OpenAIClientOptions>(configuration);
    }
  }

```
