### ISSUE TITLE
JsonReaderException when invoking AutomationCertificateCollection.CreateOrUpdateAsync to create a new certificate

### ISSUE THREAD

**Issue by davecader** [Azure/azure-sdk-for-net#36295]
### Library name and version

Azure.ResourceManager.Automation 1.0.1

### Describe the bug

We are consistently observing as JsonReaderException when invoking AutomationCertificateCollection.CreateOrUpdateAsync to create a new certificate in Azure Automation. The error message is "'A' is an invalid end of a number. Expected a delimiter. LineNumber: 0 | BytePositionInLine: 8.".

Stack Trace:

   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.TryGetNumber(ReadOnlySpan`1 data, Int32& consumed)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, Utf8JsonReader reader, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedBytes)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 json, JsonDocumentOptions options)
   at System.Text.Json.JsonDocument.Parse(String json, JsonDocumentOptions options)
   at Azure.ResourceManager.Automation.Models.AutomationCertificateCreateOrUpdateContent.Azure.Core.IUtf8JsonSerializable.Write(Utf8JsonWriter writer)
   at Azure.Core.Utf8JsonWriterExtensions.WriteObjectValue(Utf8JsonWriter writer, Object value)
   at Azure.ResourceManager.Automation.CertificateRestOperations.CreateCreateOrUpdateRequest(String subscriptionId, String resourceGroupName, String automationAccountName, String certificateName, AutomationCertificateCreateOrUpdateContent content)
   at Azure.ResourceManager.Automation.CertificateRestOperations.<CreateOrUpdateAsync>d__12.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.ResourceManager.Automation.AutomationCertificateCollection.<CreateOrUpdateAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Kelverion.RunbookStudio.Cloud.Core.AutomationCertificateCollectionClient.<CreateCore>d__2.MoveNext() in C:\Users\DavidCader\source\repos\app-automation-console\Src\Kelverion.RunbookStudio.Cloud\Core\AutomationCertificateCollectionClient.cs:line 36
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Kelverion.RunbookStudio.Cloud.Core.AutomationCollectionClientBase`1.<Create>d__9.MoveNext() in C:\Users\DavidCader\source\repos\app-automation-console\Src\Kelverion.RunbookStudio.Cloud\Core\AutomationCollectionClientBase.cs:line 58

### Expected behavior

The certificate should be create successfully

### Actual behavior

A JsonReaderException is invariably observered.

### Reproduction Steps

public async Task CreateOrUpdate_CreateOrUpdateACertificate()
        {
            // Generated from example definition: specification/automation/resource-manager/Microsoft.Automation/preview/2020-01-13-preview/examples/createOrUpdateCertificate.json
            // this example is just showing the usage of "Certificate_CreateOrUpdate" operation, for the dependent resources, they will have to be created separately.

            // get your azure access token, for more details of how Azure SDK get your access token, please refer to https://learn.microsoft.com/en-us/dotnet/azure/sdk/authentication?tabs=command-line
            TokenCredential cred = new DefaultAzureCredential();
            // authenticate your client
            ArmClient client = new ArmClient(cred);

            // this example assumes you already have this AutomationAccountResource created on azure
            // for more information of creating AutomationAccountResource, please refer to the document of AutomationAccountResource
            string subscriptionId = "subid";
            string resourceGroupName = "rg";
            string automationAccountName = "myAutomationAccount18";
            ResourceIdentifier automationAccountResourceId = AutomationAccountResource.CreateResourceIdentifier(subscriptionId, resourceGroupName, automationAccountName);
            AutomationAccountResource automationAccount = client.GetAutomationAccountResource(automationAccountResourceId);

            // get the collection of this AutomationCertificateResource
            AutomationCertificateCollection collection = automationAccount.GetAutomationCertificates();

            // invoke the operation
            string certificateName = "testCert";
            AutomationCertificateCreateOrUpdateContent content = new AutomationCertificateCreateOrUpdateContent("testCert", "base 64 value of cert")
            {
                Description = "Sample Cert",
                Thumbprint = BinaryData.FromString("thumbprint of cert"),
                IsExportable = false,
            };
            ArmOperation<AutomationCertificateResource> lro = await collection.CreateOrUpdateAsync(WaitUntil.Completed, certificateName, content);
            AutomationCertificateResource result = lro.Value;

            // the variable result is a resource, you could call other operations on this instance as well
            // but just for demo, we get its data from this resource instance
            AutomationCertificateData resourceData = result.Data;
            // for demo we just print out the id
            Console.WriteLine($"Succeeded on id: {resourceData.Id}");
        }

### Environment

Windows 10
.NET Framework 4.8.1
Visual Studio 17.4.4

**Comment by m-redding** [comment]
Thank you for your feedback. Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @davecader , Thank you for using Azure SDK for .NET.
I think your issues is reported from 
`Thumbprint = BinaryData.FromString("thumbprint of cert"),`
Please check the comments of [this property](https://github.com/Azure/azure-sdk-for-net/blob/35863b12c2ac57911bf661ee8630852bb4727af2/sdk/automation/Azure.ResourceManager.Automation/src/Generated/Models/AutomationCertificateCreateOrUpdateContent.cs#L51),  make sure you have the added extra `\"\"` outside your thumbprint string

**Comment by davecader** [comment]
I have tested your suggestion and it appears to work. I appreciate the quick response, but this SDK could really benefit from some proper documentation. Too much trial and error to get anything to work.
