### ISSUE TITLE
[BUG] WaitForCompletionAsync on TriggerRestoreAsync throws a FormatException.

### ISSUE THREAD

**Issue by campionite** [Azure/azure-sdk-for-net#36360]
### Library name and version

Azure.ResourceManager.DataProtectionBackup 1.1.2

### Describe the bug

Here is a code snippet that throws System.FormatException. Based on my research, the DataProtectionOperationJobExtendedInfo.DeserializeDataProtectionOperationJobExtendedInfo() method is not able to deserialize the jobId property. It is most likely failing on [Line#32 in DataProtectionOperationJobExtendedInfo.Serialization.cs](https://github.com/Azure/azure-sdk-for-net/blob/35863b12c2ac57911bf661ee8630852bb4727af2/sdk/dataprotection/Azure.ResourceManager.DataProtectionBackup/src/Generated/Models/DataProtectionOperationJobExtendedInfo.Serialization.cs#L32)
`jobId = property.Value.GetGuid();`
The jobId property is not coming back as a true guid. Instead the value of jobId is something like this - _"/subscriptions/{subId}/resourcegroups/{rgName}/providers/Microsoft.DataProtection/BackupVaults/{vaultName}/backupJobs/5b005931-cfdc-4f08-9865-52ca5ff257d6"_

`

         try
            {

                SubscriptionResource sub = await _armClient.GetDefaultSubscriptionAsync();
                var resourceGroup = (await sub.GetResourceGroups().GetAsync(_resourceGroupName)).Value;
                var vault = (await resourceGroup.GetDataProtectionBackupVaults().GetAsync(_vaultName)).Value;
                var name = "";
                await foreach (var item in vault.GetDataProtectionBackupInstances().GetAllAsync())
                {
                    Console.WriteLine(item.Id);
                    name = item.Data.Name;
                }
                var instance = (await vault.GetDataProtectionBackupInstances().GetAsync(name)).Value;
                DataSourceInfo dataSourceInfo = instance.Data.Properties.DataSourceInfo;
                RecoverySetting recoverySetting = new RecoverySetting("FailIfExists");
                IEnumerable<ItemLevelRestoreCriteria> restoreCriteria = new List<ItemLevelRestoreCriteria>
            {
                new RangeBasedItemLevelRestoreCriteria
                {
                    MinMatchingValue = "container-067f6afb4-2433-4da8-a882-50008ec236a9",
                    MaxMatchingValue = "container-067f6afb4-2433-4da8-a882-50008ec236a9-0"
                }
            };
                RestoreTargetInfoBase restoreTarget = new ItemLevelRestoreTargetInfo(recoverySetting, restoreCriteria, dataSourceInfo);
                SourceDataStoreType sourceDataStoreType = SourceDataStoreType.OperationalStore;
                var recoverOn = new DateTimeOffset(new DateTime(2023, 5, 18, 1, 27, 13, DateTimeKind.Utc));
                BackupRestoreContent backupRestoreContent = new BackupRecoveryTimeBasedRestoreContent(restoreTarget, sourceDataStoreType, recoverOn);
                BackupValidateRestoreContent backupValidateRestoreContent = new BackupValidateRestoreContent(backupRestoreContent);
                var backupInstance = await instance.GetAsync();
                var backupInstancetData = backupInstance.Value.Data;
                var operation = await backupInstance.Value.TriggerRestoreAsync(WaitUntil.Started, backupRestoreContent);
                var operationStatus = await operation.WaitForCompletionAsync(); //Line#448
            }
            catch (FormatException ex)
            {
                throw;
            }
            catch (Exception ex)
            {

                throw;
            }

`

Stack trace - 
`System.FormatException
  HResult=0x80131537
  Message=One of the identified items was in an invalid format.
  Source=Azure.ResourceManager.DataProtectionBackup
  StackTrace:
   at Azure.ResourceManager.DataProtectionBackup.Models.DataProtectionOperationJobExtendedInfo.DeserializeDataProtectionOperationJobExtendedInfo(JsonElement element)
   at Azure.ResourceManager.DataProtectionBackup.DataProtectionOperationJobExtendedInfoOperationSource.<Azure-Core-IOperationSource<Azure-ResourceManager-DataProtectionBackup-Models-DataProtectionOperationJobExtendedInfo>-CreateResultAsync>d__1.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.NextLinkOperationImplementation.OperationToOperationOfT`1.<UpdateStateAsync>d__3.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.OperationInternalBase.<UpdateStatusAsync>d__13.MoveNext()
   at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__15.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   at AzureBlobStorageDemo.Tests.AzureBlobStorageDemoTests.<TriggerRestore_new>d__18.MoveNext() in C:\repos\version3\azure-blobstorage-recovery-demo\azure-blobstorage-recovery-demo\AzureBlobStorageDemo.Tests\AzureBlobStorageDemoTests.cs:line 448`

### Expected behavior

The WaitForCompletionAsync should not throw System.FormatException exception.

### Actual behavior

The method WaitForCompletionAsync throws the following exception -
System.FormatException : One of the identified items was in an invalid format.

### Reproduction Steps

Run the code snippet attached in the description.

### Environment

![image](https://github.com/Azure/azure-sdk-for-net/assets/8433828/bd298493-41e1-4a1c-a3f7-0e9d8693f714)

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by campionite** [comment]
@ArthurMa1978  - Could you please provide an update on this issue. Is this being investigated?

**Comment by HarveyLink** [comment]
Fixed with PR: #36901 , will apply the fix in the next release.
