### ISSUE TITLE
Fluent: NullReferenceException in VirtualMachineScaleSetImpl.LoadCurrentPrimaryLoadBalancersIfAvailable

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3659]
I'm hitting an NRE in Fluent SDK 1.1.3. The scenario involves creating a VMSS with an internal load balancer only (no public facing load balancer), and then trying to update it with a custom script extension

                vmssWithLB = vmssWithVNet
                    .WithoutPrimaryInternetFacingLoadBalancer()
                    .WithExistingPrimaryInternalLoadBalancer(loadBalancer)
                    .WithPrimaryInternalLoadBalancerBackends(LoadBalancerResource.BackendName)
                    .WithPrimaryInternalLoadBalancerInboundNatPools(
                        LoadBalancerResource.NatPool130XXName,
                        LoadBalancerResource.NatPool150XXName,
                        LoadBalancerResource.NatPool160XXName,
                        LoadBalancerResource.NatPool330XXName);
```
vmss.Update().DefineNewExtension(extensionName)
                            .WithPublisher("Microsoft.Compute")
                            .WithType("CustomScriptExtension")
                            .WithVersion("1.8")
                            .WithPublicSetting("fileUris", new string[] { scriptBlobSasUri.AbsoluteUri })
                            .WithProtectedSetting("storageAccountName", tenantStorage.AccountName)
                            .WithProtectedSetting("storageAccountKey", tenantStorage.GetSecretKey())
                            .WithProtectedSetting("commandToExecute", commandToExecute)
                            .Attach().ApplyAsync();
```
Here is the stack trace:

```Exception in context VmScaleSetResource:wus943843. Details: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetImpl.LoadCurrentPrimaryLoadBalancersIfAvailable()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetImpl.SetPrimaryIPConfigurationBackendsAndInboundNatPools()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetImpl.<CreateInnerAsync>d__290.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableParentResource`8.<CreateResourceAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.CreatableUpdatable`5.<ApplyAsync>d__3.MoveNext()```

**Comment by TimLovellSmith** [comment]
I am not sure what exactly is null. I do wonder if perhaps GetById using NetworkManager is returning null...

**Comment by TimLovellSmith** [comment]
Confirmed that this issue still exists in 1.2.0 too.

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#44
