### ISSUE TITLE
[BUG] The environment variable MSI_ENDPOINT contains an invalid Uri.

### ISSUE THREAD

**Issue by gritradir** [Azure/azure-sdk-for-net#36615]
### Library name and version

Azure.Identity 1.8.2
Azure.Security.KeyVault.Certificates 4.5.1
Azure.Security.KeyVault.Secrets 4.5.0

### Describe the bug

Trying to reach _Key Vault_ from _App Service_
Getting the following error when trying to get the certificate on startup

```
Azure.Identity.AuthenticationFailedException: The environment variable MSI_ENDPOINT contains an invalid Uri.
 ---> System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.Identity.AppServiceManagedIdentitySource.TryValidateEnvVars(String msiEndpoint, String secret, Uri& endpointUri)
```

Have managed identity enabled for both slots in App Service. Both slots have policy on Key Vault configured for all actions.
The error happens on this call `await certificateClient.DownloadCertificateAsync(certificateName)` (Azure.Security.KeyVault.Certificates 4.5.1)

This works on my local with DefaultIdentityProvider, trying to use managed identity, both are failing

```
var keyVaultUrl = "<keyvault url>";
var certificateName = "<cert name>";

var credential = new ManagedIdentityCredential();
var certificateClient = new CertificateClient(new Uri(keyVaultUrl), credential);
var certificate = await certificateClient.DownloadCertificateAsync(certificateName);
```

The app is in .net 6.

### Expected behavior

Managed Identity is configured properly and is reaching Key Vault successfully

### Actual behavior

`Azure.Identity.AuthenticationFailedException` Exception is thrown

### Reproduction Steps

var keyVaultUrl = "<keyvault url>";
var certificateName = "<cert name>";

var credential = new ManagedIdentityCredential();
var certificateClient = new CertificateClient(new Uri(keyVaultUrl), credential);
var certificate = await certificateClient.DownloadCertificateAsync(certificateName);

### Environment

.NET 6
AppService on linux

**Comment by gritradir** [comment]
Pipeline issues
