### ISSUE TITLE
[BUG] Tags related test cases on Compute is failing

### ISSUE THREAD

**Issue by ArcturusZhang** [Azure/azure-sdk-for-net#36714]
### Library name and version

Azure.ResourceManager.Compute

### Describe the bug

The tag related tests added by [this PR](https://github.com/Azure/azure-sdk-for-net/pull/36232) is failing: https://github.com/Azure/azure-sdk-for-net/pull/36711/checks?check_run_id=13886786314
Need to figure out why and fix.

### Expected behavior

They do not fail

### Actual behavior

They fail

### Reproduction Steps

See the build log here: https://github.com/Azure/azure-sdk-for-net/pull/36711/checks?check_run_id=13886786314

**Comment by HarveyLink** [comment]
Closed as fixed.

**Comment by ArcturusZhang** [comment]
Reopen this issue because in some cases they still fail.
Stack trace when it fails:
```
2025-01-05T05:39:16.8744042Z   Failed SetTags(null) [127 ms]
2025-01-05T05:39:16.8744450Z   Error Message:
2025-01-05T05:39:16.8744949Z    System.ArgumentException : Invalid resource type Microsoft.Compute/diskAccesses expected Microsoft.Resources/tags
2025-01-05T05:39:16.8745445Z Parameter name: id
2025-01-05T05:39:16.8747158Z   Stack Trace:
2025-01-05T05:39:16.8747871Z      at Azure.ResourceManager.Resources.TagResource.ValidateResourceId(ResourceIdentifier id) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs:line 87
2025-01-05T05:39:16.8748641Z    at Azure.ResourceManager.Resources.TagResource..ctor(ArmClient client, ResourceIdentifier id) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs:line 64
2025-01-05T05:39:16.8749362Z    at Azure.ResourceManager.Resources.TagResource..ctor(ArmClient client, TagResourceData data) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs:line 49
2025-01-05T05:39:16.8750649Z    at Azure.ResourceManager.Resources.TagResourceOperationSource.Azure.Core.IOperationSource<Azure.ResourceManager.Resources.TagResource>.CreateResult(Response response, CancellationToken cancellationToken) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/LongRunningOperation/TagResourceOperationSource.cs:line 28
2025-01-05T05:39:16.8751587Z    at Azure.Core.NextLinkOperationImplementation.OperationToOperationOfT`1.<UpdateStateAsync>d__3.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs:line 674
2025-01-05T05:39:16.8752532Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8753062Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8753541Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8754003Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8754554Z    at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 273
2025-01-05T05:39:16.8755360Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8755987Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8756549Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8757082Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8757671Z    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
2025-01-05T05:39:16.8758601Z    at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 105
2025-01-05T05:39:16.8759312Z    at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 83
2025-01-05T05:39:16.8760110Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8760703Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8761275Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8761827Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8762383Z    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
2025-01-05T05:39:16.8763085Z    at Azure.Core.OperationPoller.WaitForCompletionResponse(OperationInternalBase operation, Nullable`1 delayHint, CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 35
2025-01-05T05:39:16.8763823Z    at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 212
2025-01-05T05:39:16.8764585Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8765124Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8766438Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8766990Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8767775Z    at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 237
2025-01-05T05:39:16.8768708Z --- En  Passed SendEmailAndWaitForStatusWithAutomaticPollingAsync(False,True,False) [22 ms]
2025-01-05T05:39:16.8769404Z d of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8770033Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8770731Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8771500Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8772122Z    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
2025-01-05T05:39:16.8772902Z    at Azure.Core.OperationInternal`1.WaitForCompletion(CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 215
2025-01-05T05:39:16.8773835Z    at Azure.ResourceManager.Resources.ResourcesArmOperation`1.WaitForCompletion(CancellationToken cancellationToken) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/LongRunningOperation/ResourcesArmOperationOfT.cs:line 89
2025-01-05T05:39:16.8774929Z    at Azure.ResourceManager.Resources.TagResource.CreateOrUpdate(WaitUntil waitUntil, TagResourceData data, CancellationToken cancellationToken) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs:line 433
2025-01-05T05:39:16.8775803Z    at Azure.ResourceManager.Compute.DiskAccessResource.SetTags(IDictionary`2 tags, CancellationToken cancellationToken) in /_/sdk/compute/Azure.ResourceManager.Compute/src/Generated/DiskAccessResource.cs:line 711
2025-01-05T05:39:16.8777171Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8778019Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8778835Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8779398Z    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2025-01-05T05:39:16.8780265Z    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 123
2025-01-05T05:39:16.8781302Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8781987Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8782666Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8783282Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8784091Z    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass6_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 174
2025-01-05T05:39:16.8785350Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8786098Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8787024Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8788268Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8789044Z    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<ValidateDiagnosticScope>d__7`1.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 220
2025-01-05T05:39:16.8790610Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8791140Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8791644Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8792118Z    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2025-01-05T05:39:16.8792651Z    at Azure.ResourceManager.Compute.Tests.DiskAccessOperationsTests.<SetTags>d__4.MoveNext() in D:\a\_work\1\s\sdk\compute\Azure.ResourceManager.Compute\tests\Scenario\DiskAccessOperationsTests.cs:line 60
2025-01-05T05:39:16.8793414Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8794013Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8794615Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8795205Z    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2025-01-05T05:39:16.8796354Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
2025-01-05T05:39:16.8797060Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2025-01-05T05:39:16.8797615Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
2025-01-05T05:39:16.8798104Z    at NUnit.Fra  Passed SendEmailAndWaitForStatusWithAutomaticPollingAsync(False,False,True) [26 ms]
2025-01-05T05:39:16.8798535Z   Passed SendEmailAndWaitForStatusWithAutomaticPollingAsync(False,True,True) [18 ms]
2025-01-05T05:39:16.8798973Z   Passed SendEmailAndWaitForStatusWithAutomaticPollingAsync(True,False,True) [22 ms]
2025-01-05T05:39:16.8799405Z mework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2025-01-05T05:39:16.8799886Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
2025-01-05T05:39:16.8800390Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
2025-01-05T05:39:16.8800662Z 
2025-01-05T05:39:16.8801239Z   Passed SendEmailAndWaitForStatusWithAutomaticPollingAsync(True,True,False) [16 ms]
2025-01-05T05:39:16.8801931Z   Passed SendEmailAndWaitForStatusWithAutomaticPollingAsync(True,True,True) [16 ms]
2025-01-05T05:39:16.8802525Z   Passed BadRequest_ThrowsException [38 ms]
2025-01-05T05:39:16.8802941Z   Passed Constructor_InvalidParamsThrows [1 ms]
2025-01-05T05:39:16.8803322Z   Failed SetTags(True) [31 ms]
2025-01-05T05:39:16.8803675Z   Error Message:
2025-01-05T05:39:16.8804111Z    System.ArgumentException : Invalid resource type Microsoft.Compute/diskAccesses expected Microsoft.Resources/tags
2025-01-05T05:39:16.8804498Z Parameter name: id
2025-01-05T05:39:16.8804846Z   Stack Trace:
2025-01-05T05:39:16.8805351Z      at Azure.ResourceManager.Resources.TagResource.ValidateResourceId(ResourceIdentifier id) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs:line 87
2025-01-05T05:39:16.8805925Z    at Azure.ResourceManager.Resources.TagResource..ctor(ArmClient client, ResourceIdentifier id) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs:line 64
2025-01-05T05:39:16.8806510Z    at Azure.ResourceManager.Resources.TagResource..ctor(ArmClient client, TagResourceData data) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs:line 49
2025-01-05T05:39:16.8807164Z    at Azure.ResourceManager.Resources.TagResourceOperationSource.Azure.Core.IOperationSource<Azure.ResourceManager.Resources.TagResource>.CreateResult(Response response, CancellationToken cancellationToken) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/LongRunningOperation/TagResourceOperationSource.cs:line 28
2025-01-05T05:39:16.8808829Z    at Azure.Core.NextLinkOperationImplementation.OperationToOperationOfT`1.<UpdateStateAsync>d__3.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/NextLinkOperationImplementation.cs:line 674
2025-01-05T05:39:16.8810054Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8810710Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8811255Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8811747Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8812280Z    at Azure.Core.OperationInternal`1.<UpdateStatusAsync>d__20.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 273
2025-01-05T05:39:16.8812975Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8813483Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8813997Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8814479Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8815008Z    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
2025-01-05T05:39:16.8815709Z    at Azure.Core.OperationInternalBase.UpdateStatus(CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 105
2025-01-05T05:39:16.8816394Z    at Azure.Core.OperationPoller.<WaitForCompletionAsync>d__11.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 83
2025-01-05T05:39:16.8817071Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8817570Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8818079Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8818579Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8819115Z    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
2025-01-05T05:39:16.8819963Z    at Azure.Core.OperationPoller.WaitForCompletionResponse(OperationInternalBase operation, Nullable`1 delayHint, CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationPoller.cs:line 35
2025-01-05T05:39:16.8821193Z    at Azure.Core.OperationInternalBase.<WaitForCompletionResponseAsync>d__19.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/OperationInternalBase.cs:line 212
2025-01-05T05:39:16.8822735Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8823767Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8824367Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8824897Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8825717Z    at Azure.Core.OperationInternal`1.<WaitForCompletionAsync>d__19.MoveNext() in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 237
2025-01-05T05:39:16.8826544Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8827122Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8827695Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8828421Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8829504Z    at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task) in /_/sdk/core/Azure.Core/src/Shared/TaskExtensions.cs:line 53
2025-01-05T05:39:16.8831992Z    at Azure.Core.OperationInternal`1.WaitForCompletion(CancellationToken cancellationToken) in /_/sdk/core/Azure.Core/src/Shared/OperationInternalOfT.cs:line 215
2025-01-05T05:39:16.8833908Z    at Azure.ResourceManager.Resources.ResourcesArmOperation`1.WaitForCompletion(CancellationToken cancellationToken) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/LongRunningOperation/ResourcesArmOperationOfT.cs:line 89
2025-01-05T05:39:16.8835134Z    at Azure.ResourceManager.Resources.TagResource.CreateOrUpdate(WaitUntil waitUntil, TagResourceData data, CancellationToken cancellationToken) in /_/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs:line 433
2025-01-05T05:39:16.8836267Z    at Azure.ResourceManager.Compute.DiskAccessResource.SetTags(IDictionary`2 tags, CancellationToken cancellationToken) in /_/sdk/compute/Azure.ResourceManager.Compute/src/Generated/DiskAccessResource.cs:line 711
2025-01-05T05:39:16.8838149Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8839244Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8840159Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8840966Z    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2025-01-05T05:39:16.8842350Z    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass5_0`1.<<WrapAsyncResultCore>g__Await|0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 123
2025-01-05T05:39:16.8843286Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8843939Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8844595Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8845250Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8846151Z    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<>c__DisplayClass6_0`1.<<ValidateDiagnosticScopeInterceptor>b__0>d.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 174
2025-01-05T05:39:16.8847139Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8847803Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8848687Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8849655Z    at System.Threading.Tasks.ValueTask`1.get_Result()
2025-01-05T05:39:16.8850632Z    at Azure.Core.TestFramework.DiagnosticScopeValidatingInterceptor.<ValidateDiagnosticScope>d__7`1.MoveNext() in D:\a\_work\1\s\sdk\core\Azure.Core.TestFramework\src\Instrumentation\DiagnosticScopeValidatingInterceptor.cs:line 220
2025-01-05T05:39:16.8851728Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8852432Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8853073Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8853644Z    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2025-01-05T05:39:16.8854579Z    at Azure.ResourceManager.Compute.Tests.DiskAccessOperationsTests.<SetTags>d__4.MoveNext() in D:\a\_work\1\s\sdk\compute\Azure.ResourceManager.Compute\tests\Scenario\DiskAccessOperationsTests.cs:line 60
2025-01-05T05:39:16.8855676Z --- End of stack trace from previous location where exception was thrown ---
2025-01-05T05:39:16.8856607Z    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2025-01-05T05:39:16.8857161Z    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
2025-01-05T05:39:16.8857753Z    at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
2025-01-05T05:39:16.8859946Z    at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
2025-01-05T05:39:16.8860964Z    at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
2025-01-05T05:39:16.8862153Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
2025-01-05T05:39:16.8862850Z    at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
2025-01-05T05:39:16.8863397Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
2025-01-05T05:39:16.8863952Z    at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```

**Comment by welovej** [comment]
### Reproduction

In pipeline if the test is assigned into ProjectRef group,  the [section ](https://github.com/Azure/azure-sdk-for-net/blob/9d19f278ed2c3a3a52d2312c14e6ab20fada004f/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Generated/TagResource.cs#L63)about conditional compilation works. Then the responsed resourcetype validate fail which is not tag resource type. So if we add a  reouscemanager project to compute locally, Then run the test locally then we got the same situation in pipeline.

#### Root cause
The tag operation [Tags_CreateOrUpdateAtScope ](https://github.com/Azure/azure-rest-api-specs/blob/90a65cb3135d42438a381eb8bb5461a2b99b199f/specification/resources/resource-manager/Microsoft.Resources/stable/2022-09-01/resources.json#L4329)''   returned  wrong LRO response when work with Provider `Microsoft.Compute/disks` and `Microsoft.Compute/diskAccesses`.  Tags resource model should be returned instead of the Parent Resource model. Please check the recording below to understand the detail.
[diskAccesses.json](https://github.com/user-attachments/files/18394460/diskAccesses.json)
[disks.json](https://github.com/user-attachments/files/18394459/disks.json).

**Comment by welovej** [comment]
The issue is now clear: the ARM API version used is not affected by `ClientTestFixture`. The current ARM API version, `2022-09-01`, meets the requirements, so we will re-record it. Previously, the `Location` header was used, but now it has been replaced with `Azure-AsyncOperation`, which resolves the issue. When you recorded it earlier, the ARM API version was likely lower.
