### ISSUE TITLE
Fluent SDK: GenericResource: Create blows up with 'parentResourcePath' cannot be null

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3674]
I'm trying to use Fluent SDK 1.1.3 and GenericResource.Define.CreateAsync() to create a VMSS and it's not working. It looks like it is a client side validation error before the call to Azure (since I would never get to see a trace of the expected PUT request)

From the error message it seems like it is not working because it expects generic resource to only be used for child resources, not top-level??

```
[Deployment: iaas268, Id: 224] Fail CREATE IGENERICRESOURCE wus858288 'parentResourcePath' cannot be null. Microsoft.Rest.ValidationException: 'parentResourcePath' cannot be null.
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.<CreateOrUpdateWithHttpMessagesAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperationsExtensions.<CreateOrUpdateAsync>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.GenericResourceImpl.<CreateResourceAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.<Microsoft-Azure-Management-ResourceManager-Fluent-Core-ResourceActions-IResourceCreator<IResourceT>-CreateResourceAsync>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.<ExecuteAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.<ExecuteNodeTaskAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AzCacheRP.Provisioning.IResourceExtensions.<CreateWithLoggingAsync>d__2`1.MoveNext() in C:\repo\cp\src\Provisioning\AzureCacheRP\Provisioning\Resources\IResourceExtensions.cs:line 63 T=+00:01:13.0759450
```

**Comment by anuchandy** [comment]
@TimLovellSmith can you try with `.withParentResourcePath("")`

**Comment by hovsepm** [comment]
This issue was moved to Azure/azure-libraries-for-net#42
