### ISSUE TITLE
[BUG] Failure to backup a key/secret returns only bad request instead of proper error message

### ISSUE THREAD

**Issue by mearvind** [Azure/azure-sdk-for-net#36839]
### Library name and version

Microsoft.Azure.KeyVault 3.0.4

### Describe the bug

Failure of Creating a Backup of keys/secret causing the SDK to fail with bad request error where as service returns proper error.

### Expected behavior

To get proper error message in case of failure

### Actual behavior

Getting below error as part of failure

System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.KeyVault.KeyVaultClient.<BackupSecretWithHttpMessagesAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<BackupSecretAsync>d__56.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Internal.CloudBackup.Service.Common.CsmV2SdkHelperV2019.CsmV2Helper.BackupKeyVaultSecretData(String secretUrl) in C:\__w\1\s\src\Service\CsmV2SdkHelperV2019\KeyVaultHelper.cs:line 93
   at Microsoft.Internal.CloudBackup.Service.Common.CsmV2SdkHelperV2019.CsmV2Helper.<>c__DisplayClass128_0.<BackupKeyVaultSecret>b__0() in C:\__w\1\s\src\Service\CsmV2SdkHelperV2019\KeyVaultHelper.cs:line 148
   at Microsoft.Internal.CloudBackup.Service.Common.CsmV2SdkHelperV2019.CsmV2Helper.<>c__DisplayClass111_0.<ExecuteV2Request>b__0() in C:\__w\1\s\src\Service\CsmV2SdkHelperV2019\CsmV2SdkHelper.cs:line 295
---> (Inner Exception #0) Microsoft.Azure.KeyVault.Models.KeyVaultErrorException: Operation returned an invalid status code 'BadRequest'
   at Microsoft.Azure.KeyVault.KeyVaultClient.<BackupSecretWithHttpMessagesAsync>d__73.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<BackupSecretAsync>d__56.MoveNext()<---
}the 

### Reproduction Steps

If a secret has more than 500 version then the backup of such secret will cause this error

### Environment

Global

**Comment by jsquire** [comment]
Hi @mearvind.  Thank you for reaching out and we regret that you're experiencing difficulties.  The `Microsoft.Azure.KeyVault` package reached end-of-life in March, 2023 and is no longer maintained or supported.  We would strongly recommend that you upgrade to one of the following, depending on your needs:

- Azure.Security.KeyVault.Certificates
- Azure.Security.KeyVault.Keys
- Azure.Security.KeyVault.Secrets

Assistance for migrating can be found in the [KeyVault migration guide](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/keyvault/Azure.Security.KeyVault.Secrets/MigrationGuide.md).
