### ISSUE TITLE
[BUG] Unexpected Uri parse

### ISSUE THREAD

**Issue by LGDoor** [Azure/azure-sdk-for-net#36841]
### Library name and version

Azure.ResourceManager.AppPlatform

### Describe the bug

When try to deserialize the `App` object, the following error happens:
> Exception: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationoptions)
at System.Uri..ctor(String uriString)
at Azure.ResourceManager.AppPlatform.Models.AppPlatformAppProperties.DeserializeAppPlatformAppProperties(JsonElement element)
at Azure.ResourceManager.AppPlatform.AppPlatformAppData.DeserializeAppPlatformAppData(JsonElement element)
at Azure.ResourceManager.AppPlatform.AppsRestOperations.GetAsync(String subscriptionld, String resourceGroupName, String serviceName, String appName, String syncStatus, CancellationToken cancellationToken)
at Azure.ResourceManager.AppPlatform.AppPlatformAppResource.GetAsync(String syncStatus, CancellationToken cancellationToken)

It's caused by [this line](https://github.com/Azure/azure-sdk-for-net/blob/b5c78801f52df11e78a1102ac29fa5780c16eef8/sdk/appplatform/Azure.ResourceManager.AppPlatform/src/Generated/Models/AppPlatformAppProperties.cs#L59), which is defined as a plain string type in the API swagger but not a Uri type since its value isn’t always an Uri (e.g. `"None"`).

### Expected behavior

The type of the property `uri` should be `string` and won't be parsed when deserialization.

### Actual behavior

Try to parse some non-Uri value and throws exception.

### Reproduction Steps

The error can be reproduced by deserializing the following payload:
> {
  "id": "/subscriptions/49d49b85-5d5f-4793-a5c7-0ff936936dc3/resourceGroups/test-rg/providers/Microsoft.AppPlatform/Spring/test-service/apps/test1",
  "location": "eastus",
  "name": "test1",
  "properties": {    
    "provisioningState": "Succeeded",
    "public": false,
    "secrets": null,
    "temporaryDisk": {
      "mountPath": "/tmp",
      "sizeInGb": 5
    },
    "url": "None"
  },
  "resourceGroup": "test-rg",
  "type": "Microsoft.AppPlatform/Spring/apps"
}

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by live1206** [comment]
Fixed in [Azure.ResourceManager.AppPlatform/1.1.0-beta.2](https://www.nuget.org/packages/Azure.ResourceManager.AppPlatform/1.1.0-beta.2)
