### ISSUE TITLE
[BUG] MissingMethodException on authorization

### ISSUE THREAD

**Issue by partemyeva** [Azure/azure-sdk-for-net#36883]
### Library name and version

Azure.Identity 1.9.0

### Describe the bug

We have a library with custom MSBuild Tasks, which TargetFramework is netstandard2.1.
From the task, we perform authorization using Azure.Identity v1.9.0 and then request for teams using Microsoft.Graph v5.12.0. The code that produces the problem:

```
var scopes = new[] { "https://graph.microsoft.com/.default" };

var credentialOptions = new UsernamePasswordCredentialOptions
{
    AuthorityHost = AzureAuthorityHosts.AzurePublicCloud,
};

var credential = new UsernamePasswordCredential(
    username,
    password,
    tenantId,
    clientId,
    credentialOptions);

var graphClient = new GraphServiceClient(credential, scopes);

var response = await graphClient.Me.JoinedTeams.GetAsync();
```

-- here we get an exception:

```
System.MissingMethodException: Method not found: 'System.Threading.Tasks.ValueTask`1<Azure.Core.AccessToken> Azure.Core.TokenCredential.GetTokenAsync(Azure.Core.TokenRequestContext, System.Threading.CancellationToken)'.
   at Microsoft.Kiota.Authentication.Azure.AzureIdentityAccessTokenProvider.GetAuthorizationTokenAsync(Uri uri, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Kiota.Authentication.Azure.AzureIdentityAccessTokenProvider.GetAuthorizationTokenAsync(Uri uri, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken)
   at Microsoft.Kiota.Abstractions.Authentication.BaseBearerTokenAuthenticationProvider.AuthenticateRequestAsync(RequestInformation request, Dictionary`2 additionalAuthenticationContext, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.GetHttpResponseMessage(RequestInformation requestInfo, CancellationToken cancellationToken, Activity activityForAttributes, String claims)
   at Microsoft.Kiota.Http.HttpClientLibrary.HttpClientRequestAdapter.SendAsync[ModelType](RequestInformation requestInfo, ParsableFactory`1 factory, Dictionary`2 errorMapping, CancellationToken cancellationToken)
   at Microsoft.Graph.Me.JoinedTeams.JoinedTeamsRequestBuilder.GetAsync(Action`1 requestConfiguration, CancellationToken cancellationToken)
```

### Expected behavior

Successful authorization

### Actual behavior

Authorization fails. But authorization is success when MSBuild task library is built from .NET6

### Reproduction Steps

Executing the code above from a task via `dotnet msbuild` (SDK v7.0.102)

### Environment

Microsoft Windows 10.0.19044
.NET SDK v7.0.102

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by partemyeva** [comment]
Thank you for your prompt response. Here is the sample project to reproduce the issue:
https://github.com/partemyeva/MSBuildTaskSample

**Comment by christothes** [comment]
Thanks - Are you able to use netstandard2.0, which matches the target framework for Azure.Identity and Azure.Core? I can't reproduce the problem if I make that change.

**Comment by christothes** [comment]
Would it work for you to multi-target netstandard2.0 and net6.0 in order to get the best of both?
