### ISSUE TITLE
[BUG] DataProtection unable to unprotect with older keys after upgrading Azure.Extensions.AspNetCore.DataProtection.Keys

### ISSUE THREAD

**Issue by khellang** [Azure/azure-sdk-for-net#37043]
### Library name and version

Azure.Extensions.AspNetCore.DataProtection.Keys

### Describe the bug

This is the exact same problem as descibed in https://github.com/Azure/azure-sdk-for-net/issues/14761, which seem to have been fixed, but we recently upgraded from 1.1.0 to 1.2.2 and got the following error:

> Could not load file or assembly 'Azure.Extensions.AspNetCore.DataProtection.Keys, Version=1.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

With the following stack trace:

```
at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.CreateDecryptor(IActivator activator, String decryptorTypeName)
   at Microsoft.AspNetCore.DataProtection.XmlEncryption.XmlEncryptionExtensions.DecryptElement(XElement element, IActivator activator)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager.Microsoft.AspNetCore.DataProtection.KeyManagement.Internal.IInternalXmlKeyManager.DeserializeDescriptorFromKeyElement(XElement keyElement)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.DeferredKey.<>c__DisplayClass1_0.<GetLazyDescriptorDelegate>g__GetLazyDescriptorDelegate|0()
   at System.Lazy\`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.get_Descriptor()
   at Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngGcmAuthenticatedEncryptorFactory.CreateEncryptorInstance(IKey key)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyBase.CreateEncryptor()
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.KeyHolder.GetEncryptorInstance(Boolean& isRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRing.GetAuthenticatedEncryptorByKeyId(Guid keyId, Boolean& isRevoked)
   at Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingBasedDataProtector.UnprotectCore(Byte[] protectedData, Boolean allowOperationsOnRevokedKeys, UnprotectStatus& status)
```

I tried manually patching the `decryptorType` XML element like this:

```diff
-decryptorType="Azure.Extensions.AspNetCore.DataProtection.Keys.AzureKeyVaultXmlDecryptor, Azure.Extensions.AspNetCore.DataProtection.Keys, Version=1.1.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8"
+decryptorType="Azure.Extensions.AspNetCore.DataProtection.Keys.AzureKeyVaultXmlDecryptor, Azure.Extensions.AspNetCore.DataProtection.Keys, Version=1.2.2.0, Culture=neutral, PublicKeyToken=92742159e12e44c8"
```

As suggested in #14761, which made the code work again.

### Expected behavior

I'm able to update `Azure.Extensions.AspNetCore.DataProtection.Keys` to a newer version, without breaking my application.

### Actual behavior

By updating `Azure.Extensions.AspNetCore.DataProtection.Keys` to a newer version, I'm unable to unprotect secrets encrypted with an earlier key.

### Reproduction Steps

- Protect something with a key encrypted with Azure.Extensions.AspNetCore.DataProtection.Keys v1.1.0
- Upgrade to Azure.Extensions.AspNetCore.DataProtection.Keys v1.2.2
- Unprotect secret stored with key from Azure.Extensions.AspNetCore.DataProtection.Keys v1.1.0

### Environment

Azure AppService on .NET Framework 4.8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @khellang,
Could you please provide a code snippet showing how your app is using the library?

**Comment by JoshLove-msft** [comment]
Details from investigation:
It looks like the exception is thrown [here](https://github.com/dotnet/aspnetcore/blob/5ca9116e320806b347f9d5823658c3fb35afcfe0/src/DataProtection/DataProtection/src/XmlEncryption/XmlEncryptionExtensions.cs#LL76C20-L76C32), which is before our [Activator](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/extensions/Azure.Extensions.AspNetCore.DataProtection.Keys/src/DecryptorTypeForwardingActivator.cs#L45) would be invoked [here](https://github.com/dotnet/aspnetcore/blob/5ca9116e320806b347f9d5823658c3fb35afcfe0/src/DataProtection/DataProtection/src/XmlEncryption/XmlEncryptionExtensions.cs#L95).

The behavior seems to have changed in https://github.com/dotnet/aspnetcore/pull/41650/files#diff-471a63d39debc3a5f12fd97006e4b57e73e5b68f52de6893c650411915b238c1. Prior to this PR, all of the forwarding logic was delegated to the registered Activator. After the change, the [Type.GetType](https://learn.microsoft.com/en-us/dotnet/api/system.type.gettype?view=net-7.0#system-type-gettype(system-string-system-boolean)) call is added which can throw (even when throwOnError is set to false).

**Comment by JoshLove-msft** [comment]
Filed https://github.com/dotnet/aspnetcore/issues/48910 as this appears to be a regression caused in https://github.com/dotnet/aspnetcore/pull/41650/files#diff-471a63d39debc3a5f12fd97006e4b57e73e5b68f52de6893c650411915b238c1. Once that bug is fixed, the issue here would be resolved by upgrading to the version of Microsoft.AspNetCore.DataProtection with the fix. Leaving this issue open so that we upgrade our dependency to the fix version, once available.

**Comment by JoshLove-msft** [comment]
@khellang can you share the version of Microsoft.AspNetCore.DataProtection being used in your app?

**Comment by khellang** [comment]
We're using 7.0.5

**Comment by JoshLove-msft** [comment]
> Thanks for digging this up! We're using 7.0.5 ☺️

Thanks @khellang! Since the bug is actually in 7.x and our dependency is on 3.1.32, I don't think we would bump our dependency to the fix version, as there is no issue with 3.1.32. Given that, I will close out this issue, but feel free to follow https://github.com/dotnet/aspnetcore/issues/48910 for updates.
