### ISSUE TITLE
Fluent: LRO exception message gives little actionable information ...

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3713]
An unfortunate feature of Fluent SDK 1.2.0: long running operation failures come with a dearth of information which could actually be used to understand what failed. This exception could really use a description of what/why it failed. (In this example we are trying to do a manual upgrade on a VM scaleset using vmss.Manager.Inner.VirtualMachineScaleSets.UpdateInstancesAsync().

```
Exception : Microsoft.Rest.Azure.CloudException: Long running operation failed with status 'Failed'.
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__1`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetLongRunningOperationResultAsync>d__0`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Rest.Azure.AzureClientExtensions.<GetPostOrDeleteOperationResultAsync>d__7`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperations.<UpdateInstancesWithHttpMessagesAsync>d__17.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachineScaleSetsOperationsExtensions.<UpdateInstancesAsync>d__12.MoveNext()
```

**Comment by hovsepm** [comment]
@TimLovellSmith  this is a known issue in ClientRuntime which was fixed after we released 1.2. We are planning to reference the latest ClientRuntime in v1.3.

**Comment by TimLovellSmith** [comment]
@hovsepm That is great news. I'm not 100% sure which version you mean it is fixed in but trying this to see if it fixes the problem:

Install-Package Microsoft.Rest.ClientRuntime.Azure -Version 3.3.10

**Comment by hovsepm** [comment]
@TimLovellSmith , yes v.3.3.10 should have the fix.
