### ISSUE TITLE
[BUG] - Azure.Identity (v1.9) handles ManagedID exceptions differently from 1.8.2, (locally doesn't fall through to next chained identity)

### ISSUE THREAD

**Issue by kevinwedwards** [Azure/azure-sdk-for-net#37409]
### Library name and version

Azure.Identity.1.9

### Describe the bug

new ChainedTokenCredential(new AzureCliCredential(), new ManagedIdentityCredential()),
![image](https://github.com/Azure/azure-sdk-for-net/assets/38870897/c7799700-dcae-40a4-9170-6c07640852e8)

1.8.2 works as expected.  When running locally, ChainedManagedIdentity attempts ManagedID first, fails, falls through to AzureCLI

1.9.0 appears to not fall through and mishandles the ManagedID attempt/response, preventing the ChainIdentity (when running locally), from falling through to the succeeding identity (in my case AzureCLI) as it should.

### Expected behavior

ManagedID attempt fails, AzureCLI is attempted.

### Actual behavior

1.9.0 fails to fall through at mishandles the ManagedID attempt and the response, preventing the ChainIdentity (when running locally), from falling through to the succeeding identity as it should.

The error received is shown here:
"The ChainedTokenCredential failed due to an unhandled exception: ManagedIdentityCredential authentication failed: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.\nSee the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot"

![image](https://github.com/Azure/azure-sdk-for-net/assets/38870897/15beda0b-9cf4-47e6-8beb-353735856828)

### Reproduction Steps

Attempt to invoke a new ChainedTokenCredential(new ManagedIdentityCredential(), new AzureCliCredential())

### Environment

dotnet 7.0.3

Edition	Windows 10 Enterprise
Version	21H2
Installed on	‎11/‎2/‎2021
OS build	19044.3086
Experience	Windows Feature Experience Pack 1000.19041.1000.0

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
I beleive this has already been fixed and will be in the next release. Would you be able to validate with this [dev build version](https://dev.azure.com/azure-sdk/public/_artifacts/feed/azure-sdk-for-net/NuGet/Azure.Identity/overview/1.10.0-alpha.20230705.1)?

**Comment by kevinwedwards** [comment]
@christothes 
1.8.1 and 1.8.2 work differently, correctly, than 1.9.0 or 1.10.0-alpha.20230705.1.

1.10.0-alpha.20230705.1 appears to have the same bug, which I believe was introduced in 1.9.0.

**Comment by christothes** [comment]
Could you share the stack trace from your exception, including any inner exception details or stack trace?

**Comment by kevinwedwards** [comment]
@christothes 

   at Azure.Identity.ChainedTokenCredential.<GetTokenImplAsync>d__7.MoveNext()
   at Azure.Identity.ChainedTokenCredential.<GetTokenAsync>d__6.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueFromCredentialAsync>d__9.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__6.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.AccessTokenCache.<GetHeaderValueAsync>d__6.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<AuthenticateAndAuthorizeRequestAsync>d__12.MoveNext()
   at Azure.Security.KeyVault.ChallengeBasedAuthenticationPolicy.<AuthorizeRequestOnChallengeAsyncInternal>d__9.MoveNext()
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.<ProcessAsync>d__11.MoveNext()
   at Azure.Core.Pipeline.RedirectPolicy.<ProcessAsync>d__7.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.HttpPipeline.<SendRequestAsync>d__18.MoveNext()
   at Azure.Security.KeyVault.KeyVaultPipeline.<SendRequestAsync>d__29.MoveNext()
   at Azure.Security.KeyVault.KeyVaultPipeline.<GetPageAsync>d__17`1.MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.<AsPages>d__2.MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.<AsPages>d__2.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.MoveNext()
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.MoveNext()
   at Azure.AsyncPageable`1.<GetAsyncEnumerator>d__6.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.<LoadAsync>d__11.MoveNext()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.<LoadAsync>d__11.MoveNext()
   at Azure.Extensions.AspNetCore.Configuration.Secrets.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationManager.AddSource(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.ConfigurationManager.Microsoft.Extensions.Configuration.IConfigurationBuilder.Add(IConfigurationSource source)
   at Microsoft.Extensions.Configuration.AzureKeyVaultConfigurationExtensions.AddAzureKeyVault(IConfigurationBuilder configurationBuilder, SecretClient client, AzureKeyVaultConfigurationOptions options)
   at Program.<Main>$(String[] args) in **redacted**



Exception Message:
"The ChainedTokenCredential failed due to an unhandled exception: ManagedIdentityCredential authentication failed: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.\nSee the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot"   
   
InnerException:
      {"ManagedIdentityCredential authentication failed: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.\nSee the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot"}

**Comment by kevinwedwards** [comment]
@christothes anything else you need for researching this?  any findings?

**Comment by kevinwedwards** [comment]
I had some stuff come up and wasn't able to get back to this... but hopefully will this week.

**Comment by kevinwedwards** [comment]
@christothes   very sorry for the delay.  

[Informational] Azure-Core: Request [bfe72513-a068-4131-bd8f-d20a50895d84] GET https://[*******].vault.azure.net/secrets/?api-version=7.2
Accept:application/json
x-ms-client-request-id:bfe72513-a068-4131-bd8f-d20a50895d84
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Secrets/4.2.0,(.NET 6.0.18; Microsoft Windows 10.0.19044)
Content-Type:application/json
client assembly: Azure.Security.KeyVault.Secrets
[Warning] Azure-Core: Error response [bfe72513-a068-4131-bd8f-d20a50895d84] 401 Unauthorized (02.0s)
Cache-Control:no-cache
Pragma:no-cache
WWW-Authenticate:Bearer authorization="https://login.microsoftonline.com/e45cbcc1-1760-419a-a16b-35802285b3b3", resource="https://vault.azure.net"
x-ms-keyvault-region:eastus2
x-ms-client-request-id:bfe72513-a068-4131-bd8f-d20a50895d84
x-ms-request-id:d9fc81bb-2f9e-40db-acfd-d2454cf4a1c8
x-ms-keyvault-service-version:1.9.865.5
x-ms-keyvault-network-info:conn_type=PrivateLink;private_endpoint=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Network/privateEndpoints/REDACTED;addr=REDACTED;act_addr_fam=InterNetworkV6;
X-Content-Type-Options:REDACTED
Strict-Transport-Security:REDACTED
Date:Mon, 24 Jul 2023 12:53:59 GMT
Content-Length:97
Content-Type:application/json; charset=utf-8
Expires:-1

[Warning] Azure-Core: Error response [bfe72513-a068-4131-bd8f-d20a50895d84] 401 Unauthorized (02.0s)
Cache-Control:no-cache
Pragma:no-cache
WWW-Authenticate:Bearer authorization="https://login.microsoftonline.com/e45cbcc1-1760-419a-a16b-35802285b3b3", resource="https://vault.azure.net"
x-ms-keyvault-region:eastus2
x-ms-client-request-id:bfe72513-a068-4131-bd8f-d20a50895d84
x-ms-request-id:d9fc81bb-2f9e-40db-acfd-d2454cf4a1c8
x-ms-keyvault-service-version:1.9.865.5
x-ms-keyvault-network-info:conn_type=PrivateLink;private_endpoint=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Network/privateEndpoints/REDACTED;addr=REDACTED;act_addr_fam=InterNetworkV6;
X-Content-Type-Options:REDACTED
Strict-Transport-Security:REDACTED
Date:Mon, 24 Jul 2023 12:53:59 GMT
Content-Length:97
Content-Type:application/json; charset=utf-8
Expires:-1

[Informational] Azure-Identity: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: bfe72513-a068-4131-bd8f-d20a50895d84
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:01Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] MSAL MSAL.NetCore with assembly version '4.54.1.0'. CorrelationId(657eb309-698f-4519-90e1-15cf27b0b3cb)
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:01Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:01Z - 657eb309-698f-4519-90e1-15cf27b0b3cb]
=== Request Data ===
Authority Provided? - True
Scopes - https://vault.azure.net/.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 657eb309-698f-4519-90e1-15cf27b0b3cb
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:01Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] === Token Acquisition (ClientCredentialRequest) started:
         Scopes: https://vault.azure.net/.default
        Authority Host: login.microsoftonline.com
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:01Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] [Region discovery] Not using a regional authority.
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:01Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] [Instance Discovery] Skipping Instance discovery because it is disabled.
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:01Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] Authority validation enabled? False.
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:01Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] Authority validation - is known env? True.
[Informational] Azure-Core: Request [2bdbc2a0-336a-4bf5-a830-b6b7b8a6aab8] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
Metadata:REDACTED
x-ms-client-request-id:2bdbc2a0-336a-4bf5-a830-b6b7b8a6aab8
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.8.2,(.NET 6.0.18; Microsoft Windows 10.0.19044)
client assembly: Azure.Identity
[Warning] Azure-Core: Error response [2bdbc2a0-336a-4bf5-a830-b6b7b8a6aab8] 502 cannotconnect (12.7s)
Via:REDACTED
Cache-Control:no-cache
X-Frame-Options:REDACTED
Proxy-Connection:REDACTED
Content-Type:text/html
Content-Length:4822

[Warning] Azure-Core: Error response [2bdbc2a0-336a-4bf5-a830-b6b7b8a6aab8] 502 cannotconnect (12.7s)
Via:REDACTED
Cache-Control:no-cache
X-Frame-Options:REDACTED
Proxy-Connection:REDACTED
Content-Type:text/html
Content-Length:4822

[Warning] Azure-Core: Response [2bdbc2a0-336a-4bf5-a830-b6b7b8a6aab8] took 12.7s
[Warning] Azure-Core: Response [2bdbc2a0-336a-4bf5-a830-b6b7b8a6aab8] took 12.7s
[Error] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:27Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] Exception type: Azure.Identity.CredentialUnavailableException

   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToProviderAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
[Error] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 12:54:27Z - 657eb309-698f-4519-90e1-15cf27b0b3cb] Exception type: Azure.Identity.CredentialUnavailableException

   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToProviderAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
[Informational] Azure-Identity: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: bfe72513-a068-4131-bd8f-d20a50895d84 Exception: Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. The request failed due to a gateway error.
Status: 502 (cannotconnect)

Content:
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>


<head>
  <meta http-equiv="X-UA-Compatible" content="IE=7" />
  <meta content="text/html" http-equiv="Content-Type">
  <title>McAfee Web Gateway - Notification</title>
  <script src="/mwg-internal/de5fs23hu73ds/files/javascript/sw.js" type="text/javascript" ></script>
  <link rel="stylesheet" href="/mwg-internal/de5fs23hu73ds/files/default/stylesheet.css" />
</head>


<body onload="swOnLoad();">
  <table class='bodyTable'>
    <tr>
      <td class='bodyData' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_body.gif'>

<table class='logoTable'>
  <tr>
    <td class='logoData'>
        REDACTED
    </td>
  </tr>
</table>



<table class='titleTable' background='/mwg-internal/de5fs23hu73ds/files/default/img/bg_navbar.jpg'>
  <tr>
    <td class='titleData'>
      Cannot Connect
    </td>
  </tr>
</table>



<table class="contentTable">
  <tr>
    <td class="contentData">
      <b>What happened?</b>
      <p>The proxy could not connect to the remote server. Either the server is down or the URL is invalid.</p>

      REDACTED
    </td>
  </tr>
</table>





<table class="infoTable">
  <tr>
    <td class="infoData">
      REDACTED
    </td>
  </tr>
</table>


<table class='policyTable'>
  <tr>
    <td class='policyHeading'>
      <hr>
      Company Acceptable Use Policy
    </td>
  </tr>
  <tr>
    REDACTED
  </tr>
</table>
</body>

</html>

Headers:
Via: REDACTED
Cache-Control: no-cache
X-Frame-Options: REDACTED
Proxy-Connection: REDACTED
Content-Type: text/html
Content-Length: 4822

[Informational] Azure-Identity: AzureCliCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: bfe72513-a068-4131-bd8f-d20a50895d84

**Comment by kevinwedwards** [comment]
**1.9.0** This is what fails.  Everything is the same until the line:
   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)


[Informational] Azure-Core: Request [5c01e655-8e99-4081-9b8b-6cc0cae81703] GET https://REDACTED.vault.azure.net/secrets/?api-version=7.2
Content-Type:application/json
Accept:application/json
x-ms-client-request-id:5c01e655-8e99-4081-9b8b-6cc0cae81703
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Security.KeyVault.Secrets/4.2.0 (.NET 6.0.18; Microsoft Windows 10.0.19044)
client assembly: Azure.Security.KeyVault.Secrets
[Warning] Azure-Core: Error response [5c01e655-8e99-4081-9b8b-6cc0cae81703] 401 Unauthorized (01.6s)
Cache-Control:no-cache
Pragma:no-cache
WWW-Authenticate:Bearer authorization="https://login.microsoftonline.com/e45cbcc1-1760-419a-a16b-35802285b3b3", resource="https://vault.azure.net"
x-ms-keyvault-region:eastus2
x-ms-client-request-id:5c01e655-8e99-4081-9b8b-6cc0cae81703
x-ms-request-id:5b9f0bc8-b7df-494c-a499-a648e93654ce
x-ms-keyvault-service-version:1.9.865.5
x-ms-keyvault-network-info:conn_type=PrivateLink;private_endpoint=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Network/privateEndpoints/REDACTED;addr=REDACTED;act_addr_fam=InterNetworkV6;
X-Content-Type-Options:REDACTED
Strict-Transport-Security:REDACTED
Date:Mon, 24 Jul 2023 13:17:58 GMT
Content-Length:97
Content-Type:application/json; charset=utf-8
Expires:-1

[Warning] Azure-Core: Error response [5c01e655-8e99-4081-9b8b-6cc0cae81703] 401 Unauthorized (01.6s)
Cache-Control:no-cache
Pragma:no-cache
WWW-Authenticate:Bearer authorization="https://login.microsoftonline.com/e45cbcc1-1760-419a-a16b-35802285b3b3", resource="https://vault.azure.net"
x-ms-keyvault-region:eastus2
x-ms-client-request-id:5c01e655-8e99-4081-9b8b-6cc0cae81703
x-ms-request-id:5b9f0bc8-b7df-494c-a499-a648e93654ce
x-ms-keyvault-service-version:1.9.865.5
x-ms-keyvault-network-info:conn_type=PrivateLink;private_endpoint=/subscriptions/REDACTED/resourceGroups/REDACTED/providers/Microsoft.Network/privateEndpoints/REDACTED;addr=REDACTED;act_addr_fam=InterNetworkV6;
X-Content-Type-Options:REDACTED
Strict-Transport-Security:REDACTED
Date:Mon, 24 Jul 2023 13:17:58 GMT
Content-Length:97
Content-Type:application/json; charset=utf-8
Expires:-1

[Informational] Azure-Identity: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: 5c01e655-8e99-4081-9b8b-6cc0cae81703
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:17:58Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] MSAL MSAL.NetCore with assembly version '4.54.1.0'. CorrelationId(ab300e60-b7b6-49aa-8d78-80706511c2dd)
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:17:58Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:17:58Z - ab300e60-b7b6-49aa-8d78-80706511c2dd]
=== Request Data ===
Authority Provided? - True
Scopes - https://vault.azure.net/.default
Extra Query Params Keys (space separated) -
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - ab300e60-b7b6-49aa-8d78-80706511c2dd
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured:

[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:17:58Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] === Token Acquisition (ClientCredentialRequest) started:
         Scopes: https://vault.azure.net/.default
        Authority Host: login.microsoftonline.com
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:17:58Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] [Region discovery] Not using a regional authority.
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:17:58Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] [Instance Discovery] Skipping Instance discovery because it is disabled.
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:17:58Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] Authority validation enabled? False.
[Informational] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:17:58Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] Authority validation - is known env? True.
[Informational] Azure-Core: Request [28cf9738-575e-4074-b0ae-4909f35b871f] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
Metadata:REDACTED
x-ms-client-request-id:28cf9738-575e-4074-b0ae-4909f35b871f
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.9.0 (.NET 6.0.18; Microsoft Windows 10.0.19044)
client assembly: Azure.Identity
[Warning] Azure-Core: Error response [28cf9738-575e-4074-b0ae-4909f35b871f] 502 cannotconnect (16.9s)
Via:REDACTED
Cache-Control:no-cache
X-Frame-Options:REDACTED
Proxy-Connection:REDACTED
Content-Type:text/html
Content-Length:4822

[Warning] Azure-Core: Error response [28cf9738-575e-4074-b0ae-4909f35b871f] 502 cannotconnect (16.9s)
Via:REDACTED
Cache-Control:no-cache
X-Frame-Options:REDACTED
Proxy-Connection:REDACTED
Content-Type:text/html
Content-Length:4822

[Warning] Azure-Core: Response [28cf9738-575e-4074-b0ae-4909f35b871f] took 16.9s
[Warning] Azure-Core: Response [28cf9738-575e-4074-b0ae-4909f35b871f] took 16.9s
[Error] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:18:15Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] Exception type: System.Text.Json.JsonReaderException

   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.GetMessageFromResponse(Response response, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToProviderAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
[Error] Azure-Identity: False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.18 Microsoft Windows 10.0.19044 [2023-07-24 13:18:15Z - ab300e60-b7b6-49aa-8d78-80706511c2dd] Exception type: System.Text.Json.JsonReaderException

   at System.Text.Json.ThrowHelper.ThrowJsonReaderException(Utf8JsonReader& json, ExceptionResource resource, Byte nextByte, ReadOnlySpan`1 bytes)
   at System.Text.Json.Utf8JsonReader.ConsumeValue(Byte marker)
   at System.Text.Json.Utf8JsonReader.ReadFirstToken(Byte first)
   at System.Text.Json.Utf8JsonReader.ReadSingleSegment()
   at System.Text.Json.Utf8JsonReader.Read()
   at System.Text.Json.JsonDocument.Parse(ReadOnlySpan`1 utf8JsonSpan, JsonReaderOptions readerOptions, MetadataDb& database, StackRowStack& stack)
   at System.Text.Json.JsonDocument.Parse(ReadOnlyMemory`1 utf8Json, JsonReaderOptions readerOptions, Byte[] extraRentedArrayPoolBytes, PooledByteBufferWriter extraPooledByteBufferWriter)
   at System.Text.Json.JsonDocument.ParseAsyncCore(Stream utf8Json, JsonDocumentOptions options, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.GetMessageFromResponse(Response response, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToProviderAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
[Informational] Azure-Identity: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://vault.azure.net/.default ] ParentRequestId: 5c01e655-8e99-4081-9b8b-6cc0cae81703 Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
 ---> System.Text.Json.JsonReaderException (0x80131500): '<' is an invalid start of a value. LineNumber: 0 | BytePositionInLine: 0.
