### ISSUE TITLE
[BUG] Scopes Conflicts between TokenExchangeManagedIdentitySource and ImdsManagedIdentitySource

### ISSUE THREAD

**Issue by msJinLei** [Azure/azure-sdk-for-net#37453]
### Library name and version

azsdk-net-Identity/1.6.1 

### Describe the bug

We are from Azure PowerShell team. Recently we receive an issue report from the customer https://github.com/Azure/azure-powershell/issues/22213.

When env variables `AZURE_CLIENT_ID`, `AZURE_TENANT_ID`, `AZURE_FEDERATED_TOKEN_FILE` and `AZURE_AUTHORITY_HOST` are set,  to acquire token using MSI fails with:
ClientAssertionCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input parameter.

We find the logic in Azure.Identity goes into the [TokenExchangeManagedIdentity](https://github.com/Azure/azure-sdk-for-net/blob/d60413a2b76ff2b9d068c2f8bdf65752926a28af/sdk/identity/Azure.Identity/src/TokenExchangeManagedIdentitySource.cs#L14). The `Scopes` it uses is different from other MSI sources, but share the same interface from [TokenRequestContext](https://github.com/Azure/azure-sdk-for-net/blob/d60413a2b76ff2b9d068c2f8bdf65752926a28af/sdk/core/Azure.Core/src/TokenRequestContext.cs#L56).

We also find Azure.Identity has a variable called [ExcludeTokenExchangeManagedIdentitySource](https://github.com/Azure/azure-sdk-for-net/blob/d60413a2b76ff2b9d068c2f8bdf65752926a28af/sdk/identity/Azure.Identity/src/ManagedIdentityClientOptions.cs#L23), which can disable `TokenExchangeManagedIdentitySource`.  But we cannot set it from `ManagedIdentityCredential`.

### Expected behavior

Acquire token with `ImdsManagedIdentitySource`

### Actual behavior

```
DEBUG: 16:01:31 - [ManagedServiceIdentityAuthenticator] Calling ManagedIdentityCredential.GetTokenAsync - TenantId:'organizations', Scopes:'https://management.core.windows.net/', UserId:''
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId: 
DEBUG: ClientAssertionCredential.GetToken invoked. Scopes: [ https://management.core.windows.net/ ] ParentRequestId: 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] MSAL MSAL.NetCore with assembly version '4.49.1.0'. CorrelationId(d7c8e151-1a70-4b32-a176-0e43cb4e9573)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] 
=== Request Data ===
Authority Provided? - True
Scopes - https://management.core.windows.net/
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - d7c8e151-1a70-4b32-a176-0e43cb4e9573
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] === Token Acquisition (ClientCredentialRequest) started:
	 Scopes: https://management.core.windows.net/
	Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] [Instance Discovery] Instance discovery is enabled and will be performed
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Fetching instance discovery from the network from host login.microsoftonline.com. 
DEBUG: Request [89edea45-c40d-4567-88aa-a50f8ae08268] GET https://login.microsoftonline.com/common/discovery/instance?api-version=1.1&authorization_endpoint=REDACTED
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
x-ms-client-request-id:89edea45-c40d-4567-88aa-a50f8ae08268
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.1 (.NET 7.0.5; Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023)
client assembly: Azure.Identity
DEBUG: Response [89edea45-c40d-4567-88aa-a50f8ae08268] 200 OK (00.2s)
Cache-Control:max-age=86400, private
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
Access-Control-Allow-Origin:REDACTED
Access-Control-Allow-Methods:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:57ef068d-1fac-46c0-a2b5-b2d16aa22b00
x-ms-ests-server:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Fri, 30 Jun 2023 16:01:31 GMT
Content-Type:application/json; charset=utf-8
Content-Length:980
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Authority validation enabled? True. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Authority validation - is known env? True. 
DEBUG: Request [ad474182-1bc7-4222-a9dc-7413a4980088] POST https://login.microsoftonline.com/af7227b1-ac3a-4487-9e9f-ba462bb409d4/oauth2/v2.0/token
x-client-SKU:REDACTED
x-client-Ver:REDACTED
x-client-OS:REDACTED
x-client-current-telemetry:REDACTED
x-client-last-telemetry:REDACTED
x-ms-PKeyAuth:REDACTED
x-ms-lib-capability:REDACTED
client-request-id:REDACTED
return-client-request-id:REDACTED
x-app-name:REDACTED
x-app-ver:REDACTED
Content-Type:application/x-www-form-urlencoded
x-ms-client-request-id:ad474182-1bc7-4222-a9dc-7413a4980088
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.6.1 (.NET 7.0.5; Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023)
client assembly: Azure.Identity
DEBUG: Error response [ad474182-1bc7-4222-a9dc-7413a4980088] 400 Bad Request (00.0s)
Cache-Control:no-store, no-cache
Pragma:no-cache
Strict-Transport-Security:REDACTED
X-Content-Type-Options:REDACTED
P3P:REDACTED
client-request-id:REDACTED
x-ms-request-id:6876ec3d-4a33-4003-9af7-ae0a4dc32400
x-ms-ests-server:REDACTED
x-ms-clitelem:REDACTED
X-XSS-Protection:REDACTED
Set-Cookie:REDACTED
Date:Fri, 30 Jun 2023 16:01:31 GMT
Content-Type:application/json; charset=utf-8
Expires:-1
Content-Length:551
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Response status code does not indicate success: 400 (BadRequest). 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Request retry failed.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] HttpStatusCode: 400: BadRequest
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] === Token Acquisition (1004) failed.
	Host: login.microsoftonline.com.
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: invalid_scope
HTTP StatusCode 400
CorrelationId d7c8e151-1a70-4b32-a176-0e43cb4e9573
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Fetching a new AT failed. Is exception retry-able? False. Is there an AT in the cache that is usable? False
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Either the exception does not indicate a problem with AAD or the token cache does not have an AT that is usable. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 7.0.5 Linux 5.15.0-1039-azure #46-Ubuntu SMP Mon May 22 15:18:07 UTC 2023 [2023-06-30 16:01:32Z - d7c8e151-1a70-4b32-a176-0e43cb4e9573] Exception type: Microsoft.Identity.Client.MsalServiceException
, ErrorCode: invalid_scope
HTTP StatusCode 400
CorrelationId d7c8e151-1a70-4b32-a176-0e43cb4e9573
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.HandleTokenRefreshErrorAsync(MsalServiceException e, MsalAccessTokenCacheItem cachedAccessTokenItem)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
DEBUG: ClientAssertionCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:  Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ClientAssertionCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z
 ---> Microsoft.Identity.Client.MsalServiceException (0x80131500): AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z
DEBUG: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://management.core.windows.net/ ] ParentRequestId:  Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ClientAssertionCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z
 ---> Microsoft.Identity.Client.MsalServiceException (0x80131500): AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z
WARNING: Unable to acquire token for tenant 'organizations' with error 'ClientAssertionCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z'
DEBUG: 16:01:32 - Unable to acquire token for tenant 'organizations' with error 'Azure.Identity.AuthenticationFailedException: ClientAssertionCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z
 ---> MSAL.NetCore.4.49.1.0.MsalServiceException: 
	ErrorCode: invalid_scope
Microsoft.Identity.Client.MsalServiceException: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.HandleTokenRefreshErrorAsync(MsalServiceException e, MsalAccessTokenCacheItem cachedAccessTokenItem)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ClientAssertionCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
	StatusCode: 400 
	ResponseBody: {"error":"invalid_scope","error_description":"AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.\r\nTrace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400\r\nCorrelation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573\r\nTimestamp: 2023-06-30 16:01:32Z","error_codes":[70011],"timestamp":"2023-06-30 16:01:32Z","trace_id":"6876ec3d-4a33-4003-9af7-ae0a4dc32400","correlation_id":"d7c8e151-1a70-4b32-a176-0e43cb4e9573"} 
	Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: d7c8e151-1a70-4b32-a176-0e43cb4e9573
x-ms-request-id: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
x-ms-ests-server: 2.1.15723.3 - NEULR1 ProdSlices
x-ms-clitelem: 1,70011,0,,
X-XSS-Protection: 0
Set-Cookie: fpc=AlAZ2br5N9dGr-vy0Jc7UMY; expires=Sun, 30-Jul-2023 16:01:32 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Fri, 30 Jun 2023 16:01:31 GMT
   --- End of inner exception stack trace ---
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.ClientAssertionCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.TokenExchangeManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage)
   at Azure.Identity.ManagedIdentityCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Microsoft.Azure.PowerShell.Authenticators.MsalAccessTokenAcquirer.GetAccessTokenAsync(String callerClassName, String parametersLog, TokenCredential tokenCredential, TokenRequestContext requestContext, CancellationToken cancellationToken, String tenantId, String userId, String homeAccountId)
   at Microsoft.Azure.Commands.Common.Authentication.Factories.AuthenticationFactory.Authenticate(IAzureAccount account, IAzureEnvironment environment, String tenant, SecureString password, String promptBehavior, Action`1 promptAction, IAzureTokenCache tokenCache, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.AcquireAccessToken(IAzureAccount account, IAzureEnvironment environment, String tenantId, SecureString password, String promptBehavior, Action`1 promptAction, String resourceId)
   at Microsoft.Azure.Commands.ResourceManager.Common.RMProfileClient.ListAccountTenants(IAzureAccount account, IAzureEnvironment environment, SecureString password, String promptBehavior, Action`1 promptAction)'
DEBUG: Azure.Identity.AuthenticationFailedException: ClientAssertionCredential authentication failed: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z
 ---> MSAL.NetCore.4.49.1.0.MsalServiceException: 
	ErrorCode: invalid_scope
Microsoft.Identity.Client.MsalServiceException: AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.
Trace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
Correlation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573
Timestamp: 2023-06-30 16:01:32Z
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.HandleTokenRefreshErrorAsync(MsalServiceException e, MsalAccessTokenCacheItem cachedAccessTokenItem)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.ApiConfig.Executors.ConfidentialClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenForClientParameters clientParameters, CancellationToken cancellationToken)
   at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientCoreAsync(String[] scopes, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.MsalConfidentialClient.AcquireTokenForClientAsync(String[] scopes, String tenantId, Boolean async, CancellationToken cancellationToken)
   at Azure.Identity.ClientAssertionCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
	StatusCode: 400 
	ResponseBody: {"error":"invalid_scope","error_description":"AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope https://management.core.windows.net/ is not valid.\r\nTrace ID: 6876ec3d-4a33-4003-9af7-ae0a4dc32400\r\nCorrelation ID: d7c8e151-1a70-4b32-a176-0e43cb4e9573\r\nTimestamp: 2023-06-30 16:01:32Z","error_codes":[70011],"timestamp":"2023-06-30 16:01:32Z","trace_id":"6876ec3d-4a33-4003-9af7-ae0a4dc32400","correlation_id":"d7c8e151-1a70-4b32-a176-0e43cb4e9573"} 
	Headers: Cache-Control: no-store, no-cache
Pragma: no-cache
Strict-Transport-Security: max-age=31536000; includeSubDomains
X-Content-Type-Options: nosniff
P3P: CP="DSP CUR OTPi IND OTRi ONL FIN"
client-request-id: d7c8e151-1a70-4b32-a176-0e43cb4e9573
x-ms-request-id: 6876ec3d-4a33-4003-9af7-ae0a4dc32400
x-ms-ests-server: 2.1.15723.3 - NEULR1 ProdSlices
x-ms-clitelem: 1,70011,0,,
X-XSS-Protection: 0
Set-Cookie: fpc=AlAZ2br5N9dGr-vy0Jc7UMY; expires=Sun, 30-Jul-2023 16:01:32 GMT; path=/; secure; HttpOnly; SameSite=None, x-ms-gateway-slice=estsfd; path=/; secure; samesite=none; httponly, stsservicecookie=estsfd; path=/; secure; samesite=none; httponly
Date: Fri, 30 Jun 2023 16:01:31 GMT
```

### Reproduction Steps

Using the MSI way to acquire token

```CSharp
var scopes = new[] { GetResourceId(msiParameters.ResourceId, msiParameters.Environment) };
var requestContext = new TokenRequestContext(scopes);
var userAccountId = SystemMsiNameRegex.IsMatch(msiParameters.Account.Id) ? null : msiParameters.Account.Id;

var identityCredential = new ManagedIdentityCredential(userAccountId);
var parametersLog = $"- TenantId:'{msiParameters.TenantId}', Scopes:'{string.Join(",", scopes)}', UserId:'{userAccountId}'";
TracingAdapter.Information($"{DateTime.Now:T} - [{callerClassName}] Calling {tokenCredential.GetType().Name}.GetTokenAsync {parametersLog}");
var token = await identityCredential .GetTokenAsync(requestContext, cancellationToken).ConfigureAwait(false);
return new MsalAccessToken(identityCredential , requestContext, token.Token, token.ExpiresOn, tenantId, userAccountId, homeAccountId);
```

### Environment

azsdk-net-Identity/1.6.1 
.NET 7.0.5
Linux 5.15.0-1039-azure

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by christothes** [comment]
Hi @msJinLei 
Is there a reason that the AZURE_FEDERATED_TOKEN_FILE is being set given that it is not used by IMDS? Without this variable, I believe we would fall through to the IMDS source.

**Comment by msJinLei** [comment]
> Hi @msJinLei Is there a reason that the AZURE_FEDERATED_TOKEN_FILE is being set given that it is not used by IMDS? Without this variable, I believe we would fall through to the IMDS source.

Yes, you are right. But the in AKS environment, the customer should be able to login with managed identity.

**Comment by msJinLei** [comment]
> > We also find Azure.Identity has a variable called [ExcludeTokenExchangeManagedIdentitySource](https://github.com/Azure/azure-sdk-for-net/blob/d60413a2b76ff2b9d068c2f8bdf65752926a28af/sdk/identity/Azure.Identity/src/ManagedIdentityClientOptions.cs#L23), which can disable `TokenExchangeManagedIdentitySource`.  But we cannot set it from `ManagedIdentityCredential`.
> 
> You can set it via this option;
> 
> https://github.com/Azure/azure-sdk-for-net/blob/483718b3fc6c5ba022bea12516bda696858f961e/sdk/identity/Azure.Identity/src/Credentials/DefaultAzureCredentialOptions.cs#L218
> 
> Does that work for you?

Switch to `DefaultAzureCredentialOptions` will cause major change to our exiting implementation.  I will evaluate it carefully at first.
CC @isra-fel
