### ISSUE TITLE
[BUG]Failed to load Automation tasks templates, throwing error "No Task templates found in this region, please try a using a resource located in a different region where Logic Apps is available. 

### ISSUE THREAD

**Issue by Sonalmz** [Azure/azure-sdk-for-net#37800]
### Library name and version

null

### Describe the bug

Automation task in Azure VM throwing error "No Task templates found in this region, please try a using a resource located in a different region where Logic Apps is available."

![image](https://github.com/Azure/azure-sdk-for-net/assets/140363581/1a032f8b-84df-4edf-8876-ef8cd3c5531c)

### Expected behavior

![image](https://github.com/Azure/azure-sdk-for-net/assets/140363581/ab2bb479-26c3-4c24-a189-c365917522ce)

### Actual behavior

In the HAR traces, We can't see any error and details of all 4 templates retrieved, but in console logs we see the below js error because of which no templates are visible in portal.
 
source: Ema.Client.Automation.Templates
stack: Error: Failed to fetch all templates: Failed to fetch
    at new t (https://portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:57:857)
    at u ([https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/BXa_RrLZvdoM.js:7:600](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fafd-v2.hosting.portal.azure.net%2Fema%2FContent%2FDynamic%2FBXa_RrLZvdoM.js%3A7%3A600&data=05%7C01%7Csonal.moze%40microsoft.com%7Cbeb5358da28e4a0f73fe08db7d9aff14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638241876921458297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=0CezCkyZcG9q8P6j7bxClPReYgPQ4U3z05eTJZ0u4sM%3D&reserved=0))
    at Object.f [as logError] ([https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/BXa_RrLZvdoM.js:7:122](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fafd-v2.hosting.portal.azure.net%2Fema%2FContent%2FDynamic%2FBXa_RrLZvdoM.js%3A7%3A122&data=05%7C01%7Csonal.moze%40microsoft.com%7Cbeb5358da28e4a0f73fe08db7d9aff14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638241876921458297%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=UGq%2BmMpJIZK3Q60EyUHXisNHOVoVHX8qx%2F34bDVzZiw%3D&reserved=0))
    at n.<anonymous> ([https://afd-v2.hosting.portal.azure.net/ema/Content/Dynamic/yQeeTZmbhDdl.js:10:2388](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fafd-v2.hosting.portal.azure.net%2Fema%2FContent%2FDynamic%2FyQeeTZmbhDdl.js%3A10%3A2388&data=05%7C01%7Csonal.moze%40microsoft.com%7Cbeb5358da28e4a0f73fe08db7d9aff14%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638241876921614575%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hU8psU58YVhyL9LhbKAoW%2FXmU%2BDg5IuXGrR266kwYOg%3D&reserved=0))
    at https://portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:17:2806
    at Object.throw (https://portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:17:2911)
    at s (https://portal.azure.com/Content/Dynamic/Dv1seNw9hbMj.js:17:1690)
![image](https://github.com/Azure/azure-sdk-for-net/assets/140363581/22931b73-c670-48f9-8c6d-e10900f7c32c)

![image](https://github.com/Azure/azure-sdk-for-net/assets/140363581/bd65f379-9af3-46e8-88be-2f3b91a4b781)

![image](https://github.com/Azure/azure-sdk-for-net/assets/140363581/14753b6b-422b-4ffc-8341-10213091fc8b)

### Reproduction Steps

We were able to repro the same , the issue is intermittent.

![image](https://github.com/Azure/azure-sdk-for-net/assets/140363581/87846b59-7c38-455e-8b34-4501c84d6f0f)
![image](https://github.com/Azure/azure-sdk-for-net/assets/140363581/e4de754b-e3cb-4842-ab91-c6d520abca96)
![image](https://github.com/Azure/azure-sdk-for-net/assets/140363581/b9c7237e-90c5-4984-8847-f95feb1713e4)

**Comment by jsquire** [comment]
Hi @Sonalmz.  Thank you for reaching out and we regret that you're experiencing difficulties.  What you're describing appears to be related to the Azure portal and not one of the Azure SDK packages.  Unfortunately, this repository is focused on the Azure SDK for .NET - we're unable to assist with other Azure issues.  Your best path forward would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request).

I'm going to close this out;  if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
