### ISSUE TITLE
[BUG] ArgumentNullException When Accessing LogsSiteConfigResource

### ISSUE THREAD

**Issue by ievgen-pavlenko** [Azure/azure-sdk-for-net#37833]
### Library name and version

Azure.ResourceManager.AppService 1.0.2 & 1.1.0-beta.1 

### Describe the bug

Hello,

I'm encountering an issue with the Azure.ResourceManager.AppService NuGet package where an ArgumentNullException is thrown when attempting to retrieve the LogsSiteConfigResource. This problem is experienced in both versions 1.0.2 and the 1.1.0-beta.1.

## Details:

**Error message:**
"Value cannot be null. (Parameter 'uriString')"

**Stack Trace:**
```
System.ArgumentNullException : Value cannot be null. (Parameter 'uriString')
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.AppService.Models.AppServiceTableStorageApplicationLogsConfig.DeserializeAppServiceTableStorageApplicationLogsConfig(JsonElement element)
   at Azure.ResourceManager.AppService.Models.ApplicationLogsConfig.DeserializeApplicationLogsConfig(JsonElement element)
   at Azure.ResourceManager.AppService.SiteLogsConfigData.DeserializeSiteLogsConfigData(JsonElement element)
   at Azure.ResourceManager.AppService.WebAppsRestOperations.GetDiagnosticLogsConfigurationAsync(String subscriptionId, String resourceGroupName, String name, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppService.LogsSiteConfigResource.GetAsync(CancellationToken cancellationToken)
```

### Expected behavior

The expectation is to be able to successfully retrieve the LogsSiteConfigResource without any exceptions being thrown.

### Actual behavior

When trying to retrieve the LogsSiteConfigResource, the System.ArgumentNullException is thrown with the message "Value cannot be null. (Parameter 'uriString')".

### Reproduction Steps

Here's a snippet of the code that triggers the error:

```csharp
var client = new AzureClient(tokenCred);
var webSiteConfigId = LogsSiteConfigResource.CreateResourceIdentifier(subscriptionId, webAppResourceGroupName, webAppName);
var webSiteConfigResource = await client.GetLogsSiteConfigResource(webSiteConfigId).GetAsync();
```

### Environment

.NET SDK:
 Version:   7.0.306
 Commit:    f500069cb7

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22000
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.306\

IDE: Visual Studio 17.6.5

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
