### ISSUE TITLE
MSI AppAuthentication error `Token response is not in the expected format`

### ISSUE THREAD

**Issue by veturi** [Azure/azure-sdk-for-net#3808]
There is an issue with AppAuthentication library when running code on a local development environment. The AppAuthentication library executes `az account get-access-token` directly and if the default output format is changed to something else than JSON the call will fail and result in `AzureServiceTokenProviderException`.

Changing the Azure CLI default output format back to JSON fixes this but this causes an issue with Azure CLI output not being as human friendly as in table mode.

Preferred functionality for this would be to ignore the global default value for Azure CLI in AppAuthentication library and always use JSON for get-access-token requests so that the developer does not need to switch between the formats when using Azure CLI. Now using AppAuthentication lib forces the output format to JSON which makes the Azure CLI much less flexible tool for development and maintenance work.

Operating system: macOS Sierra 10.12.6
Visual Studio Code 1.17.2
Azure CLI 2.0.19

To reproduce the issue:
1. In Azure CLI execute `az configure` and change the default output format to table format
2. Attempt to request secret for example from KeyVault:
```
AzureServiceTokenProvider _tokenProvider = new AzureServiceTokenProvider();
var keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(_tokenProvider.KeyVaultTokenCallback));

var secret = await keyVaultClient.GetSecretAsync("https://<keyvaultname>.vault.azure.net/secrets/<secretname>");
```
3. Run the code and the following exception will be raised from the `GetSecretAsync()` function:

```
Unhandled Exception: Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/<guidhere>. Exception Message: Tried the following 2 methods to get an access token, but none of them worked.
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/<guidhere>. Exception Message: Tried to get token using Managed Service Identity. Unable to connect to the Managed Service Identity (MSI) endpoint. Please check that you are running on an Azure resource that has MSI setup.
Parameters: Connectionstring: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/<guidhere>. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired.  Token response is not in the expected format.

   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAccessTokenAsyncImpl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultCredential.<PostAuthenticate>d__9.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultCredential.<ProcessHttpRequestAsync>d__10.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultClient.<GetSecretWithHttpMessagesAsync>d__65.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<GetSecretAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CommonApp.API.Services.BlobStorageService.<Persist>d__2.MoveNext() in /Users/<user>/application/service.cs:line 24
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

**Comment by varunsh-msft** [comment]
Thanks for reporting this! This has been fixed in the latest version of the library.

**Comment by seshenoy** [comment]
@varunsh-msft   I referred to the latest library of AppAuthentication and accessing to get an MSI token using Visual Studio but getting the same error.
Details :
Code used :
  var azureServiceTokenProvider = new AzureServiceTokenProvider();
            //Request an access token to other Azure services
            var accessToken = await azureServiceTokenProvider.GetAccessTokenAsync("<App Id of Target >");

AppAuthentication Library : 1.2.0-preview2

Error : 
Parameters: Connection String: [No connection string specified], Resource: 078eb22a-6cbe-4eb6-ab5a-cf61aa91e8a9, Authority: . Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. 
Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : TS003: Error, TS004: Unable to get access token. 'Failed to refresh access token'

**Comment by varunsh-msft** [comment]
It looks like you tried to get token for resource 078eb22a-6cbe-4eb6-ab5a-cf61aa91e8a9, which is not an Azure resource. For such cases, Visual Studio/ CLI does not work. You need to use an explicit service principal credential. Please refer [this ](https://docs.microsoft.com/en-us/azure/key-vault/service-to-service-authentication#authenticating-to-custom-services)for the exact steps.

**Comment by seshenoy** [comment]
@varunsh-msft I am unclear how you recognized that 078eb22a-6cbe-4eb6-ab5a-cf61aa91e8a9 is not an Azure Resource. This is the resource id of the app service on Azure : /subscriptions/<Hidden>/resourceGroups/<Hidden>/providers/Microsoft.Web/sites/<hidden>

If I execute the following scripts on powershell : 
$web=Get-AzureADServicePrincipal -SearchString "MyHiddenAppName"
$web.appId

I get 078eb22a-6cbe-4eb6-ab5a-cf61aa91e8a9 as the app id.... it even has MSI turned on and therefore an object Id as well... 

Can you still confirm that I still need to create a separate service principal ?

**Comment by varunsh-msft** [comment]
What I meant is that it is not an Azure service. Azure services that support Azure AD authentication are listed [here](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/services-support-managed-identities#azure-services-that-support-azure-ad-authentication) along with their resource Ids. It is not one of those resource Ids. So, you need to create a separate service principal for this scenario.
