### ISSUE TITLE
[BUG] AzureLocation not supporting NULL check

### ISSUE THREAD

**Issue by abiisnn** [Azure/azure-sdk-for-net#38128]
### Library name and version

Azure.Core 1.32.0

### Describe the bug

ThanksI'm migrating Microsoft.Azure.Management.ResourceManager.Fluent.Core to Azure.Core which main changes are changing **[Region](https://learn.microsoft.com/en-us/dotnet/api/microsoft.azure.management.resourcemanager.fluent.core.region?view=azure-dotnet)** to **[AzureLocation](https://learn.microsoft.com/en-us/dotnet/api/azure.core.azurelocation.-ctor?view=azure-dotnet#azure-core-azurelocation-ctor(system-string))**.

We had the following code:

```
using Microsoft.Azure.Management.ResourceManager.Fluent.Core;
private Region _region;

if (_region == null) 
{
   _region = Region.Create(displayName);
}
```
When I tried to migrate it to now use AzureLocation:

```
using Microsoft.Azure.Management.ResourceManager.Fluent.Core;
private AzureLocation _location;

if (_location == null) 
{
   _location = new AzureLocation(displayName);
}
```

it didn't work, I got the following error, pointing to the line where I'm comparing `_location == null`, not where I'm setting` _location = new AzureLocation` .

```
Error Message:
   System.ArgumentNullException : Value cannot be null. (Parameter 'location')
  Stack Trace:
     at Azure.Core.AzureLocation..ctor(String location)
   at Azure.Core.AzureLocation.op_Implicit(String location)
```

I ended finding a workaround so I don't have to compare` _location == null`, but I saw something similar was reported before #34818 and you didn't find a way to reproduce it.

Should we be able to compare `_location == null`?

### Expected behavior

- Give a better error message

### Actual behavior

The following error is thrown
```
Error Message:
   System.ArgumentNullException : Value cannot be null. (Parameter 'location')
  Stack Trace:
     at Azure.Core.AzureLocation..ctor(String location)
   at Azure.Core.AzureLocation.op_Implicit(String location)
```

### Reproduction Steps

Added in description

**Comment by abiisnn** [comment]
Thank you for answering!
