### ISSUE TITLE
[BUG] Azure.Identity 1.8.0+ throws Exception Attempting Managed Identity in Local Dev Env

### ISSUE THREAD

**Issue by czb182** [Azure/azure-sdk-for-net#38136]
### Library name and version

Azure.Identity 1.8.2

### Describe the bug

When updating Azure.Identity from 1.7.0 to 1.8.0 or higher I am now  getting exceptions on ManagedIdentity.    I am use Azure CLI in my local environment.  This is happening in my .NET V4 Azure Function running on core-tools.

Azure Functions Core Tools
Core Tools Version:       4.0.5198 Commit hash: N/A  (64-bit)
Function Runtime Version: 4.21.1.20667

I suspect it is trying various authentication methods using DefaultAzureCredential and logging the failure from trying Managed Identity.  If that is the case, seems like that should be hidden from me.  Or maybe there should (or already is) way to stop it from trying ManagedIdentity on my local environment.

[2023-08-10T16:03:13.035Z] False MSAL 4.54.1.0 MSAL.NetCore .NET 6.0.16 Microsoft Windows 10.0.19045 [2023-08-10 16:03:13Z - b2881984-ccc1-4415-9854-6782137aee04] Exception type: Azure.Identity.CredentialUnavailableException
[2023-08-10T16:03:13.036Z] ---> Inner Exception Details
[2023-08-10T16:03:13.037Z] Exception type: System.AggregateException
[2023-08-10T16:03:13.037Z] ---> Inner Exception Details
[2023-08-10T16:03:13.038Z] Exception type: Azure.RequestFailedException
[2023-08-10T16:03:13.039Z] ---> Inner Exception Details
[2023-08-10T16:03:13.039Z] Exception type: System.Net.Http.HttpRequestException
[2023-08-10T16:03:13.040Z] ---> Inner Exception Details
[2023-08-10T16:03:13.041Z] Exception type: System.Net.Sockets.SocketException
[2023-08-10T16:03:13.042Z]
[2023-08-10T16:03:13.043Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[2023-08-10T16:03:13.044Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[2023-08-10T16:03:13.045Z]    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
[2023-08-10T16:03:13.045Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2023-08-10T16:03:13.046Z] === End of inner exception stack trace ===
[2023-08-10T16:03:13.047Z]
[2023-08-10T16:03:13.047Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2023-08-10T16:03:13.048Z]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-08-10T16:03:13.049Z]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-08-10T16:03:13.049Z]    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)[2023-08-10T16:03:13.050Z]    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[2023-08-10T16:03:13.051Z]    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-08-10T16:03:13.051Z]    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[2023-08-10T16:03:13.052Z]    at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2023-08-10T16:03:13.053Z]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[2023-08-10T16:03:13.054Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2023-08-10T16:03:13.054Z] === End of inner exception stack trace ===
[2023-08-10T16:03:13.055Z]
[2023-08-10T16:03:13.058Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2023-08-10T16:03:13.059Z]    at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
[2023-08-10T16:03:13.060Z]    at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-08-10T16:03:13.061Z]    at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-08-10T16:03:13.062Z]    at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-08-10T16:03:13.063Z]    at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-08-10T16:03:13.064Z]    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-08-10T16:03:13.064Z] === End of inner exception stack trace ===
[2023-08-10T16:03:13.065Z]
[2023-08-10T16:03:13.065Z]    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2023-08-10T16:03:13.066Z]    at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2023-08-10T16:03:13.067Z]    at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2023-08-10T16:03:13.068Z] === End of inner exception stack trace ===
[2023-08-10T16:03:13.069Z]
[2023-08-10T16:03:13.069Z]    at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2023-08-10T16:03:13.072Z]    at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2023-08-10T16:03:13.073Z]    at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
[2023-08-10T16:03:13.073Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToProviderAsync(CancellationToken cancellationToken)
[2023-08-10T16:03:13.074Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.FetchNewAccessTokenAsync(CancellationToken cancellationToken)
[2023-08-10T16:03:13.075Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
[2023-08-10T16:03:13.076Z]    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)

### Expected behavior

Now Exceptions throw

### Actual behavior

Throwing Exception

### Reproduction Steps

have not tried to create minimal

### Environment

.NET SDK:
 Version:   7.0.400
 Commit:    73bf45718d

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.400\

Host:
  Version:      7.0.10
  Architecture: x64
  Commit:       a6dbb800a4

**Comment by jsquire** [comment]
Hi @czb182.   Thank you for reaching out and we regret that you're experiencing difficulties.   The behavior that you're seeing is normal and expected.   `DefaultAzureCredential` is a chained credential that attempts authentication with a number of sources and in a specific order.   The exception that you're seeing is handled internally and not surfaced to callers.  You are seeing it only because the Azure Functions runtime hooks the Azure SDK log source and forwards it to its own logs.

Using [DefaultCredentialOptions](https://learn.microsoft.com/dotnet/api/azure.identity.defaultazurecredentialoptions?view=azure-dotnet), you can configure which credentials are active in the chain and turn sources off that you know that you won't be authenticating with.  Likewise, you could use one of the more specific credentials (such as `VisualStudioCredential` for local development) to scope auth to just the source that you'd like it to use.
