### ISSUE TITLE
[BUG] Unable to get Data Factory pipeline when @if() exists in setVariable activity

### ISSUE THREAD

**Issue by derekdevv** [Azure/azure-sdk-for-net#38197]
### Library name and version

Azure.ResourceManager.DataFactory (1.0.0-beta.3)

### Describe the bug

In my console app, i have code below to get an ADF pipeline and create a run
```
ArmClient client = new ArmClient(new ClientSecretCredential(tenantID, appId, secret));
var subs = client.GetSubscriptions();
ResourceGroupResource resourceGroup = subs.Get(subscriptionId).Value.GetResourceGroup(resourceGroup);
var adf = resourceGroup.GetDataFactory(dataFactory);
var pipeline = adf.Value.GetDataFactoryPipeline(pipeline]);
pipeline.Value.CreateRun();
```
my pipeline is configured as below

```
{
    "name": "pipelineName",
    "properties": {
        "activities": [
            {
                "name": "Set variable1",
                "type": "SetVariable",
                "dependsOn": [],
                "policy": {
                    "secureOutput": false,
                    "secureInput": false
                },
                "userProperties": [],
                "typeProperties": {
                    "variableName": "start",
                    "value": {
                        "value": "@if(true, '1','2')",
                        "type": "Expression"
                    }
                }
            }
        ],
        "variables": {
            "start": {
                "type": "String",
                "defaultValue": "3"
            }
        },
        "annotations": [],
        "lastPublishTime": "2023-08-14T17:35:22Z"
    },
    "type": "Microsoft.DataFactory/factories/pipelines"
}
```

### Expected behavior

The console app should be able to get the pipeline for
`var pipeline = adf.Value.GetDataFactoryPipeline(pipeline]);`

### Actual behavior

the line `var pipeline = adf.Value.GetDataFactoryPipeline(pipeline]);`
throws the error below
```
System.InvalidOperationException
  HResult=0x80131509
  Message=The converter specified on 'Azure.Core.Expressions.DataFactory.DataFactoryElement`1[System.BinaryData]' is not compatible with the type 'Azure.Core.Expressions.DataFactory.DataFactoryElement`1[System.BinaryData]'.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializationConverterOnAttributeNotCompatible(Type classTypeAttributeIsOn, MemberInfo memberInfo, Type typeToConvert)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetConverterFromAttribute(JsonConverterAttribute converterAttribute, Type typeToConvert, MemberInfo memberInfo, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetConverterForType(Type typeToConvert, JsonSerializerOptions options, Boolean resolveJsonConverterAttribute)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.CreateJsonTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Metadata.DefaultJsonTypeInfoResolver.GetTypeInfo(Type type, JsonSerializerOptions options)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoNoCaching(Type type)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Text.Json.JsonSerializerOptions.GetTypeInfoInternal(Type type, Boolean ensureConfigured, Boolean resolveIfMutable)
   at System.Text.Json.JsonSerializer.GetTypeInfo(JsonSerializerOptions options, Type inputType)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Azure.ResourceManager.DataFactory.Models.SetVariableActivity.DeserializeSetVariableActivity(JsonElement element)
   at Azure.ResourceManager.DataFactory.Models.PipelineActivity.DeserializePipelineActivity(JsonElement element)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineData.DeserializeDataFactoryPipelineData(JsonElement element)
   at Azure.ResourceManager.DataFactory.PipelinesRestOperations.Get(String subscriptionId, String resourceGroupName, String factoryName, String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineCollection.Get(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at Azure.ResourceManager.DataFactory.DataFactoryResource.GetDataFactoryPipeline(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at [my console app name].<Main>d__9.MoveNext() in [my local path]

  This exception was originally thrown at this call stack:
    [External Code]
    [my console app name](string[]) in Program.cs
```

### Reproduction Steps

Create a pipeline with setVariable activity, within the activity use `@if() ` to set the variable value.
Then in a console app with the Azure.ResourceManager.DataFactory (1.0.0-beta.3) try to get the pipeline

```
ArmClient client = new ArmClient(new ClientSecretCredential(tenantID, appId, secret));
var subs = client.GetSubscriptions();
ResourceGroupResource resourceGroup = subs.Get(subscriptionId).Value.GetResourceGroup(resourceGroup);
var adf = resourceGroup.GetDataFactory(dataFactory);
var pipeline = adf.Value.GetDataFactoryPipeline(pipeline]);
pipeline.Value.CreateRun();
```

### Environment

Target framework
.NET 7.0

Microsoft Visual Studio Professional 2022 (64-bit) - Current
Version 17.5.1

**Comment by JoshLove-msft** [comment]
Looks like we are missing the `DataFactoryElement<BinaryData>` case here - https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core.Expressions.DataFactory/src/DataFactoryElementJsonConverter.cs#L15

**Comment by garethrzs** [comment]
I'm getting the same issue as above. Is there a solution?
