### ISSUE TITLE
Operation Is Not Valid due to the current state of the object exception on Service Bus Receiver reconnection. 

### ISSUE THREAD

**Issue by hart0349** [Azure/azure-sdk-for-net#38360]
We have a windows service that have a ServiceBus Receiver processing messages. Upon restart and our Service Bus Receiver instance are connected immediately we are getting errorHandler invoked with "Operation is not valid due to the current state of the object."

We can repeat the behavior by pumping messages and creating a dummy receiver and put artificial delay < peeklock timeout and killing the exe.  We tried setting the autocomplete message mode to off thinking that the auto-complete is messing with this, but we still see the same behavior. 

The service is long running, is there a need to recycle Service Bus Receiver from time to time ?

The nuget package: Azure.Messaging.ServiceBus (7.12.0) - Microsoft.Azure.Amqp (2.6.1)

The full stack:
Source: Microsoft.Azure.Amqp
       StackTrace:    at Microsoft.Azure.Amqp.WorkCollection`3.StartWork(TKey key, TWork work)
   at Microsoft.Azure.Amqp.ReceivingAmqpLink.<>c.<DisposeMessageAsync>b__37_0(DisposeParam p, TimeSpan t, CancellationToken k, AsyncCallback c, Object s)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl[TArg1,TArg2,TArg3](Func`6 beginMethod, Func`2 endFunction, Action`1 endAction, TArg1 arg1, TArg2 arg2, TArg3 arg3, Object state, TaskCreationOptions creationOptions)
   at Microsoft.Azure.Amqp.ReceivingAmqpLink.DisposeMessageAsync(ArraySegment`1 deliveryTag, ArraySegment`1 txnId, Outcome outcome, Boolean batchable, TimeSpan timeout)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<DisposeMessageAsync>d__49.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<>c.<<AbandonAsync>b__53_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__22`1.<<RunOperation>b__22_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__23`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__23`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.Amqp.AmqpReceiver.<AbandonAsync>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Messaging.ServiceBus.ServiceBusReceiver.<AbandonMessageAsync>d__50.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Azure.Messaging.ServiceBus.ReceiverManager.<ProcessOneMessage>d__17.MoveNext()
       TargetSite: Void StartWork(TKey, TWork)
       Type: System.InvalidOperationException

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Hi @hart0349,
Are you able to share your service shutdown code so we can better understand the application lifecycle?

It's also worth noting that there have been several reliability fixes in the Service Bus and underlying AMQP libraries since the versions that you are on.
