### ISSUE TITLE
[BUG] An exception is thrown when trying to load Nullable<int> datatype from AzureTableStorage 

### ISSUE THREAD

**Issue by Jimmy-Ahmed** [Azure/azure-sdk-for-net#38409]
### Library name and version

Azure.Data.Tables 12.8.1

### Describe the bug

Hi,

I have the below code

```
await var result = this.tableClient.Query<TEntity>().AsQueryable().ToList();

public abstract class RequestEntity: ITableEntity
{
    public virtual int Id { get; set; }

    public virtual int? Quantity { get; set; }

    // other properties
}
```

I cannot use this.tableClient.QueryAsync as I build my queries dynamically using IQueryable

An exception is being thrown, when I change the "Quantity " from int? to strinng. it works as expected.

### Expected behavior

Data should be loaded.

### Actual behavior

I am getting the below exception

Unable to cast object of type 'System.String' to type 'System.Nullable`1[System.Int32]'.

   at Azure.Data.Tables.TablesTypeBinder.TryGet[T](BoundMemberInfo memberInfo, IDictionary`2 source, T& value)
   at Azure.Core.TypeBinder`1.BoundMemberInfo`1.Deserialize(TExchange source, Object o, TypeBinder`1 binderImplementation)
   at Azure.Core.TypeBinder`1.BoundTypeInfo.Deserialize[T](TExchange source)
   at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntityList[T](IReadOnlyList`1 entityList)
   at Azure.Data.Tables.TableClient.<>c__DisplayClass56_0`1.<Query>b__0(Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.<>c__DisplayClass12_0`1.<CreateEnumerable>b__0(String _, Nullable`1 pageSizeHint)
   at Azure.Core.PageableHelpers.FuncPageable`1.<AsPages>d__4.MoveNext()
   at Azure.Pageable`1.<GetEnumerator>d__8.MoveNext()
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

### Reproduction Steps

Run my code

### Environment

VS2022
Windows 11

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by Jimmy-Ahmed** [comment]
I just tried `var x1 = this.tableClient.QueryAsync<RequestEntity>().ToListAsync().Result;` and got the same error.
