### ISSUE TITLE
[FEATURE REQ] Allow disabling of AzureMonitorStatsbeat.GetVmMetadataResponse for non-azure hosted use.

### ISSUE THREAD

**Issue by jakenuts** [Azure/azure-sdk-for-net#38419]
### Library name

Azure.Monitor.OpenTelemetry.Exporter

### Please describe the feature.

While this message indicates it can be safely ignored, it is a bit disconcerting to see this long exception stack trace in every single run of a project using this library locally or on non-Azure platforms. It would be great if you could signal that you don't want this to occur knowing that you are not running on Azure.

OpenTelemetry-AzureMonitor-Exporter - EventId: [10], EventName: [VmMetadataFailed], Message: [Failed to get Azure VM Metadata due to an exception. If not hosted in an Azure VM this can safely be ignored. System.AggregateException: One or more errors occurred. (A socket operation was attempted to an unreachable network. (xxx.xxx.xxx.xxx:80))
 ---> System.Net.Http.HttpRequestException: A socket operation was attempted to an unreachable network. (xxx.xxx.xxx.xxx:80)
 ---> System.Net.Sockets.SocketException (10051): A socket operation was attempted to an unreachable network.
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
   at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
   at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|281_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.WaitForConnectionAsync(Boolean async, CancellationToken requestCancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.GetStringAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---]

**Comment by navba-MSFT** [comment]
Adding Service team to look into this

**Comment by TimothyMothra** [comment]
Hi @jakenuts, you can disable this by setting the Environment Variable `APPLICATIONINSIGHTS_STATSBEAT_DISABLED` to `true`
