### ISSUE TITLE
What? 429 is a valid status code...

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#3848]
`Message d197e0bf-1c37-4483-bfb1-5a19d04615fd Workflow 'Create' had exception Microsoft.Rest.Azure.CloudException: Operation returned an invalid status code '429'
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperations.<CheckExistenceWithHttpMessagesAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsOperationsExtensions.<CheckExistenceAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourceGroupsImpl.<CheckExistenceAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at AzCacheRP.Provisioning.ResourceGroupResource.<CreateAsync>d__24.MoveNext() in `

https://en.wikipedia.org/wiki/List_of_HTTP_status_codes#4xx_Client_errors

Reproed with Fluent SDK 1.2.0

**Comment by hovsepm** [comment]
This looks like a bug in swagger spec for resource manager - https://github.com/Azure/azure-rest-api-specs/blob/current/specification/resources/resource-manager/Microsoft.Resources/2017-05-10/resources.json#L664 
429 is not modeled there so it by design that it throws `invalid status code` in client runtime

**Comment by hovsepm** [comment]
On another thought 429 should be handled in ClientRuntime for all the requests IMHO

**Comment by darrelmiller** [comment]
@hovsepm An OpenAPI specification is not supposed to be an exhaustive list of status codes and can never be due to the existence of HTTP intermediaries that are unknown to the API provider.  Throwing an invalid status code error because a status code is not defined in the OpenAPI definition is a fundamentally broken approach.  The HTTP specification is very clear in how clients should interpret status codes they don't explicitly handle. https://tools.ietf.org/html/rfc7231#section-6

**Comment by hovsepm** [comment]
@darrelmiller That should again be handled in ClientRuntime. My point is that it is not a Fluent SDK specific issue but an issue in common client runtime and should be fixed across the libraries.

**Comment by darrelmiller** [comment]
@hovsepm Sorry, I got hung up on your first comment about the client runtime throwing exceptions by design.  I missed your later comment about 429 being handled for all requests.

**Comment by shahabhijeet** [comment]
@hovsepm CR will deal with status codes if it's a LRO, I don't see RG CheckExistence being an LRO operation.
Can you clarify what scenarios should CR handle when dealing with status codes.

**Comment by TimLovellSmith** [comment]
@hovsepm I don't think the runtime needs additional behavior in the form of autoretry etc. It's just that having an error message that it is an 'invalid status code' is a really confusing thing to do! There's nothing invalid about it, it's defined by standard.

**Comment by shahabhijeet** [comment]
@TimLovellSmith if you still encounter issue, please open a new issue.
