### ISSUE TITLE
[BUG] GetServiceFabricClusters / Iterating over clusters results in exception

### ISSUE THREAD

**Issue by 23min** [Azure/azure-sdk-for-net#38666]
### Library name and version

Azure.ResourceManager.ServiceFabric 1.0.1

### Describe the bug

When listing the Service Fabric Clusters in a resource group, an execption occurs which results in no clusters retrieved. 

### Expected behavior

GetServiceFabricClusters results in a collection of clusters that can be iterated over.

### Actual behavior

Exception occurs

Message:
Error: 
```
One of the identified items was in an invalid format.
```

Stack trace:
```
   at Azure.ResourceManager.ServiceFabric.Models.ClusterAadSetting.DeserializeClusterAadSetting(JsonElement element)
   at Azure.ResourceManager.ServiceFabric.ServiceFabricClusterData.DeserializeServiceFabricClusterData(JsonElement element)
   at Azure.ResourceManager.ServiceFabric.ServiceFabricClusterCollection.<GetAll>b__10_1(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetEnumerator>d__17.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

### Reproduction Steps

Unsure whether any specific conditions need to be satisfied for this. 
We have a ServiceFabric cluster in our subscription.
Redacted JSON from Resource Explorer is available if needed.

### Environment

.Net 6
Azure Functions v4
Subscription is hosted in northeurope

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by dvbb** [comment]
Hi @23min

> at Azure.ResourceManager.ServiceFabric.Models.ClusterAadSetting.DeserializeClusterAadSetting(JsonElement element)

Based on the Stack trace you showed, this is a deserialization issue, it is some actual response values do not match the SDK-defined type, could you provide the response body to help us quickly find the issue?
