### ISSUE TITLE
[BUG] Deserialization problem on MapsRoutingClient.GetDirections

### ISSUE THREAD

**Issue by patrickhacens** [Azure/azure-sdk-for-net#38719]
### Library name and version

Azure.Maps.Routing

### Describe the bug

> Happens on both 1.0.0-beta.1  and 1.0.0-beta.2

During `MapsRoutingClient.GetDirectionsAsync` the following exception is thrown:

> System.InvalidOperationException: 'The requested operation requires an element of type 'String', but the target element has type 'Number'.'

StackTrace:
>    at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at Azure.Maps.Routing.Models.RouteInstruction.DeserializeRouteInstruction(JsonElement element)
   at Azure.Maps.Routing.Models.RouteGuidance.DeserializeRouteGuidance(JsonElement element)
   at Azure.Maps.Routing.Models.RouteData.DeserializeRouteData(JsonElement element)
   at Azure.Maps.Routing.Models.RouteDirections.DeserializeRouteDirections(JsonElement element)
   at Azure.Maps.Routing.RouteRestClient.<GetRouteDirectionsAsync>d__18.MoveNext()
   at Azure.Maps.Routing.MapsRoutingClient.<GetDirectionsAsync>d__16.MoveNext()
   at Program.<<<Main>$>g__WithAzureMaps|0_0>d.MoveNext() in C:\Users\patri\source\repos\Tester\ConsoleApp1\Program.cs:line 74
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\patri\source\repos\Tester\ConsoleApp1\Program.cs:line 19
   at Program.<Main>(String[] args)

It seems to have some problems during the deserialization of the response

### Expected behavior

The Actual response from the API

### Actual behavior

Exception

### Reproduction Steps

```csharp
var credential = new AzureKeyCredential("[credential key]");
var routeClient = new MapsRoutingClient(credential);

var routeOptions = new RouteDirectionOptions
{
    TravelMode =  TravelMode.Truck,
    RouteType = RouteType.Economy,
    InstructionsType = RouteInstructionsType.Text,
    Language = RoutingLanguage.EnglishUsa,
};

var query = new RouteDirectionQuery(new[]
{
    new GeoPosition(-88.117999999999995, 43.224960000000003),
    new GeoPosition(-111.11321, 45.67727)
}, routeOptions);

var routeResponse = await routeClient.GetDirectionsAsync(query);
```

### Environment

Windows 11 Pro 22621.2134
```
.NET SDK:
 Version:   7.0.304
 Commit:    7e794e2806

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.304\

Host:
  Version:      7.0.7
  Architecture: x64
  Commit:       5b20af47d9

.NET SDKs installed:
  7.0.100 [C:\Program Files\dotnet\sdk]
  7.0.304 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.18 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  Not found
```

Visual Studio 2022 64 bit
Version 17.6.4

**Comment by patrickhacens** [comment]
Downloaded the source code and run it today.
The problem is specific to the `roundaboutExitNumber` in the `RouteInstruction` type

setting it to int seems to resolve the issue, although the documentation specify it to be a string
https://learn.microsoft.com/en-us/rest/api/maps/route/get-route-directions?tabs=HTTP#routeinstruction
