### ISSUE TITLE
[BUG] Inconsistent serialization for decimal

### ISSUE THREAD

**Issue by MarkMpn** [Azure/azure-sdk-for-net#38854]
### Library name and version

Azure.Monitor.Ingestion 1.0.0, Azure.Monitor.Query 1.2.0

### Describe the bug

There appears to be an inconsistency between how Azure.Monitor.Ingestion serializes decimal values and how Azure.Monitor.Query deserializes them, leading to an error when I try to read a value I've previously written.

During serialization the value is written as a number (as expected), but the deserializer is expecting a string and throws an `InvalidOperationException`.

### Expected behavior

The number should be deserialized as a decimal.

### Actual behavior

An `InvalidOperationException` is thrown when trying to deserialize the decimal value.

### Reproduction Steps

Define a class to hold the record to log, including a decimal value, e.g.

```csharp
class MyLogEntry
{
  public string Name { get; set; }
  public decimal? Value { get; set; }
}
```

Add some records to Azure Log Analytics using the `LogsIngestionClient`:

```csharp
var values = new[]
{
  new MyLogEntry { Name = "Test1", Value = 1 },
  new MyLogEntry { Name = "Test2", Value = 2 }
};

var ingestionClient = new LogsIngestionClient(endpoint, new DefaultAzureCredential());
ingestionClient.Upload(immutableId, streamName, values);
```

Wait for the records to be ingested, then try to read them back using the `LogsQueryClient`:

```csharp
var queryClient = new LogsQueryClient(new DefaultAzureCredential());
var queryResult = queryClient.QueryWorkspace<MyLogEntry>(workspaceId, @"
  CustomTableName_CL
  | order by TimeGenerated desc
  | take 10",
  new QueryTimeRange(TimeSpan.FromDays(1)));
```

Instead of returning the two records, this throws an exception:

```
System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Number'.
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at Azure.Monitor.Query.Models.LogsTableRow.GetDecimal(Int32 index)
   at Azure.Monitor.Query.RowBinder.TryGet[T](BoundMemberInfo memberInfo, LogsTableRow source, T& value)
   at Azure.Core.TypeBinder`1.BoundMemberInfo`1.Deserialize(TExchange source, Object o, TypeBinder`1 binderImplementation)
   at Azure.Core.TypeBinder`1.BoundTypeInfo.Deserialize[T](TExchange source)
   at Azure.Monitor.Query.RowBinder.BindResults[T](IReadOnlyList`1 tables)
   at Azure.Monitor.Query.LogsQueryClient.QueryWorkspace[T](String workspaceId, String query, QueryTimeRange timeRange, LogsQueryOptions options, CancellationToken cancellationToken)
   at Program.Main()
```

### Environment

Windows 11, .NET 6
Visual Studio 17.5.4

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
