### ISSUE TITLE
[BUG] System.UriFormatException is thrown when list galleries

### ISSUE THREAD

**Issue by krizex** [Azure/azure-sdk-for-net#38912]
### Library name and version

Azure.ResourceManager.Compute 1.1.0

### Describe the bug

The SDK throws exception `System.UriFormatException` if the "publisherUri" field of a community gallery is not an URI. Please note Azure portal does not check the URI when creating the gallery.

```
Got Azure Exception in: AzureRmClientWrapper.GetGalleriesAsync, try handle it: System.UriFormatException: Invalid URI: The format of the URI could not be determined.
   at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
   at Azure.ResourceManager.Compute.Models.CommunityGalleryInfo.DeserializeCommunityGalleryInfo(JsonElement element)
   at Azure.ResourceManager.Compute.Models.SharingProfile.DeserializeSharingProfile(JsonElement element)
   at Azure.ResourceManager.Compute.GalleryData.DeserializeGalleryData(JsonElement element)
   at Azure.ResourceManager.Compute.GalleryCollection.<GetAllAsync>b__9_2(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at System.Linq.AsyncEnumerable.SelectEnumerableAsyncIterator`2.<MoveNextCore>d__7.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/Operators/Select.cs:line 221
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Linq.AsyncIteratorBase`1.<MoveNextAsync>d__8.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 70
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Linq.AsyncIteratorBase`1.<MoveNextAsync>d__8.MoveNext() in /_/Ix.NET/Source/System.Linq.Async/System/Linq/AsyncIterator.cs:line 75
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Linq.AsyncEnumerableEx.<DoCore>d__56`1.MoveNext() in /_/Ix.NET/Source/System.Interactive.Async/System/Linq/Operators/Do.cs:line 310
```

<img width="1188" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/3365993/d366ecaf-0e70-4bda-9d7b-3e3030064dcd">

### Expected behavior

No exception

### Actual behavior

System.UriFormatException thrown

### Reproduction Steps

Create a gallery whose "publisherUri" is not a valid URL, e.g. "Not.a.valid.uri"

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by krizex** [comment]
Hi @HarveyLink , this issue blocks us to enumerate the galleries. Is there any update?

**Comment by HarveyLink** [comment]
Hi @krizex , issue fixed, expected to ship in next release.

**Comment by krizex** [comment]
@HarveyLink Cool, thank you!
