### ISSUE TITLE
[BUG] OperationalInsightsTableCollection - The requested operation requires an element of type 'String', but the target element has type 'True'.    at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException

### ISSUE THREAD

**Issue by trouden** [Azure/azure-sdk-for-net#38915]
### Library name and version

Azure.ResourceManager 1.7.0, Azure.ResourceManager.OperationalInsights 1.1.0

### Describe the bug

Based on this example: https://learn.microsoft.com/en-us/rest/api/loganalytics/tables/get?tabs=dotnet#tablesget 
The code throws a JsonElementWrongTypeException.

```
// get the collection of this OperationalInsightsTableResource
OperationalInsightsTableCollection collection = operationalInsightsWorkspace.GetOperationalInsightsTables();

// invoke the operation
string tableName = "AppEvents";
bool result = await collection.ExistsAsync(tableName);
```

Stacktrace:

```
The requested operation requires an element of type 'String', but the target element has type 'True'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at Azure.ResourceManager.OperationalInsights.OperationalInsightsTableData.DeserializeOperationalInsightsTableData(JsonElement element)
   at Azure.ResourceManager.OperationalInsights.TablesRestOperations.GetAsync(String subscriptionId, String resourceGroupName, String workspaceName, String tableName, CancellationToken cancellationToken)
   at Azure.ResourceManager.OperationalInsights.OperationalInsightsTableCollection.ExistsAsync(String tableName, CancellationToken cancellationToken)
   at imec.PartnerMatrix.Cli.PartnerMatrixDeployment.DoEnsureResourcesAsync(IDeploymentContext context) in F:\Projects\IMEC\imec.PartnerPortal\src\imec.PartnerMatrix.Cli\PartnerMatrixDeployment.cs:line 92
   at Dlw.Platina.DevOps.Provision.AbstractDevOpsDeployment.EnsureResourcesAsync(IDeploymentContext context)
   at Dlw.Platina.DevOps.Provision.Cli.ProvisionCommand'1.EnsureResources(ResourceNaming resourceNamespace, T deployment, IDeploymentContext context)
   at Dlw.Platina.DevOps.Provision.Cli.ProvisionCommand'1.DoExecute()
   at Dlw.Platina.DevOps.Cli.CliCommand.Execute()
```

The actual JSON returned:

```
{
    "properties": {
        "totalRetentionInDays": 90,
        "archiveRetentionInDays": 0,
        "plan": "Analytics",
        "retentionInDaysAsDefault": true,
        "totalRetentionInDaysAsDefault": true,
        "schema": {
            "tableSubType": "Any",
            "name": "AppEvents",
            "tableType": "Microsoft",
            "standardColumns": [
                {
                    "name": "TenantId",
                    "type": "guid",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "TimeGenerated",
                    "type": "datetime",
                    "description": "Date and time when customEvent was recorded.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "Name",
                    "type": "string",
                    "description": "Human-readable name of the customEvent.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "Properties",
                    "type": "dynamic",
                    "description": "Application-defined properties.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "Measurements",
                    "type": "dynamic",
                    "description": "Application-defined measurements.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "OperationName",
                    "type": "string",
                    "description": "Application-defined name of the overall operation. The OperationName values typically match the Name values for AppRequests.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "OperationId",
                    "type": "string",
                    "description": "Application-defined operation ID.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ParentId",
                    "type": "string",
                    "description": "ID of the parent operation.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "SyntheticSource",
                    "type": "string",
                    "description": "Synthetic source of the operation.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "SessionId",
                    "type": "string",
                    "description": "Application-defined session ID.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "UserId",
                    "type": "string",
                    "description": "Anonymous ID of a user accessing the application.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "UserAuthenticatedId",
                    "type": "string",
                    "description": "Persistent string that uniquely represents each authenticated user in the application.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "UserAccountId",
                    "type": "string",
                    "description": "Application-defined account associated with the user.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "AppVersion",
                    "type": "string",
                    "description": "Version of the application.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "AppRoleName",
                    "type": "string",
                    "description": "Role name of the application.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "AppRoleInstance",
                    "type": "string",
                    "description": "Role instance of the application.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ClientType",
                    "type": "string",
                    "description": "Type of the client device.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ClientModel",
                    "type": "string",
                    "description": "Model of the client device.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ClientOS",
                    "type": "string",
                    "description": "Operating system of the client device.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ClientIP",
                    "type": "string",
                    "description": "IP address of the client device.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ClientCity",
                    "type": "string",
                    "description": "City where the client device is located.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ClientStateOrProvince",
                    "type": "string",
                    "description": "State or province where the client device is located.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ClientCountryOrRegion",
                    "type": "string",
                    "description": "Country or region where the client device is located.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ClientBrowser",
                    "type": "string",
                    "description": "Browser running on the client device.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ResourceGUID",
                    "type": "string",
                    "description": "Unique, persistent identifier of an Azure resource.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "IKey",
                    "type": "string",
                    "description": "Instrumentation key of the Azure resource.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "SDKVersion",
                    "type": "string",
                    "description": "Version of the SDK used by the application to generate this telemetry item.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "ItemCount",
                    "type": "int",
                    "description": "Number of telemetry items represented by a single sample item.",
                    "isDefaultDisplay": true,
                    "isHidden": false
                },
                {
                    "name": "SourceSystem",
                    "type": "string",
                    "isDefaultDisplay": true,
                    "isHidden": false
                }
            ],
            "solutions": [
                "LogManagement"
            ],
            "isTroubleshootingAllowed": false
        },
        "provisioningState": "Succeeded",
        "retentionInDays": 90
    },
    "id": "/subscriptions/57c1b396-5b86-4aef-9148-d74c91181b02/resourceGroups/REDACTED/providers/Microsoft.OperationalInsights/workspaces/REDACTED/tables/AppEvents",
    "name": "AppEvents"
}
```

### Expected behavior

The JSON should be deserialized correctly.

### Actual behavior

A JsonElementWrongTypeException is thrown.

### Reproduction Steps

The example here https://learn.microsoft.com/en-us/rest/api/loganalytics/tables/get?tabs=dotnet#tablesget doesn't work.

### Environment

Console App running on .NET 7

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
