### ISSUE TITLE
Error when trying to create function-app from within another functionapp

### ISSUE THREAD

**Issue by LjungqvistK** [Azure/azure-sdk-for-net#3920]
The following code produces the error below:
```
functionApp = _azureContext.AppServices.FunctionApps
                        .Define(appName)
                        .WithExistingAppServicePlan(appservicePlan)                        
                        .WithExistingResourceGroup(rgName)
                        .WithNewStorageAccount(SdkContext.RandomResourceName(myPrefix, 24), SkuName.StandardGRS)
                        .Create();
```

Other types of resources work fine to create (even when in a function-app), such as ServiceBus+Namespace and StorageAccounts.

Running the above code also works fine when running in a console-application.

I suspect it has to do with the specific NewtonSoft.Json version required by Microsoft.NET.Sdk.Functions (9.0.8), but I could ofcourse be wrong. 

StackTrace:
```
at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.Serialization.JsonSerializerProxy.DeserializeInternal(JsonReader reader, Type objectType)
at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
at Microsoft.Azure.Management.AppService.Fluent.WebAppsOperations.<CreateOrUpdateConfigurationWithHttpMessagesAsync>d__39.MoveNext()
```

```

**Comment by hovsepm** [comment]
@LjungqvistK please reopen this issue in Fluent SDK repo. https://github.com/Azure/azure-libraries-for-net/issues
