### ISSUE TITLE
Microsoft.Azure.OperationalInsights.Models.QueryResults is not null but throws NullReferenceException

### ISSUE THREAD

**Issue by jeroenwo** [Azure/azure-sdk-for-net#3969]
Hi,

I have created a unit test for my functionality. As it is not possible to Moq the `IOperationalInsightsDataClient` (see #3968), I have made a wrapper. I create an instance of `QueryResults` and provide that as the result in the unit test:
```csharp
[TestMethod]
public async Task TestRepository_NoLogAnalyticsData_ReturnsTrue()
{
    var clientMock = new Mock<ILogAnalyticsWrapper>();
            
    clientMock
        .Setup(x => x.QueryAsync(It.IsAny<string>(), null, null, default(CancellationToken)))
        .ReturnsAsync(new QueryResults()); // Return new instance of QueryResults.
            
    var repository = new LogAnalyticsTestRepository(clientMock.Object);
    var result = await repository.SuccessfulRetrieveAsync("query");

    Assert.IsTrue(result);
}
```

When checking the `QueryResults`: 
```csharp
public class LogAnalyticsTestRepository
{
    private readonly ILogAnalyticsWrapper _logAnalytics;

    public LogAnalyticsTestRepository(ILogAnalyticsWrapper logAnalytics)
    {
        _logAnalytics = logAnalytics ?? throw new ArgumentNullException(nameof(logAnalytics));
    }

    public async Task<bool> SuccessfulRetrieveAsync(string query)
    {
        var data = await _logAnalytics.QueryAsync(query);
            
        if (data?.Results == null || !data.Results.Any()) // Test the result.
        {
            return false;
        }
        return true;
    }
}
```
`data.Results` is not null:
![image](https://user-images.githubusercontent.com/13014081/34405156-00f0ea74-ebb2-11e7-805c-ef8dd178b510.png)

But the second evaluation (`!data.Results.Any()`) throws a NullReferenceException:
```
Test Name:	TestRepository_NoLogAnalyticsData_ReturnsTrue
Test FullName:	LogAnalyticsTestRepositoryTests.TestRepository_NoLogAnalyticsData_ReturnsTrue
Test Source:	 : line -1
Test Outcome:	Failed
Test Duration:	0:00:00.3307742

Result StackTrace:	
at Microsoft.Azure.OperationalInsights.Models.QueryResults.<get_Results>d__1.MoveNext()
   at System.Linq.Enumerable.Any[TSource](IEnumerable`1 source)
   at LogAnalyticsTestRepository.<SuccessfulRetrieveAsync>d__2.MoveNext() in C:\<enter project path here>Tests\LogAnalyticsTestRepository.cs:line 21
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Nextens.StatusDashboards.SystemResources.Tests.LogAnalyticsTestRepositoryTests.<TestRepository_NoLogAnalyticsData_ReturnsTrue>d__0.MoveNext() in C:\<enter project path here>Tests\LogAnalyticsTestRepositoryTests.cs:line 25
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.TestPlatform.MSTestAdapter.PlatformServices.ThreadOperations.ExecuteWithAbortSafety(Action action)
Result Message:	
Test method LogAnalyticsTestRepositoryTests.TestRepository_NoLogAnalyticsData_ReturnsTrue threw exception: 
System.NullReferenceException: Object reference not set to an instance of an object.
```
![image](https://user-images.githubusercontent.com/13014081/34405177-22fa5fec-ebb2-11e7-8b86-48f616548965.png)

The additional interface: 
```csharp
/// <summary>
/// Extension methods cannot be mocked with Moq. 
/// Abstract the extension method (QueryAsync of the Microsoft.Azure.OperationalInsights package)
/// so we can use it with Moq for unit testing purposes.
/// http://adventuresdotnet.blogspot.nl/2011/03/mocking-static-methods-for-unit-testing.html
/// </summary>
public interface ILogAnalyticsWrapper
{
    Task<QueryResults> QueryAsync(string query, TimeSpan? timespan = null, IList<string> workspaces = null, CancellationToken cancellationToken = default(CancellationToken));
}
```
And implementation of the wrapper:
```csharp
/// <inheritdoc />
public class LogAnalyticsWrapper : ILogAnalyticsWrapper
{
    private readonly IOperationalInsightsDataClient _operationalInsightsClient;

    public LogAnalyticsWrapper(IOperationalInsightsDataClient operationalInsightsClient)
    {
        this._operationalInsightsClient = operationalInsightsClient ?? throw new ArgumentNullException(nameof(operationalInsightsClient));
    }

    public async Task<QueryResults> QueryAsync(string query, TimeSpan? timespan = null, IList<string> workspaces = null, CancellationToken cancellationToken = default(CancellationToken))
    {
        return await _operationalInsightsClient.QueryAsync(query, timespan, workspaces, cancellationToken);
    }
}
```

Am I doing something wrong or is this strange behaviour? If something isn't `null`, it shouldn't throw a `NullReferenceException`..

**Comment by jsquire** [comment]
Closing this out as this refers to a legacy version of the library and there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
