### ISSUE TITLE
Azure.ResourceManager.CosmosDB.CosmosDBAccountResource.GetAsync fails deserializing the new "identity" property

### ISSUE THREAD

**Issue by thomas-hammond** [Azure/azure-sdk-for-net#39871]
### Library name and version

Azure.ResourceManager 1.8.1

### Describe the bug

When calling Azure.ResourceManager.CosmosDB.CosmosDBAccountResource.GetAsync, the underlying system attempts to deserialize the "identity" property on the CosmosDB resource. It fails with the following exception:

System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'String'.
  at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
  at System.Text.Json.JsonElement.EnumerateObject()
  at Azure.ResourceManager.Models.ManagedServiceIdentityTypeV3Converter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
  at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
  at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
  --- End of inner exception stack trace ---
  at System.Text.Json.ThrowHelper.ReThrowWithPath(ReadStack& state, Utf8JsonReader& reader, Exception ex)
  at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
  at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
  at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
  at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
  at Azure.ResourceManager.Models.ManagedServiceIdentity.DeserializeManagedServiceIdentity(JsonElement element, JsonSerializerOptions options)
  at Azure.ResourceManager.Models.ManagedServiceIdentity.ManagedServiceIdentityConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
  at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
  at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
  at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
  at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
  at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
  at Azure.ResourceManager.CosmosDB.CosmosDBAccountData.DeserializeCosmosDBAccountData(JsonElement element)
  at Azure.ResourceManager.CosmosDB.DatabaseAccountsRestOperations.GetAsync(String subscriptionId, String resourceGroupName, String accountName, CancellationToken cancellationToken)
  at Azure.ResourceManager.CosmosDB.CosmosDBAccountResource.GetAsync(CancellationToken cancellationToken)

### Expected behavior

The SDK call should correctly deserialize the resource.

### Actual behavior

The SDK fails with the exception shown in the description.

### Reproduction Steps

Call Azure.ResourceManager.CosmosDB.CosmosDBAccountResource.GetAsync on a CosmosDB resource.

### Environment

Windows 11, DotNet 7.0

**Comment by thomas-hammond** [comment]
Quick note: if I add a pipeline policy to remove the "identity" property, the code works fine, but this is only a short-term fix.

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by ArthurMa1978** [comment]
@thomas-hammond  thank you for reporting this issue, the 1.8.1 introduced unexpected breaking change so we have take back this release, and will update a new version soon.
