### ISSUE TITLE
[BUG] Sqlconnection created with MSAL access token option is getting object disposed exception with executing connection.OpenAsync

### ISSUE THREAD

**Issue by Manoj-Kothapalli-Microsoft** [Azure/azure-sdk-for-net#39916]
### Library name and version

Azure.Identity

### Describe the bug

We are currently eliminating the usage of ADAL packages in our cod which resulted in chnaging the access token generation code from ADAL to MSAL to connect to our SQL stores. We have made below changes and used ManagedIdentitiyCredential object to generate the token and assigned it to SqlConection object. Post deployment, we are experience frequent SqlConnection object disposed exception while using Msal token. When code is chnaged back to use Adal token it is working as expected. 

Note: The issue is very intermittent. We can see some success OpenAsync execution. after 3-4 calls immediately next call goes to error state

Code changes:

<img width="665" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/150523291/97f608b9-53f9-405a-a9ad-fc629fb636cf">

Error:

Exception: System.Data.SqlClient.SqlException (0x80131904): A network-related or instance-specific error occurred while establishing a connection to SQL Server. The server was not found or was not accessible. Verify that the instance name is correct and that SQL Server is configured to allow remote connections. (provider: TCP Provider, error: 35 - An internal exception was caught)
 ---> System.ObjectDisposedException: Cannot access a disposed object.
Object name: 'System.Net.Sockets.Socket'.
   at System.Net.Sockets.Socket.ThrowObjectDisposedException()
   at System.Net.Sockets.Socket.SetSocketOption(SocketOptionLevel optionLevel, SocketOptionName optionName, Int32 optionValue)
   at System.Data.SqlClient.SNI.SNITCPHandle..ctor(String serverName, Int32 port, Int64 timerExpire, Object callbackObject, Boolean parallel)
   at System.Data.ProviderBase.DbConnectionPool.CheckPoolBlockingPeriod(Exception e)
   at System.Data.ProviderBase.DbConnectionPool.CreateObject(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.UserCreateRequest(DbConnection owningObject, DbConnectionOptions userOptions, DbConnectionInternal oldConnection)
   at System.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location ---
   at Microsoft.Commerce.Billing.Storage.SqlCommandExecutor`1.Execute(CancellationToken cancellationToken, EventTraceActivity traceId) in C:\__w\1\s\private\Billing\shared\Common.Storage.Core\V1\SqlCommandExecutor.cs:line 187

### Expected behavior

SqlConnection should not error out at connection.OpenAsync() and should work how it works while using Adal access token. 

### Actual behavior

SqlConnection object OpenAsync is timeodout failing with exception mentioned in description.

### Reproduction Steps

using (SqlConnection connection = new SqlConnection(this.connectionString))
{
    connectionStopWatch.Restart();
    string aksManagedIdentityClientId = ServiceConfigurations.AKSManagedIdentityClientId;
    // Get Access token for SQLMI using AKS Managed identity if MSI ClientId(AppId) is not empty
    if (!string.IsNullOrEmpty(aksManagedIdentityClientId))
    {
        var tokenProvider = new ManagedIdentityCredential(aksManagedIdentityClientId);
        connection.AccessToken = tokenProvider.GetTokenAsync(new TokenRequestContext(new[]{ azureResourceSQLMI })).Result.Token;
    }
    await connection.OpenAsync(cancellationToken);
    connectionStopWatch.Stop();

### Environment

.NET, Azure.Identity - 1.10.3, System.Data.SqlClient - 4.6.1.5

**Comment by jsquire** [comment]
@Manoj-Kothapalli-Microsoft:  The stack trace indicates that the error has to do with network sockets used by `System.Data.ProviderBase.DbConnectionPool` being in a disposed state.  As this occurs after you've used `Azure.Identity` to acquire a token and associate it with a connection, the request for token acquisition has been successfully satisfied. 

This is not related to `Azure.Identity` which library neither mints tokens nor controls the SQL connection pool.  The Azure SDK team is unable to assist with this issue.  I'd suggest opening an issue in the [SqlClient](https://github.com/dotnet/SqlClient) repository for further discussion.
