### ISSUE TITLE
[BUG] "Unexpected end of file has occurred" error in Azure.Storage.Blobs

### ISSUE THREAD

**Issue by andrei-faber** [Azure/azure-sdk-for-net#39996]
### Library name and version

Azure.Storage.Blobs 12.16.0

### Describe the bug

Getting this exception randomly in Azure.Storage.Blobs called from Az.Storage 5.6.0:

```
2023-11-09T23:05:59.4286814Z Exception        : System.Xml.XmlException: Unexpected end of file has occurred. The following elements are not 
2023-11-09T23:05:59.4324629Z                    closed: Last-Modified, Properties, Blob, Blobs, EnumerationResults. Line 1, position 65215.
2023-11-09T23:05:59.4335195Z                       at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2023-11-09T23:05:59.4349384Z                       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
2023-11-09T23:05:59.4363313Z                       at System.Xml.XmlTextReaderImpl.ParseElementContent()
2023-11-09T23:05:59.4377925Z                       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
2023-11-09T23:05:59.4391701Z                       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
2023-11-09T23:05:59.4404042Z                       at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
2023-11-09T23:05:59.4418993Z                       at Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegment(String prefix, String marker, 
2023-11-09T23:05:59.4432017Z                    Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, CancellationToken 
2023-11-09T23:05:59.4449108Z                    cancellationToken)
2023-11-09T23:05:59.4471091Z                       at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, 
2023-11-09T23:05:59.4486407Z                    BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken 
2023-11-09T23:05:59.4505290Z                    cancellationToken)
2023-11-09T23:05:59.4521537Z                       at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, 
2023-11-09T23:05:59.4528909Z                    Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
2023-11-09T23:05:59.4541387Z                       at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2023-11-09T23:05:59.4553957Z                       at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.AsPages(String continuationToken, 
2023-11-09T23:05:59.4566248Z                    Nullable`1 pageHintSize)+MoveNext()
2023-11-09T23:05:59.4585914Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByPref
2023-11-09T23:05:59.4658346Z                    ix(Int64 taskId, IStorageBlobManagement localChannel, String containerName, String prefix, Func`2 
2023-11-09T23:05:59.4658891Z                    blobFilter, Boolean includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.4659442Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByName
2023-11-09T23:05:59.4660065Z                    (Int64 taskId, IStorageBlobManagement localChannel, String containerName, String blobName, Boolean 
2023-11-09T23:05:59.4662196Z                    includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.4679451Z                       at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTa
2023-11-09T23:05:59.4689706Z                    sk(Int64 taskId, Task task)
2023-11-09T23:05:59.4703725Z Message          : Unexpected end of file has occurred. The following elements are not closed: Last-Modified, 
2023-11-09T23:05:59.4716872Z                    Properties, Blob, Blobs, EnumerationResults. Line 1, position 65215.
2023-11-09T23:05:59.4731451Z StackTrace       :    at System.Xml.XmlTextReaderImpl.Throw(Exception e)
2023-11-09T23:05:59.4741118Z                       at System.Xml.XmlTextReaderImpl.Throw(String res, String arg)
2023-11-09T23:05:59.4756183Z                       at System.Xml.XmlTextReaderImpl.ParseElementContent()
2023-11-09T23:05:59.4785888Z                       at System.Xml.Linq.XContainer.ReadContentFrom(XmlReader r)
2023-11-09T23:05:59.4800422Z                       at System.Xml.Linq.XDocument.Load(XmlReader reader, LoadOptions options)
2023-11-09T23:05:59.4813311Z                       at System.Xml.Linq.XDocument.Load(Stream stream, LoadOptions options)
2023-11-09T23:05:59.4826058Z                       at Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegment(String prefix, String marker, 
2023-11-09T23:05:59.4843339Z                    Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, CancellationToken 
2023-11-09T23:05:59.4853849Z                    cancellationToken)
2023-11-09T23:05:59.4873257Z                       at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, 
2023-11-09T23:05:59.4885694Z                    BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken 
2023-11-09T23:05:59.4939986Z                    cancellationToken)
2023-11-09T23:05:59.4958996Z                       at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, 
2023-11-09T23:05:59.4973311Z                    Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
2023-11-09T23:05:59.4994641Z                       at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2023-11-09T23:05:59.5009552Z                       at Azure.Storage.StorageCollectionEnumerator`1.StoragePageable.AsPages(String continuationToken, 
2023-11-09T23:05:59.5046172Z                    Nullable`1 pageHintSize)+MoveNext()
2023-11-09T23:05:59.5067706Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByPref
2023-11-09T23:05:59.5090293Z                    ix(Int64 taskId, IStorageBlobManagement localChannel, String containerName, String prefix, Func`2 
2023-11-09T23:05:59.5103729Z                    blobFilter, Boolean includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.5122139Z                       at Microsoft.WindowsAzure.Commands.Storage.Blob.Cmdlet.GetAzureStorageBlobCommand.ListBlobsByName
2023-11-09T23:05:59.5135690Z                    (Int64 taskId, IStorageBlobManagement localChannel, String containerName, String blobName, Boolean 
2023-11-09T23:05:59.5153513Z                    includeDeleted, Boolean includeVersion)
2023-11-09T23:05:59.5173087Z                       at Microsoft.WindowsAzure.Commands.Storage.Common.LimitedConcurrencyTaskScheduler.RunConcurrentTa
2023-11-09T23:05:59.5196098Z                    sk(Int64 taskId, Task task)
```

### Expected behavior

no exception

### Actual behavior

exception

### Reproduction Steps

```
    $context = New-AzStorageContext -StorageAccountName $backupStorage
    $blobs = Get-AzStorageBlob -Container $containerName -Context $context
```

See also https://github.com/Azure/azure-powershell/issues/23398

### Environment

Windows 10.0.20348

global.json file:
  Not found

Host:
  Version:      6.0.16
  Architecture: x64
  Commit:       1e620a42e7

.NET SDKs installed:
  No SDKs were found.

.NET runtimes installed:
  Microsoft.NETCore.App 6.0.16 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]

Az.Storage 5.6.0, Azure.Storage.Blobs 12.16.0

**Comment by seanmcc-msft** [comment]
See this comment from the PowerShell issue - https://github.com/Azure/azure-powershell/issues/23398#issuecomment-1818089590
