### ISSUE TITLE
[BUG] OpenAI JSON mode is broken

### ISSUE THREAD

**Issue by weng5e** [Azure/azure-sdk-for-net#40645]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.10

### Describe the bug

I am trying out the new JSON mode parameter in the new released SDK. It seems like that it is not working as expected. It is failing with 400 bad request complaining about the request body with JSON mode setup is invalid.

<img width="1231" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/22308724/040cada1-007c-4055-b6be-979c56511eae">

### Expected behavior

The api call should successfully finish

### Actual behavior

The api call failed with 400.

Error
```
Azure.RequestFailedException: 'json_object' is not of type 'object' - 'response_format'
Status: 400 (model_error)

Content:
{
  "error": {
    "message": "'json_object' is not of type 'object' - 'response_format'",
    "type": "invalid_request_error",
    "param": null,
    "code": null
  }
}


Headers:
Access-Control-Allow-Origin: REDACTED
x-ms-region: REDACTED
x-ratelimit-remaining-tokens: REDACTED
apim-request-id: REDACTED
X-Request-ID: REDACTED
ms-azureml-model-error-reason: REDACTED
ms-azureml-model-error-statuscode: REDACTED
x-ms-client-request-id: ad8c1b50-9e70-4e0e-9223-7744513905ee
x-ratelimit-remaining-requests: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
Date: Thu, 07 Dec 2023 17:45:08 GMT
Content-Length: 170
Content-Type: application/json

   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at Liftr.Sample.Web.Controllers.Gpt4ChatCompletionController.PostAsync(ChatRequestBody chatRequestBody) in C:\Git\LiftrTools\src\Samples\Liftr.Sample.Web\Controllers\Gpt4ChatCompletionController.cs:line 60
   at lambda_method82(Closure , Object )
   at 

HEADERS
=======
Accept: text/plain
Host: localhost:7521
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
:method: POST
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Content-Type: application/json
Cookie: ai_user=95bd3cYlO6N6Rs4tEBUsey|2023-11-30T18:50:22.774Z,.AspNetCore.Antiforgery.BiHL3w92asdasdpa6dk1nNxetfm4,CurrentUserContext=user222-token
Origin: https://localhost:7521
Referer: https://localhost:7521/swagger/index.html
Content-Length: 2734
sec-ch-ua: "Google Chrome";v="119", "Chromium";v="119", "Not?A_Brand";v="24"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty
```

### Reproduction Steps

Repro code:
```
private async Task ReproAsync()
{
    var azureOpenAIClient = _openAIClientFactory.GetGpt4OpenAIClient();

    var chatCompletionCreateRequest = new ChatCompletionsOptions()
    {
        Temperature = (float)0.7,
        MaxTokens = 800,
        NucleusSamplingFactor = (float)0.95,
        FrequencyPenalty = 0,
        PresencePenalty = 0,
        ResponseFormat = ChatCompletionsResponseFormat.JsonObject,
    };

    chatCompletionCreateRequest.Messages.Add(new ChatRequestSystemMessage("You are a good assitant."));
    chatCompletionCreateRequest.Messages.Add(new ChatRequestUserMessage("Who are you?"));

    using var ops = _logger.StartTimedOperation("gpt4ChatCompletion");
    try
    {
        chatCompletionCreateRequest.DeploymentName = "icr-gpt4-1106";
        Response<ChatCompletions> responseWithoutStream = await azureOpenAIClient.GetChatCompletionsAsync(chatCompletionCreateRequest);

        var chatCompletionResponse = responseWithoutStream.Value;
        _logger.Information("open_ai_chat. chatCompletionCreateRequest: {@chatCompletionCreateRequest}, chatCompletionResponse: {@chatCompletionResponse}", chatCompletionCreateRequest, chatCompletionResponse);
    }
    catch (Exception ex)
    {
        _logger.Error(ex, "open_ai_chat_fail");
        ops.FailOperation(ex.Message);
        throw;
    }
}
```

**Comment by trrwilson** [comment]
thanks; we're investigating this issue right now.

**Comment by weng5e** [comment]
@trrwilson Thank you so much for the quick turn around! It is working good now!
