### ISSUE TITLE
[BUG] AmbiguousMatchException in production and not development

### ISSUE THREAD

**Issue by justingden** [Azure/azure-sdk-for-net#40770]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.11

### Describe the bug

We have developed a solution using Azure OpenAI and calling the service works well in development. However, once we deploy to Azure Web Apps it fails with the following exception:
```
System.Reflection.AmbiguousMatchException
Multiple custom attributes of the same type found.

System.Reflection.AmbiguousMatchException: Multiple custom attributes of the same type found.
   at System.Attribute.GetCustomAttribute(Assembly element, Type attributeType, Boolean inherit)
   at System.Runtime.InteropServices.RuntimeInformation.get_FrameworkDescription()
   at Azure.Core.RuntimeInformationWrapper.get_FrameworkDescription()
   at Azure.Core.TelemetryDetails.GenerateUserAgentString(Assembly clientAssembly, String applicationId, RuntimeInformationWrapper runtimeInformation)
   at Azure.Core.TelemetryDetails..ctor(Assembly assembly, String applicationId, RuntimeInformationWrapper runtimeInformation)
   at Azure.Core.Pipeline.HttpPipelineBuilder.CreateTelemetryPolicy(ClientOptions options)
   at Azure.Core.Pipeline.HttpPipelineBuilder.BuildInternal(HttpPipelineOptions buildOptions, HttpPipelineTransportOptions defaultTransportOptions)
   at Azure.Core.Pipeline.HttpPipelineBuilder.Build(ClientOptions options, HttpPipelinePolicy[] perCallPolicies, HttpPipelinePolicy[] perRetryPolicies, ResponseClassifier responseClassifier)
   at Azure.AI.OpenAI.OpenAIClient..ctor(Uri endpoint, AzureKeyCredential keyCredential, OpenAIClientOptions options)
   at PI.Business.AI.AiChatManager..ctor(String endpoint, String key, String deploymentName) in [excluded]
   at PI.Web.Areas.Insights.Controllers.AIController.<ExecuteMethodInstance>d__19.MoveNext() in [excluded]
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass8_0.<BeginInvokeAsynchronousActionMethod>b__1(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_0.<InvokeActionMethodFilterAsynchronouslyRecursive>b__0()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass11_2.<InvokeActionMethodFilterAsynchronouslyRecursive>b__2()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass7_0.<BeginInvokeActionMethodWithFilters>b__1(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResult`1.CallEndDelegate(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncResultWrapper.WrappedAsyncResultBase`1.End()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_6.<BeginInvokeAction>b__4()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass3_1.<BeginInvokeAction>b__1(IAsyncResult asyncResult)
```

### Expected behavior

There is no exception thrown.

### Actual behavior

Throws the exception given in the description.

### Reproduction Steps

Using a .NET Framework 4.8 project: include the dependencies given in the Environment section; call constructor for Azure.AI.OpenAI.OpenAIClient with Uri endpoint, AzureKeyCredential keyCredential, and OpenAIClientOptions options; and deploy to Azure Web App.

### Environment

.NET Framework 4.8
Azure.Core v 1.36
Azure.AI.OpenAI 1.0.0-beta.11

Issue only occurs once deployed to Azure Web App configured for .NET 4.8 (it is unknown if there deployments will fail).

Project also includes Application Insights, which may or may not be involved:
Application Insights 2.22.0

**Comment by justingden** [comment]
The closest issue I have found has existed for quite a long time:
https://github.com/Azure/autorest/issues/1542

I have gone through this and tried many of the recommendations and nothing has resolved the issue.

One is that an older version of Application Insights may be causing a conflict, but the project is upgraded to the latest.

**Comment by jsquire** [comment]
//cc: @JoshLove-msft. @lmolkova:  Not sure if this is related to the OpenAI diagnostics use or indicates something in Core.   Would appreciate thoughts and, if needed, adding "Service Attention" to route to the OpenAI team.

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by justingden** [comment]
The reproduction steps as described will not recreate the issue. We have tried further with a simple repro project and have not been able to get it to fail in a web app. Unfortunately, our main application is much more complex, and isolating what else needs to be added to cause this scenario is unrealistic.

**Comment by justingden** [comment]
However, we have been digging deeper into the issue and it seems to be directly related to an attempt to construct the user agent for telemetry for HTTP pipeline in Azure.Core. The guidance for this process is given here:
https://azure.github.io/azure-sdk/general_azurecore.html
I am not sure what scenario would cause this type of failure during this process and it seems like something that should be caught and handled.

**Comment by justingden** [comment]
Based on the Azure Core code and the guidance, it is getting duplicate AssemblyInformationalVersion attributes from one of the Azure client libraries (references below). 

In the GenerateUserAgentString of the Telemetry detail class it is getting the attributes:
`AssemblyInformationalVersionAttribute? versionAttribute = clientAssembly.GetCustomAttribute<AssemblyInformationalVersionAttribute>();`

This is to satisfy the guidance for telemetry in Azure Core:
https://azure.github.io/azure-sdk/general_azurecore.html

At this point, I can deploy the web app to a new sandbox instance and the problem is eliminated in that instance but not our production one.

What could be causing this duplication?

**Comment by justingden** [comment]
In the end, I was able to resolve this issue by creating a new deployment slot which created a clean instance, and redeploying the app. However, I hope that someone addresses this issue with at least guidance on how to resolve it in the future as I see many other people reporting this issue with Azure Core over the years. I have backed up the instance that had this failure in case someone in development would like to look into the cause.

**Comment by JoshLove-msft** [comment]
One thought - were you always using the latest App Insights version on the faulty instance or were you initially using a different version?

**Comment by justingden** [comment]
Initially, we had an older version of App Insights in the project and updated it after the issue. It is possible that something was left behind somewhere. However, it is interesting it only happened once deployed. Azure Web Apps also has the ability to turn on App Insights without embedding it in your application. I don't know that it was ever turned on in the past, but it is possible.

**Comment by JoshLove-msft** [comment]
Given that things are working now, and there is a known issue involving older versions of the App Insights library that was initially deployed to your instance, it seems we can conclude that you were hitting the same underlying issue. I am going to close this out now but feel free to reopen if you wish to discuss further.
