### ISSUE TITLE
[BUG] Error in deserialization of DataFactoryPipelineResource

### ISSUE THREAD

**Issue by rlucassen** [Azure/azure-sdk-for-net#40850]
### Library name and version

Azure.ResourceManager.DataFactory 1.0.0-beta5

### Describe the bug

When retrieving DataFactoryPipelineResource from ArmClient it fails on deserializing of headers in AzureFunctionActivity.

```
System.InvalidCastException: Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.
   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Deserialize[T](JsonElement json)
   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCoreAsObject(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Azure.ResourceManager.DataFactory.Models.AzureFunctionActivity.DeserializeAzureFunctionActivity(JsonElement element)
   at Azure.ResourceManager.DataFactory.Models.PipelineActivity.DeserializePipelineActivity(JsonElement element)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineData.DeserializeDataFactoryPipelineData(JsonElement element)
   at Azure.ResourceManager.DataFactory.PipelinesRestOperations.GetAsync(String subscriptionId, String resourceGroupName, String factoryName, String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineResource.GetAsync(String ifNoneMatch, CancellationToken cancellationToken)
```

It seems that it tries to deserialize the following piece of JSON to `DataFactoryElement<string>`:
```
"headers": {
  "Authorization": {
    "value": "[removed]",
    "type": "Expression"
  }
}
```

### Expected behavior

Retrieve DataFactoryPipelineResource for a pipeline with Azure Function activities without any problems

### Actual behavior

Exception on deserializing json response

### Reproduction Steps

Create ADF pipeline with Azure Function Activity with headers.
```
var armClient = new ArmClient(tokenCredential, subscriptionId);
var dataFactoryPipelineResourceId = DataFactoryPipelineResource.CreateResourceIdentifier(subscriptionId, resourceGroup, dataFactoryName, pipelineName);
var dataFactoryPipelineResource = await client.GetDataFactoryPipelineResource(dataFactoryPipelineResourceId).GetAsync();
```

### Environment

.NET 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by JoshLove-msft** [comment]
Looks like the swagger definition was [recently fixed](https://github.com/Azure/azure-rest-api-specs/pull/26846) and we may just need to regen the library.

**Comment by ArthurMa1978** [comment]
Yes, ADF team is working on the fix, @ruowan for awareness.

**Comment by sdzunenko** [comment]
Have the same issues here: unable to get pipeline for run it programmatically. 

```csharp
 try
 {
     var pipeline = await GetDataFactoryClient().GetDataFactoryPipelineAsync(pipelineName, cancellationToken: ctx);
     if (!pipeline.HasValue)
         return new AdfPipelineResult(false, $"Pipeline with name '{pipelineName}' does not exists");

     var pipelineRun = await pipeline.Value.CreateRunAsync(parameters, cancellationToken: ctx);
     return new AdfPipelineResult(pipelineName, pipelineRun.Value.RunId, "Pipeline ran successfully");

 }
 catch (Exception ex)
 {
     logger.LogError(ex, "Pipeline '{pipelineName}' wan unable to start", pipelineName);
     return new AdfPipelineResult(false, ex.Message);
 }
```

Line `await GetDataFactoryClient().GetDataFactoryPipelineAsync(pipelineName, cancellationToken: ctx);` throwing following exception: 'Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.'

Is anybody working on that?

**Comment by three-little-birds** [comment]
+1

**Comment by ArthurMa1978** [comment]
Swagger was fixed and released new SDK.

**Comment by francisminu** [comment]
> Have the same issues here: unable to get pipeline for run it programmatically.
> 
> ```cs
>  try
>  {
>      var pipeline = await GetDataFactoryClient().GetDataFactoryPipelineAsync(pipelineName, cancellationToken: ctx);
>      if (!pipeline.HasValue)
>          return new AdfPipelineResult(false, $"Pipeline with name '{pipelineName}' does not exists");
> 
>      var pipelineRun = await pipeline.Value.CreateRunAsync(parameters, cancellationToken: ctx);
>      return new AdfPipelineResult(pipelineName, pipelineRun.Value.RunId, "Pipeline ran successfully");
> 
>  }
>  catch (Exception ex)
>  {
>      logger.LogError(ex, "Pipeline '{pipelineName}' wan unable to start", pipelineName);
>      return new AdfPipelineResult(false, ex.Message);
>  }
> ```
> 
> Line `await GetDataFactoryClient().GetDataFactoryPipelineAsync(pipelineName, cancellationToken: ctx);` throwing following exception: 'Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.'
> 
> Is anybody working on that?

Does anyone know why this error is thrown?

**Comment by sdzunenko** [comment]
> Swagger was fixed and released new SDK.

Didn't help. Have the same issue now with latest version. 
Something else that needs to be additionally done?
**It is impossible now for run ADF pipeline programmatically**, and this critical for us.
