### ISSUE TITLE
[BUG] Azure.Storage.Blobs >12.17.0 missing System.IO.Hashing dependency

### ISSUE THREAD

**Issue by magamig** [Azure/azure-sdk-for-net#40874]
### Library name and version

Azure.Storage.Blobs 12.17.0

### Describe the bug

During runtime of Azure.Storage.Blobs 12.17.0 I hit the following issue:

````
Failed to refresh blob: 2023-99-99 99:99:99Z/**/**.json, with exception: ** ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.IO.Hashing, Version=6.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' or one of its dependencies. The system cannot find the file specified.
   at Azure.Storage.Blobs.PartitionedDownloader.<DownloadToInternal>d__16.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   at Azure.Storage.Blobs.PartitionedDownloader.DownloadToInternal(Stream destination, BlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<StagedDownloadAsync>d__92.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__90.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.<DownloadToAsync>d__82.MoveNext()
````

However, System.IO.Hashing 6.0.0 is not referenced anywhere on its Dependencies:
![image](https://github.com/Azure/azure-sdk-for-net/assets/8484196/4fa5cd9e-3cdd-454e-8390-87bfcef777a2)

The previous version 12.12.0 I was using did not hit such issues.

### Expected behavior

No runtime issues

### Actual behavior

Hits runtime issues described above

### Reproduction Steps

Call ``Azure.Storage.Blobs.PartitionedDownloader.DownloadToInternal`` without including referencing System.IO.Hashing 6.0.0

### Environment

Windows Server 2022
.NET Framework 4.6.2

**Comment by seanmcc-msft** [comment]
@magamig, I'm not seeing this.  [Azure.Storage.Blobs v12.17.0](https://www.nuget.org/packages/Azure.Storage.Blobs/12.17.0#dependencies-body-tab) has a dependency on [Azure.Storage.Common v12.16.0](https://www.nuget.org/packages/Azure.Storage.Common/12.16.0#dependencies-body-tab), which has a dependency on System.IO.Hashing 6.0.0.
