### ISSUE TITLE
[BUG] Something Fuzzy is going on with the fileshareclient. (only in Core, .net481 is ok)

### ISSUE THREAD

**Issue by well0549** [Azure/azure-sdk-for-net#41146]
### Library name and version

Azure.Storage.Files.Shares" Version="12.17.1" 

### Describe the bug

Ok, This is quite a long explanation, so please bear with me. The function Executes a CompiledTransform with extensions. 

I have an Isolated-Azure function using the .Net Framework 4.81 (Consumption Plan)
I have an isolated-Azure Function using the .Net core (6.0) framework. (Conmsumption Plan)

Both functions run (virtually) the same code / Transformations.

I have a queue that is read and for each message in the queue a HTTP request is done to one of the transform functions.

So what the function does is the following:

- Receive a http Request
- Get Data from the header ( Source Blob Name, Transform Name, and optionally a storage account name with a storageaccount key)
- Read Xslt
- Read a file with extensions needed to perform the transformation
- Read all the extensions mentioned in the extension file. And put them in cache (bytearray)
- It will create a new compiled transform (with the extensions)
- It will perform the transformation
- Write the result back in a response blob
- return a http response.

If the storage account and accountkey is empty, it will load the dll from it's internal resources. If a storageaccount and a storageaccpount key is present in the header, it will download the files from the corresponding Azure File Share with the shareclient.

Each Call to the transformation will create a new fileshareclient (if accountname and key is Set). All the needed dll's are cached in a local byte array. So it will download each file only once. However, it will check each time if a specific directory exists on the fileshare. Some transformations could use other extensions or files.

My test stack is 1024 messages, Ther are uploaded to the queue and then the (Durable) Receive-function will call the Transform function.

For .Net 4.81, everything works fine. It will process all messages without problems. If I use the resources it works, and if I use a combination of StorageAccount and Account key, it works. Sometimes the function hosts cycles beacuse the temp folder is full (because of the compiles going on and we cannot delete files in the temp folders) But the durable function that calls the transform function has a retry set of 10 so eventually it will work. After a while everything is processed without problems.

If I do the same for .net Core (same map, same extensions but compiled to .net core6)  everything works fine when the dll's come from the inmternal resources. But if i switch to the FileShareClient (accountname and AccountKey) I get a permission denied error.

````
024-01-10T15:55:35.640 [Information] Returning Error: System.ObjectDisposedException: Cannot access a closed Stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)
   at HTTPTransformCoreIsolated.TransformCore.ExecuteTransformation(StringBuilder log, String transformName, String blobName, ConcurrentDictionary`2 mapCache, String storageAccount, String containerName, Connections connections)
   at HTTPTransformCoreIsolated.TransformCore.Run(HttpRequestData request)
````

But the thing is I am reading it from memory ! (from a byte array)

````
// Add an argument for each defined extension object
foreach (var extension in transformation.Extensions)
{
    FileInformation assemblyInfo = new FileInformation();
    assemblyInfo.FileName = Path.GetFileName(extension.AssemblyFileName);
    connections.LoadExtensionBinary(transformation.Name, assemblyInfo);
    var assembly = Assembly.Load(assemblyInfo.FileBytes);
    var type = assembly.GetType($"{extension.Namespace}.{extension.ClassName}");
    if (type == null)
        throw new Exception($"Cannot get type {extension.AssemblyName}");
    string ns = $"http://schemas.microsoft.com/BizTalk/2003/ScriptNS{counter}";
    arguments.AddExtensionObject(ns, Activator.CreateInstance(type)!);
    counter++;
}
````

It seems we get an error on Assembly.Load....

But this is exact the same piece code that runs ok in .net 4.81 (from resources and from share client) It runs also okay for .net Core 6.0, but not if it get's my data from the fileshareclient.

The number of messages is pretty consistent, it will process approx 868 messages without any problem but then it starts with the Error above.

I have to cycle the host completely to make this error go away.

So why i think this is somehow realated to the fileshare client is because of the fact that is the only difference i can see. 

It's strange that i get a 'Cannot access a closed Stream.
   at System.IO.MemoryStream.Seek(Int64 offset, SeekOrigin loc)' when i am reading from a byte array.

I have tried the Transformation on my local machine and there I can run thousands of transformations  without any problem, using the same code. (So im reading from the exact same files share, the exact same files, exact same caching mechanism)

The code i use to download a file from the fileshare client is:

````
       private byte[] LoadFilefromFileShare(ShareFileClient fileclient)
       {
           try
           {
               if (fileCache.ContainsKey(fileclient.Uri.AbsoluteUri))
               {
                   return fileCache[fileclient.Uri.AbsoluteUri];
               }
               else
               {
                   // Download the file
                   using (ShareFileDownloadInfo download = fileclient.Download())
                   {
                       using (MemoryStream stream = new MemoryStream())
                       {
                           download.Content.CopyTo(stream);
                           stream.Position = 0;
                           byte[] bytes = new byte[stream.Length];
                           stream.Read(bytes, 0, (int)stream.Length);
                           fileCache.TryAdd(fileclient.Uri.AbsoluteUri, bytes);
                           return bytes;
                       }
                   }
               }
           }
           catch (Exception ex)
           {
               throw;
           }
       }
````

### Expected behavior

Perform the Transformation.

Or when that is not possible Cycle the host (but that does unfortunately not happen)

### Actual behavior

Service will only give back the same error over and over

### Reproduction Steps

Really hard to repro because there is a lot of code/resources  involved.

Maybe i provided you with enough information to give a hint where to look.

### Environment

Fine on .net 4.81 in isolated host
Fine on .net core 6.0 on isolated-host (when not using fileshareclient)
Error on .net core 6.0 on isolated-host (when using fileshareclient)

**Comment by well0549** [comment]
Just some extra information, it is running on a consumption plan. As I run my tests, it scales out several instances. (4 to 8). Maybe it is related to that.

**Comment by well0549** [comment]
Had to do when the cache was instantiated. I instantiated the cache in the class. Now in the program. Issue is gone. Not a bug
