### ISSUE TITLE
[BUG] Storage DataMovement concurrent collection modification

### ISSUE THREAD

**Issue by ncoussemacq** [Azure/azure-sdk-for-net#41219]
### Library name and version

Azure.Storage.DataMovement 12.0.0-beta.4

### Describe the bug

I'm trying to use Azure.Storage.DataMovement library in a project and I'm randomly facing an exception at runtime when running a transfer in my unit tests.

> System.InvalidOperationException : Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.
Stack Trace:
 at System.Collections.Generic.Dictionary 2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
 at System.Collections.Generic.Dictionary 2.Add(TKey key, TValue value)
StorageHandler.UnitTests.BlobFolderHandlerUnitTests.CopyTo_BlobFolder_Succeeds(copyToSubPath: True) [FAIL]
 at Azure.Storage.DataMovement.TransferManager.BuildAndAddTransferJobAsync(StorageResource sourceResource, StorageResource destinationResource, DataTransferOptions transferOptions, String transferId, Boolean resumeJob, CancellationToken cancellationToken)
 at Azure.Storage.DataMovement.TransferManager.StartTransferAsync(StorageResource sourceResource, StorageResource destinationResource, DataTransferOptions transferOptions, CancellationToken cancellationToken)
 at Azure.Storage.Blobs.BlobContainerClientExtensions.StartUploadDirectoryAsync(BlobContainerClient client, String localDirectoryPath, BlobContainerClientTransferOptions options)
C:\__w\1\s\Components\VideoEncodingService\StorageHandler\BlobFolderHandler.cs(105,0): at StorageHandler.BlobFolderHandler.UploadFromAsync(IFolderHandler sourceFolder, Boolean overwrite, CancellationToken cancellationToken)
C:\__w\1\s\Components\VideoEncodingService\StorageHandler.UnitTests\BlobFolderHandlerUnitTests.cs(125,0): at StorageHandler.UnitTests.BlobFolderHandlerUnitTests.CopyTo_BlobFolder_Succeeds(Boolean copyToSubPath)
 --- End of stack trace from previous location ---

If it helps, line 105 of BlobFolderHandler.cs is pretty basic : 
`
var transfer = await _lazyBlobContainerClient.Value.StartUploadDirectoryAsync(localSource.Path, this._subDirectoryPath);
`

### Expected behavior

No exception should be raised

### Actual behavior

An InvalidOperationException is randomly raised when starting a file transfer

### Reproduction Steps

var transfer = await _lazyBlobContainerClient.Value.StartUploadDirectoryAsync(localSource.Path, this._subDirectoryPath);

### Environment
.NET 8

_No response_

**Comment by ncoussemacq** [comment]
Any Update on this ?

It seems that LocalTransferCheckpointer:AddNewJobAsync is not thread safe. Changing the type of _transferStates field from Dictionary<string, JobPlanFile>to ConcurrentDictionary<string, JobPlanFile> could be enough to fix the issue.
