### ISSUE TITLE
[BUG] Failed to SetMetadata with underscore and numbers at same string position in keys. 

### ISSUE THREAD

**Issue by ytyen** [Azure/azure-sdk-for-net#41328]
### Library name and version

Azure.Storage.Blobs 12.15.0 ~ 12.19.1

### Describe the bug

Failed to set metadata with some similar keys that are distinguished with underscore and numbers.
ex:
```plaintext
FOO_BAR
FOO2_BAR
```
I suspect the keys are being sorted in ordinal, not Lexicographical in some places. The document says the headers must be ordered lexicographically. https://learn.microsoft.com/en-us/rest/api/storageservices/authorize-with-shared-key#constructing-the-canonicalized-headers-string

This issue has also been observed when running .NET in Invariant Mode (`DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1`) with old Azure.Storage.Blobs (equal or below 12.14.1).

### Expected behavior

Response 200 and set metadata successfully.

### Actual behavior

Response 403
```plaintext
Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.
RequestId:....skipped....
Time:2024-01-17T04:01:28.8639123Z
Status: 403 (Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.)
ErrorCode: AuthenticationFailed

Additional Information:
AuthenticationErrorDetail: The MAC signature found in the HTTP request '....skipped....' is not the same as any computed signature. Server used following string to sign: 'PUT











x-ms-client-request-id:....skipped....
x-ms-date:Wed, 17 Jan 2024 04:01:28 GMT
x-ms-meta-foo_bar:111
x-ms-meta-foo2_bar:222
x-ms-return-client-request-id:true
x-ms-version:2021-10-04
....skipped....
comp:metadata'.
```

```plaintext
at Azure.Storage.Blobs.BlobRestClient.SetMetadata(Nullable`1 timeout, IDictionary`2 metadata, String leaseId, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, String ifMatch, String ifNoneMatch, String ifTags, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.SetMetadataInternal(IDictionary`2 metadata, BlobRequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.SetMetadata(IDictionary`2 metadata, BlobRequestConditions conditions, CancellationToken cancellationToken)
```

### Reproduction Steps

```charp
var dict = new Dictionary<string, string>();
dict.Add("FOO_BAR", "111");
dict.Add("FOO2_BAR", "222");

blobClient.SetMetadata(dict);
```

**Comment by seanmcc-msft** [comment]
@ytyen, the service does not support metadata values containing `_`.
