### ISSUE TITLE
[BUG] BlobBatchClient.DeleteBlobsAsync fails with "Server failed to authenticate the request" error

### ISSUE THREAD

**Issue by pacoteinnov** [Azure/azure-sdk-for-net#41363]
### Library name and version

Azure.Storage.Blobs.Batch 12.16.1

### Describe the bug

When trying to delete blobs in a batch, an "Server failed to authenticate the request" is thrown by BlobBatchClient.DeleteBlobsAsync.

It works without using a batch.

It works by using the CLI.

Same error with BlobBatch.DeleteBlob + SubmitBatchAsync (throwOnAnyFailure = true).

### Expected behavior

No exception and file deleted.

### Actual behavior

Exception thrown by BlobBatchClient.DeleteBlobsAsync:
```
System.AggregateException
  HResult=0x80131500
  Message=1 batch operation(s) failed. (Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bceccbe1-b01e-0042-4e7b-49303b1ee966
Time:2024-01-17T19:26:58.6238936Z
Status: 401 (Server failed to authenticate the request. Please refer to the information in the www-authenticate header.)
ErrorCode: NoAuthenticationInformation

Content:
﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bceccbe1-b01e-0042-4e7b-49303b1ee966
Time:2024-01-17T19:26:58.6238936Z</Message></Error>

Headers:
x-ms-error-code: NoAuthenticationInformation
x-ms-request-id: bceccbe1-b01e-0042-4e7b-49303b1ee966
x-ms-version: 2023-11-03
x-ms-client-request-id: 79b87d3c-1ee0-4eeb-9d03-433f81fc7222
Content-Length: 303
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/<redacted>/oauth2/authorize resource_id=https://storage.azure.com
)
  Source=Azure.Storage.Blobs.Batch
  StackTrace:
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<UpdateOperationResponses>d__38.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<SubmitBatchInternal>d__36.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<DeleteBlobsInteral>d__41.MoveNext()
   at Azure.Storage.Blobs.Specialized.BlobBatchClient.<DeleteBlobsAsync>d__40.MoveNext()
   at ReproBatchDeleteAzure.Program.<Main>d__0.MoveNext() in C:\Users\pacote\source\repos\ReproBatchDeleteAzure\Program.cs:line 29

  This exception was originally thrown at this call stack:
    Azure.Storage.Blobs.Specialized.BlobBatch.DeleteBlob.AnonymousMethod__24_0(Azure.Response)
    Azure.Storage.Blobs.Specialized.DelayedResponse.SetLiveResponse(Azure.Response, bool)
    Azure.Storage.Blobs.Specialized.BlobBatchClient.UpdateOperationResponses(System.Collections.Generic.IList<Azure.Core.HttpMessage>, Azure.Response, bool, bool, System.Threading.CancellationToken)

Inner Exception 1:
RequestFailedException: Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bceccbe1-b01e-0042-4e7b-49303b1ee966
Time:2024-01-17T19:26:58.6238936Z
Status: 401 (Server failed to authenticate the request. Please refer to the information in the www-authenticate header.)
ErrorCode: NoAuthenticationInformation

Content:
﻿<?xml version="1.0" encoding="utf-8"?>
<Error><Code>NoAuthenticationInformation</Code><Message>Server failed to authenticate the request. Please refer to the information in the www-authenticate header.
RequestId:bceccbe1-b01e-0042-4e7b-49303b1ee966
Time:2024-01-17T19:26:58.6238936Z</Message></Error>

Headers:
x-ms-error-code: NoAuthenticationInformation
x-ms-request-id: bceccbe1-b01e-0042-4e7b-49303b1ee966
x-ms-version: 2023-11-03
x-ms-client-request-id: 79b87d3c-1ee0-4eeb-9d03-433f81fc7222
Content-Length: 303
Content-Type: application/xml
Server: Windows-Azure-Blob/1.0
WWW-Authenticate: Bearer authorization_uri=https://login.microsoftonline.com/<redacted>/oauth2/authorize resource_id=https://storage.azure.com
```

### Reproduction Steps

```
string storageAccountName = "<ACCOUNT_NAME>";
string containerName = "<CONTAINER_NAME>";
string filename = "<EXISTING_FILENAME>";

BlobServiceClient blobServiceClient =
    new(
        new Uri($"https://{storageAccountName}.blob.core.windows.net"),
        new DefaultAzureCredential()
    );

BlobContainerClient blobContainerClient = blobServiceClient.GetBlobContainerClient(
    containerName
);

// Does not work
{
    BlobBatchClient blobBatchClient = new(blobContainerClient);

    await blobBatchClient.DeleteBlobsAsync(
        new[] { blobContainerClient.GetBlobClient(filename).Uri }
    );
}

// Works
{
    await blobContainerClient.DeleteBlobAsync(filename);
}

// This works
// az storage blob delete-batch --account-name $storageAccountName --source $containerName --pattern $filename
}
```

**Comment by seanmcc-msft** [comment]
@pacoteinnov, what RBAC roles are assigned to your service principal or AAD app?  The Least privileged built-in role is Storage Blob Data Contributor - https://learn.microsoft.com/en-us/rest/api/storageservices/blob-batch?tabs=microsoft-entra-id#permissions

**Comment by pacoteinnov** [comment]
@seanmcc-msft Thanks for the repsone.  I might have used a principal without the Storage Blob Data Contributor role.  We have a settled to use more fine-grained roles and we use the workaround of not using a batch.
