### ISSUE TITLE
[FEATURE REQ]: Support passing the fully qualified name to the service bus client without having to trim it

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-sdk-for-net#41785]
### Library name

Azure.Messaging.ServiceBus

### Please describe the feature.

This is the value that comes back from the RP and it's strange that the SDK doesn't support it without me having to remove the scheme (https://).

Here is the error message:

```
ArgumentException: The value 'https://<redacted>.servicebus.windows.net' is not a well-formed Service Bus fully qualified namespace. (Parameter 'fullyQualifiedNamespace')

at Azure.Core.Argument.AssertWellFormedServiceBusNamespace(String argumentValue, String argumentName)
   at Azure.Messaging.ServiceBus.ServiceBusConnection..ctor(String fullyQualifiedNamespace, TokenCredential credential, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusConnection.CreateWithCredential[TCredential](String fullyQualifiedNamespace, TCredential credential, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String fullyQualifiedNamespace, Object credential, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String fullyQualifiedNamespace, TokenCredential credential, ServiceBusClientOptions options)
   at Microsoft.Extensions.Hosting.AspireServiceBusExtensions.MessageBusComponent.<>c__DisplayClass0_0`1.<AddClient>b__0(ServiceBusClientOptions options, TokenCredential cred) in C:\dev\git\aspire\src\Components\Aspire.Azure.Messaging.ServiceBus\AspireServiceBusExtensions.cs:line 77
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__DisplayClass8_0`2.<Azure.Core.Extensions.IAzureClientFactoryBuilderWithCredential.RegisterClientFactory>b__0(TOptions options, TokenCredential credential, IServiceProvider _)
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__DisplayClass15_0`2.<RegisterClientFactory>b__0(IServiceProvider provider, Object options, TokenCredential credential)
   at Microsoft.Extensions.Azure.ClientRegistration`1.GetClient(IServiceProvider serviceProvider, Object options, TokenCredential tokenCredential)
   at Microsoft.Extensions.Azure.AzureClientFactory`2.CreateClient(String name)
   at Microsoft.Extensions.Azure.AzureClientFactoryBuilder.<>c__15`2.<RegisterClientFactory>b__15_1(IServiceProvider provider)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(ServiceIdentifier serviceIdentifier)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(ServiceIdentifier serviceIdentifier, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at lambda_method16(Closure, Object, HttpContext)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)
```

**Comment by jsquire** [comment]
Added via #41819.  This will ship as part of the Feb releases.
