### ISSUE TITLE
[BUG] NullReferenceException in Azure.Core.Pipeline.StorageRequestFailedDetailsParser.TryParse

### ISSUE THREAD

**Issue by vrozovmicrosoft** [Azure/azure-sdk-for-net#41845]
### Library name and version

Azure.Storage.Blobs – 12.16.0

### Describe the bug

NullReferenceException after a failure in enumerating blobs

The call to:
IAsyncEnumerator<BlobItem> enumerator ...
enumerator.MoveNextAsync().AsTask().ConfigureAwait(false).GetAwaiter().GetResult();
Ended with NullReferenceException 

Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Core.Pipeline.StorageRequestFailedDetailsParser.TryParse(Response response, ResponseError& error, IDictionary`2& data)
   at Azure.RequestFailedException.GetRequestFailedExceptionContent(Response response, RequestFailedDetailsParser parser)
   at Azure.Core.Pipeline.ClientDiagnostics.<CreateRequestFailedExceptionAsync>d__6.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Azure.Storage.Blobs.ContainerRestClient.<ListBlobFlatSegmentAsync>d__56.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobContainerClient.<GetBlobsInternal>d__77.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.<GetNextPageAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.<GetAsyncEnumerator>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at System.Threading.Tasks.ValueTask`1.ValueTaskSourceAsTask.<>c.<.cctor>b__4_0(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

### Expected behavior

Actual failure exception

### Actual behavior

NullReferenceException 

### Reproduction Steps

No steps to reproduce, happened once

**Comment by zhouwangzw** [comment]
I have seen similar exception in Azure.Storage.Blobs 12.19.1.0

Error when adding request to request store (retries:0). Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Azure.Core.Pipeline.StorageRequestFailedDetailsParser.TryParse(Response response, ResponseError& error, IDictionary`2& data)
   at Azure.RequestFailedException.GetRequestFailedExceptionContent(Response response, RequestFailedDetailsParser parser)
   at Azure.RequestFailedException..ctor(Response response, Exception innerException, RequestFailedDetailsParser detailsParser)
   at Azure.RequestFailedException..ctor(Response response, Exception innerException)
   at Azure.RequestFailedException..ctor(Response response)
   at Azure.Storage.Blobs.ContainerRestClient.ListBlobFlatSegmentAsync(String prefix, String marker, Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.AsPages(String continuationToken, Nullable`1 pageHintSize)+MoveNext()
   at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.AsPages(String continuationToken, Nullable`1 pageHintSize)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()

**Comment by seanmcc-msft** [comment]
@vrozovmicrosoft, please try to reproduce on the latest version (Azure.Storage.Blobs v12.23.0), and provide a code snippet to repo if you are able to reproduce.

**Comment by jalauzon-msft** [comment]
The `NullReferenceException` was very likely just fixed with #48268.

However, this indicates that your request failed for another reason, and we just had trouble parsing the response. Likely it was a response that did not come from Storage and therefore did not contain the expected XML fields. The linked PR makes the parsing more lenient and therefore you would then be able to see the actual exception that occurred.

This will be fixed in our next version so I'm going to close this but please open a new issue if the issue persists after trying the new version that will be released.
