### ISSUE TITLE
CheckExistenceByIdWithHttpMessagesAsync returning 405 Method Not Allowed

### ISSUE THREAD

**Issue by AaronFixer** [Azure/azure-sdk-for-net#4210]
I have a task running against several resources in my system and I am checking if they exist. I am calling the following async method. This call uses service principal credentials in the `ResourceManagement Client`.

    var resourceExists = await resourceClient.Resources.CheckExistenceByIdWithHttpMessagesAsync(resource.Id, resourceTypeGroup.ApiVersions[0]); 

This makes the following API call: 

https://management.azure.com//subscriptions/{Subscription}/resourceGroups/{RG}/providers/Microsoft.Network/networkInterfaces/{NI Name}?api-version=2018-04-01

If I do the same call locally through Postman, I get a success and the state of my resources. 

The API is causing an exception with a `Method Not Allowed` error: 

```
Microsoft.Rest.Azure.CloudException: Operation returned an invalid status code 'MethodNotAllowed'
   at Microsoft.Azure.Management.ResourceManager.Fluent.ResourcesOperations.<CheckExistenceByIdWithHttpMessagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

This seems to happen with all resources, so its a problem with the library, not the API calls.

**Comment by AaronFixer** [comment]
This actually seems to be a problem with the endpoints. Not the library, using a HEAD method returns the same error for me with the REST API.
