### ISSUE TITLE
[BUG] Incorrect path when trying to upload files using memorystream on storage accounts with path routing behind application gateway

### ISSUE THREAD

**Issue by erorubrz** [Azure/azure-sdk-for-net#42155]
### Library name and version

Azure.Storage.Blobs 12.19.1

### Describe the bug

Hello everyone,

we are using [MemoryStream](https://learn.microsoft.com/en-us/azure/storage/blobs/storage-blob-upload#upload-a-block-blob-by-staging-blocks-and-committing) to upload content to our storage account. This works fine when connected directly to the storage account.

Now to the issue. We are currently accessing the storage account behind an application gateway and it is located under a path routing with rules etc. So it looks like this: `https://contoso.com/storage/`

I have tried using REST API to PUT data into the storage account inside a container and it works flawlessly. But when using the Storage SDK, the path of the destination file is completely broken.

So we are giving the URL of the storage account, which is `https://contoso.com/storage/`, the container name which is `pushes` and the file name which is `test.zip`. The resulting URL should be `https://contoso.com/storage/pushes/test.zip`, but when looking at the app gateway logs, I get this URL `https://contoso.com/storage/test.zip`. Somehow I believe the issue comes from the path routing from the app gateway. This will result in an error and the file will not be uploaded.

### Expected behavior

Actually uploading the file to the correct path.

### Actual behavior

So we are giving the URL of the storage account, which is `https://contoso.com/storage/`, the container name which is `pushes` and the file name which is `test.zip`. The resulting URL should be `https://contoso.com/storage/pushes/test.zip`, but when looking at the app gateway logs, I get this URL `https://contoso.com/storage/test.zip`. Somehow I believe the issue comes from the path routing from the app gateway. This will result in an error and the file will not be uploaded.

```
Azure.RequestFailedException: The specified container does not exist.
RequestId:5642e817-e01e-0076-1662-6591bb000000
Time:2024-02-22T07:41:35.3387482Z
Status: 404 (The specified container does not exist.)
ErrorCode: ContainerNotFound

Content:
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerNotFound</Code><Message>The specified container does not exist.
RequestId:5642e817-e01e-0076-1662-6591bb000000
Time:2024-02-22T07:41:35.3387482Z</Message></Error>

Headers:
Date: Thu, 22 Feb 2024 07:41:35 GMT
Connection: keep-alive
Server: Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0
x-ms-request-id: 5642e817-e01e-0076-1662-6591bb000000
x-ms-client-request-id: 261a9150-18cf-49a8-afd9-dee8e14e47d2
x-ms-version: 2023-11-03
x-ms-error-code: ContainerNotFound
Content-Type: application/xml
Content-Length: 225

   at Azure.Storage.Blobs.BlockBlobRestClient.StageBlock(String blockId, Int64 contentLength, Stream body, Byte[] transactionalContentMD5, Byte[] transactionalContentCrc64, Nullable`1 timeout, String leaseId, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, String encryptionScope, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.StageBlockInternal(String base64BlockId, Stream content, UploadTransferValidationOptions transferValidationOverride, BlobRequestConditions conditions, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlockBlobClient.StageBlock(String base64BlockId, Stream content, BlockBlobStageBlockOptions options, CancellationToken cancellationToken)
   at BlobUploadTest.Form1.UploadFileBlocks(BlockBlobClient blobClient, BlockBlobTransferStatus transferStatus, String fileName) in C:\Users\M01991\Infra\BlobUploadTest\BlobUploadTest\Form1.cs:line 115
   at BlobUploadTest.Form1.buttonUploadFile_Click(Object sender, EventArgs e) in C:\Users\M01991\Infra\BlobUploadTest\BlobUploadTest\Form1.cs:line 33
```

### Reproduction Steps

- Create Storage Account
- Create App Gateway
- Create DNS Configuration (contoso.com)
- Add Storage Account under Path Routing (contoso.com/storage)
- Run Upload File Code with Azure.Storage.Blobs SDK

We do use Terraform for our Infrastructure so many steps have been omited.

### Environment

.net 6

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.
//cc: @xgithubtriage

**Comment by erorubrz** [comment]
Hello. Any updates on this issue?
Thx

**Comment by amnguye** [comment]
Could we get a full code snippet of how you're interacting with the Storage SDK?

**Comment by erorubrz** [comment]
I uploaded the whole test application here: https://github.com/erorubrz/BlobUploadTest
Thanks

**Comment by amnguye** [comment]
Looks like because you're using a custom domain to access the blob container, the URL we're expecting should be in the custom URL format.

See
https://learn.microsoft.com/en-us/azure/storage/blobs/storage-custom-domain-name?tabs=azure-portal#step-4-test-your-custom-domain

Looks like it should be in the format of "http://<subdomain.customdomain>/<mycontainer>/<myblob>" where the container name should come right after the domain name.
