### ISSUE TITLE
[BUG]Azure.Identity.CredentialUnavailableException exception at function startup for QueueTrigger

### ISSUE THREAD

**Issue by Gamecock** [Azure/azure-sdk-for-net#42161]
### Library name and version

Azure.Identity  1.10.4

### Describe the bug

Func Start Locally throws Azure.Identity.CredentialUnavailableException.

However all functions (2 Http and one Queue Trigger) work fine

### Expected behavior

Function startup should occur without exceptions

### Actual behavior

Stack trace with `func start --verbose`

[2024-02-23T16:44:02.686Z] Worker process started and initialized.
[2024-02-23T16:44:06.148Z] Host lock lease acquired by instance ID '0000000000000000000000009715E822'.
[2024-02-23T16:44:07.001Z] False MSAL 4.56.0.0 MSAL.NetCore .NET 6.0.21 Microsoft Windows 10.0.19045 [2024-02-23 16:44:06Z - efe41f1a-3b23-4252-9fcd-eb45011d9bb0] Exception type: Azure.Identity.CredentialUnavailableException
[2024-02-23T16:44:07.003Z] ---> Inner Exception Details
[2024-02-23T16:44:07.005Z] Exception type: System.AggregateException
[2024-02-23T16:44:07.006Z] ---> Inner Exception Details
[2024-02-23T16:44:07.008Z] Exception type: Azure.RequestFailedException
[2024-02-23T16:44:07.010Z] ---> Inner Exception Details
[2024-02-23T16:44:07.011Z] Exception type: System.Net.Http.HttpRequestException
[2024-02-23T16:44:07.013Z] ---> Inner Exception Details
[2024-02-23T16:44:07.014Z] Exception type: System.Net.Sockets.SocketException
[2024-02-23T16:44:07.015Z] 
[2024-02-23T16:44:07.016Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[2024-02-23T16:44:07.017Z]    at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[2024-02-23T16:44:07.019Z]    at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|277_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
[2024-02-23T16:44:07.020Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2024-02-23T16:44:07.022Z] === End of inner exception stack trace ===
[2024-02-23T16:44:07.023Z] 
[2024-02-23T16:44:07.024Z]    at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[2024-02-23T16:44:07.027Z]    at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2024-02-23T16:44:07.029Z]    at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2024-02-23T16:44:07.030Z]    at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(HttpRequestMessage request)
[2024-02-23T16:44:07.030Z]    at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[2024-02-23T16:44:07.031Z]    at System.Net.Http.HttpConnectionPool.GetHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[2024-02-23T16:44:07.032Z]    at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[2024-02-23T16:44:07.033Z]    at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[2024-02-23T16:44:07.033Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2024-02-23T16:44:07.034Z] === End of inner exception stack trace ===
[2024-02-23T16:44:07.035Z] 
[2024-02-23T16:44:07.036Z]    at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpMessage message, Boolean async)
[2024-02-23T16:44:07.037Z]    at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)
[2024-02-23T16:44:07.038Z]    at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-02-23T16:44:07.039Z]    at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-02-23T16:44:07.040Z]    at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-02-23T16:44:07.041Z]    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-02-23T16:44:07.042Z] === End of inner exception stack trace ===
[2024-02-23T16:44:07.043Z] 
[2024-02-23T16:44:07.043Z]    at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
[2024-02-23T16:44:07.044Z]    at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2024-02-23T16:44:07.045Z]    at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2024-02-23T16:44:07.045Z] === End of inner exception stack trace ===
[2024-02-23T16:44:07.046Z] 
[2024-02-23T16:44:07.046Z]    at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2024-02-23T16:44:07.047Z]    at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
[2024-02-23T16:44:07.048Z]    at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
[2024-02-23T16:44:07.048Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)
[2024-02-23T16:44:07.049Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
[2024-02-23T16:44:07.050Z]    at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
[2024-02-23T16:44:07.050Z]    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)

### Reproduction Steps

```
using Azure.Identity;
using Azure.Storage.Queues;
using Azure.Storage.Queues.Models;
using Microsoft.Azure.Functions.Worker;
using Microsoft.Extensions.Logging;

namespace Onity.IoTManagement
{
    public class ProcessDisable
    {
        private readonly ILogger<ProcessDisable> logger;

        public ProcessDisable(ILogger<ProcessDisable> logger)//, IConfigAccessor configAccessor, IIoTServiceClient ioTServiceClient)
        {
            this.logger = logger;
       }

        [Function(nameof(ProcessDisable))]
        public async Task Run([QueueTrigger("disable-gateway", Connection = "IotQueues")] QueueMessage message)
        {
            logger.LogInformation($"C# Queue trigger function processed: {message.MessageText}");
       }
   }
}
```

### Environment

$ dotnet --info
.NET SDK (reflecting any global.json):
 Version:   6.0.402
 Commit:    6862418796

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.19045
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\6.0.402\

Host:
  Version:      8.0.1
  Architecture: x64
  Commit:       bf5e279d92

.NET SDKs installed:
  6.0.402 [C:\Program Files\dotnet\sdk]
  8.0.101 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.11 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 8.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]

Environment variables:
  Not set

global.json file:
  C:\Projects\Onity\OnPortal\server\IoTManagement\global.json

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by jsquire** [comment]
Hi @Gamecock.  Thank you for reaching out and we regret that you're experiencing difficulties.   This is normal and expected behavior, as the Functions infrastructure configures a `DefaultAzureCredential` instance as part of its dependency injection.   As a chained credential, `DefaultAzureCredential` will try several different credential types and use the first that is available on the host environment.  In this case, the attempt to use a managed identity fails, as your local host does not have an MI endpoint.   More information is available in the [DefaultAzureCredential documentation](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/identity-readme?view=azure-dotnet#defaultazurecredential).

If desired, you can configure the `DefaultAzureCredentialOptions` used to remove undesired credentials from the chain or switch to a more specific credential.  To do so, you write a Function startup class to participate in the DI configuration.  _(see: [Use dependency injection in .NET Azure Functions](https://learn.microsoft.com/azure/azure-functions/functions-dotnet-dependency-injection))_

In your DI registration, you would use the Azure extensions to override the default credential used with one configured as you'd like.  For example, configuring the options for `DefaultAzureCredential` would look something like:

```csharp
using Azure.Identity;
using Microsoft.Extensions.Azure;
using Microsoft.Azure.Functions.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection;

[assembly: FunctionsStartup(typeof(MyNamespace.Startup))]

namespace MyNamespace;

public class Startup : FunctionsStartup
{
    public override void Configure(IFunctionsHostBuilder builder)
    {
        builder.Services.AddAzureClients(azureBuilder => 
        {
            var options = new DefaultAzureCredentialOptions
            {
                ExcludeManagedIdentityCredential = true
            };

            // Configure a new credential to be used by default
            // for all clients that require TokenCredential.

            azureBuilder.UseCredential(new DefaultAzureCredential(options));
        });
    }
}
```

This would also allow you to create a different credential type, such as a chained credential that includes only VS and VSCode for local development scenarios.

More information and examples for configuring Azure clients in DI can be found in: [Dependency injection with the Azure SDK for .NET](https://learn.microsoft.com/dotnet/azure/sdk/dependency-injection?tabs=web-app-builder).

**Comment by Gamecock** [comment]
I updated the builder as you suggested, but same error.  Feels wrong that DI should throw an exception when it's working correctly.  This is what the start of my DI Configuration looks like now.

`    .ConfigureServices(s => 
        {
        //  https://github.com/Azure/azure-sdk-for-net/issues/42161
            s.AddAzureClients(azureBuilder =>
            {
                 var options = new DefaultAzureCredentialOptions
            {
                ExcludeManagedIdentityCredential = true
            };

            // Configure a new credential to be used by default
            // for all clients that require TokenCredential.

            azureBuilder.UseCredential(new DefaultAzureCredential(options));
            });`

**Comment by jsquire** [comment]
The error that you're seeing is from the Azure.Identity library and is how its credentials operate.   The DI extensions have no influence nor control over their behavior.   Opting out of managed identity will stop the managed identity credential from being used, but DefaultAzureCredential is still a chained type and will continue to probe other credentials until an available source is found.  If you want to prevent errors from appearing entirely, you'd need to use the specific credential for the auth type that you'd like to use or configure logging to opt-out of gathering the Azure Identity source.

If you'd like to provide a slice of the Azure Identity logs that are being captured, then we'd be happy to take a look and advise which credentials are returning the specific errors that you are now seeing without MI enabled.
