### ISSUE TITLE
[BUG] Enabling Embedded web view for InteractiveBrowserCredential causes runtime exception on some machines

### ISSUE THREAD

**Issue by timmydo** [Azure/azure-sdk-for-net#42235]
### Library name and version

Azure.Identity 1.10.2

### Describe the bug

Using Embedded web view for interactive browser auth throws runtime exception. MSAL asking to include another library and call an extension method

### Expected behavior

expected Interactive auth prompt

### Actual behavior

Azure.Identity.AuthenticationFailedException: The ChainedTokenCredential failed due to an unhandled exception: InteractiveBrowserCredential authentication failed: To enable the embedded webview on Windows, reference Microsoft.Identity.Client.Desktop and call the extension method .WithEmbeddedBrowserSupport().
       ---> Azure.Identity.AuthenticationFailedException: InteractiveBrowserCredential authentication failed: To enable the embedded webview on Windows, reference Microsoft.Identity.Client.Desktop and call the extension method .WithEmbeddedBrowserSupport().
       ---> MSAL.NetCore.4.55.0.0.MsalClientException:
        ErrorCode: no_system_webview
Microsoft.Identity.Client.MsalClientException: To enable the embedded webview on Windows, reference Microsoft.Identity.Client.Desktop and call the extension method .WithEmbeddedBrowserSupport().
         at Microsoft.Identity.Client.Platforms.Shared.NetStdCore.NetCoreWebUIFactory.CreateAuthenticationDialog(CoreUIParent coreUIParent, WebViewPreference webViewPreference, RequestContext requestContext)
         at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.CreateWebAuthenticationDialog()
         at Microsoft.Identity.Client.Internal.AuthCodeRequestComponent.FetchAuthCodeAndPkceVerifierAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.GetTokenResponseAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.InteractiveRequest.ExecuteAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
         at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenInteractiveParameters interactiveParameters, CancellationToken cancellationToken)
         at Azure.Identity.AbstractAcquireTokenParameterBuilderExtensions.ExecuteAsync[T](AbstractAcquireTokenParameterBuilder`1 builder, Boolean async, CancellationToken cancellationToken)
         at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveCoreAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean enableCae, BrowserCustomizationOptions browserOptions, Boolean async, CancellationToken cancellationToken)
         at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean enableCae, BrowserCustomizationOptions browserOptions, Boolean async, CancellationToken cancellationToken)
         at Azure.Identity.InteractiveBrowserCredential.GetTokenViaBrowserLoginAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
         at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
         at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
         at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
         at Azure.Identity.InteractiveBrowserCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
         at Azure.Identity.ChainedTokenCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
         --- End of inner exception stack trace ---
         at Azure.Identity.ChainedTokenCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
         at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
         at Azure.Identity.ChainedTokenCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)

### Reproduction Steps

```
            ChainedTokenCredential credential = new(
            new SharedTokenCacheCredential(new SharedTokenCacheCredentialOptions(tokenCachePersistenceOptions)
            {
                TenantId = MicrosoftTenantId,
            }),
            new InteractiveBrowserCredential(new InteractiveBrowserCredentialOptions
            {
                TenantId = MicrosoftTenantId,
                TokenCachePersistenceOptions = tokenCachePersistenceOptions,
                BrowserCustomization = new BrowserCustomizationOptions()
                {
                    UseEmbeddedWebView = true, //hopefully hsts issues go away on localhost redirect
                }
            }));
```

then call `credential.GetToken(...)`

### Environment

.NET 8

```
    Microsoft.Identity.Client Version="[4.55.0]"
    Azure.Identity Version="[1.10.2]"
```

**Comment by christothes** [comment]
Hi @timmydo -  Does this work if you reference Microsoft.Identity.Client.Desktop in  your app?

**Comment by christothes** [comment]
Discussed more offline - Here is the support matrix for the embedded browser option: https://learn.microsoft.com/entra/msal/dotnet/acquiring-tokens/using-web-browsers#browser-availability

We don't currently have support for [WebView2](https://learn.microsoft.com/en-us/entra/msal/dotnet/advanced/webview2)
