### ISSUE TITLE
[BUG] Storage upload failing.

### ISSUE THREAD

**Issue by dssagar93** [Azure/azure-sdk-for-net#42293]
### Library name and version

Azure.Container.Regisry:latest

### Describe the bug

I am getting blob upload unknown registry intermittently during upload of tar file. It uploads the image config but fails during client.UploadBlobAsync(<binary-data>);

### Expected behavior

Should get uploaded

### Actual behavior

Not uploading blobs of tar file.

### Reproduction Steps

Create an oci image from a tar file containing layers

**Comment by jsquire** [comment]
Hi @dssagar93.  Thank you for reaching out and we regret that you're experiencing difficulties.   Would you please share the exact error message and stack trace that you're seeing?  That will help us understand if you're seeing a client or service error and ensure that we can get you to the right folks for help.

**Comment by dssagar93** [comment]
Hi @jsquire, I have a registry created inside ACR where I am trying to upload a tar file as an image. I create an OCI Image manifest, I loop through .tar layers and try to push the individual layers using client.UploadBlobAsync(). It throws following exception.

Azure.RequestFailedException: 'blob upload unknown to registry
Status: 404 (Not Found)
ErrorCode: BLOB_UPLOAD_UNKNOWN

Content:
{"errors":[{"code":"BLOB_UPLOAD_UNKNOWN","message":"blob upload unknown to registry","detail":{}}]}


Headers:
Server: openresty
Date: Fri, 01 Mar 2024 13:40:57 GMT
Connection: keep-alive
Access-Control-Expose-Headers: REDACTED
Docker-Distribution-Api-Version: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
X-Ms-Client-Request-Id: 0a9218db-29f9-48c6-a5fd-d58ca011a5d5
X-Ms-Correlation-Request-Id: REDACTED
X-Ms-Request-Id: 0bafe0eb-5447-48ed-abad-2f8ab95a68c3
Content-Type: application/json; charset=utf-8
Content-Length: 100

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/containerregistry/uploadblob/troubleshoot

**Comment by jsquire** [comment]
@dssagar93:  Thanks for the additional context.   Would you please provide the stack trace?   I'd also like to see a snippet to understand how you're configuring the client.   The error details that you've provided indicate `openresty` as a server, which is not something that I'd expect to see in an Azure service.   I'm wondering if there's a proxy or other interceptor running in your environment that is interfering with traffic.

**Comment by dssagar93** [comment]
Hi @jsquire, I am using the below code to configure the client.

```
ContainerRegistryContentClient client = new ContainerRegistryContentClient(endpoint, "name", new DefaultAzureCredential(),
    new ContainerRegistryClientOptions()
    {
        Audience = ContainerRegistryAudience.AzureResourceManagerPublicCloud,
        TenantId=""
    });
    
```

**Stacktrace**
    
Azure.RequestFailedException: blob upload unknown to registry
Status: 404 (Not Found)
ErrorCode: BLOB_UPLOAD_UNKNOWN

Content:
{"errors":[{"code":"BLOB_UPLOAD_UNKNOWN","message":"blob upload unknown to registry","detail":{}}]}


Headers:
Server: openresty
Date: Fri, 01 Mar 2024 18:42:00 GMT
Connection: keep-alive
Access-Control-Expose-Headers: REDACTED
Docker-Distribution-Api-Version: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
X-Ms-Client-Request-Id: 816ca1d6-2219-4dee-af28-cbe505484424
X-Ms-Correlation-Request-Id: REDACTED
X-Ms-Request-Id: f6323dab-c0ee-499d-9ad7-010dff5315c6
Content-Type: application/json; charset=utf-8
Content-Length: 100

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/containerregistry/uploadblob/troubleshoot

   at Azure.Containers.ContainerRegistry.ContainerRegistryContentClient.UploadBlobAsync(Stream content, CancellationToken cancellationToken)
   at ContainerWebApp.Controllers.WeatherForecastController.CreateContainerAsync(ContainerFormModel containerFormModel) in C:\Users\v-sagkhatri\Downloads\ContainerWebApp_3\ContainerWebApp\Controllers\WeatherForecastController.cs:line 144
   at lambda_method5(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

HEADERS
=======
Accept: text/plain
Host: localhost:7111
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/122.0.0.0 Safari/537.36
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.9
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryVct0F1axKF5LFcDQ
Origin: https://localhost:7111
Referer: https://localhost:7111/swagger/index.html
Content-Length: 555811759
sec-ch-ua: "Chromium";v="122", "Not(A:Brand";v="24", "Google Chrome";v="122"
sec-ch-ua-mobile: ?0
sec-ch-ua-platform: "Windows"
sec-fetch-site: same-origin
sec-fetch-mode: cors
sec-fetch-dest: empty

**Comment by jsquire** [comment]
Hi @dssagar93.  Thanks for the additional context.  I've traced through the SDK code to confirm that it does not manipulate the base URI for requests, and it does not.  There would be no corner case that would cause intermittent failures like you're seeing.  

The error response is returned by the service directly, as is the associated message.   Unfortunately, service issues are not something that we can assist with from this repository.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).

**Comment by dssagar93** [comment]
Hi @jsquire , is there any possible way through which I can debug and learn more about the issue?
If not, I'll close this issue.

**Comment by jsquire** [comment]
@dssagar93:  Not to my knowledge.  This is a service-side error, so it would either need to appear in public service documentation somewhere (I couldn't find it) or you would need access to the service code, which is not open source.

**Comment by blueww** [comment]
@jsquire 
For server issue you can raise a help ticker on Azure Portal to ask server team's help, see details [here](https://learn.microsoft.com/en-us/azure/azure-portal/supportability/how-to-create-azure-support-request#go-to-help--support-from-the-global-header).
