### ISSUE TITLE
[BUG] when put resource input empty string, get resource via SDK met "Value cannot be an empty string. (Parameter 'resourceId')" error

### ISSUE THREAD

**Issue by yungezz** [Azure/azure-sdk-for-net#42663]
### Library name and version

Azure.ResourceManager.AppContainers Version=1.1.0-beta.1

### Describe the bug

when PUT containerApp env contains property equal to empty string, then get containerApp env via SDK will fail with error  "Value cannot be an empty string. (Parameter 'resourceId')"

### Expected behavior

SDK get containerApp env succeed.

### Actual behavior

get containerApp env via SDK will fail with error  "Value cannot be an empty string. (Parameter 'resourceId')"

### Reproduction Steps

- PUT containerAPp env with below sample payload
```
https://management.azure.com/subscriptions/xxxx/resourceGroups/xxxx/providers/Microsoft.App/managedEnvironments/xxxx?api-version=2022-10-01

{"location": "eastus2", "tags": null, "properties": {"daprAIInstrumentationKey": null, "vnetConfiguration": {"infrastructureSubnetId": "", "runtimeSubnetId": "", "internal": false}, "appLogsConfiguration": {"destination": "log-analytics", "logAnalyticsConfiguration": {"customerId": "xxxxx", "sharedKey": "xxxxx"}}, "customDomainConfiguration": null, "workloadProfiles": null, "InfrastructureResourceGroup": null, "zoneRedundant": false}}

```

- Get via SDK
```
ContainerAppManagedEnvironmentResource env = client.GetContainerAppManagedEnvironmentResource(envId);
```

response with stacktrace
```
System.ArgumentException: Value cannot be an empty string. (Parameter 'resourceId')
   at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.AppContainers.Models.ContainerAppVnetConfiguration.DeserializeContainerAppVnetConfiguration(JsonElement element)
   at Azure.ResourceManager.AppContainers.ContainerAppManagedEnvironmentData.DeserializeContainerAppManagedEnvironmentData(JsonElement element)
   at Azure.ResourceManager.AppContainers.ManagedEnvironmentsRestOperations.GetAsync(String subscriptionId, String resourceGroupName, String environmentName, CancellationToken cancellationToken)
   at Azure.ResourceManager.AppContainers.ContainerAppManagedEnvironmentResource.GetAsync(CancellationToken cancellationToken)
```

**Comment by HarveyLink** [comment]
Hi @yungezz , It's kind of expected behavior, the `infrastructureSubnetId` is a `ResourceIdentifier` type value, the value should not be empty. On the other hand, if we don't have the value while creating the resource, I sugget not to set the value, not to empty.

**Comment by yungezz** [comment]
hi @HarveyLink the API allows empty string, so user could set value to be empty. How to prevent user from it?
