### ISSUE TITLE
Azure.ResourceManager.ApiManagement SDK, ApiCollection throws exception in foreach

### ISSUE THREAD

**Issue by cokosharp** [Azure/azure-sdk-for-net#42773]
I have an interesting issue that occurs sometimes when somebody adds an api to apim which is not configured properly. Then an exception will be thrown when I try to list the apis in apim. It would not be a big deal if I could catch the exception inside the foreach and just continue listing the rest of the apis, but the exception breaks the loop and is getting caught outside it. 

So I wonder what is going on, and if there's maybe another way of listing the apis using the SDK ?
Or is this a bug in the SDK?

EDIT: 
The error I get: 
Exception thrown: 'System.UriFormatException' ("Invalid URI: The format of the URI could not be determined.") 

The URL the SDK is calling:
"https://management.azure.com/subscriptions/.../resourceGroups/.../providers/Microsoft.ApiManagement/service/.../apis?api-version=2021-08-01"

UPDATE:

The error itself is something reoccurring; every now and then, the listing of APIs fails because an exception is thrown in the SDK for one of the apis.

We were using the deprecated package Microsoft.Azure.Management.ApiManagement before, which worked fine. Calling the REST API directly also works fine.

Exception detail:
  at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind, UriCreationOptions& creationOptions)
   at System.Uri..ctor(String uriString)
   at Azure.ResourceManager.ApiManagement.ApiData.DeserializeApiData(JsonElement element)
   at Azure.ResourceManager.ApiManagement.ApiCollection.<>c__DisplayClass9_0.<GetAllAsync>b__2(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at ...d__14.MoveNext()

Simple test code below

```
ResourceIdentifier id = ApiManagementServiceResource.CreateResourceIdentifier(_subscriptionId, _resourceGroupName, _serviceName);
ClientSecretCredential credentials = new(_tenantId, _clientId, _clientSecret);

ArmClient client = new(credentials);
ApiManagementServiceResource apimService = await client.GetApiManagementServiceResource(id).GetAsync();

ApiCollection apiList = apimService.GetApis();

try
{
    foreach (var api in apiList)
    {
        try
        {
            Console.WriteLine(api.Id);
        }
        catch (Exception ex)
        {
            // Not catched here
            Console.WriteLine(ex.Message);
        }
    }
}
catch (Exception ex)
{
    // Catched here
    Console.WriteLine(ex.Message);
}
```

**Comment by cokosharp** [comment]
I would say that this is actually a bug in the SDK.
In function Azure.ResourceManager.ApiManagement.ApiData.DeserializeApiData, there is no check if property0.Value is a valid URI here: 
termsOfServiceUri = new Uri(property0.Value.GetString());

In our case, one of the apis had the property "termsOfService": "n/a", which is not a valid URI, and an exception is thrown.

As a workaround, I'm now calling the rest api directly instead of through the SDK for this particular issue.

**Comment by cokosharp** [comment]
Created a bug report instead
