### ISSUE TITLE
[BUG] SubscriptionResource.GetLocationsAsync fails with System.FormatException

### ISSUE THREAD

**Issue by Fenrazar** [Azure/azure-sdk-for-net#43116]
### Library name and version

Azure.ResourceManager 1.11.0

### Describe the bug

I'm trying to query Azure for the list of locations to work around another bug and I'm getting an error.

### Expected behavior

Return a list of deserialized Azure.ResourceManager.Resources.Models.LocationExpanded

### Actual behavior

`System.FormatException: The input string '-79.8164' was not in a correct format.`
```
   at System.Number.ThrowFormatException[TChar](ReadOnlySpan`1 value)
   at System.Double.Parse(String s)
   at Azure.ResourceManager.Resources.Models.LocationMetadata.ReadLongitude(JsonProperty property, Nullable`1& longitude)
   at Azure.ResourceManager.Resources.Models.LocationMetadata.DeserializeLocationMetadata(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.Resources.Models.LocationExpanded.DeserializeLocationExpanded(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.Resources.SubscriptionResource.<>c.<GetLocationsAsync>b__47_1(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.<GetAsyncEnumerator>d__15.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
```

### Reproduction Steps

```csharp
var armClient = new ArmClient(new DefaultAzureCredential());
SubscriptionResource subscription = _armClient.GetSubscriptionResource("xxxxxxxxxxxxxxxxxxxxx");
var response = subscription.GetLocationsAsync();
var result = await response.ToListAsync(); // <- System.FormatException: 'The input string '-79.8164' was not in a correct format.
```

### Environment

- dotnet 8
- VS 17.9.5

**Comment by Fenrazar** [comment]
https://github.com/Azure/azure-sdk-for-net/blob/b423a6907354e85db2abf1adfb7c3c4bd7b97197/sdk/resourcemanager/Azure.ResourceManager/src/Resources/Custom/Models/LocationMetadata.cs#L34
It's missing the "CultureInfo.InvariantCulture"

**Comment by Fenrazar** [comment]
My bad, I should have specified this. I'm on `fr-fr`:
![image](https://github.com/Azure/azure-sdk-for-net/assets/4925354/75fd9a57-4079-4f5f-ba64-50df5ce667fd)

```
cache-control: no-cache
content-length: 41473
content-type: application/json; charset=utf-8
expires: -1
pragma: no-cache
x-ms-correlation-request-id: 90e241b4-b9fb-4f2e-9e70-e43ab9af11f3
x-ms-ratelimit-remaining-subscription-reads: 11999
x-ms-request-id: 90e241b4-b9fb-4f2e-9e70-e43ab9af11f3
x-ms-routing-request-id: FRANCECENTRAL:20240410T101956Z:90e241b4-b9fb-4f2e-9e70-e43ab9af11f3
```

![image](https://github.com/Azure/azure-sdk-for-net/assets/4925354/1079a68c-be72-49b4-bb47-6b5685784c90)

I was able to move around this issue by forcing the current culture to invariant as every other SDK call.
![image](https://github.com/Azure/azure-sdk-for-net/assets/4925354/0e561c77-ad1f-4562-9fcb-e8b363e4869b)

**Comment by HarveyLink** [comment]
Duplicated with https://github.com/Azure/azure-sdk-for-net/issues/35365.
CultureInfo is not supported for now. We're going to close this issue.
You could track for the latest update here: https://github.com/Azure/autorest.csharp/issues/3651.

**Comment by ArcturusZhang** [comment]
So looks like the culture info in system.text.json is not the real root cause - we customized the serialization to parse the string into double.
We will fix this in the next version.
