### ISSUE TITLE
[BUG] Cannot write large messages (>1MB) to Premium Partitioned Namespace

### ISSUE THREAD

**Issue by evt-jonny** [Azure/azure-sdk-for-net#43187]
### Library name and version

Azure.Messaging.ServiceBus 7.17.4

### Describe the bug

We have been looking into switching to a premium, partitioned service bus namespace in order to deal with throughput issues we are seeing with our current non-partitioned namespace.

We receive an error when trying to write a message larger than 1MB to a topic or queue in this new namespace, even when the topic/queue is configured to allow message sizes up to 10MB.

### Expected behavior

We should still be able to write large messages to partitioned queues and topics. [The documentation](https://learn.microsoft.com/en-us/azure/service-bus-messaging/service-bus-partitioning) has no mention of this limitation when switching to a partitioned namespace.

### Actual behavior

```
Azure.Messaging.ServiceBus.ServiceBusException
 HResult=0x80131500
 Message=The message (id:64923656, size:4194312 bytes) is larger than is currently allowed (1048576 bytes).
 Source=Azure.Messaging.ServiceBus
 StackTrace:
  at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchInternalAsync>d__23.MoveNext()
  at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendBatchInternalAsync>d__23.MoveNext()
  at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<>c.<<SendAsync>b__24_0>d.MoveNext()
  at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<>c__22`1.<<RunOperation>b__22_0>d.MoveNext()
  at System.Threading.Tasks.ValueTask`1.get_Result()
  at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__23`2.MoveNext()
  at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__23`2.MoveNext()
  at System.Threading.Tasks.ValueTask`1.get_Result()
  at Azure.Messaging.ServiceBus.ServiceBusRetryPolicy.<RunOperation>d__22`1.MoveNext()
  at Azure.Messaging.ServiceBus.Amqp.AmqpSender.<SendAsync>d__24.MoveNext()
  at Azure.Messaging.ServiceBus.ServiceBusSender.<SendMessagesAsync>d__26.MoveNext()
  at Azure.Messaging.ServiceBus.ServiceBusSender.<SendMessageAsync>d__25.MoveNext()
  at Program.<<Main>$>d__0.MoveNext() in J:\working\asb-sendmessages\asb-sendmessages\Program.cs:line 22
  at Program.<<Main>$>d__0.MoveNext() in J:\working\asb-sendmessages\asb-sendmessages\Program.cs:line 31
```

### Reproduction Steps

```
using Azure.Messaging.ServiceBus;
using System.Text;

// the client that owns the connection and can be used to create senders and receivers
ServiceBusClient client;

// the sender used to publish messages to the queue
ServiceBusSender sender;

var clientOptions = new ServiceBusClientOptions()
{
    TransportType = ServiceBusTransportType.AmqpWebSockets
};
client = new ServiceBusClient("<NAMESPACE-CONNECTION-STRING>", clientOptions);
sender = client.CreateSender("test1");

var message = new ServiceBusMessage(Encoding.UTF8.GetBytes(new string('A', 1024 * 1024 * 4)));

try
{
    await sender.SendMessageAsync(message);
    Console.WriteLine($"A message has been published to the queue.");
}
finally
{
    // Calling DisposeAsync on client types is required to ensure that network
    // resources and other unmanaged objects are properly cleaned up.
    await sender.DisposeAsync();
    await client.DisposeAsync();
}

Console.WriteLine("Press any key to end the application");
Console.ReadKey();
```

**Comment by jsquire** [comment]
Hi @evt-jonny.  Thank you for reaching out and we regret that you're experiencing difficulties.  Unfortunately, the behavior (and error) that you're seeing is from the Service Bus service and not something that the Azure SDK package has insight into nor influence over.   From the client perspective, my expectation would match yours in that an entity configured to allow 10MB should not  be restricting messages to 1MB.

Because this is service behavior, the Azure SDK maintainers are unable to assist.  To ensure that the right team has visibility and can help, your best path forward for would be to [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request), or inquire on the [Microsoft Q&A site](https://learn.microsoft.com/answers/questions/).   For feature suggestions, you may also want to consider the [Azure Feedback site](https://feedback.azure.com/d365community).

I'm going to close this out; if I've misunderstood what you're describing, please let us know in a comment and we'd be happy to assist as we're able.
