### ISSUE TITLE
Null ref in the ModuleInfrastructure.GetFilePath when generating the bicep for an empty construct

### ISSUE THREAD

**Issue by davidfowl** [Azure/azure-sdk-for-net#43261]
```C#
using var builder = DistributedApplication.CreateBuilder();
var construct = builder.AddAzureConstruct("x", _ => { });
construct.Resource.GetBicepTemplateFile();
```

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Azure.Provisioning
  StackTrace:
   at Azure.Provisioning.ModuleInfrastructure.GetFilePath(ModuleConstruct construct, String outputPath)
   at Azure.Provisioning.ModuleInfrastructure.WriteBicepFile(ModuleConstruct construct, String outputPath)
   at Azure.Provisioning.ModuleInfrastructure.Write(String outputPath)
   at Azure.Provisioning.Infrastructure.Build(String outputPath)
   at Aspire.Hosting.AzureConstructResource.GetBicepTemplateFile(String directory, Boolean deleteTemporaryFileOnDispose) in C:\dev\git\aspire\src\Aspire.Hosting.Azure\AzureConstructResource.cs:line 58
```

**Comment by mitchdenny** [comment]
What did the Aspire callback looklike for this?

**Comment by davidfowl** [comment]
Updated
