### ISSUE TITLE
[BUG] ITableEntity with `int` is converted to Int64 in TableStorage and cannot be read back

### ISSUE THREAD

**Issue by svrooij** [Azure/azure-sdk-for-net#43443]
### Library name and version

Azure.Data.Tables 12.8.2 & 12.8.3

### Describe the bug

I have an `ITableEntity` with an `int` property, upon saving this is saved in a `Int64` column (according to the storage explorer). When I try loading the item it tells me it's not valid, and when I change the column type to `Int32` in the storage explorer (and don't change anything else), it loads just fine.

### Expected behavior

I expect it to create an `Int32` column for an `int`, or at least I expect that I can use the TableClient to create an Item and read back the same item with the same `ITableEntity` implementation that was provider when creating the item.

### Actual behavior

It creates an `Int64` column for an `int` and refuses to read back the same item.

```shell
Exception: System.InvalidCastException: Unable to cast object of type 'System.String' to type 'System.Int32'.
[2024-04-16T12:41:00.608Z]    at Azure.Data.Tables.TablesTypeBinder.TryGet[T](BoundMemberInfo memberInfo, IDictionary`2 source, T& value)
[2024-04-16T12:41:00.609Z]    at Azure.Core.TypeBinder`1.BoundMemberInfo`1.Deserialize(TExchange source, Object o, TypeBinder`1 binderImplementation)
[2024-04-16T12:41:00.609Z]    at Azure.Core.TypeBinder`1.BoundTypeInfo.Deserialize[T](TExchange source)
[2024-04-16T12:41:00.610Z]    at Azure.Data.Tables.DictionaryTableExtensions.ToTableEntity[T](IDictionary`2 entity, BoundTypeInfo typeInfo)
[2024-04-16T12:41:00.611Z]    at Azure.Data.Tables.TableClient.GetEntityInternalAsync[T](Boolean async, String partitionKey, String rowKey, Boolean noThrow, IEnumerable`1 select, CancellationToken cancellationToken)
[2024-04-16T12:41:00.611Z]    at Azure.Data.Tables.TableClient.GetEntityIfExistsAsync[T](String partitionKey, String rowKey, IEnumerable`1 select, CancellationToken cancellationToken)
```

### Reproduction Steps

1. Create a class with an `int` property
2. Initiate the object
3. Use TableClient to create the item
4. (optional) Use Storage explorer to check what is in storage
5. Use TableClient to read the item
6. Crash...

If I change the `int` to a `long` right before loading it, it works just fine.

```csharp
public class OopsEntity: ITableEntity
{
    private DateTimeOffset? _timestamp;
    private ETag _eTag;
    public required string PartitionKey { get; set; }
    public required string RowKey { get; set; }
    public DateTimeOffset? Timestamp { get => _timestamp; set => _timestamp = value; }
    public ETag ETag { get => _eTag; set => _eTag = value; }
    public int Oops{ get; set; }
}

public async Task Crash() {
  string partition = "some-partition";
  string id = "some-id";
  // Get the table client from somewhere
  TableClient tableClient = new TableClient(...);
  OopsEntity item = new OopsEntity { ParitionKey = partition, RowKey = id, Oops = 10 };
  await tableClient.AddEntitityAsync(item);
  var loadedItem = await tableClient.GetEntityAsync<OopsEntity>(parition, id);
}
```

### Environment

I'm using the `TableInputAttribute` to get the `TableClient` in an Azure Function, but I guess it has to do with the TableClient and not the place where I get it from. 
```
.NET SDK:
 Version:           8.0.204
 Commit:            c338c7548c
 Workload version:  8.0.200-manifests.7d36c14f

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\8.0.204\
```

**Comment by christothes** [comment]
Hi @svrooij 
I'm not able to reproduce this with the code above. The table gets created with an int32 value for the int valued property.

Are you possibly doing something else not included in the sample code?

**Comment by svrooij** [comment]
I thought it had nothing to do with Azure Functions, but I'm doing this in an Azure Function, dotnet-isolated dotnet8.
Thing it might be that combination then. Will create a project with just this in it later today.

**Comment by christothes** [comment]
Hi @svrooij - 
Since it appears that this only reproduces when using the `TableOutput` binding, I'd recommend opening an issue for this over here - https://github.com/Azure/azure-functions-dotnet-worker/issues

**Comment by surgupta-msft** [comment]
Reopening the issue - got incorrectly closed by github automation.

**Comment by surgupta-msft** [comment]
Ohh my apologies, opened by mistake. I am working on corresponding dotnet worker issue - https://github.com/Azure/azure-functions-dotnet-worker/issues/2402
