### ISSUE TITLE
[BUG] - ServiceBusSessionReceiver creation intermittently throwing ServiceBusConnection has already been closed and cannot perform the requested operation error.

### ISSUE THREAD

**Issue by wk-ashish** [Azure/azure-sdk-for-net#43470]
### Library name and version

Azure.Messaging.ServiceBus 7.17.2

### Describe the bug

`ServiceBusSessionReceiver ` intermittently throwing `ServiceBusConnection `has already been closed and cannot perform the requested operation error.

**DEBUG log**

```
An exception occurred while creating a ServiceBusSessionReceiver (Namespace '', Entity path ''). Error Message: 'System.ObjectDisposedException: ServiceBusConnection has already been closed and cannot perform the requested operation.
Object name: 'ServiceBusConnection'.
   at Azure.Core.Argument.AssertNotDisposed(Boolean wasDisposed, String targetName)
   at Azure.Messaging.ServiceBus.ServiceBusConnection.ThrowIfClosed()
   at Azure.Messaging.ServiceBus.ServiceBusReceiver..ctor(ServiceBusConnection connection, String entityPath, Boolean isSessionEntity, ServiceBusReceiverOptions options, String sessionId, Boolean isProcessor, CancellationToken cancellationToken)'
```

### Expected behavior

It should not produce this random errors

### Actual behavior

Logs fill up with errors that are not errors

### Reproduction Steps

- Create Service Bus Topic subscription with session enabled
- Create `ServiceBusClient `using `Microsoft.Extensions.Azure`.
- Create `CreateSessionProcessor `using `ServiceBusClient `
- Request `StartProcessingAsync `from created session processor.

**Comment by nparikhepc** [comment]
I also have same issue.

In AutoFacModule.cs
I assigned 
 builder.RegisterType<ServiceBusFacade>().As<IServiceBusFacade>();
 
 In Startup.cs
  builder.RegisterType<AzFunctionServiceBusFacade>()
     .As<IPubSubServiceBus>()
     .As<IQueueableServiceBus>()
     .As<IScheduleableServiceBus>()
     .As<IServiceBusFacade>()
     .AsSelf()
     .SingleInstance();

**Comment by nparikhepc** [comment]
I also have same issue 
 Registered ServiceBusFacade as a singleton

 builder.RegisterType<AzFunctionServiceBusFacade>()
     .As(IPubSubServiceBus)()
     .As<IQueueableServiceBus>()
     .As<IScheduleableServiceBus>()
     .As<IServiceBusFacade>()
     .AsSelf()
     .SingleInstance();

**Comment by jsquire** [comment]
Hi @nparikhepc.  Apologies that this was overlooked for so long.  Looking things over, I'm afraid there's not enough context to reproduce the behavior that you're seeing.  In order to assist, we'll need to understand how to repro.  Ideally, in a small, stand-alone application without your facade and builder registrations.
