### ISSUE TITLE
[BUG]Azure OpenAI library is failed in MAUI with Azure.RequestFailedException: Invalid value for 'content': expected a string, got null. Status: 400 (model_error)  Content: {   "error": {     "message": "Invalid value for 'content': expected a string, got null.",     "type": "invalid_request_error",     "param": "messages.[0].content",     "code": null   } }   

### ISSUE THREAD

**Issue by vovanb** [Azure/azure-sdk-for-net#44174]
### Library name and version

Azure.AI.OpenAI 1.0.0-beta.17

### Describe the bug

same code working fine in .net core console v8 and failed in MAUI application on Android

### Expected behavior

should work same 

### Actual behavior

received exception 
```
1.0.0-beta.17{Azure.RequestFailedException: Invalid value for 'content': expected a string, got null.
Status: 400 (model_error)

Content:
{
  "error": {
    "message": "Invalid value for 'content': expected a string, got null.",
    "type": "invalid_request_error",
    "param": "messages.[0].content",
    "code": null
  }
}


Headers:
Access-Control-Allow-Origin: REDACTED
apim-request-id: REDACTED
x-ratelimit-remaining-requests: REDACTED
Strict-Transport-Security: REDACTED
x-ratelimit-remaining-tokens: REDACTED
x-ms-rai-invoked: REDACTED
X-Request-ID: REDACTED
ms-azureml-model-error-reason: REDACTED
ms-azureml-model-error-statuscode: REDACTED
x-ms-client-request-id: 96c069a5-1230-4c5e-a3fd-f80e925e59d0
X-Content-Type-Options: REDACTED
azureml-model-session: REDACTED
x-ms-region: REDACTED
Date: Tue, 21 May 2024 16:13:58 GMT
Content-Length: 188
Content-Type: application/json

   at Azure.Core.HttpPipelineExtensions.ProcessMessageAsync(HttpPipeline pipeline, HttpMessage message, RequestContext requestContext, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.OpenAIClient.GetChatCompletionsAsync(ChatCompletionsOptions chatCompletionsOptions, CancellationToken cancellationToken)
   at MauiAppTestOpenAI.MainPage.GetCompletionAsync() in 
```

### Reproduction Steps

Same code in console application working fine and in MAUI Android is failing with exeption:

```
using Azure;
using Azure.AI.OpenAI;
using System.Text;
Console.OutputEncoding = Encoding.UTF8;
Console.WriteLine("Staring chatGPT");


 string openAIKey = "REPLACE WITH YOUR OWN";
OpenAIClient client = new OpenAIClient(
  new Uri("https://openaiuksouthgpt4.openai.azure.com/"),
  new AzureKeyCredential(openAIKey));

Response<ChatCompletions> responseWithoutStream = await client.GetChatCompletionsAsync(

new ChatCompletionsOptions()
{
    DeploymentName = "GPT4",
    Messages =
  {
      
          new ChatRequestSystemMessage( @"Don't ask questions, answer very short with exact data"),
      new ChatRequestUserMessage( @"What is date today?") ,
  },
    Temperature = 1,
    MaxTokens = 250,


    NucleusSamplingFactor = 1,
    FrequencyPenalty = 0,
    PresencePenalty = 0,
});


ChatCompletions response = responseWithoutStream.Value;
string strResult = response.Choices[0].Message.Content;

Console.WriteLine("OpenAI response " + @strResult);
```

### Environment

On Windows in Console app it is working, in MAUI Android is failing

**Comment by vovanb** [comment]
note same code with 1.0.0-beta.8 is working fine

**Comment by EPinci** [comment]
Having the same issue.
Same exact code, calling the same deployed model: Blazor in MAUI on Android throws the above exception, Blazor in asp.net works fine.
Last know good version is 1.0.0-beta.15.

**Comment by vemotion76** [comment]
Version 2.0.0-beta.1 also does not work (Android); when attempting to call CompleteChat(messages), it returns "Operation is not supported on this platform." (it works on Windows.)

**Comment by vikramrajsivaram** [comment]
Facing the same issue here, working in Windows, broken in Android. And I cannot go back to 1.0.0-beta.15 because it does not support me sending binary data to the sdk.
![image](https://github.com/Azure/azure-sdk-for-net/assets/11582801/f006a703-e3aa-46dc-a458-8e3e84002024)

**Comment by arafattehsin** [comment]
Any updates on this please? It's blocking a lot of use-cases.
