### ISSUE TITLE
Application crash due to ServiceBusClientWebSocket.ConnectAsync

### ISSUE THREAD

**Issue by GitHubSachin** [Azure/azure-sdk-for-net#4448]
Under high load our app which uses servicebus eventhubs to send telemetry data from background thread crashed with exception stack below. This is .net 4.5.2 desktop version and using 4.1.6 version of WindowsAzure.ServiceBus package.
The crash happens when application is under load. which is about 600 app instances running on a server, one of them will crash with below error

Unhandled Exception: System.AggregateException: One or more errors occurred. 
	---> System.Net.WebException: The request was canceled    at System.Net.ServicePointManager.FindServicePoint(Uri address, IWebProxy proxy, ProxyChain& chain, HttpAbortDelegate& abortDelegate, Int32& abortState)    
	at System.Net.HttpWebRequest.FindServicePoint(Boolean forceFind)    
	at System.Net.HttpWebRequest.Abort(Exception exception, Int32 abortState)    
	at System.Net.HttpWebRequest.Abort()    
	at Microsoft.ServiceBus.ServiceBusClientWebSocket.<>c.<ConnectAsync>b__45_0(Object s)    
	at System.Threading.CancellationCallbackInfo.ExecutionContextCallback(Object obj)    
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)    
	at System.Threading.CancellationCallbackInfo.ExecuteCallback()    
	at System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(CancellationCallbackCoreWorkArguments args)    
	at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)    
--- End of inner exception stack trace ---    
	at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)    
	at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)    
	at System.Threading.CancellationTokenSource.TimerCallbackLogic(Object obj)    
	at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)  
	at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    
	at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)    
	at System.Threading.TimerQueueTimer.CallCallback()    
	at System.Threading.TimerQueueTimer.Fire()    
	at System.Threading.TimerQueue.FireNextTimers()    
	at System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by JonKragh** [comment]
Same issue here under high load.

- Approximately 100 concurrent C# tasks in a windows service
- Pumping order updates to azure service bus
- .NET 4.6.2 - I could upgrade if needed
- I upgraded to WindowsAzure.ServiceBus 4.1.10 and it did not resolve the issue

I ended up adding a lock to work around this for now. 

Removing the lock here reproduces the issue.


        static object _servicebusorderlock = new object();

        public void SendMessageOrderUpdate(string subJson)
        {
            lock (_servicebusorderlock)
            {
                try
                {
                    byte[] bytes = Encoding.UTF8.GetBytes(subJson);
                    MemoryStream stream = new MemoryStream(bytes, writable: false);
                    BrokeredMessage message = new BrokeredMessage(stream) {ContentType = "application/json"};
                    var factory = MessagingFactory.CreateFromConnectionString(_serviceBusConnectionString);
                    var sender = factory.CreateMessageSender("OrderUpdate");
                    sender.Send(message);
                }
                catch (Exception exc)
                {
                    ErrorUtil.RecordException(exc);
                }
            }
        }

   at System.Threading.CancellationTokenSource.ExecuteCallbackHandlers(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.NotifyCancellation(Boolean throwOnFirstException)
   at System.Threading.CancellationTokenSource.TimerCallbackLogic(Object obj)
   at System.Threading.TimerQueueTimer.CallCallbackInContext(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.TimerQueueTimer.CallCallback()
   at System.Threading.TimerQueueTimer.Fire()
   at System.Threading.TimerQueue.FireNextTimers()
   at System.Threading.TimerQueue.AppDomainTimerCallback()

**Comment by jfggdl** [comment]
Thanks for reaching out. We recommend to update your solution to use the current .Net SDK. 

We are going to be closing this issue, but if you have additional questions, please create a new issue in https://github.com/Azure/azure-service-bus.
