### ISSUE TITLE
[BUG]Failed to download PEM certificate from azure.keyvault with failure "The provided key does not match the public key for this certificate"

### ISSUE THREAD

**Issue by cdlliuy** [Azure/azure-sdk-for-net#44596]
### Library name and version

Azure.Security.KeyVault.Certificates 4.6.0; Azure.Core 1.40.0; Azure.Identity 1.11.4

### Describe the bug

when using CertifcatesClient to download certificates  `client.DownloadCertificateAsync(certname)` for a PEM format cert in Azure keyvault,  I got exception:
```

System.Reflection.TargetInvocationException
  HResult=0x80131604
  Message=Exception has been thrown by the target of an invocation.
  Source=System.Private.CoreLib
  StackTrace:
   at System.Reflection.MethodBaseInvoker.InvokeWithFewArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
   at Azure.Core.PemReader.CreateRsaCertificate(Byte[] cer, Byte[] key, X509KeyStorageFlags keyStorageFlags)
   at Azure.Core.PemReader.LoadCertificate(ReadOnlySpan`1 data, Byte[] cer, KeyType keyType, Boolean allowCertificateOnly, X509KeyStorageFlags keyStorageFlags)
   at Azure.Security.KeyVault.Certificates.CertificateClient.<DownloadCertificateAsync>d__19.MoveNext()
   at Azure.Security.KeyVault.Certificates.CertificateClient.<DownloadCertificateAsync>d__18.MoveNext()
   at Microsoft.BingAds.Utils.KeyVaultHelperNew.<GetCertAsyncInternal>d__4.MoveNext() in E:\A\private\Common\Microsoft.BingAds.Utils\Microsoft.BingAds.Utils\KeyVaultHelperNew.cs:line 294
   at Microsoft.BingAds.Utils.KeyVaultHelperNew.<GetCertAsyncInternal>d__4.MoveNext() in E:\A\private\Common\Microsoft.BingAds.Utils\Microsoft.BingAds.Utils\KeyVaultHelperNew.cs:line 318
   at Microsoft.BingAds.Utils.KeyVaultHelper.<GetCertAsync>d__14.MoveNext() in E:\A\private\Common\Microsoft.BingAds.Utils\Microsoft.BingAds.Utils\KeyVaultHelper.cs:line 359
   at Program.<getCertTest>d__6.MoveNext() in E:\A\private\Common\Microsoft.BingAds.Utils\LocalTest\Program.cs:line 68
   at Program.<Main>d__3.MoveNext() in E:\A\private\Common\Microsoft.BingAds.Utils\LocalTest\Program.cs:line 17

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
ArgumentException: The provided key does not match the public key for this certificate. (Parameter 'privateKey')
```

For the cert itself,  it is automated generated by Azure Keyvault 
When generating the cert with PKCS#12,  the `DownloadCertificate` function works correctly. 
But when generating with PEM by just changing the content type to PME in below,  the same code failed.
<img width="463" alt="image" src="https://github.com/Azure/azure-sdk-for-net/assets/17263036/a42f5d38-fd11-4488-a594-cae8d4d8888b">

I read the code of `DownloadCertificate` .  It looks like to have specific handling for PEM format already.  
Anything wrong here? 
__

### Expected behavior

see above description

### Actual behavior

see above description

### Reproduction Steps

1. register a domain in One-Cert system with private AME issuer only 
2. generate a cert for this domain with PEM format
3. do `DownloadCertificate` func

**Comment by adelKhatib** [comment]
Same issue!
