### ISSUE TITLE
[BUG] Azure.Monitor.OpenTelemetry.AspNetCore package

### ISSUE THREAD

**Issue by kdcllc** [Azure/azure-sdk-for-net#44662]
### Library name and version

Azure.Monitor.OpenTelemetry.AspNetCore 1.2.0

### Describe the bug

`Program.cs`

```csharp
        // Add OpenTelemetry and configure it to use Azure Monitor.
        builder.Services.AddOpenTelemetry().UseAzureMonitor();
```
`appsetting.json`
```json
  "AzureMonitor": {
    "ConnectionString": ""
}
```
```bash
dotnet run
Building...

Unhandled exception. System.InvalidOperationException: The service collection cannot be modified because it is read-only.
   at Microsoft.Extensions.DependencyInjection.ServiceCollection.ThrowReadOnlyException()
   at Microsoft.Extensions.DependencyInjection.ServiceCollection.Insert(Int32 index, ServiceDescriptor item)
   at Microsoft.Extensions.DependencyInjection.OpenTelemetryServicesExtensions.AddOpenTelemetry(IServiceCollection services)
```

### Expected behavior

Project to build and run.

### Actual behavior

Throws this error and I can't move beyond this

### Reproduction Steps

simple app doesn't work!

### Environment

.NET SDK:
 Version:           8.0.301
 Commit:            1a0e9c0300
 Workload version:  8.0.300-manifests.f6879a9a
 MSBuild version:   17.10.4+10fbfbf2e

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         linux-x64
 Base Path:   /home/user/dotnet/sdk/8.0.301/

.NET workloads installed:
There are no installed workloads to display.

Host:
  Version:      8.0.6
  Architecture: x64
  Commit:       3b8b000a0e

.NET SDKs installed:
  8.0.301 [/home/user/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 8.0.6 [/home/user/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 8.0.6 [/home/user/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/home/user/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download

**Comment by rajkumar-rangaraj** [comment]
Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) that recreates this issue to help troubleshoot it.

**Comment by kdcllc** [comment]
@rajkumar-rangaraj as strange as it might sound the next day this code worked https://github.com/kdcllc/openai-aca-lb/blob/17e0115ac1321f83107031fd88efa94f62422408/src/Program.cs#L13.

I am closing this issue. Thanks
