### ISSUE TITLE
[BUG] - ACA Jobs - Stopping Job .Net SDK throwing The requested operation requires an element of type 'Object', but the target element has type 'String'.

### ISSUE THREAD

**Issue by rahulsingii** [Azure/azure-sdk-for-net#44806]
### Library name and version

Azure.ResourceManager.AppContainers 1.2.0

### Describe the bug

I have a simple container job which is triggered based on azure service bus. I am successfully able to stop the job replica using the command line. I then tried stopping it through the .Net SDK following the sample mentioned in [documentation](https://learn.microsoft.com/en-us/rest/api/containerapps/jobs/stop-execution?view=rest-containerapps-2023-05-01&tabs=dotnet). It is stopping the job but throwing exception in the final method:-

`await containerAppJobExecution.StopExecutionJobAsync(WaitUntil.Completed);`

Exception Message - 

> The requested operation requires an element of type 'Object', but the target element has type 'String'.

Stack Trace - 

at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.TryGetNamedPropertyValue(Int32 index, ReadOnlySpan`1 propertyName, JsonElement& value)
   at System.Text.Json.JsonElement.TryGetProperty(String propertyName, JsonElement& value)
   at Azure.Core.NextLinkOperationImplementation.IsFinalState(Response response, HeaderSource headerSource, Nullable`1& failureState, String& resourceLocation)
   at Azure.Core.NextLinkOperationImplementation.Create(HttpPipeline pipeline, RequestMethod requestMethod, Uri startRequestUri, Response response, OperationFinalStateVia finalStateVia, Boolean skipApiVersionOverride, String apiVersionOverrideValue)
   at Azure.ResourceManager.AppContainers.AppContainersArmOperation..ctor(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Request request, Response response, OperationFinalStateVia finalStateVia, Boolean skipApiVersionOverride, String apiVersionOverrideValue)
   at Azure.ResourceManager.AppContainers.ContainerAppJobExecutionResource.<StopExecutionJobAsync>d__18.MoveNext()

### Expected behavior

Job is stopping but SDK shouldn't throw exception.

### Actual behavior

Exception is thrown.

### Reproduction Steps

1. Create the container app job provided in the sample.
2. Try stopping a particular job replica using the .Net SDK.

### Environment

Project version - .Net 8

**Comment by jsquire** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by HarveyLink** [comment]
Hi @rahulsingii , thank you for using Azure SDK for .NET.
Based on the service [spec](https://github.com/Azure/azure-rest-api-specs/blob/ab064e0047ec560a700d6b501097d99471ad817b/specification/app/resource-manager/Microsoft.App/stable/2024-03-01/Jobs.json#L404-L406)
```
         "responses": {
          "200": {
            "description": "Container Apps Jobs terminated successfully."
          },
```
The response should not contain any content. But now the content is:
```
"Job Execution: <placeholder>, stopped successfully."
```
This is not we expected.
You could [open an Azure support request](https://docs.microsoft.com/azure/azure-portal/supportability/how-to-create-azure-support-request) to let ContainerAPP service team change the response.

**Comment by rahulsingii** [comment]
@HarveyLink - Thank you for your response. Can't the SDK team be assigned here instead? I am getting no help from Azure support plus it doesn't seem to be my subscription issue so maybe it should be addressred here?

**Comment by jsquire** [comment]
@rahulsingii :  Not sure why I've been mentioned here, as my role was just to perform initial triage.  That said, to clarify Minghao's analysis, this behavior is the result of the service not following its own published API spec.   The Azure SDK package has no insight nor influence over the service behavior, which is clearly in error.

Looping in @ArthurMa1978 as the management package owner.  Do you agree with the recommended path, or should there be an internal IcM for the service team opened to push for a fix?

**Comment by HarveyLink** [comment]
We have reached out the service team, they will apply a fix to this issue, will comment back once we have further updates.
