### ISSUE TITLE
[BUG] Getting exception when using _chatClient.CompleteChatAsync

### ISSUE THREAD

**Issue by YoavDolev** [Azure/azure-sdk-for-net#44904]
### Library name and version

Azure.AI.OpenAI 2.0.0-beta.2

### Describe the bug

Hi,
I'm encountering the following error:
![image](https://github.com/Azure/azure-sdk-for-net/assets/167105383/cb253193-2d51-4c47-a9aa-32ae07b11bfe)
When trying to run the following line of code:

```
ChatCompletion completion = await _chatClient.CompleteChatAsync(
            [
                new SystemChatMessage(request.SystemMessage),
                new UserChatMessage(request.Query)
            ],
            chatCompletionsOptions
        );
```
chatCompletionsOptions is built with this datasource:
```
 var chatExtensionConfiguration = new AzureSearchChatDataSource()
            {
                Endpoint = _config.SearchServiceEndpoint,
                IndexName = _config.SearchIndex,
                Filter = request.Filter,
                FieldMappings = new DataSourceFieldMappings()
                {
                    ContentFieldNames = { "content_with_image_summary" },
                    FilepathFieldName = "filepath",
                    TitleFieldName = "title",
                    ContentFieldSeparator = ContentFieldSeperator,
                    UrlFieldName = "url",
                    VectorFieldNames = { "content_with_image_summary_vector" }
                },
                Authentication = DataSourceAuthentication.FromSystemManagedIdentity(),
                VectorizationSource =
                    DataSourceVectorizer.FromEndpoint(_config.EmbeddingEndpoint,
                        DataSourceAuthentication.FromSystemManagedIdentity()),
                InScope = true,
                RoleInformation = request.SystemMessage,
                QueryType = dataSourceQueryType,
                SemanticConfiguration = SemanticConfiguration
            };
```
Creating options like so:
```
      ChatCompletionOptions chatCompletionsOptions = new ChatCompletionOptions
      {
          Temperature = 0,
          MaxTokens = 800,
      };
      chatCompletionsOptions.AddDataSource(chatExtensionConfiguration);
```
These are the packages' versions I'm working with:
 
```
  <PackageReference Include="Azure.AI.OpenAI" Version="2.0.0-beta.2" />
  <PackageReference Include="Azure.Identity" Version="1.11.3" />
  <PackageReference Include="Azure.ResourceManager" Version="1.10.1" />
  <PackageReference Include="Azure.ResourceManager.CognitiveServices" Version="1.3.1" />
  <PackageReference Include="Azure.ResourceManager.Search" Version="1.2.1" />
  <PackageReference Include="Azure.Security.KeyVault.Secrets" Version="4.5.0" />
```
The issues started after updating the Azure.Identity package which prompted us to update the Azure.AI.OpenAI to the new major version.
The issue is not consistent and sometimes fails or passes for the same inputs, it even succeeds for the same input that failed within the same run.
I'd appreciate any help you may provide! 

### Expected behavior

Managing to handle the requests without any exceptions.

### Actual behavior

Raising exceptions with status 400 (Bad Request) as shown above

### Reproduction Steps

The exception is raised from the code provided above, the fails are non-consecutive and the task may succeed or fail as what seem randomly to me.

### Environment

OPEN_API_VERSION="2024-02-01"
CHAT_COMPLETION_MODEL_ID="gpt-4-1106-Preview"

**Comment by trrwilson** [comment]
Thank you, @YoavDolev -- that's certainly not a very helpful error to work from!

Is there an `InnerException` on the `ClientResultException` being thrown? This looks suspiciously like an issue that @glecaros was looking into, where the HTTP 400 wrapped a rate limiting error (HTTP 429) that corresponded to the intermittent failures.

**Comment by YoavDolev** [comment]
There is no inner exception, though this issue did present with an inner exception in previous version. 
This seems to be a rate limiting issue on the part of "AzureSearchChatDataSource" which I'm adding as a data source. It seems to be rate limiting (which is expected) but the error isn't propagating properly. I'm getting the rate limiting error codes (499,502) which is usually returned from it but the inner exception isn't thrown with the "CompleteChatAsync" call so I can't handle it properly in my retry policy.
It would be very helpful for a proper rate limiting 429 exceptions being thrown in "ClientResultException " but we could also do with a way to present the inner exception

**Comment by arelsharon** [comment]
Hey, just to add, we are also getting 401 errors in addition to the 400 errors, Our issue seems very similar to #44804

**Comment by MTCMarkFranco** [comment]
what is the status of this? further observations: the datasource payload seems to be missing indexname and ApiKey properties and fails as well as underlying 400 and 419 intermittent errors.

**Comment by AR-George** [comment]
Using Azure.AI.OpenAI 2.0.0-beta.2. 
Not to jump on the "me too" bandwagon but we're also seeing this issue _sometimes_

We get 400 before hitting HTTP 429 (rate limit error). 

The exception message is:
Service request failed.
Status: 400 (Bad Request)
and there is no inner exception. 

We're using chat 4 with 20k tokens so I'm really surprised that we're hitting the limit (which is set to the max of 20k tokens) with just some simple questions on a bunch of documents. It's also odd that we get 400 errors before it returns 429.

**Comment by arelsharon** [comment]
Any update on this?

**Comment by rgknp** [comment]
I am facing similar issue. Calling the chatClient.CompleteChatAsync(messages, options); works as long as there is no data source added. The moment I add below:
                options.AddDataSource(new AzureSearchChatDataSource()
                {
                    Endpoint = new Uri(searchEndpoint),
                    IndexName = searchIndex,
                    //Authentication = DataSourceAuthentication.FromSystemManagedIdentity(),
                    Authentication = DataSourceAuthentication.FromApiKey(searchResourceKey),
                    AllowPartialResult = true,
                    InScope = true,
                    QueryType = question,
                    Strictness = 4,
                    TopNDocuments = 20
                });

I start getting 400 error. 

  System.ClientModel.ClientResultException
  HResult=0x80131500
  Message=Service request failed.
Status: 400 (Bad Request)

  Source=Azure.AI.OpenAI
  StackTrace:
   at Azure.AI.OpenAI.ClientPipelineExtensions.<ProcessMessageAsync>d__0.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result() in /_/src/libraries/System.Private.CoreLib/src/System/Threading/Tasks/ValueTask.cs:line 812
   at Azure.AI.OpenAI.Chat.AzureChatClient.<CompleteChatAsync>d__8.MoveNext()
   at OpenAI.Chat.ChatClient.<CompleteChatAsync>d__5.MoveNext()

**Comment by aorlenko** [comment]
Same problem here. It'd be great if there was any additional data in the exception that would clarify what exactly is wrong. I'm using Azure.AI.OpenAI Version="2.1.0-beta.2".

**Comment by Licantrop0** [comment]
I can also repro this with Azure.Ai.OpenAI 2.1.0

```csharp
List<ChatMessage> chatMessages = [new SystemChatMessage("<SYSTEM_PROMPT>")];

var chatOptions = new ChatCompletionOptions();
chatOptions.AddDataSource(new AzureSearchChatDataSource()
{
    Endpoint = new Uri("<AZURE_SEARCH_ENDPOINT>"),
    IndexName = "<AZURE_SEARCH_INDEX>",
    Authentication = DataSourceAuthentication.FromApiKey("<AZURE_SEARCH_KEY>"),
});

chatMessages.Add(new UserChatMessage("<USER_INPUT>"));

ChatCompletion completion = await OpenAIHelpers.AIChatClient.CompleteChatAsync(chatMessages, chatOptions);
Console.WriteLine($"Intent: {completion.GetMessageContext()?.Intent}");
Console.WriteLine(completion?.Content.First().Text);
```

**Comment by jagdish-kumawat** [comment]
when using latest stable version getting bad request when this statement is added - QueryType = DataSourceQueryType.VectorSemanticHybrid,

**Comment by TrueCodePoet** [comment]
I am Getting the Service request failed. Status: 400 (Bad Request) error if I use AddDataSource .  I can separate into searchClient and chatClient with no issues.  I have attempted as many configurational changes as I can think of.  as long as I AddDataSource i get 400.

I wish I could provide more of an error output to help but the error is not help full as others have pointed out.

**Comment by erik-konttorp** [comment]
I had this problem to, but when I changed to Authentication = DataSourceAuthentication.FromApiKey i worked for me.

**Comment by julitogtu** [comment]
I'm still getting same issue, any way to solve this?

**Comment by ogarules** [comment]
Same issue here, no news on how to solve this?

**Comment by navba-MSFT** [comment]
I am encountering the same issue.

**Error:**
An unhandled exception was thrown by the application.
System.ClientModel.ClientResultException: Service request failed.
Status: 400 (Bad Request)

   at OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at OpenAI.Chat.ChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
   at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancel







**Findings:**

If I remove the below section it works fine:

```
 ChatCompletionOptions options = new();
 options.AddDataSource(new AzureSearchChatDataSource()
 {
     Endpoint = new Uri(searchEndpoint),
     IndexName = searchIndexName,
     Authentication = DataSourceAuthentication.FromSystemManagedIdentity(),
 });

 ```

 

Also If I use the Keys it works fine.  The issue is only when I use the **System Managed Identity:**

```
ChatCompletionOptions options = new();
options.AddDataSource(new AzureSearchChatDataSource()
{
    Endpoint = new Uri(searchEndpoint),
    IndexName = searchIndexName,
    Authentication = DataSourceAuthentication.FromApiKey(searchKey),
});

```
 
Does anyone have any workarounds (other than using the apikeys) ? Thanks in advance.

**Comment by sydbank-lmd** [comment]
> I am encountering the same issue.
> 
> **Error:** An unhandled exception was thrown by the application. System.ClientModel.ClientResultException: Service request failed. Status: 400 (Bad Request)
> 
> at OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options) at OpenAI.Chat.ChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options) at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancel
> 
> **Findings:**
> 
> If I remove the below section it works fine:
> 
> ```
>  ChatCompletionOptions options = new();
>  options.AddDataSource(new AzureSearchChatDataSource()
>  {
>      Endpoint = new Uri(searchEndpoint),
>      IndexName = searchIndexName,
>      Authentication = DataSourceAuthentication.FromSystemManagedIdentity(),
>  });
> ```
> 
> Also If I use the Keys it works fine. The issue is only when I use the **System Managed Identity:**
> 
> ```
> ChatCompletionOptions options = new();
> options.AddDataSource(new AzureSearchChatDataSource()
> {
>     Endpoint = new Uri(searchEndpoint),
>     IndexName = searchIndexName,
>     Authentication = DataSourceAuthentication.FromApiKey(searchKey),
> });
> ```
> 
> Does anyone have any workarounds (other than using the apikeys) ? Thanks in advance.

I'm having the exact same issue. I've ensured that both my own identity as well as the OpenAI instance has Search Index Data Contributor, Search Service Contributor as well as Search Index Data Contributor. Probably too much, but still doesn't change anything. I can only make it work using API keys too, which is a bummer as we are trying to get rid of secrets

**Comment by Ashetyn-tegna** [comment]
We were able to resolve this same issue on our project by navigating to the search index's service, clicking the side menu for "Networking" then checking a box at the bottom under "Exceptions" which states to "Allow Azure services on the trusted services list to access this search service"

<img width="951" height="863" alt="Image" src="https://github.com/user-attachments/assets/cf819a87-51b8-4b9d-8a7f-964471317682" />
