### ISSUE TITLE
[BUG] 401 using DefaultAzureCredentials

### ISSUE THREAD

**Issue by cdwaddell** [Azure/azure-sdk-for-net#44910]
### Library name and version

 Azure.AI.OpenAI  2.0.0-beta.2

### Describe the bug

I have the following setup as a Singleton using dependency injection:

```
new AzureOpenAIClient(
    new Uri(endpoint),
    new DefaultAzureCredential(),
    new AzureOpenAIClientOptions(ServiceVersion.V2024_06_01)
);
```

I then inject this into my application and use this code to chat:

```
var chatClient = _openAIClient.GetChatClient(deploymentName);
var response = await chatClient.CompleteChatAsync(messages, options);
```

Intermittently, this call returns a 401. It seems to happen every 30 seconds or so and lasts for 30 seconds, then it goes away. Is there an issue with token management? FYI, this code worked fine before v2.0.

### Expected behavior

These should all result in 200 responses.

### Actual behavior

Intermittent 401 responses.

### Reproduction Steps

Use dependency injection with a Singleton:

```
new AzureOpenAIClient(
    new Uri(endpoint),
    new DefaultAzureCredential(),
    new AzureOpenAIClientOptions(ServiceVersion.V2024_06_01)
);
```

In a controller, do this:

```
var chatClient = _openAIClient.GetChatClient(deploymentName);
var response = await chatClient.CompleteChatAsync(messages, options);
```

### Environment

.Net 8.0.2 running on a Linux App Service in Azure. Locally running this on Mac OS.

**Comment by cdwaddell** [comment]
FYI, the correct RBAC permissions are granted for our development team and for our App Service Managed Identity:
* Cognitive Services OpenAI User
* Cognitive Services Usages Reader

**Comment by scottaddie** [comment]
@cdwaddell I need a couple things to troubleshoot:
1. Which version of the Azure.Identity package are you using?
2. Can you please [enable logging](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Diagnostics.md#logging) and provide the output here? This will tell us which authN mechanism `DefaultAzureCredential` is attempting to use.

**Comment by cdwaddell** [comment]
1. We were running 4.11.3 of Azure.Identity. I do see that 4.12.0 is now out, so I am going to push an update to that one.
2. Unfortunately, I work for a locked down industry so can't post any logging here. I can't even create tickets unless I use my personal account on my personal device. That being said, I'll see if I can dig into the logs and see what authn is used when we get a 401. I can see that when we get a 200, it is using the App Service MI.

Also of Note, we use DefaultAzureCredentials for KeyVault, StorageAccount, Queue, and Azure AI Search. OpenAI is the only service with intermittent 401s which started when I updated to v2.0.

**Comment by scottaddie** [comment]
@cdwaddell You'll definitely want to update your Azure.Identity package, as version 1.11.3 contains a known vulnerability.

Tagging @christothes to help triage further.

**Comment by cdwaddell** [comment]
> @cdwaddell You'll definitely want to update your Azure.Identity package, as version 1.11.3 contains a known vulnerability.
> 
> Tagging @christothes to help triage further.

I saw that :) thanks for the heads up!

**Comment by trrwilson** [comment]
Independently of the Identity package: we do have a custom implementation for token management in the v2.0 AOAI library and it's highly probable it's not as robust (or perhaps even correct) as it needs to be -- this is due to the new client being built atop System.ClientModel rather than Azure.Core. We'll follow up. And thank you for the report!

**Comment by cdwaddell** [comment]
That makes sense, the upgrade to v2.0 has been painful due to SCM as well. Thanks for the update.

**Comment by cdwaddell** [comment]
@trrwilson I reviewed the custom token management code, and it looks good superficially. The only thing that stands out is potential concurrency problems, but I can rule that out as it is happening locally when a single thread is the only worker. When running locally, it appears to hit every 7th or 8th request instead of on a timer interval as I suggested in my initial report.

@scottaddie , here are the logs when I run it locally. This is the error:
```
System.ClientModel.ClientResultException: Service request failed.

Status: 401 (Unauthorized)
   at Azure.AI.OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at Azure.AI.OpenAI.Chat.AzureChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
   at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)
   at MetIQ.API.Services.Generation.OpenAILLMService.GenerateWithContext(String systemPrompt, IEnumerable`1 context, IList`1 conversationHistory, Prompt userPrompt) in /Users/********/Source/Repos/MetIQ/13882_MetIQ_API/src/api/Services/Generation/OpenAILLMService.cs:line 114
   at MetIQ.API.RagStrategies.GenericRetrievalRerankGenerateStrategy.PerformSearchAndGeneration(String systemPrompt, IList`1 conversationHistory, Prompt userPrompt, IRetrievalService retrievalService, IEnumerable`1 generationAugmentationServices, IGenerationService generationService, List`1 searchCriteria) in /Users/********/Source/Repos/MetIQ/13882_MetIQ_API/src/api/RagStrategies/GenericRetrievalRerankGenerateStrategy.cs:line 234
   at MetIQ.API.RagStrategies.GenericRetrievalRerankGenerateStrategy.Generate(String systemPrompt, IList`1 conversationHistory, Prompt userPrompt, List`1 filters) in /Users/********/Source/Repos/MetIQ/13882_MetIQ_API/src/api/RagStrategies/GenericRetrievalRerankGenerateStrategy.cs:line 73
   at [MetIQ.API.Controllers.ChatController.Post](http://metiq.api.controllers.chatcontroller.post/)(CompletionV1 v1Completion, Guid usecase) in /Users/********/Source/Repos/MetIQ/13882_MetIQ_API/src/api/Controllers/ChatController.cs:line 56
   at lambda_method20(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
```

Here are the logs for the token selection that occurred immediately before the error. You will notice that it landed on my local user account using the CLI credentials, on the server it is the MI of the App Service.
```
[Informational] Azure-Core: Request [53f6d504-82b8-45a2-9ea9-da1e16b698d9] exception System.Threading.Tasks.TaskCanceledException: The operation was cancelled because it exceeded the configured timeout of 0:00:01. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.

2

---> System.Threading.Tasks.TaskCanceledException: A task was canceled.

   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   --- End of inner exception stack trace ---

   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   at Azure.Core.Pipeline.HttpClientTransport.ProcessSyncOrAsync(HttpMessage message, Boolean async)

   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)

   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)

   --- End of inner exception stack trace ---

   at Azure.Core.Pipeline.ResponseBodyPolicy.ThrowIfCancellationRequestedOrTimeout(CancellationToken originalToken, CancellationToken timeoutToken, Exception inner, TimeSpan timeout)

   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)

   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)

[Error] Azure-Identity: False MSAL 4.61.3.0 MSAL.NetCore .NET 8.0.2 MacOS [2024-07-09 23:36:55Z - 7c03621c-f8f1-4bbb-a6e3-e0548d5becc7] Exception type: Azure.Identity.CredentialUnavailableException

---> Inner Exception Details

Exception type: System.Threading.Tasks.TaskCanceledException

---> Inner Exception Details

Exception type: System.Threading.Tasks.TaskCanceledException

---> Inner Exception Details

Exception type: System.Threading.Tasks.TaskCanceledException

To see full exception details, enable PII Logging. See https://aka.ms/msal-net-logging

   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)

   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)

   at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)


=== End of inner exception stack trace ===

To see full exception details, enable PII Logging. See https://aka.ms/msal-net-logging

   at System.Net.Http.HttpClient.HandleFailure(Exception e, Boolean telemetryStarted, HttpResponseMessage response, CancellationTokenSource cts, CancellationToken cancellationToken, CancellationTokenSource pendingRequestsCts)

   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)

   at Azure.Core.Pipeline.HttpClientTransport.ProcessSyncOrAsync(HttpMessage message, Boolean async)

   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline)

   at Azure.Core.Pipeline.ResponseBodyPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)


   at Azure.Core.Pipeline.RedirectPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)

2

   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)

   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)

   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)



=== End of inner exception stack trace ===

To see full exception details, enable PII Logging. See https://aka.ms/msal-net-logging

   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)

   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)

   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)

   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)

   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)

   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)

   at Microsoft.Identity.Client.Internal.Requests.RequestBase.<>c__DisplayClass11_1.<<RunAsync>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.Identity.Client.Utils.StopwatchService.MeasureCodeBlockAsync(Func`1 codeBlock)

   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)



[Informational] Azure-Identity: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://cognitiveservices.azure.com/.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): ManagedIdentityCredential authentication unavailable. No response received from the managed identity endpoint.

---> System.Threading.Tasks.TaskCanceledException (0x8013153b): The operation was cancelled because it exceeded the configured timeout of 0:00:01. Network timeout can be adjusted in ClientOptions.Retry.NetworkTimeout.

2

---> System.Threading.Tasks.TaskCanceledException (0x8013153b): A task was canceled.

[Informational] Azure-Identity: VisualStudioCredential.GetToken invoked. Scopes: [ https://cognitiveservices.azure.com/.default ] ParentRequestId:

[Informational] Azure-Identity: VisualStudioCredential.GetToken was unable to retrieve an access token. Scopes: [ https://cognitiveservices.azure.com/.default ] ParentRequestId:  Exception: Azure.Identity.CredentialUnavailableException (0x80131500): Visual Studio Token provider can't be accessed at /Users/********/.IdentityService/AzureServiceAuth/tokenprovider.json

---> System.IO.DirectoryNotFoundException (0x80070003): Could not find a part of the path '/Users/********/.IdentityService/AzureServiceAuth/tokenprovider.json'.

[Informational] Azure-Identity: AzureCliCredential.GetToken invoked. Scopes: [ https://cognitiveservices.azure.com/.default ] ParentRequestId:

[Informational] Azure-Identity: Client ID: ********. Tenant ID: ********. User Principal Name: [********](mailto:********) Object ID: ********

[Informational] Azure-Identity: AzureCliCredential.GetToken succeeded. Scopes: [ https://cognitiveservices.azure.com/.default ] ParentRequestId:  ExpiresOn: 2024-07-10T00:15:28.0000000+00:00

[Informational] Azure-Identity: DefaultAzureCredential credential selected: Azure.Identity.AzureCliCredential

[Informational] Azure-Identity: DefaultAzureCredential.GetToken succeeded. Scopes: [ https://cognitiveservices.azure.com/.default ] ParentRequestId:  ExpiresOn: 2024-07-10T00:15:28.0000000+00:00
```

**Comment by christothes** [comment]
From the Azure.Identity perspective, you are getting a token, so everything is ok from that perspective. The 401 seems to indicate that the token is not authorized for the resource, which is strange to see intermittently.

**Comment by annelo-msft** [comment]
> That makes sense, the upgrade to v2.0 has been painful due to SCM as well. Thanks for the update.

@cdwaddell, I am curious to learn more about your experience here.  What kind of difficulties are you having that are related to SCM?  Many thanks in advance for sharing your perspective!

**Comment by cdwaddell** [comment]
I forked the repo, and removed this check:
![image](https://github.com/user-attachments/assets/6ae88cfa-d37a-4129-9f17-98148195044b)
And I no longer get a 401 error.

**Comment by cdwaddell** [comment]
> > That makes sense, the upgrade to v2.0 has been painful due to SCM as well. Thanks for the update.
> 
> @cdwaddell, I am curious to learn more about your experience here. What kind of difficulties are you having that are related to SCM? Many thanks in advance for sharing your perspective!

@annelo-msft, glad to give our feedback:
* We use the Azure SDK and follow the guidelines around responses and response objects. All of which change in SCM (ie. RequestFailedExceptions becomse ClientResultExceptions). So we have to redo our middleware to make changes that no longer align to the azure-sdk-fo-net standard documentation.
* We have written numerous HttpPipelinePolicies, and leverage Microsoft.Extensions.Http.Resilience (formerly Polly). All of which needed to be reimplemented in SCM as PipelinePolicies. Some features were unable to be reimplemented because the corollary SCM classes are marked as Internal, or do not exist.
* We also had extensive Unit Testing around our classes where we Mocked the response objects. Those same Mocks are not possible or they became very difficult. Again, this is usually because of Internal classes, and the removal of Factory classes that made the v1.0 Azure OAI library easy to Mock.

**Comment by annelo-msft** [comment]
> @annelo-msft, glad to give our feedback

Thanks so much for this information!  If you're willing to also share information around which types being internal have been problematic for you, that would be helpful for us moving forward.  SCM is still in beta, so we have the ability to make some adjustments there if needed.  We are also actively adding features related to the ones in Azure.Core, so your input on features you would like to see the most could help us prioritize our work on this.

@KrzysztofCwalina, @joseharriaga, @trrwilson FYI - there may be opportunities here to make migrations from Azure.Core-based libraries to Azure libraries built around the SCM pipeline easier for end-users based on this feedback.

@cdwaddell, many thanks, and if more pain points occur to you as you go along, we would love to have them for our tracking.

**Comment by trrwilson** [comment]
> > From the Azure.Identity perspective, you are getting a token, so everything is ok from that perspective. The 401 seems to indicate that the token is not authorized for the resource, which is strange to see intermittently.
> 
> I forked the repo, and removed this check: ![image](https://private-user-images.githubusercontent.com/3679097/348327288-6ae88cfa-d37a-4129-9f17-98148195044b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzI3NTEsIm5iZiI6MTcyMTA3MjQ1MSwicGF0aCI6Ii8zNjc5MDk3LzM0ODMyNzI4OC02YWU4OGNmYS1kMzdhLTQxMjktOWYxNy05ODE0ODE5NTA0NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMTk0MDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNDZjMGY5OTYyNTZlMmQxNTA2Yzc1NDQ5NTU0NzQwZWNkZTc1M2QyM2JmNTc0ZWMzZTVjNzFiMDYyMDMwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U_sVIatkUzA5UVLhJXTxQu-i7OTVhsBSSDvqGeO7cPY) And I no longer get any 401 errors.

@cdwaddell, removing that check will forcibly refresh the token on every call (calling the full, multi-second acquisition each time) -- it's great that removing it unblocks token use, but it'd be great to understand why it is that the forcibly refreshed token suddenly works. Do you see the same debug token spew with the pre-fallback acquisition succeeding on the second try (with the caching removed)?

Holistically, it seems like the right fix here is to ensure that a token is invalided if the request isn't successful.

**Comment by cdwaddell** [comment]
> > > From the Azure.Identity perspective, you are getting a token, so everything is ok from that perspective. The 401 seems to indicate that the token is not authorized for the resource, which is strange to see intermittently.
> > 
> > 
> > I forked the repo, and removed this check: ![image](https://private-user-images.githubusercontent.com/3679097/348327288-6ae88cfa-d37a-4129-9f17-98148195044b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEwNzI3NTEsIm5iZiI6MTcyMTA3MjQ1MSwicGF0aCI6Ii8zNjc5MDk3LzM0ODMyNzI4OC02YWU4OGNmYS1kMzdhLTQxMjktOWYxNy05ODE0ODE5NTA0NGIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxNSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTVUMTk0MDUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmYyNDZjMGY5OTYyNTZlMmQxNTA2Yzc1NDQ5NTU0NzQwZWNkZTc1M2QyM2JmNTc0ZWMzZTVjNzFiMDYyMDMwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.U_sVIatkUzA5UVLhJXTxQu-i7OTVhsBSSDvqGeO7cPY) And I no longer get any 401 errors.
> 
> @cdwaddell, removing that check will forcibly refresh the token on every call (calling the full, multi-second acquisition each time) -- it's great that removing it unblocks token use, but it'd be great to understand why it is that the forcibly refreshed token suddenly works. Do you see the same debug token spew with the pre-fallback acquisition succeeding on the second try (with the caching removed)?
> 
> Holistically, it seems like the right fix here is to ensure that a token is invalided if the request isn't successful.

I do not think the token will be forcibly refreshed with every call since the DefaultAzureCredentials and class handles token lifetime and refreshing for us. Unless I am missing something:

https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet#methods

**Comment by christothes** [comment]
> > Holistically, it seems like the right fix here is to ensure that a token is invalided if the request isn't successful.
> 
> I do not think the token will be forcibly refreshed with every call since the DefaultAzureCredentials class handles token lifetime and refreshing for us. Unless I am missing something:
> 
> https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet#methods

It's true that most of Azure.Identity's `TokenCredential` implementations will cache the token and refresh as appropriate. The scenario where you'd see the most latency, however, is for local dev/test if you are using any of the dev tool credentials.

**Comment by cdwaddell** [comment]
> > > Holistically, it seems like the right fix here is to ensure that a token is invalided if the request isn't successful.
> > 
> > 
> > I do not think the token will be forcibly refreshed with every call since the DefaultAzureCredentials class handles token lifetime and refreshing for us. Unless I am missing something:
> > https://learn.microsoft.com/en-us/dotnet/api/azure.identity.defaultazurecredential?view=azure-dotnet#methods
> 
> It's true that most of Azure.Identity's `TokenCredential` implementations will cache the token and refresh as appropriate. The scenario where you'd see the most latency, however, is for local dev/test if you are using any of the dev tool credentials.

I am using DefaultAzureCredentials which is either Managed Instance or AZ CLI when running locally, so I do not need the extra expiration check which seems to cause the use of tokens that are no longer valid resulting in a 401.
