### ISSUE TITLE
[QUERY] ServiceBus - using managed identity throws exception in webjob part

### ISSUE THREAD

**Issue by bogdanpescarus** [Azure/azure-sdk-for-net#45277]
### Library name and version

Microsoft.Azure.WebJobs.Extensions.ServiceBus 5.16.2

### Query/Question

We are trying to migrate our service bus away from connection strings and use managed identities instead.

This is how we try to do it:

```
                var serviceBusName = ConfigManager.GetServiceBusName();
                var fullyQualifiedNamespace = string.Format("{0}.servicebus.windows.net", serviceBusName);
                var builder = new HostBuilder();

                builder.ConfigureAppConfiguration((hostBuilderContext, config) =>
                    {
                        config.Add(new MemoryConfigurationSource()
                        {
                            InitialData = new Dictionary<string, string>
                            {
                                //{ $"AzureWebJobsServiceBus", connectionString },  // this is how we did it in the past, when we had connection strings
                                { "ServiceBusConnection:fullyQualifiedNamespace", fullyQualifiedNamespace },
                                //{ "ConnectionStrings:ServiceBus", fullyQualifiedNamespace },  // tried this as well
                                //{ "connection:fullyQualifiedNamespace", fullyQualifiedNamespace },  // tried this as well
                            },
                        });

                       // ... other non relevant configs
                    });

                builder.ConfigureWebJobs(b =>
                    {
                        b.AddServiceBus();
                        // ...
                    })
                    .UseEnvironment(ConfigManager.GetEnvironmentVariable().ToString())
                    .ConfigureHostConfiguration(y => y.AddEnvironmentVariables("Environment"))
                    .ConfigureServices((hostContext, services) =>
                    {
                        Startup.InitializeAsync(services, hostContext.Configuration, _refresher);  // (**)
                    });

                var host = builder.Build();
                using (host)
                {
                    Console.WriteLine("Init ServiceBus !!");
                    ServiceBusProvider.InitializeServiceBusMessageReceiver();  // here we initialize the ServiceBusClient, ServiceBusAdministratorClient, a subscription and a topic (and this works without throwing any exception)
                    await host.RunAsync();
                }
```

(**) In the Startup.InitializeAsync() method, I added this:

```
            services.AddAzureClients(builder =>
            {
                builder.AddServiceBusClientWithNamespace(fullyQualifiedNamespace);
                builder.UseCredential(new ManagedIdentityCredential());
            });
```

But the webjob won't start. There's an exception thrown by host.RunAsync(). The message states:
`Service Bus account connection string with name 'ServiceBus' does not exist in the settings. Make sure that it is a defined App Setting.`

And the stacktrace is this:
```
   at Microsoft.Azure.WebJobs.Extensions.ServiceBus.Config.ServiceBusClientFactory.ResolveConnectionInformation(String connection)
   at Microsoft.Azure.WebJobs.Extensions.ServiceBus.Config.ServiceBusClientFactory.CreateClientFromSetting(String connection)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.<>c__DisplayClass36_0.<.ctor>b__8()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.Dispose()
   at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 55
   at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\CompositeListener.cs:line 70
   at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\ListenerFactoryListener.cs:line 91
   at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\ShutdownListener.cs:line 50
   at Microsoft.Azure.WebJobs.JobHost.Dispose(Boolean disposing) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 292
   at Microsoft.Azure.WebJobs.JobHost.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 303
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at M365.Narada.EmailService.Program.<Main>d__5.MoveNext() in C:\__w\1\s\ConsumerEmails\M365.ConsumerNarada.EmailService\Program.cs:line 201
```

Am I missing something? All that I'm trying to do is migrate away from connection strings to Managed Identitiy, and I see that the ServiceBus has APIs for this. 
Thanks!

**Comment by bogdanpescarus** [comment]
Edit:

If I do this:

```
                builder.ConfigureAppConfiguration((hostBuilderContext, config) =>
                    {
                        config.Add(new MemoryConfigurationSource()
                        {
                            InitialData = new Dictionary<string, string>
                            {
                                //{ $"AzureWebJobsServiceBus", connectionString },
                                //{ $"AzureWebJobsServiceBus", fullyQualifiedNamespace },
                                //{ "ServiceBusConnection:fullyQualifiedNamespace", fullyQualifiedNamespace },
                                **{ "ServiceBus:fullyQualifiedNamespace", fullyQualifiedNamespace },
                                { "ServiceBus", fullyQualifiedNamespace },**
                                //{ "ConnectionStrings:ServiceBus", fullyQualifiedNamespace },
                                //{ "connection:fullyQualifiedNamespace", fullyQualifiedNamespace },
                            },
                        });

                        var settings = new Dictionary<string, string>
                        {
                            //{ "ConnectionStrings:ServiceBus", fullyQualifiedNamespace },
                            //{ "connection:fullyQualifiedNamespace", fullyQualifiedNamespace },
                            //{ "ServiceBusConnection:fullyQualifiedNamespace", fullyQualifiedNamespace },
                            **{ "ServiceBus:fullyQualifiedNamespace", fullyQualifiedNamespace },
                            { "ServiceBus", fullyQualifiedNamespace },**
                        };
                   // ...
               }
```

I get the following stack trace:
   at Azure.Messaging.ServiceBus.ServiceBusConnectionStringProperties.Parse(String connectionString)
   at Azure.Messaging.ServiceBus.ServiceBusConnection..ctor(String connectionString, ServiceBusClientOptions options)
   at Azure.Messaging.ServiceBus.ServiceBusClient..ctor(String connectionString, ServiceBusClientOptions options)
   at Microsoft.Azure.WebJobs.ServiceBus.MessagingProvider.<>c__DisplayClass19_0.<CreateClient>b__0(String _)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.<>c__DisplayClass36_0.<.ctor>b__8()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.LazyInitValue()
   at Microsoft.Azure.WebJobs.ServiceBus.Listeners.ServiceBusListener.Dispose()
   at Microsoft.Azure.WebJobs.Host.Listeners.FunctionListener.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\FunctionListener.cs:line 55
   at Microsoft.Azure.WebJobs.Host.Listeners.CompositeListener.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\CompositeListener.cs:line 70
   at Microsoft.Azure.WebJobs.Host.Listeners.ListenerFactoryListener.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\ListenerFactoryListener.cs:line 91
   at Microsoft.Azure.WebJobs.Host.Listeners.ShutdownListener.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\Listeners\ShutdownListener.cs:line 50
   at Microsoft.Azure.WebJobs.JobHost.Dispose(Boolean disposing) in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 292
   at Microsoft.Azure.WebJobs.JobHost.Dispose() in D:\a\_work\1\s\src\Microsoft.Azure.WebJobs.Host\JobHost.cs:line 303
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.DisposeAsync()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.Internal.Host.<DisposeAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.<RunAsync>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at M365.Narada.EmailService.Program.<Main>d__5.MoveNext() in C:\__w\1\s\ConsumerEmails\M365.ConsumerNarada.EmailService\Program.cs:line 207

**Comment by bogdanpescarus** [comment]
Ah, nevermind, I managed to make it work. Apparently the magic combo is:

`{ "AzureWebJobsServiceBus:fullyQualifiedNamespace", fullyQualifiedNamespace}`

I added this as an in memory config and it worked !!

**Comment by JoshLove-msft** [comment]
Yes, the issue is that your connection setting was not matching the default connection setting. You can either use the default as you mention above, or explicitly specify your connection setting name in the ServiceBusTrigger attribute in your function.
