### ISSUE TITLE
Randomly fail to create PublicIPAddress in batch mode

### ISSUE THREAD

**Issue by ccic** [Azure/azure-sdk-for-net#4531]
My SDK version is 1.11.1, Newtownsoft.Json version is 11.0.2:

"Microsoft.Azure.Management.Compute.Fluent" Version="1.11.1"
"Microsoft.Azure.Management.Fluent" Version="1.11.1"
"Microsoft.Azure.Management.ResourceManager.Fluent" Version="1.11.1"
"Newtonsoft.Json" Version="11.0.2"

I want to create some PublicIPAddress in batch mode, so I write the following code:

            // create vms
            var publicIpTaskList = new List<Task<IPublicIPAddress>>();
            Util.Log("Creating public IP address...");
            for (var i = 0; i < agentConfig.VmCount; i++)
            {
                // create public ip
                var publicIPAddress = azure.PublicIPAddresses.Define(agentConfig.Prefix + Convert.ToString(i) + "PubIP")
                    .WithRegion(region)
                    .WithExistingResourceGroup(resourceGroupName)
                    .WithLeafDomainLabel(agentConfig.Prefix + Convert.ToString(i))
                    .WithDynamicIP()
                    .CreateAsync();
                publicIpTaskList.Add(publicIPAddress);
            }
            Task.WaitAll(publicIpTaskList.ToArray());
But I encounter errors randomly. 

Unhandled Exception: System.AggregateException: One or more errors occurred. (Object reference not set to an instance of an object.) ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ExpandableStringEnum`1.set_Value(String value)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ExpandableStringEnum`1.Parse(String value)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ExpandableStringEnumConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(JsonProperty property, JsonConverter propertyConverter, JsonContainerContract containerContract, JsonProperty containerProperty, JsonReader reader, Object target)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(Object newObject, JsonReader reader, JsonObjectContract contract, JsonProperty member, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Network.Fluent.PublicIPAddressesOperations.BeginCreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String publicIpAddressName, PublicIPAddressInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Network.Fluent.PublicIPAddressesOperations.CreateOrUpdateWithHttpMessagesAsync(String resourceGroupName, String publicIpAddressName, PublicIPAddressInner parameters, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Network.Fluent.PublicIPAddressesOperationsExtensions.CreateOrUpdateAsync(IPublicIPAddressesOperations operations, String resourceGroupName, String publicIpAddressName, PublicIPAddressInner parameters, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.Network.Fluent.PublicIPAddressImpl.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.Creatable`4.Microsoft.Azure.Management.ResourceManager.Fluent.Core.ResourceActions.IResourceCreator<IResourceT>.CreateResourceAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.CreatorTaskItem`1.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.DAG.TaskGroupBase`1.ExecuteNodeTaskAsync(DAGNode`1 node, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.WaitAllCore(Task[] tasks, Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.WaitAll(Task[] tasks)

**Comment by shahabhijeet** [comment]
@ccic opened in the right repo
https://github.com/Azure/azure-libraries-for-net/issues/455
