### ISSUE TITLE
[BUG] After update versions for Azure.Core, Azure.Storage.Blobs

### ISSUE THREAD

**Issue by Alex-Anisov** [Azure/azure-sdk-for-net#45370]
### Library name and version

Azure.Core 1.40.0 + Azure.Storage.Blobs 12.20.0

### Describe the bug

We have a code:

```
using Azure.Storage.Blobs;
using Azure.Storage.Blobs.Models;
using System;
using System.Collections.Concurrent;

public static class UserDelegationKeyFactory
{
    static ConcurrentDictionary<string, UserDelegationKey> _cache = new ConcurrentDictionary<string, UserDelegationKey>();

    public static UserDelegationKey GetOrCreate(BlobServiceClient client)
    {
        DateTimeOffset utcNow = DateTimeOffset.UtcNow;

        // Check if a valid cached key exists
        if (_cache.TryGetValue(client.AccountName, out UserDelegationKey cachedUserDelegationKey))
        {
            // Calculate the minimal valid threshold as 6 days and 23 hours from now
            DateTimeOffset minimalValidThreshold = utcNow.AddHours((6 * 24) + 23);

            // Check if the cached key will be valid beyond this threshold
            if (cachedUserDelegationKey.SignedExpiresOn > minimalValidThreshold)
                return cachedUserDelegationKey;
        }

        // If no valid cached key, or it's expiring sooner than 6 days and 23 hours from now, create a new one
        var startTime = utcNow.AddMinutes(-5);

        // Set expiry time to 7 days from the adjusted start time
        var expiryTime = startTime.AddDays(7);

        var newUserDelegationKey = client.GetUserDelegationKey(startTime, expiryTime);
        _cache[client.AccountName] = newUserDelegationKey;

        return newUserDelegationKey;
    }
}
```

Everything was ok, till the moment we started update Nuget packages:

Azure.Core 1.33.0 -> 1.40.0
Azure.Storage.Blobs 12.14.1 -> 12.20.0

After update, on different environments we started to see sporadic dependenci errors with next tack trace:

System.Threading.ThreadAbortException: Thread was being aborted.
at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
at Azure.Storage.Blobs.ServiceRestClient.GetUserDelegationKey(KeyInfo keyInfo, Nullable`1 timeout, CancellationToken cancellationToken)
at Azure.Storage.Blobs.BlobServiceClient.<GetUserDelegationKeyInternal>d__58.MoveNext()

We have different configurations which execute code above, on VMs and in Docker containers, targeting blobs on different storage accounts and even in different Azure regions. Every combination of environment-storage account-azure region was affected more or less, was not able to discover any regularity related to abovementioned factors.
We had errors for few days till versions revert.

After rollback package versions to 1.33.0\12.14.1 accordingly, we are not seeing such errors on any our environments.

Already had a call with Azure support, was not able to identify any problems on storage account side\our WMs (i.e. high CPU\Memory) in correlation with erroring period.

### Expected behavior

No errors when getting UserDelegationKey for blob

### Actual behavior

Sporadic errors when getting UserDelegationKey for blob with stack trace

System.Threading.ThreadAbortException: Thread was being aborted.
at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
at Azure.Core.Pipeline.RetryPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelinePolicy.ProcessNext(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.Process(HttpMessage message, ReadOnlyMemory`1 pipeline)
at Azure.Core.Pipeline.HttpPipeline.Send(HttpMessage message, CancellationToken cancellationToken)
at Azure.Storage.Blobs.ServiceRestClient.GetUserDelegationKey(KeyInfo keyInfo, Nullable`1 timeout, CancellationToken cancellationToken)
at Azure.Storage.Blobs.BlobServiceClient.<GetUserDelegationKeyInternal>d__58.MoveNext()

### Reproduction Steps

No STR yet, but working on small app, which might reproduce this issue.

### Environment

Azure WMs\ Docker Containers
Target Framework - net48

**Comment by amnguye** [comment]
Taken offline.

Updating discussion looks to be fixed in Azure.Core v1.41.0, so please upgrade accordingly. Also if you upgrade to Azure.Storage.Blobs v12.20.1, it will automatically point to v1.41.0 of Azure.Core
