### ISSUE TITLE
[BUG] Get latest rolling upgrade status of VMSS failed with System.ArgumentNullException: Value cannot be null. (Parameter 'id')

### ISSUE THREAD

**Issue by sjtufl** [Azure/azure-sdk-for-net#45613]
### Library name and version

Azure.ResourceManager.Compute 1.5.0

### Describe the bug

Use ` VirtualMachineScaleSetRollingUpgradeResource.GetLatest()` to fetch latest rolling upgrade status of a VMSS will always fail with the exception below:

```
System.ArgumentNullException: Value cannot be null. (Parameter 'id')
   at Azure.ResourceManager.ArmResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetRollingUpgradeResource..ctor(ArmClient client, ResourceIdentifier id)
   at Azure.ResourceManager.Compute.VirtualMachineScaleSetRollingUpgradeResource.GetAsync(CancellationToken cancellationToken)
```

### Expected behavior

Successful response with `VirtualMachineScaleSetRollingUpgradeData` in the body.

### Actual behavior

Exception is thrown.

### Reproduction Steps

Assume vmss is of `VirtualMachineScaleSetResource` type,

```
var getRollingUpgradeResult = await vmss.GetVirtualMachineScaleSetRollingUpgrade().GetAsync();
```

### Environment

.NET SDK:
 Version:           8.0.400

Runtime Environment:
 OS Name:     Windows

**Comment by VladimirKhvostov** [comment]
@HarveyLink,
Do you have an ETA for the fix?

Here is an example of 
`GET https://management.azure.com/subscriptions/<subId>/resourceGroups/<resourceGroup>/providers/Microsoft.Compute/virtualMachineScaleSets/<vmssName>/rollingUpgrades/latest?api-version=2024-07-01 ` payload:

```Json
{
  "type": "Microsoft.Compute/virtualMachineScaleSets/rollingUpgrades",
  "location": "westus2",
  "properties": {
    "policy": {
      "maxBatchInstancePercent": 10,
      "maxUnhealthyInstancePercent": 10,
      "maxUnhealthyUpgradedInstancePercent": 20,
      "pauseTimeBetweenBatches": "PT10M",
      "prioritizeUnhealthyInstances": true,
      "maxSurge": false,
      "rollbackFailedInstancesOnPolicyBreach": false
    },
    "runningStatus": {
      "lastAction": "Start",
      "lastActionTime": "2025-03-13T01:44:36.1596526+00:00",
      "code": "RollingForward",
      "startTime": "2025-03-13T01:44:36.2690258+00:00"
    },
    "progress": {
      "successfulInstanceCount": 0,
      "failedInstanceCount": 0,
      "inProgressInstanceCount": 1,
      "pendingInstanceCount": 5
    }
  }
}
```
It does not have Id.

![Image](https://github.com/user-attachments/assets/30416997-e779-4afb-907f-4a3e4ee0b337)

**Comment by HarveyLink** [comment]
After some investigating, we found that this is a service issue, will contact service for the further fix.
