### ISSUE TITLE
System.NullReferenceException on at OpenAI.Chat.StreamingChatCompletionUpdate.get_ContentUpdate()

### ISSUE THREAD

**Issue by behrad-techtiq** [Azure/azure-sdk-for-net#45667]
### Library name and version

Azure.AI.OpenAI/2.0.0-beta-2

### Describe the bug

implemented chat streaming as [this](https://learn.microsoft.com/en-us/dotnet/api/overview/azure/ai.openai-readme?view=azure-dotnet-preview#stream-chat-messages) 

`completionUpdate.ContentUpdate returns System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenAI.Chat.StreamingChatCompletionUpdate.get_ContentUpdate()
   at Program.Main(String[] args) `
   
   
   in middle of response.

<img width="2444" alt="Screenshot 2024-08-24 at 1 08 09 PM" src="https://github.com/user-attachments/assets/49fddf78-19a9-4c2c-93e3-ad5f179f690e">

### Expected behavior

finish the response without the error

### Actual behavior

`System.NullReferenceException: Object reference not set to an instance of an object.
   at OpenAI.Chat.StreamingChatCompletionUpdate.get_ContentUpdate()
   at Program.Main(String[] args) in 

### Reproduction Steps

AzureOpenAIClient azureClient = new(
    new Uri("https://your-azure-openai-resource.com"),
    new DefaultAzureCredential());
ChatClient chatClient = azureClient.GetChatClient("my-gpt-35-turbo-deployment");

ResultCollection<StreamingChatCompletionUpdate> completionUpdates = chatClient.CompleteChatStreaming(
    [
        new SystemChatMessage("You are a helpful assistant that talks like a pirate."),
        new UserChatMessage("Hi, can you help me?"),
        new AssistantChatMessage("Arrr! Of course, me hearty! What can I do for ye?"),
        new UserChatMessage("What's the best way to train a parrot?"),
    ]);

foreach (StreamingChatCompletionUpdate completionUpdate in completionUpdates)
{
    foreach (ChatMessageContentPart contentPart in completionUpdate.ContentUpdate)
    {
        Console.Write(contentPart.Text);
    }
}`

### Environment

.net 8 Console app

**Comment by behrad-techtiq** [comment]
@jpalvarezl any update on this ?
Thanks
