### ISSUE TITLE
[BUG] SharedTokenCacheCredential authentication fails in Azure.Identity on ubuntu on pipeline

### ISSUE THREAD

**Issue by walmikiarjun** [Azure/azure-sdk-for-net#45692]
### Library name and version

Version      : 2.242.1

### Describe the bug
```
2024-08-27T18:37:03.7576305Z ##[section]Starting: Generate database script
2024-08-27T18:37:03.7586650Z ==============================================================================
2024-08-27T18:37:03.7586817Z Task         : .NET Core
2024-08-27T18:37:03.7586904Z Description  : Build, test, package, or publish a dotnet application, or run a custom dotnet command
2024-08-27T18:37:03.7587047Z Version      : 2.242.1
2024-08-27T18:37:03.7587118Z Author       : Microsoft Corporation
2024-08-27T18:37:03.7587216Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/build/dotnet-core-cli
2024-08-27T18:37:03.7587346Z ==============================================================================
2024-08-27T18:37:04.0837997Z Info: .NET Core SDK/runtime 2.2 and 3.0 are now End of Life(EOL) and have been removed from all hosted agents. If you're using these SDK/runtimes on hosted agents, kindly upgrade to newer versions which are not EOL, or else use UseDotNet task to install the required version.
2024-08-27T18:37:04.0855609Z [command]/opt/hostedtoolcache/dotnet/dotnet ef migrations script -p svc-mje-api/source/Dow.Mjeapi.Data/Dow.Mjeapi.Data.csproj -s svc-mje-api/source/Dow.Mjeapi/Dow.Mjeapi.csproj -o /home/vsts/work/1/a/migration.sql -i
2024-08-27T18:37:06.2340787Z Build started...
2024-08-27T18:37:11.7047683Z Build succeeded.
2024-08-27T18:37:19.2643549Z fail: Dow.Mjeapi.Startup[0]
2024-08-27T18:37:19.2645037Z       EventId: e53cfc9b-883a-4ef8-84cf-a4305f8faf86, Message: InteractiveBrowserCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH., CustomMessage: 
2024-08-27T18:37:19.2646226Z       Azure.Identity.AuthenticationFailedException: InteractiveBrowserCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
2024-08-27T18:37:19.2647912Z        ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
2024-08-27T18:37:19.2648413Z          at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
2024-08-27T18:37:19.2648739Z          at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.VerifyPersistence()
2024-08-27T18:37:19.2649049Z          at Azure.Identity.MsalCacheHelperWrapper.VerifyPersistence()
2024-08-27T18:37:19.2649383Z          at Azure.Identity.TokenCache.GetCacheHelperAsync(Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2649750Z          at Azure.Identity.TokenCache.GetCacheHelperAsync(Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2650125Z          at Azure.Identity.TokenCache.RegisterCache(Boolean async, ITokenCache tokenCache, CancellationToken cancellationToken)
2024-08-27T18:37:19.2650542Z          at Azure.Identity.MsalClientBase`1.GetClientAsync(Boolean enableCae, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2651085Z          at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveCoreAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean enableCae, BrowserCustomizationOptions browserOptions, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2651776Z          at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean enableCae, BrowserCustomizationOptions browserOptions, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2652344Z          at Azure.Identity.InteractiveBrowserCredential.GetTokenViaBrowserLoginAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2653073Z          at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2653668Z          --- End of inner exception stack trace ---
2024-08-27T18:37:19.2654015Z          at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
2024-08-27T18:37:19.2654469Z          at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2654851Z          at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2024-08-27T18:37:19.2655201Z          at Azure.Identity.InteractiveBrowserCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2655680Z          at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2656169Z          at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2656615Z          at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
2024-08-27T18:37:19.2657053Z          at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2657433Z          at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2024-08-27T18:37:19.2657792Z          at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2658480Z          at Dow.Mjeapi.Startup.<>c__DisplayClass17_0.<ConfigureServices>b__8(DbContextOptionsBuilder options) in /home/vsts/work/1/s/svc-mje-api/source/Dow.Mjeapi/Startup.cs:line 182
2024-08-27T18:37:19.2760812Z fail: Dow.Mjeapi.Startup[0]
2024-08-27T18:37:19.2761552Z       Error retrieving access token for database connection.
2024-08-27T18:37:19.2762850Z       Azure.Identity.AuthenticationFailedException: InteractiveBrowserCredential authentication failed: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
2024-08-27T18:37:19.2764150Z        ---> Microsoft.Identity.Client.Extensions.Msal.MsalCachePersistenceException: Persistence check failed. Data was written but it could not be read. Possible cause: on Linux, LibSecret is installed but D-Bus isn't running because it cannot be started over SSH.
2024-08-27T18:37:19.2764815Z          at Microsoft.Identity.Client.Extensions.Msal.Storage.VerifyPersistence()
2024-08-27T18:37:19.2765205Z          at Microsoft.Identity.Client.Extensions.Msal.MsalCacheHelper.VerifyPersistence()
2024-08-27T18:37:19.2765659Z          at Azure.Identity.MsalCacheHelperWrapper.VerifyPersistence()
2024-08-27T18:37:19.2766679Z          at Azure.Identity.TokenCache.GetCacheHelperAsync(Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2767079Z          at Azure.Identity.TokenCache.GetCacheHelperAsync(Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2767419Z          at Azure.Identity.TokenCache.RegisterCache(Boolean async, ITokenCache tokenCache, CancellationToken cancellationToken)
2024-08-27T18:37:19.2767773Z          at Azure.Identity.MsalClientBase`1.GetClientAsync(Boolean enableCae, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2768254Z          at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveCoreAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean enableCae, BrowserCustomizationOptions browserOptions, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2769164Z          at Azure.Identity.MsalPublicClient.AcquireTokenInteractiveAsync(String[] scopes, String claims, Prompt prompt, String loginHint, String tenantId, Boolean enableCae, BrowserCustomizationOptions browserOptions, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2769659Z          at Azure.Identity.InteractiveBrowserCredential.GetTokenViaBrowserLoginAsync(TokenRequestContext context, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2770067Z          at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2770557Z          --- End of inner exception stack trace ---
2024-08-27T18:37:19.2770857Z          at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
2024-08-27T18:37:19.2771262Z          at Azure.Identity.InteractiveBrowserCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2771598Z          at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2024-08-27T18:37:19.2771918Z          at Azure.Identity.InteractiveBrowserCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2772331Z          at Azure.Identity.DefaultAzureCredential.GetTokenFromSourcesAsync(TokenCredential[] sources, TokenRequestContext requestContext, Boolean async, CancellationToken cancellationToken)
2024-08-27T18:37:19.2772744Z          at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2773131Z          at Azure.Identity.CredentialDiagnosticScope.FailWrapAndThrow(Exception ex, String additionalMessage, Boolean isCredentialUnavailable)
2024-08-27T18:37:19.2773521Z          at Azure.Identity.DefaultAzureCredential.GetTokenImplAsync(Boolean async, TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2773848Z          at Azure.Core.Pipeline.TaskExtensions.EnsureCompleted[T](ValueTask`1 task)
2024-08-27T18:37:19.2774160Z          at Azure.Identity.DefaultAzureCredential.GetToken(TokenRequestContext requestContext, CancellationToken cancellationToken)
2024-08-27T18:37:19.2774758Z          at Dow.Mjeapi.Startup.<>c__DisplayClass17_0.<ConfigureServices>b__8(DbContextOptionsBuilder options) in /home/vsts/work/1/s/svc-mje-api/source/Dow.Mjeapi/Startup.cs:line 182
2024-08-27T18:37:19.2987425Z The exception 'An exception was thrown while activating λ:Microsoft.EntityFrameworkCore.DbContextOptions[] -> λ:Microsoft.EntityFrameworkCore.DbContextOptions -> λ:Microsoft.EntityFrameworkCore.DbContextOptions`1[[Dow.Mjeapi.Data.DatabaseContext, Dow.Mjeapi.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null]].' was thrown while attempting to find 'DbContext' types. For the different patterns supported at design time, see https://go.microsoft.com/fwlink/?linkid=851728
2024-08-27T18:37:19.3449293Z 
2024-08-27T18:37:19.3472562Z ##[error]Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 1
2024-08-27T18:37:19.3488164Z Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
2024-08-27T18:37:19.3490154Z ##[error]Dotnet command failed with non-zero exit code on the following projects : [ '' ]
2024-08-27T18:37:19.3547041Z ##[section]Finishing: Generate database script
```

### Expected behavior

I have window system why i am getting linux error in my pipeline   

### Actual behavior

We run this tool both on our dev machines and in the Azure DevOps release pipeline.  it fails on the build agent in the release pipeline (ubuntu):

my startup file is  
```c#
services.AddDbContext<DatabaseContext>(
     options =>
     {
         var connectionString = Configuration.GetConnectionString(DBConnectionKey);

         if (connectWithKey)
         {
             try
             {
                 var tokenCredential = new DefaultAzureCredential(
                     includeInteractiveCredentials: true);
                 // Set up EventHubProducerClient
                // var eventHubClient = new EventHubProducerClient("myeventhub.eventhubs.windows.net", "myhubpath", tokenCredential);
                 var token = tokenCredential.GetToken(
                     new TokenRequestContext(new[] { $"{DBTokenUrl}.default" })
                 ).Token;
                 var sqlConnection = new SqlConnection(connectionString)
                 {
                     AccessToken = token
                 };

                 options.UseSqlServer(sqlConnection);
                 Console.WriteLine("EventHub and SQL Server clients initialized successfully.");
             }
             catch (Exception ex)
             {
                 ExceptionManager.HandleException(ex);
                 _logger.LogError(ex, "Error retrieving access token for database connection.");
                 throw;
             }
         }
         else
         {
            // options.UseSqlServer(connectionString);
         }
     });
```

### Reproduction Steps

Dev environment

### Environment

window 10

**Comment by christothes** [comment]
Hi @walmikiarjun - 
When running on a build agent, `includeInteractiveCredentials: true` should not be passed to the `DefaultAzureCredential` constructor. This will result in being prompted interactively, which cannot be seen on the build agent. This specific error is happening for an unrelated reason that we should address but fixing that issue will then allow for the interactive credential prompt, which will hang on the agent.

If you want to preserve interactive login for local development, I'd recommend conditionally using a different credential when you detect that the code is running on the pipeline. If this is on Azure DevOps, you could detect this via the `TF_BUILD` environment variable being set to true.
