### ISSUE TITLE
[BUG] HDInsight GetHDInsightClustersAsync throws 'Value cannot be an empty string. (Parameter 'resourceId')'

### ISSUE THREAD

**Issue by chkp-swapnil-dhage** [Azure/azure-sdk-for-net#45709]
### Library name and version

Resource Management - HDInsight 1.1.0

### Describe the bug

When trying to list all the HDInsight clusters in a subscription using HDInsight Resource Management sdk, the call to GetHDInsightClustersAsync throws an error: "Value cannot be an empty string. (Parameter 'resourceId')". 

at Azure.Core.Argument.AssertNotNullOrEmpty(String value, String name)
   at Azure.Core.ResourceIdentifier..ctor(String resourceId)
   at Azure.ResourceManager.HDInsight.Models.HDInsightStorageAccountInfo.DeserializeHDInsightStorageAccountInfo(JsonElement element)
   at Azure.ResourceManager.HDInsight.Models.StorageProfile.DeserializeStorageProfile(JsonElement element)
   at Azure.ResourceManager.HDInsight.Models.HDInsightClusterProperties.DeserializeHDInsightClusterProperties(JsonElement element)
   at Azure.ResourceManager.HDInsight.HDInsightClusterData.DeserializeHDInsightClusterData(JsonElement element)
   at Azure.ResourceManager.HDInsight.Mocking.MockableHDInsightSubscriptionResource.<GetHDInsightClustersAsync>b__15_2(JsonElement e)
   at Azure.Core.PageableHelpers.PageableImplementation`1.CreatePage(Response response, String& nextLink)
   at Azure.Core.PageableHelpers.PageableImplementation`1.<AsPagesAsync>d__16.MoveNext()
   at Azure.Core.PageableHelpers.PageableImplementation`1.<AsPagesAsync>d__16.System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult(Int16 token)
   at System.Linq.AsyncEnumerable.<<ToListAsync>g__Core|424_0>d`1.MoveNext()
   at System.Linq.AsyncEnumerable.<<ToListAsync>g__Core|424_0>d`1.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ValueTaskAwaiter`1.GetResult()
   
the corresponding REST API response contains the following storage profile data:

"storageProfile": {
  "storageaccounts": [
    {
      "name": "hdinsightsdkupgstorage.blob.core.windows.net",
      "resourceId": "",
      "msiResourceId": null,
      "key": null,
      "fileSystem": null,
      "container": "clusterhdinsightsdkupgr-2024-08-27t11-22-30-704z",
      "saskey": null,
      "isDefault": true,
      "fileshare": null
    }
  ]
}

The HDInsight cluster was created from the Azure portal, and the storage was automatically created as part of it. Here, we can see that the `resourceId` is `null`, but the REST API still responds without failing. However, the SDK call throws a deserialization error for the storage account.
   

### Expected behavior

The call to `GetHDInsightClustersAsync` should not fail. The cluster was created through the Azure portal, and the REST API call with an empty `resourceId` doesn't fail. The appropriate fix would be to either ensure the API responds with the storage account `resourceId` or to allow a `null` value for the `resourceId`.

### Actual behavior

The call to `GetHDInsightClustersAsync` fails with deserialization error for empty the storage account `resourceId`. 

### Reproduction Steps

Create the HDInsightCluster resource from azure portal along with the storage account and try to call GetHDInsightClustersAsync for subscription resource.

**Comment by m-redding** [comment]
Thank you for your feedback.  Tagging and routing to the team member best able to assist.

**Comment by chkp-swapnil-dhage** [comment]
Could you please confirm if this issue is addressed in [1.2.0-beta.3](https://www.nuget.org/packages/Azure.ResourceManager.HDInsight/1.2.0-beta.3)? If not, when can I expect a beta release that includes this fix?
