### ISSUE TITLE
[BUG] CompleteChatAsync causes FromObjectAsJson method not found

### ISSUE THREAD

**Issue by RicBruIAI** [Azure/azure-sdk-for-net#45991]
### Library name and version

Azure.AI.OpenAI 2.0.0-beta.5

### Describe the bug

Whenever i launch the CompleteChatAsync method from a chat client (obtained with GetChatClient on a gpt 3.5 turbo, 0613 version model) it triggers this exception:
`Method not found: 'System.BinaryData System.BinaryData.FromObjectAsJson(!!0, System.Text.Json.JsonSerializerOptions)'.`

I am just porting the library from the 1.0.0-beta.17 to the latest one after receiving an emal indicating that the versions of the models on Azure will be auto-updated to the latest one (0125), so I am preparing my project with the latest SDKs, the project is using .NET version 6.0 and the project type is a Azure Functions project.

### Expected behavior

Just compute the results as expected without throwing the exception.

### Actual behavior

Exception thrown: 
`Method not found: 'System.BinaryData System.BinaryData.FromObjectAsJson(!!0, System.Text.Json.JsonSerializerOptions)'.`

### Reproduction Steps

Just create a Azure Functions project, imported the Azure.AI.OpenAI SDK from NuGet, deployed a model, using the keys to connect with it and launch the basic sample.

### Environment

.NET version 6.0.424

EDIT:
I've noticed such behaviour only on Azure Functions project.

```
System.TypeInitializationException
  HResult=0x80131534
  Message=The type initializer for 'OpenAI.ModelSerializationExtensions' threw an exception.
  Source=OpenAI
  StackTrace:
   at OpenAI.Chat.ChatCompletionOptions.ToBinaryContent()
   at OpenAI.Chat.ChatClient.<CompleteChatAsync>d__5.MoveNext()
   at IAI.Microlearning.Function.Functions.CourseFunction.<GenerateCourseHttpStart>d__15.MoveNext() in C:\Users\<ProjectPath>\Functions\CourseFunction.cs:line 880

  This exception was originally thrown at this call stack:

Inner Exception 1:
MissingMethodException: Method not found: 'System.BinaryData System.BinaryData.FromObjectAsJson(!!0, System.Text.Json.JsonSerializerOptions)'.
```

**Comment by RicBruIAI** [comment]
I've found the issue, in the Function API project, I had to specify the Nuget package **System.Memory.Data** to the version **8.0.0**. I actually don't know why this is necessary because on the other projects it wasn't specified (there was the version 1.0.2 actually).
