### ISSUE TITLE
[BUG] Frequent 401 exceptions when using DefaultAzureCredentials in the AzureOpenAIClient sdk

### ISSUE THREAD

**Issue by kushal-r** [Azure/azure-sdk-for-net#46398]
### Library name and version

Az Open AI sdk 2.0.0-beta.5

### Describe the bug

When using Az Open AI sdk 2.0.0-beta.5 for connecting with text embedding model using default azure credentials, few requests are getting dropped with status 401 Unauthorized. This is not happening for all requests, one in every ~110ms is having this issue. 
 

### Expected behavior

These should all result in 200 responses.

### Actual behavior

Intermittent 401 responses

### Reproduction Steps

Service fabric applications and using dependency injection

```
 AzureOpenAIClientOptions options = new AzureOpenAIClientOptions();
 _azureOpenAIClient = new(
     new Uri("openai"),
     new DefaultAzureCredential(),
     options);
 _embeddingClient = _azureOpenAIClient.GetEmbeddingClient("modelname");
```

Invoking the embeddings like this:

`var response = await _embeddingClient.GenerateEmbeddingsAsync(texts, options);
`
sdk : 
Dotnet core: 6.0
Azure.AI.OpenAI Version="2.0.0-beta.5"
       

```
System.ClientModel.ClientResultException: Service request failed.
Status: 401 (Unauthorized)

   at Azure.AI.OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at Azure.AI.OpenAI.Embeddings.AzureEmbeddingClient.GenerateEmbeddingsAsync(BinaryContent content, RequestOptions options)
   at OpenAI.Embeddings.EmbeddingClient.GenerateEmbeddingsAsync(IEnumerable`1 inputs, EmbeddingGenerationOptions options, CancellationToken cancellationToken)
   at 
Services.OpenAITextEmbeddingGenerator.GenerateEmbeddingAsync(IList`1 texts, Int32 dimensions, CancellationToken ct) in D:\a\_work\1\s\src\StoreValueAdd\Services\SearchDocumentConverter\Services\OpenAITextEmbeddingGenerator.cs:line 73
```

### Environment

Dotnet core 6.0

**Comment by mikeharder** [comment]
Possible duplicate of #46109
