### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by AkhileshAji** [Azure/azure-sdk-for-net#46514]
### Library name and version

Azure.AI.OpenAI (2.1.0-beta.1, 2.0.0, 2.0.0-beta.6)

### Describe the bug

When trying to upload files for batch or fine-tuning I get the following error
```
System.ClientModel.ClientResultException: HTTP 400 (invalidPayload)
The file has no or an empty content type specified.
   at Azure.AI.OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at Azure.AI.OpenAI.Files.AzureFileClient.UploadFileAsync(BinaryContent content, String contentType, RequestOptions options)
   at OpenAI.Files.OpenAIFileClient.UploadFileAsync(Stream file, String filename, FileUploadPurpose purpose, CancellationToken cancellationToken)
   at Azure.AI.OpenAI.Files.AzureFileClient.UploadFileAsync(Stream file, String filename, FileUploadPurpose purpose, CancellationToken cancellationToken)
   at GPTResumeParser.BatchParsing.GPTBatchParseClient.SendBatchParseRequestAsync(Byte[] file, String fileName, String batchId, CancellationToken ct)

HEADERS
=======
Accept: text/plain
Connection: keep-alive
Host: localhost
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:130.0) Gecko/20100101 Firefox/130.0
Accept-Encoding: gzip, deflate, br, zstd
Accept-Language: en-US,en;q=0.5
Referer: http://localhost/swagger/index.html
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
Priority: u=0
```

I am generating the file request like
```
        var client = new AzureOpenAIClient(new Uri(_openAIOptions.AzureEndpoint), new System.ClientModel.ApiKeyCredential(_openAIOptions.AzureApiKey)).GetOpenAIFileClient();
        var fileResponse = await client.UploadFileAsync(new BinaryData(data: file), fileName, FileUploadPurpose.Batch).ConfigureAwait(false);
```

Using Fiddler I am able to grab the request and the form-data is not sending a content-type
```
Content-Disposition: form-data; name=file; filename=12162d56-d5ef-4bba-9999-dd0122c9a0fa.jsonl; filename*=utf-8''12162d56-d5ef-4bba-9999-dd0122c9a0fa.jsonl={"custom_id...
```
When running this against the OpenAIFileClient not against azure I get the exact same request, but OpenAI does not complain about the lack of content type

### Expected behavior

I am expecting to be able to upload the file with the appropriate content type

### Actual behavior

The content type is missing in the form data

### Reproduction Steps

Create the client and attempt to upload a file

### Environment

Running on Windows 10, .net6
Visual Sudio 17.10.1

**Comment by AngelosP** [comment]
Hi @AkhileshAji,

Thank you for raising this issue! Hang tight while we take a look. 

Out of curiosity, do you get the same error when you do something like this (file client + non-async)?

```
var file = BinaryData.FromBytes(File.ReadAllBytes(fileName));

OpenAIFileInfo fileInfo = client.GetFileClient().UploadFile(
    file,
    fileName,
    FileUploadPurpose.FineTune);
```

**Comment by rakshachoudhary14** [comment]
> Hi [@AkhileshAji](https://github.com/AkhileshAji),
> 
> Thank you for raising this issue! Hang tight while we take a look.
> 
> Out of curiosity, do you get the same error when you do something like this (file client + non-async)?
> 
> ```
> var file = BinaryData.FromBytes(File.ReadAllBytes(fileName));
> 
> OpenAIFileInfo fileInfo = client.GetFileClient().UploadFile(
>     file,
>     fileName,
>     FileUploadPurpose.FineTune);
> ```

I tried the non-async and I am getting the same error 
System.ClientModel.ClientResultException: 'HTTP 400 (: invalidPayload)

Invalid file ContentType'

**Comment by rakshachoudhary14** [comment]
Is there anyone , who could send the file correctly

**Comment by ramon-rocha** [comment]
Is there any kind of workaround for this?
