### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by dolphinsd** [Azure/azure-sdk-for-net#46545]
### Library name and version

Azure.AI.OpenAI 2.1.0-beta.1

### Describe the bug

Setting MaxOutputTokenCount cause API call error with o1 model:

System.ClientModel.ClientResultException: HTTP 400 (invalid_request_error: unsupported_parameter)
Parameter: max_tokens

Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.
   at Azure.AI.OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at Azure.AI.OpenAI.Chat.AzureChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
   at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)

### Expected behavior

MaxOutputTokenCount  should set correct param based on the model

### Actual behavior

Wrong param is set

### Reproduction Steps

Call o1 model with setting MaxOutputTokenCount to a number

**Comment by AngelosP** [comment]
Hi @dolphinsd ,

Thank you for raising this issue. Please hang tight while we take a look and do not hesitate to add more details if you have any.

**Comment by janaka** [comment]
Hi, confirmed, we've seen this also. Setting `MaxOutputTokenCount=null` works. Setting MaxOutputTokenCount to a number throws this error. 

re-creatable code below:

```csharp
        [Fact]
        public async Task AzureOpenAIChatCompletionShouldReturnExpectedResult()
        {
            // Arrange
            var azureClientOptions = new AzureOpenAIClientOptions(version: AzureOpenAIClientOptions.ServiceVersion.V2024_08_01_Preview);
            var client = new AzureOpenAIClient(new Uri("https://RESOURCE_NAME_HERE.openai.azure.com/"), new ApiKeyCredential(API_KEY_HERE), azureClientOptions);
            var chatCompletionsOptions = new ChatCompletionOptions()
            {
                MaxOutputTokenCount = 20000, // omit or set to null works
                Temperature = 1.0f
            };
            var messages = new List<ChatMessage>
            {
                new UserChatMessage("What's the Sun?")
            };

            // Act
            var chatClient = client.GetChatClient(o1-preview-2024-09-12-DEPLOYMENT_NAME_HERE);
            var response = await chatClient.CompleteChatAsync(messages, chatCompletionsOptions);
            var result = string.Concat(response.Value.Content.Select(c => c.Text));

            // Assert
            Assert.NotNull(result);
            CustomAssertions.ContainsEither(result, "sun", "Sun");
        }
```

**Comment by bartczernicki** [comment]
The OpenAI.NET library has this working and routing through the MaxOutputTokenCount. Can this be fixed or applied with parity as this block o1 paramater settings.

**Comment by vovanb** [comment]
is it fixed?

**Comment by bartczernicki** [comment]
> is it fixed?

Yes, reasoning models now have the reasoning effort controls supported.

**Comment by vovanb** [comment]
When I set 
`
                var options = new ChatCompletionOptions()
                {
                    Temperature = 1f,
                    MaxOutputTokenCount = 200
                };`

and I am using gpt-5.2-chat with Azure.AI.OpenAI 2.1 latest stable : 

```
[0:] System.ClientModel.ClientResultException: HTTP 400 (invalid_request_error: unsupported_parameter)
09:29:38:659	Parameter: max_tokens
09:29:38:659	
09:29:38:659	Unsupported parameter: 'max_tokens' is not supported with this model. Use 'max_completion_tokens' instead.
09:29:38:659	   at Azure.AI.OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
09:29:38:659	   at Azure.AI.OpenAI.Chat.AzureChatClient.CompleteChatAsync(BinaryContent content, RequestOptions options)
09:29:38:659	   at OpenAI.Chat.ChatClient.CompleteChatAsync(IEnumerable`1 messages, ChatCompletionOptions options, CancellationToken cancellationToken)
```

**Comment by bartczernicki** [comment]
@vovanb You need todo something like this:

ChatCompletionOptions options = new()
{
    MaxOutputTokenCount = 200 
};

// For newer models (GPT-5, o4, etc.)
options.SetNewMaxCompletionTokensPropertyEnabled(true);

**Comment by janaka** [comment]
Also note, the Azure OpenAI API now has support  OpenAI compatibility mode which means you can use the OpenAI-dotnet link directly with Azure OpenAI interence services.

This means less chance of hitting missing params and ability to use json patch as an escape hatch if you do.

**Comment by samakhvalau** [comment]
This is sick, is this open source or like why wouldn't they spend a fraction of billions to fix goddamn .net wrapper lol

**Comment by janaka** [comment]
just use the OAI SDK directly. we ditched this azure sdk last year.
