### ISSUE TITLE
[BUG] Breaking change in exceptions thrown by BlobServiceClient

### ISSUE THREAD

**Issue by gt-dltk** [Azure/azure-sdk-for-net#46654]
### Library name and version

Azure.Storage.Blobs 12.22.2

### Describe the bug

We are migrating an application from net48 to net8.0.

On net48, failed operations reliably throw a `RequestFailedException`, as described in the documentation.

On net8.0, the same operations throw an `AggregationException`. This is a breaking change: software that previously handled failures correctly by catching `RequestFailedException` is now broken.

Handling the `AggregationException` is not a satisfactory because:

1. it is not documented and therefore subject to breaking changes in the future
2. the semantics are not clear: what if not all exceptions are `RequestFailedException`? What if there are equivalent `RequestFailedException`? Should the first one be used? The last one?

### Expected behavior

All methods that previously threw `RequestFailedException` and are documented as such should throw the same exception, whether running on net48 or net8.0.

### Actual behavior

Different exceptions are thrown on net48 and net8.0.

### Reproduction Steps

Here is a test case reproducing the issue, using XUnit and FluentAssertions. Run it under both net48 and net8.0. It fails on net8.0.

```csharp
        [Fact]
        public async Task GetPropertiesAsync_WhenAccountDoesNotExist_ThrowsRequestFailedException()
        {
            string connStringWithNonExistingDomain =
                $"DefaultEndpointsProtocol=https;" +
                $"AccountName=abc6546556482741849;" + // some account name that should not exist
                $"AccountKey=<REDACTED>" + // key does not matter
                $"EndpointSuffix=core.windows.net";
            var sut = new BlobServiceClient(connStringWithNonExistingDomain);

            Func<Task> act = () => sut.GetPropertiesAsync();

            await act.Should().ThrowExactlyAsync<RequestFailedException>();
        }
```

**Comment by nickliu-msft** [comment]
Hi @gt-dltk thanks for submitting this request.

To answer your above questions:
1. We actually recently updated documentation on AggregationException
https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/storage/Azure.Storage.Blobs/README.md#troubleshooting
2. To my understanding, if there is an AggregationException, all of the listed Exceptions should be RequestFailedException.

Also below is my reproduction of your given code:

```
        public async Task GetPropertiesAsync_WhenAccountDoesNotExist_ThrowsRequestFailedException()
        {
            string connStringWithNonExistingDomain =
                $"DefaultEndpointsProtocol=https;" +
                $"AccountName=abc6546556482741849;" + // some account name that should not exist
                $"AccountKey=Eby8vdM02xNOcqFlqUwJPLlmEtlCDXJ1OUzFT50uSRZ6IFsuFq2UVErCz4I6tq/K1SZFPTOtr/KBHBeksoGMGw==;" + // key does not matter
                $"EndpointSuffix=core.windows.net";
            var sut = new BlobServiceClient(connStringWithNonExistingDomain);
            try
            {
                await sut.GetPropertiesAsync();
            }
            catch (Exception ex)
            {
                Console.WriteLine("EXCEPTION = " + ex);
                if (ex is AggregateException)
                {
                    AggregateException aggregateException = (AggregateException)ex;
                    foreach (var innerException in aggregateException.Flatten().InnerExceptions)
                    {
                        Console.WriteLine($"Exception: {innerException.GetType()} - {innerException.Message}");
                    }
                }
            }
        }
```

For both net48 and net8.0, I got AggregationException for the top-level exception caught and confirmed that each of the inner-exceptions were of type RequestFailedException. Can you confirm if you are seeing the same on your end? If so I am not seeing the issue that you have described as you can handle net48 and net8.0 through AggregationException. 

FYI, I am on the latest version of Blobs

**Comment by gt-dltk** [comment]
@nickliu-msft, thanks for the reply and the effort put in reproducing the issue. I also appreciate the update to the README file.

I haven't verified that the same exception is thrown for both net48 and net8.0 in the latest version of the SDK. We do not have net48 code that depends on this library anymore.

The problems remains.

#### 1. The SDK throws undocumented exceptions (`AggregateException`).

Here is the documentation for `BlobServiceClient.GetProperties`: https://learn.microsoft.com/en-us/dotnet/api/azure.storage.blobs.blobserviceclient.getproperties?view=azure-dotnet

It clearly states that: 

> A [RequestFailedException](https://learn.microsoft.com/en-us/dotnet/api/azure.requestfailedexception?view=azure-dotnet) will be thrown if a failure occurs.

Yet, that's not what it does. This is only one example. I haven't verified that all methods of all classes throw the documented exceptions in all cases.

This means that consumers of the library simply cannot trust the documentation of the library to use it correctly. They have to actually verify that the library behaves (or not) as it claims. That defies the purpose of using a Microsoft-provided SDK: the main reason to use SDK is to be provided with a well-defined API surface that can be trusted to behave as described.

#### 2. Breaking changes

People (including us) have written code that consumes this library, catches `RequestFailedException` and handle it in whichever way makes sense for their application.

I have not been able to find any release notes where the change from throwing `RequestFailedException` to throwing `AggregateException` was mentioned. As a result, people (including us), have updated the library and may find themselves with broken software as a result. Code that previously correctly handled failures is now misbehaving.

We have changed our code accordingly, but the point here is that breaking changes should only be introduced in major versions and documented, so that consumers can adjust their code when they upgrade.

Testing (on the consumer's side) can detect some of these breaking changes. However, it is not practical for consumers to have automated tests covering all possible failures of all the SDK classes/methods that they use. Once again, the main reason to use SDK is to be provided with a well-defined API surface that can be trusted.

#### 3. The semantics are not clear

Exceptions are not only used for logging, as in your example. Sometimes, the callers wants to catch exceptions and decide what to do about it.

This `AggregateException` is unclear: if there are multiple `RequestFailedException` in the aggregate, how am I supposed to interpret them? Do they have some kind of ordering to them? Which one of them is the one that I should based my logic on?

-------

It is too late to avoid the breaking change. But my expectation to resolve this issue would be:

1. The documentation is updated: all members that are documenting as throwing `RequestFailedException` but actually throw `AggregateException` should be documented as such.
2. The meaning of the `AggregateException` is clarified.
3. The release notes of which this change was introduced are updated to describe the breaking change.

**Comment by amnguye** [comment]
@jsquire Is there a difference between net 4.8.X and net 8.0+ where in a Retry Policy that we now throw a `AggregrateException` in net 8.0+ and in net 4.8.X we still throw a `RequestFailedException` ?

**Comment by jsquire** [comment]
@amnguye :  No, there is no behavioral difference between platforms.  A `RequestFailedException` is surfaced from the pipeline if there was a single failure for an operation.   An `AggregateException` is surfaced from the pipeline for when operations are retried, and multiple failures are observed.   _([src](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/Pipeline/RetryPolicy.cs#L149))_.    

This behavior has remained unchanged since the original commit of the retry policy in 2019.  _([src](https://github.com/Azure/azure-sdk-for-net/commit/415dc6149b76e83c5278c585ba3f9ed2ba076e02#diff-febd7cf998bc4ddf62421967426fcbf48bafee8f8391bb97c485ecf4b019cf78R43))_.

**Comment by nickliu-msft** [comment]
@gt-dltk when migrating from net48 to net8.0, did you by chance configure the retry policy? If so that would definitely explain why before the migration there was just one RequestFailedException and afterwards there were multiple RequestFailedException underneath one AggregateException. As Jesse mentioned above, AggregateException only comes into play when there are multiple failures are observed and this has been around for a long time.

Either way, it seems like you have resolved this issue in your code. To close this out, I will go ahead and update all areas of documentation for AggregateException

**Comment by jsquire** [comment]
@nickliu-msft :  That sounds like a good start.   I'd suggest tracing through the code and seeing whether the Storage classifier is considering exceptions retriable on one platform rather than others and, if not, confirming that the RetryPolicy itself is making the decision.

**Comment by nickliu-msft** [comment]
@gt-dltk thanks for providing a thorough reproduction. I mimicked everything that you provided, however, I am still seeing AggregateException being thrown for _**both**_ net48 and net8.0. 

It is not until I add a BlobClientOptions to explicitly disable retries that I see RequestFailedException being thrown (_**but**_ this again happens for both net48 and net8.0).

```
        [Fact]
        public async Task GetPropertiesAsync_WhenAccountDoesNotExist_ThrowsRequestFailedException()
        {
            var options = new BlobClientOptions
            {
                Retry =
                {
                    MaxRetries = 0, // Number of retry attempts
                }
            };
            string connStringWithNonExistingDomain =
                $"DefaultEndpointsProtocol=https;" +
                $"AccountName=abc6546556482741849;" + // some account name that should not exist
                 $"AccountKey=<REDACTED>" + // key does not matter
                $"EndpointSuffix=core.windows.net";
            var sut = new BlobServiceClient(connStringWithNonExistingDomain, options);

            Func<Task> act = () => sut.GetPropertiesAsync();

            await act.Should().ThrowExactlyAsync<RequestFailedException>();
        }
```

As such, I am failing to see any discrepancies between net48 and net8.0.

Can you do try 2 things for me:
1. Can you iterate through the AggregateException in your example and see which Exceptions are underneath it? I have a feeling it is multiple identical RequestFailedExceptions which suggests that these are due to retries.
2. Replicate the above code with retries explicitly disabled and see if you are seeing the same results as me (RequestFailedException being thrown for both net48 and net8.0)

**Comment by gt-dltk** [comment]
@nickliu-msft , thanks for following up.

With the `MaxRetries = 0`, I see the same behavior as you do: both net48 and net8.0 throw a `RequestFailedException`.

----

With retries, I still see `AggregateException` on net8.0 and `RequestFailedException` on net48. But I think I might have found the source of the issue.

On our machines, we have some endpoint security software installed, through which all HTTP requests are proxied. When the domain name failed to resolve, the proxy returns a `502 Bad Gateway`.

Below is net8.0 exception:

![Image](https://github.com/user-attachments/assets/89f4ca22-1c30-4866-bdf6-ec734e69ca0f)

Stacktrace of one of the `RequestFailedException`:

```
   at Azure.Core.Pipeline.HttpClientTransport.<ProcessSyncOrAsync>d__11.MoveNext()
   at Azure.Core.Pipeline.HttpPipelineTransportPolicy.<ProcessAsync>d__4.MoveNext()
   at Azure.Core.Pipeline.ResponseBodyPolicy.<ProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.HttpPipelineSynchronousPolicy.<InnerProcessAsync>d__5.MoveNext()
   at Azure.Core.Pipeline.RedirectPolicy.<ProcessAsync>d__7.MoveNext()
   at Azure.Core.Pipeline.RetryPolicy.<ProcessAsync>d__5.MoveNext()
```

Stacktrace of the `HttpRequestException`:

```
   at System.Net.Http.HttpConnectionPool.<EstablishProxyTunnelAsync>d__110.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.<ConnectAsync>d__103.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.<CreateHttp11ConnectionAsync>d__105.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.<AddHttp11ConnectionAsync>d__79.MoveNext()
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.<WaitWithCancellationAsync>d__1.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.HttpConnectionWaiter`1.<WaitForConnectionWithTelemetryAsync>d__6.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Net.Http.HttpConnectionPool.<SendWithVersionDetectionAndRetryAsync>d__89.MoveNext()
   at System.Net.Http.HttpClient.<<SendAsync>g__Core|83_0>d.MoveNext()
   at Azure.Core.Pipeline.HttpClientTransport.<ProcessSyncOrAsync>d__11.MoveNext()
```

**Comment by jsquire** [comment]
> On our machines, we have some endpoint security software installed, through which all HTTP requests are proxied. When the domain name failed to resolve, the proxy returns a 502 Bad Gateway.

This could very well be the root cause.  If the intercepting proxy is failing with this kind of Gateway error, it's quite possible that failure code is being surfaced differently by the network stack in the .NET Framework implementation and the modern .NET runtime network stack, where one is considered transient and retried and the other isn't.

Do we know what the HTTP status codes are in each case?

**Comment by gt-dltk** [comment]
In both case, the proxy returns a 502 with some `text/html` content (see at the bottom), but the `RequestFailedException` is different.

On net8.0, the `RequestFailedException`s contained in the `AggregateException` have `Status = 0` and an inner exception of type `HttpRequestError` with `StatusCode = null, HttpRequestError = ProxyTunnelError`.

On net48, the `RequestFailedException` has `Status = 502` and no inner exception.

Here is the net48 exception:

![Image](https://github.com/user-attachments/assets/f7f93210-0c49-46eb-a40d-3b7b98a85ca8)

And the stack trace (not very informative)
```
   at Azure.Storage.Blobs.ServiceRestClient.<GetPropertiesAsync>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobServiceClient.<GetPropertiesInternal>d__49.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Blobs.BlobServiceClient.<GetPropertiesAsync>d__48.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at AzureBlobStorage.UnitTest.<GetPropertiesAsync_WhenAccountDoesNotExist_ThrowsRequestFailedException>d__0.MoveNext() in <REDACTED>\AzureBlobStorage\UnitTest.cs:line 26
```


---

The net48 exception message:

```
Service request failed.
Status: 502 (Bad Gateway)

Content:
<html><head><title>502 Bad Gateway</title></head>
<body><h1>DNS error</h1>
<p>DNS error (the host name of the page you are looking for does not exist)<br><br>Please check that the host name has been spelled correctly.<br></p>
</body></html>


Headers:
Connection: close
Content-Type: text/html
Server: <REDACTED>
```

**Comment by jsquire** [comment]
Thanks, @gt-dltk.  That solves the mystery.  It is indeed a .NET runtime behavioral difference in how it interprets and surfaces the proxy error.   One was classified retriable and the other was not.
