### ISSUE TITLE
uploading files for use in latest fileAssitant

### ISSUE THREAD

**Issue by JohnTranstel** [Azure/azure-sdk-for-net#47121]
### Library name and version

azure.ai.openai.assistants\1.0.0-beta.4\ 

### Query/Question

        I am creating an assistant as below.
I upload a file and get a valid looking fileId of the form
 file-IEhMNtaYJdLreZ53HdyqRyJL

When I then step into
            var fileUploadResponse = await vectorStore.AddFileToVectorStoreAsync(operation.VectorStoreId,   fileId, true);

It fails, 
System.ClientModel.ClientResultException: 'HTTP 404 (invalid_request_error: )
Files [file-IEhMNtaYJdLreZ53HdyqRyJL] were not found'

What am I doing wrong?

public static async Task<OpenAIFileAssistant> CreateFileAssistant(OpenAIFileAssistant fileAssistant)
        {
                       AzureOpenAIClient azureClient = new(
                       new Uri("uri"),
                      new ApiKeyCredential(apikey));

             var assistantClient = azureClient.GetAssistantClient();

            assistantCreationOptions = new AssistantCreationOptions()
            {
                Name = "File Analysis",
                Instructions = fileAssistant.Instruction,
                Tools = { ToolDefinition.CreateFileSearch() },
            };

            var assistant = await assistantClient.CreateAssistantAsync("gpt-4-PRMagic", assistantCreationOptions);
             var vectorStore = azureClient.GetVectorStoreClient();
            var operation = vectorStore.CreateVectorStore(true);

            string fullfilepath = fileAssistant.FilePath;
            string fileId = "";
            Files localFile = new Files("uri", apiKey);
            var uploadResponse = await localFile.UploadAsync(Files.Purpose.assistants, fullfilepath);
            if (uploadResponse is Files.FileResponse)
            {
                Files.FileResponse fileResponse = (Files.FileResponse)uploadResponse;
                fileId = fileResponse.id;
            }

            var fileUploadResponse = await vectorStore.AddFileToVectorStoreAsync(operation.VectorStoreId,   fileId, true);

            OpenAIFileAssistant response = new OpenAIFileAssistant();
            var thread = await assistantClient.CreateThreadAsync();
            response.FilePath = fileAssistant.FilePath;
            response.Question = "";
            response.Reply = "file uploaded with filename of" + fileUploadResponse.Value.ToString();
            response.AssistantValueId = assistant.Value.Id;
            response.ThreadValueId = thread.Value.Id;
            response.FileValueId = fileUploadResponse.Value.FileId;
            return response;
        }

### Environment

Microsoft Visual Studio Community 2022
Version 17.7.3
VisualStudio.17.Release/17.11.4+35312.102
Microsoft .NET Framework
Version 4.8.09037

Installed Version: Community

ASP.NET and Web Tools   17.7.273.65229
ASP.NET and Web Tools

Azure App Service Tools v3.0.0   17.7.273.65229
Azure App Service Tools v3.0.0

Azure Functions and Web Jobs Tools   17.7.273.65229
Azure Functions and Web Jobs Tools

C# Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

Microsoft JVM Debugger   1.0
Provides support for connecting the Visual Studio debugger to JDWP compatible Java Virtual Machines

NuGet Package Manager   6.7.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit https://docs.nuget.org/

Razor (ASP.NET Core)   17.7.3.2333001+0ab18affdf2a37647768d0e25f5f021bee6257a1
Provides languages services for ASP.NET Core Razor.

SQL Server Data Tools   17.7.10.1
Microsoft SQL Server Data Tools

TypeScript Tools   17.0.20628.2001
TypeScript Tools for Microsoft Visual Studio

Visual Basic Tools   4.7.0-3.23416.8+43b0b05cc4f492fd5de00f6f6717409091df8daa
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual F# Tools   17.7.0-beta.23314.10+e612cf93b989503c89e3a5830090062b7ab5e143
Microsoft Visual F# Tools

Visual Studio IntelliCode   2.2
AI-assisted development for Visual Studio.

WiX Toolset Visual Studio Extension   1.0.0.18
WiX Toolset Visual Studio Extension version 1.0.0.18
Copyright (c) .NET Foundation and contributors. All rights reserved.

**Comment by saasaTom** [comment]
I also have a similar problem (Using version: 2.1.0-beta.2) in some code that loops around some files uploading some 250 or so files.  Almost all of the files upload fine, but around 3-5 of them fail with the 404 error:

```C#
       var fileResult = await fileClient.UploadFileAsync(file, filename, FileUploadPurpose.Assistants, cancellationToken);
        var openAIFile = fileResult.Value;
            var addFileToVectorStoreOperation = await vectorStoreClient.AddFileToVectorStoreAsync(vectorStoreId, openAIFile.Id, true, cancellationToken);
```

The fileResult.Value.Status says "Processed" but the vectorStoreClient.AddFileToVectorStoreAsync command returns an error:

```c#
No file found with id 'file-........' in vector store 'vs_........'.
   at OpenAI.ClientPipelineExtensions.ProcessMessageAsync(ClientPipeline pipeline, PipelineMessage message, RequestOptions options)
   at OpenAI.VectorStores.VectorStoreClient.AddFileToVectorStoreAsync(String vectorStoreId, BinaryContent content, Boolean waitUntilCompleted, RequestOptions options)
   at OpenAI.VectorStores.VectorStoreClient.AddFileToVectorStoreAsync(String vectorStoreId, String fileId, Boolean waitUntilCompleted, CancellationToken cancellationToken)
   at file.UploadFileToVectorStoreAsync(VectorStoreClient vectorStoreClient, OpenAIFileClient fileClient, Guid tenantId, String vectorStoreId, Stream file, String filename, CancellationToken cancellationToken) in /Users/USER/file.cs:line 423
   at file.UploadAndSaveKbEntryAsync(KnowledgeAssistantOperation operation, Guid tenantId, String assistantId, String vectorStoreId, VectorStoreClient vectorStoreClient, OpenAIFileClient fileClient, EntryQuestionAndAnswer entry, Int32 currentCount, Int32 totalCount, CancellationToken cancellationToken) in /Users/USER/file.cs:line 551
Error processing entry .........: System.ClientModel.ClientResultException: HTTP 404 (invalid_request_error: )

```

**Comment by JohnTranstel** [comment]
Hi Tom,
there seem to be very few of us working in C# in this area.  I am happy to contact you directly to share what I am trying/doing. If you are interested email me at John@Transtel.com
