### ISSUE TITLE
[BUG]  Error in deserialization of DataFactoryPipelineResource

### ISSUE THREAD

**Issue by jmelhus** [Azure/azure-sdk-for-net#47196]
### Library name and version

Azure.ResourceManager.DataFactory 1.6.0

### Describe the bug

When retrieving DataFactoryPipelineResource from ArmClient it fails on deserializing 

System.InvalidCastException: 'Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.'

```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.
  Source=Azure.Core.Expressions.DataFactory
  StackTrace:
   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Deserialize[T](JsonElement json)
   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.ReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.CastingConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Azure.ResourceManager.DataFactory.Models.RestSource.DeserializeRestSource(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.CopyActivitySource.DeserializeCopyActivitySource(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.CopyActivity.DeserializeCopyActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.PipelineActivity.DeserializePipelineActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineData.DeserializeDataFactoryPipelineData(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.PipelinesRestOperations.<GetAsync>d__15.MoveNext()
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineCollection.<GetAsync>d__7.MoveNext()
   at Azure.ResourceManager.DataFactory.DataFactoryResource.<GetDataFactoryPipelineAsync>d__43.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in C:\Users\jmelh\source\repos\AzureDataFactory\AzureDataFactory\Program.cs:line 27
```
This error occurs when I have a pipeline with a linked REST service which has authentication in http header. 

Also see this issue https://github.com/Azure/azure-sdk-for-net/issues/40850

### Expected behavior

Retrieve DataFactoryPipelineResource for a pipeline or retrieve all pipelines without any problems

### Actual behavior

Exception on deserializing json response

### Reproduction Steps

Create ADF pipeline with REST linked service and anonymous authentication which adds auth header

```
{
    "name": "LinkedRESTService",
    "type": "Microsoft.DataFactory/factories/linkedservices",
    "properties": {
        "annotations": [],
        "type": "RestService",
        "typeProperties": {
            "url": "https://something-something.com/api/data",
            "enableServerCertificateValidation": true,
            "authenticationType": "Anonymous",
            "encryptedCredential": "myencryptedvalue"
        }
    }
}
```

Get pipeline with SDK

```
var credential = new DefaultAzureCredential();
var armClient = new ArmClient(credential);
var dataFactoryResourceId = new ResourceIdentifier("resourceId");
var dataFactory = armClient.GetDataFactoryResource(dataFactoryResourceId);
var pipeline = await dataFactory.GetDataFactoryPipelineAsync("myPipeLineName");
```

### Environment

.NET 8

**Comment by ArthurMa1978** [comment]
Thank you @jmelhus for your feedback, @ruowan please look into this issue.

**Comment by mkoval-ua** [comment]
@ruowan Any updates on this issue? this is affecting our ability to get and run pipeline programmatically because of that error

**Comment by homeallone** [comment]
@ruowan I also hit the same issue. I got 3 pipelines.. only on of them is getting this problem. Installed version v1.7. 

Unable to cast object of type 'System.Collections.Generic.Dictionary`2[System.String,System.Object]' to type 'System.String'.

   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Deserialize[T](JsonElement json)
   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.ReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.CastingConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Azure.ResourceManager.DataFactory.Models.RestSource.DeserializeRestSource(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.CopyActivitySource.DeserializeCopyActivitySource(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.CopyActivity.DeserializeCopyActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.PipelineActivity.DeserializePipelineActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.ForEachActivity.DeserializeForEachActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.PipelineActivity.DeserializePipelineActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineData.DeserializeDataFactoryPipelineData(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.PipelinesRestOperations.Get(String subscriptionId, String resourceGroupName, String factoryName, String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineCollection.Get(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at Azure.ResourceManager.DataFactory.DataFactoryResource.GetDataFactoryPipeline(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at gfs_ta.TestFramework.Connector.DataFactoryConnector.<RunPipelineAsync>d__14.MoveNext() in C:\Users\missb\source\repos\GFS_TA\gfs_ta.TestFramework\Connector\DataFactoryConnector.cs:line 59

**Comment by mikestrach** [comment]
Seems to be the same as #43244

**Comment by EvaRichieChuang** [comment]
Got the same error with latest nuget package ( 1.11.1) and ADF v2
```
   at System.Runtime.CompilerServices.CastHelpers.<IsInstanceOf_NoCacheLookup>g____PInvoke|4_0(Void* __toTypeHnd_native, Int32 __throwCastException_native, ObjectHandleOnStack __obj_native)
   at System.Runtime.CompilerServices.CastHelpers.<IsInstanceOf_NoCacheLookup>g____PInvoke|4_0(Void* __toTypeHnd_native, Int32 __throwCastException_native, ObjectHandleOnStack __obj_native)
   at System.Runtime.CompilerServices.CastHelpers.ChkCastAny_NoCacheLookup(Void* toTypeHnd, Object obj)
   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Deserialize[T](JsonElement json)
   at Azure.Core.Expressions.DataFactory.DataFactoryElementJsonConverter.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.ReadAsObject(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.Converters.CastingConverter`1.Read(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Azure.ResourceManager.DataFactory.Models.WebActivity.DeserializeWebActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.PipelineActivity.DeserializePipelineActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.IfConditionActivity.DeserializeIfConditionActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.Models.PipelineActivity.DeserializePipelineActivity(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineData.DeserializeDataFactoryPipelineData(JsonElement element, ModelReaderWriterOptions options)
   at Azure.ResourceManager.DataFactory.PipelinesRestOperations.Get(String subscriptionId, String resourceGroupName, String factoryName, String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at Azure.ResourceManager.DataFactory.DataFactoryPipelineCollection.Get(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at Azure.ResourceManager.DataFactory.DataFactoryResource.GetDataFactoryPipeline(String pipelineName, String ifNoneMatch, CancellationToken cancellationToken)
   at AzOperationFunction.AzOperation.<Run>d__3.MoveNext() in D:\Backend\CSharp\Applications\Web\AzOperationFunction\AzOperation.cs:line 75
```
