### ISSUE TITLE
ChatCompletion.GetMessageContext() throws an InvalidOperationException during the deserialization of citations

### ISSUE THREAD

**Issue by tcihak-fqa** [Azure/azure-sdk-for-net#47207]
### Library name and version

Azure.AI.OpenAI v2.1.0-beta.2

### Describe the bug

I have a RAG AI application that occasionally throws an exception when calling the ChatCompletion.GetMessageContext() method.
The exception occurs during the deserialization of citations.
More specificially, the completion data contains a citation with a "chunk_id" value that is a number.

### Expected behavior

The chat completion APIs shouldn't return data that cannot be deserialized.

### Actual behavior

Here is the exception:

```
System.InvalidOperationException
  HResult=0x80131509
  Message=The requested operation requires an element of type 'String', but the target element has type 'Number'.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.CheckExpectedType(JsonTokenType expected, JsonTokenType actual)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at System.Text.Json.JsonElement.GetString()
   at Azure.AI.OpenAI.Chat.ChatCitation.DeserializeChatCitation(JsonElement element, ModelReaderWriterOptions options)
   at Azure.AI.OpenAI.Chat.ChatMessageContext.DeserializeChatMessageContext(JsonElement element, ModelReaderWriterOptions options)
   at Azure.AI.OpenAI.Chat.ChatMessageContext.System.ClientModel.Primitives.IPersistableModel<Azure.AI.OpenAI.Chat.ChatMessageContext>.Create(BinaryData data, ModelReaderWriterOptions options)
   at System.ClientModel.Primitives.ModelReaderWriter.Read(BinaryData data, Type returnType, ModelReaderWriterOptions options)
   at Azure.AI.OpenAI.Internal.AdditionalPropertyHelpers.GetAdditionalProperty[T](IDictionary`2 additionalProperties, String key)
   at Azure.AI.OpenAI.Chat.AzureChatExtensions.GetMessageContext(ChatCompletion chatCompletion)
   at FarmQA.AiFunctions.Functions.SupportChatFunction.<SupportChatAsync>d__7.MoveNext() in C:\Repos\FQADevOps\Source\FarmQA.AiFunctions\Functions\SupportChatFunction.cs:line 78
```

Here is the chat completion response data. The second citation has a "chunk_id": value that is a number.

```
{
    "id": "a3bf90ad-a79f-42ff-b2f8-5bf29862e720",
    "model": "gpt-4o-mini",
    "created": 1731937629,
    "object": "extensions.chat.completion",
    "choices": [
        {
            "index": 0,
            "finish_reason": "stop",
            "message": {
                "role": "assistant",
                "content": "My content",
                "end_turn": true,
                "context": {
                    "citations": [
                        {
                            "content": "Citation 1 content ...",
                            "title": "Creating management zones and writing prescriptions",
                            "url": "https://support.farmqa.com/hc/en-us/articles/8722556299533-Creating-management-zones-and-writing-prescriptions",
                            "filepath": null,
                            "chunk_id": "0"
                        },
                        {
                            "content": "Citation 2 content ...",
                            "title": "FarmQA.com",
                            "url": "https://farmqa.com/solutions/imagery",
                            "filepath": null,
                            "chunk_id": 0
                        },
                    ],
                    "intent": "[\"How to obtain satellite images?\", \"Methods to access satellite imagery\", \"Where to find satellite images\"]"
                }
            }
        }
    ],
    "usage": {
        "prompt_tokens": 6495,
        "completion_tokens": 284,
        "total_tokens": 6779
    },
    "system_fingerprint": "fp_04751d0b65"
}
```

### Reproduction Steps

```
                var allMessages = new List<ChatMessage>();
                allMessages.AddRange(chatRequest.UserPrompts.Select(p => ChatMessage.CreateUserMessage(p)));
                if (!string.IsNullOrWhiteSpace(chatRequest.SystemPrompt))
                {
                    allMessages.Add(ChatMessage.CreateSystemMessage(chatRequest.SystemPrompt));
                }

                var completionOptions = GetSupportDocCompletionOptions(); // Code omitted in this example
                var chatCompletion = await chatClient.CompleteChatAsync(allMessages, completionOptions, cancellationToken);
                var result = chatCompletion.Value;
                if (result.FinishReason == ChatFinishReason.Stop && result.Content.Any())
                {
#pragma warning disable AOAI001
                    var chatCitations = new List<ChatCitation>();
                    try
                    {
                        // The following line can throw this exception:
                        // System.InvalidOperationException: 'The requested operation requires an element of type 'String', but the target element has type 'Number'.'
                        // The reason is that the ChatCitation.ChunkId deserialized value is a number.
                        var messageContext = result.GetMessageContext();
                        chatCitations = messageContext?.Citations?.Select((cit, index) =>
                            new ChatCitation
                            {
                                Title = cit.Title,
                                Url = cit.Url,
                                TextToken = $"doc{index + 1}"
                            }).ToList();
                    }
                    catch (Exception ex)
                    {
                        log.LogError(ex, "SupportChatFunction.GetMessageContext.Exception");
                    }
#pragma warning restore AOAI001

                    var response = new ChatResponse
                    {
                        Text = result.Content[0].Text,
                        Citations = chatCitations,
                    };

                    return new OkObjectResult(response);
                }

                return new NoContentResult();
            }
            catch (ClientResultException ex)
            {
                log.LogError(ex, "SupportChatFunction.ClientResultException");
                return new StatusCodeResult(ex.Status);
            }
            catch (HttpRequestException ex)
            {
                log.LogError(ex, "SupportChatFunction.HttpRequestException");
                return new StatusCodeResult((int)ex.StatusCode);
            }
            catch (Exception ex)
            {
                log.LogError(ex, "SupportChatFunction.Exception");
                return new StatusCodeResult(500);
            }
        }

```

### Environment

.NET SDK:
 Version:           9.0.100
 Commit:            59db016f11
 Workload version:  9.0.100-manifests.c6f19616
 MSBuild version:   17.12.7+5b8665660

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22631
 OS Platform: Windows
 RID:         win-x64
 Base Path:   C:\Program Files\dotnet\sdk\9.0.100\

Microsoft Visual Studio Community 2022
Version 17.12.0
VisualStudio.17.Release/17.12.0+35506.116
Microsoft .NET Framework
Version 4.8.09032

**Comment by Riddersholm97** [comment]
Any solution to this problem? 

I get the following exception when calling StreamingChatCompletionUpdate.GetMessageContext()

```
System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
         at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
         at System.Text.Json.JsonElement.EnumerateObject()
         at Azure.AI.OpenAI.Chat.ChatRetrievedDocument.DeserializeChatRetrievedDocument(JsonElement element, ModelReaderWriterOptions options)
         at Azure.AI.OpenAI.Chat.ChatMessageContext.DeserializeChatMessageContext(JsonElement element, ModelReaderWriterOptions options)
         at Azure.AI.OpenAI.Internal.AdditionalPropertyHelpers.GetAdditionalProperty[T](IDictionary`2 additionalProperties, String additionalPropertyKey, Func`3 deserializeFunction)
         at Azure.AI.OpenAI.Internal.AdditionalPropertyHelpers.GetAdditionalPropertyAsChatMessageContext(IDictionary`2 additionalProperties, String additionalPropertyKey)
         at Azure.AI.OpenAI.Chat.AzureChatExtensions.GetMessageContext(StreamingChatCompletionUpdate chatUpdate)
```

**Comment by Macro21** [comment]
Same exception:

`System.InvalidOperationException: The requested operation requires an element of type 'Object', but the target element has type 'Array'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonElement.EnumerateObject()
   at Azure.AI.OpenAI.Chat.ChatRetrievedDocument.DeserializeChatRetrievedDocument(JsonElement element, ModelReaderWriterOptions options)
   at Azure.AI.OpenAI.Chat.ChatMessageContext.DeserializeChatMessageContext(JsonElement element, ModelReaderWriterOptions options)
   at Azure.AI.OpenAI.Internal.AdditionalPropertyHelpers.GetAdditionalProperty[T](IDictionary`2 additionalProperties, String additionalPropertyKey, Func`3 deserializeFunction)
   at Azure.AI.OpenAI.Internal.AdditionalPropertyHelpers.GetAdditionalPropertyAsChatMessageContext(IDictionary`2 additionalProperties, String additionalPropertyKey)
   at Azure.AI.OpenAI.Chat.AzureChatExtensions.GetMessageContext(StreamingChatCompletionUpdate chatUpdate)
   at SemanticKernel.SKAgentChatGroup.GetCitations(StreamingKernelContent streamingKernelContent) `

**Comment by Macro21** [comment]
I’ve created an agent using **Semantic Kernel** that aims to answer user questions by leveraging knowledge from **Azure AI Search**, using the default connector.

The issue only arises when I set the `**OutputContexts**` property to `**AllRetrievedDocuments**`. If I set it to `**Citations**` or leave `OutputContexts` unset, everything works fine. Here's the configuration:

```csharp
var config = new AzureSearchChatDataSource
{
    Endpoint = aiSearchEndpoint,
    IndexName = documentsIndexName,
    Authentication = DataSourceAuthentication.FromSystemManagedIdentity(),
    TopNDocuments = settings?.CurrentValue?.SearchClient?.TopNDocuments ?? 10,
    Strictness = settings?.CurrentValue?.SearchClient?.Strictness ?? 3,
    FieldMappings = fieldMappings,
    VectorizationSource = DataSourceVectorizer.FromDeploymentName(embeddingsDeploymentId),
    Filter = filter,
    AllowPartialResults = true,
    QueryType = "vector_semantic_hybrid",
    SemanticConfiguration = semanticConfiguration, 
    OutputContexts = DataSourceOutputContexts.Citations
};
```

It seems the deserialization expects an object but instead receives an array when using `AllRetrievedDocuments`.

:mag: I’ve found a related issue here:  
https://github.com/Azure/azure-sdk-for-net/issues/46719
