### ISSUE TITLE
[BUG] Exception thrown when the AI streamed response encounter Content filters

### ISSUE THREAD

**Issue by sandrohanea** [Azure/azure-sdk-for-net#47243]
### Library name and version

Azure.AI.Projects 1.0.0-alpha.20241114.1

### Describe the bug

An exception is thrown when the content of the streamed event is deserialized and "content filters" are set.

1. Create a new assistant.
2. Send a message that will be flagged by the RAI checks: (e.g. `I want to kill myself`)
3. Run the Assistant with streaming.

It seems that RunUpdate is deserialized as "ThreadRun" but that fails => it should be a different type for that specific updateKind caused by filtered contents.

### Expected behavior

 Getting the RAI Filtered result in the stream

### Actual behavior

Exception is thrown during deserialization:

### Reproduction Steps

With the steps above, the error is thrown:

```
System.InvalidOperationException: The requested operation requires an element of type 'String', but the target element has type 'Object'.
   at System.Text.Json.ThrowHelper.ThrowJsonElementWrongTypeException(JsonTokenType expectedType, JsonTokenType actualType)
   at System.Text.Json.JsonDocument.GetString(Int32 index, JsonTokenType expectedType)
   at Azure.AI.Projects.ThreadRun.DeserializeThreadRun(JsonElement element, ModelReaderWriterOptions options)
   at Azure.AI.Projects.RunUpdate.DeserializeRunUpdates(JsonElement element, StreamingUpdateReason updateKind, ModelReaderWriterOptions options)
   at Azure.AI.Projects.StreamingUpdate.FromEvent(SseItem`1 sseItem)
   at Azure.AI.Projects.AsyncStreamingUpdateCollection.AsyncStreamingUpdateEnumerator.System.Collections.Generic.IAsyncEnumerator<Azure.AI.Projects.StreamingUpdate>.MoveNextAsync()
   at Azure.AI.Projects.AsyncStreamingUpdateCollection.GetValuesFromPageAsync(ClientResult page)+MoveNext()
   at Azure.AI.Projects.AsyncStreamingUpdateCollection.GetValuesFromPageAsync(ClientResult page)+MoveNext()
   at Azure.AI.Projects.AsyncStreamingUpdateCollection.GetValuesFromPageAsync(ClientResult page)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at System.ClientModel.AsyncCollectionResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at System.ClientModel.AsyncCollectionResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at System.ClientModel.AsyncCollectionResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at System.ClientModel.AsyncCollectionResult`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
```

### Environment

Host:
Version: 9.0.0
Architecture: x64
Commit: 9d5a6a9aa4

**Comment by ShivangiReja** [comment]
Hi @sandrohanea,  Thank you for reporting this issue and providing detailed steps to reproduce it.  

The issue seems to be related to how the [ThreadRun.IncompleteDetails](https://github.com/Azure/azure-rest-api-specs/blob/17ab26e678f06460cd154e2c0cb187aae158f4bf/specification/ai/Azure.AI.Projects/agents/runs/models.tsp#L96) property is defined in the TypeSpec schema. Currently, this property is generated as an extensible enum in the C# SDK based on the TypeSpec definition. However, the service response from the `CreateRun` method returns `ThreadRun.IncompleteDetails` as an object. This mismatch between the schema and the actual service response leads to the deserialization error.

@jhakulin or @dargilco can investigate and address the inconsistency between the TypeSpec schema and the service response?

This issue is not limited to streaming and can also be reproduced with the `CreateRun` method using the below code snippet: 
```csharp
Response<AgentThread> threadResponse = await client.CreateThreadAsync();

 Response<ThreadMessage> messageResponse = await client.CreateMessageAsync(
     thread.Id,
     MessageRole.User,
     "I want to kill myself.");
 ThreadMessage message = messageResponse.Value;

 Response<ThreadRun> runResponse = await client.CreateRunAsync(
     thread.Id,
     agent.Id);
 ThreadRun run = runResponse.Value;

 do
 {
     await Task.Delay(TimeSpan.FromMilliseconds(500));
     runResponse = await client.GetRunAsync(thread.Id, runResponse.Value.Id);
 }
 while (runResponse.Value.Status == RunStatus.Queued
     || runResponse.Value.Status == RunStatus.InProgress);
```

**Comment by ShivangiReja** [comment]
Here’s an alternate approach you can use to make it work:

In the C# SDK, we provide both convenience methods and protocol methods. The issue lies in the convenience method, where we use input and output models. However, you can still use the protocol method without any issues. Protocol methods allow you to retrieve the raw response directly.

Below is a snippet demonstrating how to use the protocol method for the GetRun method:

```csharp
       string status = null;
        do
        {
            await Task.Delay(TimeSpan.FromMilliseconds(500));
            Response getRunResponse = await client.GetRunAsync(thread.Id, runResponse.Value.Id, new RequestContext());
            dynamic response = getRunResponse.Content.ToDynamicFromJson();
            status = response.status;
        }
        while (status == RunStatus.Queued
            || status == RunStatus.InProgress);
```

For more information, please refer to the documentation on [Azure SDK for .NET protocol and convenience methods overview](https://learn.microsoft.com/en-us/dotnet/azure/sdk/protocol-convenience-methods?tabs=protocol-methods%2Csystem-clientmodel).

**Comment by dargilco** [comment]
Closing as this was already fixed.
