### ISSUE TITLE
[QUERY] How to deploy arm template ?

### ISSUE THREAD

**Issue by FisherMS** [Azure/azure-sdk-for-net#47310]
### Library name and version

Azure.ResourceManager.Resources 1.7.0

### Query/Question

source code:
https://github.com/Azure-Samples/azure-samples-net-management/blob/master/samples/resources/deploy-using-arm-template/Program.cs

I use these codes to deploy arm template ,but it's failed.

Response:
```log
Creating a resource group with name: rgrsat521693001f3f3
Created a resource group with name: rgrsat521693001f3f3
Starting a deployment for an Azure App Service: dprsatba1506167e88a
Deleting Resource Group: rgrsat521693001f3f3
Deleted Resource Group: rgrsat521693001f3f3
Azure.RequestFailedException: The request content was invalid and could not be deserialized: 'Error converting value "{
  "$schema": "http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "hostingPlanName": {
      "type": "string",
      "defaultValue": "hprsat76276532deabd"
    },
    "skuName": {
      "type": "string",
      "defaultValue": "B1"
    },
    "skuCapacity": {
      "type": "int",
      "defaultValue": 1
    },
    "webSiteName": {
      "type": "string",
      "defaultValue": "wnrsat37f480969b8fe"
    }
  },
  "resources": [
    {
      "apiVersion": "2015-08-01",
      "name": "[parameters('hostingPlanName')]",
      "type": "Microsoft.Web/serverfarms",
      "location": "[resourceGroup().location]",
      "tags": {
        "displayName": "HostingPlan"
      },
      "sku": {
        "name": "[parameters('skuName')]",
        "capacity": "[parameters('skuCapacity')]"
      },
      "properties": {
        "name": "[parameters('hostingPlanName')]"
      }
    },
    {
      "apiVersion": "2015-08-01",
      "name": "[parameters('webSiteName')]",
      "type": "Microsoft.Web/sites",
      "location": "[resourceGroup().location]",
      "tags": {
        "[concat('hidden-related:', resourceGroup().id, '/providers/Microsoft.Web/serverfarms/', parameters('hostingPlanName'))]": "Resource",
        "displayName": "Website"
      },
      "dependsOn": [
        "[concat('Microsoft.Web/serverfarms/', parameters('hostingPlanName'))]"
      ],
      "properties": {
        "name": "[parameters('webSiteName')]",
        "serverFarmId": "[resourceId('Microsoft.Web/serverfarms', parameters('hostingPlanName'))]"
      },
      "resources": [
        {
          "apiVersion": "2015-08-01",
          "name": "web",
          "type": "config",
          "dependsOn": [
            "[concat('Microsoft.Web/sites/', parameters('webSiteName'))]"
          ],
          "properties": {
            "javaVersion": "1.8",
            "javaContainer": "TOMCAT",
            "javaContainerVersion": "8.0"
          }
        }
      ]
    }
  ]
}" to type 'Azure.Deployments.Core.Definitions.Schema.Template'. Path 'properties.template', line 1, position 3222.'.
Status: 400 (Bad Request)
ErrorCode: InvalidRequestContent

Content:
{"error":{"code":"InvalidRequestContent","message":"The request content was invalid and could not be deserialized: 'Error converting value \"{\r\n  \"$schema\": \"http://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#\",\r\n  \"contentVersion\": \"1.0.0.0\",\r\n  \"parameters\": {\r\n    \"hostingPlanName\": {\r\n      \"type\": \"string\",\r\n      \"defaultValue\": \"hprsat76276532deabd\"\r\n    },\r\n    \"skuName\": {\r\n      \"type\": \"string\",\r\n      \"defaultValue\": \"B1\"\r\n    },\r\n    \"skuCapacity\": {\r\n      \"type\": \"int\",\r\n      \"defaultValue\": 1\r\n    },\r\n    \"webSiteName\": {\r\n      \"type\": \"string\",\r\n      \"defaultValue\": \"wnrsat37f480969b8fe\"\r\n    }\r\n  },\r\n  \"resources\": [\r\n    {\r\n      \"apiVersion\": \"2015-08-01\",\r\n      \"name\": \"[parameters('hostingPlanName')]\",\r\n      \"type\": \"Microsoft.Web/serverfarms\",\r\n      \"location\": \"[resourceGroup().location]\",\r\n      \"tags\": {\r\n        \"displayName\": \"HostingPlan\"\r\n      },\r\n      \"sku\": {\r\n        \"name\": \"[parameters('skuName')]\",\r\n        \"capacity\": \"[parameters('skuCapacity')]\"\r\n      },\r\n      \"properties\": {\r\n        \"name\": \"[parameters('hostingPlanName')]\"\r\n      }\r\n    },\r\n    {\r\n      \"apiVersion\": \"2015-08-01\",\r\n      \"name\": \"[parameters('webSiteName')]\",\r\n      \"type\": \"Microsoft.Web/sites\",\r\n      \"location\": \"[resourceGroup().location]\",\r\n      \"tags\": {\r\n        \"[concat('hidden-related:', resourceGroup().id, '/providers/Microsoft.Web/serverfarms/', parameters('hostingPlanName'))]\": \"Resource\",\r\n        \"displayName\": \"Website\"\r\n      },\r\n      \"dependsOn\": [\r\n        \"[concat('Microsoft.Web/serverfarms/', parameters('hostingPlanName'))]\"\r\n      ],\r\n      \"properties\": {\r\n        \"name\": \"[parameters('webSiteName')]\",\r\n        \"serverFarmId\": \"[resourceId('Microsoft.Web/serverfarms', parameters('hostingPlanName'))]\"\r\n      },\r\n      \"resources\": [\r\n        {\r\n          \"apiVersion\": \"2015-08-01\",\r\n          \"name\": \"web\",\r\n          \"type\": \"config\",\r\n          \"dependsOn\": [\r\n            \"[concat('Microsoft.Web/sites/', parameters('webSiteName'))]\"\r\n          ],\r\n          \"properties\": {\r\n            \"javaVersion\": \"1.8\",\r\n            \"javaContainer\": \"TOMCAT\",\r\n            \"javaContainerVersion\": \"8.0\"\r\n          }\r\n        }\r\n      ]\r\n    }\r\n  ]\r\n}\" to type 'Azure.Deployments.Core.Definitions.Schema.Template'. Path 'properties.template', line 1, position 3222.'."}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
x-ms-failure-cause: REDACTED
x-ms-ratelimit-remaining-subscription-writes: REDACTED
x-ms-ratelimit-remaining-subscription-global-writes: REDACTED
x-ms-request-id: d27c93f1-0407-4545-a357-398b91e77c1b
x-ms-correlation-request-id: REDACTED
x-ms-routing-request-id: REDACTED
Strict-Transport-Security: REDACTED
X-Content-Type-Options: REDACTED
X-Cache: REDACTED
X-MSEdge-Ref: REDACTED
Date: Thu, 21 Nov 2024 01:31:44 GMT
Content-Length: 2665
Content-Type: application/json; charset=utf-8
Expires: -1

   at Azure.ResourceManager.Resources.DeploymentsRestOperations.CreateOrUpdateAtScopeAsync(String scope, String deploymentName, ArmDeploymentContent content, CancellationToken cancellationToken)
   at Azure.ResourceManager.Resources.ArmDeploymentCollection.CreateOrUpdateAsync(WaitUntil waitUntil, String deploymentName, ArmDeploymentContent content, CancellationToken cancellationToken)
   at DeployUsingARMTemplate.Program.RunSample(ArmClient client) in R:\azure-samples-net-management\samples\resources\deploy-using-arm-template\Program.cs:line 52
   at DeployUsingARMTemplate.Program.Main(String[] args) in R:\azure-samples-net-management\samples\resources\deploy-using-arm-template\Program.cs:line 86
```

### Environment

netcore 3.1 / VS2019
netcore 8 /VS2022

**Comment by FisherMS** [comment]
Thank you guys, I solve it. just use BinaryData.FromString(File.ReadAllText(template.json)) is ok.
