### ISSUE TITLE
[BUG] ArgumentNullException when parsing RequestFailedException while resolving AsyncPageable for RuleProperties on a Subscription

### ISSUE THREAD

**Issue by joshnorwich** [Azure/azure-sdk-for-net#47517]
### Library name and version

Azure.ServiceBus.Messaging 7.18.2

### Describe the bug

One of our Azure AppServices, when updated to NET8, cannot enumerate the AsyncPageable collection of RuleProperties for this specific service's subscription. Similar updated services with similar subscriptions and CustomRules entries are not impacted. 

Deleting the existing CustomRule entries, replacing them with the default passthrough rule ($DefaultRule 1=1), and trying instead to have the code check the rules of a newly created subscription instead of the one that appears to be problematic all failed to resolve the issue. It seems that this upgraded service cannot manage any of the rules in its subscriptions due to an unknowable ServiceRequestException that is being obscured by the ArgumentNullException.

### Expected behavior

I expect this shared library we use across the team to be able to fetch the AsyncPageable collection of Rules off this service's subscription like it is able to do for several other services that have been successfully upgraded to NET8 and deployed. Barring that I'd expect the SDK to be able to successfully parse the underlying RequestFailedException using ServiceBusRequestFailedDetailsParser.TryParse into something consumable/readable rather than the ArgumentNullException I am receiving.

### Actual behavior

When attempting to enumerate the AsyncPageable collection of RuleProperties from the ServiceBusAdministrationClient.GetRulesAsync method, an underlying service request is encountering a request failure but the SDK is unable to convert some missing piece of BinaryData into a string when parsing the RequestFailedException. So rather than any insight into why this particular service when upgraded to .net8 cannot manage it's subscription rules I just receive the following ArgumentNullException from within the Azure.Core.Pipeline library.

StackTrace of ArgumentNullException
`ERROR: Value cannot be null. (Parameter 'bytes')
   at System.ArgumentNullException.Throw(String paramName)
   at System.Text.Encoding.GetString(Byte* bytes, Int32 byteCount)
   at System.BinaryData.ToString()
   at Azure.Core.Pipeline.ServiceBusRequestFailedDetailsParser.TryParse(Response response, ResponseError& error, IDictionary`2& data)
   at Azure.RequestFailedException.CreateExceptionDetails(Response response, RequestFailedDetailsParser parser)
   at Azure.RequestFailedException..ctor(Response response, Exception innerException, RequestFailedDetailsParser detailsParser)
   at Azure.RequestFailedException..ctor(Response response, Exception innerException)
   at Azure.RequestFailedException..ctor(Response response)
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.ThrowIfRequestFailed(Request request, Response response)
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.SendHttpRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.GetEntityAsync(String entityPath, String query, Boolean enrich, CancellationToken cancellationToken)
   at Azure.Messaging.ServiceBus.Administration.HttpRequestAndResponse.GetEntitiesPageAsync[T](String path, String nextSkip, Func`2 parseFunction, CancellationToken cancellationToken)
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+MoveNext()
   at Azure.Core.PageResponseEnumerator.FuncAsyncPageable`1.AsPages(String continuationToken, Nullable`1 pageSizeHint)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.AsyncPageable`1.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Neo.Events.AzureServiceBus.WrapperManagementClient.TryCheckRuleAsync(String topic, String subscription, String rule, String condition, CancellationToken token)`

### Reproduction Steps

1. Use this method to check the rules of any of the 5 subscriptions for the problematic AppService

`private async Task TryCheckRuleAsync(string topic, string subscription, string rule, string condition, CancellationToken token) {
    logger.Debug($"{topic}:{subscription} Fetching rules"); //THIS IS LOGGED
    AsyncPageable<RuleProperties> rules = managementClient.GetRulesAsync(topic, subscription, token);
    logger.Debug($"{topic}:{subscription} Successfully Fetched Rules");  //THIS IS LOGGED

    IAsyncEnumerator<RuleProperties> enumerator = rules.GetAsyncEnumerator(token);
    try {
        logger.Debug($"{topic}:{subscription} Iterating over Rules");  //THIS IS LOGGED
        while (await enumerator.MoveNextAsync()) {
            RuleProperties ruleProperty = enumerator.Current;
            logger.Debug($"{topic}:{subscription} Checking rule <{ruleProperty.Name}> against <{rule}>/<{ruleNameBis}>"); // // THESE LOG LINES ARE NEVER PRODUCED
            logger.Debug($"{topic}:{subscription} Filter is {ruleProperty.Filter}"); // THESE LOG LINES ARE NEVER PRODUCED
        }
    } catch (ServiceBusException sbex) {
        logger.Exception(sbex, $"{topic}:{subscription} ServiceBus Exception detected. {sbex.Message} - {sbex.InnerException?.Message}"); // NO ServiceBusException IS EVER CAUGHT
        throw;
    } catch (Exception ex) {
        logger.Exception(ex, $"{topic}:{subscription} Exception detected. {ex.Message} - {ex.InnerException?.Message}"); // ONLY THIS EXCEPTION GETS CAUGHT
        throw;
    } finally {
        await enumerator.DisposeAsync();
    }`

### Environment

Azure AppService

**Comment by jsquire** [comment]
Hi @joshnorwich.   Thanks for reaching out and we regret that you're experiencing difficulties.   This looks to be the first request to the Service Bus endpoint failing due to a service-generated error.  That takes place when the first page is requested via enumeration.   Unfortunately, there's not enough context to determine the root cause.    While we attempt to reproduce this, it would be helpful if you would be so kind as to [capture Azure SDK logs](https://learn.microsoft.com/dotnet/azure/sdk/logging) for the scenario, which will allow us to see the raw HTTP traffic.

> catch (ServiceBusException sbex) {
    logger.Exception(sbex, $"{topic}:{subscription} ServiceBus Exception detected. {sbex.Message} - {sbex.InnerException?.Message}"); // NO ServiceBusException IS EVER CAUGHT

This is expected, as `ServiceBusException` wraps raw AMQP error codes.   The administration client is HTTP-based and will follow Azure.Core semantics for responses and errors, as described [here](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/samples/Response.md#handling-exceptions).

**Comment by joshnorwich** [comment]
Hello @jsquire , Do I need to accomplish this via the OpenTelemetry nuget and tying the appservice slot to our Application Insights instance? I tried the example in your "capture SDK logs" link under the heading "Log HTTP request and response bodies" where I set IsContentLoggingEnabled to true on the client options for the ServiceBusAdministrationClient and set both "Azure.Core" and "Azure.Messaging.ServiceBus" to Debug in appsettings but I do not see any additional logs in the slot's logfile.

**Comment by jsquire** [comment]
@joshnorwich :  ETW logs captured by the `AzureEventSourceListener` do not automatically flow into AppInsights or other stores.   You would have to forward them there in the delegate manually or by using something like the [AzureEventSourceLogForwarder](https://learn.microsoft.com//dotnet/api/microsoft.extensions.azure.azureeventsourcelogforwarder?view=azure-dotnet) from the `Microsoft.Extensions.Azure` package.  Open Telemetry is different than logs; there is no way that I'm aware of to push ETW logs to Otel automatically, though @TimothyMothra may have thoughts.

**Comment by joshnorwich** [comment]
Alright @jsquire  thank you. I will have to wrestle with a couple of our company level libraries to get the logs forwarded. My service bus client is in a "Contoso"BusManagement package and all my logging bootstrapping is in a "Contoso"Logger package so it may take a little bit to put together all the alpha packaged nugets I'll need but I promise I will discover the root service request causing this edge case after the holiday break.

**Comment by joshnorwich** [comment]
@jsquire Apologies for the delay. After many different attempts I've captured the raw HTTP request and response occurring to my service bus endpoint that causes this ArgumentNullException:

Request:
`{"EventName":"Request","EventId":1,"ActivityId":"00000000-0000-0000-0000-000000000000","RelatedActivityId":"00000000-0000-0000-0000-000000000000","Payload":["efb4be08-436b-4a2a-a4a0-e6ae72c6b185","GET","https://<SERVICE BUS ENDPOINT>/<TOPIC>/Subscriptions/<MY APPS SUBSCRIPTION>/rules?api-version=2021-05&enrich=REDACTED&$skip=REDACTED&$top=REDACTED","Authorization:REDACTED\r\nx-ms-client-request-id:efb4be08-436b-4a2a-a4a0-e6ae72c6b185\r\nx-ms-return-client-request-id:true\r\nUser-Agent:azsdk-net-Messaging.ServiceBus/7.18.1 (.NET 8.0.8; Microsoft Windows 10.0.20348)\r\n","Azure.Messaging.ServiceBus"],"PayloadNames":["requestId","method","uri","headers","clientAssembly"],"EventSource":{"Name":"Azure-Core","Guid":"44cbc7c6-6776-5f3c-36c1-75cd3ef19ea9","Settings":8,"ConstructionException":null},"Keywords":263882790666240,"Opcode":0,"Task":65533,"Tags":0,"Message":"Request [{0}] {1} {2}\r\n{3}client assembly: {4}","Channel":0,"Version":0,"Level":4,"OSThreadId":20640,"TimeStamp":"2025-01-28T03:54:15.3035829Z"}

Request [efb4be08-436b-4a2a-a4a0-e6ae72c6b185] GET https://<SERVICE BUS ENDPOINT>/<TOPIC>/Subscriptions/<MY APPS SUBSCRIPTION>/rules?api-version=2021-05&enrich=REDACTED&$skip=REDACTED&$top=REDACTED
Authorization:REDACTED
x-ms-client-request-id:efb4be08-436b-4a2a-a4a0-e6ae72c6b185
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Messaging.ServiceBus/7.18.1 (.NET 8.0.8; Microsoft Windows 10.0.20348)
client assembly: Azure.Messaging.ServiceBus`

Response:
`{"EventName":"ErrorResponse","EventId":8,"ActivityId":"00000000-0000-0000-0000-000000000000","RelatedActivityId":"00000000-0000-0000-0000-000000000000","Payload":["0e248658-2fd5-491a-a121-459f3f25c962",401,"SubCode=40100: Unauthorized : Unauthorized access for 'EnumerateRules' operation on endpoint 'sb://<SERVICE BUS ENDPOINT/<TOPIC>/Subscriptions/<MY APPS SUBSCRIPTION>/rules?api-version=2021-05&enrich=False&$skip=0&$top=100'. Tracking Id: 81f8b0ce-7935-4813-b535-f03c43495b87_G57","ETag:637551999310070000\r\nServer:Microsoft-HTTPAPI/2.0\r\nStrict-Transport-Security:REDACTED\r\nDate:Tue, 28 Jan 2025 03:54:14 GMT\r\nContent-Length:0\r\n",0.8974952],"PayloadNames":["requestId","status","reasonPhrase","headers","seconds"],"EventSource":{"Name":"Azure-Core","Guid":"44cbc7c6-6776-5f3c-36c1-75cd3ef19ea9","Settings":8,"ConstructionException":null},"Keywords":263882790666240,"Opcode":0,"Task":65526,"Tags":0,"Message":"Error response [{0}] {1} {2} ({4:00.0}s)\r\n{3}","Channel":0,"Version":0,"Level":3,"OSThreadId":15024,"TimeStamp":"2025-01-28T03:54:15.3737007Z"}

Error response [0e248658-2fd5-491a-a121-459f3f25c962] 401 SubCode=40100: Unauthorized : Unauthorized access for 'EnumerateRules' operation on endpoint 'sb://<SERVICE BUS ENDPOINT/<TOPIC>/Subscriptions/<MY APPS SUBSCRIPTION>/rules?api-version=2021-05&enrich=False&$skip=0&$top=100'. Tracking Id: 81f8b0ce-7935-4813-b535-f03c43495b87_G57 (00.9s)
ETag:637551999310070000
Server:Microsoft-HTTPAPI/2.0
Strict-Transport-Security:REDACTED
Date:Tue, 28 Jan 2025 03:54:14 GMT
Content-Length:0
`

I can see from the http error that my app lacks EnumerateRules access which gives me something to actually investigate thank goodness.

I suppose it is the fact that the error response has Content-Length of 0 that is throwing the Exception handling inside your Service Bus SDK for a loop and producing the ArgumentNullException for param 'bytes'?

**Comment by joshnorwich** [comment]
The issue with my service directly seems to be that I am connecting to the SB endpoint with a connection string without a Manage SAS policy, only Send and Listen. Is this still the case as described in https://github.com/Azure/azure-service-bus/issues/462 ?

**Comment by jsquire** [comment]
Thanks, @joshnorwich.   That capture is exactly what we needed.

> I suppose it is the fact that the error response has Content-Length of 0 that is throwing the Exception handling inside your Service Bus SDK for a loop and producing the ArgumentNullException for param 'bytes'?

Yes, that would do it.  I'm not quite sure why we're attempting to access the body for a 401, but I suspect it has to do with the old Atom service not following Azure REST patterns.   We'll dig into this.

> The issue with my service directly seems to be that I am connecting to the SB endpoint with a connection string without a Manage SAS policy, only Send and Listen. Is this still the case as described in https://github.com/Azure/azure-service-bus/issues/462 ?

Yes; the service requires any interactions with the administration service to have manage permissions.

**Comment by jsquire** [comment]
Confirming that I was able to reproduce this, and it does root cause to there being no content body present for 401 response coming from the Service Bus administration service.   Specifically, this [catch block](https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/servicebus/Azure.Messaging.ServiceBus/src/Administration/ServiceBusRequestFailedDetailsParser.cs#L40) needs an additional check to guard against empty content.  

We'll get this fixed up.

**Comment by jsquire** [comment]
fixed by #48156
