### ISSUE TITLE
[BUG] Azure.AI.DocumentIntelligence: Deserialize ClassifyDocumentOptions, Erroring out on 'Azure.AI.DocumentIntelligence.ClassifierDocumentTypeDetails'

### ISSUE THREAD

**Issue by jaliyaudagedara** [Azure/azure-sdk-for-net#47610]
### Library name and version

Azure.AI.DocumentIntelligence 1.0.0

### Describe the bug

Consider the below example:
```csharp
using Azure.AI.DocumentIntelligence;
using System.Text.Json;

Dictionary<string, ClassifierDocumentTypeDetails> documentTypes = new()
{
    { "Document1", new(new BlobFileListContentSource(new Uri("https://www.microsoft.com"), "fileList1")) },
    { "Document2", new(new BlobFileListContentSource(new Uri("https://www.microsoft.com"), "fileList2")) }
};

BuildClassifierOptions buildClassifierOptions = new("someClassifierId", documentTypes);

string json = JsonSerializer.Serialize(buildClassifierOptions, new JsonSerializerOptions { WriteIndented = true });
Console.WriteLine(json);
// {
//   "ClassifierId": "someClassifierId",
//   "Description": null,
//   "BaseClassifierId": null,
//   "DocumentTypes": {
//     "Document1": {
//       "BlobSource": null,
//       "BlobFileListSource": {
//         "ContainerUri": "https://www.microsoft.com",
//         "FileList": "fileList1"
//       },
//       "SourceKind": null
//     },
//     "Document2": {
//       "BlobSource": null,
//       "BlobFileListSource": {
//         "ContainerUri": "https://www.microsoft.com",
//         "FileList": "fileList2"
//       },
//       "SourceKind": null
//     }
//   },
//   "AllowOverwrite": null
// }

buildClassifierOptions = JsonSerializer.Deserialize<BuildClassifierOptions>(json, new JsonSerializerOptions
{
    PropertyNameCaseInsensitive = true
});
```
This is erroring out on `Deserialize`;
```
Unhandled exception. System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Azure.AI.DocumentIntelligence.ClassifierDocumentTypeDetails'. Path: $.DocumentTypes.Document1 | LineNumber: 5 | BytePositionInLine: 18.
 ---> System.NotSupportedException: Deserialization of types without a parameterless constructor, a singular parameterized constructor, or a parameterized constructor annotated with 'JsonConstructorAttribute' is not supported. Type 'Azure.AI.DocumentIntelligence.ClassifierDocumentTypeDetails'.
   --- End of inner exception stack trace ---
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(ReadStack& state, Utf8JsonReader& reader, Exception innerException)
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException_DeserializeNoConstructor(JsonTypeInfo typeInfo, Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonDictionaryConverter`3.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, TDictionary& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.TryRead[TArg](ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo, TArg& arg)
   at System.Text.Json.Serialization.Converters.SmallObjectWithParameterizedConstructorConverter`5.ReadAndCacheConstructorArgument(ReadStack& state, Utf8JsonReader& reader, JsonParameterInfo jsonParameterInfo)
   at System.Text.Json.Serialization.Converters.ObjectWithParameterizedConstructorConverter`1.OnTryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value)
   at System.Text.Json.Serialization.JsonConverter`1.TryRead(Utf8JsonReader& reader, Type typeToConvert, JsonSerializerOptions options, ReadStack& state, T& value, Boolean& isPopulatedValue)
   at System.Text.Json.Serialization.JsonConverter`1.ReadCore(Utf8JsonReader& reader, T& value, JsonSerializerOptions options, ReadStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Deserialize(Utf8JsonReader& reader, ReadStack& state)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 utf8Json, JsonTypeInfo`1 jsonTypeInfo, Nullable`1 actualByteCount)
   at System.Text.Json.JsonSerializer.ReadFromSpan[TValue](ReadOnlySpan`1 json, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Deserialize[TValue](String json, JsonSerializerOptions options)
   at Program.<Main>$(String[] args) in C:\Users\Jaliya\Desktop\ConsoleApp2\ConsoleApp2\Program.cs:line 16
```

### Expected behavior

string is correctly deserialized to given type.

### Actual behavior

Deserialization is erroring out.

### Reproduction Steps

Given above

### Environment

dotnet: 9.0

**Comment by jaliyaudagedara** [comment]
@kinelski, saw this:
https://github.com/Azure/azure-sdk-for-net/blob/01f732ec4b7ba80e792f43c14fb17e1329aa7961/sdk/documentintelligence/Azure.AI.DocumentIntelligence/src/Generated/ClassifierDocumentTypeDetails.Serialization.cs#L16

There we have `DeserializeClassifierDocumentTypeDetails`.

**Comment by kinelski** [comment]
@jaliyaudagedara,

When serializing/deserializing .NET SDK models, you must use our `JsonModelConverter` ([explained here](https://github.com/Azure/azure-sdk-for-net/blob/80b5a9cf9eaaf1a889250e9d927d9f8ced5bff3b/sdk/core/System.ClientModel/samples/ModelReaderWriter.md#read-and-write-with-systemtextjson)):
```csharp
JsonSerializerOptions options = new JsonSerializerOptions()
{
    Converters = { new JsonModelConverter() }
};

InputModel model = new InputModel();
string data = JsonSerializer.Serialize(model, options);
```
This will fix the issue you're seeing with `ClassifierDocumentTypeDetails`.

That said, please be aware that models `AnalyzeBatchDocumentsOptions`, `AnalyzeDocumentOptions`, and `ClassifyDocumentOptions` currently have a bug that prevents some of their properties from being serialized (https://github.com/Azure/azure-sdk-for-net/issues/47612). It shouldn't affect you if you're only working with `BuildClassifierOptions`.
