### ISSUE TITLE
NullReferenceException in ExpandableStringEnum.Value setter

### ISSUE THREAD

**Issue by TimLovellSmith** [Azure/azure-sdk-for-net#4804]
```
[Deployment: isf2, Id: 961] GC: Error encountered while deleting resource: 961/iaasruntime/:NSG:wus2_961_bb7ecb4c1f5d402bb89a2219f9322b61
System.NullReferenceException: Object reference not set to an instance of an object.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ExpandableStringEnum`1.set_Value(String value)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ExpandableStringEnum`1.Parse(String value)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.ExpandableStringEnumConverter`1.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(IList list, JsonReader reader, JsonArrayContract contract, JsonProperty containerProperty, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.Linq.JToken.ToObject(Type objectType, JsonSerializer jsonSerializer)
   at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Microsoft.Rest.Serialization.SafeJsonConvert.DeserializeObject[T](String json, JsonSerializerSettings settings)
   at Microsoft.Azure.Management.Network.Fluent.NetworkSecurityGroupsOperations.<GetWithHttpMessagesAsync>d__6.MoveNext()
```

**Comment by TimLovellSmith** [comment]
Sorry admins, I put this in the wrong repo didn't I! - could someone please move this to Azure-libraries-for-net? Or I can reopen it if you can't move it.

**Comment by TimLovellSmith** [comment]
Looks like either there needs to be a null check for value in 'value.ToLower()' here, or further up the stack..

```
  public string Value

        {

            get { return value; }

            private set

            {

                this.value = value;

                values[value.ToLower()] = (T)this;

            }

        }
```

**Comment by shahabhijeet** [comment]
@TimLovellSmith please open in the right repo.
Closing.
