### ISSUE TITLE
BackupProtectionContainers.List results in Exception

### ISSUE THREAD

**Issue by thepenguinmaster** [Azure/azure-sdk-for-net#4806]
Running the following code to list vault containers results in an exception. 
`

        public async Task deleteTest(string resourceGroupName)
        {
            try
            {
                var creds = new ResourceManagerCredential(subDetails);
                RecoveryServicesBackupClient _recoveryBackupClient = new RecoveryServicesBackupClient(creds)
                {
                    SubscriptionId = subDetails.SubscriptionId
                };
                var vaults = await _recoveryClient.Vaults.ListByResourceGroupAsync(resourceGroupName);
                var tasks = new List<Task>();
                foreach (var vault in vaults)
                {
                    var cont = _recoveryBackupClient.BackupProtectionContainers.List(vault.Name, resourceGroupName);
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.ToString());
            }
        }`

The vault exists as well as the resource group. 
The error returned is always the same:
`

Microsoft.Rest.Azure.CloudException: Input provided for the call is invalid
Please check the required inputs
   at Microsoft.Azure.Management.RecoveryServices.Backup.BackupProtectionContainersOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.RecoveryServices.Backup.BackupProtectionContainersOperationsExtensions.<ListAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.RecoveryServices.Backup.BackupProtectionContainersOperationsExtensions.List(IBackupProtectionContainersOperations operations, String vaultName, String resourceGroupName, ODataQuery1 odataQuery)
   at ArmAutoDeploy.Sandbox.Vault.VaultSandbox.deleteTest(String resourceGroupName) in D:\...\AzureTest.cs:line 136`

Only two parameters are required and this feels like it might be a bug of some kind. My objective here is to delete a vault with any number of resources with the .NET API.

**Comment by jsquire** [comment]
Closing this out as there has been no recent engagement.  Please feel free to reopen or file a new issue if this remains a problem with the current version of the library.
