### ISSUE TITLE
NotFound Error 

### ISSUE THREAD

**Issue by josher565** [Azure/azure-sdk-for-net#4917]
Hi Folks, I'm daring to be wrong here. I suspect I'm about to make a fool of myself however..

I'm using 3.2.0 of Microsoft.Azure.CognitiveServices.Vision.ComputerVision which I believe is the latest version hosted on Nuget.

This error was thrown from this [sample]( https://github.com/Microsoft/Cognitive-Vision-Windows.git )

```
Microsoft.Azure.CognitiveServices.Vision.ComputerVision.Models.ComputerVisionErrorException: Operation returned an invalid status code 'NotFound'
   at Microsoft.Azure.CognitiveServices.Vision.ComputerVision.ComputerVisionClient.<AnalyzeImageWithHttpMessagesAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.CognitiveServices.Vision.ComputerVision.ComputerVisionClientExtensions.<AnalyzeImageAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
```

I have my own tester code that throws the [same error with the same location URI and subscription keys]( https://github.com/josher565/CognitiveOcr)

Could someone drop me a clue or tell me if I have something real? Thank you for reading.

**Comment by josher565** [comment]
So, I changed direction with my test code and created a new Computer Vision account on eastus. Now, if I call it with keys valid to that service, I don't get "Not Found". However, if I loop until I get a reply, it never finishes. The API test page says that I should wait up to a minute for a result. Its much longer than a minute for a result. https://eastus.dev.cognitive.microsoft.com/docs/services/5adf991815e1060e6355ad44/operations/587f2c6a154055056008f200

Maybe I'm calling the wrong result method?
https://github.com/josher565/CognitiveOcr

Anything would be appreciated.

**Comment by josher565** [comment]
yup.. I'm learning things. The issue is on my side rather than yours. But you guys know that right ;)

thanks for letting me bump into things
