### ISSUE TITLE
AzureServiceTokenProvider not respecting az login identity

### ISSUE THREAD

**Issue by MaxWilson** [Azure/azure-sdk-for-net#4935]
[Also filed here: https://github.com/Azure/azure-libraries-for-net/issues/510]

**Issue:** Domain-joined identity appears to override logged in identity. AzureServiceTokenProvider.<GetAccessTokenAsyncImpl>d__14.MoveNext() incorrectly throws exception (only) when run from domain-joined machine.

**Known workarounds:** none except using a non-domain-joined dev machine.

**Version:** Microsoft.Azure.Services.AppAuthentication, Version=1.0.3.0

**Minimal Repro:** 

Set up an Azure KeyVault that you have access to under one identity. E.g. WilsonData, accessible by wilson.max@gmail.com.

On a machine where your domain-joined identity is different (e.g. maxw@microsoft.com), run "az login" to log in as non-domain identity (wilson.max@gmail.com) and run the following code:

```
            var tok = new AzureServiceTokenProvider();
            var kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(tok.KeyVaultTokenCallback));
            var kvUrl = "https://wilsondata.vault.azure.net/";
            var dbUrl = kv.GetSecretAsync(kvUrl, "DB-url").Result;
            Console.WriteLine(dbUrl.Value);
```

**Expected behavior:** should authenticate to KeyVault and print secret value.

**Actual behavior:** "AzureServiceTokenProviderException... Access token could not be acquired." (Note: works fine from non-domain-joined machine.)

**Exception details:**

```
Unhandled Exception: System.AggregateException: One or more errors occurred. ---> Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: RunAs=App;AppId=797be866-267a-437a-b711-845ad3644443;TenantId=72f988bf-86f1-41af-91ab-2d7cd011db47;CertificateThumbprint=EB95D82AE9E73AEFD0BFA36707E895D0F64653F8;CertificateStoreLocation=LocalMachine, Resource: https://vault.azure.net, Authority: https://login.windows.net/4510468d-3790-4a1a-8209-84281b2d1596. Exception Message: Tried 1 certificate(s). Access token could not be acquired.
Exception for cert #1 with thumbprint EB95D82AE9E73AEFD0BFA36707E895D0F64653F8: AADSTS700016: Application with identifier '797be866-267a-437a-b711-845ad3644443' was not found in the directory '4510468d-3790-4a1a-8209-84281b2d1596'. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You may have sent your authentication request to the wrong tenant
Trace ID: c5f80665-5830-4f6e-9172-6e8ff5955d00
Correlation ID: 6637bce1-9ec3-48e1-92d3-c07df3ab7e33
Timestamp: 2018-10-26 18:33:57Z
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAccessTokenAsyncImpl>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.<PostAuthenticate>d__11.MoveNext()
```

I don't recognize most of the values in the above exception message but the tenantId "72f988bf-86f1-41af-91ab-2d7cd011db47" is for the Microsoft tenant, which wilson.max@gmail.com does not have access to. AzureServiceTokenProvider shouldn't be trying to use that tenant at runtime.

**Additional info:** output from az account get-access-token is as follows:

```
D:\code\WilsonData\ConsoleApp1\bin\Debug>az account get-access-token
{
  "accessToken": "eyJ0...6lGsg",
  "expiresOn": "2018-10-26 12:25:42.082471",
  "subscription": "2f4e9444-9448-4618-b9e4-4d41ce647375",
  "tenant": "4510468d-3790-4a1a-8209-84281b2d1596",
  "tokenType": "Bearer"
}
```

**Comment by MaxWilson** [comment]
This turns out to have been user error, nothing to do with domain joining or az login after all. The machine which was erring had an environment variable set (AzureServicesAuthConnectionString) unbeknownst to me, perhaps left over from a tutorial in the past. Deleting this environment variable resolved my issue.
