### ISSUE TITLE
Strong name validation failed

### ISSUE THREAD

**Issue by oflipman** [Azure/azure-sdk-for-net#5038]
Hi,
I followed the instructions in the documentation.
I used this command in admin Developer prompt: "Sn.exe -Vr *,31bf3856ad364e35".
And i got this response: "Verification entry added for assembly '*,31bf3856ad364e35'"
I still get this error when I try to rebuild the project:

Severity	Code	Description	Project	File	Line	Suppression State
Error	MSB4018	The "PostBuildTask" task failed unexpectedly.
System.IO.FileLoadException: Could not load file or assembly 'Microsoft.Azure.Management.Kusto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'Microsoft.Azure.Management.Kusto, Version=1.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at Microsoft.Azure.Sdk.Build.Tasks.BuildStages.PostBuildTask.GetApiMapUsingReflection(String assemblyFullPath)
   at Microsoft.Azure.Sdk.Build.Tasks.BuildStages.PostBuildTask.GetApiMap(String assemblyPath)
   at Microsoft.Azure.Sdk.Build.Tasks.BuildStages.PostBuildTask.GetApiMapFromProject()
   at Microsoft.Azure.Sdk.Build.Tasks.BuildStages.PostBuildTask.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__26.MoveNext()
Microsoft.Azure.Management.Kusto	C:\Git\Clients\azure-sdk-for-net\tools\SdkBuildTools\targets\ideCmd.targets	16	

I also tried to execute the Sn -vr with  the 'Microsoft.Azure.Management.Kusto.dll, and still got the same error.

Am I doing something wrong?

**Comment by shahabhijeet** [comment]
@oflipman can you point me to your fork/branch where I can reproduce this error.

**Comment by oflipman** [comment]
We managed to make it work.
It was a problem on our side, I did not build the project correctly
