### ISSUE TITLE
WebSiteManagementClient.Certificates.List() crashes on deserialization

### ISSUE THREAD

**Issue by Fraaankes** [Azure/azure-sdk-for-net#5122]
Hey
When trying to get the list of certificates available to a webapp, im getting the following exception:
```
Microsoft.Rest.SerializationException
  HResult=0x80131500
  Message=Unable to deserialize the response.
  Source=Microsoft.Azure.Management.Websites
  StackTrace:
   at Microsoft.Azure.Management.WebSites.CertificatesOperations.<ListWithHttpMessagesAsync>d__5.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.WebSites.CertificatesOperationsExtensions.<ListAsync>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at UpdateAllWebAppPfxs.Program.<Main>d__0.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at UpdateAllWebAppPfxs.Program.<Main>(String[] args)

Inner Exception 1:
JsonSerializationException: Cannot deserialize the current JSON array (e.g. [1,2,3]) into type 'Microsoft.Azure.Management.WebSites.Models.Page`1[Microsoft.Azure.Management.WebSites.Models.Certificate]' because the type requires a JSON object (e.g. {"name":"value"}) to deserialize correctly.
To fix this error either change the JSON to a JSON object (e.g. {"name":"value"}) or change the deserialized type to an array or a type that implements a collection interface (e.g. ICollection, IList) like List<T> that can be deserialized from a JSON array. JsonArrayAttribute can also be added to the type to force it to deserialize from a JSON array.
Path '', line 1, position 1.

```
Looking at fiddler i can see the response from `https://management.azure.com/subscriptions/<subscriptionId>/providers/Microsoft.Web/certificates?api-version=2018-02-01 ` is of the form `[{"id": ...}]` and not `{ "value": [ .. ] }` as is expected in the Page<T> model.
I dont know if its the API or the SDK model that is in the wrong here ?

**Comment by AlexGhiondea** [comment]
@Fraaankes please let us know if this is still an issue.
