### ISSUE TITLE
[BUG] Microsoft.Azure.Services.AppAuthentication.TokenResponse. Unexpected end of file. Following elements are not closed: root

### ISSUE THREAD

**Issue by MarcoK80** [Azure/azure-sdk-for-net#5338]
When using Microsoft.Azure.Services.AppAuthentication 1.0.3 on Azure Devops Build agents (self hosted) with Azure CLI task we sporadically observe that no Token was returned or a cutted Token gets returned.

Error Message:

Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException: Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/***. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/***. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. MSI ResponseCode: BadRequest, Response: {"error":"invalid_request","error_description":"Identity not found"}
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/***. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. Environment variable LOCALAPPDATA not set.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/***. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. Token response is not in the expected format. Exception Message: There was an error deserializing the object of type Microsoft.Azure.Services.AppAuthentication.TokenResponse. Unexpected end of file. Following elements are not closed: root.

Stack Trace:
    at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAccessTokenAsyncImpl(String authority, String resource, String scope)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.PostAuthenticate(HttpResponseMessage response)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()

**To Reproduce**
Use the code snippet provided and test on a build agent:

***Code Snippet***

 var azureServiceTokenProvider = new AzureServiceTokenProvider();
            var keyVaultClient = new KeyVaultClient(
                new KeyVaultClient.AuthenticationCallback(
                    azureServiceTokenProvider.KeyVaultTokenCallback));

**Expected behavior**
Token should be returned properly

**Additional context**
We can overcome and resolve this by adding a retry mechanism for the Token request:

private readonly Policy RetryPolicy = Policy
            .Handle<AzureServiceTokenProviderException>()
            .WaitAndRetryAsync(5, retryAttempt => TimeSpan.FromMilliseconds(50));

  var keyVaultClient = new KeyVaultClient(
                new KeyVaultClient.AuthenticationCallback(GetAzureTokenAsync));

            ConfigurationBuilder configurationBuilder = new ConfigurationBuilder();
            configurationBuilder.AddAzureKeyVault(
                $"https://{keyVaultName}.vault.azure.net/", keyVaultClient, new DefaultKeyVaultSecretManager());
            Config = configurationBuilder.Build();

  private async Task<string> GetAzureTokenAsync(string authority, string resource, string scope)
        {
            return await RetryPolicy.ExecuteAsync(async () => await new AzureServiceTokenProvider().KeyVaultTokenCallback(authority, resource, scope));
        }

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

CC: @schaabs

**Comment by nonik0** [comment]
@MarcoK80 Hi Marco, in the latest AppAuth release we've added the suggested MSI retry logic described [here](https://docs.microsoft.com/en-us/azure/active-directory/managed-identities-azure-resources/how-to-use-vm-token#retry-guidance), which should hopefully help to alleviate sporadic token request failures.

Please continue to let us know any feedback you may have!
