### ISSUE TITLE
Could not load type 'Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate'

### ISSUE THREAD

**Issue by rajasekhar2** [Azure/azure-sdk-for-net#5636]
Facing lot of issues with Fluent Nuget. I am using Microsoft.Azure.Management.Cdn.Fluent" version="1.13.0"  and "Microsoft.IdentityModel.Clients.ActiveDirectory" version="3.14.2". At runtime I am getting error as "Could not load type 'Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate'" when I use Fluent methods to create a resource using arm template.

***Exception or Stack Trace***
Could not load type 'Microsoft.IdentityModel.Clients.ActiveDirectory.ClientAssertionCertificate' from assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.2.11, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__24.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__14.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateResourceAsync>d__59.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.<CreateAsync>d__58.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Health.Cloud.PortalExtension.TestMethods.BaseTest.<CreateResource>d__9.MoveNext()

**To Reproduce**
Use AuthenticationProvider to retrieve keyvault secret and then use credentials to create a resource with ARM template.
 AzureServiceTokenProvider azureServiceTokenProvider = new AzureServiceTokenProvider();
            KeyVaultClient keyVaultClient = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider.KeyVaultTokenCallback));
            var userName = keyVaultClient.GetSecretAsync("abc").Result.Value;
            var password = keyVaultClient.GetSecretAsync("efg").Result.Value;
var credentials = SdkContext.AzureCredentialsFactory.FromUser
                                (username, password, "clientID", "tenantId"
                            , AzureEnvironment.AzureGlobalCloud);
 azure.Deployments
                     .Define("name")
                     .WithExistingResourceGroup("ResourceGroupName")
                     .WithTemplate(templateJson.ToString())
                     .WithParameters("{ }")
                     .WithMode(DeploymentMode.Incremental)
                     .CreateAsync();

**Expected behavior**
resource should get created without error

**Setup (please complete the following information):**
 - OS: Windows
 - IDE : VS2017
 - >net 4.52

**Comment by kurtzeborn** [comment]
This appears to be an issue in the fluent repos for .Net, so I'm going to move the issue to that repo (azure-libraries-for-net).
