### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by schmidtaa** [Azure/azure-sdk-for-net#5885]
**Describe the bug**

We're getting the following error when entries in the blob are generated. It is sporadic and seems like may be correlated with higher load.

***Exception or Stack Trace***

2019-04-10T13:04:41
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AppendStreamToBlob(Stream stream)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()

2019-04-10T13:04:41
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.FlushBuffer(Boolean waitForCompletion)

2019-04-10T13:04:41
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.FlushBuffer(Boolean waitForCompletion)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.OnFlushBuffer(Object state)

2019-04-10T19:04:18
System.Threading.ThreadAbortException: Thread was being aborted.
   at System.Xml.XmlUtf8RawTextWriter..ctor(Stream stream, XmlWriterSettings settings)
   at System.Xml.XmlWriterSettings.CreateWriter(Stream output)
   at Microsoft.WindowsAzure.Storage.Blob.Protocol.BlobRequest.WriteBlockListBody(IEnumerable`1 blocks, Stream outputStream)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.PutBlockListImpl(IEnumerable`1 blocks, AccessCondition accessCondition, BlobRequestOptions options)
   at Microsoft.WindowsAzure.Storage.Blob.CloudBlockBlob.PutBlockList(IEnumerable`1 blockList, AccessCondition accessCondition, BlobRequestOptions options, OperationContext operationContext)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AppendStreamToBlob(Stream stream)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()

2019-04-10T19:04:18
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.FlushBuffer(Boolean waitForCompletion)

2019-04-10T19:04:18
System.Threading.ThreadAbortException: Thread was being aborted.
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.FlushBuffer(Boolean waitForCompletion)
   at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.OnFlushBuffer(Object state)

2019-04-19T22:53:39
Microsoft.WindowsAzure.Storage.StorageException: The remote server returned an error: (400) Bad Request. ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.
at System.Net.HttpWebRequest.GetResponse()
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand1 cmd, IRetryPolicy policy, OperationContext operationContext) --- End of inner exception stack trace --- at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand1 cmd, IRetryPolicy policy, OperationContext operationContext)
at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AppendStreamToBlob(Stream stream)
at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()
Request Information
RequestID:a912f750-c01e-011a-3302-f7a557000000
RequestDate:Fri, 19 Apr 2019 22:53:38 GMT
StatusMessage:The specified block list is invalid.
ErrorCode:InvalidBlockList

2019-04-19T22:43:49
System.Threading.ThreadAbortException: Thread was being aborted.
at Microsoft.WindowsAzure.Storage.Core.Executor.Executor.ExecuteSync[T](RESTCommand`1 cmd, IRetryPolicy policy, OperationContext operationContext)
at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.AppendStreamToBlob(Stream stream)
at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()

2019-04-19T22:43:49
System.Threading.ThreadAbortException: Thread was being aborted.
at Microsoft.WindowsAzure.WebSites.Diagnostics.AzureBlobTraceListener.ConsumeBuffer()
at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.FlushBuffer(Boolean waitForCompletion)

2019-04-19T22:43:49
System.Threading.ThreadAbortException: Thread was being aborted.
at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.FlushBuffer(Boolean waitForCompletion)
at Microsoft.WindowsAzure.WebSites.Diagnostics.BaseTraceListener.OnFlushBuffer(Object state)

**To Reproduce**

1. Create blob in the Azure
2. Create snippet to log entries via log4net to the blob using AzureBlobTraceListener

***Code Snippet***

Logger.Info or Logger.Error or Logger.Warn causes this.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
4.7.3324.0 built by: NET472REL1LAST_C

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [ ] Bug Description Added
- [ ] Repro Steps Added
- [ ] Setup information Added

**Comment by kurtzeborn** [comment]
Thank you for opening this issue! We are routing it to the appropriate team for follow up.

**Comment by blueww** [comment]
@tg-msft 
This looks not in SRP storage SDK, but in dataplane. Would you please help to look?

@schmidtaa 
Which SDK are you using? If you are using "Microsoft.Azure.Storage.Blob" or "WindowsAzure.Storage", You should file issue in https://github.com/Azure/azure-storage-net . This is not the right repo for the issue.

**Comment by schmidtaa** [comment]
Opened in azure-storage-net
