### ISSUE TITLE
ServiceFabricProcessor: HardGetRuntimeInfoFailure failing on .NET Framework 

### ISSUE THREAD

**Issue by weshaggard** [Azure/azure-sdk-for-net#5995]
```
[xUnit.net 00:00:28.97]     Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.EventHubExceptionTests.HardGetRuntimeInfoFailure [FAIL]
Failed   Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.EventHubExceptionTests.HardGetRuntimeInfoFailure
Error Message:
 Assert.Contains() Failure
Not found: ErrorInjector
In value:  One or more errors occurred.
Stack Trace:
   at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.EventHubExceptionTests.GeneralStartupFailure(String name, EHErrorLocation location, Boolean isEventHubsException) in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\ServiceFabricProcessor\EventHubExceptionTests.cs:line 298
   at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.EventHubExceptionTests.HardGetRuntimeInfoFailure() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\ServiceFabricProcessor\EventHubExceptionTests.cs:line 201
```
When running the EventHubs tests on .NET Framework the HardGetRuntimeInfoFailure test fails.

**Comment by weshaggard** [comment]
Looks like we also have the following test failing at least sometimes:

```
Failed   Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.OptionsTests.RuntimeInformationTest
Error Message:
 Assert.True() Failure
Expected: True
Actual:   False
Stack Trace:
   at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.OptionsTests.RuntimeInformationTest() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\ServiceFabricProcessor\OptionsTests.cs:line 191
```

**Comment by jsquire** [comment]
Reported as fixed with [#7446](https://github.com/Azure/azure-sdk-for-net/pull/7446).   As a result, closing this out.

**Comment by jsquire** [comment]
Reopening; this test has been failing intermittently in CI builds and also had nightly run failures.   Marking to be ignored pending further investigation.

**Comment by JamesBirdsall** [comment]
For the record, this is a test issue in ServiceFabricProcessor which is still in preview. The entire CIT mechanism needs some work to make it more deterministic, and that will happen when we have time to start moving SFP toward GA.

**Comment by samuelkoppes** [comment]
We are investigating this issue, and will report back with a status update by 11/4/2020.

**Comment by kasun04** [comment]
The Microsoft.Azure.EventHubs.ServiceFabricProcessor package is in preview and there are no plans for a stable release. This package will soon be deprecated and therefore we won't be taking any changes.

**Comment by kasun04** [comment]
Please remove the package from the test pipeline.
