### ISSUE TITLE
[BUG]Tests fail in Microsoft.Azure.CognitiveServices.AnomalyDetector. Tests

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#6208]
**Bug Description**
Various tests are failing in Microsoft.Azure.CognitiveServices.AnomalyDetector.

***Exception or Stack Trace***
```
[xUnit.net 00:00:01.25]     AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestNormalDistributionSeries [FAIL]
[xUnit.net 00:00:01.25]     AnomalyDetectorSDK.Tests.LastPointDetectTests.TestLastAnomalySeries [FAIL]
Failed   AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestNormalDistributionSeries
Error Message:
 System.AggregateException : One or more errors occurred. (Unable to find a matching HTTP request for URL 'POST /anomalydetector/v1.0/timeseries/entire/detect'. Calling method Item().)
---- System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /anomalydetector/v1.0/timeseries/entire/detect'. Calling method Item().
Stack Trace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestNormalDistributionSeries() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\tests\EntireSeriesDetectTests.cs:line 152
----- Inner Stack Trace -----
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClient.EntireDetectWithHttpMessagesAsync(Request body, Dictionary`2 customHeaders, CancellationToken cancellationToken) in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClient.cs:line 318
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClientExtensions.EntireDetectAsync(IAnomalyDetectorClient operations, Request body, CancellationToken cancellationToken) in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClientExtensions.cs:line 43
Failed   AnomalyDetectorSDK.Tests.LastPointDetectTests.TestLastAnomalySeries
Error Message:
 System.AggregateException : One or more errors occurred. (Unable to find a matching HTTP request for URL 'POST /anomalydetector/v1.0/timeseries/last/detect'. Calling method Item().)
---- System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /anomalydetector/v1.0/timeseries/last/detect'. Calling method Item().
Stack Trace:
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at AnomalyDetectorSDK.Tests.LastPointDetectTests.TestLastAnomalySeries() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\tests\LastPointDetectTests.cs:line 81
----- Inner Stack Trace -----
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClient.LastDetectWithHttpMessagesAsync(Request body, Dictionary`2 customHeaders, CancellationToken cancellationToken) in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClient.cs:line 487
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClientExtensions.LastDetectAsync(IAnomalyDetectorClient operations, Request body, CancellationToken cancellationToken) in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClientExtensions.cs:line 70

Total tests: 7. Passed: 5. Failed: 2. Skipped: 0.
Test Run Failed.
Test execution time: 2.4308 Seconds
Test run for C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.AnomalyDetector.Tests\Debug\net461\Microsoft.Azure.CognitiveServices.AnomalyDetector.Tests.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:04.07]     AnomalyDetectorSDK.Tests.LastPointDetectTests.TestNormalDistributionSeries [FAIL]
[xUnit.net 00:00:04.08]     AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestLastAnomalySeries [FAIL]
[xUnit.net 00:00:04.09]     AnomalyDetectorSDK.Tests.LastPointDetectTests.TestSineDistributionSeries [FAIL]
[xUnit.net 00:00:04.09]     AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestSineDistributionSeries [FAIL]
Failed   AnomalyDetectorSDK.Tests.LastPointDetectTests.TestNormalDistributionSeries
Error Message:
 System.AggregateException : One or more errors occurred.
---- System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /anomalydetector/v1.0/timeseries/last/detect'. Calling method Item().
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AnomalyDetectorSDK.Tests.LastPointDetectTests.TestNormalDistributionSeries() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\tests\LastPointDetectTests.cs:line 138
----- Inner Stack Trace -----
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClient.<LastDetectWithHttpMessagesAsync>d__29.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClient.cs:line 487
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClientExtensions.<LastDetectAsync>d__1.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClientExtensions.cs:line 70
Failed   AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestLastAnomalySeries
Error Message:
 System.AggregateException : One or more errors occurred.
---- System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /anomalydetector/v1.0/timeseries/entire/detect'. Calling method Item().
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestLastAnomalySeries() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\tests\EntireSeriesDetectTests.cs:line 52
----- Inner Stack Trace -----
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClient.<EntireDetectWithHttpMessagesAsync>d__28.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClient.cs:line 318
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClientExtensions.<EntireDetectAsync>d__0.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClientExtensions.cs:line 43
Failed   AnomalyDetectorSDK.Tests.LastPointDetectTests.TestSineDistributionSeries
Error Message:
 System.AggregateException : One or more errors occurred.
---- System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /anomalydetector/v1.0/timeseries/last/detect'. Calling method Item().
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AnomalyDetectorSDK.Tests.LastPointDetectTests.TestSineDistributionSeries() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\tests\LastPointDetectTests.cs:line 100
----- Inner Stack Trace -----
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClient.<LastDetectWithHttpMessagesAsync>d__29.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClient.cs:line 487
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClientExtensions.<LastDetectAsync>d__1.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClientExtensions.cs:line 70
Failed   AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestSineDistributionSeries
Error Message:
 System.AggregateException : One or more errors occurred.
---- System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /anomalydetector/v1.0/timeseries/entire/detect'. Calling method Item().
Stack Trace:
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at AnomalyDetectorSDK.Tests.EntireSeriesDetectTests.TestSineDistributionSeries() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\tests\EntireSeriesDetectTests.cs:line 114
----- Inner Stack Trace -----
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClient.<EntireDetectWithHttpMessagesAsync>d__28.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClient.cs:line 318
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.CognitiveServices.AnomalyDetector.AnomalyDetectorClientExtensions.<EntireDetectAsync>d__0.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.AnomalyDetector\src\Generated\AnomalyDetectorClientExtensions.cs:line 43

Total tests: 7. Passed: 3. Failed: 4. Skipped: 0.
Test Run Failed.
Test execution time: 5.0466 Seconds
```

**To Reproduce**
Remove Skip property from the Test Attibute on the specific test.

**Expected behavior**
Test Fails.  Different tests fail on different runs

**Comment by jongio** [comment]
@annelo-msft - This is T1, thoughts on what to do with this?

**Comment by jsquire** [comment]
Given the age of this issue and the deprecation of most of the track one libraries, closing this as stale.  If tests are still failing, please file a new issue.
