### ISSUE TITLE
[BUG]Tests fail in Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#6212]
**Bug Description**
Various tests are failing in Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests

***Exception or Stack Trace***
```
Starting test execution, please wait...
[xUnit.net 00:00:00.88]     Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.SentimentTests.Sentiment [FAIL]
[xUnit.net 00:00:00.90]     Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.DetectLanguageTests.DetectLanguage [FAIL]
[xUnit.net 00:00:00.90]     Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.KeyPhrasesTests.KeyPhrases [FAIL]
Failed   Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.SentimentTests.Sentiment
Error Message:
 System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests\Debug\netcoreapp2.0\SessionRecords\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.EntitiesTests\Sentiment.json'.
Parameter name: callerIdentity
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(String className, String methodName)
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.SentimentTests.Sentiment() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\tests\TextAnalytics\SentimentTests.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
Failed   Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.DetectLanguageTests.DetectLanguage
Error Message:
 System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests\Debug\netcoreapp2.0\SessionRecords\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.EntitiesTests\DetectLanguage.json'.
Parameter name: callerIdentity
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(String className, String methodName)
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.DetectLanguageTests.DetectLanguage() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\tests\TextAnalytics\DetectLanguageTests.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
Failed   Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.KeyPhrasesTests.KeyPhrases
Error Message:
 System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests\Debug\netcoreapp2.0\SessionRecords\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.EntitiesTests\KeyPhrases.json'.
Parameter name: callerIdentity
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(String className, String methodName)
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.KeyPhrasesTests.KeyPhrases() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\tests\TextAnalytics\KeyPhrasesTests.cs:line 19
--- End of stack trace from previous location where exception was thrown ---

Total tests: 4. Passed: 1. Failed: 3. Skipped: 0.
Test Run Failed.
Test execution time: 1.9935 Seconds
Test run for C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests\Debug\net461\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:01.91]     Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.KeyPhrasesTests.KeyPhrases [FAIL]
[xUnit.net 00:00:02.42]     Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.DetectLanguageTests.DetectLanguage [FAIL]
[xUnit.net 00:00:02.43]     Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.EntitiesTests.Entities [FAIL]
Failed   Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.KeyPhrasesTests.KeyPhrases
Error Message:
 System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests\Debug\net461\SessionRecords\Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.SentimentTests\KeyPhrases.json'.
Parameter name: callerIdentity
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(String className, String methodName)
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.KeyPhrasesTests.<KeyPhrases>d__0.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\tests\TextAnalytics\KeyPhrasesTests.cs:line 19
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.DetectLanguageTests.DetectLanguage
Error Message:
 System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /text/analytics/v2.1/languages'. Calling method Item().
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.TextAnalyticsClient.<DetectLanguageWithHttpMessagesAsync>d__28.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\src\Generated\TextAnalytics\TextAnalyticsClient.cs:line 323
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.TextAnalyticsClientExtensions.<DetectLanguageAsync>d__0.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\src\Generated\TextAnalytics\TextAnalyticsClientExtensions.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.DetectLanguageTests.<DetectLanguage>d__0.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\tests\TextAnalytics\DetectLanguageTests.cs:line 23
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.EntitiesTests.Entities
Error Message:
 System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /text/analytics/v2.1/entities'. Calling method Item().
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.TextAnalyticsClient.<EntitiesWithHttpMessagesAsync>d__29.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\src\Generated\TextAnalytics\TextAnalyticsClient.cs:line 499
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.TextAnalyticsClientExtensions.<EntitiesAsync>d__1.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\src\Generated\TextAnalytics\TextAnalyticsClientExtensions.cs:line 76
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.CognitiveServices.Language.TextAnalytics.Tests.EntitiesTests.<Entities>d__0.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Language.TextAnalytics\tests\TextAnalytics\EntitiesTests.cs:line 20
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Total tests: 4. Passed: 1. Failed: 3. Skipped: 0.
Test Run Failed.
Test execution time: 3.2244 Seconds
```

**To Reproduce**
Remove Skip property from the Test Attibute on the specific test.

**Expected behavior**
Test Fails. Different tests fail on different runs.

**Comment by jsquire** [comment]
Given the age of this issue and the deprecation of most of the track one libraries, closing this as stale.  If tests are still failing, please file a new issue.
