### ISSUE TITLE
[BUG]Tests fail in Microsoft.Azure.CognitiveServices.Personalizer.Tests

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#6213]
**Bug Description**
Various tests are failing in Microsoft.Azure.CognitiveServices.Personalizer.Tests

***Exception or Stack Trace***
```
Test run for C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Personalizer.Tests\Debug\netcoreapp2.0\Microsoft.Azure.CognitiveServices.Personalizer.Tests.dll(.NETCoreApp,Version=v2.0)
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:00.93]     Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankNullParametersTest.RankNullParameters [FAIL]
[xUnit.net 00:00:00.95]     Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankServerFeaturesTest.RankServerFeatures [FAIL]
Failed   Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankNullParametersTest.RankNullParameters
Error Message:
 System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Personalizer.Tests\Debug\netcoreapp2.0\SessionRecords\Microsoft.Azure.CognitiveServices.Personalizer.Tests.RewardTest\RankNullParameters.json'.
Parameter name: callerIdentity
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(String className, String methodName)
   at Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankNullParametersTest.RankNullParameters() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Personalizer\tests\Personalizer\RankNullParametersTest.cs:line 15
--- End of stack trace from previous location where exception was thrown ---
Failed   Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankServerFeaturesTest.RankServerFeatures
Error Message:
 System.ArgumentException : Unable to find recorded mock file 'C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Personalizer.Tests\Debug\netcoreapp2.0\SessionRecords\Microsoft.Azure.CognitiveServices.Personalizer.Tests.RewardTest\RankServerFeatures.json'.
Parameter name: callerIdentity
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.Initialize(String callerIdentity, String testIdentity, HttpRecorderMode mode)
   at Microsoft.Rest.ClientRuntime.Azure.TestFramework.MockContext.Start(String className, String methodName)
   at Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankServerFeaturesTest.RankServerFeatures() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Personalizer\tests\Personalizer\RankServerFeaturesTest.cs:line 15
--- End of stack trace from previous location where exception was thrown ---

Total tests: 3. Passed: 1. Failed: 2. Skipped: 0.
Test Run Failed.
Test execution time: 2.0462 Seconds
Test run for C:\git\azure-sdk-for-net\artifacts\bin\Microsoft.Azure.CognitiveServices.Personalizer.Tests\Debug\net461\Microsoft.Azure.CognitiveServices.Personalizer.Tests.dll(.NETFramework,Version=v4.6.1)
Microsoft (R) Test Execution Command Line Tool Version 16.0.1
Copyright (c) Microsoft Corporation.  All rights reserved.

Starting test execution, please wait...
[xUnit.net 00:00:02.17]     Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankNullParametersTest.RankNullParameters [FAIL]
[xUnit.net 00:00:02.18]     Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankServerFeaturesTest.RankServerFeatures [FAIL]
Failed   Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankNullParametersTest.RankNullParameters
Error Message:
 System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /personalizer/v1.0/rank'. Calling method Item().
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Personalizer.Events.<RankWithHttpMessagesAsync>d__7.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Personalizer\src\Generated\Events.cs:line 414
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.CognitiveServices.Personalizer.EventsExtensions.<RankAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankNullParametersTest.<RankNullParameters>d__0.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Personalizer\tests\Personalizer\RankNullParametersTest.cs:line 32
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Failed   Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankServerFeaturesTest.RankServerFeatures
Error Message:
 System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'POST /personalizer/v1.0/rank'. Calling method Item().
Stack Trace:
   at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
   at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.CognitiveServices.Personalizer.Events.<RankWithHttpMessagesAsync>d__7.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Personalizer\src\Generated\Events.cs:line 414
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.CognitiveServices.Personalizer.EventsExtensions.<RankAsync>d__7.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Personalizer\src\Generated\EventsExtensions.cs:line 161
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.CognitiveServices.Personalizer.Tests.RankServerFeaturesTest.<RankServerFeatures>d__0.MoveNext() in C:\git\azure-sdk-for-net\sdk\cognitiveservices\Microsoft.Azure.CognitiveServices.Personalizer\tests\Personalizer\RankServerFeaturesTest.cs:line 46
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

Total tests: 3. Passed: 1. Failed: 2. Skipped: 0.
Test Run Failed.
Test execution time: 2.9635 Seconds
```

**To Reproduce**
Remove Skip property from the Test Attibute on the specific test.

**Expected behavior**
Test Fails. Different tests fail on different runs.

**Comment by kaerm** [comment]
@tyclintw I am not sure if this is still valid - can you take a look and close if this has been resolved

**Comment by jsquire** [comment]
Given the age of this issue and the deprecation of most of the track one libraries, closing this as stale.  If tests are still failing, please file a new issue.
