### ISSUE TITLE
[BUG]Azure.Batch.Unit.Tests.HttpClientBehaviorTests Fails on no Windows OS

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#6417]
**Bug Description**
Azure.Batch.Unit.Tests.HttpClientBehaviorTests fails on Linux and MacOs. Microsoft.Net.Http.Server uses the Windows HTTP Server API not available on non-windows OS. Consider using Kestrel server.

***Exception or Stack Trace***
```
[xUnit.net 00:00:02.42]     Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: DELETE) [FAIL]
[xUnit.net 00:00:02.45]     Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: POST) [FAIL]
Failed   Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: DELETE)
Error Message:
 System.TypeInitializationException : The type initializer for 'Microsoft.Net.Http.Server.HttpApi' threw an exception.
---- System.DllNotFoundException : Unable to load shared library 'httpapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhttpapi.dll: cannot open shared object file: No such file or directory
Stack Trace:
   at Microsoft.Net.Http.Server.WebListener..ctor(WebListenerSettings settings)
   at Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(HttpMethod httpMethod) in /home/vsts/work/1/s/sdk/batch/Microsoft.Azure.Batch/tests/UnitTests/HttpClientBehaviorTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.Net.Http.Server.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
   at Microsoft.Net.Http.Server.HttpApi.InitHttpApi(UInt16 majorVersion, UInt16 minorVersion)
   at Microsoft.Net.Http.Server.HttpApi..cctor()
Failed   Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: POST)
Error Message:
 System.TypeInitializationException : The type initializer for 'Microsoft.Net.Http.Server.HttpApi' threw an exception.
---- System.DllNotFoundException : Unable to load shared library 'httpapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhttpapi.dll: cannot open shared object file: No such file or directory
Stack Trace:
   at Microsoft.Net.Http.Server.WebListener..ctor(WebListenerSettings settings)
   at Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(HttpMethod httpMethod) in /home/vsts/work/1/s/sdk/batch/Microsoft.Azure.Batch/tests/UnitTests/HttpClientBehaviorTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.Net.Http.Server.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
   at Microsoft.Net.Http.Server.HttpApi.InitHttpApi(UInt16 majorVersion, UInt16 minorVersion)
   at Microsoft.Net.Http.Server.HttpApi..cctor()
[xUnit.net 00:00:02.46]     Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: GET) [FAIL]
[xUnit.net 00:00:02.46]     Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: HEAD) [FAIL]
[xUnit.net 00:00:02.46]     Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: PATCH) [FAIL]
[xUnit.net 00:00:02.46]     Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: PUT) [FAIL]
[xUnit.net 00:00:02.46]     Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: OPTIONS) [FAIL]
Failed   Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: GET)
Error Message:
 System.TypeInitializationException : The type initializer for 'Microsoft.Net.Http.Server.HttpApi' threw an exception.
---- System.DllNotFoundException : Unable to load shared library 'httpapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhttpapi.dll: cannot open shared object file: No such file or directory
Stack Trace:
   at Microsoft.Net.Http.Server.WebListener..ctor(WebListenerSettings settings)
   at Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(HttpMethod httpMethod) in /home/vsts/work/1/s/sdk/batch/Microsoft.Azure.Batch/tests/UnitTests/HttpClientBehaviorTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.Net.Http.Server.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
   at Microsoft.Net.Http.Server.HttpApi.InitHttpApi(UInt16 majorVersion, UInt16 minorVersion)
   at Microsoft.Net.Http.Server.HttpApi..cctor()
Failed   Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: HEAD)
Error Message:
 System.TypeInitializationException : The type initializer for 'Microsoft.Net.Http.Server.HttpApi' threw an exception.
---- System.DllNotFoundException : Unable to load shared library 'httpapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhttpapi.dll: cannot open shared object file: No such file or directory
Stack Trace:
   at Microsoft.Net.Http.Server.WebListener..ctor(WebListenerSettings settings)
   at Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(HttpMethod httpMethod) in /home/vsts/work/1/s/sdk/batch/Microsoft.Azure.Batch/tests/UnitTests/HttpClientBehaviorTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.Net.Http.Server.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
   at Microsoft.Net.Http.Server.HttpApi.InitHttpApi(UInt16 majorVersion, UInt16 minorVersion)
   at Microsoft.Net.Http.Server.HttpApi..cctor()
Failed   Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: PATCH)
Error Message:
 System.TypeInitializationException : The type initializer for 'Microsoft.Net.Http.Server.HttpApi' threw an exception.
---- System.DllNotFoundException : Unable to load shared library 'httpapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhttpapi.dll: cannot open shared object file: No such file or directory
Stack Trace:
   at Microsoft.Net.Http.Server.WebListener..ctor(WebListenerSettings settings)
   at Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(HttpMethod httpMethod) in /home/vsts/work/1/s/sdk/batch/Microsoft.Azure.Batch/tests/UnitTests/HttpClientBehaviorTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.Net.Http.Server.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
   at Microsoft.Net.Http.Server.HttpApi.InitHttpApi(UInt16 majorVersion, UInt16 minorVersion)
   at Microsoft.Net.Http.Server.HttpApi..cctor()
Failed   Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: PUT)
Error Message:
 System.TypeInitializationException : The type initializer for 'Microsoft.Net.Http.Server.HttpApi' threw an exception.
---- System.DllNotFoundException : Unable to load shared library 'httpapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhttpapi.dll: cannot open shared object file: No such file or directory
Stack Trace:
   at Microsoft.Net.Http.Server.WebListener..ctor(WebListenerSettings settings)
   at Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(HttpMethod httpMethod) in /home/vsts/work/1/s/sdk/batch/Microsoft.Azure.Batch/tests/UnitTests/HttpClientBehaviorTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.Net.Http.Server.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
   at Microsoft.Net.Http.Server.HttpApi.InitHttpApi(UInt16 majorVersion, UInt16 minorVersion)
   at Microsoft.Net.Http.Server.HttpApi..cctor()
Failed   Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(httpMethod: OPTIONS)
Error Message:
 System.TypeInitializationException : The type initializer for 'Microsoft.Net.Http.Server.HttpApi' threw an exception.
---- System.DllNotFoundException : Unable to load shared library 'httpapi.dll' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libhttpapi.dll: cannot open shared object file: No such file or directory
Stack Trace:
   at Microsoft.Net.Http.Server.WebListener..ctor(WebListenerSettings settings)
   at Azure.Batch.Unit.Tests.HttpClientBehaviorTests.HttpClient_IncludesContentLengthHeaderOnExpectedHttpVerbs(HttpMethod httpMethod) in /home/vsts/work/1/s/sdk/batch/Microsoft.Azure.Batch/tests/UnitTests/HttpClientBehaviorTests.cs:line 37
--- End of stack trace from previous location where exception was thrown ---
----- Inner Stack Trace -----
   at Microsoft.Net.Http.Server.HttpApi.HttpInitialize(HTTPAPI_VERSION version, UInt32 flags, Void* pReserved)
   at Microsoft.Net.Http.Server.HttpApi.InitHttpApi(UInt16 majorVersion, UInt16 minorVersion)
   at Microsoft.Net.Http.Server.HttpApi..cctor()
```

**To Reproduce**
Remove the Pre-Processor directive `#if Windows`. Trigger `net - batch -ci` pipeline on DevOps.

**Expected behavior**
Test Fails on Linux and MacOS

**Screenshots**

**Setup (please complete the following information):**
 - OS: MacOS, Linux

**Comment by jsquire** [comment]
Closing; this is quite old at this point.  If tests continue to fail, a new issue will be opened.
