### ISSUE TITLE
HardEventHubReceiveFailure is flaky

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7335]
```
 X Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.EventHubExceptionTests.HardEventHubReceiveFailure [1s 150ms]
  Error Message:
   Shut down before open
Expected: False
Actual:   True
  Stack Trace:
     at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.TestState.VerifyNormalStartup(Int32 maxRetries) in /Users/vsts/agent/2.155.1/work/1/s/sdk/eventhub/Microsoft.Azure.EventHubs/tests/ServiceFabricProcessor/TestState.cs:line 108
   at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.EventHubExceptionTests.EventHubReceiveFailure(String name, Exception error, Boolean isEventHubsException) in /Users/vsts/agent/2.155.1/work/1/s/sdk/eventhub/Microsoft.Azure.EventHubs/tests/ServiceFabricProcessor/EventHubExceptionTests.cs:line 387
   at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.EventHubExceptionTests.HardEventHubReceiveFailure() in /Users/vsts/agent/2.155.1/work/1/s/sdk/eventhub/Microsoft.Azure.EventHubs/tests/ServiceFabricProcessor/EventHubExceptionTests.cs:line 364

```

**Comment by JamesBirdsall** [comment]
Fixed by #7446
