### ISSUE TITLE
Error when trying to authenticate: Method not found: 'System.Diagnostics.ActivityIdFormat System.Diagnostics.Activity.get_IdFormat()'.

### ISSUE THREAD

**Issue by tombrothers** [Azure/azure-sdk-for-net#7354]
**Describe the bug**
An error occurs when trying to enable storage account diagnostics (classic).

***Exception or Stack Trace***
Method not found: 'System.Diagnostics.ActivityIdFormat System.Diagnostics.Activity.get_IdFormat()'.
```

   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.BufferResponsePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.LoggingPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.ImdsAvailableAsync(CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.GetMsiTypeAsync(CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateAsync(String[] scopes, String clientId, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityCredential.GetTokenAsync(String[] scopes, CancellationToken cancellationToken)
   at Azure.Core.Pipeline.BearerTokenAuthenticationPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobRestClient.Service.SetPropertiesAsync(HttpPipeline pipeline, Uri resourceUri, BlobServiceProperties blobServiceProperties, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.SetPropertiesInternal(BlobServiceProperties properties, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobServiceClient.SetPropertiesAsync(BlobServiceProperties properties, CancellationToken cancellationToken)
   at CareSeed.Greenhouse.Azure.Services.Storage.BlobService.EnableDiagnosticsAsync(String subscriptionId, String storageAccountName, CancellationToken cancellationToken) in C:\_dev\CareSeed.Greenhouse.App\CareSeed.Greenhouse.Azure\Services\Storage\BlobService.cs:line 61
```

**To Reproduce**
Execute equivalent of code snippet.

***Code Snippet***
```
var uri = new Uri($"https://{storageAccountName}.blob.core.windows.net/");
var clientId = await this.GetClientIdAsync();
var managedIdentityCredential = new ManagedIdentityCredential(clientId);
var client = new BlobServiceClient(uri, managedIdentityCredential);
var properties = new BlobServiceProperties
{
	Logging = new Logging
	{
		Version = "2.0",
		Read = true,
		Write = true,
		Delete = true,
		RetentionPolicy = new RetentionPolicy
		{
			Enabled = true,
			Days = 30
		}
	},
	HourMetrics = new Metrics
	{
		Enabled = true,
		IncludeAPIs = true,
		Version = "1.0",
		RetentionPolicy = new RetentionPolicy
		{
			Enabled = true,
			Days = 7
		}
	}
};

var response = await client.SetPropertiesAsync(properties, cancellationToken);
```

**Expected behavior**
Expected to not get an exception.

**Setup (please complete the following information):**
 - OS: Windows 10 1903
 - IDE : Visual Studio Professional 2019 16.1.14
 - Azure.Storage.Blobs 12.0.0-preview.2

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x ] Bug Description Added
- [x ] Repro Steps Added
- [x ] Setup information Added

**Comment by AlexGhiondea** [comment]
@tombrothers can you let me know what .NET version are you targeting?

I guess that you are not targeting (or running) on .NET Core 3 Preview 8 -- can you confirm?

**Comment by tombrothers** [comment]
This is in an Azure Functions v2 project so it is .Net Core 2.  I don't have a direct dependency on System.Diagnostics.DiagnosticsSource so it is the version that is references by Azure.Storage.Blobs which is 4.6.0.preview7.19362.9.

**Comment by AlexGhiondea** [comment]
Thanks for letting me know! Do you happen to have a repro that we can take a look at?

The package that you mention should have worked just fine on the .NET Core 2.0.

/cc @pakrym

**Comment by lmolkova** [comment]
@brettsam it seems Functions downgrade System.Diagnostics.DiagnosticSource (4.6.0-preview) that was brought by the new version of Azure Blobs SDK 12.0.0-preview.2. It seems it was downgraded to the 4.5.*. could it be the case?

**Comment by pakrym** [comment]
It looks like Azure Functions runtime is overriding the `System.Diagnostics.DiagnosticSource` dependency version to 4.5.x that doesn't have `Activity.get_IdFormat` method even thought we bring explicit dependency to `4.6.0-preview`

cc @paulbatum

**Comment by lmolkova** [comment]
Tied with template http-trigger function without new Azure Blob storage.
Just installed latest DiagnosticSource

```csharp
[FunctionName("Function1")]
public static async Task<IActionResult> Run(
    [HttpTrigger(AuthorizationLevel.Function, "get", "post", Route = null)] HttpRequest req,
    ILogger log)
{
    log.LogInformation(Activity.Current?.IdFormat.ToString());
     ...
}
```

[8/21/2019 7:04:36 PM] System.Private.CoreLib: Exception while executing function: Function1. FunctionApp4: Could not load type 'System.Diagnostics.ActivityIdFormat' from assembly 'System.Diagnostics.DiagnosticSource, Version=4.0.3.1, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'.

probably this happens because function runtime brings AppInsights SDK of a certain version that depends on DiagnosticSource and both are downgraded.

I suggest this issue to be transferred to https://github.com/azure/azure-webjobs-sdk as it seems it's not related to Azure Storage sdk.

**Comment by mitchdenny** [comment]
This is also impacting KeyVault. Haven't been able to find a workaround yet.

**Comment by brettsam** [comment]
Functions takes a dependency on a specific version of DiagnosticSource. I'm going to move this to our repo as it looks like it's on us.

**Comment by brettsam** [comment]
It doesn't appear I have the permissions to transfer -- could one of the owners move this issue to https://github.com/Azure/azure-functions-host?

**Comment by pakrym** [comment]
@mitchdenny  already filed https://github.com/Azure/azure-functions-host/issues/4906

**Comment by mitchdenny** [comment]
I can transfer from this repo - but I can't select yours.

**Comment by mitchdenny** [comment]
@pakrym implemented a workaround in Azure.Core which should unblock this. I'm going to close this one down since the latest preview package should work for you. Let us know if that is not the case. When Azure Functions updates to a newer version of DiagnosticsSource the code should just adapt.

Azure Functions will probably update to the newer DiagnosticsSource package when a non-preview release is published.
