### ISSUE TITLE
[BUG] Connected Service is failing in Visual Studio 2019 16.3 Preview 2

### ISSUE THREAD

**Issue by mikedouglasdev** [Azure/azure-sdk-for-net#7468]
**Describe the bug**
In following the instructions to use the connected service in Visual Studio, there were multiple issues. https://docs.microsoft.com/en-us/azure/key-vault/vs-key-vault-add-connected-service

***Exception or Stack Trace***
In the Add Connected Service wizard, it fails with this message:
When creating a new Key Vault...
```
Error:Adding Azure Key Vault to the project failed: An invalid value was provided for 'accessPolicies'.
```

When I follow the steps and try to execute the code, I get the following error:
```
Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProviderException
  HResult=0x80131500
  Message=Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/254973fc-e7d1-44b7-b975-3f8ded0bf011. Exception Message: Tried the following 3 methods to get an access token, but none of them worked.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/254973fc-e7d1-44b7-b975-3f8ded0bf011. Exception Message: Tried to get token using Managed Service Identity. Access token could not be acquired. An error occurred while sending the request.
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/254973fc-e7d1-44b7-b975-3f8ded0bf011. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. 
Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : TS003: Error, No method by the name 'locate' is found.
 
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/254973fc-e7d1-44b7-b975-3f8ded0bf011. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. ERROR: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: b682c508-2cc5-4420-8981-06a3ee0b5d00\r\nCorrelation ID: 8bc4f069-9f42-44d7-b1ba-1b71a2c2b9ea\r\nTimestamp: 2019-09-04 00:09:15Z","error_codes":[9002313],"timestamp":"2019-09-04 00:09:15Z","trace_id":"b682c508-2cc5-4420-8981-06a3ee0b5d00","correlation_id":"8bc4f069-9f42-44d7-b1ba-1b71a2c2b9ea","error_uri":"https://login.microsoftonline.com/error?code=9002313"}
Traceback (most recent call last):
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\cli.py", line 197, in invoke
    cmd_result = self.invocation.execute(args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 332, in execute
    six.reraise(*sys.exc_info())
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\six.py", line 693, in reraise
    raise value
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 306, in execute
    result = cmd(params)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\commands\__init__.py", line 167, in __call__
    return super(AzCliCommand, self).__call__(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\knack\commands.py", line 109, in __call__
    return self.handler(*args, **kwargs)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\__init__.py", line 420, in default_command_handler
    result = op(**command_args)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\command_modules\profile\custom.py", line 67, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 499, in get_raw_token
    account[_TENANT_ID], resource)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\azure\cli\core\_profile.py", line 789, in retrieve_token_for_user
    token_entry = context.acquire_token(resource, username, _CLIENT_ID)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 134, in acquire_token
    return self._acquire_token(token_func)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 117, in _acquire_token
    return token_func(self)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\authentication_context.py", line 132, in token_func
    return token_request.get_token_from_cache_with_refresh(user_id)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\token_request.py", line 349, in get_token_from_cache_with_refresh
    return self._find_token_from_cache()
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\token_request.py", line 128, in _find_token_from_cache
    return self._cache_driver.find(cache_query)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\cache_driver.py", line 199, in find
    is_resource_tenant_specific)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\cache_driver.py", line 184, in _refresh_entry_if_necessary
    return self._acquire_new_token_from_mrrt(entry)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\cache_driver.py", line 160, in _acquire_new_token_from_mrrt
    token_response = self._refresh_function(entry, self._resource)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\token_request.py", line 138, in _get_token_with_token_response
    return self._get_token_with_refresh_token(refresh_token, resource, None)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\token_request.py", line 341, in _get_token_with_refresh_token
    return self._oauth_get_token(oauth_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\token_request.py", line 113, in _oauth_get_token
    return client.get_token(oauth_parameters)
  File "C:\Program Files (x86)\Microsoft SDKs\Azure\CLI2\lib\site-packages\adal\oauth2_client.py", line 288, in get_token
    raise AdalError(return_error_string, error_response)
adal.adal_error.AdalError: Get Token request returned http error: 400 and server response: {"error":"invalid_grant","error_description":"AADSTS9002313: Invalid request. Request is malformed or invalid.\r\nTrace ID: b682c508-2cc5-4420-8981-06a3ee0b5d00\r\nCorrelation ID: 8bc4f069-9f42-44d7-b1ba-1b71a2c2b9ea\r\nTimestamp: 2019-09-04 00:09:15Z","error_codes":[9002313],"timestamp":"2019-09-04 00:09:15Z","trace_id":"b682c508-2cc5-4420-8981-06a3ee0b5d00","correlation_id":"8bc4f069-9f42-44d7-b1ba-1b71a2c2b9ea","error_uri":"https://login.microsoftonline.com/error?code=9002313"}


  Source=Microsoft.Azure.Services.AppAuthentication
  StackTrace:
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<GetAuthResultAsyncImpl>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<<get_KeyVaultTokenCallback>b__8_0>d.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultCredential.<PostAuthenticate>d__11.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultCredential.<ProcessHttpRequestAsync>d__13.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.KeyVault.KeyVaultClient.<GetSecretsWithHttpMessagesAsync>d__67.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.<GetSecretsAsync>d__50.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.<LoadAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.BuildCommonServices(AggregateException& hostingStartupErrors)
   at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
   at demoweb.Program.BuildWebHost(String[] args) in C:\development\demo\demoweb\demoweb\Program.cs:line 24
   at demoweb.Program.Main(String[] args) in C:\development\demo\demoweb\demoweb\Program.cs:line 20
```

**To Reproduce**
I followed the steps for building an ASP.NET Core web application in the article above.  I tried 2.0, 2.2, and 3.0.  Also have the same error.
I tried with my Microsoft Account and I also created a new AAD account and gave it appropriate permissions but received the same error.
I also tried updating the Microsoft.Azure.Services.AppAuthentication library to 1.3.1.
The directions said to add this package, Microsoft.Azure.KeyVault.  I added this but I also saw there was a Microsoft.Azure.KeyVault.Core version.  I tried that too but it didn't help.

***Code Snippet***
I only added the code that was included in the article above.

**Expected behavior**

**Screenshots**

**Setup (please complete the following information):**
 - OS: Windows 10, IIS Express
 - IDE : Visual Studio 2019 16.3 Preview 2
 - Version of the Library used

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by isra-fel** [comment]
Sorry for late response Mike. I practiced the guide and it worked perfectly.

The idea of this guide is to get your Azure token from visual studio, and use it to get your secret from key vault, so guessing from these lines, I believe the error was caused by API mismatch between the authentication library and visual studio. Updating them might solve the problem.

> Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/254973fc-e7d1-44b7-b975-3f8ded0bf011. Exception Message: Tried to get token using Visual Studio. Access token could not be acquired. 
> Exception for Visual Studio token provider Microsoft.Asal.TokenService.exe : TS003: Error, No method by the name 'locate' is found.

Here's my configuration:
|item|version|
|-|-|
|Visual studio |16.5.4|
|.Net core sdk |3.1.201|
|Microsoft.Azure.Services.AppAuthentication |1.4.0|
|Microsoft.Azure.KeyVault.Core| 3.0.5|

Sample repo: https://github.com/isra-fel/test-vs-connected-service-kv
