### ISSUE TITLE
[BUG] CheckpointBatchTest Failing on .NET Framework

### ISSUE THREAD

**Issue by chidozieononiwu** [Azure/azure-sdk-for-net#7492]
**Describe the bug**
CheckpointBatchTest Fails randomly on .NET Framework

***Exception or Stack Trace***
```[xUnit.net 00:00:20.93]     Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.CheckpointingTests.CheckpointBatchTest [FAIL]
22:44:36.0911952: End Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.CheckpointingTests.CheckpointBatchTest
22:44:36.0911952: Begin Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.CheckpointingTests.CheckpointEventTest on .NETFramework,Version=v4.5.1
  X Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.CheckpointingTests.CheckpointBatchTest [10s 20ms]
  Error Message:
   Unexpected change in sequence number from 800 to 791
Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.CheckpointingTests.CheckpointBatchTest() in D:\a\1\AzureSDKEngSystem\Net\SourceDirectory\sdk\eventhub\Microsoft.Azure.EventHubs\tests\ServiceFabricProcessor\CheckpointingTests.cs:line 81
Results File: D:\a\1\AzureSDKEngSystem\Net\SourceDirectory\sdk\eventhub\Azure.Messaging.EventHubs\tests\TestResults\net461.trx
```

**To Reproduce**
Steps to reproduce the behavior: Queue PR Build

**Expected behavior**
Test fails randomly

**Comment by jsquire** [comment]
This test has been marked as flaky and will be skipped in builds going forward.   Tracking using  [#7435](https://github.com/Azure/azure-sdk-for-net/issues/7492)

**Comment by pakrym** [comment]
Now failing on netcoreapp:

```
 X Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.CheckpointingTests.CheckpointBatchTest [5s 56ms]
  Error Message:
   Unexpected change in sequence number from 290 to 281
Expected: True
Actual:   False
  Stack Trace:
     at Microsoft.Azure.EventHubs.Tests.ServiceFabricProcessor.CheckpointingTests.CheckpointBatchTest() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\tests\ServiceFabricProcessor\CheckpointingTests.cs:line 81

``

**Comment by jsquire** [comment]
Looks like the skip was removed; marked again and updated the issue tracking Service Fabric Processor test issues.   See #9799

**Comment by jsquire** [comment]
Closing this as #9799 has merged and the test should no longer be active.
