### ISSUE TITLE
[BUG] FrontDoor EnableHttps fails with TLS version 1.2

### ISSUE THREAD

**Issue by xenalite** [Azure/azure-sdk-for-net#7509]
**Describe the bug**
When EnableHttps action is called on Front Door frontend endpoint with MinimumTlsVersion specified as 1.2, the call fails with a 500 internal server error.

***Exception or Stack Trace***
```
Microsoft.Azure.Management.FrontDoor.Models.ErrorResponseException: Operation returned an invalid status code 'InternalServerError'
   at Microsoft.Azure.Management.FrontDoor.FrontendEndpointsOperations.BeginEnableHttpsWithHttpMessagesAsync(String resourceGroupName, String frontDoorName, String frontendEndpointName, CustomHttpsConfiguration customHttpsConfiguration, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.FrontDoor.FrontendEndpointsOperations.EnableHttpsWithHttpMessagesAsync(String resourceGroupName, String frontDoorName, String frontendEndpointName, CustomHttpsConfiguration customHttpsConfiguration, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.FrontDoor.FrontendEndpointsOperationsExtensions.EnableHttpsAsync(IFrontendEndpointsOperations operations, String resourceGroupName, String frontDoorName, String frontendEndpointName, CustomHttpsConfiguration customHttpsConfiguration, CancellationToken cancellationToken)
   at Microsoft.Azure.Management.FrontDoor.FrontendEndpointsOperationsExtensions.EnableHttps(IFrontendEndpointsOperations operations, String resourceGroupName, String frontDoorName, String frontendEndpointName, CustomHttpsConfiguration customHttpsConfiguration)
   at (...)
```

**To Reproduce**
Execute `EnableHttps` action using code snippet below.

***Code Snippet***
```
var httpsConfig = new CustomHttpsConfiguration
{
    MinimumTlsVersion = "1.2",
    CertificateSource = "AzureKeyVault",
    Vault = new KeyVaultCertificateSourceParametersVault(coreResources.KeyVault.Id),
    SecretName = GlobalConfig.HttpsCertificateSecretName,
    SecretVersion = coreResources
        .KeyVault
        .Secrets
        .GetByName(GlobalConfig.HttpsCertificateSecretName)
        .Inner
        .SecretIdentifier
        .Version
};

_frontDoorClient.FrontendEndpoints.EnableHttps(frontDoorResourceId.ResourceGroupName, frontDoorResourceId.Name, instanceName, httpsConfig);
```

**Expected behavior**
For the call to succeed.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2017
 - Microsoft.Azure.Management.FrontDoor 1.0.0

**Additional context**
Request URI:
```
PUT 
https://management.azure.com/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.Network/frontDoors/<fd>/frontendEndpoints/<endpoint>/enableHttps?api-version=2019-05-01
```

Request Body:
```
{
  "certificateSource": "AzureKeyVault",
  "minimumTlsVersion": "1.2",
  "keyVaultCertificateSourceParameters": {
    "vault": {
      "id": "/subscriptions/<subid>/resourceGroups/<rg>/providers/Microsoft.KeyVault/vaults/<kv>"
    },
    "secretName": "HttpsCertificate",
    "secretVersion": "aca4ba9a86b8490da93473e9eae3066e"
  },
  "protocolType": "ServerNameIndication"
}
```

When `MinimumTlsVersion` is specified as `1.0`, the call succeeds.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by uandrei** [comment]
Hi, 

Was wondering if there are any updates on this or at least some timelines when it's expected to go into production.

I'm a bit shocked that a GA service which is meant to be the first point of call with regards to traffic going into an application can have it's connection downgraded to TLSv1.0 and susceptible to all the vulnerabilities that come with it.

**Comment by xenalite** [comment]
This bug is no longer reproducible. You do not have to change SDK version.

**Comment by fpnewton** [comment]
I'm having this same issue.
