### ISSUE TITLE
Storage: QueueClient.GetAccessPolicy fails with null Start/ExpiryTime

### ISSUE THREAD

**Issue by tg-msft** [Azure/azure-sdk-for-net#7517]
"I found that this was caused by not having a start time and end time defined.  The Azure Portal does not require those, but the SDK requires them (they’re not nullable).  The access policies for file shares are set up to be nullable, so queues should be updated to be similar."

   at Azure.Storage.Queues.Models.AccessPolicy.FromXml(XElement element)
   at Azure.Storage.Queues.Models.SignedIdentifier.FromXml(XElement element)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Azure.Storage.Queues.QueueRestClient.Queue.GetAccessPolicyAsync_CreateResponse(Response response)
   at Azure.Storage.Queues.QueueRestClient.Queue.<GetAccessPolicyAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.Queues.QueueClient.<GetAccessPolicyInternal>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Azure.Storage.TaskExtensions.EnsureCompleted[T](Task`1 task)
   at Azure.Storage.Queues.QueueClient.GetAccessPolicy(CancellationToken cancellationToken)

**Comment by ShivangiReja** [comment]
Closed with https://github.com/Azure/azure-sdk-for-net/pull/7979
