### ISSUE TITLE
[Bug][Storage] FileClient.Upload() unit tests fire diagnostic warning

### ISSUE THREAD

**Issue by seanmcc-msft** [Azure/azure-sdk-for-net#7608]
[Test]
        public async Task UploadRangeFromUrlAsync()
        {
            var shareName = this.GetNewShareName();
            using (this.GetNewShare(out var share, shareName))
            {
                // Arrange
                var directoryName = this.GetNewDirectoryName();
                var directory = this.InstrumentClient(share.GetDirectoryClient(directoryName));
                await directory.CreateAsync();

                var fileName = this.GetNewFileName();
                var data = this.GetRandomBuffer(Constants.KB);
                var sourceFile = this.InstrumentClient(directory.GetFileClient(fileName));
                await sourceFile.CreateAsync(maxSize: 1024);
                using (var stream = new MemoryStream(data))
                {
                    await sourceFile.UploadAsync(stream); // Exception thrown here
                }
            }
        }

 UploadRangeFromUrlAsync
   Source: FileClientTests.cs line: 958
   Duration: 18 sec

  Message: 
    System.InvalidOperationException : Expected diagnostic event not fired Azure.Storage.Files.FileClient.Upload.Start 
        fired events [Azure.Storage.Files.FileClient.UploadRange.Start, ], [Azure.Storage.Files.FileClient.UploadRange.Stop, ] 
        You may have forgotten to set your operationId to Azure.Storage.Files.FileClient.Upload.Start in UploadAsync or applied the Azure.Core.ForwardsClientCallsAttribute to UploadAsync.
  Stack Trace: 
    at DiagnosticScopeValidatingInterceptor.Intercept(IInvocation invocation) in DiagnosticScopeValidatingInterceptor.cs line: 60
    at AbstractInvocation.Proceed()
    at FileClientProxy.UploadAsync(Stream content, IProgress`1 progressHandler, CancellationToken cancellationToken)
    at FileClientTests.UploadRangeFromUrlAsync() in FileClientTests.cs line: 974
    at GenericAdapter`1.GetResult() in TaskAwaitAdapter.cs line: 99
    at AsyncToSyncAdapter.Await(Func`1 invoke) in AsyncToSyncAdapter.cs line: 60
    at TestMethodCommand.Execute(TestExecutionContext context) in TestMethodCommand.cs line: 64
    at <>c__DisplayClass1_0.<Execute>b__0() in BeforeAndAfterTestCommand.cs line: 58
    at BeforeAndAfterTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action) in BeforeAndAfterTestCommand.cs line: 73

**Comment by tg-msft** [comment]
This is an issue when running unit tests, not with `FileClient.UploadAsync`.  The fix is in the error message:

> You may have forgotten to set your operationId to Azure.Storage.Files.FileClient.Upload.Start in UploadAsync or **applied the Azure.Core.ForwardsClientCallsAttribute to UploadAsync.**
