### ISSUE TITLE
[Flaky Test] SubscribePublishesEventsWithOneSubscriberAndMultipleBatches 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#7640]
``` 
X SubscribePublishesEventsWithOneSubscriberAndMultipleBatches [10s 337ms]
  Error Message:
   System.Threading.Tasks.TaskCanceledException : A task was canceled.
  Stack Trace:
     at Azure.Messaging.EventHubs.Core.CancellationTokenExtensions.ThrowIfCancellationRequested[T](CancellationToken instance) in /Users/vsts/agent/2.155.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/CancellationTokenExtensions.cs:line 28
   at Azure.Messaging.EventHubs.Core.ChannelReaderExtensions.EnumerateChannel[T](ChannelReader`1 reader, Nullable`1 maximumWaitTime, CancellationToken cancellationToken) in /Users/vsts/agent/2.155.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs/src/Core/ChannelReaderExtensions.cs:line 115
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.Messaging.EventHubs.Core.ChannelReaderExtensions.EnumerateChannel[T](ChannelReader`1 reader, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken) in /Users/vsts/agent/2.155.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubConsumer.cs:line 299
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken) in /Users/vsts/agent/2.155.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubConsumer.cs:line 299
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken) in /Users/vsts/agent/2.155.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs/src/EventHubConsumer.cs:line 307
   at System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore`1.GetResult(Int16 token)
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Tests.EventHubConsumerTests.SubscribePublishesEventsWithOneSubscriberAndMultipleBatches() in /Users/vsts/agent/2.155.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs/tests/EventHubConsumer/EventHubConsumerTests.cs:line 708
   at Azure.Messaging.EventHubs.Tests.EventHubConsumerTests.SubscribePublishesEventsWithOneSubscriberAndMultipleBatches() in /Users/vsts/agent/2.155.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs/tests/EventHubConsumer/EventHubConsumerTests.cs:line 708
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.BlockUntilCompleted()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Execution.SimpleWorkItem.PerformWork()
```

**Comment by jsquire** [comment]
Should be fixed by #7903
