### ISSUE TITLE
[Storage] IndexOutOfRangeException when UploadAsync() is cancelled

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#7820]
One time, I saw the following exception during an `UploadAsync()` perf test.  I believe this was caused by calling `UploadAsync(Stream, ParallelTransferOptions, CancellationToken)`, and having the token expire around the same time the upload would have completed.  `ParallelTransferOptions.MaximumThreadCount` was set to `1`, and `ParallelTransferOptions.MaximumTransferLength` was unset (so it should have used the default of 4MB).

I tried to repro this manually a few times but couldn't get the exception again.  To repro this consistently, you might need to run a lot of iterations where the cancellation is near the end of the upload.

```
/app/Azure.Storage.Blobs.PerfStress# dotnet run -c release --no-build -- upload -s 524288000 -p 1 -d 10 -t 1
=== Options ===
{
  "MaximumTransferLength": null,
  "MaximumThreadCount": 1,
  "Size": 524288000,
  "Async": true,
  "Duration": 10,
  "Parallel": 1
}

=== Progresss ===
0
0
0
0
0
0
0
0
0
Unhandled exception.
System.AggregateException: One or more errors occurred. (Index was outside the bounds of the array.)
 ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at System.Linq.Enumerable.SelectIPartitionIterator`2.PreallocatingToArray(Int32 count)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Azure.Storage.Blobs.BlobClient.<>c__DisplayClass19_0.<StagedUploadAsync>g__CommitBlockListAsync|6(Boolean async, CancellationToken cancellation)
   at Azure.Storage.PartitionedUploader.UploadAsync[T,P](Func`1 uploadStreamAsync, Func`5 uploadPartitionAsync, Func`3 commitAsync, Func`2 uploadAsSinglePartition, Func`2 getStreamPartitioner, Int64 singleUploadThreshold, Nullable`1 parallelTransferOptions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadAsync(Stream content, Nullable`1 blobHttpHeaders, IDictionary`2 metadata, Nullable`1 blobAccessConditions, Nullable`1 customerProvidedKey, IProgress`1 progressHandler, Nullable`1 accessTier, Int64 singleBlockThreshold, ParallelTransferOptions parallelTransferOptions, Boolean async, CancellationToken cancellationToken)
   at Azure.Test.PerfStress.PerfStressProgram.RunLoopAsync(IPerfStressTest test, CancellationToken cancellationToken) in /app/Azure.Test.PerfStress/PerfStressProgram.cs:line 117
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Azure.Test.PerfStress.PerfStressProgram.Run(Type testType, PerfStressOptions options) in /app/Azure.Test.PerfStress/PerfStressProgram.cs:line 67
   at Azure.Test.PerfStress.PerfStressProgram.<>c__DisplayClass1_0.<Main>b__1(PerfStressOptions o) in /app/Azure.Test.PerfStress/PerfStressProgram.cs:line 30
   at CommandLine.ParserResultExtensions.WithParsed[T](ParserResult`1 result, Action`1 action)
   at Azure.Test.PerfStress.PerfStressProgram.Main(Assembly assembly, String[] args) in /app/Azure.Test.PerfStress/PerfStressProgram.cs:line 31
   at Azure.Storage.Blobs.PerfStress.Program.Main(String[] args) in /app/Azure.Storage.Blobs.PerfStress/Program.cs:line 10
```

**Comment by tg-msft** [comment]
Duplicate of #7983
