### ISSUE TITLE
[BUG] BlockBlobClient requires seekable streams

### ISSUE THREAD

**Issue by jaschrep-msft** [Azure/azure-sdk-for-net#7871]
**Describe the bug**
BlockBlobClient::UploadInternal() creates lambdas that call Seek() on the stream passed in. This stream can be one directly handed in by the customer, who may not have a seekable stream, and who has no available options that accept non-seekable streams

Additionally, this functionality is used by BlobClient, which is designed to upload much larger data streams than BlockBlobClient, making seekable streams even harder.

***Exception or Stack Trace***
```
Message: 
    System.NotSupportedException : Stream does not support seeking.
  Stack Trace: 
    at CryptoStream.Seek(Int64 offset, SeekOrigin origin)
    at NonDisposingStream.Seek(Int64 offset, SeekOrigin origin) in NonDisposingStream.cs line: 38
    at <>c__DisplayClass16_0.<UploadInternal>b__1() in BlockBlobClient.cs line: 560
    at ReliableOperation.DoAsync[T](Func`1 operation, Action reset, Action cleanup, Func`2 predicate, Int32 maximumRetries) in ReliableOperation.cs line: 72
    at ValueTask`1.get_Result()
    at BlockBlobClient.UploadInternal(Stream content, Nullable`1 blobHttpHeaders, IDictionary`2 metadata, Nullable`1 blobAccessConditions, Nullable`1 accessTier, IProgress`1 progressHandler, Boolean async, CancellationToken cancellationToken) in BlockBlobClient.cs line: 530
    at TaskExtensions.EnsureCompleted[T](Task`1 task) in TaskExtensions.cs line: 24
    at PartitionedUploader.UploadAsync[T,P](Func`1 uploadStreamAsync, Func`5 uploadPartitionAsync, Func`3 commitAsync, Func`2 uploadAsSinglePartition, Func`2 getStreamPartitioner, Int64 singleUploadThreshold, Nullable`1 parallelTransferOptions, Boolean async, CancellationToken cancellationToken) in PartitionedUploader.cs line: 83
    at TaskExtensions.EnsureCompleted[T](Task`1 task) in TaskExtensions.cs line: 24
    at BlobClient.StagedUploadAsync(Stream content, Nullable`1 blobHttpHeaders, IDictionary`2 metadata, Nullable`1 blobAccessConditions, IProgress`1 progressHandler, Nullable`1 accessTier, Int64 singleBlockThreshold, ParallelTransferOptions parallelTransferOptions, Boolean async, CancellationToken cancellationToken) in BlobClient.cs line: 807
    at TaskExtensions.EnsureCompleted[T](Task`1 task) in TaskExtensions.cs line: 24
    at BlobClient.Upload(Stream content, Nullable`1 blobHttpHeaders, IDictionary`2 metadata, Nullable`1 blobAccessConditions, IProgress`1 progressHandler, Nullable`1 accessTier, ParallelTransferOptions parallelTransferOptions, CancellationToken cancellationToken) in BlobClient.cs line: 501
    at BlobClient.Upload(Stream content, CancellationToken cancellationToken) in BlobClient.cs line: 317
    at BlobClient.Upload(Stream content) in BlobClient.cs line: 194
    at EncryptedBlockBlobClientTests.Upload(Int64 dataSize) in EncryptedBlockBlobClientTests.cs line: 130
```

**To Reproduce**
Call any upload method that accepts a Stream with a non-seekable stream.

***Code Snippet***
Add the code snippet that causes the issue.
https://github.com/Azure/azure-sdk-for-net/blob/323aa8266fbf649f157929c5d460ef0825c74dbc/sdk/storage/Azure.Storage.Blobs/src/BlockBlobClient.cs#L560

**Expected behavior**
Have the reasonably size-capped content stream buffered as it's consumed to allow seeking if needed.

**Setup (please complete the following information):**
 - OS: Windows 10
 - IDE : Visual Studio 2019
 - Encountered in commit 6bef5b2b7a5d6e9b0fe31927b9b15ca41a2a84aa

**Additional context**
Encountered when developing client-side encryption, by having BlobClient and PartitionedUploader consume a CryptoStream.

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by josh-endries** [comment]
I am having this problem right now in 12.6.0, however I am not using one of the stream overloads. This is my current code:

```
var blobClient = BlobContainerClient.GetBlobClient(Checkpoint.BlobName);
var response = await blobClient.DownloadAsync(CancellationToken).ConfigureAwait(false);
var blobContentStream = response.Value.Content;
var streamReader = new StreamReader(blobContentStream);
```

I get tons of `System.NotSupportedException` due to streams not supporting seek when it makes the `DownloadAsync` call, but it seems to work anyway in some scenarios. When I had this in an IAsyncEnumerable, where I would open the downloaded file and yield out lines, the exceptions happened and it would kill my app. Converting it to returning one line per call with a cursor works, albeit with the exceptions. I've tried various tweaks, such as using `Download`, non-await, etc. but the same thing happens.

Maybe it's due to the `StreamReader`, though the exception happens seemingly before it gets to that line...

**Comment by LordJZ** [comment]
I can also confirm I am getting `NotSupportedException` about seek from `Download`/`DownloadAsync`, but cannot repro on a clean solution. Had to revert to older versions of the SDK.

**Comment by JimSuplizio** [comment]
Hi @jaschrep-msft, we deeply appreciate your input into this project. Regrettably, this issue has remained inactive for over 2 years, leading us to the decision to close it. We've implemented this policy to maintain the relevance of our issue queue and facilitate easier navigation for new contributors. If you still believe this topic requires attention, please feel free to create a new issue, referencing this one. Thank you for your understanding and ongoing support.
