### ISSUE TITLE
[BUG] ServiceFabricProcessor throws an unexpected exception

### ISSUE THREAD

**Issue by dmytro-gokun** [Azure/azure-sdk-for-net#7933]
1. ProcessErrorAsync is called with the following exception:

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: '$cbs'.
   at Microsoft.Azure.Amqp.AmqpCbsLink.BeginSendToken(ICbsTokenProvider tokenProvider, Uri namespaceAddress, String audience, String resource, String[] requiredClaims, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__0(AsyncCallback c, Object s)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at Microsoft.Azure.Amqp.TaskHelpers.CreateTask[T](Func`3 begin, Func`2 end, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at Microsoft.Azure.EventHubs.PartitionReceiver.ReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.ReceivePumpAsync(CancellationToken cancellationToken, Boolean invokeWhenNoEvents)
```

2. CloseAsync is called with Reason = Cancelled

3. ServiceFabricProcessor.RunAsync throws 

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: '$cbs'.
   at Microsoft.Azure.EventHubs.ServiceFabricProcessor.ServiceFabricProcessor.RunAsync(CancellationToken fabricCancellationToken)
   at MyClass.RunAsync(CancellationToken ct) in '...'

4. I need to restart the replica etc.

```

I might be wrong here, but it looks something wrong is going here. ObjectDisposedException looks like a bug hidden somewhere inside of this code. Correct me if i am wrong and this behavior is okay.

**Comment by JamesBirdsall** [comment]
@dmytro-gokun I agree, that doesn't look right. Do you know if the cancellation token is cancelled when this happens?

**Comment by dmytro-gokun** [comment]
@JamesBirdsall Unfortunately, i do not know. I will add this information to the log and, if this happens again, i will know.

**Comment by nrandell** [comment]
I've just seen a similar occurence using the latest `Azure.Messaging.EventHubs` `5.0.0-preview.4`

I know for a fact that the cancellation token passed in hadn't been cancelled as I cancelled it this morning and everything else cancelled and exited correctly.

```
System.ObjectDisposedException: Cannot access a disposed object.
Object name: '$cbs'.
   at Microsoft.Azure.Amqp.AmqpCbsLink.BeginSendToken(ICbsTokenProvider tokenProvider, Uri namespaceAddress, String audience, String resource, String[] requiredClaims, TimeSpan timeout, AsyncCallback callback, Object state)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__0(AsyncCallback c, Object s)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at Microsoft.Azure.Amqp.TaskHelpers.CreateTask[T](Func`3 begin, Func`2 end, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at TrackOne.Amqp.AmqpPartitionReceiver.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at TrackOne.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at TrackOne.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at TrackOne.PartitionReceiver.ReceiveAsync(Int32 maxMessageCount, Nullable`1 waitTime)
   at Azure.Messaging.EventHubs.Compatibility.TrackOneEventHubConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConsumer.<>c__DisplayClass50_0.<<StartBackgroundChannelPublishingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Azure.Messaging.EventHubs.Core.ChannelReaderExtensions.EnumerateChannel[T](ChannelReader`1 reader, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+MoveNext()
   at Azure.Messaging.EventHubs.Core.ChannelReaderExtensions.EnumerateChannel[T](ChannelReader`1 reader, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+MoveNext()
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+MoveNext()
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+MoveNext()
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at TTLiveData.Shared.EventHubSource`1.ReceiveFromPartition(EventHubClient client, String partitionId, ChannelWriter`1 channelWriter, CancellationToken ct) in /home/vsts/work/1/s/TTLiveData.Shared/EventHubSource.cs:line 69
   at TTLiveData.Shared.EventHubSource`1.ReceiveFromPartition(EventHubClient client, String partitionId, ChannelWriter`1 channelWriter, CancellationToken ct) in /home/vsts/work/1/s/TTLiveData.Shared/EventHubSource.cs:line 69
   at TTLiveData.Shared.EventHubSource`1.ReceiveFromPartition(EventHubClient client, String partitionId, ChannelWriter`1 channelWriter, CancellationToken ct) in /home/vsts/work/1/s/TTLiveData.Shared/EventHubSource.cs:line 69
```
After that, I try to get events again and I get an error saying `Can't create session when the connection is closing.`

```
System.InvalidOperationException: Can't create session when the connection is closing.
   at Microsoft.Azure.Amqp.AmqpConnection.AddSession(AmqpSession session, Nullable`1 channel)
   at Microsoft.Azure.Amqp.AmqpCbsLink.OpenCbsRequestResponseLinkAsyncResult.GetAsyncSteps()+MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.AmqpCbsLink.EndCreateCbsLink(IAsyncResult result)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.AmqpCbsLink.EndSendToken(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at TrackOne.Amqp.AmqpPartitionReceiver.CreateLinkAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at TrackOne.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at TrackOne.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at TrackOne.PartitionReceiver.ReceiveAsync(Int32 maxMessageCount, Nullable`1 waitTime)
   at Azure.Messaging.EventHubs.Compatibility.TrackOneEventHubConsumer.ReceiveAsync(Int32 maximumMessageCount, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubConsumer.<>c__DisplayClass50_0.<<StartBackgroundChannelPublishingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Channels.AsyncOperation`1.GetResult(Int16 token)
   at Azure.Messaging.EventHubs.Core.ChannelReaderExtensions.EnumerateChannel[T](ChannelReader`1 reader, Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.AmqpCbsLink.EndSendToken(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.EventHubConsumer.SubscribeToEvents(Nullable`1 maximumWaitTime, CancellationToken cancellationToken)+MoveNext()
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at TTLiveData.Shared.EventHubSource`1.ReceiveFromPartition(EventHubClient client, String partitionId, ChannelWriter`1 channelWriter, CancellationToken ct) in C:\Users\nick\Source\Customers\TowerTransit\TTLiveData\TTLiveData.Shared\EventHubSource.cs:line 71
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at TTLiveData.Shared.EventHubSource`1.ReceiveFromPartition(EventHubClient client, String partitionId, ChannelWriter`1 channelWriter, CancellationToken ct) in C:\Users\nick\Source\Customers\TowerTransit\TTLiveData\TTLiveData.Shared\EventHubSource.cs:line 71
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at TTLiveData.Shared.EventHubSource`1.ReceiveFromPartition(EventHubClient client, String partitionId, ChannelWriter`1 channelWriter, CancellationToken ct) in C:\Users\nick\Source\Customers\TowerTransit\TTLiveData\TTLiveData.Shared\EventHubSource.cs:line 71
   at TrackOne.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at TrackOne.Amqp.AmqpPartitionReceiver.OnReceiveAsync(Int32 maxMessageCount, TimeSpan waitTime)
   at TrackOne.PartitionReceiver.ReceiveAsync(Int32 maxMessageCount, Nullable`1 waitTime)
```

**Comment by AliGuemues** [comment]
Any updates on this?

**Comment by dmytro-gokun** [comment]
I did not see this exception for last 3 months. I think it can be safely closed.
