### ISSUE TITLE
[P1] [Stress] [Storage] UploadAsync() throws array index exception

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#7983]
## Overview ##
While running a 60-second perf test of `UploadAsync()` with 8 parallel uploads and a 1 GB blob, the following exception was thrown.  Out of 3 perf runs, 2 runs failed with this exception and 1 run succeeded.  The exceptions seems to be thrown at the very end of the perf test, when the `CancellationToken` passed to `UploadAsync()` becomes canceled.

## Root Cause ##
Skimming the code, the root cause might be a race condition where `blockMap` is modified during `CommitBlockListAsync()`:

https://github.com/Azure/azure-sdk-for-net/blob/e70ca70406f81781de0edf795170086786555c49/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L989
https://github.com/Azure/azure-sdk-for-net/blob/e70ca70406f81781de0edf795170086786555c49/sdk/storage/Azure.Storage.Blobs/src/BlobClient.cs#L1045

## Repro Steps ##
1. Create `CancellationToken` with a 60-second duration.
2. Call `UploadAsync(CancellationToken)` in a loop with a 1 GB blob and a maximum of 8 in-flight parallel uploads.
3. Wait 60 seconds for the `CancellationToken` to be canceled.

## Exception ##
```
Unhandled exception. System.ArgumentException: The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.
   at System.Collections.Concurrent.ConcurrentDictionary`2.System.Collections.Generic.ICollection<System.Collections.Generic.KeyValuePair<TKey,TValue>>.CopyTo(KeyValuePair`2[] array, Int32 index)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.OrderedEnumerable`1.GetEnumerator()+MoveNext()
   at System.Linq.Enumerable.SelectIPartitionIterator`2.PreallocatingToArray(Int32 count)
   at System.Linq.Enumerable.SelectIPartitionIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Azure.Storage.Blobs.BlobClient.<>c__DisplayClass19_0.<StagedUploadAsync>g__CommitBlockListAsync|6(Boolean async, CancellationToken cancellation)
   at Azure.Storage.PartitionedUploader.UploadAsync[T,P](Func`1 uploadStreamAsync, Func`5 uploadPartitionAsync, Func`3 commitAsync, Func`2 uploadAsSinglePartition, Func`2 getStreamPartitioner, Int64 singleUploadThreshold, Nullable`1 parallelTransferOptions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobClient.StagedUploadAsync(Stream content, Nullable`1 blobHttpHeaders, IDictionary`2 metadata, Nullable`1 blobAccessConditions, IProgress`1 progressHandler, Nullable`1 accessTier, Int64 singleBlockThreshold, ParallelTransferOptions parallelTransferOptions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.PerfStress.UploadTest.RunAsync(CancellationToken cancellationToken) in /app/net/Azure.Storage.Blobs.PerfStress/UploadTest.cs:line 32
   at Azure.Test.PerfStress.PerfStressProgram.RunLoopAsync(IPerfStressTest test, CancellationToken cancellationToken) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 159
   at Azure.Test.PerfStress.PerfStressProgram.Run(Type testType, PerfStressOptions options) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 101
   at Azure.Test.PerfStress.PerfStressProgram.Run(Type testType, PerfStressOptions options) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 113
   at Azure.Test.PerfStress.PerfStressProgram.Run(Type testType, PerfStressOptions options) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 121
   at Azure.Test.PerfStress.PerfStressProgram.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext() in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Test.PerfStress.PerfStressProgram.Main(Assembly assembly, String[] args) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 26
   at Azure.Storage.Blobs.PerfStress.Program.Main(String[] args) in /app/net/Azure.Storage.Blobs.PerfStress/Program.cs:line 10
   at Azure.Storage.Blobs.PerfStress.Program.<Main>(String[] args)
```

**Comment by tg-msft** [comment]
Removing blocking-release as it's not an API breaking change

**Comment by Petermarcu** [comment]
I see a comment that the blocking-release label was getting removed but it was added back. Is this still blocking?
