### ISSUE TITLE
[Stress] [Storage] RequestFailedException should be retriable

### ISSUE THREAD

**Issue by mikeharder** [Azure/azure-sdk-for-net#7987]
While testing downloads of a 1 GB blob with version `12.0.0-preview.3`, an `HttpRequestException` was thrown.  After #7669, this should be wrapped in a `RequestFailedException`, which is one improvement.  However, I still think the exception will be fatal rather than retried, assuming this is the relevant code:

https://github.com/Azure/azure-sdk-for-net/blob/ac66dfbe3912c3e4a8716ae1b92fc98ea5b072b2/sdk/core/Azure.Core/src/Pipeline/ResponseClassifier.cs#L22-L25

If this is correct, I think `RequestFailedException` should be included in `IsRetriableException()`.

CC: @tg-msft 

## Stack Trace
```
Unhandled exception. System.Net.Http.HttpRequestException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpPipelineMessage message)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.BufferResponsePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.HttpPipeline.SendRequestAsync(Request request, Boolean bufferResponse, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobRestClient.Blob.DownloadAsync(HttpPipeline pipeline, Uri resourceUri, String snapshot, Nullable`1 timeout, String range, String leaseId, Nullable`1 rangeGetContentHash, Nullable`1 rangeGetContentCRC64, String encryptionKey, String encryptionKeySha256, Nullable`1 encryptionAlgorithm, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, String requestId, Boolean async, Boolean bufferResponse, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.StartDownloadAsync(HttpRange range, Nullable`1 accessConditions, Nullable`1 customerProvidedKey, Boolean rangeGetContentHash, Int64 startOffset, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadInternal(HttpRange range, Nullable`1 accessConditions, Nullable`1 customerProvidedKey, Boolean rangeGetContentHash, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Specialized.BlobBaseClient.DownloadAsync(HttpRange range, Nullable`1 accessConditions, Nullable`1 customerProvidedKey, Boolean rangeGetContentHash, CancellationToken cancellationToken)
```

**Comment by mikeharder** [comment]
Using the latest dev build `12.0.0-dev.20191008.1`, I hit this again during a `GetBlobs()` test, and verified the exception is not retried.

```
Unhandled exception. Azure.RequestFailedException: Connection reset by peer
 ---> System.Net.Http.HttpRequestException: Connection reset by peer
 ---> System.Net.Sockets.SocketException (104): Connection reset by peer
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean allowHttp2, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.GetHttpConnectionAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpPipelineMessage message)
   --- End of inner exception stack trace ---
   at Azure.Core.Pipeline.HttpClientTransport.ProcessAsync(HttpPipelineMessage message)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessNextAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.RequestActivityPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean isAsync)
   at Azure.Core.Pipeline.BufferResponsePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.RetryPolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline, Boolean async)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Core.Pipeline.SynchronousHttpPipelinePolicy.ProcessAsync(HttpPipelineMessage message, ReadOnlyMemory`1 pipeline)
   at Azure.Storage.Blobs.BlobRestClient.Container.ListBlobsFlatSegmentAsync(HttpPipeline pipeline, Uri resourceUri, String prefix, String marker, Nullable`1 maxresults, IEnumerable`1 include, Nullable`1 timeout, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.BlobContainerClient.GetBlobsInternal(String marker, BlobTraits traits, BlobStates states, String prefix, Nullable`1 pageSizeHint, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Blobs.Models.GetBlobsAsyncCollection.GetNextPageAsync(String continuationToken, Nullable`1 pageSizeHint, Boolean isAsync, CancellationToken cancellationToken)

   at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.GetAsyncEnumerator(CancellationToken cancellationToken)+MoveNext()
   at Azure.Storage.StorageCollectionEnumerator`1.StorageAsyncPageable.GetAsyncEnumerator(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.Storage.Blobs.PerfStress.GetBlobsTest.RunAsync(CancellationToken cancellationToken) in /app/net/Azure.Storage.Blobs.PerfStress/GetBlobsTest.cs:line 37
   at Azure.Storage.Blobs.PerfStress.GetBlobsTest.RunAsync(CancellationToken cancellationToken) in /app/net/Azure.Storage.Blobs.PerfStress/GetBlobsTest.cs:line 37
   at Azure.Test.PerfStress.PerfStressProgram.RunLoopAsync(IPerfStressTest test, CancellationToken cancellationToken) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 159
   at Azure.Test.PerfStress.PerfStressProgram.Run(Type testType, PerfStressOptions options) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 101
   at Azure.Test.PerfStress.PerfStressProgram.Run(Type testType, PerfStressOptions options) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 113
   at Azure.Test.PerfStress.PerfStressProgram.Run(Type testType, PerfStressOptions options) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 121
   at Azure.Test.PerfStress.PerfStressProgram.<>c__DisplayClass2_0.<<Main>b__1>d.MoveNext() in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 31
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Test.PerfStress.PerfStressProgram.Main(Assembly assembly, String[] args) in /app/net/Azure.Test.PerfStress/PerfStressProgram.cs:line 26
   at Azure.Storage.Blobs.PerfStress.Program.Main(String[] args) in /app/net/Azure.Storage.Blobs.PerfStress/Program.cs:line 10
   at Azure.Storage.Blobs.PerfStress.Program.<Main>(String[] args)
```
