### ISSUE TITLE
[BUG] Getting token with VNET

### ISSUE THREAD

**Issue by lcarli** [Azure/azure-sdk-for-net#8064]
We are using one web app + AKV + VNET integration between those services.
Without VNET works fine but when we turn it on.. we're not capable to fetch secrets. 

I downloaded this project and put trace everywhere.

I fell inside the method to get the token. So, inside the class **KeyVaultCredential**, when we try to **ProcessHttpRequestAsync** he stop and show me the exception below.

**Stack Trace**
```
Credentials.ProcessHttpRequestAsync
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at Microsoft.Rest.RetryDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.FinishSendAsyncBuffered(Task`1 sendTask, HttpRequestMessage request, CancellationTokenSource cts, Boolean disposeCts)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\{user}\Downloads\azure-sdk-for-net-master\sdk\keyvault\Microsoft.Azure.KeyVault\src\Customized\Authentication\KeyVaultCredential.cs:line 145
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken) in C:\Users\{user}\Downloads\azure-sdk-for-net-master\sdk\keyvault\Microsoft.Azure.KeyVault\src\Customized\Authentication\KeyVaultCredential.cs:line 167
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretWithHttpMessagesAsync(String vaultBaseUrl, String secretName, String secretVersion, Dictionary`2 customHeaders, CancellationToken cancellationToken) in C:\Users\{user}\Downloads\azure-sdk-for-net-master\sdk\keyvault\Microsoft.Azure.KeyVault\src\Generated\KeyVaultClient.cs:line 5089

```

**To Reproduce**
Create ANY web app, ANY keyvault, ANY VNET. Integrate everything.

***Code Snippet***
The method that I used to call Azure Key Vault (using this SDK)
```csharp
var azureServiceTokenProvider1 = new AzureServiceTokenProvider();
var kv = new KeyVaultClient(new KeyVaultClient.AuthenticationCallback(azureServiceTokenProvider1.KeyVaultTokenCallback));
var secretIdentifier = $"{url}";
SecretBundle secret = await kv.GetSecretAsync(secretIdentifier: secretIdentifier).ConfigureAwait(false);
return secret.Value;
```

------------------------------------------------------------

CLASS KeyVaultCredential : ServiceClientCredentials
(line 124)
```csharp
using (var r = new HttpRequestMessage(request.Method, request.RequestUri))
{                    
   response = await client.SendAsync(r).ConfigureAwait(false);
}
```

**Expected behavior**

**Setup (please complete the following information):**
- Azure Web App
- Azure Key Vault
- Azure Virtual Network

**Comment by KarenHammons** [comment]
Hello @lcarli, It's not clear if you are securing access to KeyVault using service endpoints.  If so you must explicitly allow the subnet in which Weapps is deployed in to gain access.  Please do let us know if that resolves the issue.

**Comment by lcarli** [comment]
Hi, @KarenHammons. 

I'm trying to secure my Keyvault to givin access just thru the VNET. 

I've one webapp attached to this VNET using the only one subnet I have (default) as you can see here:

[WebApp](https://1drv.ms/u/s!AkInlHYUNYMLpdE-_w22wpDVJgnKkg?e=FSvlDR)

I have one VNET with one subnet only as you can see above: (and all the service endpoints related)

[VNET](https://1drv.ms/u/s!AkInlHYUNYMLpdE8RaF9mDCz6CkCdQ?e=488qBC)
[VNET-Subnet](https://1drv.ms/u/s!AkInlHYUNYMLpdE9hhDwvQ1nChssIQ?e=bri3bM)

And I have on KeyVult where I attached this VNET and subnet, as you can see here:

[AKV](https://1drv.ms/u/s!AkInlHYUNYMLpdE7ImrJSz1tKjcjgQ?e=ReHRuR)

Did I missing something?

Thank you already,

**Comment by lcarli** [comment]
Hi, @KarenHammons and team!

Have you guy any news about this problem?

**Comment by KarenHammons** [comment]
Hi @lcarli we did discuss further.  I would encourage you to open a support case for this issue if you haven't already.  If you have, please paste the SR # here and I can follow up on it.

**Comment by allegradomel** [comment]
#please-close

**Comment by KarenHammons** [comment]
Closed.
