### ISSUE TITLE
withParameters not working properly for ARM deployments

### ISSUE THREAD

**Issue by nakhanha** [Azure/azure-sdk-for-net#8314]
``` 
Message=The request content was invalid and could not be deserialized: 'Error converting value "https://schema.management.azure.com/schemas/2015-01-01/deploymentParameters.json#" to type 'Microsoft.WindowsAzure.ResourceStack.Frontdoor.Data.Definitions.DeploymentParameterDefinition'. Path 'properties.parameters.$schema', line 8, position 100.'.
  Source=Microsoft.Azure.Management.ResourceManager.Fluent
  StackTrace:
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<BeginCreateOrUpdateWithHttpMessagesAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperations.<CreateOrUpdateWithHttpMessagesAsync>d__7.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentsOperationsExtensions.<CreateOrUpdateAsync>d__2.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.CreateResource()
   at Microsoft.Azure.Management.ResourceManager.Fluent.DeploymentImpl.Create()
```

**This is my code**

```csharp
            string JSONresult = JsonConvert.SerializeObject(rootObj);
  var deployment = azure.Deployments.Define("myDeployment")
                .WithExistingResourceGroup(groupName)
                .WithTemplateLink(templatePath, "1.0.0.1")
                 .WithParameters(JSONresult)
                .WithMode(Microsoft.Azure.Management.ResourceManager.Fluent.Models.DeploymentMode.Incremental)
                .Create();
```

This error only happens when I pass object or JSON String. Doesnt happen for withParameterLink

**Comment by nakhanha** [comment]
ARM deployment not working with string or property

**Comment by isra-fel** [comment]
Sorry for late response. @weidongxu-microsoft could you please share some insights? Thank you.

**Comment by weidongxu-microsoft** [comment]
@nakhanha 
Could you provide a sample of the json string?

**Comment by sandrastanisavljevikj** [comment]
Is there any update on this one, facing the same issue here..

**Comment by nakhanha** [comment]
It was a issue with my template.json after fixing it issue was resolved.
