### ISSUE TITLE
[Flaky test] CreateEpochReceiverAfterNonEpochReceiver test is flaky

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8612]
System.TimeoutException : The operation did not complete within the allocated time 00:00:30 for object request3.

```
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)

   at Microsoft.Azure.Amqp.AmqpCbsLink.SendTokenAsyncResult.<>c__DisplayClass13_0.<GetAsyncSteps>b__3(SendTokenAsyncResult thisPtr, IAsyncResult r)

   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)

   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)

   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<CreateLinkAsync>d__15.MoveNext() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\src\Amqp\AmqpPartitionReceiver.cs:line 182

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.<OnCreateAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.Azure.Amqp.Singleton`1.<GetOrCreateAsync>d__13.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\src\Amqp\AmqpPartitionReceiver.cs:line 66

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at Microsoft.Azure.EventHubs.Amqp.AmqpPartitionReceiver.<OnReceiveAsync>d__13.MoveNext() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\src\Amqp\AmqpPartitionReceiver.cs:line 121

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()

   at Microsoft.Azure.EventHubs.PartitionReceiver.<ReceiveAsync>d__30.MoveNext() in D:\a\1\s\sdk\eventhub\Microsoft.Azure.EventHubs\src\PartitionReceiver.cs:line 201

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()

   at Microsoft.Azure.EventHubs.Tests.Client.ReceiverTests.<CreateEpochReceiverAfterNonEpochReceiver>d__
```

**Comment by pakrym** [comment]
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=179012&view=ms.vss-test-web.build-test-results-tab&runId=6610340&resultId=100145&paneView=debug

**Comment by serkantkaraca** [comment]
Assuming this is fixed by https://github.com/Azure/azure-sdk-for-net/pull/7014. Please reactivate if this is not the case.
