### ISSUE TITLE
[BUG] EventHubProducerClient.SendAsync using TokenCredential fails with AADSTS70011 ... The scope Send is not valid

### ISSUE THREAD

**Issue by stefando** [Azure/azure-sdk-for-net#8723]
**Describe the bug**
EventHubProducerClient.SendAsync with TokenProvider fails with:
"error":"invalid_scope",
"error_description":"AADSTS70011: The provided request must include a 'scope' input parameter. The provided value for the input parameter 'scope' is not valid. The scope Send is not valid.

***Exception or Stack Trace***
```
at Azure.Identity.AadIdentityClient.SendAuthRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Identity.AadIdentityClient.AuthenticateAsync(String tenantId, String clientId, String clientSecret, String[] scopes, CancellationToken cancellationToken)
   at Azure.Identity.ClientSecretCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at Azure.Identity.ExtendedAccessToken.GetTokenOrThrow()
   at Azure.Identity.EnvironmentCredential.GetTokenAsync(TokenRequestContext requestContext, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.CbsTokenProvider.GetTokenAsync(Uri namespaceAddress, String appliesTo, String[] requiredClaims)
   at Microsoft.Azure.Amqp.TaskHelpers.EndAsyncResult(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.<>c.<CallTask>b__24_1(TIteratorAsyncResult thisPtr, IAsyncResult r)
   at Microsoft.Azure.Amqp.IteratorAsyncResult`1.StepCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Azure.Amqp.ExceptionDispatcher.Throw(Exception exception)
   at Microsoft.Azure.Amqp.AsyncResult.End[TAsyncResult](IAsyncResult result)
   at Microsoft.Azure.Amqp.AsyncResult`1.End(IAsyncResult asyncResult)
   at Microsoft.Azure.Amqp.AmqpCbsLink.EndSendToken(IAsyncResult result)
   at Microsoft.Azure.Amqp.AmqpCbsLink.<>c__DisplayClass4_0.<SendTokenAsync>b__1(IAsyncResult a)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.CreateSendingLinkAsync(AmqpConnection connection, Uri endpoint, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpConnectionScope.OpenProducerLinkAsync(String partitionId, TimeSpan timeout, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.CreateLinkAndEnsureProducerStateAsync(String partitionId, TimeSpan timeout, CancellationToken cancellationToken)
   at Microsoft.Azure.Amqp.FaultTolerantAmqpObject`1.OnCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Microsoft.Azure.Amqp.Singleton`1.GetOrCreateAsync(TimeSpan timeout)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(Func`1 messageFactory, String partitionKey, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(Func`1 messageFactory, String partitionKey, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.Amqp.AmqpProducer.SendAsync(IEnumerable`1 events, SendOptions sendOptions, CancellationToken cancellationToken)
   at Azure.Messaging.EventHubs.EventHubProducerClient.SendAsync(IEnumerable`1 events, SendOptions options, CancellationToken cancellationToken)
```

**To Reproduce**
1. Credentials with the "Azure Event Hubs Data Owner" role for configured EventHub.
2. Successful call client.GetEventHubPropertiesAsync()
3. **Exception when trying to send data.**

***Code Snippet***
```csharp
var creds = new EnvironmentCredential();
await using (var client = new EventHubProducerClient(
  "<<myNs>>.servicebus.windows.net",
  "<<MyEh>>",
  creds))
{
  // This call works
  var properties = await client.GetEventHubPropertiesAsync();
  Console.WriteLine($"*** Hub \"{ properties.Name }\" reached successfully.");

  var bytes = await File.ReadAllBytesAsync(@"<<some bytes to send>>");
  var ed = new EventData(bytes);                
  await client.SendAsync(new[] {ed});
}
```

**Expected behavior**
Data sent to Event Hub.

**Setup (please complete the following information):**
  Win10
  dotnet core 3.0
  Azure.Identity **1.0.0**
  Azure.Messaging.EventHubs **5.0.0-preview.5**

**Additional context**
I can send the data via Microsoft.Azure.EventHubs 4.1.0, EventHubClient.CreateWithManagedIdentity() using the same credentials

**Comment by AlexGhiondea** [comment]
@stefando thanks for reporting this!

This looks like an issue we ran into already and that was supposed to be fixed.

@jsquire can you take a look?

**Comment by jsquire** [comment]
Thank you for bringing this to our attention, @stefando, and apologies for the difficulties.  I believe this has been fixed with [#8598](https://github.com/Azure/azure-sdk-for-net/pull/8598) which merged too late to make the Preview 5 build.   Our original fix missed two scenarios which it appears are triggered here.

I'm going to leave this open until the pending identity sample merges and proves to be stable with our nightly test runs.

**Comment by jsquire** [comment]
Hi @stefando.   I notice that you have re-opened this.  Could I ask if that was for tracking purposes or if you had new information that you wanted to share?

As mentioned, this is a known issue with the Preview 5 build.  The fix has been made and we now have coverage for principal-based authorization running as part of our nightly tests.   Unfortunately, the fix will not be available in an official package until our next release.  

You're welcome to run your scenario against the `master` branch code, if you'd like to validate before our next release.  If you choose to do so, we would very much appreciate your feedback on how things went.

**Comment by stefando** [comment]
I closed it before by mistake. It's just for tracking purposes.

**Comment by jsquire** [comment]
The preview 6 package of [Azure.Messaging.EventHubs](https://www.nuget.org/packages/Azure.Messaging.EventHubs/5.0.0-preview.6) has been published.  The fix that I spoke of is included there, and I've verified that our identity-based tests for inspecting the Event Hub, publishing events, and reading events are consistently passing.

Closing this out as resolved.  Please let us know if you experience any further issues.
