### ISSUE TITLE
ManagementClient.ManagementCertificates.Create throw an exception because of an http 201 response

### ISSUE THREAD

**Issue by liuhongbo** [Azure/azure-sdk-for-net#875]
Here is the code:

```
var p = new ManagementCertificateCreateParameters();
var x509 = new X509Certificate2(pfx, "test");
p.Data = x509.Export(X509ContentType.Cert, "test");
p.Thumbprint = x509.Thumbprint;
p.PublicKey = x509.PublicKey.EncodedKeyValue.RawData;
client.ManagementCertificates.Create(p);
```

ManagementCertificates.Create will throw an exception with the following stack information:

```
Microsoft.WindowsAzure.CloudException: Created
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Microsoft.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at   Microsoft.WindowsAzure.ManagementCertificateOperationsExtensions.Create(IManagementCertificateOperations operations, ManagementCertificateCreateParameters parameters)
   at ......
```

I used the fiddler to capture the http request and resonpse

The response looks like this:

```
HTTP/1.1 201 Created
Cache-Control: no-cache
Content-Length: 0
Location: https://management.core.windows.net/subscriptions/1600f73e-1406-4234-b701-3a585d8df7e8/certificates/848AA2451D8A54DD0B2907910CADE4E7209C7DAB
Server: 1.0.6198.176 (rd_rdfe_stable.141216-1945) Microsoft-HTTPAPI/2.0
x-ms-servedbyregion: ussouth2
x-ms-request-id: 1e7c03ce3490564e986ba14a6d993ffe
Date: Thu, 25 Dec 2014 03:55:51 GMT
```

So basically, the certificate is created successfully.  However,  the code in file azure-sdk-for-net/src/Management/Generated/ManagementCertificateOperations.cs

```
  if (statusCode != HttpStatusCode.OK)
  {
          cancellationToken.ThrowIfCancellationRequested();
          CloudException ex = CloudException.Create(httpRequest, requestContent, httpResponse, await httpResponse.Content.ReadAsStringAsync().ConfigureAwait(false));
          if (shouldTrace)
          {
              Tracing.Error(invocationId, ex);
          }
          throw ex;
    }
```

should change as  

```
if (statusCode != HttpStatusCode.Created)
...
```

**Comment by shahabhijeet** [comment]
please reopen if this is still an issue.
