### ISSUE TITLE
[BUG]AzureKeyValut Client issue

### ISSUE THREAD

**Issue by LeelaShivaPriyaAlluri** [Azure/azure-sdk-for-net#8831]
We are part of Microsoft Intune Team. We recently updated “Microsoft.Azure.KeyVault.KeyVaultClient” version from 3.0.3 to 3.0.4. With this update our deployments are failing with below error.

2019-11-18T17:12:29.5378011Z System.TypeLoadException: Method 'get_SerializationSettings' in type 'Microsoft.Azure.KeyVault.KeyVaultClient' from assembly 'Microsoft.Azure.KeyVault, Version=3.0.4.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' does not have an implementation.
2019-11-18T17:12:29.5378011Z    at Microsoft.Management.Services.Deployment.SfAppDeploy.Commands.SfAppDeployBaseCmdlet.Initialize()
2019-11-18T17:12:29.5378011Z    at System.Management.Automation.Cmdlet.DoBeginProcessing()
2019-11-18T17:12:29.5378011Z    at System.Management.Automation.CommandProcessorBase.DoBegin()

Can you please help us here?

**Comment by heaths** [comment]
On which version of Json .NET do you depend? At the time 3.0.4 was built, we depended on Newtonsoft.Json 10.0.3. Do you have that or newer installed into your project? If you do, another possibility is something another team hit: a version of Json .NET was in the GAC but specific for net35, which is lacking some types that were necessary. If you can, check that you're not picking up a GAC'd copy of Json .NET.

To see if another, older version is already loaded in PowerShell, run:
```powershell
[System.AppDomain]::CurrentDomain.GetAssemblies() | select FullName | sort FullName  
```

**Comment by heaths** [comment]
We'd be happy to look into this but will need more information. If you could supply the requested information and reopen the bug, we will take a look.
