### ISSUE TITLE
[Flaky test] ReadLastEnqueuedEventPropertiesDelegatesToTheConsumer 

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#8964]
```
  X ReadLastEnqueuedEventPropertiesDelegatesToTheConsumer [16ms]
  Error Message:
   Azure.Messaging.EventHubs.Errors.EventHubsClientClosedException : The Event Hub client responsible for this information has already been closed and cannot perform the requested operation. (The Event Hub client responsible for this information)
  Stack Trace:
     at Azure.Core.Argument.AssertNotClosed(Boolean wasClosed, String targetName) in /Users/runner/runners/2.160.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs.Shared/src/Core/Argument.cs:line 132
   at Azure.Messaging.EventHubs.PartitionContext.ReadLastEnqueuedEventProperties() in /Users/runner/runners/2.160.1/work/1/SourceDirWith49CharsLengthTestForLongPaths/sdk/eventhub/Azure.Messaging.EventHubs/src/PartitionContext.cs:line 51

```
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=201225&view=logs&j=9cfc3b0b-53b1-524f-85ed-0ef4880bef82&t=277ae693-9b68-5ef5-d666-bb5a558e8cc2&l=680

**Comment by jsquire** [comment]
I've not seen this fail locally, during CI, nor during the nightly runs.   Is there any additional information or context for consistent repro?

Was this a single failure or are you seeing this consistently?

**Comment by pakrym** [comment]
That's the only failure I've seen.

**Comment by jsquire** [comment]
Fair enough.   I'll give it a look in the next couple of days with other test stability work.

**Comment by jsquire** [comment]
Timings were adjusted with #9188, and I'd expect this to be stable.   Please reopen if you see flaky behavior continue.
