### ISSUE TITLE
[BUG] [Event Hubs Track 2] Exception when resuming processing from a checkpoint

### ISSUE THREAD

**Issue by ellismg** [Azure/azure-sdk-for-net#9213]
**Describe the bug**
With https://github.com/Azure/azure-sdk-for-net/pull/9166 we changed how we constructed the EventPosition when using data from a checkpoint.  Because `EventPosition.FromOffset()` returns an inclusive range, and we don't want to reprocess the last event, we add one to the offset.

However, in cases where you are resuming processing on a partition that has had no events sent to it since the last checkpoint operation, using this offset will cause the service to return an error, which we'll then pass to their error handler for a partition (and then we will close the partition)

***Exception or Stack Trace***
```
Error on Partition 1: System.ArgumentException: The supplied offset '13953' is invalid. The last offset in the system is '13952' TrackingId:1150026e-8d88-46f4-aecc-9aa8f97ad3ad_B6, SystemTracker:matell-eh-ns:eventhub:matell-eh-1~13107, Timestamp:2019-12-19T22:40:38 Reference:1ebf14fa-ce69-4e28-b040-363f3cf47b8d, TrackingId:102ae465-4152-4c65-8464-f25b35aa1831_B6, SystemTracker:matell-eh-ns:eventhub:matell-eh-1~13107|$default, Timestamp:2019-12-19T22:40:38 TrackingId:91e1ce3d33c241978084f6923ffc918a_G18, SystemTracker:gateway5, Timestamp:2019-12-19T22:40:38
   at Azure.Messaging.EventHubs.EventHubConsumerClient.<>c__DisplayClass46_0.<<PublishPartitionEventsToChannelAsync>g__performCleanup|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.EventHubConsumerClient.ReadEventsFromPartitionAsync(String partitionId, EventPosition startingPosition, ReadEventOptions readOptions, CancellationToken cancellationToken)+MoveNext()
   at Azure.Messaging.EventHubs.EventHubConsumerClient.ReadEventsFromPartitionAsync(String partitionId, EventPosition startingPosition, ReadEventOptions readOptions, CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Azure.Messaging.EventHubs.EventProcessorClient.<>c__DisplayClass94_0.<<RunPartitionProcessingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.EventProcessorClient.<>c__DisplayClass94_0.<<RunPartitionProcessingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.EventProcessorClient.<>c__DisplayClass94_0.<<RunPartitionProcessingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.EventProcessorClient.<>c__DisplayClass94_0.<<RunPartitionProcessingAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Azure.Messaging.EventHubs.EventProcessorClient.StopPartitionProcessingIfRunningAsync(String partitionId, ProcessingStoppedReason reason, CancellationToken cancellationToken)
```

**To Reproduce**
1. Make sure you have 5.0.0-dev.20191219.1 or later of the EventHub and EventHubProcessor libraries (you need the fix from #9166).
2. Publish some events to an event hub, and then stop the publishing
3. Construct a processor, read all the events and checkpoint each event.  Once done terminate.
4. Repeat step 3.  The expectation is that you don't see any exceptions but you also don't see the last event for each partition (the issue that #9166) was trying to fix.

**Comment by jsquire** [comment]
Well... that was unexpected.  My notes from conversations with the service team are either incorrect or the service is doing something unexpected.    I'll follow-up with the service team to confirm the behavior and make any necessary adjustments.

**Comment by jsquire** [comment]
I've reintroduced the concept of inclusive/exclusive for offsets and we're now using that instead of the "shift-by-one" technique.   This should be resolved, though we're pending a live test for the scenario due to some conflicting work.   We'll get that in as part of the ongoing processor test overhaul.

**Comment by ellismg** [comment]
Thanks, Jessie!
