### ISSUE TITLE
Cannot get or set ACL of Data Lake Gen2 filesystem root.

### ISSUE THREAD

**Issue by TakeshiMasukawa** [Azure/azure-sdk-for-net#9319]
I tried to get & set ACL of ADLS Gen2 filesystem root, but it doesn't work.

I tried the code below.
```code.cs
var sharedKeyCredential = new StorageSharedKeyCredential(storageAccountName, storageAccountKey);
var serviceClient = new DataLakeServiceClient(new Uri($"https://{storageAccountName}.dfs.core.windows.net"), sharedKeyCredential);
var fileSystemClient = serviceClient.GetFileSystemClient(containerName);
var directoryClient = fileSystemClient.GetDirectoryClient("");
var res = await directoryClient.GetAccessControlAsync();
```

This code throws the exception below.

Azure.RequestFailedException
ErroCode: 400
Message: `Value for one of the query parameters specified in the request URI is invalid.`
Stack trace:
```
   at Azure.Storage.Files.DataLake.DataLakeRestClient.Path.GetPropertiesAsync_CreateResponse(Response response)
   at Azure.Storage.Files.DataLake.DataLakeRestClient.Path.GetPropertiesAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, String requestId, Nullable`1 timeout, Nullable`1 action, Nullable`1 upn, String leaseId, Nullable`1 ifMatch, Nullable`1 ifNoneMatch, Nullable`1 ifModifiedSince, Nullable`1 ifUnmodifiedSince, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakePathClient.GetAccessControlInternal(Nullable`1 userPrincipalName, DataLakeRequestConditions conditions, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakePathClient.GetAccessControlAsync(Nullable`1 userPrincipalName, DataLakeRequestConditions conditions, CancellationToken cancellationToken)
   at b_ridgeAnalyticDbFunctions.Function.AddAclTest.Run(HttpRequest req, ILogger log) in C:\Users\masukawa\source\repos\b-ridgeAnalyticDbFunctions\b-ridgeAnalyticDbFunctions\Function\AddAclTest.cs:line 32
```

It seems send the request below.
```HEAD https://{storageAccountName}.dfs.core.windows.net/{containerName}?action=getAccessControl```

Via azure rest API, I can get ACL of filesystem root by the request below.
```HEAD https://{storageAccountName}.dfs.core.windows.net/{containerName}/?action=getAccessControl```

The difference is a slash after the container name.
How can I do this by the SDK?

**Comment by TakeshiMasukawa** [comment]
I could achieve my purpose by updating private field of "directoryClient" by reflection.

```
typeof(DataLakePathClient)
    .GetField("_dfsUri", BindingFlags.Instance | BindingFlags.NonPublic)
    .SetValue(directoryClient , new Uri(directoryClient .Uri.ToString()));
var res = await directoryClient.GetAccessControlAsync();
```

I hope I can do this without reflection.

**Comment by jsquire** [comment]
@AlexGhiondea: Would you be so kind as to help route this?

**Comment by seanmcc-msft** [comment]
Hi,

It appears this was an oversight on our part, I'll add DataLakeFileSystemClient.GetAccessControl(), .SetAccessControlList(), and .SetPermissions().

-Sean

**Comment by TakeshiMasukawa** [comment]
Thank you for considering my request!

**Comment by seanmcc-msft** [comment]
@TakeshiMasukawa, no problem!  Thanks for all the details you provided.

**Comment by seanmcc-msft** [comment]
We're going to take a different approach, and add a GetRootDirectoryClient() method on the FileSystemClient.

**Comment by seanmcc-msft** [comment]
DataLakeFileSystemClient now has a GetRootDirectoryClient() method, and DataLakeFileClient.GetDirectoryClient("") will also work.
