### ISSUE TITLE
Uploading large streams to Azure Data Lake is too complicated

### ISSUE THREAD

**Issue by Tornhoof** [Azure/azure-sdk-for-net#9492]
**Describe the bug**
The DataLakeFileClient method AppendAsync takes a stream as input, but the upload process aborts after ~100Mb (apparently max blob block size).
It is possible to bypass this by calling AppendAsync multiple times and then flush at the end.
So far so good, but as ``AppendAsync`` closes the stream and this makes kinda complicated too call AppendAsync multiple times. You'd need to provide some kind of wrapper stream which prevents closing and honors the size limit.

***Exception or Stack Trace***
```ini
Azure.RequestFailedException: The request body is too large and exceeds the maximum permissible limit.
RequestId:99fbddf0-301f-0033-47a2-cb81cb000000
Time:2020-01-15T12:53:11.6553729Z
 ---> System.Exception: Exception of type 'System.Exception' was thrown.
   --- End of inner exception stack trace ---
   at Azure.Storage.Files.DataLake.DataLakeRestClient.Path.AppendDataAsync_CreateResponse(Response response)
   at Azure.Storage.Files.DataLake.DataLakeRestClient.Path.AppendDataAsync(ClientDiagnostics clientDiagnostics, HttpPipeline pipeline, Uri resourceUri, Stream body, String version, Nullable`1 position, Nullable`1 timeout, Nullable`1 contentLength, Byte[] transactionalContentHash, String leaseId, String requestId, Boolean async, String operationName, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeFileClient.AppendInternal(Stream content, Nullable`1 offset, Byte[] contentHash, String leaseId, Boolean async, CancellationToken cancellationToken)
   at Azure.Storage.Files.DataLake.DataLakeFileClient.AppendAsync(Stream content, Int64 offset, Byte[] contentHash, String leaseId, CancellationToken cancellationToken)
```

**To Reproduce**
1. Upload files > 100 MB.

***Code Snippet***
```csharp
using System;
using System.IO;
using System.Threading.Tasks;
using Azure.Storage;
using Azure.Storage.Files.DataLake;

namespace TooLargeRepro
{
    class Program
    {
        static async Task Main(string[] args)
        {
            var storageAccountName = "<Account>";

            string storageAccountKey = "<Key>";
            StorageSharedKeyCredential sharedKeyCredential = new StorageSharedKeyCredential(storageAccountName, storageAccountKey);
            // Create DataLakeServiceClient using StorageSharedKeyCredentials
            Uri serviceUri = new Uri("<URL>");
            DataLakeServiceClient serviceClient = new DataLakeServiceClient(serviceUri, sharedKeyCredential);
            // Create a DataLake Filesystem
            DataLakeFileSystemClient filesystem = serviceClient.GetFileSystemClient(Guid.NewGuid().ToString().ToLowerInvariant());
            await filesystem.CreateAsync().ConfigureAwait(false);
            var response = await filesystem.CreateFileAsync("test.dat").ConfigureAwait(false);
            var fileClient = response.Value;
            await using var fs = new MemoryStream();
            byte[] b = new byte[64 * 1024];
            for (int i = 0; i < 2048; i++)
            {
                RandomNumberGenerator.Fill(b);
                fs.Write(b);
            }
            fs.Position = 0;
            var length = fs.Length;
            await fileClient.AppendAsync(fs, 0).ConfigureAwait(false);
            await fileClient.FlushAsync(length).ConfigureAwait(false);
        }
    }
}
```
See example code in 
**Expected behavior**
I can upload large files via streams without the need of handling the block size limitations and everything else myself. 

Fwiw, my (mostly untested) SizeLimitedStream is below
<details>

```csharp

using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace DataLake2PoC
{
    public sealed class SizeLimitStream : Stream
    {
        private readonly Stream _stream;
        private readonly bool _keepOpen;
        private readonly long _start;

        public SizeLimitStream(Stream stream, long sizeLimit, bool keepOpen = true)
        {
            _stream = stream;
            _keepOpen = keepOpen;
            Length = Math.Min(sizeLimit, _stream.Length - _stream.Position);
            _start = _stream.Position;
        }

        public override void Flush()
        {
        }

        public override Task FlushAsync(CancellationToken cancellationToken)
        {
            return Task.CompletedTask;
        }

        public override Task<int> ReadAsync(byte[] buffer, int offset, int count, CancellationToken cancellationToken)
        {
            var actualCount = (int)Math.Min(count, Length - Position);
            return _stream.ReadAsync(buffer, offset, actualCount, cancellationToken);
        }

        public override ValueTask<int> ReadAsync(Memory<byte> buffer, CancellationToken cancellationToken  = default)
        {
            var sliced = buffer.Slice(0, (int) Math.Min(buffer.Length, Length - Position));
            return _stream.ReadAsync(sliced, cancellationToken);
        }

        public override int Read(byte[] buffer, int offset, int count)
        {
            var actualCount = (int) Math.Min(count, Length - Position);
            return _stream.Read(buffer, offset, actualCount);
        }

        /// <summary>
        /// TODO tests
        /// </summary>
        public override long Seek(long offset, SeekOrigin origin)
        {
            switch (origin)
            {
                case SeekOrigin.Begin:
                    return _stream.Seek(_start + offset, SeekOrigin.Begin);
                case SeekOrigin.Current:
                    return _stream.Seek(offset, SeekOrigin.Current) - _start;
                case SeekOrigin.End:
                    return _stream.Seek(offset, SeekOrigin.End) - _start;
                default:
                    throw new ArgumentOutOfRangeException(nameof(origin), origin, null);
            }
        }

        public override void SetLength(long value) => throw new NotSupportedException();

        public override void Write(byte[] buffer, int offset, int count) => throw new NotSupportedException();

        public override bool CanRead => _stream.CanRead;

        public override bool CanSeek => _stream.CanSeek;

        public override bool CanWrite => false;

        public override long Length { get; }

        public override long Position
        {
            get => _stream.Position - _start;
            set => _stream.Position = value + _start;
        }

        public override async ValueTask DisposeAsync()
        {
            if (!_keepOpen)
            {
                await _stream.DisposeAsync().ConfigureAwait(false);
            }

            await base.DisposeAsync().ConfigureAwait(false);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (!_keepOpen)
                {
                    _stream.Dispose();
                }
            }
            base.Dispose(disposing);
        }
    }
}
```
</details>

and you use it like this:

```csharp

await using var fs = File.OpenRead(file);
var length = fs.Length;
const long sizeLimit = 64 * 1024 * 1024;
if (length > 0)
{
    long written = 0;
    do
    {
        await using var slStream = new SizeLimitStream(fs, sizeLimit);
        await fileClient.AppendAsync(slStream, written).ConfigureAwait(false);
        written += slStream.Position;
    } while (written < length);

    await fileClient.FlushAsync(length).ConfigureAwait(false);
}
```

**Screenshots**

**Setup (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
 - IDE : [e.g. IntelliJ] Visual Studio 2019 16.4.
 - Version of the Library used: 12.0 Preview 8

**Additional context**

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [x] Bug Description Added
- [x] Repro Steps Added
- [x] Setup information Added

**Comment by jsquire** [comment]
//cc: @tg-msft, @JoshLove-msft

**Comment by seanmcc-msft** [comment]
Hi @Tornhoof, we're aware of the 100MB limitation, and are working towards rectifying the situation.  We're also exploring adding additional convenience APIs to make file uploads and downloads more straightforward.

Related https://github.com/Azure/azure-sdk-for-net/issues/9413.

**Comment by seanmcc-msft** [comment]
Related https://github.com/Azure/azure-sdk-for-net/issues/9509
