### ISSUE TITLE
[BUG] SDK creates a lot of HttpClient causing connection starvation

### ISSUE THREAD

**Issue by tomkerkhove** [Azure/azure-sdk-for-net#9615]
**Describe the bug**
When using the SDK for long-running processes, we've noticed that it's causing Linux workloads to run out of connections (https://github.com/tomkerkhove/promitor/issues/798).

After digging deeper, we thought we were not using the SDK correctly so we've POCed a refactoring where we only authenticate once and re-use it for the rest of the processing (https://github.com/tomkerkhove/promitor/pull/844).

After digging deeper, [@maartenba found that the SDK is creating a lot of HttpClients ](https://github.com/tomkerkhove/promitor/pull/844#issuecomment-577135547) and not re-using them.

Is this on purpose or is this a bug?

***Exception or Stack Trace***
```
System.Net.Http.HttpRequestException: Too many open files in system ---> System.Net.Sockets.SocketException: Too many open files in system
   at System.Net.Sockets.Socket..ctor(AddressFamily addressFamily, SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.DualSocketMultipleConnectAsync..ctor(SocketType socketType, ProtocolType protocolType)
   at System.Net.Sockets.Socket.ConnectAsync(SocketType socketType, ProtocolType protocolType, SocketAsyncEventArgs e)
   at System.Net.Http.ConnectHelper.ConnectAsync(String host, Int32 port, CancellationToken cancellationToken)
```

**To Reproduce**
- Authenticate client
- Have look how many clients are created

**Expected behavior**
Re-use of one HttpClient rather than 70+

**Setup (please complete the following information):**
 - OS: Linux
 - IDE : Visual Studio
 - Version of the Library used: 1.30.0

**Information Checklist**
Kindly make sure that you have added all the following information above and checkoff the required fields otherwise we will treat the issuer as an incomplete report
- [X] Bug Description Added
- [X] Repro Steps Added
- [X] Setup information Added

**Comment by jsquire** [comment]
//cc: @pakrym, @AlexGhiondea

**Comment by pakrym** [comment]
Considering the screenshot in a linked thread I don't think this is Track 2.

**Comment by tomkerkhove** [comment]
Adding @maartenba who did the analysis

**Comment by AlexGhiondea** [comment]
@tomkerkhove do you have more information about which client library this is referring to?

**Comment by tomkerkhove** [comment]
We're using Azure Monitor Fluent SDK

**Comment by maartenba** [comment]
Profiler snapshots are [here](https://www.dropbox.com/sh/wnr8bxeebxxf8nz/AABH1Tw31ztV0TcsgTEd3GRca). Can be opened with [dotMemory](https://jetbrains.com/dotmemory) & [dotTrace](https://jetbrains.com/dottrace).

**Comment by tomkerkhove** [comment]
Any update on this @AlexGhiondea ?

**Comment by AlexGhiondea** [comment]
@erich-wang could you take a look?

**Comment by tomkerkhove** [comment]
Is there a way we can provide an HttpClient to use?

Or did you manage to make some progress @erich-wang?

**Comment by adam-resdiary** [comment]
@AlexGhiondea just wondering is there any update on this?

**Comment by AlexGhiondea** [comment]
@erich-wang do you have an update here?

**Comment by tomkerkhove** [comment]
Bump @erich-wang

**Comment by erich-wang** [comment]
I'm not owner of mgmt sdk any more, sorry for missing this issue.
Transfter to right repo since it is fluent related issue.
