### ISSUE TITLE
authority' should be in Uri format (Parameter 'authority')

### ISSUE THREAD

**Issue by jaymin93** [Azure/azure-sdk-for-net#9697]
**Describe the bug**

using azure sdk authentication along with the key vault authentication using authenticationContext.AcquireTokenAsync throws 

**Expected behavior**
i am expecting it to be work even though i am using it from the same console app  , although i tried to make in different project but i ran into same issue. 

**Actual behavior (include Exception or Stack Trace)**
What is the actual behavior?

i am getting exception as below 

**authority' should be in Uri format (Parameter 'authority'**
stack trace 

   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.DetectAuthorityType(String authority)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator.Init(IServiceBundle serviceBundle, String authority, Boolean validateAuthority)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.Internal.Instance.Authenticator..ctor(IServiceBundle serviceBundle, String authority, Boolean validateAuthority)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(IServiceBundle serviceBundle, String authority, AuthorityValidationType validateAuthority, TokenCache tokenCache, IHttpClientFactory httpClientFactory)
   at Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext..ctor(String authority, Boolean validateAuthority, TokenCache tokenCache)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.GetAuthenticationContext(String domain, ActiveDirectoryServiceSettings serviceSettings, TokenCache cache)
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.<LoginSilentAsync>d__37.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.<LoginSilentAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Rest.Azure.Authentication.ApplicationTokenProvider.<LoginSilentAsync>d__17.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Authentication.AzureCredentials.<ProcessHttpRequestAsync>d__24.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperations.<GetWithHttpMessagesAsync>d__10.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesOperationsExtensions.<GetAsync>d__5.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.Compute.Fluent.VirtualMachinesImpl.<GetInnerByGroupAsync>d__65.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.<GetByResourceGroupAsync>d__9.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.Extensions.Synchronize[TResult](Func`1 function)
   at Microsoft.Azure.Management.ResourceManager.Fluent.Core.GroupableResources`5.GetByResourceGroup(String groupName, String name)
   at AzureVM.VirtualMachineData.CurrentPowerState() in project.cs:line 76

**To Reproduce**
Steps to reproduce the behavior (include a code snippet, screenshot, or any additional information that might help us reproduce the issue)

see  below code to access the key vault client with authentication , i am getting key from key vault then i need to access other azure resources 

using (var keyClient = new KeyVaultClient(async (authority, resource, scope) =>
            {
                var adCredential = new ClientCredential(keyvaultclientId, keyvaultclientSecret);
                var authenticationContext = new AuthenticationContext(authority, false);
                return (await authenticationContext.AcquireTokenAsync(resource, adCredential)).AccessToken;
            }))

so to use other resource i am using below code

AzureObj = Azure
                            .Configure()
                            .WithLogLevel(HttpLoggingDelegatingHandler.Level.BodyAndHeaders)
                            .Authenticate(InitAzureAppCrdentials(clientId, clientSecret, tenantId))
                            .WithSubscription(Subsciption);

   private AzureCredentials InitAzureAppCrdentials(string ClientId, string ClientSecret, string TenantId){

retrun SdkContext.AzureCredentialsFactory.FromServicePrincipal(ClientId, ClientSecret, TenantId, AzureEnvironment.AzureGlobalCloud);

}

if i do not use key vault client to get key i am able to do operation using azure object but since i am getting key vault client accessing any resource by "getbyresourcegroup"  gives me exception 

**authority' should be in Uri format (Parameter 'authority'**

and i am not able to do  any operation in azure 

**Environment:**
 - Name and version of the Library package used: Microsoft.Azure.KeyVault 3.4 , Microsoft.Azure.Management.Fluent, Microsoft.Azure.Management.ResourceManager.fluent 1.30.0
 - Hosting platform or OS and .NET runtime version windows 10 pro , .net core 3.1 console 
 - IDE and version : Visual Studio 16.4.3

**Comment by heaths** [comment]
Could you clarify where in your sample code the exception is thrown? We also recommend moving away from the fluent APIs since these are not under active development.

In fact, we recommend moving to the new Azure.Security.KeyVault.* packages which support a much simpler authentication model, such as including the Azure.Identity package and just passing `new DefaultAzureCredential()`, which is optimized for cloud-hosted scenarios but easy to use when under development using browser/interactive tokens or service principals.

**Comment by vscodewinodws** [comment]
Could you clarify where in your sample code the exception is thrown? We also recommend moving away from the fluent APIs since these are not under active development.

"after key vault auth part if i access any property ( property of azureobj ) to access virtual machine, web app , etc etc any resource i am getting this error"

in case of switching to another nugget package i will try it out but i think there should be a deprecation or any developer communication about new nuget.

**Comment by heaths** [comment]
The older Microsoft.Azure.* packages are not deprecated, but those for which Azure.* packages exist they are just no longer under active development. The fluent packages haven't been updated in quite a while. But authentication is much easier in Azure.* packages.

Please let us know whether upgrading works or not.
