### ISSUE TITLE
[BUG] azureServiceTokenProvider not working on macOs when the region is set to china

### ISSUE THREAD

**Issue by a4r5twer** [Azure/azure-sdk-for-net#9902]
**Describe the bug**
build keyvaultclient with azureServiceTokenProvider will thow error when you set your region to china in macOs

**Expected behavior**
```
var azureServiceTokenProvider = new AzureServiceTokenProvider();
            var keyVaultClient = new KeyVaultClient(
                           new KeyVaultClient.AuthenticationCallback(
                               azureServiceTokenProvider.KeyVaultTokenCallback));
            ConfigurationBuilder newBuilder = new ConfigurationBuilder();
            newBuilder.AddAzureKeyVault(keyVaultUrl, keyVaultClient, new DefaultKeyVaultSecretManager());
            var root = newBuilder.Build();
```
this code get run successfully 
**Actual behavior (include Exception or Stack Trace)**
```
Parameters: Connection String: [No connection string specified], Resource: https://vault.azure.net, Authority: https://login.windows.net/72f988bf-86f1-41af-91ab-2d7cd011db47. Exception Message: Tried to get token using Azure CLI. Access token could not be acquired. Fatal Python error: config_get_locale_encoding: failed to get the locale encoding: nl_langinfo(CODESET) failed
Python runtime state: preinitialized


   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.GetAuthResultAsyncImpl(String resource, String authority, CancellationToken cancellationToken)
   at Microsoft.Azure.Services.AppAuthentication.AzureServiceTokenProvider.<get_KeyVaultTokenCallback>b__8_0(String authority, String resource, String scope)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.PostAuthenticate(HttpResponseMessage response)
   at Microsoft.Azure.KeyVault.KeyVaultCredential.ProcessHttpRequestAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClient.GetSecretsWithHttpMessagesAsync(String vaultBaseUrl, Nullable`1 maxresults, Dictionary`2 customHeaders, CancellationToken cancellationToken)
   at Microsoft.Azure.KeyVault.KeyVaultClientExtensions.GetSecretsAsync(IKeyVaultClient operations, String vaultBaseUrl, Nullable`1 maxresults, CancellationToken cancellationToken)
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.LoadAsync()
   at Microsoft.Extensions.Configuration.AzureKeyVault.AzureKeyVaultConfigurationProvider.Load()
   at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`1 providers)
   at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
```

**To Reproduce**

Set macOs region to china ,after i set the region to United states everything works fine 

**Environment:**
Microsoft.Azure.KeyVault  3.0.4

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.14
 OS Platform: Darwin
 RID:         osx.10.14-x64
.netCore 3.0

Visual Studio Enterprise 2019 for Mac
Version 8.4.4 (build 91)

**Comment by tg-msft** [comment]
//fyi @heaths

**Comment by heaths** [comment]
The azure CLI is failing to load:
```
Fatal Python error: config_get_locale_encoding: failed to get the locale encoding: nl_langinfo(CODESET) failed
```
@iscai-msft or @chlowell any thoughts to fix this?

@a4r5twer do you get a similar issue when you use the azure CLI (e.g. `az keyvault key list (args)`) with your region set to China?

**Comment by chlowell** [comment]
Could be Azure/azure-cli#11849

**Comment by a4r5twer** [comment]
> az keyvault key list
@heaths
![image](https://user-images.githubusercontent.com/37093759/74537964-14af7600-4f76-11ea-8194-8e71cc02ca1b.png)
hi heaths after setting my location to china i can get the keyvault list 
and i can download it to local by az keyvault secret download --file command as a txt

**Comment by heaths** [comment]
How exactly are you setting your locale to China? If setting `LANG` to something like `LANG=zh-CN` could you try `LANG=zh-CN.UTF-8`?

**Comment by heaths** [comment]
Also, try `az login` (run `az logout` first if you're already logged in). It's possible that enumerating keys in Key Vault doesn't run through the same code path.

**Comment by heaths** [comment]
Closing with no customer response. If you still require help, please provide the information requested and we can reopen the bug for further troubleshooting.
