### ISSUE TITLE
[Flaky test] Should_retry_when_throttled_and_no_ambient_transaction_is_detected

### ISSUE THREAD

**Issue by pakrym** [Azure/azure-sdk-for-net#9957]
Error message
```
Microsoft.Azure.ServiceBus.ServerBusyException : Rico KABOOM!
```

Stack trace
```
   at Microsoft.Azure.ServiceBus.UnitTests.RetryPolicyTests.<>c__DisplayClass0_0.<Should_retry_when_throttled_and_no_ambient_transaction_is_detected>b__0() in D:\a\1\s\sdk\servicebus\Microsoft.Azure.ServiceBus\tests\RetryPolicyTests.cs:line 28
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout) in D:\a\1\s\sdk\servicebus\Microsoft.Azure.ServiceBus\src\RetryPolicy.cs:line 82
   at Microsoft.Azure.ServiceBus.RetryPolicy.RunOperation(Func`1 operation, TimeSpan operationTimeout) in D:\a\1\s\sdk\servicebus\Microsoft.Azure.ServiceBus\src\RetryPolicy.cs:line 107
   at Microsoft.Azure.ServiceBus.UnitTests.RetryPolicyTests.Should_retry_when_throttled_and_no_ambient_transaction_is_detected() in D:\a\1\s\sdk\servicebus\Microsoft.Azure.ServiceBus\tests\RetryPolicyTests.cs:line 18
--- End of stack trace from previous location where exception was thrown ---
```

**Comment by JoshLove-msft** [comment]
Closing out as this is now being tracked separately.
