### ISSUE TITLE
AvroSerializer not support Dictionary with object as value type with KnownType, typical scenario for OData Patch

### ISSUE THREAD

**Issue by chuanboz** [Azure/azure-sdk-for-net#996]
take below code as an example, the scenario here is very typical for OData Patch, where client side needs to send multiple properties of the entity to server side, so it model it as a dictionary of string to object, where the type of object is known since that's the property type of the entity.

however when trying to serialize/deserialize it via Avro, it will fail

```C#
    [DataContract]
    [KnownType(typeof(int))]
    [KnownType(typeof(string))]
    [KnownType(typeof(ClassOfInt))]
    public class ClassOfObjectDictionary : IEquatable<ClassOfObjectDictionary>
    {
        [DataMember]
        internal Dictionary<string, object> PatchSet;

        public override bool Equals(object obj)
        {
            return this.Equals(obj as ClassOfObjectDictionary);
        }

        public bool Equals(ClassOfObjectDictionary other)
        {
            if (other == null)
            {
                return false;
            }

            return (this.PatchSet == null && other.PatchSet == null) ||
                (this.PatchSet != null && this.PatchSet.SequenceEqual(other.PatchSet));
        }

        public override int GetHashCode()
        {
            return this.PatchSet.GetHashCode();
        }

        public static ClassOfObjectDictionary Create()
        {
            var data = NestedClass.Create(false);
            return new ClassOfObjectDictionary
            {
                PatchSet = new Dictionary<string, object>()
                {
                     {"Name", "OData"},
                     {"Age", 15},
                     {"ClassOfIntReference", data.ClassOfIntReference}
                },
            };
        }
    }
```
here is the Unit Test to repro the issue
```C#
[TestMethod]
        [TestCategory("CheckIn")]
        public void Serializer_ClassOfObjectDictionary()
        {
            var serializer = AvroSerializer.Create<ClassOfObjectDictionary>();
            var deserializer = AvroSerializer.CreateDeserializerOnly<ClassOfObjectDictionary>(serializer.WriterSchema.ToString(), new AvroSerializerSettings());

            var expected = ClassOfObjectDictionary.Create();
            RoundTripSerializationWithCheck(serializer, deserializer, expected);
        }
```

**Comment by chuanboz** [comment]
this is the very first exception message, even get over this one by using custom resolver, there are still multiple different errors to prevent this work from end to end.
```
Test Name:	Serializer_ClassOfObjectDictionary
Test FullName:	Microsoft.Hadoop.Avro.Tests.AvroSerializerTests.Serializer_ClassOfObjectDictionary
Test Source:	d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro.Tests\AvroSerializerTests.cs : line 1485
Test Outcome:	Failed
Test Duration:	0:00:00.0275901

Result Message:	
Test method Microsoft.Hadoop.Avro.Tests.AvroSerializerTests.Serializer_ClassOfObjectDictionary threw exception: 
System.Runtime.Serialization.SerializationException: Type 'System.Object' is not supported by the resolver.
Result StackTrace:	
at Microsoft.Hadoop.Avro.AvroDataContractResolver.ResolveType(Type type) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Resolvers\AvroDataContractResolver.cs:line 98
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.CreateSchema(Boolean forceNullable, Type type, Dictionary`2 schemas, UInt32 currentDepth) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 117
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.BuildComplexTypeSchema(Type type, Dictionary`2 schemas, UInt32 currentDepth) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 220
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.CreateNotNullableSchema(Type type, Dictionary`2 schemas, UInt32 currentDepth) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 170
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.CreateSchema(Boolean forceNullable, Type type, Dictionary`2 schemas, UInt32 currentDepth) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 124
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.AddRecordFields(IEnumerable`1 members, Dictionary`2 schemas, UInt32 currentDepth, RecordSchema record) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 453
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.BuildRecordTypeSchema(Type type, Dictionary`2 schemas, UInt32 currentDepth) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 350
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.BuildComplexTypeSchema(Type type, Dictionary`2 schemas, UInt32 currentDepth) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 249
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.CreateNotNullableSchema(Type type, Dictionary`2 schemas, UInt32 currentDepth) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 170
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.CreateSchema(Boolean forceNullable, Type type, Dictionary`2 schemas, UInt32 currentDepth) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 124
   at Microsoft.Hadoop.Avro.Schema.ReflectionSchemaBuilder.BuildSchema(Type type) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\Schema\ReflectionSchemaBuilder.cs:line 87
   at Microsoft.Hadoop.Avro.AvroSerializer.CreateForCore[T](String writerSchema, AvroSerializerSettings settings) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\AvroSerializer.Static.cs:line 156
   at Microsoft.Hadoop.Avro.AvroSerializer.Create[T](AvroSerializerSettings settings) in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\AvroSerializer.Static.cs:line 69
   at Microsoft.Hadoop.Avro.AvroSerializer.Create[T]() in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro\AvroSerializer.Static.cs:line 48
   at Microsoft.Hadoop.Avro.Tests.AvroSerializerTests.Serializer_ClassOfObjectDictionary() in d:\GitHub\Avro\src\HDInsight\Microsoft.Hadoop.Avro.Tests\AvroSerializerTests.cs:line 1486
```

**Comment by markcowl** [comment]
@chuanboz Thank you for the feedback, assigning to the appropriate feature team

**Comment by shixiaoyu** [comment]
Hi Mark, 
Do you have an ETA roughly when this change will be released?

**Comment by chuanboz** [comment]
@djoelz, added pull request for the proposal fix of this issue, please help take a look.
https://github.com/hdinsight/azure-sdk-for-net/pull/75

**Comment by chuanboz** [comment]
close the issue as fix being incorporated

**Comment by Epstone** [comment]
@djoelz, @chuanboz
In which library release should this fix be included? The pull request link above is broken. 
I'm seeing this with version 1.5.6  from here https://www.nuget.org/packages/Microsoft.Hadoop.Avro/

**Comment by chuanboz** [comment]
@Epstone, we're using version 1.5.6 and that is working for me.
if you're still seeing it repro, maybe you shall report an issue with specific repro steps.

**Comment by tpsands** [comment]
I am seeing this issue still. Version 1.5.6 from NuGet. Class to be serialized was generated by the tool in the Tools project:
`   [DataContract(Namespace = "mynamespace")]
    [KnownType(typeof(Dictionary<string, object>))]
    public partial class Measurement
    {
        private const string JsonSchema = @"{""type"":""record"",""name"":""mynamespace"",""fields"":[{""name"":""DeviceID"",""type"":""string""},{""name"":""SW"",""type"":""string""},{""name"":""MeasurementTime"",""type"":""double""},{""name"":""Measures"",""type"":{""type"":""map"",""values"":[""string"",""int"",""long"",""double"",""boolean"",""float""]}}]}";

        public static string Schema
        {
            get
            {
                return JsonSchema;
            }
        }

        [DataMember]
        public string DeviceID { get; set; }

        [DataMember]
        public string SW { get; set; }

        [DataMember]
        public double MeasurementTime { get; set; }

        [DataMember]
        public IDictionary<string, object> Measures { get; set; }
}
`

I have omitted the constructor. The code that then uses this and gives the exception is:
`          
//here is where the exception is thrown.  
var avroEventSerializer = Microsoft.Hadoop.Avro.AvroSerializer.Create<Measurement>();
.
.
.

`

The specific exception is: "Type 'System.Object' is not supported by the resolver."

**Comment by Epstone** [comment]
I can just suggest you a workaround for the problem. Maybe it helps even with the disadvantages created. 
`  {
  "namespace": "some.namespace",
  "type": "record",
  "name": "Measures",
  "fields": [
      {"name": "IntegerMeasures", "type" : ["null", {"type": "map", "values": "int"}]},
      {"name": "BooleanMeasures", "type" : ["null", {"type": "map", "values": "boolean"}]},
      {"name": "DoubleMeasures", "type" :  ["null", {"type": "map", "values": "double"}]}]
  }`
