### ISSUE TITLE
MergeCertificateAsync does not serialize request body

### ISSUE THREAD

**Issue by twsouthwick** [Azure/azure-sdk-for-net#9986]
**Describe the bug**
When trying to call `MergeCertificateAsync` an exception is thrown.

**Expected behavior**
That the API is called with no error.

**Actual behavior (include Exception or Stack Trace)**
```
Azure.RequestFailedException: Service request failed.
Status: 400 (Bad Request)

Content:
{"error":{"code":"BadParameter","message":"Request body not specified"}}

Headers:
Cache-Control: no-cache
Pragma: no-cache
Server: Microsoft-IIS/10.0
x-ms-keyvault-region: eastasia
x-ms-request-id: dc7f7126-a161-4911-9094-957355609fa9
x-ms-keyvault-service-version: 1.1.0.893
x-ms-keyvault-network-info: addr=131.107.159.246;act_addr_fam=InterNetwork;
X-AspNet-Version: 4.0.30319
X-Powered-By: ASP.NET
Strict-Transport-Security: max-age=31536000;includeSubDomains
X-Content-Type-Options: nosniff
Date: Fri, 14 Feb 2020 19:58:04 GMT
Content-Length: 72
Content-Type: application/json; charset=utf-8
Expires: -1

   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync(Request request, CancellationToken cancellationToken)
   at Azure.Security.KeyVault.KeyVaultPipeline.SendRequestAsync[TResult](RequestMethod method, Func`1 resultFactory, CancellationToken cancellationToken, String[] path)
   at Azure.Security.KeyVault.Certificates.CertificateClient.MergeCertificateAsync(MergeCertificateOptions mergeCertificateOptions, CancellationToken cancellationToken)
   at McMaster.AspNetCore.LetsEncrypt.AzureKeyVaultCertificateRepository.SaveAsync(X509Certificate2 certificate, CancellationToken cancellationToken) in C:\Users\tasou\Projects\Software\LetsEncrypt\src\LetsEncrypt.Azure\AzureKeyVaultCertificateRepository.cs:line 103
```

**To Reproduce**

```csharp
public async Task SaveAsync(X509Certificate2 certificate, CancellationToken cancellationToken)
{
    var domainName = certificate.GetNameInfo(X509NameType.DnsName, false);

    _logger.LogInformation("Saving certificate for {Domain} in Azure KeyVault.", domainName);

    if (!(await ShouldImportVersionAsync(domainName, certificate, cancellationToken)))
    {
        _logger.LogInformation("Certificate for {Domain} is already up-to-date in Azure KeyVault. Skipping importing.", domainName);
        return;
    }

    var exported = certificate.Export(X509ContentType.Pfx);

    var options = new MergeCertificateOptions(NormalizeHostName(domainName),new[] { exported });

    try
    {
        await _client.MergeCertificateAsync(options, cancellationToken);

        _logger.LogInformation("Imported certificate into Azure KeyVault for {Domain}", domainName);
    }
    catch (RequestFailedException ex)
    {
        _logger.LogWarning(ex, "Failed to save {Domain} certificate to Azure KeyVault", domainName);
    }
}
```

**Environment:**
 - Name and version of the Library package used: Azure.Security.KeyVault.Certificates v4.0.0
 - Hosting platform or OS and .NET runtime version (`dotnet --info` output for .NET Core projects):
```
$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   3.1.101
 Commit:    b377529961

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.18363
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\3.1.101\

Host (useful for support):
  Version: 3.1.1
  Commit:  a1388f194c

.NET Core SDKs installed:
  2.2.103 [C:\Program Files\dotnet\sdk]
  3.1.101 [C:\Program Files\dotnet\sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.All 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.1.15 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.NETCore.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
  Microsoft.WindowsDesktop.App 3.1.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```
 - IDE and version : Visual Studio 16.4.4

**Comment by twsouthwick** [comment]
@heaths I found this while exploring #9963, but is different in that 

https://github.com/Azure/azure-sdk-for-net/blob/0eb893cfda1a9b39801d414ec77ce753eec43868/sdk/keyvault/Azure.Security.KeyVault.Certificates/src/CertificateClient.cs#L1443

does not pass through the options. It appears that the sync version has the same issue.
